/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Otsikko on pakollinen",
	nourl: "URL-osoite on pakollinen.",
	fileSchema: "Jos haluat lisätä etätiedoston tai paikallisen tiedoston linkin, sen tulee noudattaa jompaakumpaa muotoa: file://etäpolku tai file:///paikallinen_polku.",
	invalidUrl: "Tämä ei ole kelvollinen yhteisön URL-osoite.",
	invalidTagChar: "Annettu tunnisteluettelo sisältää virheellisen merkin &. Poista tämä merkki tunnisteluettelosta.",
	txtHelp: "Ohje",
	txtHelpTags: "Tunnisteohje",
	txtHelpTagsClose: "Sulje tunnisteiden ohje",
	tagsall: "Kaikki",
	tagsyours: "Omat",
	tagsrecent: "Viimeisimmät: ",
	tagspopular: "Suositut: ",
	tagsrecommended: "Suositellut: ",
	nothingselected: "Yhteisön valinta on pakollinen.",
	nothingselected_activity: "Aktiviteetin valinta on pakollinen.",
	nothingselected_blogs: "Verkkolokin valinta on pakollinen.",
	nothingselected_all: "Palvelua tai merkintää ei ole valittu. Kirjanmerkki ei tallennu.",
	nothingFeedselected: "Palvelua tai merkintää ei ole valittu. Syöte ei tallennu.",
	alertDialogTitle: "Viesti",
	alertDialogOK: "OK",
	expand: "Laajenna tämä osa napsauttamalla",
	collapse: "Pienennä tämä osa napsauttamalla",
	discussThis: "Keskustele tästä aiheesta",
	by: "Tekijä:",
	posted: "Lisätty:",
	attachments: "Liitteet",
	communityForum: "Yhteisön keskusteluryhmä",
	notCommunityPage: "Nykyinen Web-sivu ei ole kelvollinen yhteisön Web-sivu. Voit luoda liittyvän yhteisön syöttämällä yhteisön otsikon, linkin ja kuvauksen manuaalisesti.",
	privateCommunityNotice: "Tämä on rajoitettu yhteisö. Se on vain jäsentensä nähtävissä.",
	forumNameHint : "Kirjoita keskusteluryhmän nimi",
	formDescriptionHint:"Kerro, miksi tämä aiheeseen liittyvä yhteisö voisi kiinnostaa omaa yhteisöäsi.",
	information : "Ilmoitus",
	error : "Virhe",
	success : "Onnistuminen",
	warning : "Varoitus",
	informationColon : "Tiedot:",
	successColon : "Onnistui:",
	warningColon : "Varoitus:",
	errorColon : "Virhe:",
	feedAlreadyExist : "Syöte on jo lisätty yhteisöön.",
	bookmarkAlreadyExist : "Kirjanmerkki on jo lisätty yhteisöön.",
	mentionAuthWarning:"Seuraavat mainitut henkilöt eivät voi tarkastella viestiä, koska he eivät ole yhteisön jäseniä:",
	mentionAuthForumWarning:"Seuraavat mainitut henkilöt eivät voi tarkastella viestiä, koska heillä ei ole tämän keskusteluryhmän käyttöoikeutta:",
	exceedDescLength: "Kirjoittamasi kuvaus on liian pitkä.",
	communities_checked:"${0} yhteisöä valittu",
	activities_checked:"${0} aktiviteettia valittu",
	blogs_checked:"${0} verkkolokia valittu"
})
