/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknutím sem zobrazíte vizitku.",
	"label.semtag.hover.alt" : "Kliknutím sem zobrazíte vizitku pro {0}.",
	"label.semtag.hover.altA11Y" : "Kliknutím sem nebo stisknutím Ctrl-Enter zobrazíte vizitku.",
	"label.personcard.dialog.title" : "Vizitka pro {0}",

	"errorDefaultMsg2" : "Došlo k chybě, kontaktujte administrátora systému.",

	"loadingSTStatus" : "Načítání stavu produktu Sametime...",
	"noStatuAvailable" : "K dispozici není žádný stav produktu Sametime.",

	"label.personcard.cardnomarkup" : "Vizitku nelze načíst.",
	"label.inactive.user.msg" : "Tato osoba již není aktivním uživatelem.",
	"label.message.information" : "Informace:",
	"label.personcard.noprofilemsg" : "Profil pro tuto osobu neexistuje.",
	"label.personcard.cardreqexpired" : "Časový limit požadavku na získání vizitky vypršel.",

	"label.bizcard.applinks.less" : "Zobrazit méně",
	"label.bizcard.applinks.more" : "Zobrazit více",

	"label.personcard.activitieslink" : "Aktivity",
	"label.personcard.activitieslink.title" : "Klepnutím na tento odkaz zobrazíte sdílené aktivity.",
	"label.personcard.blogslink" : "Blogy",
	"label.personcard.blogslink.title" : "Klepnutím sem zobrazíte blog této osoby.",
	"label.personcard.communitieslink" : "Komunity",
	"label.personcard.communitieslink.title" : "Klepnutím sem zobrazíte komunity této osoby.",
	"label.personcard.dogearlink" : "Záložky",
	"label.personcard.dogearlink.title" : "Klepnutím sem zobrazíte záložky této osoby.",
	"label.personcard.fileslink" : "Soubory",
	"label.personcard.fileslink.title" : "Klepnutím sem zobrazíte sdílené soubory této osoby.",
	"label.personcard.forumlink" : "Fóra",
	"label.personcard.forumlink.title" : "Klepnutím sem zobrazíte příspěvky této osoby do fóra.",
	"label.personcard.homepagelink" : "Domovská stránka",
	"label.personcard.homepagelink.title" : "Klepnutím sem zobrazíte domovskou stránku této osoby.",
	"label.personcard.mobilelink" : "Mobilní přístup",
	"label.personcard.mobilelink.title" : "Klepnutím sem zobrazíte mobilní stránku této osoby.",
	"label.personcard.newslink" : "Novinky",
	"label.personcard.newslink.title" : "Klepnutím sem zobrazíte novinky této osoby.",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klepnutím sem zobrazíte profil této osoby.",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klepnutím sem zobrazíte sdílené položky této osoby v produktu Quickr.",
	"label.personcard.wikislink" : "Wikiweby",
	"label.personcard.wikislink.title" : "Klepnutím sem zobrazíte wikiweby této osoby.",

	"personCardMoreActions" : "Další akce",
	"personCardMoreActionsAltText" : "Klepnutím sem zobrazíte nabídku akcí.",

	"label.bizcard.dismiss": "Vizitku lze odmítnout stisknutím klávesy Esc.",
	"label.bizcard.fullProfile": "Celý profil",
	"label.bizcard.activities": "Aktivity",
	"label.bizcard.communities": "Komunity",
	"label.bizcard.files": "Soubory",
	"label.bizcard.forums": "Fóra",
	"label.bizcard.bookmarks": "Záložky",
	"label.bizcard.blogs": "Blogy",
	"label.bizcard.wikis": "Wikiweby",

	"personCardAddAsColleagues" : "Pozvat do mé sítě",
	"personCardAddAsMyColleagues" : "Pozvat do mé sítě",
	"personCardFollow" : "Sledovat",
	"personCardUnfollow" : "Ukončit sledování",
	"personCardChat" : "Konverzace",
	"personCardCall" : "Hovor",
	"personCardSendMail" : "Odeslat e-mail",
	"personCardSendEMail" : "Odeslat e-mail",
	"personCardProxyStatusAvailable" : "Jsem k dispozici",
	"personCardDownloadVCard" : "Stáhnout vizitku vCard",

	"friends" : "Síť",
	"friendsFullPageTitle" : "Síť",
	"friendsMenuTitleAllContacts" : "Všechny kontakty v síti",
	"friendsMenuTitleMyContacts" : "Mé kontakty v síti",
	"friendsInvitations" : "Pozvánky",
	"friendsMenuTitleInCommon" : "Společné osoby",
	"friendsShowAllCommonFriends" : "Zobrazit vše...",
	"friendsViewAllFriends" : "Zobrazit vše ({0})",
	"friendsSendFriendRequest" : "Zaslat požadavek",
	"friendsNoFriends" : "K tomuto profilu nejsou přidruženy žádné kontakty v síti.",
	"friendsColleaguesInvite" : "Pozvat uživatele {0}, aby se stal vaším kontaktem",
	"friendsColleaguesFor" : "Kontakty v síti pro uživatele {0}",
	"friendsNewInv" : "{0} nová pozvánka",
	"friendsNewInvs" : "{0} nových pozvánek",
	"friendsLoading" : "Načítání sítě...",
	"friendsLoadingInv" : "Nahrávání pozvánek...",
	"friendsSelectFriendForRemoval" : "Zvolte kontakty, které chcete odstranit jako první.",
	"friendsRemoved" : "Kontakty v síti byly odebrány.",
	"friendsInvSent" : "Nebyla odeslána žádná pozvánka, protože již existuje nevyřízená pozvánka.",
	"friendsRemovedSelected" : "Odebrat z mé sítě",
	"friendsSortByDisplayName" : "Zobrazované jméno",
	"friendsSortByRecent" : "Nedávné",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "Alternativní e-mail:",
	"friendsNewInvitationsCount" : "Obdrželi jste {0} nových pozvánek.",
	"friendsNoInv" : "Žádné pozvánky",
	"friendsInCommonSingle" : "Celkem máte {0} společný kontakt v síti.",
	"friendsInCommonMulti" : "Celkem máte {0} společných kontaktů v síti.",
	"friendsIncludeMsgForInv" : "Uvést v pozvánce zprávu:",
	"friendsInitialMsgForInv" : "Chci se zeptat, zda vás mohu přidat do svého seznamu kontaktů v síti produktu Connections.",
	"friendsSendInvAction" : "Odeslat pozvánku",
	"friendsCancelInvAction" : "Storno",
	"friendsAcceptAction" : "Přijmout",
	"friendsIgnoreAction" : "Ignorovat",
	"friendsYouExceedTextLimit" : "Vaše zpráva s pozvánkou je příliš dlouhá. Maximální délka je {1} znaků. Toto pole obsahuje {0} znaků.",
	"friendsCannotAddYourself" : "Jako kontakt v síti nemůžete přidat sami sebe.",
	"friendsIsYourColleague" : "Uživatel {0} je kontaktem ve vaší síti.",
	"friendsRecentlyAdded" : "Lidé, které jste v poslední době přidali do své sítě.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Klepnutím sem síťovou sekci sbalíte.",
	"friendsExpandWidget" : "Klepnutím sem síťovou sekci rozbalíte.",
	"friendsIsInYourNetwork" : "{0} je ve vaší síti.",
	"friendsActionsFor" : "Akce pro modul widget Síť",
	"friendsInviteFollowError" : "Při pokusu o sledování {0} došlo k chybě.",
	"friendsInviteTagError" : "Při pokusu o vytvoření přístup ke značce {0} došlo k chybě.",
	"friendsPleaseLogIn" : "Chcete-li pozvat ostatní uživatele do své sítě, je nutné se přihlásit.",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Pozvání k připojení do vaší sítě nelze odeslat, protože uživatel {0} je již k vaší síti přihlášen.",
	"friendsInviteAddTagsFor" : "Přidat značky pro {0}:",
	"friendsInviteAlsoFollow" : "Zároveň sledovat",
	"friendsInviteReceiveUpdates" : "(příjem aktualizací)",
	"friendsInviteUpdatesDescription" : "Aktualizace informací o sledovaných lidech můžete přijímat prostřednictvím domovské stránky a e-mailového souhrnu.",
	"friendsInviteFollowHelp": "Další informace naleznete v tématu {0}Sledování osob{1}.",
	"friendsNetwork" : "Síť",
	"friendsMyNetwork" : "Síť",
	"friendsNetworkFor" : "Síť pro uživatele {0}",
	"friendsRemoveSelected" : "Odebrat vybrané",
	"friendsRemoveSelectedTip" : "Klepnutím odeberete vybrané lidi ze své sítě.",
	"friendsNetworkInCommon" : "Celkem máte {0} společných síťových připojení.",
	"friendsAddToMyNetwork" : "Rád/a bych si vás přidal/a do své sítě Connections.",
	"friendsInvite" : "Pozvat do mé sítě",
	"friendsInvitePerson" : "Pozvat uživatele {0} do své sítě",
	"friendsInviteMessage" : "Rád/a bych si vás přidal/a do své sítě Connections.",
	"friendsInvitedEmailSubject" : "[Profily] Jste zváni k připojení do mé sítě.",
	"friendsInvitedEmailMsg1" : "vás pozval/a jako kontakt do své sítě a součástí pozvání byla následující zpráva:",
	"friendsInvitedEmailMsg2" : "Otevřít stránku s pozváním do sítě",
	"friendsInvitedEmailMsg3" : "Rád/a bych vás přidal do své sítě.",
	"friendsInvitedEmailMsg4" : "Uživatel {0} vás pozval, abyste se stali síťovým kontaktem:",
	"friendsInvitedEmailMsg5" : "Uživatel {0} vás pozval jako kontakt do své sítě a součástí pozvání byla následující zpráva:",
	"friendsInviteLegalNote" : "Odesláním tohoto pozvání souhlasíte s povolením přidávání komentářů na nástěnku ve vašem profilu pro uživatele {0}.",
	"friendsInviteFailed" : "V důsledku chyby serveru nebylo pozvanému uživateli zasláno e-mailové oznámení. Přesto však pozvaný uživatel bude moci přijmout vaše pozvání prostřednictvím webové aplikace služby Profily.",
	"personInNetwork" : "Síťový kontakt"
})
