/* Copyright IBM Corp. 2008, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Potreban je naslov.",
	nourl: "Potreban je URL.",
	invalidUrl: "Ovo nije ispravan URL zajednice.",
	txtHelp: "Pomoć",
	txtHelpTags: "Pomoć za oznake",
	txtHelpTagsClose: "Zatvori pomoć za oznake",
	tagsall: "Sve",
	tagsyours: "Vaši",
	tagsrecent: "Nedavne: ",
	tagspopular: "Popularne: ",
	tagsrecommended: "Preporučene: ",
	nothingselected: "Potreban je izbor zajednice.",
	nothingselected_activity: "Potreban je izbor aktivnosti.",
	nothingselected_blogs: "Potreban je izbor bloga.",
	nothingselected_all: "Nije izabrana usluga ili unos, bukmark nebit će spremljen.",
	nothingFeedselected: "Nije izabrana usluga ili unos, tekuće informacije nebit će spremljene.",
	alertDialogTitle: "Poruka",
	alertDialogOK: "OK",
	expand: "Kliknite za proširiti ovu sekciju",
	collapse: "Kliknite za skupiti ovu sekciju",
	discussThis: "Raspravite ovo",
	by: "od:",
	posted: "Objavio:",
	attachments: "Prilozi",
	communityForum: "Forum zajednice",
	notCommunityPage: "Trenutna Web stranica nije važeća Web stranica zajednice. Ručno možete unijeti naslov zajednice te vezu i opis za kreiranje odgovarajuće zajednice.",
	privateCommunityNotice: "Ova zajednica ima ograničenja. Vidljiva je samo članovima zajednice.",
	forumNameHint : "Upišite ime foruma",
	formDescriptionHint:"Opišite zašta bi ova povezana zajednica mogla biti interesantna vašoj zajednici.",
	information : "Informacije",
	error : "Greška",
	success : "Uspjeh",
	warning : "Upozorenje",
	informationColon : "Informacije:",
	successColon : "Uspjeh:",
	warningColon : "Upozorenje:",
	errorColon : "Greška:",
	feedAlreadyExist : "U zajednici već postoje tekuće informacije.",
	bookmarkAlreadyExist : "U zajednici već postoji bukmark.",
	mentionAuthWarning:"Sljedeće osobe neće moći pogledati poruku jer nisu članovi zajednice:",
	mentionAuthForumWarning:"Sljedeće osobe neće moći pogledati poruku jer ne mogu pristupiti ovom forumu:",
	exceedDescLength: "Opis koji ste unijeli je predug.",
	communities_checked:"${0} zajednica je odabrano",
	activities_checked:"${0} zajednica je odabrano",
	blogs_checked:"${0} blogova odabrano"
})

