/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtriraj po:",
"SHOW":"Prikaži:",
"ACL_FILTER_LABEL":"Filtriraj po vidljivosti",
"PARENT_FILTER_LABEL":"Filtriraj po kontejneru",
"TYPE_FILTER_LABEL":"Filtriraj po tipu",
"PAGING_TOP":"Primarno straničenje",
"PAGING_BOTTOM":"Sekundarno straničenje",
"PREVIOUS":"Prethodno",
"NEXT":"Sledeće",
"PAGE":"Stranica {0} od {1}",
"PAGE_COLON":"Stranica:",
"RESULTS":"{span}{0}-{1}{/span} od {2}",
"ITEMS":"{0} stavke",
/* Application names */
"ACTIVITIES":"Aktivnosti",
"BLOGS":"Blogovi",
"CALENDAR":"Kalendar",
"COMMUNITIES":"Zajednice",
"BOOKMARKS":"Obeleživači",
"DOGEAR":"Obeleživači",
"EVENTS":"Događaji",
"FILES":"Datoteke",
"FORUMS":"Forumi",
"PROFILES":"Profili",
"WIKI":"Vikiji",
"WIKIS":"Vikiji",
"FEEDS":"Fidovi",
"STATUS_UPDATES":"Ažuriranja statusa",
"ONECOMMENT":"1 komentar",
"COMMENTS":"{0} komentara",
"ONEPERSON":"1 osoba",
"PEOPLE":"{0} ljudi",
"TAGS":"Oznake:",
"TAGSMORE":"i {0} više",
"NORESULTSMESSAGE":"Nisu pronađeni rezultati za tu pretragu",
"JAN":"Januar",
"FEB":"Februar",
"MAR":"Mart",
"APR":"April",
"MAY":"Maj",
"JUN":"Jun",
"JUL":"Jul",
"AUG":"Avgust",
"SEP":"Septembar",
"OCT":"Oktobar",
"NOV":"Novembar",
"DEC":"Decembar",
"NO_CONTACT":"Pretraga nije obavljena jer nije bilo moguće kontaktirati server",
"SERVER_ERROR":"Pretraživanje nije izvršeno zbog greške na serveru",
"SORT_BY":"Sortiraj prema:",
"SORT_RELEVANCE":"Relevantnost",
"SORT_DATE":"Datum",
"SORT_LAST_UPDATED":"Poslednje ažuriranje",
"SORT_DUE_DATE":"Rok",
"SORT_VISITS":"Posete",
"SORT_COMMENTS":"Komentari",
"SORT_RECOMMENDATION":"Označeno sa Sviđa mi se",
"SORT_POPULARITY":"Popularnost",
"SORT_FIRSTNAME":"Ime",
"SORT_LASTNAME":"Prezime",
"SORT_DOWNLOADS":"Preuzimanja",
"SORT_TYPE":"Tip",
"SORT_SIZE":"Veličina",
"SORT_TITLE":"Naslov",
"PRIVATE":"Privatno",
"MODERATED":"Uređeno",
"COMMUNITY_ACTIVITY":"Aktivnost zajednice",
"COMMUNITY_BLOG":"Blog zajednice",
"COMMUNITY_FILE":"Datoteka zajednice",
"COMMUNITY_FORUM":"Forum zajednice",
"COMMUNITY_WIKI":"Viki zajednice",
"COMMUNITY_FEED":"Fid zajednice",
"COMMUNITY_BOOKMARK":"Obeleživač zajednice",
"NO_TAG":"Još nema oznaka",
"NO_DATE":"Još nema datuma",
"NO_PEOPLE":"Još nema osoba",
"REMOVE_FILTER_LABEL":"Kliknite da biste uklonili",
"REMOVE_FILTER_TITLE":"Ukloni",
"REMOVE_FILTER_TOOLTIP":"Ukloni filter",
"COMMENT_ON":"Komentar na:",
"EXPAND_COLLAPSE":"Kliknite da biste proširili / skupili",
"EXPAND":"Proširi",
"COLLAPSE":"Skupi",
"EXPAND_MONTHS_FILTER":"Proširi filter meseca za godinu {0}",
"SORT_RELEVANCE_LABEL":"Kliknite da biste sortirali po važnosti",
"SORT_DATE_LABEL":"Kliknite da biste sortirali po datumu",
"SORT_UPDATED_LABEL":"Kliknite da biste sortirali po poslednjem ažuriranju",
"SORT_DUE_LABEL":"Kliknite da biste sortirali po datumu roka",
"SORT_VISITS_LABEL":"Kliknite da biste sortirali po broju poseta",
"SORT_COMMENTS_LABEL":"Kliknite da biste sortirali po broju komentara",
"SORT_RECOMMENDATIONS_LABEL":"Kliknite da biste sortirali po broju sviđanja",
"SORT_POPULARITY_LABEL":"Kliknite da biste sortirali po popularnosti",
"SORT_FIRST_NAME_LABEL":"Kliknite da biste sortirali po datom imenu",
"SORT_LAST_NAME_LABEL":"Kliknite da biste sortirali po prezimenu",
"RATING":"Označeno sa Sviđa mi se",
"GRADUATED":"Usvojene",
"ONEVOTE":"1 glas",
"VOTES":"{0} glasova",
"BOOKMARK_THIS_RESULT":"Obeležite ovo",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (neaktivno)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} osoba obeleženo",
/* eg from an Activity */
"FROMANACTIVITY":"iz Aktivnosti",
"FROMABLOG":"iz Bloga",
"FROMANIDEATIONBLOG":"iz Bloga ideja",
"FROMANEVENT":"iz Događaja",
"FROMAFORUM":"iz Foruma",
"FROMAWIKI":"iz Vikija",
"FROMACOMMUNITY":"iz Zajednica",
"FROMXCOMMUNITIES":"iz {0} zajednica",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivnost",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Blog ideja",
"ENTRY_ALONE":"Unos",
"EVENT_ALONE":"Događaj",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Viki",
"COMMUNITY_ALONE":"Zajednica",
"XCOMMUNITIES_ALONE":"{0} zajednica",
"SHAREDCOMMUNITIES":"Deljeno sa ovim zajednicama",
"INACOMMUNITY":"u zajednici",
"LASTUPDATED":"Poslednje ažuriranje indeksa pretrage:",
"NODESCRIPTION":"Nema opisa ili rezimea za rezultat.",
"ATTACHMENT":"Prilog:",
"ACTIVITY":"Aktivnost:",
"ACTIVITYBOOKMARK":"Obeleživač aktivnosti:",
"ACTIVITYCOMMENT":"Komentar aktivnosti:",
"ACTIVITYENTRY":"Unos aktivnosti:",
"ACTIVITYSECTION":"Odeljak aktivnosti:",
"ACTIVITYTODO":"Planirane aktivnosti:",
"BLOG":"Blog:",
"BLOGENTRY":"Unos bloga:",
"BLOGCOMMENT":"Komentar bloga:",
"BOOKMARK":"Obeleživač:",
"CALENDAREVENT":"Događaj:",
"CATEGORY":"Kategorija:",
"COMMENT":"Komentar:",
"COMMUNITY":"Zajednica:",
"ENTRY":"Unos:",
"EVENTDATEON":"Dana: {0}",
"EVENTISALLDAY":"Celodnevni događaj",
"EVENTREPEATS":"Ponavljanja",
"FEED":"Fid:",
"FILE":"Datoteka:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Kategorija foruma:",
"FORUMTOPIC":"Tema foruma:",
"IDEA":"Ideja:",
"IDEACOMMENT":"Komentar ideje:",
"IDEATIONBLOG":"Blog ideja:",
"PAGE":"Stranica:",
"PROFILE":"Profil:",
"SECTION":"Odeljak:",
"STATUSUPDATE":"Ažuriranje statusa",
"STATUSUPDATE_PREFIX":"Ažuriranje statusa:",
"TOPIC":"Tema:",
"TOPIC_WITH_ATTACHMENT":"Tema",
"WIKITYPE":"Viki:",
"WIKIPAGE":"Viki stranica:",
"WIKIFILE":"Viki prilog:",
"SEARCH":"Pretraga:",
"TODO":"Obaveza:",
"ALLRESULTS":"Svi rezultati",
"PUBLICCONTENT":"Javni sadržaj",
"MYCONTENT":"Moj sadržaj",
"RESULTNOTFOUND":"Niste pronašli ono što ste tražili?",
"TEMPDIFFICULTIES":"Napomena: Zbog privremenih poteškoća sa indeksiranjem, pretraga nije obuhvatila {0} koji su promenjeni poslednjih {1} dan(a).",
"TRYLATER":"Pokušajte ponovo kasnije.",
"MULTIPLETEMPDIFFICULTIES":"Napomena: Zbog privremenih poteškoća sa indeksiranjem, pretraga nije obuhvatila {0} koji su nedavno promenjeni",
"YOUAREAUTHOR":"Vi ste autor",
"YOUARECONTRIBUTOR":"Vi ste učesnik",
"YOUAREOWNER":"Vi ste vlasnik",
"YOUAREMEMBER":"Vi ste član",
/* Profiles */
"MYNETWORK":"Moja mreža",
"ALLPEOPLE":"Sve osobe",
"EXCLUDEINACTIVE":"Izuzmi neaktivne osobe",
"PHONE":"Telefon:",
"EMAIL":"E-pošta:",
/* Communities */
"ALLCOMMUNITIES":"Sve aplikacije Zajednice",
"PUBLICCOMMUNITIES":"Javne zajednice",
"MYCOMMUNITIES":"Moje zajednice",
"EVERYTHINGCOMMUNITIES":"Sve iz aplikacije Zajednice",
"COMMUNITIESONLY":"Zajednice",
"COMMUNITIESCONTENT":"Sadržaj iz aplikacije Zajednica",
/* Activities */
"ALLACTIVITIES":"Sve aktivnosti",
"PUBLICACTIVITIES":"Javne aktivnosti",
"MYACTIVITIES":"Moje aktivnosti",
"EVERYTHINGACTIVITIES":"Sve iz aplikacije Aktivnosti",
"ACTIVITIESONLY":"Aktivnosti",
"SECTIONSACTIVITIES": "Odeljci iz aplikacije Aktivnosti",
"ENTRIESACTIVITIES":"Unosi iz aplikacije Aktivnosti",
"TODOSACTIVITIES":"Obaveze iz aplikacije Aktivnosti",
"BOOKMARKSACTIVITIES":"Obeleživači iz aplikacije Aktivnosti",
"FILESACTIVITIES":"Prilozi iz aplikacije Aktivnosti",
"ALLTYPESACTIVITIES":"Svi tipovi Aktivnosti",
"COMMUNITYACTIVITIES":"Aktivnosti iz aplikacije Zajednice",
"STANDALONEACTIVITIES":"Samostalne Aktivnosti",
/* Forums */
"ALLFORUMS":"Svi Forumi",
"PUBLICFORUMS":"Javni forumi",
"MYFORUMS":"Moji forumi",
"EVERYTHINGFORUMS":"Sve iz aplikacije Forumi",
"FORUMSONLY":"Forumi",
"TOPICSFORUMS":"Teme foruma",
"FORUMCATEGORIES": "Kategorije foruma",
"FILESFORUMS":"Prilozi iz aplikacije Forumi",
"ALLTYPESFORUMS":"Svi tipovi aplikacije Forumi",
"COMMUNITYFORUMS":"Forumi iz aplikacije Zajednice",
"STANDALONEFORUMS":"Samostalni Forumi",
/* Blogs */
"ALLBLOGS":"Svi Blogovi",
"PUBLICBLOGS":"Javni Blogovi",
"MYBLOGS":"Moji blogovi",
"EVERYTHINGBLOGS":"Sve iz aplikacije Blogovi",
"BLOGSONLY":"Blogovi",
"ENTRIESBLOGS":"Unosi na blogu",
"FILESBLOGS":"Prilozi iz aplikacije Blogovi",
"EVERYTHINGIDEATIONBLOGS":"Sve iz aplikacije Blogovi ideja",
"BLOGSIDEATIONBLOGS":"Blogovi ideja",
"BLOGSIDEAS":"Ideje",
"ALLTYPESBLOGS":"Svi tipovi blogova",
"COMMUNITYBLOGS":"Blogovi iz aplikacije Zajednice",
"COMMUNITYIDEATIONBLOGS":"Blogovi ideja iz aplikacije Zajednice",
"STANDALONEBLOGS":"Samostalni Blogovi",
/* Bookmarks */
"ALLBOOKMARKS":"Svi Obeleživači",
"PUBLICBOOKMARKS":"Javni obeleživači",
"MYBOOKMARKS":"Moji obeleživači",
"ALLTYPESBOOKMARKS":"Svi tipovi obeleživača",
"COMMUNITYBOOKMARKS":"Obeleživači iz aplikacije Zajednice",
"STANDALONEBOOKMARKS":"Samostalni Obeleživači",
/* Files */
"ALLFILES":"Sve datoteke",
"PUBLICFILES":"Javne datoteke",
"MYFILES":"Moje datoteke",
"ALLTYPESFILES":"Svi tipovi datoteka",
"COMMUNITYFILES":"Datoteke iz Zajednica",
"STANDALONEFILES":"Samostalne datoteke",
"NUMDOWNLOADS":"{0} Preuzimanja",
/* Wikis */
"ALLWIKIS":"Svi vikiji",
"PUBLICWIKIS":"Javni vikiji",
"MYWIKIS":"Moji vikiji",
"EVERYTHINGWIKIS":"Sve iz vikija",
"WIKISONLY":"Vikiji",
"PAGESWIKIS":"Viki stranice",
"FILESWIKIS":"Prilozi iz vikija",
"ALLTYPESWIKIS":"Svi tipovi vikija",
"COMMUNITYWIKIS":"Vikiji iz Zajednica",
"STANDALONEWIKIS":"Samostalni vikiji",
/* Status Updates */
"ALLSTATUSUPDATES":"Sva ažuriranja statusa",
"PUBLICSTATUSUPDATES":"Javna ažuriranja statusa",
"MYSTATUSUPDATES":"Moja ažuriranja statusa",
"ALLTYPESSTATUSUPDATES":"Svi tipovi ažuriranja statusa",
"COMMUNITYSTATUSUPDATES":"Ažuriranja statusa iz Zajednica",
"STANDALONESTATUSUPDATES":"Ažuriranja statusa iz Profila",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Nekoliko korisnika obeležilo je URL adresu",
"BOOKMARKEDCOMMUNITY":"Nekoliko korisnika obeležilo je zajednicu",
"BOOKMARKEDPROFILE":"Nekoliko korisnika obeležilo je profil",
"BOOKMARKEDBLOG":"Nekoliko korisnika obeležilo je blog",
"COMMUNITYBLOG":"Ovo je blog u zajednici",
"BOOKMARKEDACTIVITY":"Nekoliko korisnika obeležilo je aktivnost",
"COMMUNITYACTIVITY":"Ovo je aktivnost u zajednici",
"BOOKMARKEDFILE":"Nekoliko korisnika obeležilo je datoteku",
"COMMUNITYFILE":"Ovo je datoteka u zajednici",
"BOOKMARKED":"Nekoliko korisnika obeležilo je viki",
"COMMUNITYWIKI":"Ovo je viki u zajednici",
"BOOKMARKEDFORUM":"Nekoliko korisnika obeležilo je forum",
"COMMUNITYFORUM":"Ovo je forum u zajednici",
"ALLTAGANDTTILE":"Da biste videli sve naslove i oznake za ovu URL adresu, kliknite na ovo dugme",
"TAGS_ARE_FROM":"Rezultat pretrage može obuhvatiti oznake iz:",
"BOOKMARKS_TITLE":"Obeleživači",
"COMMUNITIES_TITLE":"Zajednice",
"ACTIVITIES_TITLE":"Aktivnosti",
"HELP":"Pomoć",
"MORESTATUSUPDATES":"Prikaži više podudaranja ažuriranja statusa",
"TITLE_PREFIX":"naslov:",
"LATEST_MESSAGE":"Najnovija poruka",
"LATEST_STATUS_UPDATE":"Najnovije ažuriranje statusa",
"LATEST_COMMUNITY_STATUS_UPDATE":"Najnovije ažuriranje statusa zajednice",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Najnovije ažuriranje statusa zajednica",
"SEARCH_RESULTS":"Svi rezultati pretrage sadržaja",
"ACTIVITIES_SEARCH_RESULTS":"Rezultati pretrage Aktivnosti",
"BLOGS_SEARCH_RESULTS":"Rezultati pretrage aplikacije Blogovi",
"BOOKMARKS_SEARCH_RESULTS":"Rezultati pretrage aplikacije Obeleživači",
"COMMUNITIES_SEARCH_RESULTS":"Rezultati pretrage aplikacije Zajednice",
"FILES_SEARCH_RESULTS":"Rezultati pretrage aplikacije Datoteke",
"FORUMS_SEARCH_RESULTS":"Rezultati pretrage aplikacije Forumi",
"PROFILES_SEARCH_RESULTS":"Rezultati pretrage aplikacije Profili",
"DIRECTORY_SEARCH_RESULTS":"Rezultati pretrage direktorijuma ${orgName}",
"WIKIS_SEARCH_RESULTS":"Rezultati pretrage vikija",
"STATUS_UPDATES_SEARCH_RESULTS":"Rezultati pretrage Ažuriranja statusa",
"VIEW_ALL":"{span}Prikaži sve{/span} ({0})",
"MATCHING_ONE_OF":"Podudaranje sa jednim od navedenog:",
"MATCHING_ALL_OF":"Podudaranje sa svim navedenim:",
"MATCHING":"Podudaranje:",
"MATCHING_DOC_TYPE":"Tip dokumenta koji se podudara:",
"BOOKMARK_HELP":"Pomoć za obeleživač",
"CLOSE_BOOKMARK_HELP":"Zatvori Pomoć za obeleživač",
"DOCUMENT_TYPE_PREFIX":"Tip dokumenta:",
"FILE_PREVIEW_ONLY":"(Samo režim pregleda)"
})

