/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
	root: {
		"ACTIVITIES_LABEL":"Activities",
		"ACTIVITIES_TITLE":"Show results from Activities",
		"ALLCONNECTIONS_LABEL":"All Content",
		"ALLCONNECTIONS_TITLE":"Show results from all of Connections",
		"APPLICATIONS_FILTER_LABEL":"Filter by Application",
		"BLOGS_LABEL":"Blogs",
		"BLOGS_TITLE":"Show results from Blogs",
		"DOGEAR_LABEL":"Bookmarks",
		"DOGEAR_TITLE":"Show results from Bookmarks",
		"COMMUNITIES_LABEL":"Communities",
		"COMMUNITIES_TITLE":"Show results from Communities",
		"COMPONENT_FILTER_LABEL":"Filter your search results to content from a specific application",
		"FILES_LABEL":"Files",
		"FILES_TITLE":"Show results from Files",
		"FORUMS_LABEL":"Forums",
		"FORUMS_TITLE":"Show results from Forums",
		"PROFILES_LABEL":"Profiles",
		"PROFILES_TITLE":"Show results from Profiles",
		"DIRECTORY_LABEL":"${orgName} Directory",
		"DIRECTORY_TITLE":"Show results from ${orgName} Directory",
		"WIKIS_LABEL":"Wikis",
		"WIKIS_TITLE":"Show results from Wikis",
		"STATUS_UPDATES_LABEL":"Status Updates",
		"STATUS_UPDATES_TITLE":"Show results from Status Updates",
		"SELECTED":"Selected."
	},

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
