/* Copyright IBM Corp. 2012, 2015  All Rights Reserved.           */

// NLS_CHARSET=UTF-8
define({
	root: {
		"ADD_PROPERTY":"Add Property",
		"APPLY":"Apply",
		"CANCEL":"Cancel",
		"CLOSE":"Close",
		"DAY":"Day",
		"EDIT_PROPERTY":"Edit Property",
		"EMPTY_TEXT":"There are no properties with which you can filter your search results at this time.",
		"END_DATE":"End Date",
		"END_DATE_PREFIX":"End Date:",
		// An example of the string below would be: "Enter a date in the format: 02/10/2012"
		"ENTER_A_DATE":"Enter a date in the format: {date}",
		"ENTER_A_NUMBER":"Enter a number",
		"ERROR_OCCURRED":"An unexpected error has occurred.",
		"FALSE":"False",
		"FORMAT_PREFIX":"Format:",
		"LEGEND":"Legend",
		"LOADING":"Loading...",
		"PROPERTY_PREFIX":"Property:",
		"PROPERTY_VALUE":"Property Value",
		"PROPERTY_VALUE_PREFIX":"Property Value:",
		"RANGE":"Range",
		"REQUIRED_FIELD":"Required field",
		"REQUIRED_LEGEND":"* Required",
		"SELECT_A_PROPERTY":"Select a property",
		"SHOW_DETAILS":"Show details",
		"START_DATE":"Start Date",
		"START_DATE_PREFIX":"Start Date:",
		"TO":"to",
		"TRUE":"True"
	},

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
