/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
	root: {
		"ACTIVITIES":"Activities",
		"BLOGS":"Blogs",
		"COMMUNITIES":"Communities",
		"DOGEAR":"Bookmarks",
		"FILES":"Files",
		"FORUMS":"Forums",
		"LOADING":"Loading...",
		"MATCHING":"Matching:",
		"MATCHING_ALL_OF":"Matching all of:",
		"MATCHING_DOCUMENT_TYPE":"Matching Document Type:",
		"MATCHING_ONE_OF":"Matching one of:",
		"PROFILES":"Profiles",
		"PROPERTIES_PREFIX":"Properties: ",
		/* An example of the below would be "Sell date: 6/1/2011 to 6/15/2011" */
		"PROPERTY_X_IS_DATE1_TO_DATE2":"{property}: {date1} to {date2}",
		/* An example of the below would be "Consultant: Heather Reeds" */
		"PROPERTY_X_IS_Y":"{property}: {value}",
		"REMOVE_FILTER_TITLE":"Remove",
		"REMOVE_FILTER_TOOLTIP":"Remove this filter",
		"STATUS_UPDATES":"Status Updates",
		"WIKIS":"Wikis"
	},

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
