/* Copyright IBM Corp. 2012, 2015  All Rights Reserved.           */

// NLS_CHARSET=UTF-8
define({
	root: {
		"COMMUNITY":"Community",
		"ERROR":"Error",
		"ERROR_OCCURRED":"The search was not performed due to a server error",
		"ERROR_PREFIX":"Error:",
		"FILE":"File",
		"FILES":"Files",
		"ITEMS":"{0} items",
		"LASTUPDATED":"Search index was last updated:",
		"LOADING":"Loading...",
		"NEXT":"Next",
		"NORESULTSMESSAGE":"No results were found for that search",
		"PAGING_TOP":"Primary paging",
		"PAGING_BOTTOM":"Secondary paging",
		"PREVIOUS":"Previous",
		"SHOW":"Show:"
	},

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
