/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
	root: {
		"SORT_BY":"Sort by:",
		"SORT_RELEVANCE":"Relevance",
		"SORT_DATE":"Date",
		"SORT_LAST_UPDATED":"Last Updated",
		"SORT_DUE_DATE":"Due Date",
		"SORT_COMMENTS":"Comments",
		"SORT_LIKES":"Likes",
		"SORT_POPULARITY":"Popularity",
		"SORT_FIRSTNAME":"First Name",
		"SORT_LASTNAME":"Last Name",
		"SORT_INACTIVE":"Sort by [${0}]",
		"SORT_ACTIVE_ASCENDING":"Sorted by [${0}], ascending. Click to sort in descending order",
		"SORT_ACTIVE_DESCENDING":"Sorted by [${0}], descending. Click to sort in ascending order",
		"SORT_ACTIVE_ASCENDING_DISABLED":"Sorted by [${0}], ascending.",
		"SORT_ACTIVE_DESCENDING_DISABLED":"Sorted by [${0}], descending.",
		"SORT_ASCENDING":"Ascending. Click to sort in descending order",
		"SORT_DESCENDING":"Descending. Click to sort in ascending order",
		"SORT_ASCENDING_DISABLED":"Ascending.",
		"SORT_DESCENDING_DISABLED":"Descending.",
		"SORT_VOTES": "Votes"
	},

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
