/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informationen für den Knoten: ",
		"INSTALLED": "Überprüfung der installierten Services",
		"RESUMETOKENS": "Überprüfung der Fortsetzungstoken",
		"SEEDLISTS": "Überprüfung, ob die Basislisten verfügbar sind",
		"CALENDARS": "Überprüfung, ob die Zeitplankalender ordnungsgemäß konfiguriert sind",
		"VARIABLES": "Überprüfung, ob die WebSphere-Variablen eingestellt wurden",
		"TASKS": "Überprüfung auf aktivierte Indexierungstasks",
		"INDEXFILES": "Überprüfung der Indexordner auf erforderliche Dateien",
		"LOGS": "Überprüfung der Protokolle auf Fehler",
		"CONFIGFILES": "Überprüfung der Konfigurationsdateien",
		"DICTIONARIES": "Überprüfung der Anzahl der aktivierten Wörterbücher",
		"SYNC": "Der Status der Knoten wird überprüft",
		"DBRECORDS": "Überprüfung der Datenbanksätze",
		"INSTALLEDMSG": "Der folgende Service ist installiert: ",
		"RESUMETOKENSMSG": "Der Fortsetzungstoken für: ",
		"SEEDLISTSMSG": "Die Basisliste konnte nicht abgerufen werden für: ",
		"CALENDARSMSG": "Überprüfung des Zeitplankalenders erfolgreich: ",
		"VARIABLESMSG": "Variable: ",
		"TASKSMSG": "Folgende Task ist aktiviert: ",
		"INDEXFILESMSG" : "Folgende Dateien befinden sich im Suchindexordner: ",
		"LOGSMSG" : "Überprüfen Sie die folgenden Fehlernachrichten: ",
		"CONFIGFILESMSG" : "Folgende Konfigurationsdateien wurden gefunden: ",
		"DICTIONARIESMSG" : "Die Anzahl der aktivierten Wörterbücher ist: ",
		"INSYNC": "Alle Knoten sind synchron",
		"OUTOFSYNC": "Die Anzahl der nicht synchronen Knoten ist: ",
		"NOTBLOCKED": "Keine Knoten sind geblockt",
		"BLOCKED": "Die Anzahl der geblockten Knoten ist: ",
		"INDATE": "Alle Knoten sind auf dem neuesten Stand",
		"OUTOFDATE": "Die Anzahl der Knoten, die nicht auf dem neuesten Stand sind: ",
		"NUMOFDOCS": "Die Anzahl der Dokumente in der Datenbank ist ",
		"FILESTOCONVERT": "Die Anzahl der zu konvertierenden Dateidokumente ist",
		"CONVERTEDFILES": "Die Anzahl der konvertierten Dateien ist ",
		"TOTALFILES": "Gesamtzahl der Dateien in der Datenbank ",
		"ERROR":"Fehler",
		"ERROR_PREFIX":"Fehler:",
		"INFO":"Information ",
		"INFO_PREFIX":"Information: ",
		"WARNING":"Warnung ",
		"WARNING_PREFIX":"Warnung:",
		"LOADING_MESSAGE": "Laden",
		"SERVER_STATUS": "Serverstatus",
		"INITIAL_INDEXING_EXCEPTIONS": "Ausnahmen im ersten Index",
		"SYS_OUT_EXCEPTIONS": "Ausnahmen im SystemOut-Protokoll",
		"SEEDLIST_VALIDATE": "Seedlists-Überprüfung",
		"ERRORS_DURING_INITIAL_INDEXING":"Die folgenden Ausnahmen sind bei der Erstellung eines ersten Index aufgetreten",
		"CRAWL_FAILED": "Keine der Daten für den folgenden Service konnten mit der Crawlersuche durchsucht werden: ",
		"EXCEPTION_ENCOUNTERED": "Die Crawlersuche ist mit der folgenden Nachricht fehlgeschlagen: ",
		"SAND_VALIDATE": "SAND-Überprüfung",
		"CHECK_FOR_SAND_FILES":"Überprüfung auf SAND-Dateien",
		"IS_FILE_AVAILABLE":"Überprüfung, ob die Datei erstellt wurde: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Die folgenden Ausnahmen sind bei der Erstellung eines ersten Index aufgetreten",
		"CRAWL_FAILED":"Keine der Daten für den folgenden Service konnten mit der Crawlersuche durchsucht werden: ",
		"EXCEPTION_ENCOUNTERED":"Die Crawlersuche ist mit der folgenden Nachricht fehlgeschlagen: "
});

