/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informações para o nó: ",
	"INSTALLED": "Verificando os serviços instalados",
	"RESUMETOKENS": "Verificando os tokens de continuação",
	"SEEDLISTS": "Verificando se as listas de valores iniciais estão disponíveis",
	"CALENDARS": "Verificando se os calendários de planejamento foram configurados corretamente",
	"VARIABLES": "Verificando se as variáveis do WebSphere foram configuradas",
	"TASKS": "Verificando se há tarefas de indexação ativadas",
	"INDEXFILES": "Verificando a pasta de índices dos arquivos necessários",
	"LOGS": "Revisando os logs em busca de erros",
	"CONFIGFILES": "Revisando os arquivos de configuração",
	"DICTIONARIES": "Verificando o número de dicionários que foram ativados",
	"SYNC": "Verificando o status dos nós",
	"DBRECORDS": "Verificando os registros do banco de dados",
	"INSTALLEDMSG": "O seguinte serviço está instalado: ",
	"RESUMETOKENSMSG": "O token de continuação para: ",
	"SEEDLISTSMSG": "Não foi possível obter a lista de valores iniciais para: ",
	"CALENDARSMSG": "Verificação de calendário de planejamento aprovada: ",
	"VARIABLESMSG": "Variável: ",
	"TASKSMSG": "A seguinte tarefa está ativada: ",
	"INDEXFILESMSG" : "Os seguintes arquivos estão na pasta de índice de procura: ",
	"LOGSMSG" : "Revise as seguintes mensagens de erro: ",
	"CONFIGFILESMSG" : "Os seguintes arquivos de configuração foram localizados: ",
	"DICTIONARIESMSG" : "O número de dicionários ativados é: ",
	"INSYNC": "Todos os nós estão sincronizados",
	"OUTOFSYNC": "O número de nós fora de sincronização é: ",
	"NOTBLOCKED": "Não há nós bloqueados",
	"BLOCKED": "O número de nós bloqueados é: ",
	"INDATE": "Todos os nós estão atualizados",
	"OUTOFDATE": "O número de nós desatualizados é: ",
	"NUMOFDOCS": "O número de documentos no banco de dados é ",
	"FILESTOCONVERT": "O número de documentos de arquivo a serem convertidos é ",
	"CONVERTEDFILES": "O número de arquivos convertidos é ",
	"TOTALFILES": "O número total de arquivos no banco de dados ",
	"ERROR":"Erro",
	"ERROR_PREFIX":"Erro:",
	"INFO":"Informações",
	"INFO_PREFIX":"Informações:",
	"WARNING":"Aviso",
	"WARNING_PREFIX":"Aviso:",
	"LOADING_MESSAGE": "Carregando",
	"SERVER_STATUS": "Status de Servidor",
	"INITIAL_INDEXING_EXCEPTIONS": "Exceções de Indexação Inicial",
	"SYS_OUT_EXCEPTIONS": "Log de Exceções SystemOut",
	"SEEDLIST_VALIDATE": "Validação de Listas de Valores Iniciais",
	"ERRORS_DURING_INITIAL_INDEXING":"As seguintes exceções ocorram ao criar um índice inicial",
	"CRAWL_FAILED": "Todos os dados do serviço a seguir não puderam ter o crawl efetuado: ",
	"EXCEPTION_ENCOUNTERED": "O crawl falhou com a mensagem a seguir: ",
	"SAND_VALIDATE": "Validação de SAND",
	"CHECK_FOR_SAND_FILES":"Verificando se há arquivos SAND",
	"IS_FILE_AVAILABLE":"Verificando se o arquivo foi criado: ",
	"ERRORS_DURING_INITIAL_INDEXING":"As seguintes exceções ocorram ao criar um índice inicial",
	"CRAWL_FAILED":"Todos os dados do serviço a seguir não puderam ter o crawl efetuado: ",
	"EXCEPTION_ENCOUNTERED":"O crawl falhou com a mensagem a seguir: "
})

