/* Copyright IBM Corp. 2015  All Rights Reserved.                    */
define({
	root: ({
			TAGS: "TAGS",
			TAGS_L: "Tags:",
			EXCEEDED_TAGS: "Plus ${count} more tags...",
			EXCEEDED_ONE_TAG: "Plus 1 more tag..."
	}),

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
