/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informace pro uzel: ",
	"INSTALLED": "Kontrola nainstalovaých služeb",
	"RESUMETOKENS": "Kontrola tokenů obnovení",
	"SEEDLISTS": "Kontrola, zda jsou k dispozici počáteční seznamy",
	"CALENDARS": "Kontrola, zda jsou kalendáře časového plánu správně konfigurovány",
	"VARIABLES": "Kontrola, zda jsou nastaveny proměnné platformy WebSphere",
	"TASKS": "Kontrola povolených úloh indexování",
	"INDEXFILES": "Kontrola existence vyžadovaných souborů v indexové složce",
	"LOGS": "Kontrola, zda protokoly neobsahují chyby",
	"CONFIGFILES": "Kontrola konfiguračních souborů",
	"DICTIONARIES": "Kontrola počtu povolených slovníků",
	"SYNC": "Kontrola stavu uzlů",
	"DBRECORDS": "Kontrola záznamů databáze",
	"INSTALLEDMSG": "Následující služba je nainstalována: ",
	"RESUMETOKENSMSG": "Token obnovení pro: ",
	"SEEDLISTSMSG": "Nepodařilo se získat počáteční seznam pro: ",
	"CALENDARSMSG": "Byla úspěšně provedena kontrola kalendáře časového plánu: ",
	"VARIABLESMSG": "Proměnná: ",
	"TASKSMSG": "Následující služba je povolena: ",
	"INDEXFILESMSG" : "Následující soubory se nacházejí ve složce vyhledávacího indexu: ",
	"LOGSMSG" : "Přezkoumejte následující chybové zprávy: ",
	"CONFIGFILESMSG" : "Byly nalezeny následující konfigurační soubory: ",
	"DICTIONARIESMSG" : "Počet povolených slovníků: ",
	"INSYNC": "Všechny uzly jsou synchronizovány.",
	"OUTOFSYNC": "Počet nesynchronizovaných uzlů: ",
	"NOTBLOCKED": "Nejsou blokovány žádné uzly.",
	"BLOCKED": "Počet blokovaných uzlů: ",
	"INDATE": "Všechny uzly jsou aktuální.",
	"OUTOFDATE": "Počet neaktuálních uzlů: ",
	"NUMOFDOCS": "Počet dokumentů v databázi: ",
	"FILESTOCONVERT": "Počet převedených souborů dokumentů: ",
	"CONVERTEDFILES": "Počet převedených souborů: ",
	"TOTALFILES": "Celkový počet souborů v databázi: ",
	"ERROR":"Chyba",
	"ERROR_PREFIX":"Chyba:",
	"INFO":"Informace",
	"INFO_PREFIX":"Informace:",
	"WARNING":"Varování",
	"WARNING_PREFIX":"Varování:",
	"LOADING_MESSAGE": "Načítání",
	"SERVER_STATUS": "Stav serveru",
	"INITIAL_INDEXING_EXCEPTIONS": "Výjimky při počátečním indexování",
	"SYS_OUT_EXCEPTIONS": "Výjimky protokolu systémového výstupu",
	"SEEDLIST_VALIDATE": "Ověřování počátečních seznamů",
	"ERRORS_DURING_INITIAL_INDEXING":"Během vytváření počátečního indexu došlo k následujícím výjimkám.",
	"CRAWL_FAILED": "Nebylo možné prolézt všechna data pro následující službu: ",
	"EXCEPTION_ENCOUNTERED": "Došlo k selhání při prolézání s následující zprávou: ",
	"SAND_VALIDATE": "Ověřování SAND",
	"CHECK_FOR_SAND_FILES":"Probíhá zjišťování souborů SAND.",
	"IS_FILE_AVAILABLE":"Probíhá kontrola vytvoření souboru: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Během vytváření počátečního indexu došlo k následujícím výjimkám.",
	"CRAWL_FAILED":"Nebylo možné prolézt všechna data pro následující službu: ",
	"EXCEPTION_ENCOUNTERED":"Došlo k selhání při prolézání s následující zprávou: "
})

