/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "יש ללחוץ כאן כדי לראות כרטיס ביקור",
	"label.semtag.hover.alt" : "יש ללחוץ כדי לראות כרטיס ביקור של {0}",
	"label.semtag.hover.altA11Y" : "יש ללחוץ כאן או להקיש Control-Enter כדי לראות את כרטיס הביקור",
	"label.personcard.dialog.title" : "כרטיס ביקור של {0}",

	"errorDefaultMsg2" : "אירעה שגיאה, יש לפנות למנהלן המערכת.",

	"loadingSTStatus" : "מצב Sametime נטען...‏",
	"noStatuAvailable" : "מצב Sametime אינו זמין",

	"label.personcard.cardnomarkup" : "לא ניתן לאחזר את כרטיס הביקור",
	"label.inactive.user.msg" : "אדם זה כבר אינו משתמש פעיל",
	"label.message.information" : "מידע:‏",
	"label.personcard.noprofilemsg" : "לא קיים פרופיל עבור אדם זה",
	"label.personcard.cardreqexpired" : "תוקף הבקשה לקבלת כרטיס הביקור פג",

	"label.bizcard.applinks.less" : "הצגת פחות",
	"label.bizcard.applinks.more" : "הצגת יותר",

	"label.personcard.activitieslink" : "פעילויות",
	"label.personcard.activitieslink.title" : "לחצו כאן כדי לראות פעילויות משותפות",
	"label.personcard.blogslink" : "בלוגים",
	"label.personcard.blogslink.title" : "לחצו כאן כדי לראות את הבלוג של אדם זה",
	"label.personcard.communitieslink" : "קהילות",
	"label.personcard.communitieslink.title" : "לחצו כאן כדי לראות את הקהילות של אדם זה",
	"label.personcard.dogearlink" : "סימניות",
	"label.personcard.dogearlink.title" : "יש ללחוץ כאן כדי לראות את הסימניות של אדם זה",
	"label.personcard.fileslink" : "קבצים",
	"label.personcard.fileslink.title" : "לחצו כאן כדי לראות את הקבצים המשותפים של אדם זה",
	"label.personcard.forumlink" : "פורומים",
	"label.personcard.forumlink.title" : "לחצו כאן כדי לראות את פרסומי הפורום של אדם זה",
	"label.personcard.homepagelink" : "דף הבית",
	"label.personcard.homepagelink.title" : "לחצו כאן כדי לראות את דף הבית של אדם זה",
	"label.personcard.mobilelink" : "נייד",
	"label.personcard.mobilelink.title" : "לחצו כאן כדי לראות את הדף הנייד של אדם זה",
	"label.personcard.newslink" : "חדשות",
	"label.personcard.newslink.title" : "לחצו כאן כדי לראות את החדשות של אדם זה",
	"label.personcard.profilelink" : "פרופיל",
	"label.personcard.profilelink.title" : "לחצו כאן כדי לראות את הפרופיל של אדם זה",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "לחצו כאן כדי לראות את שיתופי quickr של אדם זה",
	"label.personcard.wikislink" : "אתרי ויקי",
	"label.personcard.wikislink.title" : "לחצו כאן כדי לראות את אתרי הוויקי של אדם זה",

	"personCardMoreActions" : "פעולות נוספות",
	"personCardMoreActionsAltText" : "לחצו לתפריט הפעולות",

	"label.bizcard.dismiss": "לחצו על Escape כדי לסגור את כרטיס הביקור.",
	"label.bizcard.fullProfile": "פרופיל שלם",
	"label.bizcard.activities": "פעילויות",
	"label.bizcard.communities": "קהילות",
	"label.bizcard.files": "קבצים",
	"label.bizcard.forums": "פורומים",
	"label.bizcard.bookmarks": "סימניות",
	"label.bizcard.blogs": "בלוגים",
	"label.bizcard.wikis": "אתרי ויקי",

	"personCardAddAsColleagues" : "הזמן אל 'הרשת שלי'",
	"personCardAddAsMyColleagues" : "הזמן אל 'הרשת שלי'",
	"personCardFollow" : "מעקב",
	"personCardUnfollow" : "הפסקת מעקב",
	"personCardChat" : "צ'אט",
	"personCardCall" : "התקשרו",
	"personCardSendMail" : "משלוח דואל",
	"personCardSendEMail" : "משלוח דואל",
	"personCardProxyStatusAvailable" : "אני זמין",
	"personCardDownloadVCard" : "הורדת vCard",

	"friends" : "רשת",
	"friendsFullPageTitle" : "רשת",
	"friendsMenuTitleAllContacts" : "כל אנשי הקשר ברשת",
	"friendsMenuTitleMyContacts" : "אנשי קשר ברשת שלי",
	"friendsInvitations" : "הזמנות",
	"friendsMenuTitleInCommon" : "אנשים משותפים",
	"friendsShowAllCommonFriends" : "הצגת הכל...",
	"friendsViewAllFriends" : "הצגת הכל ({0})",
	"friendsSendFriendRequest" : "שלח בקשה",
	"friendsNoFriends" : "אין חברי רשת המשויכים לפרופיל זה",
	"friendsColleaguesInvite" : "הזמנת {0} כחבר רשת",
	"friendsColleaguesFor" : "חברי רשת עבור {0}",
	"friendsNewInv" : "{0} הזמנה חדשה",
	"friendsNewInvs" : "{0} הזמנות חדשות",
	"friendsLoading" : "הרשת נטענת...‏",
	"friendsLoadingInv" : "טוען הזמנות...",
	"friendsSelectFriendForRemoval" : "יש לבחור את אנשי הקשר שברצונך להסיר קודם.",
	"friendsRemoved" : "‫חברי הרשת סולקו.‏‬",
	"friendsInvSent" : "‫לא נשלחו הזמנות מפני שכבר יש הזמנה ממתינה.‏‬",
	"friendsRemovedSelected" : "סילוק מתוך 'הרשת שלי'",
	"friendsSortByDisplayName" : "שם להצגה",
	"friendsSortByRecent" : "בשימוש לאחרונה",
	"friendsTelephone" : "טלפון:",
	"friendsEmail" : "דוא\"ל:",
	"friendsAltEmail" : "דואל חלופי:",
	"friendsNewInvitationsCount" : "יש לכם {0} הזמנות חדשות",
	"friendsNoInv" : "אין הזמנות",
	"friendsInCommonSingle" : "יש לכם {0} חבר רשת משותפים",
	"friendsInCommonMulti" : "יש לכם {0} חברי רשת משותפים",
	"friendsIncludeMsgForInv" : "כלול הודעה בהזמנתך:",
	"friendsInitialMsgForInv" : "ברצוני להוסיף אותך אל רשימת חברי הרשת שלי ב-Connections.",
	"friendsSendInvAction" : "משלוח הזמנה",
	"friendsCancelInvAction" : "ביטול",
	"friendsAcceptAction" : "קבלה",
	"friendsIgnoreAction" : "התעלמות",
	"friendsYouExceedTextLimit" : "‫הודעת ההזמנה שלכם ארוכה מדי. האורך המרבי הוא {1} תווים. יש {0} תווים בשדה זה.‏‬",
	"friendsCannotAddYourself" : "‫אינכם יכולים להוסיף את עצמכם כחברי רשת.‏‬",
	"friendsIsYourColleague" : "{0} הוא חבר רשת שלכם",
	"friendsRecentlyAdded" : "אנשים שהוספתם לאחרונה לרשת שלכם",
	"friendsDate" : "תאריך",
	"friendsCollapseWidget" : "לחצו כדי לכווץ את מקטע הרשת",
	"friendsExpandWidget" : "לחצו כדי להרחיב את מקטע הרשת",
	"friendsIsInYourNetwork" : "{0} ברשת שלכם.",
	"friendsActionsFor" : "פעולות עבור 'רשת'",
	"friendsInviteFollowError" : "אירעה שגיאה בניסיון לעקוב אחר {0}",
	"friendsInviteTagError" : "אירעה שגיאה בניסיון ליצור תג {0}",
	"friendsPleaseLogIn" : "התחברו כדי להזמין משתמש זה לרשת שלכם",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "לא ניתן לשלוח הזמנה לרשת שלכם כי {0} כבר נמצא ברשת שלכם.",
	"friendsInviteAddTagsFor" : "הוספת תגים עבור {0}:",
	"friendsInviteAlsoFollow" : "גם מעקב",
	"friendsInviteReceiveUpdates" : "(קבלת עדכונים)",
	"friendsInviteUpdatesDescription" : "קבלת עדכונים על אנשים שאתם עוקבים אחריהם בדף הבית ובסיכום בדואל.",
	"friendsInviteFollowHelp": "כדי לקבל מידע נוסף, ראו {0}מעקב אחר אנשים{1}.",
	"friendsNetwork" : "רשת",
	"friendsMyNetwork" : "רשת",
	"friendsNetworkFor" : "רשת עבור {0}",
	"friendsRemoveSelected" : "הסירו את הפריטים שנבחרו",
	"friendsRemoveSelectedTip" : "לחצו כדי לסלק את האנשים שנבחרו מהרשת שלכם.",
	"friendsNetworkInCommon" : "יש לכם {0} חברי רשת משותפים.",
	"friendsAddToMyNetwork" : "ברצוני להוסיף אותך אל רשת Connections שלי.",
	"friendsInvite" : "הזמן אל 'הרשת שלי'",
	"friendsInvitePerson" : "הזמנת {0} לרשת שלכם",
	"friendsInviteMessage" : "ברצוני להוסיף אותך אל רשת Connections שלי.",
	"friendsInvitedEmailSubject" : "[פרופילים] אתם מוזמנים להצטרף אל הרשת שלי",
	"friendsInvitedEmailMsg1" : "הזמין אותך לרשת שלו, וההזמנה כוללת את ההודעה שלהלן:",
	"friendsInvitedEmailMsg2" : "פתיחת דף הזמנות הרשת שלכם",
	"friendsInvitedEmailMsg3" : "ברצוני להוסיף אותך לרשת שלי.",
	"friendsInvitedEmailMsg4" : "{0} הזמין אתכם להיות חברי רשת:",
	"friendsInvitedEmailMsg5" : "{0} הזמין אותך לרשת שלו, וההזמנה כוללת את ההודעה שלהלן:",
	"friendsInviteLegalNote" : "בכך שאתם שולחים הזמנה זו, אתם מסכימים להרשות ל-{0} להוסיף הערות ללוח הפרופיל שלכם.",
	"friendsInviteFailed" : "בגלל שגיאה בשרת, לא נשלח דיווח בדוא\"ל לאדם זה. עם זאת, הוא יוכל להיענות להזמנתכם דרך יישום הרשת של הפרופילים.",
	"personInNetwork" : "חבר רשת"
})
