/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "제목은 필수 항목입니다.",
	nourl: "URL은 필수 항목입니다.",
	fileSchema: "원격 또는 로컬 파일 링크를 추가하려면 file://remote_path 또는 file:///local_path 형식 중 하나를 준수해야 합니다.",
	invalidUrl: "유효한 커뮤니티 URL이 아닙니다.",
	invalidTagChar: "입력한 태그 목록에 올바르지 않은 문자('&')가 포함되어 있습니다. 태그 목록에서 이 문자를 제거하십시오.",
	txtHelp: "도움말",
	txtHelpTags: "태그 도움말",
	txtHelpTagsClose: "태그 도움말 닫기",
	tagsall: "모두",
	tagsyours: "사용자 태그",
	tagsrecent: "최근: ",
	tagspopular: "인기: ",
	tagsrecommended: "추천: ",
	nothingselected: "커뮤니티 선택이 필요합니다.",
	nothingselected_activity: "활동 선택이 필요합니다.",
	nothingselected_blogs: "블로그 선택이 필요합니다.",
	nothingselected_all: "서비스 또는 항목을 선택하지 않아서 책갈피가 저장되지 않습니다.",
	nothingFeedselected: "서비스 또는 항목을 선택하지 않아서 피드가 저장되지 않습니다.",
	alertDialogTitle: "메시지",
	alertDialogOK: "확인",
	expand: "이 섹션을 펼치려면 클릭",
	collapse: "이 섹션을 접으려면 클릭",
	discussThis: "다음 문제에 대해 토론 ",
	by: "작성: ",
	posted: "게시됨: ",
	attachments: "첨부 파일 ",
	communityForum: "커뮤니티 포럼",
	notCommunityPage: "현재 웹 페이지가 유효한 커뮤니티 웹 페이지가 아닙니다. 수동으로 커뮤니티 제목, 링크 및 설명을 입력하여 관련 커뮤니티를 작성할 수 있습니다.",
	privateCommunityNotice: "이 커뮤니티는 제한됩니다. 커뮤니티의 회원만 볼 수 있습니다.",
	forumNameHint : "포럼 이름 입력",
	formDescriptionHint:"이 관련 커뮤니티가 사용자의 커뮤니티의 관심 대상인 이유를 설명하십시오.",
	information : "정보",
	error : "오류",
	success : "성공",
	warning : "경고",
	informationColon : "정보:",
	successColon : "성공:",
	warningColon : "경고: ",
	errorColon : "오류:",
	feedAlreadyExist : "커뮤니티에 피드가 이미 있습니다.",
	bookmarkAlreadyExist : "커뮤니티에 책갈피가 이미 있습니다.",
	mentionAuthWarning:"멘션된 나의 관심 사용자는 커뮤니티의 회원이 아니므로 메시지를 볼 수 없습니다. ",
	mentionAuthForumWarning:"멘션된 나의 관심 사용자는 이 포럼에 대한 액세스 권한이 없으므로 메시지를 볼 수 없습니다. ",
	exceedDescLength: "입력한 설명이 너무 깁니다.",
	communities_checked:"${0}개의 커뮤니티를 선택함",
	activities_checked:"${0}개의 활동을 선택함",
	blogs_checked:"${0}개의 블로그를 선택함"
})
