/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "O título é necessário.",
	nourl: "A Url é requerida.",
	fileSchema: "Se você deseja incluir um link de arquivo remoto ou local, ele deve se adequar a um dos formatos a seguir: file://remote_path ou file:///local_path.",
	invalidUrl: "Esta não é uma URL de comunidade válida.",
	invalidTagChar: "A lista de tags inserida contém o caractere inválido "&". Remova esse caractere da lista de tags.",
	txtHelp: "Ajuda",
	txtHelpTags: "Ajuda para Marcações",
	txtHelpTagsClose: "Fechar Ajuda de Marcações",
	tagsall: "Todos",
	tagsyours: "Seu",
	tagsrecent: "Recente: ",
	tagspopular: "Popular: ",
	tagsrecommended: "Recomendada: ",
	nothingselected: "É necessário selecionar uma comunidade.",
	nothingselected_activity: "Uma seleção de atividade é necessária.",
	nothingselected_blogs: "Uma seleção de blog é necessária.",
	nothingselected_all: "Nenhum serviço ou entrada é selecionado, o favorito não será salvo.",
	nothingFeedselected: "Não há serviço ou entrada selecionada, o feed não será salvo.",
	alertDialogTitle: "Mensagem",
	alertDialogOK: "OK",
	expand: "Clique para expandir esta seção",
	collapse: "Clique para reduzir esta seção",
	discussThis: "Discutir Isto",
	by: "por:",
	posted: "Postado:",
	attachments: "Anexos",
	communityForum: "Fórum da Comunidade",
	notCommunityPage: "A página da web atual não é uma página da web de comunidade válida. É possível inserir manualmente o título, o link e a descrição da comunidade para criar uma comunidade relacionada.",
	privateCommunityNotice: "Esta comunidade é restrita. Ela só está visível aos membros da comunidade.",
	forumNameHint : "Digite o nome de um fórum",
	formDescriptionHint:"Descreva por que essa comunidade relacionada interessaria à sua comunidade.",
	information : "Informações",
	error : "Erro",
	success : "Êxito",
	warning : "Aviso",
	informationColon : "Informações:",
	successColon : "Sucesso:",
	warningColon : "Aviso:",
	errorColon : "Erro:",
	feedAlreadyExist : "O feed já existe na comunidade.",
	bookmarkAlreadyExist : "O favorito já existe na comunidade.",
	mentionAuthWarning:"As pessoas mencionadas a seguir não poderão visualizar a mensagem, porque elas não são membros da comunidade:",
	mentionAuthForumWarning:"As pessoas mencionadas a seguir não poderão visualizar a mensagem, porque elas não podem acessar esse fórum.",
	exceedDescLength: "A descrição inserida é muito longa.",
	communities_checked:"${0} comunidades selecionadas",
	activities_checked:"${0} atividades selecionadas",
	blogs_checked:"${0} blogs selecionados"
})
