/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"กรองตาม:",
"SHOW":"แสดง:",
"ACL_FILTER_LABEL":"กรองตามทัศนวิสัย",
"PARENT_FILTER_LABEL":"กรองตามคอนเทนเนอร์",
"TYPE_FILTER_LABEL":"กรองตามชนิด",
"PAGING_TOP":"การเพจหลัก",
"PAGING_BOTTOM":"การเพจรอง",
"PREVIOUS":"ก่อนหน้า",
"NEXT":"ถัดไป",
"PAGE":"หน้า {0} จาก {1}",
"PAGE_COLON":"หน้า:",
"RESULTS":"{span}{0}-{1}{/span} จาก {2}",
"ITEMS":"{0} ไอเท็ม",
/* Application names */
"ACTIVITIES":"กิจกรรม",
"BLOGS":"บล็อก",
"CALENDAR":"ปฏิทิน",
"COMMUNITIES":"ชุมชน",
"BOOKMARKS":"บุ๊กมาร์ก",
"DOGEAR":"บุ๊กมาร์ก",
"EVENTS":"เหตุการณ์",
"FILES":"ไฟล์",
"FORUMS":"ฟอรัม",
"PROFILES":"โปรไฟล์",
"WIKI":"วิกิ",
"WIKIS":"วิกิ",
"FEEDS":"ฟีด",
"STATUS_UPDATES":"การอัพเดตสถานะ",
"ONECOMMENT":"1 ข้อคิดเห็น",
"COMMENTS":"{0} ข้อคิดเห็น",
"ONEPERSON":"1 คน",
"PEOPLE":"{0} คน",
"TAGS":"แท็ก:",
"TAGSMORE":"และ {0} มากกว่า",
"NORESULTSMESSAGE":"ไม่พบผลลัพธ์สำหรับการค้นหานั้น",
"JAN":"มกราคม",
"FEB":"กุมภาพันธ์",
"MAR":"มีนาคม",
"APR":"เมษายน",
"MAY":"พฤษภาคม",
"JUN":"มิถุนายน",
"JUL":"กรกฎาคม",
"AUG":"สิงหาคม",
"SEP":"กันยายน",
"OCT":"ตุลาคม",
"NOV":"พฤศจิกายน",
"DEC":"ธันวาคม",
"NO_CONTACT":"ไม่มีการค้นหา เนื่องจากไม่สามารถติดต่อเซิร์ฟเวอร์",
"SERVER_ERROR":"ไม่มีการค้นหา เนื่องจากเซิร์ฟเวอร์มีข้อผิดพลาด",
"SORT_BY":"เรียงลำดับตาม:",
"SORT_RELEVANCE":"ระดับความสัมพันธ์",
"SORT_DATE":"วันที่",
"SORT_LAST_UPDATED":"อัพเดตล่าสุด",
"SORT_DUE_DATE":"วันที่ครบกำหนด",
"SORT_VISITS":"การเยี่ยมชม",
"SORT_COMMENTS":"ความคิดเห็น",
"SORT_RECOMMENDATION":"ชอบ",
"SORT_POPULARITY":"ความนิยม",
"SORT_FIRSTNAME":"ชื่อ",
"SORT_LASTNAME":"นามสกุล",
"SORT_DOWNLOADS":"ดาวน์โหลด",
"SORT_TYPE":"ประเภท",
"SORT_SIZE":"ขนาด",
"SORT_TITLE":"คำนำหน้าชื่อ",
"PRIVATE":"ไพรเวต",
"MODERATED":"ควบคุม",
"COMMUNITY_ACTIVITY":"กิจกรรมชุมชน",
"COMMUNITY_BLOG":"บล็อกชุมชน",
"COMMUNITY_FILE":"ไฟล์ชุมชน",
"COMMUNITY_FORUM":"ฟอรัมชุมชน",
"COMMUNITY_WIKI":"วิกิชุมชน",
"COMMUNITY_FEED":"ฟีดชุมชน",
"COMMUNITY_BOOKMARK":"บุ๊กมาร์กชุมชน",
"NO_TAG":"ยังไม่มีแท็ก",
"NO_DATE":"ยังไม่มีวันที่",
"NO_PEOPLE":"ยังไม่มีบุคคล",
"REMOVE_FILTER_LABEL":"คลิกเพื่อลบ",
"REMOVE_FILTER_TITLE":"ลบ",
"REMOVE_FILTER_TOOLTIP":"ลบตัวกรองนี้",
"COMMENT_ON":"ข้อคิดเห็นเกี่ยวกับ:",
"EXPAND_COLLAPSE":"คลิกเพื่อขยาย / ยุบ",
"EXPAND":"ขยาย",
"COLLAPSE":"ยุบ",
"EXPAND_MONTHS_FILTER":"ขยายตัวกรองเดือนของปี {0}",
"SORT_RELEVANCE_LABEL":"คลิกเพื่อเรียงลำดับตามระดับความเกี่ยวข้อง",
"SORT_DATE_LABEL":"คลิกเพื่อเรียงลำดับตามวันที่",
"SORT_UPDATED_LABEL":"คลิกเพื่อเรียงลำดับตามการอัพเดตล่าสุด",
"SORT_DUE_LABEL":"คลิกเพื่อเรียงลำดับตามวันที่ครบกำหนด",
"SORT_VISITS_LABEL":"คลิกเพื่อเรียงลำดับตามจำนวนการเข้าเยี่ยมชม",
"SORT_COMMENTS_LABEL":"คลิกเพื่อเรียงลำดับตามจำนวนข้อคิดเห็น",
"SORT_RECOMMENDATIONS_LABEL":"คลิกเพื่อเรียงลำดับตามตัวเลขของการชื่นชอบ",
"SORT_POPULARITY_LABEL":"คลิกเพื่อเรียงลำดับตามความนิยม",
"SORT_FIRST_NAME_LABEL":"คลิกเพื่อเรียงลำดับตามชื่อที่กำหนดไว้",
"SORT_LAST_NAME_LABEL":"คลิกเพื่อเรียงลำดับตามนามสกุล",
"RATING":"ชื่นชอบ",
"GRADUATED":"สำเร็จ",
"ONEVOTE":"1 โหวต",
"VOTES":"{0} โหวต",
"BOOKMARK_THIS_RESULT":"บุ๊กมาร์กนี้",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (ไม่แอ็คทีฟ)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} บุคคลที่ไม่ได้บุ๊กมาร์ก",
/* eg from an Activity */
"FROMANACTIVITY":"จากกิจกรรม",
"FROMABLOG":"จากบล็อก",
"FROMANIDEATIONBLOG":"จากบล็อกระดมความคิด",
"FROMANEVENT":"จากเหตุการณ์",
"FROMAFORUM":"จากฟอรัม",
"FROMAWIKI":"จากวิกิ",
"FROMACOMMUNITY":"จากชุมชน",
"FROMXCOMMUNITIES":"จาก {0} ชุมชน",
/* For search results parentage */
"ACTIVITY_ALONE":"กิจกรรม",
"BLOG_ALONE":"บล็อก",
"IDEATIONBLOG_ALONE":"บล็อกระดมความคิด",
"ENTRY_ALONE":"รายการ",
"EVENT_ALONE":"เหตุการณ์",
"FORUM_ALONE":"ฟอรัม",
"WIKI_ALONE":"วิกิ",
"COMMUNITY_ALONE":"ชุมชน",
"XCOMMUNITIES_ALONE":"{0} ชุมชน",
"SHAREDCOMMUNITIES":"แบ่งใช้กับชุมชนเหล่านี้",
"INACOMMUNITY":"ในชุมชน",
"LASTUPDATED":"ค้นหาดัชนีที่อัพเดตล่าสุด:",
"NODESCRIPTION":"ไม่มีรายละเอียดหรือข้อมูลสรุปสำหรับผลลัพธ์สำหรับ",
"ATTACHMENT":"สิ่งที่แนบ:",
"ACTIVITY":"กิจกรรม:",
"ACTIVITYBOOKMARK":"บุ๊กมาร์กกิจกรรม:",
"ACTIVITYCOMMENT":"ข้อคิดเห็นกิจกรรม:",
"ACTIVITYENTRY":"รายการกิจกรรม:",
"ACTIVITYSECTION":"ส่วนกิจกรรม:",
"ACTIVITYTODO":"สิ่งที่ต้องทำของกิจกรรม:",
"BLOG":"บล็อก:",
"BLOGENTRY":"รายการบล็อก:",
"BLOGCOMMENT":"ข้อคิดเห็นบล็อก:",
"BOOKMARK":"บุ๊กมาร์ก:",
"CALENDAREVENT":"เหตุการณ์:",
"CATEGORY":"หมวดหมู่:",
"COMMENT":"ข้อคิดเห็น:",
"COMMUNITY":"ชุมชน:",
"ENTRY":"รายการ:",
"EVENTDATEON":"บน: {0}",
"EVENTISALLDAY":"เหตุการณ์ตลอดวัน",
"EVENTREPEATS":"ทำซ้ำ",
"FEED":"ฟีด:",
"FILE":"ไฟล์:",
"FORUM":"ฟอรัม:",
"FORUMCATEGORY":"หมวดหมู่ฟอรัม:",
"FORUMTOPIC":"หัวข้อฟอรัม:",
"IDEA":"แนวคิด:",
"IDEACOMMENT":"ข้อคิดเห็นแนวคิด:",
"IDEATIONBLOG":"บล็อกระดมความคิด:",
"PAGE":"หน้า:",
"PROFILE":"โปรไฟล์:",
"SECTION":"ส่วน:",
"STATUSUPDATE":"อัพเดตสถานะ",
"STATUSUPDATE_PREFIX":"อัพเดตสถานะ:",
"TOPIC":"หัวเรื่อง:",
"TOPIC_WITH_ATTACHMENT":"หัวข้อ",
"WIKITYPE":"วิกิ:",
"WIKIPAGE":"เพจวิกิ:",
"WIKIFILE":"สิ่งที่แนบของวิกิ:",
"SEARCH":"ค้นหา:",
"TODO":"สิ่งที่ต้องทำ:",
"ALLRESULTS":"ผลลัพธ์ทั้งหมด",
"PUBLICCONTENT":"เนื้อหาพับลิก",
"MYCONTENT":"เนื้อหาของฉัน",
"RESULTNOTFOUND":"ไม่พบสิ่งที่คุณกำลังค้นหาหรือ?",
"TEMPDIFFICULTIES":"หมายเหตุ: เนื่องจากความยากในการสร้างดัชนีชั่วคราว การค้นหาของคุณจึงไม่ได้รวม {0} ที่มีการเปลี่ยนแปลงใน {1} วันล่าสุด",
"TRYLATER":"โปรดลองอีกครั้งในภายหลัง",
"MULTIPLETEMPDIFFICULTIES":"หมายเหตุ: เนื่องจากความยากในการสร้างดัชนีชั่วคราว การค้นหาของคุณไม่ได้รวม {0} ที่มีการเปลี่ยนแปลงเมื่อเร็วๆ นี้",
"YOUAREAUTHOR":"คุณคือผู้เขียน",
"YOUARECONTRIBUTOR":"คุณคือผู้สนับสนุน",
"YOUAREOWNER":"คุณเป็นเจ้าของ",
"YOUAREMEMBER":"คุณเป็นสมาชิก",
/* Profiles */
"MYNETWORK":"เครือข่ายของฉัน",
"ALLPEOPLE":"บุคคลทั้งหมด",
"EXCLUDEINACTIVE":"ไม่รวมบุคคลที่ไม่แอ็คทีฟ",
"PHONE":"โทรศัพท์:",
"EMAIL":"อีเมล:",
/* Communities */
"ALLCOMMUNITIES":"ชุมชนทั้งหมด",
"PUBLICCOMMUNITIES":"ชุมชนพับลิก",
"MYCOMMUNITIES":"ชุมชนของฉัน",
"EVERYTHINGCOMMUNITIES":"ทุกอย่างจากชุมชน",
"COMMUNITIESONLY":"ชุมชน",
"COMMUNITIESCONTENT":"เนื้อหาจากชุมชน",
/* Activities */
"ALLACTIVITIES":"กิจกรรมทั้งหมด",
"PUBLICACTIVITIES":"กิจกรรมแบบพับลิก",
"MYACTIVITIES":"กิจกรรมของฉัน",
"EVERYTHINGACTIVITIES":"ทั้งหมดจากกิจกรรม",
"ACTIVITIESONLY":"กิจกรรม",
"SECTIONSACTIVITIES": "ส่วนจากกิจกรรม",
"ENTRIESACTIVITIES":"รายการจากกิจกรรม",
"TODOSACTIVITIES":"สิ่งที่ต้องทำจากกิจกรรม",
"BOOKMARKSACTIVITIES":"บุ๊กมาร์กจากกิจกรรม",
"FILESACTIVITIES":"สิ่งที่แนบจากกิจกรรม",
"ALLTYPESACTIVITIES":"ประเภททั้งหมดของกิจกรรม",
"COMMUNITYACTIVITIES":"กิจกรรมจากชุมชน",
"STANDALONEACTIVITIES":"กิจกรรมสแตนด์อะโลน",
/* Forums */
"ALLFORUMS":"ฟอรัมทั้งหมด",
"PUBLICFORUMS":"ฟอรัมพับลิก",
"MYFORUMS":"ฟอรัมของฉัน",
"EVERYTHINGFORUMS":"ทั้งหมดจากฟอรัม",
"FORUMSONLY":"ฟอรัม",
"TOPICSFORUMS":"หัวข้อฟอรัม",
"FORUMCATEGORIES": "หมวดหมู่ฟอรัม",
"FILESFORUMS":"สิ่งที่แนบจากฟอรัม",
"ALLTYPESFORUMS":"ประเภททั้งหมดของฟอรัม",
"COMMUNITYFORUMS":"ฟอรัมจากชุมชน",
"STANDALONEFORUMS":"ฟอรัมสแตนด์อะโลน",
/* Blogs */
"ALLBLOGS":"บล็อกทั้งหมด",
"PUBLICBLOGS":"บล็อกพับลิก",
"MYBLOGS":"บล็อกของฉัน",
"EVERYTHINGBLOGS":"ทุกอย่างจากบล็อก",
"BLOGSONLY":"บล็อก",
"ENTRIESBLOGS":"รายการบล็อก",
"FILESBLOGS":"สิ่งที่แนบจากบล็อก",
"EVERYTHINGIDEATIONBLOGS":"ทุกอย่างจากบล็อกระดมความคิด",
"BLOGSIDEATIONBLOGS":"บล็อกระดมความคิด",
"BLOGSIDEAS":"แนวคิด",
"ALLTYPESBLOGS":"ประเภททั้งหมดของบล็อก",
"COMMUNITYBLOGS":"บล็อกจากชุมชน",
"COMMUNITYIDEATIONBLOGS":"บล็อกระดมความคิดจากชุมชน",
"STANDALONEBLOGS":"บล็อกสแตนด์อะโลน",
/* Bookmarks */
"ALLBOOKMARKS":"บุ๊กมาร์กทั้งหมด",
"PUBLICBOOKMARKS":"บุ๊กมาร์กพับลิก",
"MYBOOKMARKS":"บุ๊กมาร์กของฉัน",
"ALLTYPESBOOKMARKS":"ประเภททั้งหมดของบุ๊กมาร์ก",
"COMMUNITYBOOKMARKS":"บุ๊กมาร์กจากชุมชน",
"STANDALONEBOOKMARKS":"บุ๊กมาร์กสแตนด์อะโลน",
/* Files */
"ALLFILES":"ไฟล์ทั้งหมด",
"PUBLICFILES":"ไฟล์พับลิก",
"MYFILES":"ไฟล์ของฉัน",
"ALLTYPESFILES":"ประเภททั้งหมดของไฟล์",
"COMMUNITYFILES":"ไฟล์จากชุมชน",
"STANDALONEFILES":"สแตนด์อะโลนไฟล์",
"NUMDOWNLOADS":"{0} ดาวน์โหลด",
/* Wikis */
"ALLWIKIS":"วิกิทั้งหมด",
"PUBLICWIKIS":"วิกิพับลิก",
"MYWIKIS":"วิกิของฉัน",
"EVERYTHINGWIKIS":"ทุกอย่างจากวิกิ",
"WIKISONLY":"วิกิ",
"PAGESWIKIS":"หน้าวิกิ",
"FILESWIKIS":"สิ่งที่แนบจากวิกิ",
"ALLTYPESWIKIS":"ประเภททั้งหมดของวิกิ",
"COMMUNITYWIKIS":"วิกิจากชุมชน",
"STANDALONEWIKIS":"วิกิสแตนด์อะโลน",
/* Status Updates */
"ALLSTATUSUPDATES":"การอัพเดตสถานะทั้งหมด",
"PUBLICSTATUSUPDATES":"อัพเดตสถานะพับลิก",
"MYSTATUSUPDATES":"การอัพเดตสถานของฉัน",
"ALLTYPESSTATUSUPDATES":"ชนิดการอัพเดตสถานะทั้งหมด",
"COMMUNITYSTATUSUPDATES":"การอัพเดตสถานะสำหรับชุมชน",
"STANDALONESTATUSUPDATES":"การอัพเดตสถานะจากโปรไฟล์",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"URL นี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"BOOKMARKEDCOMMUNITY":"ชุมชนนี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"BOOKMARKEDPROFILE":"โปรไฟล์นี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"BOOKMARKEDBLOG":"บล็อกนี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"COMMUNITYBLOG":"นี่คือบล็อกภายในชุมชน",
"BOOKMARKEDACTIVITY":"กิจกรรมนี้ถูกบุ๊กมาร์กตามจำนวนผู้ใช้",
"COMMUNITYACTIVITY":"นี่คือกิจกรรมภายในชุมชน",
"BOOKMARKEDFILE":"ไฟล์นี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"COMMUNITYFILE":"นี่คือไฟล์ภายในชุมชน",
"BOOKMARKED":"วิกินี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"COMMUNITYWIKI":"นี่คือวิกิภายในชุมชน",
"BOOKMARKEDFORUM":"ฟอรัมนี้ถูกบุ๊กมาร์กโดยผู้ใช้จำนวนหนึ่ง",
"COMMUNITYFORUM":"นี่คือฟอรัมภายในชุมชน",
"ALLTAGANDTTILE":"เมื่อต้องการดูหัวเรื่อง และแท็กทั้งหมดสำหรับ URL นี้ให้คลิกปุ่มนี้",
"TAGS_ARE_FROM":"ผลลัพธ์การค้นหานี้อาจรวมแท็กจาก:",
"BOOKMARKS_TITLE":"บุีกมาร์ก",
"COMMUNITIES_TITLE":"ชุมชน",
"ACTIVITIES_TITLE":"กิจกรรม",
"HELP":"วิธีใช้",
"MORESTATUSUPDATES":"ดูการจับคู่การอัพเดตสถานะเพิ่มเติม",
"TITLE_PREFIX":"หัวเรื่อง:",
"LATEST_MESSAGE":"ข้อความล่าสุด",
"LATEST_STATUS_UPDATE":"อัพเดตสถานะล่าสุด",
"LATEST_COMMUNITY_STATUS_UPDATE":"อัพเดตสถานะชุมชนล่าสุด",
"LATEST_COMMUNITIES_STATUS_UPDATE":"อัพเดตสถานะชุมชนล่าสุด",
"SEARCH_RESULTS":"ผลลัพธ์การค้นหาเนื้อหาทั้งหมด",
"ACTIVITIES_SEARCH_RESULTS":"ผลลัพธ์การค้นหาของกิจกรรม",
"BLOGS_SEARCH_RESULTS":"ผลลัพธ์การค้นหาบล็อก",
"BOOKMARKS_SEARCH_RESULTS":"ผลลัพธ์การค้นหาบุ๊กมาร์ก",
"COMMUNITIES_SEARCH_RESULTS":"ผลลัพธ์การค้นหาชุมชน",
"FILES_SEARCH_RESULTS":"ผลลัพธ์การค้นหาไฟล์",
"FORUMS_SEARCH_RESULTS":"ผลลัพธ์การค้นหาฟอรัม",
"PROFILES_SEARCH_RESULTS":"ผลลัพธ์การค้นหาโปรไฟล์",
"DIRECTORY_SEARCH_RESULTS":"ผลลัพธ์การค้นหาไดเร็กทอรี ${orgName}",
"WIKIS_SEARCH_RESULTS":"ผลลัพธ์การค้นหาวิกิ",
"STATUS_UPDATES_SEARCH_RESULTS":"ผลลัพธ์การค้นหาอัพเดตสถานะ",
"VIEW_ALL":"{span}ดูทั้งหมด{/span} ({0})",
"MATCHING_ONE_OF":"การจับคู่หนึ่งใน:",
"MATCHING_ALL_OF":"การจับคู่ทั้งหมดของ:",
"MATCHING":"การจับคู่:",
"MATCHING_DOC_TYPE":"การจับคู่ชนิดเอกสาร:",
"BOOKMARK_HELP":"วิธีใช้บุ๊กมาร์ก",
"CLOSE_BOOKMARK_HELP":"ปิดวิธีใช้บุ๊กมาร์ก",
"DOCUMENT_TYPE_PREFIX":"ชนิดเอกสาร:",
"FILE_PREVIEW_ONLY":"(โหมดแสดงตัวอย่างเท่านั้น)"
})

