/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "ข้อมูลสำหรับโหนด: ",
	"INSTALLED": "การตรวจสอบเซอร์วิสที่ติดตั้งไว้",
	"RESUMETOKENS": "การตรวจสอบโทเคนการดำเนินการต่อ",
	"SEEDLISTS": "การตรวจสอบว่า seedlists พร้อมใช้งาน",
	"CALENDARS": "การตรวจสอบว่าปฏิทินตารางเวลาถูกกำหนดคอนฟิกไว้อย่างถูกต้อง",
	"VARIABLES": "การตรวจสอบว่าตัวแปร WebSphere มีการตั้งค่า",
	"TASKS": "ตรวจสอบภารกิจการจัดทำดัชนีที่เปิดใช้งาน",
	"INDEXFILES": "การตรวจสอบโฟลเดอร์ดัชนีสำหรับไฟล์ที่จำเป็น",
	"LOGS": "การตรวจสอบไฟล์บันทึกสำหรับข้อผิดพลาด",
	"CONFIGFILES": "การตรวจสอบไฟล์คอนฟิกูเรชัน",
	"DICTIONARIES": "การตรวจสอบจำนวนพจนานุกรมที่เปิดใช้งาน",
	"SYNC": "การตรวจสอบสถานะของโหนด",
	"DBRECORDS": "การตรวจสอบระเบียนฐานข้อมูล",
	"INSTALLEDMSG": "เซอร์วิสต่อไปนี้ถูกติดตั้ง: ",
	"RESUMETOKENSMSG": "โทเคนเริ่มต้นใหม่สำหรับ: ",
	"SEEDLISTSMSG": "ไม่สามารถรับ seedlist สำหรับ: ",
	"CALENDARSMSG": "ปฏิทินตารางเวลาที่ผ่านการตรวจสอบแล้ว: ",
	"VARIABLESMSG": "ตัวแปร: ",
	"TASKSMSG": "ภารกิจต่อไปนี้ถูกเปิดใช้: ",
	"INDEXFILESMSG" : "ไฟล์ต่อไปนี้อยู่ในโฟลเดอร์ดัชนีการค้นหา: ",
	"LOGSMSG" : "ตรวจสอบข้อความแสดงข้อผิดพลาดต่อไปนี้: ",
	"CONFIGFILESMSG" : "พบไฟล์คอนฟิกูเรชันต่อไปนี้: ",
	"DICTIONARIESMSG" : "จำนวนพจนานุกรมที่เปิดใช้คือ: ",
	"INSYNC": "โหนดทั้งหมดอยู่ระหว่างการซิงค์",
	"OUTOFSYNC": "จำนวนโหนดที่ไม่ได้ซิงค์คือ: ",
	"NOTBLOCKED": "ไม่มีโหนดที่ถูกบล็อก",
	"BLOCKED": "จำนวนของโหนดที่ถูกบล็อกคือ: ",
	"INDATE": "โหนดทั้งหมดยังใช้งานได้",
	"OUTOFDATE": "จำนวนของโหนดที่หมดอายุคือ: ",
	"NUMOFDOCS": "จำนวนเอกสารในฐานข้อมูลคือ ",
	"FILESTOCONVERT": "จำนวนของเอกสารไฟล์ที่ต้องการแปลง คือ ",
	"CONVERTEDFILES": "จำนวนไฟล์ที่ถูกแปลงคือ ",
	"TOTALFILES": "จำนวนไฟล์ทั้งหมดในฐานข้อมูล ",
	"ERROR":"ข้อผิดพลาด",
	"ERROR_PREFIX":"ข้อผิดพลาด:",
	"INFO":"ข้อมูล",
	"INFO_PREFIX":"ข้อมูล:",
	"WARNING":"คำเตือน",
	"WARNING_PREFIX":"การเตือน:",
	"LOADING_MESSAGE": "การโหลด",
	"SERVER_STATUS": "สถานะเซิร์ฟเวอร์",
	"INITIAL_INDEXING_EXCEPTIONS": "Initial Indexing Exceptions",
	"SYS_OUT_EXCEPTIONS": "SystemOut Log Exceptions",
	"SEEDLIST_VALIDATE": "Seedlists Validation",
	"ERRORS_DURING_INITIAL_INDEXING":"ข้อยกเว้นต่อไปนี้เกิดขึ้นขณะสร้างดัชนีเริ่มต้น",
	"CRAWL_FAILED": "ข้อมูลทั้งหมดสำหรับเซอร์วิสต่อไปนี้ไม่สามารถ crawl ได้: ",
	"EXCEPTION_ENCOUNTERED": "การ crawl ล้มเหลวโดยมีข้อความต่อไปนี้: ",
	"SAND_VALIDATE": "SAND Validation",
	"CHECK_FOR_SAND_FILES":"กำลังตรวจสอบไฟล์ SAND",
	"IS_FILE_AVAILABLE":"การตรวจสอบว่าไฟล์ถูกสร้างหรือไม่: ",
	"ERRORS_DURING_INITIAL_INDEXING":"ข้อยกเว้นต่อไปนี้เกิดขึ้นขณะสร้างดัชนีเริ่มต้น",
	"CRAWL_FAILED":"ข้อมูลทั้งหมดสำหรับเซอร์วิสต่อไปนี้ไม่สามารถ crawl ได้: ",
	"EXCEPTION_ENCOUNTERED":"การ crawl ล้มเหลวโดยมีข้อความต่อไปนี้: "
})

