/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klik her for at se visitkort",
	"label.semtag.hover.alt" : "Klik for at se visitkort for {0}",
	"label.semtag.hover.altA11Y" : "Klik her eller tryk på control-enter for at se visitkortet",
	"label.personcard.dialog.title" : "Visitkort til {0}",

	"errorDefaultMsg2" : "Der er opstået en fejl. Kontakt systemadministratoren.",

	"loadingSTStatus" : "Indlæser Sametime-status...",
	"noStatuAvailable" : "Ingen Sametime-status tilgængelig",

	"label.personcard.cardnomarkup" : "Visitkortet kan ikke hentes",
	"label.inactive.user.msg" : "Denne person er ikke længere aktiv bruger.",
	"label.message.information" : "Information:",
	"label.personcard.noprofilemsg" : "Der er ingen profil for denne person.",
	"label.personcard.cardreqexpired" : "Forespørgslen om at hente visitkortet udløb",

	"label.bizcard.applinks.less" : "Vis mindre",
	"label.bizcard.applinks.more" : "Vis mere",

	"label.personcard.activitieslink" : "Aktiviteter",
	"label.personcard.activitieslink.title" : "Klik her for at se delte aktiviteter.",
	"label.personcard.blogslink" : "Blogge",
	"label.personcard.blogslink.title" : "Klik her for at se denne persons blog",
	"label.personcard.communitieslink" : "Fællesskaber",
	"label.personcard.communitieslink.title" : "Klik her for at se denne persons fællesskaber",
	"label.personcard.dogearlink" : "Bogmærker",
	"label.personcard.dogearlink.title" : "Klik her for at tilføje denne side som bogmærke",
	"label.personcard.fileslink" : "Filer",
	"label.personcard.fileslink.title" : "Klik her for at se denne persons delte filer.",
	"label.personcard.forumlink" : "Forummer",
	"label.personcard.forumlink.title" : "Klik her for at se denne persons forumindlæg.",
	"label.personcard.homepagelink" : "Hjem",
	"label.personcard.homepagelink.title" : "Klik her for at se denne persons hjemmeside.",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Klik her for at se denne persons mobilside.",
	"label.personcard.newslink" : "Nyheder",
	"label.personcard.newslink.title" : "Klik her for at se denne persons nyheder.",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klik her for at se denne persons profil.",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klik her for at se denne persons Quickr-deling.",
	"label.personcard.wikislink" : "Wikier",
	"label.personcard.wikislink.title" : "Klik her for at se denne persons wikier.",

	"personCardMoreActions" : "Flere handlinger",
	"personCardMoreActionsAltText" : "Klik for handlinger menu",

	"label.bizcard.dismiss": "Tryk på Esc for at afvise visitkortet.",
	"label.bizcard.fullProfile": "Fuld profil",
	"label.bizcard.activities": "Aktiviteter",
	"label.bizcard.communities": "Fællesskaber",
	"label.bizcard.files": "Filer",
	"label.bizcard.forums": "Forummer",
	"label.bizcard.bookmarks": "Bogmærker",
	"label.bizcard.blogs": "Blogge",
	"label.bizcard.wikis": "Wikier",

	"personCardAddAsColleagues" : "Invitér til mit netværk",
	"personCardAddAsMyColleagues" : "Invitér til mit netværk",
	"personCardFollow" : "Følg",
	"personCardUnfollow" : "Hold op med at følge",
	"personCardChat" : "Chat",
	"personCardCall" : "Opkald",
	"personCardSendMail" : "Send e-mail",
	"personCardSendEMail" : "Send e-mail",
	"personCardProxyStatusAvailable" : "Jeg er til stede",
	"personCardDownloadVCard" : "Download vCard",

	"friends" : "Netværk",
	"friendsFullPageTitle" : "Netværk",
	"friendsMenuTitleAllContacts" : "Alle netværkskontakter",
	"friendsMenuTitleMyContacts" : "Mine netværkskontakter",
	"friendsInvitations" : "Invitationer",
	"friendsMenuTitleInCommon" : "Fælles personer",
	"friendsShowAllCommonFriends" : "Vis alle...",
	"friendsViewAllFriends" : "Vis alle ({0})",
	"friendsSendFriendRequest" : "Sendt anmodning",
	"friendsNoFriends" : "Der er ikke knyttet nogen netværkskontakter til denne profil",
	"friendsColleaguesInvite" : "Invitér {0} til at være din netværkskontakt",
	"friendsColleaguesFor" : "Netværkskontakter for {0}",
	"friendsNewInv" : "{0} ny invitation",
	"friendsNewInvs" : "{0} nye invitationer",
	"friendsLoading" : "Indlæser netværk...",
	"friendsLoadingInv" : "Sender invitationer...",
	"friendsSelectFriendForRemoval" : "Vælg først de kontakter, du vil fjerne.",
	"friendsRemoved" : "Netværkskontakt(er) fjernet.",
	"friendsInvSent" : "Ingen invitation er sendt, da en invitation allerede venter.",
	"friendsRemovedSelected" : "Fjern fra mit netværk",
	"friendsSortByDisplayName" : "Vist navn",
	"friendsSortByRecent" : "Seneste",
	"friendsTelephone" : "Telefon",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "Alternativ e-mail:",
	"friendsNewInvitationsCount" : "Du har {0} nye invitationer",
	"friendsNoInv" : "Ingen invitationer",
	"friendsInCommonSingle" : "I har {0} netværkskontakt til fælles",
	"friendsInCommonMulti" : "I har {0} netværkskontakter til fælles",
	"friendsIncludeMsgForInv" : "Medtag en besked i din invitation:",
	"friendsInitialMsgForInv" : "Jeg vil gerne tilføje dig til min liste over Connections-netværkskontakter.",
	"friendsSendInvAction" : "Send invitation",
	"friendsCancelInvAction" : "Annullér",
	"friendsAcceptAction" : "Acceptér",
	"friendsIgnoreAction" : "Ignorér",
	"friendsYouExceedTextLimit" : "Beskeden med din invitation er for lang. Den må maksimalt være på {1} tegn. Der er {0} tegn i feltet.",
	"friendsCannotAddYourself" : "Du kan ikke tilføje dig selv som netværkskontakt.",
	"friendsIsYourColleague" : "{0} er din netværkskontakt",
	"friendsRecentlyAdded" : "Personer, du for nylig har tilføjet til dit netværk.",
	"friendsDate" : "Dato",
	"friendsCollapseWidget" : "Klik for at skjule sektionen",
	"friendsExpandWidget" : "Klik for at udvide netværksafsnittet",
	"friendsIsInYourNetwork" : "{0} person i dit netværk.",
	"friendsActionsFor" : "Handlinger for netværk",
	"friendsInviteFollowError" : "Der er opstået en fejl under forsøg på at finde klassefil {0}",
	"friendsInviteTagError" : "Der er opstået en fejl under forsøg på at oprette en hændelse {0}",
	"friendsPleaseLogIn" : "Log på for at invitere personer til dit netværk",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Det er ikke muligt at invitere til dit netværk, fordi {0} allerede er i dit netværk.",
	"friendsInviteAddTagsFor" : "Emneord for {0}:",
	"friendsInviteAlsoFollow" : "Følg også",
	"friendsInviteReceiveUpdates" : "(modtag opdateringer)",
	"friendsInviteUpdatesDescription" : "Få opdateringer på hjemmesiden og i et e-mailresumé om personer, du følger.",
	"friendsInviteFollowHelp": "Der er flere oplysninger i {0}Følg personer{1}.",
	"friendsNetwork" : "Netværk",
	"friendsMyNetwork" : "Netværk",
	"friendsNetworkFor" : "Netværk for {0}",
	"friendsRemoveSelected" : "Fjern vælger",
	"friendsRemoveSelectedTip" : "Klik for at fjerne de valgte personer fra dit netværk.",
	"friendsNetworkInCommon" : "I har {0} netværksforbindelser til fælles.",
	"friendsAddToMyNetwork" : "Jeg vil gerne tilføje dig til mit Connections-netværk.",
	"friendsInvite" : "Invitér til mit netværk",
	"friendsInvitePerson" : "Invitér {0} til dit netværk",
	"friendsInviteMessage" : "Jeg vil gerne tilføje dig til mit Connections-netværk.",
	"friendsInvitedEmailSubject" : "[Profiler] Du er inviteret til at deltage i mit netværk",
	"friendsInvitedEmailMsg1" : "har inviteret dig til at blive netværkskontakt. Invitationen indeholder følgende besked:",
	"friendsInvitedEmailMsg2" : "Åbn netværksinvitationssiden",
	"friendsInvitedEmailMsg3" : "Jeg vil gerne tilføje dig til mit netværk.",
	"friendsInvitedEmailMsg4" : "{0} inviterede dig til at blive netværkskontakt.",
	"friendsInvitedEmailMsg5" : "{0} har inviteret dig til at blive netværkskontakt. Invitationen indeholder følgende besked:",
	"friendsInviteLegalNote" : "Ved at sende denne invitation accepterer du, at {0} må kommentere din profiltavle.",
	"friendsInviteFailed" : "På grund af en serverfejl er der ikke sendt en e-mailnotifikation til den inviterede. Den inviterede vil dog stadig kunne acceptere din invitation via webapplikationen Profiler.",
	"personInNetwork" : "Netværkskontakt"
})
