/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klicka här för att visa visitkort",
	"label.semtag.hover.alt" : "Klicka för att visa visitkort för {0}",
	"label.semtag.hover.altA11Y" : "Klicka här eller tryck på ctrl+enter för att visa visitkortet",
	"label.personcard.dialog.title" : "Visitkort för {0}",

	"errorDefaultMsg2" : "Ett fel inträffade. Kontakta systemadministratören.",

	"loadingSTStatus" : "Läser in Sametime-status ...",
	"noStatuAvailable" : "Det finns ingen tillgänglig Sametime-status",

	"label.personcard.cardnomarkup" : "Det gick inte att hämta visitkortet",
	"label.inactive.user.msg" : "Den här personen är inte längre en aktiv användare",
	"label.message.information" : "Information:",
	"label.personcard.noprofilemsg" : "Det finns ingen profil för den här personen",
	"label.personcard.cardreqexpired" : "Begäran om att hämta visitkortet har upphört att gälla",

	"label.bizcard.applinks.less" : "Visa färre",
	"label.bizcard.applinks.more" : "Visa fler",

	"label.personcard.activitieslink" : "Aktiviteter",
	"label.personcard.activitieslink.title" : "Klicka här för att se delade aktiviteter",
	"label.personcard.blogslink" : "Bloggar",
	"label.personcard.blogslink.title" : "Klicka här för att se bloggen för den här personen",
	"label.personcard.communitieslink" : "Gemenskaper",
	"label.personcard.communitieslink.title" : "Klicka här för att se gemenskaperna för den här personen",
	"label.personcard.dogearlink" : "Bokmärken",
	"label.personcard.dogearlink.title" : "Klicka här för att se bokmärkena för den här personen",
	"label.personcard.fileslink" : "Filer",
	"label.personcard.fileslink.title" : "Klicka här för att se de delade filerna för den här personen",
	"label.personcard.forumlink" : "Forum",
	"label.personcard.forumlink.title" : "Klicka här för att se foruminläggen för den här personen.",
	"label.personcard.homepagelink" : "Hem",
	"label.personcard.homepagelink.title" : "Klicka här för att se hemsidan för den här personen",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Klicka här för att se den mobila sidan för den här personen.",
	"label.personcard.newslink" : "Nyheter",
	"label.personcard.newslink.title" : "Klicka här för att se nyheterna för den här personen.",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klicka här för att se profilen för den här personen.",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klicka här för att se Quickr-delningarna för den här personen.",
	"label.personcard.wikislink" : "Wikier",
	"label.personcard.wikislink.title" : "Klicka här för att se wikierna för den här personen.",

	"personCardMoreActions" : "Fler åtgärder",
	"personCardMoreActionsAltText" : "Klicka här för att öppna åtgärdsmenyn",

	"label.bizcard.dismiss": "Om du vill stänga visitkortet trycker du på Esc.",
	"label.bizcard.fullProfile": "Fullständig profil",
	"label.bizcard.activities": "Aktiviteter",
	"label.bizcard.communities": "Gemenskaper",
	"label.bizcard.files": "Filer",
	"label.bizcard.forums": "Forum",
	"label.bizcard.bookmarks": "Bokmärken",
	"label.bizcard.blogs": "Bloggar",
	"label.bizcard.wikis": "Wikier",

	"personCardAddAsColleagues" : "Bjud in till mitt nätverk",
	"personCardAddAsMyColleagues" : "Bjud in till mitt nätverk",
	"personCardFollow" : "Följ",
	"personCardUnfollow" : "Sluta följa",
	"personCardChat" : "Chatta",
	"personCardCall" : "Ring",
	"personCardSendMail" : "Skicka mejl",
	"personCardSendEMail" : "Skicka mejl",
	"personCardProxyStatusAvailable" : "Jag är tillgänglig",
	"personCardDownloadVCard" : "Ladda ned vCard-kort",

	"friends" : "Nätverk",
	"friendsFullPageTitle" : "Nätverk",
	"friendsMenuTitleAllContacts" : "Alla nätverkskontakter",
	"friendsMenuTitleMyContacts" : "Mina nätverkskontakter",
	"friendsInvitations" : "Inbjudningar",
	"friendsMenuTitleInCommon" : "Personer gemensamt",
	"friendsShowAllCommonFriends" : "Visa alla ...",
	"friendsViewAllFriends" : "Visa alla ({0})",
	"friendsSendFriendRequest" : "Skicka begäran",
	"friendsNoFriends" : "Det finns inga nätverkskontakter som är associerade med den här profilen",
	"friendsColleaguesInvite" : "Bjud in {0} som nätverkskontakt",
	"friendsColleaguesFor" : "Nätverkskontakter för {0}",
	"friendsNewInv" : "{0} ny inbjudan",
	"friendsNewInvs" : "{0} nya inbjudningar",
	"friendsLoading" : "Läser in nätverket ...",
	"friendsLoadingInv" : "Läser in inbjudningar ...",
	"friendsSelectFriendForRemoval" : "Markera de kontakter som du vill ta bort först.",
	"friendsRemoved" : "Nätverkskontakt(er) togs bort.",
	"friendsInvSent" : "Ingen inbjudan skickades eftersom det redan finns en väntande inbjudan.",
	"friendsRemovedSelected" : "Ta bort från mitt nätverk",
	"friendsSortByDisplayName" : "Visningsnamn",
	"friendsSortByRecent" : "Senaste",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "Mejladress:",
	"friendsAltEmail" : "Alternativ mejladress:",
	"friendsNewInvitationsCount" : "Du har {0} ny inbjudan/nya inbjudningar",
	"friendsNoInv" : "Inga inbjudningar",
	"friendsInCommonSingle" : "Ni har {0} gemensam nätverkskontakt",
	"friendsInCommonMulti" : "Ni har {0} gemensamma nätverkskontakter",
	"friendsIncludeMsgForInv" : "Inkludera ett meddelande i inbjudan:",
	"friendsInitialMsgForInv" : "Jag vill lägga till dig till min lista över Connections-nätverkskontakter.",
	"friendsSendInvAction" : "Skicka inbjudan",
	"friendsCancelInvAction" : "Avbryt",
	"friendsAcceptAction" : "Acceptera",
	"friendsIgnoreAction" : "Ignorera",
	"friendsYouExceedTextLimit" : "Ditt inbjudningsmeddelande är för långt. Det får vara högst {1} tecken. Det finns {0} tecken i fältet.",
	"friendsCannotAddYourself" : "Du kan inte lägga till dig själv som nätverkskontakt.",
	"friendsIsYourColleague" : "{0} är din nätverkskontakt",
	"friendsRecentlyAdded" : "Personer som du nyligen har lagt till i ditt nätverk.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Klicka här för att komprimera nätverksavsnittet",
	"friendsExpandWidget" : "Klicka här för att expandera nätverksavsnittet",
	"friendsIsInYourNetwork" : "{0} är i ditt nätverk",
	"friendsActionsFor" : "Åtgärder för Nätverk",
	"friendsInviteFollowError" : "Ett fel inträffade när du försökte följa {0}",
	"friendsInviteTagError" : "Ett fel inträffade när du försökte tagga {0}",
	"friendsPleaseLogIn" : "Om du vill bjuda in personer till ditt nätverk måste du logga in",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Det går inte att bjuda in {0} till ditt nätverk eftersom han/hon redan finns i det.",
	"friendsInviteAddTagsFor" : "Lägg till taggar för {0}:",
	"friendsInviteAlsoFollow" : "Följ också",
	"friendsInviteReceiveUpdates" : "(ta emot uppdateringar)",
	"friendsInviteUpdatesDescription" : "Du kan få uppdateringar om personer du följer på hemsidan och i en mejlsammanfattning.",
	"friendsInviteFollowHelp": "Om du vill ha mer information, se {0}Följa personer{1}.",
	"friendsNetwork" : "Nätverk",
	"friendsMyNetwork" : "Nätverk",
	"friendsNetworkFor" : "Nätverk för {0}",
	"friendsRemoveSelected" : "Ta bort markerade",
	"friendsRemoveSelectedTip" : "Klicka för att ta bort de markerade personerna från nätverket.",
	"friendsNetworkInCommon" : "Ni har {0} gemensamma nätverksanslutningar.",
	"friendsAddToMyNetwork" : "Jag vill lägga till dig till mitt Connections-nätverk.",
	"friendsInvite" : "Bjud in till mitt nätverk",
	"friendsInvitePerson" : "Bjud in {0} till ditt nätverk",
	"friendsInviteMessage" : "Jag vill lägga till dig till mitt Connections-nätverk.",
	"friendsInvitedEmailSubject" : "[Profiler] Du har fått en inbjudan om att delta i mitt nätverk",
	"friendsInvitedEmailMsg1" : "har bjudit in dig som nätverkskontakt, med följande meddelande i inbjudan:",
	"friendsInvitedEmailMsg2" : "Öppna din nätverksinbjudansida",
	"friendsInvitedEmailMsg3" : "Jag vill lägga till dig till mitt nätverk.",
	"friendsInvitedEmailMsg4" : "{0} har bjudit in dig som nätverkskontakt:",
	"friendsInvitedEmailMsg5" : "{0} har bjudit in dig som nätverkskontakt, med följande meddelande i inbjudan:",
	"friendsInviteLegalNote" : "Genom att skicka den här inbjudan godkänner du att {0} får kommentera din profilanslagstavla.",
	"friendsInviteFailed" : "Det uppstod ett serverfel. Det gick inte att skicka mejlet till den inbjudna personen, men han/hon kan använda Profiler i webbapplikationen för att acceptera din inbjudan.",
	"personInNetwork" : "Nätverkskontakt"
})
