/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Nodoarentzako informazioa: ",
		"INSTALLED": "Instalatutako zerbitzuak egiaztatzen",
		"RESUMETOKENS": "Laburpen-tokenak egiaztatzen",
		"SEEDLISTS": "Helbide elektronikoen seriea erabilgarri dagoela egiaztatzen",
		"CALENDARS": "Egutegiak ondo konfiguratuta daudela egiaztatzen",
		"VARIABLES": "WebSphere aldagaiak bidali direla egiaztatzen",
		"TASKS": "Gaitutako indexatze-zereginak egiaztatzen",
		"INDEXFILES": "Beharrezko fitxategien indize-karpeta egiaztatzen",
		"LOGS": "Erroreak topatzeko erregistroak berrikusten",
		"CONFIGFILES": "Konfigurazio-fitxategiak berrikusten",
		"DICTIONARIES": "Gaitutako hiztegi kopurua egiaztatzen",
		"SYNC": "Nodoen egoerak egiaztatzen",
		"DBRECORDS": "Datu-basearen erregistroak egiaztatzen",
		"INSTALLEDMSG": "Honako zerbitzu hau dago instalatuta: ",
		"RESUMETOKENSMSG": "Honen laburpen-tokena: ",
		"SEEDLISTSMSG": "Ezin izan da honen helbide elektronikoen seriea lortu: ",
		"CALENDARSMSG": "Egutegia egiaztatu da: ",
		"VARIABLESMSG": "Aldagaia: ",
		"TASKSMSG": "Honako zeregina dago gaituta: ",
		"INDEXFILESMSG" : "Honako fitxategi hauek daude bilaketa-indizearen karpetan: ",
		"LOGSMSG" : "Berrikusi honako errore-mezu hau: ",
		"CONFIGFILESMSG" : "Honako konfigurazio-fitxategi hauek aurkitu dira: ",
		"DICTIONARIESMSG" : "Hau da gaitutako hiztegi kopurua: ",
		"INSYNC": "Nodo guztiak sinkronizatuta daude",
		"OUTOFSYNC": "Hau da sinkronizatu gabeko nodo kopurua: ",
		"NOTBLOCKED": "Ez dago blokeatutako nodorik",
		"BLOCKED": "Hau da blokeatutako nodo kopurua: ",
		"INDATE": "Nodo guztiak eguneratuta daude",
		"OUTOFDATE": "Hau da zaharkitutako nodo kopurua: ",
		"NUMOFDOCS": "Hau da datu-baseko dokumentu kopurua: ",
		"FILESTOCONVERT": "Hau da bihurtu beharreko fitxategi kopurua: ",
		"CONVERTEDFILES": "Hau da bihurtutako fitxategi kopurua: ",
		"TOTALFILES": "Datu-baseko fitxategi kopuru osoa ",
		"ERROR":"Errorea",
		"ERROR_PREFIX":"Errorea:",
		"INFO":"Informazioa",
		"INFO_PREFIX":"Informazioa:",
		"WARNING":"Abisua",
		"WARNING_PREFIX":"Abisua:",
		"LOADING_MESSAGE": "Kargatzen",
		"SERVER_STATUS": "Zerbitzari-egoera",
		"INITIAL_INDEXING_EXCEPTIONS": "Hasierako indexatze-salbuespenak",
		"SYS_OUT_EXCEPTIONS": "SystemOut erregistro-salbuespenak",
		"SEEDLIST_VALIDATE": "Helbide elektronikoen serieen balidazioa",
		"ERRORS_DURING_INITIAL_INDEXING":"Honako salbuespen hauek gertatu dira hasierako indizea sortzean",
		"CRAWL_FAILED": "Ezin izan dira honako zerbitzu honen datu guztiak miatu: ",
		"EXCEPTION_ENCOUNTERED": "Miaketak honako mezu honekin huts egin du: ",
		"SAND_VALIDATE": "SAND balidazioa",
		"CHECK_FOR_SAND_FILES":"SAND fitxategiak egiaztatzen",
		"IS_FILE_AVAILABLE":"Fitxategia sortu dela egiaztatzen: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Honako salbuespen hauek gertatu dira hasierako indizea sortzean",
		"CRAWL_FAILED":"Ezin izan dira honako zerbitzu honen datu guztiak miatu: ",
		"EXCEPTION_ENCOUNTERED":"Miaketak honako mezu honekin huts egin du: "
});

