/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtra per:",
		"SHOW":"Mostra:",
		"ACL_FILTER_LABEL":"Filtra per visibilitat",
		"PARENT_FILTER_LABEL":"Filtra per contenidor",
		"TYPE_FILTER_LABEL":"Filtra per tipus",
		"PAGING_TOP":"Paginació principal",
		"PAGING_BOTTOM":"Paginació secundària",
		"PREVIOUS":"Anterior",
		"NEXT":"Següent",
		"PAGE":"Pàgina {0} de {1}",
		"PAGE_COLON":"Pàgina:",
		"RESULTS":"{span}{0}-{1}{/span} de {2}",
		"ITEMS":"{0} elements",
		/* Application names */
		"ACTIVITIES":"Activitats",
		"BLOGS":"Blocs",
		"CALENDAR":"Calendari",
		"COMMUNITIES":"Comunitats",
		"BOOKMARKS":"Adreces d'interès",
		"DOGEAR":"Adreces d'interès",
		"EVENTS":"Esdeveniments",
		"FILES":"Fitxers",
		"FORUMS":"Fòrums",
		"PROFILES":"Perfils",
		"WIKI":"Wikis",
		"WIKIS":"Wikis",
		"FEEDS":"Canals d'informació",
		"STATUS_UPDATES":"Actualitzacions d'estat",
		"ONECOMMENT":"1 comentari",
		"COMMENTS":"{0} comentaris",
		"ONEPERSON":"1 persona",
		"PEOPLE":"{0} persones",
		"TAGS":"Etiquetes:",
		"TAGSMORE":"i {0} més",
		"NORESULTSMESSAGE":"No s'ha trobat cap resultat per a aquesta cerca",
		"JAN":"Gener",
		"FEB":"Febrer",
		"MAR":"Març",
		"APR":"Abril",
		"MAY":"Mai",
		"JUN":"Jun",
		"JUL":"Jul",
		"AUG":"Agost",
		"SEP":"Setembre",
		"OCT":"Octubre",
		"NOV":"Novembre",
		"DEC":"Desembre",
		"NO_CONTACT":"La cerca no s'ha realitzat perquè no s'ha pogut contactar amb el servidor",
		"SERVER_ERROR":"La cerca no s'ha realitzat a causa d'un error del servidor",
		"SORT_BY":"Ordena per:",
		"SORT_RELEVANCE":"Rellevància",
		"SORT_DATE":"Data",
		"SORT_LAST_UPDATED":"Darrera actualització",
		"SORT_DUE_DATE":"Data de venciment",
		"SORT_VISITS":"Visites",
		"SORT_COMMENTS":"Comentaris",
		"SORT_RECOMMENDATION":"M'agrada",
		"SORT_POPULARITY":"Popularitat",
		"SORT_FIRSTNAME":"Nom",
		"SORT_LASTNAME":"Cognoms",
		"SORT_DOWNLOADS":"Descàrregues",
		"SORT_TYPE":"Tipus",
		"SORT_SIZE":"Mida",
		"SORT_TITLE":"Càrrec",
		"PRIVATE":"Privat",
		"MODERATED":"Moderat",
		"COMMUNITY_ACTIVITY":"Activitat de comunitat",
		"COMMUNITY_BLOG":"Bloc de comunitat",
		"COMMUNITY_FILE":"Fitxer de comunitat",
		"COMMUNITY_FORUM":"Fòrum de comunitat",
		"COMMUNITY_WIKI":"Wiki de comunitat",
		"COMMUNITY_FEED":"Canal d'informació de comunitat",
		"COMMUNITY_BOOKMARK":"Adreça d'interès de comunitat",
		"NO_TAG":"Encara no hi ha cap etiqueta",
		"NO_DATE":"Encara no hi ha cap data",
		"NO_PEOPLE":"Encara no hi ha ningú",
		"REMOVE_FILTER_LABEL":"Feu clic per eliminar",
		"REMOVE_FILTER_TITLE":"Elimina",
		"REMOVE_FILTER_TOOLTIP":"Elimina aquest filtre",
		"COMMENT_ON":"Comenteu sobre:",
		"EXPAND_COLLAPSE":"Feu clic per expandir / reduir",
		"EXPAND":"Expandeix",
		"COLLAPSE":"Redueix",
		"EXPAND_MONTHS_FILTER":"Expandeix el filtre dels mesos de l'any {0}",
		"SORT_RELEVANCE_LABEL":"Feu clic per ordenar per rellevància",
		"SORT_DATE_LABEL":"Feu clic per ordenar per data",
		"SORT_UPDATED_LABEL":"Feu clic per ordenar per darrera actualització",
		"SORT_DUE_LABEL":"Feu clic per ordenar per data de venciment",
		"SORT_VISITS_LABEL":"Feu clic per ordenar per nombre de visites",
		"SORT_COMMENTS_LABEL":"Feu clic per ordenar per nombre de comentaris",
		"SORT_RECOMMENDATIONS_LABEL":"Feu clic per ordenar per número de vegades que ha agradat",
		"SORT_POPULARITY_LABEL":"Feu clic per ordenar per popularitat",
		"SORT_FIRST_NAME_LABEL":"Feu clic per ordenar per nom",
		"SORT_LAST_NAME_LABEL":"Feu clic per ordenar per cognom",
		"RATING":"M'agrada",
		"GRADUATED":"Graduada",
		"ONEVOTE":"1 vot",
		"VOTES":"{0} vots",
		"BOOKMARK_THIS_RESULT":"Marqueu això com a adreça d'interès",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (inactiu)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} persones marcades com a adreça d'interès",
		/* eg from an Activity */
		"FROMANACTIVITY":"d'una activitat",
		"FROMABLOG":"d'un bloc",
		"FROMANIDEATIONBLOG":"d'un bloc d'idees",
		"FROMANEVENT":"des d'un esdeveniment",
		"FROMAFORUM":"d'un fòrum",
		"FROMAWIKI":"d'un wiki",
		"FROMACOMMUNITY":"d'una comunitat",
		"FROMXCOMMUNITIES":"de {0} comunitats",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Activitat",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog d'idees",
		"ENTRY_ALONE":"Entrada",
		"EVENT_ALONE":"Esdeveniment",
		"FORUM_ALONE":"Fòrum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Comunitat",
		"XCOMMUNITIES_ALONE":"{0} comunitats",
		"SHAREDCOMMUNITIES":"Compartit amb aquestes comunitats",
		"INACOMMUNITY":"en una comunitat",
		"LASTUPDATED":"L'índex de cerca es va actualitzar per darrera vegada:",
		"NODESCRIPTION":"Cap descripció o resum per a aquest resultat.",
		"ATTACHMENT":"Adjunció:",
		"ACTIVITY":"Activitat:",
		"ACTIVITYBOOKMARK":"Adreça d'interès d'activitat:",
		"ACTIVITYCOMMENT":"Comentari d'activitat:",
		"ACTIVITYENTRY":"Entrada d'activitat:",
		"ACTIVITYSECTION":"Secció d'activitat:",
		"ACTIVITYTODO":"Tasca pendent d'activitat:",
		"BLOG":"Bloc:",
		"BLOGENTRY":"Entrada de bloc:",
		"BLOGCOMMENT":"Comentari de bloc:",
		"BOOKMARK":"Adreça d'interès:",
		"CALENDAREVENT":"Esdeveniment:",
		"CATEGORY":"Categoria:",
		"COMMENT":"Comentari:",
		"COMMUNITY":"Comunitat:",
		"ENTRY":"Entrada:",
		"EVENTDATEON":"El: {0}",
		"EVENTISALLDAY":"Esdeveniment de tot el dia",
		"EVENTREPEATS":"Es repeteix",
		"FEED":"Canal d'informació:",
		"FILE":"Fitxer:",
		"FORUM":"Fòrum:",
		"FORUMCATEGORY":"Categoria del fòrum:",
		"FORUMTOPIC":"Tema del fòrum:",
		"IDEA":"Idea:",
		"IDEACOMMENT":"Comentari d'idea:",
		"IDEATIONBLOG":"Bloc d'idees:",
		"PAGE":"Pàgina:",
		"PROFILE":"Perfil:",
		"SECTION":"Secció:",
		"STATUSUPDATE":"Actualització d'estat",
		"STATUSUPDATE_PREFIX":"Actualització d'estat:",
		"TOPIC":"Tema:",
		"TOPIC_WITH_ATTACHMENT":"Tema",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Pàgina del wiki:",
		"WIKIFILE":"Fitxer adjunt del wiki:",
		"SEARCH":"Cerca:",
		"TODO":"Tasca:",
		"ALLRESULTS":"Tots els resultats",
		"PUBLICCONTENT":"Contingut públic",
		"MYCONTENT":"El meu contingut",
		"RESULTNOTFOUND":"No heu trobat el que cercàveu?",
		"TEMPDIFFICULTIES":"Nota: Per dificultats temporals d'indexació la vostra cerca no ha inclòs {0}, que s'ha(n) canviat en el(s) darrer(s) {1} dia(es).",
		"TRYLATER":"Torneu a intentar-ho més endavant.",
		"MULTIPLETEMPDIFFICULTIES":"Nota: Per dificultats d'indexació, la vostra cerca no ha inclòs {0} que s'ha canviat darrerament",
		"YOUAREAUTHOR":"Sou un autor",
		"YOUARECONTRIBUTOR":"Sou un col·laborador",
		"YOUAREOWNER":"Sou un propietari",
		"YOUAREMEMBER":"Sou un membre",
		/* Profiles */
		"MYNETWORK":"La meva xarxa",
		"ALLPEOPLE":"Totes les persones",
		"EXCLUDEINACTIVE":"Exclou persones inactives",
		"PHONE":"Telèfon:",
		"EMAIL":"Correu electrònic:",
		/* Communities */
		"ALLCOMMUNITIES":"Totes les comunitats",
		"PUBLICCOMMUNITIES":"Comunitats públiques",
		"MYCOMMUNITIES":"Les meves comunitats",
		"EVERYTHINGCOMMUNITIES":"Tot de les comunitats",
		"COMMUNITIESONLY":"Comunitats",
		"COMMUNITIESCONTENT":"Contingut de Comunitats",
		/* Activities */
		"ALLACTIVITIES":"Totes les activitats",
		"PUBLICACTIVITIES":"Activitats públiques",
		"MYACTIVITIES":"Les meves activitats",
		"EVERYTHINGACTIVITIES":"Tot d'Activitat",
		"ACTIVITIESONLY":"Activitats",
		"SECTIONSACTIVITIES": "Seccions d'Activitats",
		"ENTRIESACTIVITIES":"Entrades d'Activitats",
		"TODOSACTIVITIES":"Taques pendents d'Activitats",
		"BOOKMARKSACTIVITIES":"Adreces d'interès d'Activitats",
		"FILESACTIVITIES":"Fitxers adjunts d'Activitats",
		"ALLTYPESACTIVITIES":"Tots els tipus d'Activitats",
		"COMMUNITYACTIVITIES":"Activitats de Comunitats",
		"STANDALONEACTIVITIES":"Activitats autònomes",
		/* Forums */
		"ALLFORUMS":"Tots els fòrums",
		"PUBLICFORUMS":"Fòrums públics",
		"MYFORUMS":"Els meus fòrums",
		"EVERYTHINGFORUMS":"Tot de Fòrums",
		"FORUMSONLY":"Fòrums",
		"TOPICSFORUMS":"Temes de Fòrums",
		"FORUMCATEGORIES": "Categories de Fòrums",
		"FILESFORUMS":"Fitxer adjunts de Fòrums",
		"ALLTYPESFORUMS":"Tots els tipus de Fòrums",
		"COMMUNITYFORUMS":"Fòrums de Comunitats",
		"STANDALONEFORUMS":"Fòrums autònoms",
		/* Blogs */
		"ALLBLOGS":"Tots els blocs",
		"PUBLICBLOGS":"Blocs públics",
		"MYBLOGS":"Els meus blocs",
		"EVERYTHINGBLOGS":"Tot de Blocs",
		"BLOGSONLY":"Blogs",
		"ENTRIESBLOGS":"Entrades de Blocs",
		"FILESBLOGS":"Fitxers adjunts de Blocs",
		"EVERYTHINGIDEATIONBLOGS":"Tot dels blocs d'idees",
		"BLOGSIDEATIONBLOGS":"Blocs d'idees",
		"BLOGSIDEAS":"Idees",
		"ALLTYPESBLOGS":"Tots els tipus de Blocs",
		"COMMUNITYBLOGS":"Blocs de Comunitats",
		"COMMUNITYIDEATIONBLOGS":"Blocs d'idees de Comunitats",
		"STANDALONEBLOGS":"Blocs autònoms",
		/* Bookmarks */
		"ALLBOOKMARKS":"Totes les adreces d'interès",
		"PUBLICBOOKMARKS":"Adreces d'interès públiques",
		"MYBOOKMARKS":"Les meves adreces d'interès",
		"ALLTYPESBOOKMARKS":"Tots els tipus d'Adreces d'interès",
		"COMMUNITYBOOKMARKS":"Adreces d'interès de Comunitats",
		"STANDALONEBOOKMARKS":"Adreces d'interès autònomes",
		/* Files */
		"ALLFILES":"Tots els fitxers",
		"PUBLICFILES":"Fitxers públics",
		"MYFILES":"Els meus fitxers",
		"ALLTYPESFILES":"Tots els tipus de Fitxers",
		"COMMUNITYFILES":"Fitxers de Comunitats",
		"STANDALONEFILES":"Fitxers autònoms",
		"NUMDOWNLOADS":"{0} descarregades",
		/* Wikis */
		"ALLWIKIS":"Tots els wikis",
		"PUBLICWIKIS":"Wikis públics",
		"MYWIKIS":"Els meus wikis",
		"EVERYTHINGWIKIS":"Tot de Wikis",
		"WIKISONLY":"Wikis",
		"PAGESWIKIS":"Pàgines de Wikis",
		"FILESWIKIS":"Fitxers adjunts de Wikis",
		"ALLTYPESWIKIS":"Tots els tipus de Wikis",
		"COMMUNITYWIKIS":"Wikis de Comunitats",
		"STANDALONEWIKIS":"Wikis autònoms",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Totes les actualitzacions d'estat",
		"PUBLICSTATUSUPDATES":"Actualitzacions d'estat públiques",
		"MYSTATUSUPDATES":"Les meves actualitzacions d'estat",
		"ALLTYPESSTATUSUPDATES":"Tots els tipus d'actualitzacions d'estat",
		"COMMUNITYSTATUSUPDATES":"Actualitzacions d'estat de comunitats",
		"STANDALONESTATUSUPDATES":"Actualitzacions d'estat de perfils",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Diversos usuaris han marcat aquest URL com a adreça d'interès",
		"BOOKMARKEDCOMMUNITY":"Diversos usuaris han marcat aquesta comunitat com a adreça d'interès",
		"BOOKMARKEDPROFILE":"Diversos usuaris han marcat aquest perfil com a adreça d'interès",
		"BOOKMARKEDBLOG":"Diversos usuaris han marcat aquest bloc com a adreça d'interès",
		"COMMUNITYBLOG":"Aquest és un bloc d'una comunitat",
		"BOOKMARKEDACTIVITY":"Diversos usuaris han marcat aquesta activitat com a adreça d'interès",
		"COMMUNITYACTIVITY":"Aquesta és una activitat d'una comunitat",
		"BOOKMARKEDFILE":"Diversos usuaris han marcat aquest fitxer com a adreça d'interès",
		"COMMUNITYFILE":"Aquest és un fitxer d'una comunitat",
		"BOOKMARKED":"Diversos usuaris han marcat aquest wiki com a adreça d'interès",
		"COMMUNITYWIKI":"Aquest és un wiki d'una comunitat",
		"BOOKMARKEDFORUM":"Diversos usuaris han marcat aquest fòrum com a adreça d'interès",
		"COMMUNITYFORUM":"Aquest és un fòrum d'una comunitat",
		"ALLTAGANDTTILE":"Per veure tots els títols i etiquetes per a aquest URL, feu clic en aquest botó",
		"TAGS_ARE_FROM":"Aquest resultat de la cerca pot incloure etiquetes de:",
		"BOOKMARKS_TITLE":"Adreces d'interès",
		"COMMUNITIES_TITLE":"Comunitats",
		"ACTIVITIES_TITLE":"Activitats",
		"HELP":"Ajuda",
		"MORESTATUSUPDATES":"Veure més coincidències d'actualitzacions d'estat",
		"TITLE_PREFIX":"Títol:",
		"LATEST_MESSAGE":"Darrer missatge",
		"LATEST_STATUS_UPDATE":"Darrera actualització d'estat",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Darrera actualització d'estat de la comunitat",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Darrera actualització d'estat de les comunitats",
		"SEARCH_RESULTS":"Resultats de cerca de tot el contingut",
		"ACTIVITIES_SEARCH_RESULTS":"Resultats de cerca d'Activitats",
		"BLOGS_SEARCH_RESULTS":"Resultats de cerca de Blocs",
		"BOOKMARKS_SEARCH_RESULTS":"Resultats de cerca d'Adreces d'interès",
		"COMMUNITIES_SEARCH_RESULTS":"Resultats de cerca de Comunitats",
		"FILES_SEARCH_RESULTS":"Resultats de cerca de Fitxers",
		"FORUMS_SEARCH_RESULTS":"Resultats de cerca de Fòrums",
		"PROFILES_SEARCH_RESULTS":"Resultats de cerca de Perfils",
		"DIRECTORY_SEARCH_RESULTS":"Resultats de la cerca de directori de ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Resultats de cerca de Wikis",
		"STATUS_UPDATES_SEARCH_RESULTS":"Resultats de cerca d'actualitzacions d'estat",
		"VIEW_ALL":"{span}Visualitza-ho tot{/span} ({0})",
		"MATCHING_ONE_OF":"Coincideix un de:",
		"MATCHING_ALL_OF":"Coincideixen tots de:",
		"MATCHING":"Coincident:",
		"MATCHING_DOC_TYPE":"Tipus de document coincident:",
		"BOOKMARK_HELP":"Ajuda d'adreça d'interès",
		"CLOSE_BOOKMARK_HELP":"Tanca l'ajuda d'adreça d'interès",
		"DOCUMENT_TYPE_PREFIX":"Tipus de document:",
		"LAST_PAGE_MESSAGE": "Teniu molts resultats de cerca. Proveu de reduir la cerca afegint més termes de cerca.",
		"LAST_PAGE_SUBMESSAGE": "Obtindreu els primers {resultNumber} resultats rellevants."
});

