/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Du måste ange ett namn.",
	nourl: "Du måste ange en URL-adress.",
	fileSchema: "Om du vill lägga till en länk till en fjärrfil eller lokal fil måste den ha följande format: file://fjärrsökväg eller file:///lokal_sökväg.",
	invalidUrl: "Det här är inte en giltig gemenskaps-URL-adress.",
	invalidTagChar: "Den tagglista du har angett innehåller det ogiltiga tecknet \"&\". Du måste ta bort detta tecken från tagglistan.",
	txtHelp: "Hjälp",
	txtHelpTags: "Hjälp för taggar",
	txtHelpTagsClose: "Stäng hjälpen för taggar",
	tagsall: "Alla",
	tagsyours: "Dina",
	tagsrecent: "Senaste: ",
	tagspopular: "Populära: ",
	tagsrecommended: "Rekommenderade: ",
	nothingselected: "Du måste välja en gemenskap.",
	nothingselected_activity: "Du måste välja en aktivitet.",
	nothingselected_blogs: "Du måste välja en blogg.",
	nothingselected_all: "Du har inte valt någon tjänst eller post. Bokmärket kommer inte att sparas.",
	nothingFeedselected: "Du har inte valt någon tjänst eller post. Flödet kommer inte att sparas.",
	alertDialogTitle: "Meddelande",
	alertDialogOK: "OK",
	expand: "Klicka här om du vill expandera det här avsnittet",
	collapse: "Klicka här om du vill komprimera det här avsnittet",
	discussThis: "Diskutera det här",
	by: "av:",
	posted: "Skickades in:",
	attachments: "Bilagor",
	communityForum: "Gemenskapsforum",
	notCommunityPage: "Den aktuella webbsidan är inte en giltig gemenskapswebbsida. Om du vill skapa en relaterad gemenskap anger du namnet på, en länk till och en beskrivning av gemenskapen.",
	privateCommunityNotice: "Den här gemenskapen är begränsad. Den visas endast för medlemmarna av den.",
	forumNameHint : "Ange ett forumnamn",
	formDescriptionHint:"Ange varför den här relaterade gemenskapen skulle vara av intresse för din gemenskap.",
	information : "Information",
	error : "Fel",
	success : "Slutfördes",
	warning : "Varning",
	informationColon : "Information:",
	successColon : "Slutfördes:",
	warningColon : "Varning!",
	errorColon : "Fel:",
	feedAlreadyExist : "Flödet finns redan i gemenskapen.",
	bookmarkAlreadyExist : "Bokmärket finns redan i gemenskapen.",
	mentionAuthWarning:"Följande personer som du har nämnt kommer inte att kunna se meddelandet eftersom de inte är medlemmar av gemenskapen:",
	mentionAuthForumWarning:"Följande personer som du har nämnt kommer inte att kunna se meddelandet eftersom de inte har åtkomst till forumet:",
	exceedDescLength: "Beskrivningen är för lång.",
	communities_checked:"${0} gemenskaper har valts",
	activities_checked:"${0} aktiviteter har valts",
	blogs_checked:"${0} bloggar har valts"
})
