define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Lukk",
		   'rs_loading' : "Laster inn...",
		   'rs_at' : "klokken",
		   'rs_searchDirectory' : "Mangler noen på listen? Bruk fullstendig søk...",
		   'rs_searchGroupDirectory' : "Mangler en gruppe på listen? Bruk fullstendig søk...",
		   'rs_searchPersonAndGroupDirectory' : "Mangler en person eller gruppe på listen? Bruk fullstendig søk...",
		   'rs_searchCommunityDirectory' : "Mangler et fellesskap på listen? Bruk fullstendig søk...",
		   'rs_shadowText_searchDirectory' : "Skriv for å finne en person",
		   'rs_shadowText_searchGroupDirectory' : "Skriv for å finne en gruppe",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Skriv for å finne en person eller gruppe",
		   'rs_shadowText_searchCommunityDirectory' : "Skriv for å finne et fellesskap",
		   'rs_listItem' : "Listeoppføring",
		   'rs_noResults' : "Ingen resultater for '${0}'",
		   'rs_today' : "I dag",
		   'rs_tomorrow' : "I morgen",
		   'rs_yesterday' : "I går",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Kanal for disse aktivitetene",
		   'rs_externalText' : "Denne aktiviteten kan ha medlemmer utenfor din organisasjon.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" ble flyttet til underfellesskapet \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Vis mer informasjon om denne aktiviteten',
		   'rs_hideInfo' : 'Skjul tilleggsinformasjon',
		   'rs_more' : "Mer",
		   'rs_hide' : "Skjul",
		   'rs_edit' : "Rediger",
		   'rs_restore' : "Gjenopprett",
		   'rs_deleteEntry' : "Slett",
		   'rs_prioritize' : "Prioriter",
		   'rs_markComplete' : "Merk som fullført",
		   'rs_markIncomplete' : "Gjenopprett",
		   'rs_linkMore' : "... [mer]",
		   'rs_linkLess' : "... [mindre]",
		   'rs_actUpdatedByDate' : "Oppdatert av ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Oppdatert av ${0}",// Updated by (author name)
		   'rs_actDue' : "Frist ${0}",// Due (date)
		   'rs_actTags' : "Tagger: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Start aktivitet fra denne malen",
		   'rs_favoriteTemplate' : "Merk som favorittmal",
		   'rs_normalTemplate' : "Merk som normal mal",
		   'rs_tunedOutPri' : "Deaktivert",
		   'rs_pagepos' : "${0} - ${1} av ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Forrige",
		   'rs_navNextLabel' : "Neste",
		   'rs_noActivities' : "Ingen aktiviteter er startet for dette fellesskapet.",
		   'rs_feedError' : "Kunne ikke laste inn kanal.",
		   'rs_highPri' : "Høy prioritet",
		   'rs_medPri' : "Middels prioritet",
		   'rs_normalPri' : "Normal prioritet (standard)",
		   'rs_tuneOut' : "Merk som deaktivert",
		   'rs_startActivity' : "Start en aktivitet",
		   'rs_startFirstActivity' : "Opprett din første aktivitet",
		   'rs_navNextLabel' : "Neste",
		   'rs_viewAll' : "Vis alle",
		   'rs_activityWidgetTitle' : "Aktiviteter",
		   'rs_activityWidgetBriefDescription' : "Spor fellesskapsmål. Opprett huskelisteoppføringer og del ressurser.",
		   'rs_activityWidgetDescription' : "Fellesskapsaktiviteter kan brukes til å samarbeide og spore fremdriften i fellesskapsprosjekter eller initiativer.",
		   'rs_completedActivityLink' : "Vis fullførte aktiviteter",
		   'rs_activitiesUnavailable' : "Aktiviteter-tjenesten er ikke tilgjengelig.",
		   'rs_errorPersists' : "Hvis problemet vedvarer, kan du kontakte systemadministratoren.",
		   'rs_shared' : "Delt",
		   'rs_removeActFromComm' : "Fjern fra fellesskap",
		   'rs_externalLabel' : "Ekstern",
		   // for ActivityForm
		   'rs_templateOptions' : "Malalternativer",
		   'rs_template' : "Mal",
		   'rs_tagsLabel' : "Tagger",
		   'rs_peopleLabel' : "Personer",
		   'rs_aboutThisTemplate' : "Om denne malen",
		   'rs_activity' : "Aktivitet",
		   'rs_copyOf' : "Kopi av ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Aktivitetsmål",
		   'rs_noTemplate' : "Ingen",
		   'rs_copyActivityMembers' : "Bruk medlemmer fra aktivitet",
		   'rs_copyTemplateMembers' : "Bruk medlemmer fra mal",
		   /* Forum Widget */
		   'rs_noTopics' : "Det finnes ennå ingen emner for dette fellesskapet.",
		   'rs_noTopicsLoggedIn' : "Still et spørsmål, drodle eller del ideer.",
		   'rs_postedBy' : "Nyeste innlegg ved",
		   'rs_topics' : "emner",
		   'rs_noTopicsShort' : "Ingen emner",
		   'rs_topic' : "emne",
		   'rs_replies' : "svar",
		   'rs_noReplies' : "Ingen svar",
		   'rs_reply' : "svar",
		   'rs_startTopic' : "Start et emne",
		   'rs_startFirstTopic' : "Start første emne",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Låst]",
		   'rs_manageForumSetting' : "Administrer foruminnstillinger",
		   'rs_forumSettingCommunityOverviewPage' : "Oversiktsside for fellesskap:",
		   'rs_defaultForumList' : "Vis forumliste som standard",
		   'rs_defaultTopicList' : "Vis emneliste som standard",
		   'rs_forumSettingApplicationView' : "Standardvisning for forumapplikasjon:",
		   'rs_forumSettingNote' : "Merk: Emner blir vist som standard hvis det bare finnes ett forum.",
		   'rs_forumSettingSubmit' : "Send",
		   'rs_forumSettingSave' : "Lagre",
		   'rs_forumSettingSaveAndClose' : "Lagre og lukk",
		   'rs_forumSettingConfirm' : "Endringene dine for Fora er lagret.",
		   'rs_forumSettingError' : "Det oppstod en feil. Kontakt administratoren.",
		   'rs_formSettingHideMessage' : "Skjul denne meldingen",
		   'rs_forumSettingCancel' : "Avbryt",
		   'rs_forumAnsweredQuestion' : "Besvart spørsmål",
		   'rs_forumUnAnsweredQuestion' : "Ubesvarte spørsmål",
		   'rs_forumSortBy' : "Sorter etter:",
		   'rs_forumSortByDate' : "Dato",
		   'rs_forumSortByReplies' : "Svar",
		   'rs_forumSortByTopic' : "Emner",
		   'rs_forumSortByTopicsAndReplies' : "Emner og svar",
		   'rs_sortByReplies' : "Sorter etter svar",
		   'rs_sortbyTopicsAndReplies' : "Sorter etter emner og svar",
		   'rs_forumOpenQuestions' : "Åpne spørsmål",
		   'rs_feedOpenQuestions' : "Kanal for disse åpne spørsmålene",
		   'rs_feedAnsweredQuestions' : "Kanal for disse besvarte spørsmålene",
		   'rs_forumMessages' : "${0}meldinger",
		   'rs_forumLastAddedPost' : "Nyeste innlegg ved ${0}",
		   'rs_forumTopics' : "${0} emner",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Opprett personkobling",
		   'rs_quote' : "Sitat",
		   'rs_labelColon' : "Etikett: ",
		   'rs_personColon' : "Person: ",
		   'rs_personLink' : "Personkobling",
		   'rs_replace' : "Erstatt",
		   'rs_inactivePerson' : "${0} (inaktiv)", // person's name (inactive)
		   'rs_PersonPicture' : "${0}s bilde", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Ekstern bruker", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (ekstern bruker)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "${0}s bilde (ekstern bruker)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Denne brukeren har tilgang til filer og fellesskap som er delt eksternt.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Varsle andre personer",
		   'rs_messageColon' : "Melding: ",
		   'rs_notifyColon' : "Varsle: ",
		   'rs_notificationConfirm' : "Varslingsmeldingen er sendt. ",
		   'rs_notificationFail' : "Varslingsmeldingen ble ikke sendt. Prøv igjen senere og kontakt systemadministratoren hvis problemet vedvarer.",
		   'rs_pickCommunity' : "Velg fra fellesskapsliste",
		   'rs_typeName' : "Oppgi navn",
		   'rs_typeToFilter' : "Skriv for å filtrere denne listen",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Skriv for å filtrere denne listen",
		   'rs_filterGroupLabel' : "Velg gruppe",
		   'rs_noResults' : "Ingen resultater ble funnet",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Viser ${0} resultater av ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Fjern",
		   /* Language Selector */
		   'rs_browser_setting' : "Nettleserinnstilling",
		   'rs_customLangaugeLinkLabel' : "Tilpass språk",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Gå til side ${0} av ${1}",
		   "rs_jumpPageLabel" : "Gå til side",
		   'rs_pageNumLabel' : "Sidetall",
		   'rs_pageLabel' : "Side:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Tagger',
		   'rs_tagCloudToggleHint' : "Klikk for å skjule eller vise",
		   'rs_tagCloudHelpAlt' : "Få hjelp til tagger",
		   'rs_tagCloudNoTags' : "Ingen tagger ennå.",
		   'rs_tagCloudNoRecentTags' : "Ingen nye tagger",
		   'rs_tagCloudNoTagsProfiles' : "Søk i katalogen. Tagger knyttet til profilene som blir returnert av søket, vil bli vist her.",
		   'rs_tagLoadingTags' : "Laster inn innhold",
		   'rs_tagCloudSelectedTags' : "Valgte tagger",
		   'rs_tagCloudSeachDesc' : "Søk etter en tagg",
		   'rs_tagCloudSeach' : "Søk",
		   'rs_tagCloudRelatedTags' : "Beslektede tagger",
		   'rs_tagCloudRelatedTagsDescription' : "Legg til en beslektet tagg for å avgrense søket ytterligere",
		   'rs_tagCloudError' : 'Det oppstod en feil',
		   'rs_viewAsCloud' : "Sky",
		   'rs_viewAsCloudTitle' : "Vis tagger som en taggsky",
		   'rs_viewAsCloudDescription' : "Viser tagger som en taggsky",
		   'rs_viewAsList' : "Liste",
		   'rs_viewAsListTitle' : "Vis tagger som en sekvensiell liste med tagger",
		   'rs_viewAsListDescription' : "Viser tagger som en sekvensiell liste med tagger",
		   'rs_tagCloudViewAll' : "Bla gjennom",
		   'rs_tagCloudViewAllTitle' : "Bla gjennom alle tagger",
		   'rs_normalTags' : "Aktive tagger",
		   'rs_removeTag' : "Fjern taggen fra de valgte filtertaggene",
		   'rs_clearAll' : "Fjern alle",
		   'rs_searchInputDefault' : "Skriv for å finne en tagg",
		   'rs_searchInputTagSelected' : "Skriv en annen tagg",
		   'rs_relatedTagTitle' : "Vis søkeresultatet for tagg ${0}, antall ${1}",
		   'rs_removeTagTitle' : "Fjern taggen ${0} fra de valgte filtertaggene",
		   'rs_addTagTitle' : "Filtrer etter taggen ${0} med antall ${1}",
		   'rs_tagDialogCloseTile' : "Lukk",
		   'rs_tagDialogTitle' : "Alle tagger",
		   'rs_tagDialogPageInfo' : "${0} - ${1} av ${2} tagger",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Bla gjennom grupper",
		   'rs_group_browse_groups_dialog_title' : "Bla gjennom grupper",
		   'rs_group_browse_find_groups' : "Søk etter grupper",
		   'rs_group_browse_add_button' : "Legg til",
		   'rs_group_browse_cancel_button' : "Avbryt",
		   'rs_group_browse_enter_string' : "Skriv for å søke etter grupper",
		   'rs_group_browse_group_typeahead_label' : "Skriv et gruppenavn:",
		   'rs_group_browse_group_name' : "Gruppenavn:",
		   'rs_group_browse_results_label' : "Velg en samsvarende gruppe:",
		   'rs_group_browse_parent_group_label' : "Du er i:",
		   'rs_group_browse_next_page' : "Neste side",
		   'rs_group_browse_previous' : "Forrige",
		   'rs_group_browse_next' : "Neste",
		   'rs_group_browse_paging' : "Sideveksling",
		   'rs_group_browse_previous_page' : "Forrige side",
		   'rs_group_browse_group_selected' : "Valgt gruppe:",
		   'rs_group_browse_group_no_groups' : "Denne gruppen inneholder ingen grupper",
		   'rs_group_browse_page_info' : "${0} - ${1} av ${2}",
		   'rs_group_browse_page_info_alt' : "Samsvarende gruppe ${0} til og med ${1} av ${2}",
		   'rs_group_browse_remove_selection' : 'Fjern nestet gruppevalg: ${0}',
		   'rs_group_browse_paging' : "Sideveksling",
		   'rs_member_groups' : "Grupper",
		   'rs_member_members' : "Medlemmer",
		   'rs_member_no_results' : "Ingen resultater ble funnet",
		   'rs_member_remove_group' : "Fjern ${0}",
		   'rs_member_add_to_community' : "Klikk for å legge til medlem",
		   'rs_member_remove_name' : "Klikk for å fjerne et medlem",
		   'rs_group_add_to_community' : "Klikk for å legge til gruppe",
		   'rs_group_remove_name' : "Klikk for å fjerne gruppe",
		   'rs_group_name' : "Gruppenavn",
		   'rs_group_role' : "Grupperolle",
		   'rs_warning' : "Advarsel",
		   'rs_a11y_warning' : "Advarsel:",
		   'rs_messagebox_close_btn_title' : "Lukk",
		   'rs_messagebox_close_btn_alt' : "Lukk",
		   'rs_messagebox_error_icon_alt' : "Feil",
		   'rs_messagebox_error_a11y_label' : "Feil:",
		   'rs_messagebox_warning_icon_alt' : "Advarsel",
		   'rs_messagebox_warning_a11y_label' : "Advarsel:",
		   'rs_messagebox_info_icon_alt' : "Informasjon",
		   'rs_messagebox_info_a11y_label' : "Informasjon:",
		   'rs_messagebox_success_icon_alt' : "Vellykket",
		   'rs_messagebox_success_a11y_label' : "Vellykket:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Sett inn kobling til Filer",
		   'rs_docpicker_label' : "Kobling til Filer",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Last ned ${0}",
		   'rs_docpicker_viewdetails_text' : "Vis detaljer",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Vis detaljer for ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Fjern",
		   'rs_attachedfile_filename' : "Bilde ${0}",
		   'rs_feedreader_warning' : "Advarsel: Denne koblingen er for kanallesere og kan vises feil i nettleseren. Klikk på OK hvis du vil fortsette, og på Avbryt hvis du vil gå tilbake til siden.",
		   'rs_search' : "Søk",
		   'rs_all_connections' : "Hele Connections",
		   'rs_advanced' : "Avansert",
		   'rs_select_scope' : "Velg søkeområde",
		   'rs_icfixlayout' : {
		      button_label : "Formater på nytt",
		      dialog_title : "Formater innhold på nytt",
		      warning : "Advarsel",
		      reformat_save : "Formater på nytt og lagre",
		      save_as_is : "Lagre som det er",
		      cancel : "Avbryt",
		      warn_layout : "Innholdet overskrider den maksimale visningsbredden. Vil du formatere på nytt automatisk for å tilpasse til tilgjengelig plass?",
		      remember_decision : "Husk valget mitt"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Det oppstod en feil ved deling av de valgte filene.",
		   'rs_sharefile_access_denied' : "Denne filen er slettet eller deles ikke lenger med deg.",
		   'rs_sharefile_invalid_request' : "Det oppstod en feil ved deling av de valgte filene.",
		   'rs_sharefile_sharing_intent_restriction' : "Filen kan bare deles innenfor organisasjonen.",
		   'rs_sharefile_error_title' : "Feil",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'I App Store',
		   'rs_mobileBanner_inGooglePlay' : 'I Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Åpne',
		   'rs_mobileBanner_view' : 'Vis',
		   'rs_mobileBanner_hide' : 'Skjul',

		   'rs_empty_column_placeholder' : 'Dra apper hit.',
		   'rs_widget_loading_error_title' : 'Kan ikke vise widgeten',
		   'rs_widget_loading_error_message' : 'Prøv igjen senere og kontakt systemadministratoren hvis problemet vedvarer.',
		   'rs_widgets_loading_error_title' : 'Kan ikke vise widgeten(e) i dette fellesskapet',
		   'rs_widget_misplacement_warning' : 'Denne appen får ikke plass i denne kolonnen. En fellesskapseier kan flytte den til en annen kolonne eller fjerne den fra siden.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Tittelen du angav, er for lang.',
		      empty_new_title : 'Tittelen du angav, kan ikke være tom.',
		      default_message : 'Kan ikke endre tittelen for denne ${0}-appen.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Tittel:  ',
		   'rs_widget_title_change_direction' : 'Endre tittelen for denne ${0}-appen.',
		   'rs_widget_title_change_title' : 'Endre tittel',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Inviter eller legg til medlemmer",
		   'rs_vmmainContentDesc' : "Inviter medlemmer for å gi dem mulighet til å delta i fellesskapet. Legg til medlemmer for å inkludere dem automatisk.",
		   'rs_vmtypeAheadLabel' : "Navn eller e-post: ",
		   'rs_vmgroupTypeAheadLabel' : "Navn: ",
		   'rs_vmtypeAheadRoleLabel' : " som ",
		   'rs_vmgroupTypeAheadRoleLabel' : " som medlemmer ",
		   'rs_vmtaNoResults' : "Fant ingen resultater.",
		   'rs_vmtaHeader' : "topptekst",
		   'rs_vmaddUser' : "Legg til",
		   'rs_vmradioSectionTitle' : "Medlemsalternativer:",
		   'rs_vmradioOne' : "Send invitasjoner for å delta i fellesskapet",
		   'rs_vmradioTwo' : "Legg til brukere automatisk i fellesskap",
		   'rs_vmtwistyA' : "Legg til en valgfri melding",
		   'rs_vmtwistyB' : "Fjern tilleggstekst",
		   'rs_vmmessage' : "Melding:",
		   'rs_vmtextAreaStartText' : "Si noe...",
		   'rs_vmcheckboxLabel' : "Send meg en kopi",
		   'rs_vmsave' : "Lagre",
		   'rs_vminvite' : "Inviter",
		   'rs_vmcancel' : "Avbryt",
		   'rs_userContentTitle' : "Angi informasjon",
		   'rs_vmaddUser' : "Opprett bruker",
		   'rs_vmback'	 : "Tilbake",
		   'rs_vmvisitor'	 : "Besøkende",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Klikk her for å kopiere dette fellesskapet',
			'rs_commpicker' : ''

});
