/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Cliquez ici pour afficher la carte de visite",
	"label.semtag.hover.alt" : "Cliquez pour afficher la carte de visite pour {0}",
	"label.semtag.hover.altA11Y" : "Cliquez ici ou appuyez sur les touches Ctrl-Entrée pour afficher la carte de visite",
	"label.personcard.dialog.title" : "Carte de visite pour {0}",

	"errorDefaultMsg2" : "Une erreur s'est produite, contactez votre administrateur système",

	"loadingSTStatus" : "Chargement du statut Sametime...",
	"noStatuAvailable" : "Aucun statut Sametime disponible",

	"label.personcard.cardnomarkup" : "La carte de visite n'a pas pu être extraite",
	"label.inactive.user.msg" : "Cette personne n'est plus un utilisateur actif",
	"label.message.information" : "Informations :",
	"label.personcard.noprofilemsg" : "Il n'existe aucun profil pour cette personne",
	"label.personcard.cardreqexpired" : "La requête d'obtention de la carte de visite a expiré",

	"label.bizcard.applinks.less" : "Afficher moins",
	"label.bizcard.applinks.more" : "Afficher plus",

	"label.personcard.activitieslink" : "Activités",
	"label.personcard.activitieslink.title" : "Cliquez ici pour voir les activités partagées",
	"label.personcard.blogslink" : "Blogues",
	"label.personcard.blogslink.title" : "Cliquez ici pour voir le blogue de cette personne",
	"label.personcard.communitieslink" : "Communautés",
	"label.personcard.communitieslink.title" : "Cliquez ici pour voir les communautés de cette personne",
	"label.personcard.dogearlink" : "Marque-pages",
	"label.personcard.dogearlink.title" : "Cliquez ici pour voir les marque-pages de cette personne",
	"label.personcard.fileslink" : "Fichiers",
	"label.personcard.fileslink.title" : "Cliquez ici pour voir les fichiers partagés de cette personne",
	"label.personcard.forumlink" : "Forums",
	"label.personcard.forumlink.title" : "Cliquez ici pour voir les articles de forum postés de cette personne",
	"label.personcard.homepagelink" : "Accueil",
	"label.personcard.homepagelink.title" : "Cliquez ici pour voir la page d'accueil de cette personne",
	"label.personcard.mobilelink" : "Mobile",
	"label.personcard.mobilelink.title" : "Cliquez ici pour voir la page mobile de cette personne",
	"label.personcard.newslink" : "Nouvelles",
	"label.personcard.newslink.title" : "Cliquez ici pour voir les nouvelles de cette personne",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Cliquez ici pour voir le profil de cette personne",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Cliquez ici pour voir les partages Quickr de cette personne",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Cliquez ici pour voir les wikis de cette personne",

	"personCardMoreActions" : "Autres actions",
	"personCardMoreActionsAltText" : "Cliquez pour obtenir le menu des actions",

	"label.bizcard.dismiss": "Appuyez sur la touche d'échappement pour fermer la carte de visite.",
	"label.bizcard.fullProfile": "Profil complet",
	"label.bizcard.activities": "Activités",
	"label.bizcard.communities": "Communautés",
	"label.bizcard.files": "Fichiers",
	"label.bizcard.forums": "Forums",
	"label.bizcard.bookmarks": "Marque-pages",
	"label.bizcard.blogs": "Blogues",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Inviter à rejoindre Mon réseau",
	"personCardAddAsMyColleagues" : "Inviter à rejoindre Mon réseau",
	"personCardFollow" : "Suivre",
	"personCardUnfollow" : "Arrêter le suivi",
	"personCardChat" : "Discuter",
	"personCardCall" : "Appeler",
	"personCardSendMail" : "Envoyer un courrier électronique",
	"personCardSendEMail" : "Envoyer un courrier électronique",
	"personCardProxyStatusAvailable" : "Je suis disponible",
	"personCardDownloadVCard" : "Télécharger vCard",

	"friends" : "Réseau",
	"friendsFullPageTitle" : "Réseau",
	"friendsMenuTitleAllContacts" : "Tous les contacts réseau",
	"friendsMenuTitleMyContacts" : "Mes contacts réseau",
	"friendsInvitations" : "Invitations",
	"friendsMenuTitleInCommon" : "Personnes en commun",
	"friendsShowAllCommonFriends" : "Afficher tout…",
	"friendsViewAllFriends" : "Tout afficher ({0})",
	"friendsSendFriendRequest" : "Envoyer une demande",
	"friendsNoFriends" : "Aucun contact réseau n'est associé à ce profil",
	"friendsColleaguesInvite" : "Inviter {0} à devenir votre contact réseau",
	"friendsColleaguesFor" : "Contacts réseau de {0}",
	"friendsNewInv" : "{0} nouvelle invitation",
	"friendsNewInvs" : "{0} nouvelles invitations",
	"friendsLoading" : "Chargement du réseau...",
	"friendsLoadingInv" : "Chargement des invitations en cours…",
	"friendsSelectFriendForRemoval" : "Sélectionnez d'abord les contacts à supprimer.",
	"friendsRemoved" : "Contact(s) réseau retiré(s).",
	"friendsInvSent" : "Aucune invitation n'a été envoyée car une invitation est déjà en attente.",
	"friendsRemovedSelected" : "Retirer de Mon réseau",
	"friendsSortByDisplayName" : "Nom d'affichage",
	"friendsSortByRecent" : "Récent",
	"friendsTelephone" : "Téléphone :",
	"friendsEmail" : "Adresse électronique :",
	"friendsAltEmail" : "Autre adresse électronique :",
	"friendsNewInvitationsCount" : "Vous avez {0} nouvelle(s) invitation(s)",
	"friendsNoInv" : "Aucune invitation",
	"friendsInCommonSingle" : "Vous avez {0} contact réseau en commun",
	"friendsInCommonMulti" : "Vous avez {0} contacts réseau en commun",
	"friendsIncludeMsgForInv" : "Inclure un message avec votre invitation :",
	"friendsInitialMsgForInv" : "Je voudrais vous ajouter à ma liste de contacts réseau Connections.",
	"friendsSendInvAction" : "Envoyer une invitation",
	"friendsCancelInvAction" : "Annuler",
	"friendsAcceptAction" : "Accepter",
	"friendsIgnoreAction" : "Ignorer",
	"friendsYouExceedTextLimit" : "Votre message d''invitation est trop long. Elle ne doit pas comporter plus de {1} caractères. Il y a {0} caractères dans cette zone.",
	"friendsCannotAddYourself" : "Vous ne pouvez pas vous ajouter vous-même en tant que contact réseau.",
	"friendsIsYourColleague" : "{0} est votre contact réseau",
	"friendsRecentlyAdded" : "Personnes ajoutées récemment à votre réseau.",
	"friendsDate" : "Date",
	"friendsCollapseWidget" : "Cliquez pour réduire la section Réseau",
	"friendsExpandWidget" : "Cliquez pour développer la section Réseau",
	"friendsIsInYourNetwork" : "{0} se trouve dans votre réseau",
	"friendsActionsFor" : "Actions pour Réseau",
	"friendsInviteFollowError" : "Une erreur s'est produite lors de la tentative de suivi de {0}",
	"friendsInviteTagError" : "Une erreur s'est produite lors de la tentative d'application d'une étiquette à {0}",
	"friendsPleaseLogIn" : "Connectez-vous avant d'inviter des personnes à rejoindre votre réseau",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "L''invitation à rejoindre votre réseau n'est pas possible, car {0} appartient déjà à votre réseau.",
	"friendsInviteAddTagsFor" : "Ajouter des étiquettes pour {0} :",
	"friendsInviteAlsoFollow" : "Suivre également",
	"friendsInviteReceiveUpdates" : "(recevoir les mises à jour)",
	"friendsInviteUpdatesDescription" : "Recevez, sur la page d'accueil et dans un courrier électronique, des mises à jour sur les personnes que vous suivez.",
	"friendsInviteFollowHelp": "Pour plus d''informations, voir {0}Suivi de personnes{1}.",
	"friendsNetwork" : "Réseau",
	"friendsMyNetwork" : "Réseau",
	"friendsNetworkFor" : "Réseau pour {0}",
	"friendsRemoveSelected" : "Retirer le sélecteur",
	"friendsRemoveSelectedTip" : "Cliquez pour retirer les personnes sélectionnées de votre réseau.",
	"friendsNetworkInCommon" : "Vous avez {0} connexions réseau en commun.",
	"friendsAddToMyNetwork" : "Je voudrais vous ajouter à mon réseau de Connections.",
	"friendsInvite" : "Inviter à rejoindre Mon réseau",
	"friendsInvitePerson" : "Inviter {0} à rejoindre votre réseau",
	"friendsInviteMessage" : "Je voudrais vous ajouter à mon réseau de Connections.",
	"friendsInvitedEmailSubject" : "[Profils] Vous êtes invité à vous joindre à mon réseau",
	"friendsInvitedEmailMsg1" : "vous a invité à devenir un contact réseau avec le message suivant inclus dans l'invitation :",
	"friendsInvitedEmailMsg2" : "Ouvrir votre page Invitation réseau",
	"friendsInvitedEmailMsg3" : "Je voudrais vous ajouter à mon réseau.",
	"friendsInvitedEmailMsg4" : "{0} vous a invité à devenir un contact réseau :",
	"friendsInvitedEmailMsg5" : "{0} vous a invité à devenir un contact réseau avec le message suivant inclus dans l''invitation :",
	"friendsInviteLegalNote" : "En envoyant cette invitation, vous acceptez d''autoriser {0} à placer des commentaires sur votre panneau de profil.",
	"friendsInviteFailed" : "En raison d'une erreur du serveur, une notification par courrier électronique n'a pas été envoyée à la personne invitée. Toutefois , la personne invitée sera toujours en mesure d'accepter votre invitation via l'application Web Profils.",
	"personInNetwork" : "Contact réseau"
})
