/* Copyright IBM Corp. 2008, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Judul diperlukan",
	nourl: "Url diperlukan.",
	fileSchema: "Jika Anda ingin menambah tautan file jarak jauh atau lokal, tautan harus sesuai dengan salah satu dari format berikut: file://remote_path atau file:///local_path.",
	invalidUrl: "Ini bukan URL komunitas yang valid.",
	txtHelp: "Bantuan",
	txtHelpTags: "Bantuan Tanda",
	txtHelpTagsClose: "Tutup Bantuan Tanda",
	tagsall: "Semua",
	tagsyours: "Milik Anda",
	tagsrecent: "Terbaru: ",
	tagspopular: "Populer: ",
	tagsrecommended: "Rekomendasi: ",
	nothingselected: "Pilihan komunitas diperlukan.",
	nothingselected_activity: "Pilihan aktivitas diperlukan.",
	nothingselected_blogs: "Pilihan blog diperlukan.",
	nothingselected_all: "Tidak ada layanan atau entri yang dipilih, penunjuk tidak akan disimpan.",
	nothingFeedselected: "Tidak ada layanan atau entri yang dipilih, feed tidak akan disimpan.",
	alertDialogTitle: "Pesan",
	alertDialogOK: "OK",
	expand: "Klik untuk memperluas bagian ini",
	collapse: "Klik untuk melipat bagian ini",
	discussThis: "Diskusikan Ini",
	by: "oleh:",
	posted: "Dipublikasikan:",
	attachments: "Lampiran",
	communityForum: "Forum Komunitas",
	notCommunityPage: "Halaman web saat ini bukan halaman web komunitas yang valid. Anda dapat secara manual memasukkan judul komunitas, link dan deskripsi untuk membuat suatu komunitas terkait.",
	privateCommunityNotice: "Komunitas ini terbatas. Hanya dapat dilihat oleh anggota komunitas.",
	forumNameHint : "Ketik nama forum",
	formDescriptionHint:"Jelaskan mengapa komunitas terkait ini menarik minat komunitas Anda.",
	information : "Informasi",
	error : "Terjadi kesalahan",
	success : "Berhasil",
	warning : "Peringatan",
	informationColon : "Informasi:",
	successColon : "Berhasil:",
	warningColon : "Peringatan:",
	errorColon : "Kesalahan:",
	feedAlreadyExist : "Feed sudah ada dalam komunitas.",
	bookmarkAlreadyExist : "Markah sudah ada dalam komunitas.",
	mentionAuthWarning:"Orang yang disebutkan berikut ini ini tidak akan dapat melihat pesan karena mereka bukan merupakan anggota komunitas:",
	mentionAuthForumWarning:"Orang yang disebutkan berikut ini tidak akan dapat mmelihat pesan karena mereka tidak dapat mengakses forum ini:",
	exceedDescLength: "Deskripsi yang Anda masukkan terlalu panjang.",
	communities_checked:"${0} komunitas dipilih",
	activities_checked:"${0} aktivitas dipilih",
	blogs_checked:"${0} blog dipilih"
})

