/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Afbeelding toevoegen",
   newUpload : "Nieuwe upload",
   URL : "URL",
   imageLibrary : "Afbeeldingenbibliotheek",
   description : "Beschrijving:",
   imageFile : "Bestanden:",
   OK: "OK",
   cancel: "Annuleren",
   required: "Verplichte velden",
   preview: "Preview:",
   previewWarning: "Het laden van de afbeelding lijst te zijn mislukt. Weet u zeker dat dit een geldige URL is?",
   alt: "Alternatieve tekst",
   filesTab: "Vanuit Bestanden",
   images:"Afbeeldingen:",
   browse:"Bladeren...",
   imagePickerTitle:"Afbeeldingen invoegen vanuit Bestanden",
   componentImagePickerTitle:" ${0} geüploade afbeeldingen",
   /* New String for insert image dialog */
   title: "Afbeelding invoegen",
   uploadBtn: "Afbeelding uploaden",   
   insertBtn: "Afbeelding invoegen",
   uploadTab: "Lokale bestanden",
   externalTab: "Web-URL",
   internalTab: "Bestaande afbeeldingen",
   fileFieldTip: "Upload afbeeldingen door ze rechtstreeks vanaf uw bureaublad naar dit venster te verslepen.",
   AdditionalSection: "Extra opties",
   ExpandSection: "Extra opties uitvouwen",
   CloseSection: "Extra opties samenvouwen",
   webURLPrompt: "Webafbeeldings-URL:",
   previewPrompt: "Preview van gebied: het kan even duren voordat grote afbeeldingen worden afgebeeld.",
   noExistingImage: "Er is nog geen afbeelding toegevoegd.",
   selectExistingImage: "Selecteer een bestaande afbeelding:",
   urlMissing: "Geef een URL op",
   urlInvalid: "Ongeldige URL. Geef een geldige URL op en probeer het opnieuw.",
   previousItem: "Vorige",
   nextItem: "Volgende",
   oneImageOneTime: "Er is al een afbeelding toegevoegd aan dit venster. U kunt slechts één afbeelding tegelijk toevoegen.",
   loadingErrorMsg: "Er is een fout opgetreden bij het laden van bestaande afbeeldingen. Probeer het later nogmaals.",
   urlInputTooltip: "Geef de web-URL van de afbeelding op"
})

