/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informaţii pentru nod: ",
	"INSTALLED": "Verificarea serviciilor instalate",
	"RESUMETOKENS": "Verificarea jetoanelor de continuare",
	"SEEDLISTS": "Verificarea dacă seedlist-urile sunt disponibile",
	"CALENDARS": "Verificarea dacă calendarele planificate au fost configurate corect",
	"VARIABLES": "Verificarea dacă variabilele WebSphere au fost setate",
	"TASKS": "Verificarea pentru taskurile indexare activate",
	"INDEXFILES": "Verificcarea folderului index pentru fişierele necesare",
	"LOGS": "Examinarea logurilor pentru erori",
	"CONFIGFILES": "Examinarea fişierelor de configuraţie",
	"DICTIONARIES": "Verificarea numărului de dicţionare care au fost activate",
	"SYNC": "Verificare stare noduri",
	"DBRECORDS": "Verificarea înregistrărilor bazei de date",
	"INSTALLEDMSG": "Serviciul următor este instalat: ",
	"RESUMETOKENSMSG": "Jetonul continuare pentru: ",
	"SEEDLISTSMSG": "Seedlist nu poate fi obţinută pentru: ",
	"CALENDARSMSG": "Verificarea calendarului planificare a fost transmis: ",
	"VARIABLESMSG": "Variabilă: ",
	"TASKSMSG": "Taskul următor este activat: ",
	"INDEXFILESMSG" : "Fişierele următoare sunt în folderul index de căutare: ",
	"LOGSMSG" : "Examinaţi mesajele de eroare următoare: ",
	"CONFIGFILESMSG" : "Următoarele fişiere de configurare nu au fost găsite: ",
	"DICTIONARIESMSG" : "Numărul de dicţionare activat este: ",
	"INSYNC": "Toate nodurile sunt în sync",
	"OUTOFSYNC": "Numărul de noduri din afara sync este: ",
	"NOTBLOCKED": "Niciun nod nu este blocat",
	"BLOCKED": "Numărul de noduri blocate este: ",
	"INDATE": "Toate nodurile sunt în dată",
	"OUTOFDATE": "Numărul de noduri în afara datei este: ",
	"NUMOFDOCS": "Numărul de documente din baza de date este ",
	"FILESTOCONVERT": "Numărul de documente de fişiere de convertit este ",
	"CONVERTEDFILES": "Numărul de fişiere convertite este ",
	"TOTALFILES": "Numărul total de fişiere din baza de date ",
	"ERROR":"Eroare",
	"ERROR_PREFIX":"Eroare:",
	"INFO":"Informaţii",
	"INFO_PREFIX":"Informaţii:",
	"WARNING":"Avertisment",
	"WARNING_PREFIX":"Avertisment:",
	"LOADING_MESSAGE": "Încărcare",
	"SERVER_STATUS": "Stare server",
	"INITIAL_INDEXING_EXCEPTIONS": "Excepţii indexare iniţială",
	"SYS_OUT_EXCEPTIONS": "Excepţii de logare SystemOut",
	"SEEDLIST_VALIDATE": "Validare liste",
	"ERRORS_DURING_INITIAL_INDEXING":"Au apărut următoarele excepţii în timpul creării unui index iniţial",
	"CRAWL_FAILED": "Nu au putut fi cercetate toate datele pentru următorul serviciu: ",
	"EXCEPTION_ENCOUNTERED": "Cercetarea a eşuat cu următorul mesaj: ",
	"SAND_VALIDATE": "Validare SAND",
	"CHECK_FOR_SAND_FILES":"Verificare pentru fişierele SAND",
	"IS_FILE_AVAILABLE":"Verificare că a fost creat fişierul: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Au apărut următoarele excepţii în timpul creării unui index iniţial",
	"CRAWL_FAILED":"Nu au putut fi cercetate toate datele pentru următorul serviciu: ",
	"EXCEPTION_ENCOUNTERED":"Cercetarea a eşuat cu următorul mesaj: "
})

