/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "คลิกที่นี่เพื่อดูนามบัตร",
	"label.semtag.hover.alt" : "คลิกเพื่อดูนามบัตรของ {0}",
	"label.semtag.hover.altA11Y" : "คลิกที่นี่หรือกด Control-Enter เพื่อดูนามบัตร",
	"label.personcard.dialog.title" : "นามบัตรของ {0}",

	"errorDefaultMsg2" : "มีข้อผิดพลาดเกิดขึ้น โปรดติดต่อผู้ดูแลระบบของคุณ",

	"loadingSTStatus" : "กำลังโหลดสถานะ Sametime...",
	"noStatuAvailable" : "ไม่มีสถานะ Sametime",

	"label.personcard.cardnomarkup" : "ไม่สามารถเรียกข้อมูลนามบัตร",
	"label.inactive.user.msg" : "บุคคลนี้ไม่ใช่ผู้ใช้ที่ใช้งานอยู่อีกต่อไป",
	"label.message.information" : "ข้อมูล:",
	"label.personcard.noprofilemsg" : "ไม่มีโปรไฟล์สำหรับบุคคลนี้อยู่",
	"label.personcard.cardreqexpired" : "คำขอรับนามบัตรหมดอายุ",

	"label.bizcard.applinks.less" : "แสดงน้อยลง",
	"label.bizcard.applinks.more" : "แสดงเพิ่มเติม",

	"label.personcard.activitieslink" : "กิจกรรม",
	"label.personcard.activitieslink.title" : "คลิกที่นี่เพื่อดูกิจกรรมที่แบ่งปัน",
	"label.personcard.blogslink" : "บล็อก",
	"label.personcard.blogslink.title" : "คลิกที่นี่เพื่อดูบล็อกของบุคคลนี้",
	"label.personcard.communitieslink" : "ชุมชน",
	"label.personcard.communitieslink.title" : "คลิกที่นี่เพื่อดูชุมชนของบุคคลนี้",
	"label.personcard.dogearlink" : "บุ๊กมาร์ก",
	"label.personcard.dogearlink.title" : "คลิกที่นี่เพื่อดูบุ๊กมาร์กของบุคคลนี้",
	"label.personcard.fileslink" : "ไฟล์",
	"label.personcard.fileslink.title" : "คลิกที่นี่เพื่อดูไฟล์ที่บุคคลนี้แบ่งปัน",
	"label.personcard.forumlink" : "ฟอรัม",
	"label.personcard.forumlink.title" : "คลิกที่นี่เพื่อดูการโพสต์ฟอรัมของบุคคลนี้",
	"label.personcard.homepagelink" : "หน้าแรก",
	"label.personcard.homepagelink.title" : "คลิกที่นี่เพื่อดูโฮมเพจของบุคคลนี้",
	"label.personcard.mobilelink" : "อุปกรณ์เคลื่อนที่",
	"label.personcard.mobilelink.title" : "คลิกที่นี่เพื่อดูโมบายล์เพจของบุคคลนี้",
	"label.personcard.newslink" : "ข่าว",
	"label.personcard.newslink.title" : "คลิกที่นี่เพื่อดูข่าวสารของบุคคลนี้",
	"label.personcard.profilelink" : "โปรไฟล์",
	"label.personcard.profilelink.title" : "คลิกที่นี่เพื่อดูโปรไฟล์ของบุคคลนี้",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "คลิกที่นี่เพื่อดูการแบ่งปัน Quickr ของบุคคลนี้",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "คลิกที่นี่เพื่อดู Wikis ของบุคคลนี้",

	"personCardMoreActions" : "ดำเนินการเพิ่มเติม",
	"personCardMoreActionsAltText" : "คลิกเพื่อดูเมนูการดำเนินการ",

	"label.bizcard.dismiss": "กด Escape เพื่อข้ามนามบัตรนี้",
	"label.bizcard.fullProfile": "โปรไฟล์เต็มรูปแบบ",
	"label.bizcard.activities": "กิจกรรม",
	"label.bizcard.communities": "ชุมชน",
	"label.bizcard.files": "ไฟล์",
	"label.bizcard.forums": "ฟอรัม",
	"label.bizcard.bookmarks": "บุ๊กมาร์ก",
	"label.bizcard.blogs": "บล็อก",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "เชิญมาที่เครือข่ายของฉัน",
	"personCardAddAsMyColleagues" : "เชิญมาที่เครือข่ายของฉัน",
	"personCardFollow" : "ติดตาม",
	"personCardUnfollow" : "หยุดการติดตาม",
	"personCardChat" : "สนทนา",
	"personCardCall" : "โทร",
	"personCardSendMail" : "ส่งอีเมล",
	"personCardSendEMail" : "ส่งอีเมล",
	"personCardProxyStatusAvailable" : "ฉันว่าง",
	"personCardDownloadVCard" : "ดาวน์โหลด vCard",

	"friends" : "เครือข่าย",
	"friendsFullPageTitle" : "เครือข่าย",
	"friendsMenuTitleAllContacts" : "ผู้ติดต่อเครือข่ายทั้งหมด",
	"friendsMenuTitleMyContacts" : "ผู้ติดต่อเครือข่ายของฉัน",
	"friendsInvitations" : "คำเชิญ",
	"friendsMenuTitleInCommon" : "บุคคลใน Common",
	"friendsShowAllCommonFriends" : "แสดงทั้งหมด...",
	"friendsViewAllFriends" : "ดูทั้งหมด ({0})",
	"friendsSendFriendRequest" : "ส่งคำขอ",
	"friendsNoFriends" : "ไม่มีผู้ติดต่อเครือข่ายถูกเชื่อมโยงกับโปรไฟล์นี้",
	"friendsColleaguesInvite" : "เชิญ {0} เป็นผู้ติดต่อในเครือข่ายของคุณ",
	"friendsColleaguesFor" : "ผู้ติดต่อในเครือข่ายสำหรับ {0}",
	"friendsNewInv" : "{0} คำเชิญใหม่",
	"friendsNewInvs" : "{0} คำเชิญใหม่",
	"friendsLoading" : "กำลังโหลดเครือข่าย...",
	"friendsLoadingInv" : "กำลังโหลดคำเชิญ...",
	"friendsSelectFriendForRemoval" : "เลือกผู้ติดต่อที่คุณต้องการลบก่อน",
	"friendsRemoved" : "ผู้ติดต่อในเครือข่ายถูกลบแล้ว",
	"friendsInvSent" : "ไม่มีการส่งคำเชิญ เนื่องจากมีคำเชิญค้างอยู่",
	"friendsRemovedSelected" : "ลบออกจากเครือข่ายของฉัน",
	"friendsSortByDisplayName" : "แสดงชื่อ",
	"friendsSortByRecent" : "ล่าสุด",
	"friendsTelephone" : "โทรศัพท์:",
	"friendsEmail" : "อีเมล:",
	"friendsAltEmail" : "อีเมลสำรอง:",
	"friendsNewInvitationsCount" : "คุณได้รับ {0} คำเชิญใหม่",
	"friendsNoInv" : "ไม่มีคำเชิญ",
	"friendsInCommonSingle" : "คุณมี {0} ผู้ติดต่อในเครือข่ายในแบบเดียวกัน",
	"friendsInCommonMulti" : "คุณมี {0} ผู้ติดต่อในเครือข่ายในแบบเดียวกัน",
	"friendsIncludeMsgForInv" : "รวมข้อความกับคำเชิญของคุณ:",
	"friendsInitialMsgForInv" : "ฉันต้องการเพิ่มคุณในรายชื่อผู้ติดต่อในเครือข่าย Connections ของฉัน",
	"friendsSendInvAction" : "ส่งคำเชิญ",
	"friendsCancelInvAction" : "ยกเลิก",
	"friendsAcceptAction" : "ยอมรับ",
	"friendsIgnoreAction" : "ละเว้น",
	"friendsYouExceedTextLimit" : "ข้อความเชิญของคุณยาวเกินไป ใช้ได้สูงสุดคือ {1} อักขระ มี {0} อักขระในฟิลด์นี้",
	"friendsCannotAddYourself" : "คุณไม่สามารถเพิ่มตัวเองเป็นผู้ติดต่อในเครือข่ายได้",
	"friendsIsYourColleague" : "{0} คือผู้ติดต่อในเครือข่ายของคุณ",
	"friendsRecentlyAdded" : "ผู้คนที่คุณได้เพิ่มในเครือข่ายของคุณล่าสุด",
	"friendsDate" : "วันที่",
	"friendsCollapseWidget" : "คลิกเพื่อยุบเครือข่ายส่วนนี้",
	"friendsExpandWidget" : "คลิกเพื่อขยายเครือข่ายส่วนนี้",
	"friendsIsInYourNetwork" : "{0} อยู่ในเครือข่ายของคุณ",
	"friendsActionsFor" : "การดำเนินการสำหรับเครือข่าย",
	"friendsInviteFollowError" : "เกิดข้อผิดพลาดขณะพยายามติดตาม {0}",
	"friendsInviteTagError" : "เกิดข้อผิดพลาดขณะพยายามแท็ก {0}",
	"friendsPleaseLogIn" : "โปรดล็อกอินเพื่อเชิญคนเข้าสู่เครือข่ายของคุณ",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "ไม่สามารถเชิญเข้าสู่เครือข่ายของคุณได้ เนื่องจาก {0} อยู่ในเครือข่ายของคุณอยู่แล้ว",
	"friendsInviteAddTagsFor" : "แท็กสำหรับ {0}",
	"friendsInviteAlsoFollow" : "และติดตาม",
	"friendsInviteReceiveUpdates" : "(รับการอัปเดต)",
	"friendsInviteUpdatesDescription" : "รับการอัปเดตเกี่ยวกับบุคคลที่คุณกำลังติดตามบนโฮมเพจ และในสรุปข้อมูลอีเมล",
	"friendsInviteFollowHelp": "สำหรับข้อมูลเพิ่มเติม โปรดดูที่ {0}ติดตามบุคคล{1}",
	"friendsNetwork" : "เครือข่าย",
	"friendsMyNetwork" : "เครือข่าย",
	"friendsNetworkFor" : "เครือข่ายสำหรับ {0}",
	"friendsRemoveSelected" : "ลบรายการที่เลือก",
	"friendsRemoveSelectedTip" : "คลิกเพื่อลบบุคคลที่เลือกจากเครือข่ายของคุณ",
	"friendsNetworkInCommon" : "คุณมี {0} การเชื่อมต่อเครือข่ายในแบบเดียวกัน",
	"friendsAddToMyNetwork" : "ฉันต้องการเพิ่มคุณในรายชื่อผู้ติดต่อในเครือข่าย Connections ของฉัน",
	"friendsInvite" : "เชิญมาที่เครือข่ายของฉัน",
	"friendsInvitePerson" : "เชิญ {0} เข้าสู่เครือข่ายของคุณ",
	"friendsInviteMessage" : "ฉันต้องการเพิ่มคุณในเครือข่าย Connections ของฉัน",
	"friendsInvitedEmailSubject" : "[Profiles] คุณได้รับเชิญให้เข้าร่วมเครือข่ายของฉัน",
	"friendsInvitedEmailMsg1" : "ได้เชิญคุณให้เป็นผู้ติดต่อในเครือข่ายโดยมีข้อความต่อไปนี้ในคำเชิญ:",
	"friendsInvitedEmailMsg2" : "เปิดเพจคำเชิญเครือข่ายของคุณ",
	"friendsInvitedEmailMsg3" : "ฉันต้องการเพิ่มคุณเข้าสู่เครือข่ายของฉัน",
	"friendsInvitedEmailMsg4" : "{0} เชิญคุณให้มาเป็นส่วนหนึ่งของผู้ติดต่อในเครือข่าย",
	"friendsInvitedEmailMsg5" : "{0} ได้เชิญคุณให้เป็นผู้ติดต่อในเครือข่ายโดยมีข้อความต่อไปนี้ในคำเชิญ:",
	"friendsInviteLegalNote" : "โดยการส่งคำเชิญนี้ คุณอนุญาตให้ {0} แสดงความคิดเห็นในบอร์ดโปรไฟล์ของคุณ",
	"friendsInviteFailed" : "เนื่องจากข้อผิดพลาดเซิร์ฟเวอร์ การแจ้งเตือนทางอีเมลไม่ได้ถูกส่งไปที่ผู้ถูกเชิญ อย่างไรก็ตาม ผู้ถูกเชิญยังคงสามารถตอบรับคำเชิญของคุณผ่านเว็บแอปพลิเคชัน Profiles ได้",
	"personInNetwork" : "ผู้ติดต่อในเครือข่าย"
})
