/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Wymagany jest tytuł.",
	nourl: "Wymagany jest adres URL.",
	fileSchema: "Jeśli chcesz dodać odsyłacz do pliku zdalnego lub lokalnego, musi on być zgodny z jednym z następujących formatów: file://ścieżka_zdalna lub file:///ścieżka_lokalna.",
	invalidUrl: "To nie jest poprawny adres URL społeczności.",
	invalidTagChar: "Wprowadzona lista znaczników zawiera nieprawidłowy znak &. Usuń go z listy znaczników.",
	txtHelp: "Pomoc",
	txtHelpTags: "Pomoc dotycząca znaczników",
	txtHelpTagsClose: "Zamknij pomoc dotyczącą znaczników",
	tagsall: "Wszystko",
	tagsyours: "Użytkownika",
	tagsrecent: "Ostatnie: ",
	tagspopular: "Popularne: ",
	tagsrecommended: "Zalecane: ",
	nothingselected: "Należy dokonać wyboru społeczności.",
	nothingselected_activity: "Należy dokonać wyboru działania.",
	nothingselected_blogs: "Należy dokonać wyboru bloga.",
	nothingselected_all: "Nie wybrano usługi ani wpisu. Zakładka nie zostanie zapisana.",
	nothingFeedselected: "Nie wybrano usługi ani wpisu. Kanał RSS nie zostanie zapisany.",
	alertDialogTitle: "Komunikat",
	alertDialogOK: "OK",
	expand: "Kliknij, aby rozwinąć tę sekcję",
	collapse: "Kliknij, aby zwinąć tę sekcję",
	discussThis: "Podyskutuj o tym",
	by: "Autor:",
	posted: "Opublikowano:",
	attachments: "Załączniki",
	communityForum: "Forum społeczności",
	notCommunityPage: "Bieżąca strona WWW nie jest poprawną stroną WWW społeczności. Aby utworzyć powiązaną społeczność, można ręcznie wprowadzić tytuł społeczności, odsyłacz i opis.",
	privateCommunityNotice: "Ta społeczność jest zastrzeżona i jest widoczna tylko dla jej członków.",
	forumNameHint : "Wpisz nazwę forum",
	formDescriptionHint:"Opisz, dlaczego ta powiązana społeczność mogłaby zainteresować Twoją społeczność.",
	information : "Informacja",
	error : "Błąd",
	success : "Powodzenie",
	warning : "Ostrzeżenie",
	informationColon : "Informacja:",
	successColon : "Powodzenie:",
	warningColon : "Ostrzeżenie:",
	errorColon : "Błąd:",
	feedAlreadyExist : "Kanał RSS już istnieje w społeczności.",
	bookmarkAlreadyExist : "Zakładka już istnieje w społeczności.",
	mentionAuthWarning:"Poniższe wspomniane osoby nie będą mogły zobaczyć wiadomości, ponieważ nie są członkami społeczności:",
	mentionAuthForumWarning:"Poniższe wspomniane osoby nie będą mogły wyświetlić tej wiadomości, ponieważ nie mają dostępu do forum:",
	exceedDescLength: "Wprowadzony opis jest zbyt długi.",
	communities_checked:"Wybrane społeczności: ${0}",
	activities_checked:"Wybrane działania: ${0}",
	blogs_checked:"Wybrane blogi: ${0}"
})
