/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "จำเป็นต้องมีหัวเรื่อง",
	nourl: "จำเป็นต้องมี Url",
	fileSchema: "หากคุณต้องการเพิ่มลิงก์ไฟล์แบบรีโมตหรือโลคัล ลิงก์นั้นต้องเป็นหนึ่งในรูปแบบต่อไปนี้: file://remote_path or file:///local_path",
	invalidUrl: "นี้คือ URL ชุมชนที่ถูกต้อง",
	invalidTagChar: "รายการแท็กที่คุณป้อนมีอักขระ '&' ซึ่งไม่ถูกต้อง  โปรดลบอักขระนี้ออกจากรายการแท็ก",
	txtHelp: "วิธีใช้",
	txtHelpTags: "วิธีใช้แท็ก",
	txtHelpTagsClose: "ปิดวิธีใช้แท็ก",
	tagsall: "ทั้งหมด",
	tagsyours: "ของคุณ",
	tagsrecent: "ล่าสุด: ",
	tagspopular: "ยอดนิยม: ",
	tagsrecommended: "แนะนำ: ",
	nothingselected: "จำเป็นต้องเลือกชุมชน",
	nothingselected_activity: "จำเป็นต้องเลือกกิจกรรม",
	nothingselected_blogs: "จำเป็นต้องเลิอกบล็อก",
	nothingselected_all: "ไม่มีเซอร์วิสหรือรายการที่ถูกเลือก บุ๊กมาร์กจะไม่ถูกบันทึก",
	nothingFeedselected: "ไม่มีเซอร์วิสหรือรายการที่ถูกเลือก ฟีดจะไม่ถูกบันทึก",
	alertDialogTitle: "ข้อความ",
	alertDialogOK: "ตกลง",
	expand: "คลิกเพื่อขยายส่วนนี้",
	collapse: "คลิกเพื่อยุบส่วนนี้",
	discussThis: "อภิปรายสิ่งนี้",
	by: "โดย:",
	posted: "ส่งแล้ว:",
	attachments: "สิ่งที่แนบมา",
	communityForum: "ฟอรัมชุมชน",
	notCommunityPage: "เว็บเพจปัจจุบันไม่ใช่เว็บเพจชุมชนที่ถูกต้อง คุณสามารถอินพุตหัวเรื่องชุมชน ลิงก์ และคำอธิบายด้วยตนเองเพื่อสร้างชุมชนที่เกี่ยวข้อง",
	privateCommunityNotice: "ชุมชนนี้ถูกจำกัด ซึ่งสามารถมองเห็นได้สำหรับสมาชิกของชุมชน",
	forumNameHint : "พิมพ์ชื่อฟอรัม",
	formDescriptionHint:"อธิบายเหตุผลที่ชุมชนที่เกี่ยวข้องนี้จะสนใจในชุมชนของคุณ",
	information : "ข้อมูล",
	error : "ข้อผิดพลาด",
	success : "สำเร็จ",
	warning : "คำเตือน",
	informationColon : "ข้อมูล:",
	successColon : "สำเร็จ:",
	warningColon : "การเตือน:",
	errorColon : "ข้อผิดพลาด:",
	feedAlreadyExist : "ฟีดมีอยู่แล้วในชุมชน",
	bookmarkAlreadyExist : "บุ๊กมาร์กมีอยู่แล้วในชุมชน",
	mentionAuthWarning:"บุคคลต่อไปนี้ที่กล่าวถึงจะไม่สามารถดูข้อความนี้ได้เนื่องจากไม่ใช่สมาชิกของชุมชน:",
	mentionAuthForumWarning:"บุคคลต่อไปนี้ที่กล่าวถึงจะไม่สามารถดูข้อความนี้ได้เนื่องจากไม่สามารถเข้าถึงฟอรัมนี้:",
	exceedDescLength: "คำอธิบายที่คุณป้อนยาวเกินไป",
	communities_checked:"${0} ชุมชนที่เลือก",
	activities_checked:"${0} กิจกรรมที่เลือก",
	blogs_checked:"${0} บล็อกที่เลือก"
})
