/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "ノードの情報: ",
	"INSTALLED": "インストール済みのサービスを確認しています",
	"RESUMETOKENS": "再開トークンを確認しています",
	"SEEDLISTS": "シードリストが利用可能かどうかを確認しています",
	"CALENDARS": "スケジュール・カレンダーが正しく構成されているかどうかを確認しています",
	"VARIABLES": "WebSphere 変数が設定されているかどうかを確認しています",
	"TASKS": "有効なインデックス付けタスクを確認しています",
	"INDEXFILES": "インデックス・フォルダーで必須ファイルを確認しています",
	"LOGS": "ログでエラーを確認しています",
	"CONFIGFILES": "構成ファイルのレビュー",
	"DICTIONARIES": "有効になっている辞書の数を確認しています",
	"SYNC": "ノードの状況を検査しています",
	"DBRECORDS": "データベース・レコードを確認しています",
	"INSTALLEDMSG": "以下のサービスがインストールされます。 ",
	"RESUMETOKENSMSG": "再開トークン: ",
	"SEEDLISTSMSG": "シードリストを取得できませんでした: ",
	"CALENDARSMSG": "スケジュール・カレンダーのチェックにパスしました: ",
	"VARIABLESMSG": "変数: ",
	"TASKSMSG": "以下のタスクが有効になっています。 ",
	"INDEXFILESMSG" : "次のファイルが検索インデックス・フォルダー内にあります: ",
	"LOGSMSG" : "以下のエラー・メッセージを確認してください: ",
	"CONFIGFILESMSG" : "次の構成ファイルが見つかりました: ",
	"DICTIONARIESMSG" : "有効な辞書の数: ",
	"INSYNC": "すべてのノードが同期されています",
	"OUTOFSYNC": "いくつかのノードが同期されていません: ",
	"NOTBLOCKED": "ブロックされているノードはありません",
	"BLOCKED": "いくつかのノードがブロックされています: ",
	"INDATE": "古くなっているノードはありません",
	"OUTOFDATE": "いくつかのノードが古くなっています: ",
	"NUMOFDOCS": "データベース内の文書の数: ",
	"FILESTOCONVERT": "変換するファイル文書の数: ",
	"CONVERTEDFILES": "変換されたファイルの数: ",
	"TOTALFILES": "データベース内のファイルの総数: ",
	"ERROR":"エラー",
	"ERROR_PREFIX":"エラー:",
	"INFO":"情報",
	"INFO_PREFIX":"情報:",
	"WARNING":"警告",
	"WARNING_PREFIX":"警告:",
	"LOADING_MESSAGE": "ロード中",
	"SERVER_STATUS": "サーバーの状況",
	"INITIAL_INDEXING_EXCEPTIONS": "初期インデックス付けの例外",
	"SYS_OUT_EXCEPTIONS": "SystemOut ログの例外",
	"SEEDLIST_VALIDATE": "シードリスト検証",
	"ERRORS_DURING_INITIAL_INDEXING":"初期インデックスの作成中に以下の例外が発生しました",
	"CRAWL_FAILED": "以下のサービスのすべてのデータをクロールできませんでした: ",
	"EXCEPTION_ENCOUNTERED": "クロールが以下のメッセージで失敗しました: ",
	"SAND_VALIDATE": "SAND 検証",
	"CHECK_FOR_SAND_FILES":"SAND ファイルを確認しています",
	"IS_FILE_AVAILABLE":"ファイルが作成されたことを確認しています: ",
	"ERRORS_DURING_INITIAL_INDEXING":"初期インデックスの作成中に以下の例外が発生しました",
	"CRAWL_FAILED":"以下のサービスのすべてのデータをクロールできませんでした: ",
	"EXCEPTION_ENCOUNTERED":"クロールが以下のメッセージで失敗しました: "
})

