/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "ビジネス・カードを表示するにはここをクリックします",
	"label.semtag.hover.alt" : "クリックすると {0} のビジネス・カードが表示されます",
	"label.semtag.hover.altA11Y" : "ビジネス・カードを表示するにはここをクリックするか、Ctrl+Enter を押します",
	"label.personcard.dialog.title" : "{0} のビジネス・カード",

	"errorDefaultMsg2" : "エラーが発生しました。システム管理者にお問い合わせください",

	"loadingSTStatus" : "Sametime 状況のロード中...",
	"noStatuAvailable" : "使用可能な Sametime 状況がありません",

	"label.personcard.cardnomarkup" : "ビジネス・カードを取得できませんでした",
	"label.inactive.user.msg" : "このユーザーはアクティブ・ユーザーではなくなっています",
	"label.message.information" : "情報:",
	"label.personcard.noprofilemsg" : "このユーザーのプロフィールは存在しません",
	"label.personcard.cardreqexpired" : "ビジネス・カードを取得する要求の有効期限が切れました",

	"label.bizcard.applinks.less" : "簡略表示",
	"label.bizcard.applinks.more" : "さらに表示",

	"label.personcard.activitieslink" : "アクティビティー",
	"label.personcard.activitieslink.title" : "共有アクティビティーを表示するにはここをクリックします",
	"label.personcard.blogslink" : "ブログ",
	"label.personcard.blogslink.title" : "このユーザーのブログを表示するにはここをクリックします",
	"label.personcard.communitieslink" : "コミュニティー",
	"label.personcard.communitieslink.title" : "このユーザーのコミュニティーを表示するにはここをクリックします",
	"label.personcard.dogearlink" : "ブックマーク",
	"label.personcard.dogearlink.title" : "このユーザーのブックマークを表示するにはここをクリックします",
	"label.personcard.fileslink" : "ファイル",
	"label.personcard.fileslink.title" : "このユーザーの共有ファイルを表示するにはここをクリックします",
	"label.personcard.forumlink" : "フォーラム",
	"label.personcard.forumlink.title" : "このユーザーのフォーラム投稿を表示するにはここをクリックします",
	"label.personcard.homepagelink" : "ホーム",
	"label.personcard.homepagelink.title" : "このユーザーのホーム・ページを表示するにはここをクリックします",
	"label.personcard.mobilelink" : "モバイル",
	"label.personcard.mobilelink.title" : "このユーザーのモバイル・ページを表示するにはここをクリックします",
	"label.personcard.newslink" : "ニュース",
	"label.personcard.newslink.title" : "このユーザーのニュースを表示するにはここをクリックします",
	"label.personcard.profilelink" : "プロフィール",
	"label.personcard.profilelink.title" : "このユーザーのプロフィールを表示するにはここをクリックします",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "このユーザーの Quickr 共有を表示するにはここをクリックします",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "このユーザーの Wiki を表示するにはここをクリックします",

	"personCardMoreActions" : "他のアクション",
	"personCardMoreActionsAltText" : "クリックしてアクション・メニューを表示",

	"label.bizcard.dismiss": "エスケープを押してこのビジネス・カードを閉じます。",
	"label.bizcard.fullProfile": "全プロフィール",
	"label.bizcard.activities": "アクティビティー",
	"label.bizcard.communities": "コミュニティー",
	"label.bizcard.files": "ファイル",
	"label.bizcard.forums": "フォーラム",
	"label.bizcard.bookmarks": "ブックマーク",
	"label.bizcard.blogs": "ブログ",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "マイ・ネットワークに招待",
	"personCardAddAsMyColleagues" : "マイ・ネットワークに招待",
	"personCardFollow" : "フォロー",
	"personCardUnfollow" : "フォローの停止",
	"personCardChat" : "チャット",
	"personCardCall" : "コール",
	"personCardSendMail" : "メールの送信",
	"personCardSendEMail" : "メールの送信",
	"personCardProxyStatusAvailable" : "応答可",
	"personCardDownloadVCard" : "vCard のダウンロード",

	"friends" : "ネットワーク",
	"friendsFullPageTitle" : "ネットワーク",
	"friendsMenuTitleAllContacts" : "すべてのネットワーク連絡先",
	"friendsMenuTitleMyContacts" : "マイ・ネットワーク連絡先",
	"friendsInvitations" : "招待",
	"friendsMenuTitleInCommon" : "共通のユーザー",
	"friendsShowAllCommonFriends" : "すべて表示...",
	"friendsViewAllFriends" : "すべて表示 ({0})",
	"friendsSendFriendRequest" : "要求の送信",
	"friendsNoFriends" : "このプロフィールに関連付けられたネットワーク連絡先はありません",
	"friendsColleaguesInvite" : "{0} をネットワーク連絡先に招待",
	"friendsColleaguesFor" : "{0} のネットワーク連絡先",
	"friendsNewInv" : "{0} 件の新規招待",
	"friendsNewInvs" : "{0} 件の新規招待",
	"friendsLoading" : "ネットワークのロード中...",
	"friendsLoadingInv" : "招待のロード中...",
	"friendsSelectFriendForRemoval" : "最初に削除する連絡先を選択します。",
	"friendsRemoved" : "ネットワーク連絡先が削除されました。",
	"friendsInvSent" : "招待は既に保留中になっているため送信できません。",
	"friendsRemovedSelected" : "マイ・ネットワークから削除",
	"friendsSortByDisplayName" : "表示名",
	"friendsSortByRecent" : "最新",
	"friendsTelephone" : "電話番号:",
	"friendsEmail" : "メール:",
	"friendsAltEmail" : "他のメール:",
	"friendsNewInvitationsCount" : "{0} 件の新規招待があります",
	"friendsNoInv" : "招待なし",
	"friendsInCommonSingle" : "共通のネットワーク連絡先が {0} 件あります",
	"friendsInCommonMulti" : "共通のネットワーク連絡先が {0} 件あります",
	"friendsIncludeMsgForInv" : "招待メッセージを入力してください:",
	"friendsInitialMsgForInv" : "私の Connections ネットワーク連絡先リストにあなたを加えたいと思います。",
	"friendsSendInvAction" : "招待の送信",
	"friendsCancelInvAction" : "キャンセル",
	"friendsAcceptAction" : "受け入れる",
	"friendsIgnoreAction" : "辞退する",
	"friendsYouExceedTextLimit" : "招待メッセージが長すぎます。このセクションは最大 {1} 文字です。このフィールドには {0} 文字あります。",
	"friendsCannotAddYourself" : "ネットワーク連絡先として自分を追加することはできません。",
	"friendsIsYourColleague" : "{0} はネットワーク連絡先です",
	"friendsRecentlyAdded" : "最近ネットワークに追加したユーザーです。",
	"friendsDate" : "日付",
	"friendsCollapseWidget" : "クリックして「ネットワーク」セクションを省略表示",
	"friendsExpandWidget" : "クリックして「ネットワーク」セクションを展開",
	"friendsIsInYourNetwork" : "{0} はネットワーク内にいます。",
	"friendsActionsFor" : "ネットワークのアクション",
	"friendsInviteFollowError" : "{0} をフォローしようとしてエラーが発生しました",
	"friendsInviteTagError" : "{0} にタグを付けようとしたときにエラーが発生しました",
	"friendsPleaseLogIn" : "他のユーザーを自分のネットワークに招待するには、ログインする必要があります",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0} は既にネットワーク内に存在しているため、ネットワークに招待することはできません。",
	"friendsInviteAddTagsFor" : "{0} のタグの追加:",
	"friendsInviteAlsoFollow" : "フォローも行う",
	"friendsInviteReceiveUpdates" : "(更新の受信)",
	"friendsInviteUpdatesDescription" : "フォローすると、そのユーザーの更新情報をホーム・ページやメール要約で受け取れるようになります。",
	"friendsInviteFollowHelp": "詳しくは、{0}ユーザーのフォロー{1} を参照してください。",
	"friendsNetwork" : "ネットワーク",
	"friendsMyNetwork" : "ネットワーク",
	"friendsNetworkFor" : "{0} のネットワーク",
	"friendsRemoveSelected" : "選択対象を削除",
	"friendsRemoveSelectedTip" : "クリックするとネットワークから選択したユーザーを削除します。",
	"friendsNetworkInCommon" : "共通のネットワーク接続が {0} 件あります。",
	"friendsAddToMyNetwork" : "私の Connections ネットワークにあなたを加えたいと思います。",
	"friendsInvite" : "マイ・ネットワークに招待",
	"friendsInvitePerson" : "あなたのネットワークに {0} を招待",
	"friendsInviteMessage" : "私の Connections ネットワークにあなたを加えたいと思います。",
	"friendsInvitedEmailSubject" : "[プロフィール] マイ・ネットワークに招待されています",
	"friendsInvitedEmailMsg1" : "がネットワーク連絡先としてあなたを招待しました。招待には以下のメッセージが含まれています。",
	"friendsInvitedEmailMsg2" : "ネットワークへの招待ページを開く",
	"friendsInvitedEmailMsg3" : "私のネットワークにあなたを加えたいと思います。",
	"friendsInvitedEmailMsg4" : "{0} がネットワーク連絡先としてあなたを招待しました:",
	"friendsInvitedEmailMsg5" : "{0} がネットワーク連絡先としてあなたを招待しました。招待には以下のメッセージが含まれています。",
	"friendsInviteLegalNote" : "この招待を送信すると、{0} があなたのプロフィール・ボードにコメントすることに同意することになります。",
	"friendsInviteFailed" : "サーバー・エラーのため、招待対象者にメール通知が送信されませんでした。ただし、招待対象者は、プロフィール Web アプリケーションによってあなたの招待を受け入れることができます。",
	"personInNetwork" : "ネットワーク連絡先"
})
