define({
	root: /* ***************************************************************** */
		/*                                                                   */
		/* Copyright IBM Corp. 2011, 2015  All Rights Reserved.              */

		({
		   dialogTitle : "Add Image",
		   newUpload : "New Upload",
		   URL : "URL",
		   imageLibrary : "Image Library",
		   description : "Description:",
		   imageFile : "Files:",
		   OK: "OK",
		   cancel: "Cancel",
		   required: "Required field",
		   preview: "Preview:",
		   previewWarning: "The image seems to have failed to load, are you sure this is a valid image url?",
		   alt: "Alternate text:",
		   filesTab: "From Files",
		   images:"Images:",
		   browse:"Browse...",
		   imagePickerTitle:"Insert Images from Files",
		   componentImagePickerTitle:" ${0} uploaded images",
		   /* New String for insert image dialog */
		   title: "Insert Image",
		   uploadBtn: "Upload Image",
		   insertBtn: "Insert Image",
		   uploadTab: "Local Files",
		   externalTab: "Web URL",
		   internalTab: "Existing Images",
		   fileFieldTip: "Drag and drop images from your desktop directly into this window to upload them.",
		   AdditionalSection: "Additional Options",
		   ExpandSection: "Expand Additional Options",
		   CloseSection: "Collapse Additional Options",
		   webURLPrompt: "Web Image URL:",
		   previewPrompt: "Preview area: Large images might take awhile to display.",
		   noExistingImage: "Oops! No image has been added yet.",
		   selectExistingImage: "Select an existing image:",
		   urlMissing: "Enter a URL",
		   urlInvalid: "Invalid URL. Make sure to enter a valid URL and try again.",
		   previousItem: "Previous",
		   nextItem: "Next",
			 oneImageOneTime: "An image is already added into this Window. You can insert only one image at a time.",
			 altTextForImgInList: "Click to select one image"
	}),

	"ar": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"es": true,
	"eu": true,
	"fi": true,
	"fr": true,
	"he": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-br": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sv": true,
	"th": true,
	"tr": true,
	"zh": true,
	"zh-tw": true
});
