/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "انقر هنا لعرض بطاقة العمل",
	"label.semtag.hover.alt" : "انقر لعرض بطاقة العمل لـ {0}",
	"label.semtag.hover.altA11Y" : "انقر هنا أو اضغط على control-enter لعرض بطاقة العمل",
	"label.personcard.dialog.title" : "بطاقة عمل لـ {0}",

	"errorDefaultMsg2" : "حدث خطأ، اتصل بموجه النظام لديك",

	"loadingSTStatus" : "جارٍ تحميل حالة Sametime...",
	"noStatuAvailable" : "لا توجد حالة Sametime متاحة",

	"label.personcard.cardnomarkup" : "لا يمكن استرجاع بطاقة العمل",
	"label.inactive.user.msg" : "لم يعد هذا الشخص مستخدمًا فعالاً.",
	"label.message.information" : "المعلومات:",
	"label.personcard.noprofilemsg" : "ملف المواصفات غير موجود لهذا الشخص",
	"label.personcard.cardreqexpired" : "تم انتهاء صلاحية طلب الحصول على بطاقة العمل",

	"label.bizcard.applinks.less" : "عرض أقل",
	"label.bizcard.applinks.more" : "عرض المزيد",

	"label.personcard.activitieslink" : "الأنشطة",
	"label.personcard.activitieslink.title" : "اضغط هنا لمشاهدة الأنشطة المشتركة",
	"label.personcard.blogslink" : "المدونات",
	"label.personcard.blogslink.title" : "اضغط هنا لرؤية مدونة هذا الشخص",
	"label.personcard.communitieslink" : "المجتمعات",
	"label.personcard.communitieslink.title" : "اضغط هنا لرؤية مجتمعات هذا الشخص",
	"label.personcard.dogearlink" : "علامات التوقف",
	"label.personcard.dogearlink.title" : "انقر هنا لرؤية علامات التوقف الخاصة بهذا الشخص",
	"label.personcard.fileslink" : "الملفات",
	"label.personcard.fileslink.title" : "انقر هنا لرؤية الملفات المشتركة لهذا الشخص",
	"label.personcard.forumlink" : "المنتديات",
	"label.personcard.forumlink.title" : "انقر هنا لرؤية منشورات المنتدى لهذا الشخص",
	"label.personcard.homepagelink" : "الصفحة الرئيسية",
	"label.personcard.homepagelink.title" : "انقر هنا لرؤية الصفحة الرئيسية لهذا الشخص",
	"label.personcard.mobilelink" : "الهاتف المحمول",
	"label.personcard.mobilelink.title" : "انقر هنا لرؤية صفحة الهاتف المحمول لهذا الشخص",
	"label.personcard.newslink" : "الأخبار",
	"label.personcard.newslink.title" : "انقر هنا لرؤية الأخبار لهذا الشخص",
	"label.personcard.profilelink" : "ملف المواصفات",
	"label.personcard.profilelink.title" : "انقر هنا لرؤية ملف مواصفات هذا الشخص",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "انقر هنا لرؤية مشاركات quickr لهذا الشخص",
	"label.personcard.wikislink" : "صفحات Wiki",
	"label.personcard.wikislink.title" : "انقر هنا لرؤية صفحات wikis لهذا الشخص",

	"personCardMoreActions" : "‏إجراءات إضافية‏",
	"personCardMoreActionsAltText" : "انقر لرؤية قائمة التصرفات",

	"label.bizcard.dismiss": "اضغط خروج للخروج من بطاقة العمل هذه.",
	"label.bizcard.fullProfile": "ملف مواصفات كامل",
	"label.bizcard.activities": "الأنشطة",
	"label.bizcard.communities": "المجتمعات",
	"label.bizcard.files": "الملفات",
	"label.bizcard.forums": "المنتديات",
	"label.bizcard.bookmarks": "علامات التوقف",
	"label.bizcard.blogs": "المدونات",
	"label.bizcard.wikis": "صفحات Wiki",

	"personCardAddAsColleagues" : "دعوة إلى \"شبكة الاتصال الخاصة بي\"",
	"personCardAddAsMyColleagues" : "دعوة إلى \"شبكة الاتصال الخاصة بي\"",
	"personCardFollow" : "متابعة",
	"personCardUnfollow" : "إيقاف المتابعة",
	"personCardChat" : "محادثة",
	"personCardCall" : "مكالمة",
	"personCardSendMail" : "إرسال بريد إلكتروني",
	"personCardSendEMail" : "إرسال بريد إلكتروني",
	"personCardProxyStatusAvailable" : "أنا متاح",
	"personCardDownloadVCard" : "تنزيل vCard",

	"friends" : "شبكة الاتصال",
	"friendsFullPageTitle" : "شبكة الاتصال",
	"friendsMenuTitleAllContacts" : "كل جهات الاتصال لشبكة الاتصال",
	"friendsMenuTitleMyContacts" : "جهات الاتصال لشبكة الاتصال الخاصة بي",
	"friendsInvitations" : "الدعوات",
	"friendsMenuTitleInCommon" : "الأشخاص المشتركون",
	"friendsShowAllCommonFriends" : "عرض الكل...",
	"friendsViewAllFriends" : "مشاهدة كل ({0})",
	"friendsSendFriendRequest" : "إرسال طلب",
	"friendsNoFriends" : "لا توجد جهات اتصال في شبكة الاتصال مرتبطة بملف المواصفات هذا",
	"friendsColleaguesInvite" : "دعوة {0} ليكون إحدى جهات اتصال شبكة الاتصال الخاصة بك",
	"friendsColleaguesFor" : "جهات اتصال الشبكة لـ {0}",
	"friendsNewInv" : "{0} دعوة جديدة",
	"friendsNewInvs" : "{0} دعوات جديدة",
	"friendsLoading" : "جارٍ تحميل شبكة الاتصال...",
	"friendsLoadingInv" : "جارٍ تحميل الدعوات...",
	"friendsSelectFriendForRemoval" : "اختر جهات الاتصال التي تريد إزالتها أولاً.",
	"friendsRemoved" : "تمت إزالة جهة (جهات) اتصال شبكة الاتصال.",
	"friendsInvSent" : "لم يتم إرسال دعوة لأن الدعوة معلقة بالفعل.",
	"friendsRemovedSelected" : "إزالة من شبكة الاتصالات الخاصة بي",
	"friendsSortByDisplayName" : "اسم العرض",
	"friendsSortByRecent" : "حديث",
	"friendsTelephone" : "الهاتف:",
	"friendsEmail" : "البريد الإلكتروني:",
	"friendsAltEmail" : "البريد الإلكتروني البديل:",
	"friendsNewInvitationsCount" : "تتوفر لديك {0} من الدعوات الجديدة",
	"friendsNoInv" : "بلا دعوات",
	"friendsInCommonSingle" : "تتوفر لديك {0} من جهات الاتصال المشتركة",
	"friendsInCommonMulti" : "تتوفر لديك {0} من جهات الاتصال المشتركة",
	"friendsIncludeMsgForInv" : "تضمين رسالة مع دعوتك:",
	"friendsInitialMsgForInv" : "أود إضافتك إلى كشف جهات اتصال شبكة اتصال Connections الخاص بي.",
	"friendsSendInvAction" : "إرسال دعوة",
	"friendsCancelInvAction" : "إلغاء‏",
	"friendsAcceptAction" : "قبول",
	"friendsIgnoreAction" : "تجاهل",
	"friendsYouExceedTextLimit" : "رسالة الدعوة الخاصة بك طويلة للغاية. يمكن أن يكون {1} من الأحرف كحد أقصى. ويوجد {0} من الأحرف في هذا المجال.",
	"friendsCannotAddYourself" : "لا يمكن إضافة نفسك كإحدى جهات اتصال شبكة الاتصال.",
	"friendsIsYourColleague" : "{0} يعد إحدى جهات اتصال شبكة الاتصال الخاصة بك",
	"friendsRecentlyAdded" : "الأشخاص الذين قمت بإضافتهم مؤخرًا لشبكة الاتصال الخاصة بك.",
	"friendsDate" : "التاريخ",
	"friendsCollapseWidget" : "انقر لطي قسم الشبكة",
	"friendsExpandWidget" : "انقر لعرض قسم الشبكة",
	"friendsIsInYourNetwork" : "{0} موجود في شبكة الاتصال الخاصة بك.",
	"friendsActionsFor" : "تصرفات شبكة الاتصال",
	"friendsInviteFollowError" : "حدث خطأ أثناء محاولة متابعة {0}",
	"friendsInviteTagError" : "حدث خطأ أثناء محاولة وضع شارة تعليم على {0}",
	"friendsPleaseLogIn" : "يرجى تسجيل الدخول لدعوة الأشخاص إلى شبكة الاتصال الخاصة بك",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "لا يمكن إرسال دعوة الى شبكة الاتصال الخاصة بك لأن {0} موجود بالفعل في شبكة الاتصال الخاصة بك.",
	"friendsInviteAddTagsFor" : "شارات التعليم لـ {0}:",
	"friendsInviteAlsoFollow" : "ومتابعة أيضًا",
	"friendsInviteReceiveUpdates" : "(تلقي التحديثات)",
	"friendsInviteUpdatesDescription" : "يمكنك تلقي التحديثات الخاصة بالأشخاص الذين تقوم بمتابعتهم في الصفحة الرئيسية وفي ملخص البريد الإلكتروني.",
	"friendsInviteFollowHelp": "للحصول على المزيد من المعلومات، راجع {0}متابعة الأشخاص{1}.",
	"friendsNetwork" : "شبكة الاتصال",
	"friendsMyNetwork" : "شبكة الاتصال",
	"friendsNetworkFor" : "شبكة اتصال لـ {0}",
	"friendsRemoveSelected" : "إزالة المحدد",
	"friendsRemoveSelectedTip" : "انقر لإزالة الأشخاص المحددين من شبكة الاتصال الخاصة بك.",
	"friendsNetworkInCommon" : "توجد لديك {0} من اتصالات الشبكة المشتركة.",
	"friendsAddToMyNetwork" : "أود إضافتك إلى كشف جهات اتصال شبكة اتصال Connections الخاص بي.",
	"friendsInvite" : "دعوة إلى \"شبكة الاتصال الخاصة بي\"",
	"friendsInvitePerson" : "دعوة {0} إلى شبكة الاتصال الخاصة بك",
	"friendsInviteMessage" : "أود إضافتك إلى شبكة اتصال Connections الخاصة بي.",
	"friendsInvitedEmailSubject" : "[Profiles] أنت مدعو للانضمام إلى شبكة الاتصال الخاصة بي",
	"friendsInvitedEmailMsg1" : "قام بدعوتك لكي تكون إحدى جهات اتصال شبكته مع تضمين الرسالة التالية في الدعوة:",
	"friendsInvitedEmailMsg2" : "فتح صفحة \"دعوة شبكة الاتصال\" الخاصة بك",
	"friendsInvitedEmailMsg3" : "أود إضافتك إلى شبكة الاتصال الخاصة بي.",
	"friendsInvitedEmailMsg4" : "قام {0} بدعوتك لتصبح إحدى جهات الاتصال في شبكته:",
	"friendsInvitedEmailMsg5" : "قام {0} بدعوتك لكي تكون إحدى جهات الاتصال في شبكته مع تضمين الرسالة التالية في الدعوة:",
	"friendsInviteLegalNote" : "من خلال إرسال هذه الدعوة، فإنك توافق على السماح لـ {0} بالتعقيب على لوحة ملف المواصفات الخاصة بك.",
	"friendsInviteFailed" : "نظرًا لحدوث خطأ في وحدة الخدمة، لم يتم إرسال إعلام بالبريد الإلكتروني إلى المدعو. ومع ذلك، سيظل المدعو قادرًا على قبول دعوتك من خلال تطبيق الويب \"Profiles\".",
	"personInNetwork" : "جهة اتصال شبكة الاتصال"
})
