/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrer par :",
"SHOW":"Afficher :",
"ACL_FILTER_LABEL":"Filtrer par visibilité",
"PARENT_FILTER_LABEL":"Filtrer par conteneur",
"TYPE_FILTER_LABEL":"Filtrer par type",
"PAGING_TOP":"Pagination principale",
"PAGING_BOTTOM":"Pagination secondaire",
"PREVIOUS":"Précédent",
"NEXT":"Suivant",
"PAGE":"Page {0} sur {1}",
"PAGE_COLON":"Page :",
"RESULTS":"{span}{0} - {1}{/span} sur {2}",
"ITEMS":"{0} éléments",
/* Application names */
"ACTIVITIES":"Activités",
"BLOGS":"Blogues",
"CALENDAR":"Agenda",
"COMMUNITIES":"Communautés",
"BOOKMARKS":"Signets",
"DOGEAR":"Signets",
"EVENTS":"Evénements",
"FILES":"Fichiers",
"FORUMS":"Forums",
"PROFILES":"Profils",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Flux",
"STATUS_UPDATES":"Mises à jour de statut",
"ONECOMMENT":"1 commentaire",
"COMMENTS":"{0} commentaires",
"ONEPERSON":"1 personne",
"PEOPLE":"{0} personnes",
"TAGS":"Etiquettes :",
"TAGSMORE":"et {0} de plus",
"NORESULTSMESSAGE":"Aucun résultat pour cette recherche",
"JAN":"Janvier",
"FEB":"Février",
"MAR":"Mars",
"APR":"Avril",
"MAY":"Mai",
"JUN":"Juin",
"JUL":"Juillet",
"AUG":"Août",
"SEP":"Septembre",
"OCT":"Octobre",
"NOV":"Novembre",
"DEC":"Décembre",
"NO_CONTACT":"La recherche n'a pas été effectuée car le serveur n'a pas pu être contacté",
"SERVER_ERROR":"La recherche n'a pas été effectuée en raison d'une erreur liée au serveur",
"SORT_BY":"Trier par :",
"SORT_RELEVANCE":"Pertinence",
"SORT_DATE":"Date",
"SORT_LAST_UPDATED":"Dernière mise à jour",
"SORT_DUE_DATE":"Date d'échéance",
"SORT_VISITS":"Visites",
"SORT_COMMENTS":"Commentaires",
"SORT_RECOMMENDATION":"Recommandations",
"SORT_POPULARITY":"Popularité",
"SORT_FIRSTNAME":"Prénom",
"SORT_LASTNAME":"Nom",
"SORT_DOWNLOADS":"Téléchargements",
"SORT_TYPE":"Type",
"SORT_SIZE":"Taille",
"SORT_TITLE":"Titre",
"PRIVATE":"Privé",
"MODERATED":"Modéré",
"COMMUNITY_ACTIVITY":"Activité de communauté",
"COMMUNITY_BLOG":"Blogue de communauté",
"COMMUNITY_FILE":"Fichier de communauté",
"COMMUNITY_FORUM":"Forum de communauté",
"COMMUNITY_WIKI":"Wiki de communauté",
"COMMUNITY_FEED":"Flux de communauté",
"COMMUNITY_BOOKMARK":"Signet de communauté",
"NO_TAG":"Pas encore d'étiquette",
"NO_DATE":"Pas encore de date",
"NO_PEOPLE":"Encore personne",
"REMOVE_FILTER_LABEL":"Cliquez pour retirer",
"REMOVE_FILTER_TITLE":"Retirer",
"REMOVE_FILTER_TOOLTIP":"Retirer ce filtre",
"COMMENT_ON":"Commenter :",
"EXPAND_COLLAPSE":"Cliquez pour développer/réduire",
"EXPAND":"Développer",
"COLLAPSE":"Réduire",
"EXPAND_MONTHS_FILTER":"Développer le filtre des mois de l'année {0}",
"SORT_RELEVANCE_LABEL":"Cliquez pour trier par pertinence",
"SORT_DATE_LABEL":"Cliquez pour trier par date",
"SORT_UPDATED_LABEL":"Cliquez pour trier par la mise à jour la plus récente",
"SORT_DUE_LABEL":"Cliquez pour trier par date d'échéance",
"SORT_VISITS_LABEL":"Cliquez pour trier par nombre de visites",
"SORT_COMMENTS_LABEL":"Cliquez pour trier par nombre de commentaires",
"SORT_RECOMMENDATIONS_LABEL":"Cliquez pour trier par nombre de recommandations",
"SORT_POPULARITY_LABEL":"Cliquez pour trier par popularité",
"SORT_FIRST_NAME_LABEL":"Cliquez pour trier par prénom",
"SORT_LAST_NAME_LABEL":"Cliquez pour trier par nom",
"RATING":"Recommandations",
"GRADUATED":"Promue(s)",
"ONEVOTE":"1 vote",
"VOTES":"{0} votes",
"BOOKMARK_THIS_RESULT":"Insérer un signet ici",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inactif)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} personnes ont ajouté un signet",
/* eg from an Activity */
"FROMANACTIVITY":"depuis une activité",
"FROMABLOG":"depuis un blogue",
"FROMANIDEATIONBLOG":"depuis un blogue d'échange d'idées",
"FROMANEVENT":"depuis un événement",
"FROMAFORUM":"depuis un forum",
"FROMAWIKI":"depuis un wiki",
"FROMACOMMUNITY":"depuis une communauté",
"FROMXCOMMUNITIES":"depuis {0} communautés",
/* For search results parentage */
"ACTIVITY_ALONE":"Activité",
"BLOG_ALONE":"Blogue",
"IDEATIONBLOG_ALONE":"Blogue d'échange d'idées",
"ENTRY_ALONE":"Entrée",
"EVENT_ALONE":"Evénement",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Communauté",
"XCOMMUNITIES_ALONE":"{0} communautés",
"SHAREDCOMMUNITIES":"Partagé avec ces communautés",
"INACOMMUNITY":"dans une communauté",
"LASTUPDATED":"Dernière mise à jour de l'index de recherche :",
"NODESCRIPTION":"Aucune description ni récapitulatif pour ce résultat.",
"ATTACHMENT":"Pièce jointe :",
"ACTIVITY":"Activité :",
"ACTIVITYBOOKMARK":"Signet d'activité :",
"ACTIVITYCOMMENT":"Commentaire d'activité :",
"ACTIVITYENTRY":"Entrée d'activité :",
"ACTIVITYSECTION":"Section d'activité :",
"ACTIVITYTODO":"Tâche d'activité :",
"BLOG":"Blogue :",
"BLOGENTRY":"Entrée de blogue :",
"BLOGCOMMENT":"Commentaire de blogue :",
"BOOKMARK":"Signet :",
"CALENDAREVENT":"Evénement :",
"CATEGORY":"Catégorie :",
"COMMENT":"Commentaire :",
"COMMUNITY":"Communauté :",
"ENTRY":"Entrée :",
"EVENTDATEON":"Le : {0}",
"EVENTISALLDAY":"Evénement durant toute la journée",
"EVENTREPEATS":"Répétitif",
"FEED":"Flux :",
"FILE":"Fichier :",
"FORUM":"Forum :",
"FORUMCATEGORY":"Catégorie de forum :",
"FORUMTOPIC":"Sujet du forum :",
"IDEA":"Idée :",
"IDEACOMMENT":"Commentaire d'idée",
"IDEATIONBLOG":"Blogue d'échange d'idées :",
"PAGE":"Page :",
"PROFILE":"Profil :",
"SECTION":"Section :",
"STATUSUPDATE":"Mise à jour de statut",
"STATUSUPDATE_PREFIX":"Mise à jour du statut :",
"TOPIC":"Sujet :",
"TOPIC_WITH_ATTACHMENT":"Sujet",
"WIKITYPE":"Wiki :",
"WIKIPAGE":"Page wiki",
"WIKIFILE":"Pièce jointe de wiki :",
"SEARCH":"Recherche :",
"TODO":"Tâche :",
"ALLRESULTS":"Tous les résultats",
"PUBLICCONTENT":"Contenu public",
"MYCONTENT":"Mon contenu",
"RESULTNOTFOUND":"Vous n'avez pas trouvé ce que vous cherchiez ?",
"TEMPDIFFICULTIES":"Remarque : En raison de difficultés temporaires à indexer, votre recherche n'incluait pas {0} ayant été modifiés au cours des {1} derniers jours.",
"TRYLATER":"Veuillez réessayer ultérieurement.",
"MULTIPLETEMPDIFFICULTIES":"Remarque : En raison de difficultés temporaires à indexer, votre recherche n'incluait pas {0} ayant été récemment modifiés.",
"YOUAREAUTHOR":"Vous êtes un auteur",
"YOUARECONTRIBUTOR":"Vous êtes in contributeur",
"YOUAREOWNER":"Vous êtes un propriétaire",
"YOUAREMEMBER":"Vous êtes un membre",
/* Profiles */
"MYNETWORK":"Mon réseau",
"ALLPEOPLE":"Toutes les personnes",
"EXCLUDEINACTIVE":"Exclure les personnes inactives",
"PHONE":"Tél. :",
"EMAIL":"Adresse électronique :",
/* Communities */
"ALLCOMMUNITIES":"Toutes les communautés",
"PUBLICCOMMUNITIES":"Communautés publiques",
"MYCOMMUNITIES":"Mes communautés",
"EVERYTHINGCOMMUNITIES":"Tout depuis Communautés",
"COMMUNITIESONLY":"Communautés",
"COMMUNITIESCONTENT":"Contenu depuis Communautés",
/* Activities */
"ALLACTIVITIES":"Toutes les activités",
"PUBLICACTIVITIES":"Activités publiques",
"MYACTIVITIES":"Mes activités",
"EVERYTHINGACTIVITIES":"Tout depuis Activités",
"ACTIVITIESONLY":"Activités",
"SECTIONSACTIVITIES": "Sections depuis Activités",
"ENTRIESACTIVITIES":"Entrées depuis Activités",
"TODOSACTIVITIES":"Tâches depuis Activités",
"BOOKMARKSACTIVITIES":"Signets depuis Activités",
"FILESACTIVITIES":"Pièces jointes depuis Activités",
"ALLTYPESACTIVITIES":"Tous les types d'activités",
"COMMUNITYACTIVITIES":"Activités depuis Communautés",
"STANDALONEACTIVITIES":"Activités autonomes",
/* Forums */
"ALLFORUMS":"Tous les forums",
"PUBLICFORUMS":"Forums publics",
"MYFORUMS":"Mes forums",
"EVERYTHINGFORUMS":"Tout depuis Forums",
"FORUMSONLY":"Forums",
"TOPICSFORUMS":"Sujets du forum",
"FORUMCATEGORIES": "Catégories de forum",
"FILESFORUMS":"Pièces jointes depuis Forums",
"ALLTYPESFORUMS":"Tous les types de forums",
"COMMUNITYFORUMS":"Forums depuis Communautés",
"STANDALONEFORUMS":"Forums autonomes",
/* Blogs */
"ALLBLOGS":"Tous les blogues",
"PUBLICBLOGS":"Blogues publics",
"MYBLOGS":"Mes blogues",
"EVERYTHINGBLOGS":"Tout depuis Blogues",
"BLOGSONLY":"Blogues",
"ENTRIESBLOGS":"Entrées de blogue",
"FILESBLOGS":"Pièces jointes depuis Blogues",
"EVERYTHINGIDEATIONBLOGS":"Tout depuis Blogues d'échange d'idées",
"BLOGSIDEATIONBLOGS":"Blogues d'échange d'idées",
"BLOGSIDEAS":"Idées",
"ALLTYPESBLOGS":"Tous les types de blogues",
"COMMUNITYBLOGS":"Blogues depuis Communautés",
"COMMUNITYIDEATIONBLOGS":"Blogues d'échange d'idées depuis Communautés",
"STANDALONEBLOGS":"Blogues autonomes",
/* Bookmarks */
"ALLBOOKMARKS":"Tous les signets",
"PUBLICBOOKMARKS":"Signets publics",
"MYBOOKMARKS":"Mes signets",
"ALLTYPESBOOKMARKS":"Tous les types de signets",
"COMMUNITYBOOKMARKS":"Signets depuis Communautés",
"STANDALONEBOOKMARKS":"Signets autonomes",
/* Files */
"ALLFILES":"Tous les fichiers",
"PUBLICFILES":"Fichiers publics",
"MYFILES":"Mes fichiers",
"ALLTYPESFILES":"Tous les types de fichiers",
"COMMUNITYFILES":"Fichiers depuis Communautés",
"STANDALONEFILES":"Fichiers autonomes",
"NUMDOWNLOADS":"{0} téléchargement",
/* Wikis */
"ALLWIKIS":"Tous les wikis",
"PUBLICWIKIS":"Wikis publics",
"MYWIKIS":"Mes wikis",
"EVERYTHINGWIKIS":"Tout depuis Wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Pages wiki",
"FILESWIKIS":"Pièces jointes depuis Wikis",
"ALLTYPESWIKIS":"Tous les types de wikis",
"COMMUNITYWIKIS":"Wikis depuis Communautés",
"STANDALONEWIKIS":"Wikis autonomes",
/* Status Updates */
"ALLSTATUSUPDATES":"Toutes les mises à jour de statut",
"PUBLICSTATUSUPDATES":"Mises à jour de statut public",
"MYSTATUSUPDATES":"Mes mises à jour de statut",
"ALLTYPESSTATUSUPDATES":"Tous les types de mise à jour de statut",
"COMMUNITYSTATUSUPDATES":"Mises à jour de statut des communautés",
"STANDALONESTATUSUPDATES":"Mises à jour de statut des profils",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Cette URL a été mise en signet par un certain nombre d'utilisateurs",
"BOOKMARKEDCOMMUNITY":"Cette communauté a été mise en signet par un certain nombre d'utilisateurs",
"BOOKMARKEDPROFILE":"Ce profil a été mis en signet par un certain nombre d'utilisateurs",
"BOOKMARKEDBLOG":"Ce blogue a été mis en signet par un certain nombre d'utilisateurs",
"COMMUNITYBLOG":"Il s'agit d'un blogue au sein d'une communauté",
"BOOKMARKEDACTIVITY":"Cette activité a été mise en signet par un certain nombre d'utilisateurs",
"COMMUNITYACTIVITY":"Il s'agit d'une activité au sein d'une communauté",
"BOOKMARKEDFILE":"Ce fichier a été mis en signet par un certain nombre d'utilisateurs",
"COMMUNITYFILE":"Il s'agit d'un fichier au sein d'une communauté",
"BOOKMARKED":"Ce wiki a été mis en signet par un certain nombre d'utilisateurs",
"COMMUNITYWIKI":"Il s'agit d'un wiki au sein d'une communauté",
"BOOKMARKEDFORUM":"Ce forum a été mis en signet par un certain nombre d'utilisateurs",
"COMMUNITYFORUM":"Il s'agit d'un forum au sein d'une communauté",
"ALLTAGANDTTILE":"Pour afficher tous les titres et toutes les étiquettes de cette URL, cliquez sur ce bouton",
"TAGS_ARE_FROM":"Ce résultat de recherche peut inclure des étiquettes de :",
"BOOKMARKS_TITLE":"Signets",
"COMMUNITIES_TITLE":"Communautés",
"ACTIVITIES_TITLE":"Activités",
"HELP":"Aide",
"MORESTATUSUPDATES":"Afficher davantage de correspondances de mise à jour de statut",
"TITLE_PREFIX":"titre :",
"LATEST_MESSAGE":"Dernier message",
"LATEST_STATUS_UPDATE":"Dernière mise à jour du statut",
"LATEST_COMMUNITY_STATUS_UPDATE":"Dernière mise à jour du statut de la communauté",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Dernière mise à jour du statut des communautés",
"SEARCH_RESULTS":"Tout le contenu - Résultats de la recherche",
"ACTIVITIES_SEARCH_RESULTS":"Activités - Résultats de la recherche",
"BLOGS_SEARCH_RESULTS":"Blogues - Résultats de la recherche",
"BOOKMARKS_SEARCH_RESULTS":"Signets - Résultats de la recherche",
"COMMUNITIES_SEARCH_RESULTS":"Communautés - Résultats de la recherche",
"FILES_SEARCH_RESULTS":"Fichiers - Résultats de la recherche",
"FORUMS_SEARCH_RESULTS":"Forums - Résultats de la recherche",
"PROFILES_SEARCH_RESULTS":"Profils - Résultats de la recherche",
"DIRECTORY_SEARCH_RESULTS":"Annuaire ${orgName} - Résultats de la recherche",
"WIKIS_SEARCH_RESULTS":"Wikis - Résultats de la recherche",
"STATUS_UPDATES_SEARCH_RESULTS":"Mises à jour de statut - Résultats de la recherche",
"VIEW_ALL":"{span}Tout afficher{/span} ({0})",
"MATCHING_ONE_OF":"Correspondant à l'une des valeurs suivantes :",
"MATCHING_ALL_OF":"Correspondant à toutes les valeurs suivantes :",
"MATCHING":"Correspondance :",
"MATCHING_DOC_TYPE":"Type de document correspondant :",
"BOOKMARK_HELP":"Aide sur les signets",
"CLOSE_BOOKMARK_HELP":"Fermer l'aide sur les signets",
"DOCUMENT_TYPE_PREFIX":"Type de document :",
"FILE_PREVIEW_ONLY":"(Mode Aperçu uniquement)"
})

