/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informations pour le noeud : ",
	"INSTALLED": "Vérification des services installés",
	"RESUMETOKENS": "Vérification des jetons de reprise",
	"SEEDLISTS": "Vérification des listes de départ pour s'assurer qu'elles sont disponibles",
	"CALENDARS": "Vérification des calendriers pour s'assurer qu'ils ont été configurés correctement",
	"VARIABLES": "Vérification des variables WebSphere pour s'assurer qu'elles ont été définies",
	"TASKS": "Vérification des tâches d'indexation activées",
	"INDEXFILES": "Vérification des fichiers requis dans le dossier d'index",
	"LOGS": "Consultation des erreurs dans les fichiers journaux",
	"CONFIGFILES": "Consultation des fichiers de configuration",
	"DICTIONARIES": "Vérification du nombre de dictionnaires ayant été activés",
	"SYNC": "Vérification du statut des noeuds",
	"DBRECORDS": "Vérification des enregistrements de la base de données",
	"INSTALLEDMSG": "Le service suivant est installé : ",
	"RESUMETOKENSMSG": "Jeton de reprise pour : ",
	"SEEDLISTSMSG": "Impossible d'obtenir la liste de départ pour: ",
	"CALENDARSMSG": "Vérification du calendrier concluante : ",
	"VARIABLESMSG": "Variable : ",
	"TASKSMSG": "La tâche suivante est activée : ",
	"INDEXFILESMSG" : "Les fichiers suivants se trouvent dans le dossier d'index de recherche : ",
	"LOGSMSG" : "Consultez les messages d'erreur suivants : ",
	"CONFIGFILESMSG" : "Les fichiers de configuration suivants ont été trouvés : ",
	"DICTIONARIESMSG" : "Le nombre de dictionnaires activés est : ",
	"INSYNC": "Tous les noeuds sont synchronisés",
	"OUTOFSYNC": "Le nombre de noeuds non synchronisés est : ",
	"NOTBLOCKED": "Aucun noeud n'est bloqué",
	"BLOCKED": "Le nombre de noeuds bloqués est : ",
	"INDATE": "Tous les noeuds sont à jour",
	"OUTOFDATE": "Le nombre de noeuds périmés est : ",
	"NUMOFDOCS": "Le nombre de documents dans la base de données est ",
	"FILESTOCONVERT": "Le nombre de documents de fichier à convertir est ",
	"CONVERTEDFILES": "Le nombre de fichiers convertis est ",
	"TOTALFILES": "Nombre total de fichiers dans la base de données ",
	"ERROR":"Erreur",
	"ERROR_PREFIX":"Erreur :",
	"INFO":"Informations",
	"INFO_PREFIX":"Informations :",
	"WARNING":"Avertissement",
	"WARNING_PREFIX":"Avertissement :",
	"LOADING_MESSAGE": "Chargement",
	"SERVER_STATUS": "Statut de serveur",
	"INITIAL_INDEXING_EXCEPTIONS": "Exceptions d'indexation initiale",
	"SYS_OUT_EXCEPTIONS": "Exceptions journal SystemOut",
	"SEEDLIST_VALIDATE": "Validation de liste de départ",
	"ERRORS_DURING_INITIAL_INDEXING":"Les exceptions suivantes se sont produites lors de la création d'un index initial",
	"CRAWL_FAILED": "Impossible de balayer les données relatives au service suivant : ",
	"EXCEPTION_ENCOUNTERED": "Le balayage a échoué avec le message suivant : ",
	"SAND_VALIDATE": "Validation SAND",
	"CHECK_FOR_SAND_FILES":"Vérification des fichiers SAND",
	"IS_FILE_AVAILABLE":"Vérification du fichier pour s'assurer qu'il a été créé : ",
	"ERRORS_DURING_INITIAL_INDEXING":"Les exceptions suivantes se sont produites lors de la création d'un index initial",
	"CRAWL_FAILED":"Impossible de balayer les données relatives au service suivant : ",
	"EXCEPTION_ENCOUNTERED":"Le balayage a échoué avec le message suivant : "
})

