/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Tilføj billede",
   newUpload : "Ny uploadning",
   URL : "URL",
   imageLibrary : "Billedbibliotek",
   description : "Beskrivelse:",
   imageFile : "Filer:",
   OK: "OK",
   cancel: "Annullér",
   required: "Påkrævet felt",
   preview: "Vis resultat:",
   previewWarning: "Billedet kunne ikke indlæses. Er du sikker på, at det er en gyldig billed-URL?",
   alt: "Alternativ tekst:",
   filesTab: "Fra Filer",
   images:"Billeder:",
   browse:"Gennemse...",
   imagePickerTitle:"Indsæt billeder fra Filer",
   componentImagePickerTitle:" ${0} uploadede billeder",
   /* New String for insert image dialog */
   title: "Indsæt billede",
   uploadBtn: "Upload billede",   
   insertBtn: "Indsæt billede",
   uploadTab: "Lokale filer",
   externalTab: "Web-URL",
   internalTab: "Eksisterende billeder",
   fileFieldTip: "Træk og placér billeder direkte fra dit skrivebord til dette vindue for at uploade dem.",
   AdditionalSection: "Flere indstillinger",
   ExpandSection: "Udvid Flere indstillinger",
   CloseSection: "Skjul Flere indstillinger",
   webURLPrompt: "Webbilled-URL:",
   previewPrompt: "Forhåndsvisningsområde: Det kan tage et stykke tid at vise store billeder.",
   noExistingImage: "Fejl. Der er ikke tilføjet noget billede endnu.",
   selectExistingImage: "Vælg et eksisterende billede:",
   urlMissing: "Angiv en URL",
   urlInvalid: "Ugyldig URL. Angiv en gyldig URL, og prøv igen.",
   previousItem: "Forrige",
   nextItem: "Næste",
   oneImageOneTime: "Der er allerede tilføjet et billede til dette vindue. Du kan kun indsætte ét billede ad gangen.",
   loadingErrorMsg: "Der er opstået en fejl under indlæsning af eksisterende billeder. Prøv igen senere.",
   urlInputTooltip: "Angiv URL'en til billedet"
})

