/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Click here to view business card",
	"label.semtag.hover.alt" : "Click to view business card for {0}",
	"label.semtag.hover.altA11Y" : "Click here or press control-enter to view the business card",
	"label.personcard.dialog.title" : "Business card for {0}",

	"errorDefaultMsg2" : "An error has occurred, contact your system administrator",

	"loadingSTStatus" : "Loading Sametime status...",
	"noStatuAvailable" : "No Sametime status available",

	"label.personcard.cardnomarkup" : "The business card could not be retrieved",
	"label.inactive.user.msg" : "This person is no longer an active user",
	"label.message.information" : "Information:",
	"label.personcard.noprofilemsg" : "A profile does not exist for this person",
	"label.personcard.cardreqexpired" : "The request to get the business card expired",

	"label.bizcard.applinks.less" : "Show less",
	"label.bizcard.applinks.more" : "Show more",

	"label.personcard.activitieslink" : "Activities",
	"label.personcard.activitieslink.title" : "Click here to see shared activities",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Click here to see this person's blog",
	"label.personcard.communitieslink" : "Communities",
	"label.personcard.communitieslink.title" : "Click here to see this person's communities",
	"label.personcard.dogearlink" : "Bookmarks",
	"label.personcard.dogearlink.title" : "Click here to see this person's bookmarks",
	"label.personcard.fileslink" : "Files",
	"label.personcard.fileslink.title" : "Click here to see this person's shared files",
	"label.personcard.forumlink" : "Forums",
	"label.personcard.forumlink.title" : "Click here to see this person's forum posts",
	"label.personcard.homepagelink" : "Home",
	"label.personcard.homepagelink.title" : "Click here to see this person's homepage",
	"label.personcard.mobilelink" : "Mobile",
	"label.personcard.mobilelink.title" : "Click here to see this person's mobile page",
	"label.personcard.newslink" : "News",
	"label.personcard.newslink.title" : "Click here to see this person's news",
	"label.personcard.profilelink" : "Profile",
	"label.personcard.profilelink.title" : "Click here to see this person's profile",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Click here to see this person's quickr shares",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Click here to see this person's wikis",

	"personCardMoreActions" : "More Actions",
	"personCardMoreActionsAltText" : "Click for action menu",

	"label.bizcard.dismiss": "Press escape to dismiss this business card.",
	"label.bizcard.fullProfile": "Full Profile",
	"label.bizcard.activities": "Activities",
	"label.bizcard.communities": "Communities",
	"label.bizcard.files": "Files",
	"label.bizcard.forums": "Forums",
	"label.bizcard.bookmarks": "Bookmarks",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Invite to My Network",
	"personCardAddAsMyColleagues" : "Invite to My Network",
	"personCardFollow" : "Follow",
	"personCardUnfollow" : "Stop Following",
	"personCardChat" : "Chat",
	"personCardCall" : "Call",
	"personCardSendMail" : "Send Email",
	"personCardSendEMail" : "Send Email",
	"personCardProxyStatusAvailable" : "I am available",
	"personCardDownloadVCard" : "Download vCard",

	"friends" : "Network",
	"friendsFullPageTitle" : "Network",
	"friendsMenuTitleAllContacts" : "All Network Contacts",
	"friendsMenuTitleMyContacts" : "My Network Contacts",
	"friendsInvitations" : "Invitations",
	"friendsMenuTitleInCommon" : "People in Common",
	"friendsShowAllCommonFriends" : "Show all...",
	"friendsViewAllFriends" : "View All ({0})",
	"friendsSendFriendRequest" : "Send request",
	"friendsNoFriends" : "No network contacts are associated with this profile",
	"friendsColleaguesInvite" : "Invite {0} to be your network contact",
	"friendsColleaguesFor" : "Network Contacts for {0}",
	"friendsNewInv" : "{0} new invitation",
	"friendsNewInvs" : "{0} new invitations",
	"friendsLoading" : "Loading Network...",
	"friendsLoadingInv" : "Loading Invitations...",
	"friendsSelectFriendForRemoval" : "Select the contacts you want to remove first.",
	"friendsRemoved" : "Network contact(s) removed.",
	"friendsInvSent" : "No invitation sent because an invitation is already pending.",
	"friendsRemovedSelected" : "Remove from My Network",
	"friendsSortByDisplayName" : "Display Name",
	"friendsSortByRecent" : "Recent",
	"friendsTelephone" : "Telephone:",
	"friendsEmail" : "Email:",
	"friendsAltEmail" : "Alternate Email:",
	"friendsNewInvitationsCount" : "You have {0} new invitation(s)",
	"friendsNoInv" : "No invitations",
	"friendsInCommonSingle" : "You have {0} network contact in common",
	"friendsInCommonMulti" : "You have {0} network contacts in common",
	"friendsIncludeMsgForInv" : "Include a message with your invitation:",
	"friendsInitialMsgForInv" : "I'd like to add you to my Connections network contacts list.",
	"friendsSendInvAction" : "Send Invitation",
	"friendsCancelInvAction" : "Cancel",
	"friendsAcceptAction" : "Accept",
	"friendsIgnoreAction" : "Ignore",
	"friendsYouExceedTextLimit" : "Your invite message is too long. It can be a maximum of {1} characters. There are {0} characters in this field.",
	"friendsCannotAddYourself" : "You cannot add yourself as a network contact.",
	"friendsIsYourColleague" : "{0} is your network contact",
	"friendsRecentlyAdded" : "People you have recently added to your network.",
	"friendsDate" : "Date",
	"friendsCollapseWidget" : "Click to collapse the network section",
	"friendsExpandWidget" : "Click to expand the network section",
	"friendsIsInYourNetwork" : "{0} is in your network.",
	"friendsActionsFor" : "Actions for Network",
	"friendsInviteFollowError" : "An error occurred while attempting to follow {0}",
	"friendsInviteTagError" : "An error occurred while attempting to tag {0}",
	"friendsPleaseLogIn" : "Please log in to invite people to your network",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Invitation to your network is not possible because the {0} is already in your network.",
	"friendsInviteAddTagsFor" : "Add tags for {0}:",
	"friendsInviteAlsoFollow" : "Also Follow",
	"friendsInviteReceiveUpdates" : "(receive updates)",
	"friendsInviteUpdatesDescription" : "Receive updates about people you are following on the Homepage and in an email summary.",
	"friendsInviteFollowHelp": "For more information, see {0}Following people{1}.",
	"friendsNetwork" : "Network",
	"friendsMyNetwork" : "Network",
	"friendsNetworkFor" : "Network for {0}",
	"friendsRemoveSelected" : "Remove Selected",
	"friendsRemoveSelectedTip" : "Click to remove the selected people from your network.",
	"friendsNetworkInCommon" : "You have {0} network connections in common.",
	"friendsAddToMyNetwork" : "I'd like to add you to my Connections network.",
	"friendsInvite" : "Invite to My Network",
	"friendsInvitePerson" : "Invite {0} to your network",
	"friendsInviteMessage" : "I'd like to add you to my Connections network.",
	"friendsInvitedEmailSubject" : "[Profiles] You are invited to join my network",
	"friendsInvitedEmailMsg1" : "has invited you to become a network contact with the following message included in the invitation:",
	"friendsInvitedEmailMsg2" : "Open your Network Invitation page",
	"friendsInvitedEmailMsg3" : "I'd like to add you to my network.",
	"friendsInvitedEmailMsg4" : "{0} has invited you to become a network contact:",
	"friendsInvitedEmailMsg5" : "{0} has invited you to become a network contact with the following message included in the invitation:",
	"friendsInviteLegalNote" : "By sending this invitation, you agree to allow {0} to comment on your profile board.",
	"friendsInviteFailed" : "Due to a server error, an email notification was not sent to the invitee. However the invitee will still be able to accept your invitation through the Profiles web application.",
	"personInNetwork" : "Network Contact"
})
