/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtra per:",
"SHOW":"Mostra:",
"ACL_FILTER_LABEL":"Filtra per visibilità",
"PARENT_FILTER_LABEL":"Filtra per contenitore",
"TYPE_FILTER_LABEL":"Filtra per tipo",
"PAGING_TOP":"Paginazione primaria",
"PAGING_BOTTOM":"Paginazione secondaria",
"PREVIOUS":"Indietro",
"NEXT":"Avanti",
"PAGE":"Pagina {0} di {1}",
"PAGE_COLON":"Pagina:",
"RESULTS":"{span}{0} - {1}{/span} di {2}",
"ITEMS":"{0} elementi",
/* Application names */
"ACTIVITIES":"Attività",
"BLOGS":"Blog",
"CALENDAR":"Calendario",
"COMMUNITIES":"Comunità",
"BOOKMARKS":"Segnalibri",
"DOGEAR":"Segnalibri",
"EVENTS":"Eventi",
"FILES":"File",
"FORUMS":"Forum",
"PROFILES":"Profili",
"WIKI":"Wiki",
"WIKIS":"Wiki",
"FEEDS":"Feed",
"STATUS_UPDATES":"Aggiornamenti dello stato",
"ONECOMMENT":"1 commento",
"COMMENTS":"{0} commenti",
"ONEPERSON":"1 persona",
"PEOPLE":"{0} persone",
"TAGS":"Tags:",
"TAGSMORE":"e {0} altro",
"NORESULTSMESSAGE":"Nessun risultato trovato per tale ricerca",
"JAN":"Gennaio",
"FEB":"Febbraio",
"MAR":"Marzo",
"APR":"Aprile",
"MAY":"Maggio",
"JUN":"Giugno",
"JUL":"Luglio",
"AUG":"Agosto",
"SEP":"Settembre",
"OCT":"Ottobre",
"NOV":"Novembre",
"DEC":"Dicembre",
"NO_CONTACT":"La ricerca non è stata eseguita perché non è stato possibile contattare il server",
"SERVER_ERROR":"Non è stato possibile eseguire la ricerca a causa di un errore del server",
"SORT_BY":"Ordina per:",
"SORT_RELEVANCE":"Rilevanza",
"SORT_DATE":"Data",
"SORT_LAST_UPDATED":"Ultimo aggiornamento",
"SORT_DUE_DATE":"Data di scadenza",
"SORT_VISITS":"Visite",
"SORT_COMMENTS":"Commenti",
"SORT_RECOMMENDATION":"Preferenze",
"SORT_POPULARITY":"Popolarità",
"SORT_FIRSTNAME":"Nome",
"SORT_LASTNAME":"Cognome",
"SORT_DOWNLOADS":"Scaricamenti",
"SORT_TYPE":"Tipo",
"SORT_SIZE":"Dimensione",
"SORT_TITLE":"Titolo",
"PRIVATE":"Privato",
"MODERATED":"Moderato",
"COMMUNITY_ACTIVITY":"Attività della comunità",
"COMMUNITY_BLOG":"Blog della comunità",
"COMMUNITY_FILE":"File della comunità",
"COMMUNITY_FORUM":"Forum della comunità",
"COMMUNITY_WIKI":"Wiki della comunità",
"COMMUNITY_FEED":"Feed della comunità",
"COMMUNITY_BOOKMARK":"Segnalibro della comunità",
"NO_TAG":"Ancora nessun tag",
"NO_DATE":"Ancora nessuna data",
"NO_PEOPLE":"Non ci sono persone",
"REMOVE_FILTER_LABEL":"Fare clic per rimuovere",
"REMOVE_FILTER_TITLE":"Rimuovi",
"REMOVE_FILTER_TOOLTIP":"Rimuovi questo filtro",
"COMMENT_ON":"Commento su:",
"EXPAND_COLLAPSE":"Fare clic per espandere / comprimere",
"EXPAND":"Espandi",
"COLLAPSE":"Comprimi",
"EXPAND_MONTHS_FILTER":"Espandi il filtro dei mesi dell'anno {0}",
"SORT_RELEVANCE_LABEL":"Fare clic per ordinare per rilevanza",
"SORT_DATE_LABEL":"Fare clic per ordinare per data",
"SORT_UPDATED_LABEL":"Fare clic per ordinare per ultimo aggiornamento",
"SORT_DUE_LABEL":"Fare clic per ordinare per data di scadenza",
"SORT_VISITS_LABEL":"Fare clic per ordinare per numero di visite",
"SORT_COMMENTS_LABEL":"Fare clic per ordinare per numero di commenti",
"SORT_RECOMMENDATIONS_LABEL":"Fare clic per ordinare per numero di preferenze",
"SORT_POPULARITY_LABEL":"Fare clic per ordinare per popolarità",
"SORT_FIRST_NAME_LABEL":"Fare clic per ordinare per nome fornito",
"SORT_LAST_NAME_LABEL":"Fare clic per ordinare per cognome",
"RATING":"Preferenze",
"GRADUATED":"Promosso",
"ONEVOTE":"1 voto",
"VOTES":"{0} voti",
"BOOKMARK_THIS_RESULT":"Contrassegna",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inattivo)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} persone contrassegnate con segnalibro",
/* eg from an Activity */
"FROMANACTIVITY":"da un'attività",
"FROMABLOG":"da un blog",
"FROMANIDEATIONBLOG":"da un blog di ideazione",
"FROMANEVENT":"da un evento",
"FROMAFORUM":"da un forum",
"FROMAWIKI":"da un wiki",
"FROMACOMMUNITY":"da una comunità",
"FROMXCOMMUNITIES":"da {0} comunità",
/* For search results parentage */
"ACTIVITY_ALONE":"Attività",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Blog di ideazione",
"ENTRY_ALONE":"Voce",
"EVENT_ALONE":"Evento",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Comunità",
"XCOMMUNITIES_ALONE":"{0} comunità",
"SHAREDCOMMUNITIES":"Condiviso con queste comunità",
"INACOMMUNITY":"in una comunità",
"LASTUPDATED":"Ultimo aggiornamento indice di ricerca:",
"NODESCRIPTION":"Nessuna descrizione o sommario per questo risultato.",
"ATTACHMENT":"Allegato",
"ACTIVITY":"Attività:",
"ACTIVITYBOOKMARK":"Segnalibro dell'attività:",
"ACTIVITYCOMMENT":"Commento dell'attività:",
"ACTIVITYENTRY":"Voce dell'attività:",
"ACTIVITYSECTION":"Sezione dell'attività:",
"ACTIVITYTODO":"To-do dell'attività:",
"BLOG":"Blog:",
"BLOGENTRY":"Voce del blog:",
"BLOGCOMMENT":"Commento del blog:",
"BOOKMARK":"Segnalibro:",
"CALENDAREVENT":"Evento:",
"CATEGORY":"Categoria:",
"COMMENT":"Commento:",
"COMMUNITY":"Comunità:",
"ENTRY":"Voce:",
"EVENTDATEON":"Il: {0}",
"EVENTISALLDAY":"Evento di un'intera giornata",
"EVENTREPEATS":"Ripetizioni",
"FEED":"Feed:",
"FILE":"File:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Categoria del forum:",
"FORUMTOPIC":"Argomento del forum:",
"IDEA":"Idea:",
"IDEACOMMENT":"Commento dell'idea:",
"IDEATIONBLOG":"Blog di ideazione:",
"PAGE":"Pagina:",
"PROFILE":"Profilo:",
"SECTION":"Sezione:",
"STATUSUPDATE":"Aggiornamento stato",
"STATUSUPDATE_PREFIX":"Aggiornamento stato:",
"TOPIC":"Argomento:",
"TOPIC_WITH_ATTACHMENT":"Argomento",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Pagina del wiki:",
"WIKIFILE":"Allegato del wiki:",
"SEARCH":"Ricerca:",
"TODO":"To-Do:",
"ALLRESULTS":"Tutti i risultati",
"PUBLICCONTENT":"Contenuto pubblico",
"MYCONTENT":"Contenuto personale",
"RESULTNOTFOUND":"Non hai trovato quello che cercavi?",
"TEMPDIFFICULTIES":"Nota: a causa di difficoltà di indicizzazione temporanee, la ricerca non ha incluso {0} che sono stati modificati negli ultimi {1} giorni.",
"TRYLATER":"Riprova in seguito.",
"MULTIPLETEMPDIFFICULTIES":"Nota: a causa di difficoltà di indicizzazione temporanee, la ricerca non ha incluso {0} che sono stati modificati di recente.",
"YOUAREAUTHOR":"L'utente è un autore",
"YOUARECONTRIBUTOR":"L'utente è un collaboratore",
"YOUAREOWNER":"L'utente è un proprietario",
"YOUAREMEMBER":"L'utente è un membro",
/* Profiles */
"MYNETWORK":"Rete personale",
"ALLPEOPLE":"Tutte le persone",
"EXCLUDEINACTIVE":"Escludi persone non attive",
"PHONE":"Telefono:",
"EMAIL":"Email:",
/* Communities */
"ALLCOMMUNITIES":"Tutte le comunità",
"PUBLICCOMMUNITIES":"Comunità pubbliche",
"MYCOMMUNITIES":"Comunità personali",
"EVERYTHINGCOMMUNITIES":"Tutto dalle comunità",
"COMMUNITIESONLY":"Comunità",
"COMMUNITIESCONTENT":"Contenuto dalle comunità",
/* Activities */
"ALLACTIVITIES":"Tutte le attività",
"PUBLICACTIVITIES":"Attività pubbliche",
"MYACTIVITIES":"Attività personali",
"EVERYTHINGACTIVITIES":"Tutto da Attività",
"ACTIVITIESONLY":"Attività",
"SECTIONSACTIVITIES": "Sezioni da Attività",
"ENTRIESACTIVITIES":"Voci da Attività",
"TODOSACTIVITIES":"To-Do da Attività",
"BOOKMARKSACTIVITIES":"Segnalibri da Attività",
"FILESACTIVITIES":"Allegati da Attività",
"ALLTYPESACTIVITIES":"Tutti i tipi di attività",
"COMMUNITYACTIVITIES":"Attività dalle comunità",
"STANDALONEACTIVITIES":"Attività indipendenti",
/* Forums */
"ALLFORUMS":"Tutti i forum",
"PUBLICFORUMS":"Forum pubblici",
"MYFORUMS":"Forum personali",
"EVERYTHINGFORUMS":"Tutto dai forum",
"FORUMSONLY":"Forum",
"TOPICSFORUMS":"Argomenti forum",
"FORUMCATEGORIES": "Categorie forum",
"FILESFORUMS":"Allegati dai forum",
"ALLTYPESFORUMS":"Tutti i tipi di forum",
"COMMUNITYFORUMS":"Forum dalle comunità",
"STANDALONEFORUMS":"Forum indipendenti",
/* Blogs */
"ALLBLOGS":"Tutti i blog",
"PUBLICBLOGS":"Blog pubblici",
"MYBLOGS":"Blog personali",
"EVERYTHINGBLOGS":"Tutto dai blog",
"BLOGSONLY":"Blog",
"ENTRIESBLOGS":"Voci del blog",
"FILESBLOGS":"Allegati dai blog",
"EVERYTHINGIDEATIONBLOGS":"Tutto dai blog di ideazione",
"BLOGSIDEATIONBLOGS":"Blog di ideazione",
"BLOGSIDEAS":"Idee",
"ALLTYPESBLOGS":"Tutti i tipi di blog",
"COMMUNITYBLOGS":"Blog dalle comunità",
"COMMUNITYIDEATIONBLOGS":"Blog di ideazione per Comunità",
"STANDALONEBLOGS":"Blog indipendenti",
/* Bookmarks */
"ALLBOOKMARKS":"Tutti i segnalibri",
"PUBLICBOOKMARKS":"Segnalibri pubblici",
"MYBOOKMARKS":"Segnalibri personali",
"ALLTYPESBOOKMARKS":"Tutti i tipi di segnalibri",
"COMMUNITYBOOKMARKS":"Segnalibri dalle comunità",
"STANDALONEBOOKMARKS":"Segnalibri indipendenti",
/* Files */
"ALLFILES":"Tutti i file",
"PUBLICFILES":"File pubblici",
"MYFILES":"File personali",
"ALLTYPESFILES":"Tutti i tipi di file",
"COMMUNITYFILES":"File dalle comunità",
"STANDALONEFILES":"File indipendenti",
"NUMDOWNLOADS":"{0} scaricamenti",
/* Wikis */
"ALLWIKIS":"Tutti i wiki",
"PUBLICWIKIS":"Wiki pubblici",
"MYWIKIS":"Wiki personali",
"EVERYTHINGWIKIS":"Tutto dai wiki",
"WIKISONLY":"Wiki",
"PAGESWIKIS":"Pagine wiki",
"FILESWIKIS":"Allegati dai wiki",
"ALLTYPESWIKIS":"Tutti i tipi di wiki",
"COMMUNITYWIKIS":"Wiki dalle comunità",
"STANDALONEWIKIS":"Wiki indipendenti",
/* Status Updates */
"ALLSTATUSUPDATES":"Tutti gli aggiornamenti di stato",
"PUBLICSTATUSUPDATES":"Aggiornamenti stato pubblici",
"MYSTATUSUPDATES":"Aggiornamenti dello stato personale",
"ALLTYPESSTATUSUPDATES":"Tutti i tipi di aggiornamenti di stato",
"COMMUNITYSTATUSUPDATES":"Aggiornamenti di stato dalle comunità",
"STANDALONESTATUSUPDATES":"Aggiornamenti di stato dai profili",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Questo URL è stato contrassegnato con un segnalibro da un certo numero di utenti",
"BOOKMARKEDCOMMUNITY":"Questa comunità è stata contrassegnata con un segnalibro da un certo numero di utenti",
"BOOKMARKEDPROFILE":"Questo profilo è stato contrassegnato con un segnalibro da un certo numero di utenti",
"BOOKMARKEDBLOG":"Questo blog è stato contrassegnato con un segnalibro da un certo numero di utenti",
"COMMUNITYBLOG":"Questo è un blog all'interno di una comunità",
"BOOKMARKEDACTIVITY":"Questa attività è stata contrassegnata con un segnalibro da un certo numero di utenti",
"COMMUNITYACTIVITY":"Questa è un'attività all'interno di una comunità",
"BOOKMARKEDFILE":"Questo file è stato contrassegnato con un segnalibro da un certo numero di utenti",
"COMMUNITYFILE":"Questo è un file all'interno di una comunità",
"BOOKMARKED":"Questo wiki è stato contrassegnato con un segnalibro da un certo numero di utenti",
"COMMUNITYWIKI":"Questo è un wiki all'interno di una comunità",
"BOOKMARKEDFORUM":"Questo forum è stato contrassegnato con un segnalibro da un certo numero di utenti",
"COMMUNITYFORUM":"Questo è un forum all'interno di una comunità",
"ALLTAGANDTTILE":"Per visualizzare tutti i titoli e i tag per questo URL, fare clic su questo pulsante",
"TAGS_ARE_FROM":"I risultati di questa ricerca possono includere tag da:",
"BOOKMARKS_TITLE":"Segnalibri",
"COMMUNITIES_TITLE":"Comunità",
"ACTIVITIES_TITLE":"Attività",
"HELP":"Guida",
"MORESTATUSUPDATES":"Visualizza altre corrispondenze di aggiornamenti di stato",
"TITLE_PREFIX":"titolo:",
"LATEST_MESSAGE":"Ultimo messaggio",
"LATEST_STATUS_UPDATE":"Ultimo aggiornamento di stato",
"LATEST_COMMUNITY_STATUS_UPDATE":"Ultimo aggiornamento di stato della comunità",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Ultimo aggiornamento dello stato delle comunità",
"SEARCH_RESULTS":"Risultati della ricerca di tutto il contenuto",
"ACTIVITIES_SEARCH_RESULTS":"Risultati della ricerca attività",
"BLOGS_SEARCH_RESULTS":"Risultati della ricerca blog",
"BOOKMARKS_SEARCH_RESULTS":"Risultati della ricerca segnalibri",
"COMMUNITIES_SEARCH_RESULTS":"Risultati della ricerca comunità",
"FILES_SEARCH_RESULTS":"Risultati della ricerca file",
"FORUMS_SEARCH_RESULTS":"Risultati della ricerca forum",
"PROFILES_SEARCH_RESULTS":"Risultati della ricerca profili",
"DIRECTORY_SEARCH_RESULTS":"Risultati della ricerca nella directory di ${orgName}",
"WIKIS_SEARCH_RESULTS":"Risultati della ricerca wiki",
"STATUS_UPDATES_SEARCH_RESULTS":"Risultati della ricerca degli aggiornamenti dello stato",
"VIEW_ALL":"{span}Visualizza tutto{/span} ({0})",
"MATCHING_ONE_OF":"Corrispondenza con uno di:",
"MATCHING_ALL_OF":"Corrispondenza con tutti di:",
"MATCHING":"Corrispondenza:",
"MATCHING_DOC_TYPE":"Tipo di documento corrispondente:",
"BOOKMARK_HELP":"Guida di Segnalibri",
"CLOSE_BOOKMARK_HELP":"Chiudi guida di Segnalibri",
"DOCUMENT_TYPE_PREFIX":"Tipo di documento:",
"FILE_PREVIEW_ONLY":"(Solo modalità di anteprima)"
})

