/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Actualizado por ${author}",
		PREVIEW_MODE_ONLY: "(Sólo modalidad de vista previa)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Comunidad visualizada hoy",
		COMMUNITY_VIEWED_YESTERDAY: "Comunidad visualizada ayer",
		COMMUNITY_VIEWED_HOURS_AGO: "Comunidad visualizada hace ${hours} horas",
		COMMUNITY_VIEWED_MINUTES_AGO: "Comunidad visualizada hace ${minutes} minutos",
		COMMUNITY_VIEWED_SECONDS_AGO: "Comunidad visualizada hace ${seconds} segundos",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Comunidad visualizada hace 1 hora",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Comunidad visualizada hace 1 minuto",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Comunidad visualizada hace 1 segundo",
		COMMUNITY_VIEWED_AT_DATE: "Comunidad visualizada el ${date}",
		//File
		FILE_VIEWED_TODAY: "Archivo visualizado hoy",
		FILE_VIEWED_YESTERDAY: "Archivo visualizado ayer",
		FILE_VIEWED_HOURS_AGO: "Archivo visualizado hace ${hours} horas",
		FILE_VIEWED_MINUTES_AGO: "Archivo visualizado hace ${minutes} minutos",
		FILE_VIEWED_SECONDS_AGO: "Archivo visualizado hace ${seconds} segundos",
		FILE_VIEWED_1_HOUR_AGO: "Archivo visualizado hace 1 hora",
		FILE_VIEWED_1_MINUTE_AGO: "Archivo visualizado hace 1 minuto",
		FILE_VIEWED_1_SECOND_AGO: "Archivo visualizado hace 1 segundo",
		FILE_VIEWED_AT_DATE: "Archivo visualizado el ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Perfil visualizado hoy",
		PROFILE_VIEWED_YESTERDAY: "Perfil visualizado ayer",
		PROFILE_VIEWED_HOURS_AGO: "Perfil visualizado hace ${hours} horas",
		PROFILE_VIEWED_MINUTES_AGO: "Perfil visualizado hace ${minutes} minutos",
		PROFILE_VIEWED_SECONDS_AGO: "Perfil visualizado hace ${seconds} segundos",
		PROFILE_VIEWED_1_HOUR_AGO: "Perfil visualizado hace 1 hora",
		PROFILE_VIEWED_1_MINUTE_AGO: "Perfil visualizado hace 1 minuto",
		PROFILE_VIEWED_1_SECOND_AGO: "Perfil visualizado hace 1 segundo",
		PROFILE_VIEWED_AT_DATE: "Perfil visualizado el ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Actividad visualizada hoy",
		ACTIVITY_VIEWED_YESTERDAY: "Actividad visualizada ayer",
		ACTIVITY_VIEWED_HOURS_AGO: "Actividad visualizada hace ${hours} horas",
		ACTIVITY_VIEWED_MINUTES_AGO: "Actividad visualizada hace ${minutes} minutos",
		ACTIVITY_VIEWED_SECONDS_AGO: "Actividad visualizada hace ${seconds} segundos",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Actividad visualizada hace 1 hora",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Actividad visualizada hace 1 minuto",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Actividad visualizada hace 1 segundo",
		ACTIVITY_VIEWED_AT_DATE: "Actividad visualizada el ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Marcador visualizado hoy",
		BOOKMARK_VIEWED_YESTERDAY: "Marcador visualizado ayer",
		BOOKMARK_VIEWED_HOURS_AGO: "Marcador visualizado hace ${hours} horas",
		BOOKMARK_VIEWED_MINUTES_AGO: "Marcador visualizado hace ${minutes} minutos",
		BOOKMARK_VIEWED_SECONDS_AGO: "Marcador visualizado hace ${seconds} segundos",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Marcador visualizado hace 1 hora",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Marcador visualizado hace 1 minuto",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Marcador visualizado hace 1 segundo",
		BOOKMARK_VIEWED_AT_DATE: "Marcador visualizado el ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Blog visto hoy",
		BLOG_VIEWED_YESTERDAY: "Blog visualizado ayer",
		BLOG_VIEWED_HOURS_AGO: "Blog visualizado hace ${hours} horas",
		BLOG_VIEWED_MINUTES_AGO: "Blog visualizado hace ${minutes} minutos",
		BLOG_VIEWED_SECONDS_AGO: "Blog visualizado hace ${seconds} segundos",
		BLOG_VIEWED_1_HOUR_AGO: "Blog visualizado hace 1 hora",
		BLOG_VIEWED_1_MINUTE_AGO: "Blog visualizado hace 1 minuto",
		BLOG_VIEWED_1_SECOND_AGO: "Blog visualizado hace 1 segundo",
		BLOG_VIEWED_AT_DATE: "Blog visualizado el ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Foro visto hoy",
		FORUM_VIEWED_YESTERDAY: "Foro visualizado ayer",
		FORUM_VIEWED_HOURS_AGO: "Foro visualizado hace ${hours} horas",
		FORUM_VIEWED_MINUTES_AGO: "Foro visualizado hace ${minutes} minutos",
		FORUM_VIEWED_SECONDS_AGO: "Foro visualizado hace ${seconds} segundos",
		FORUM_VIEWED_1_HOUR_AGO: "Foro visualizado hace 1 hora",
		FORUM_VIEWED_1_MINUTE_AGO: "Foro visualizado hace 1 minuto",
		FORUM_VIEWED_1_SECOND_AGO: "Foro visualizado hace 1 segundo",
		FORUM_VIEWED_AT_DATE: "Foro visualizado el ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Wiki visto hoy",
		WIKI_VIEWED_YESTERDAY: "Wiki visualizado ayer",
		WIKI_VIEWED_HOURS_AGO: "Wiki visualizado hace ${hours} horas",
		WIKI_VIEWED_MINUTES_AGO: "Wiki visualizado hace ${minutes} minutos",
		WIKI_VIEWED_SECONDS_AGO: "Wiki visualizado hace ${seconds} segundos",
		WIKI_VIEWED_1_HOUR_AGO: "Wiki visualizado hace 1 hora",
		WIKI_VIEWED_1_MINUTE_AGO: "Wiki visualizado hace 1 minuto",
		WIKI_VIEWED_1_SECOND_AGO: "Wiki visualizado hace 1 segundo",
		WIKI_VIEWED_AT_DATE: "Wiki visualizado el ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Evento visto hoy",
		EVENT_VIEWED_YESTERDAY: "Evento visto ayer",
		EVENT_VIEWED_HOURS_AGO: "Evento visto hace ${hours} horas",
		EVENT_VIEWED_MINUTES_AGO: "Evento visto hace ${minutes} minutos",
		EVENT_VIEWED_SECONDS_AGO: "Evento visto hace ${seconds} segundos",
		EVENT_VIEWED_1_HOUR_AGO: "Evento visto hace 1 hora",
		EVENT_VIEWED_1_MINUTE_AGO: "Evento visto hace 1 minuto",
		EVENT_VIEWED_1_SECOND_AGO: "Evento visto hace 1 segundo",
		EVENT_VIEWED_AT_DATE: "Evento visto el ${date}",
		//To Do
		TODO_VIEWED_TODAY: "Tarea pendiente visualizada hoy",
		TODO_VIEWED_YESTERDAY: "Tarea pendiente visualizada ayer",
		TODO_VIEWED_HOURS_AGO: "Tarea pendiente visualizada hace ${hours} horas",
		TODO_VIEWED_MINUTES_AGO: "Tarea pendiente visualizada hace ${minutes} minutos",
		TODO_VIEWED_SECONDS_AGO: "Tarea pendiente visualizada hace ${seconds} segundos",
		TODO_VIEWED_1_HOUR_AGO: "Tarea pendiente visualizada hace 1 hora",
		TODO_VIEWED_1_MINUTE_AGO: "Tarea pendiente visualizada hace 1 minuto",
		TODO_VIEWED_1_SECOND_AGO: "Tarea pendiente visualizada hace 1 segundo",
		TODO_VIEWED_AT_DATE: "Tarea pendiente visualizada el ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "Encuesta visualizada hoy",
		SURVEY_VIEWED_YESTERDAY: "Encuesta visualizada ayer",
		SURVEY_VIEWED_HOURS_AGO: "Encuesta visualizada hace ${hours} horas",
		SURVEY_VIEWED_MINUTES_AGO: "Encuesta visualizada hace ${minutes} minutos",
		SURVEY_VIEWED_SECONDS_AGO: "Encuesta visualizada hace ${seconds} segundos",
		SURVEY_VIEWED_1_HOUR_AGO: "Encuesta visualizada hace 1 hora",
		SURVEY_VIEWED_1_MINUTE_AGO: "Encuesta visualizada hace 1 minuto",
		SURVEY_VIEWED_1_SECOND_AGO: "Encuesta visualizada hace 1 segundo",
		SURVEY_VIEWED_AT_DATE: "Encuesta visualizada el ${date}",
		//Survey
		GENERIC_VIEWED_TODAY: "Visualizado hoy",
		GENERIC_VIEWED_YESTERDAY: "Visualizado ayer",
		GENERIC_VIEWED_HOURS_AGO: "Visualizado hace ${hours} horas",
		GENERIC_VIEWED_MINUTES_AGO: "Visualizado hace ${minutes} minutos",
		GENERIC_VIEWED_SECONDS_AGO: "Visualizado hace ${seconds} segundos",
		GENERIC_VIEWED_1_HOUR_AGO: "Visualizado hace 1 hora",
		GENERIC_VIEWED_1_MINUTE_AGO: "Visualizado hace 1 minuto",
		GENERIC_VIEWED_1_SECOND_AGO: "Visualizado hace 1 segundo",
		GENERIC_VIEWED_AT_DATE: "Visualizado el ${date}"
});

