define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Fermer",
		   'rs_loading' : "Chargement...",
		   'rs_at' : "à",
		   'rs_searchDirectory' : "Personne non répertoriée ? Utilisez la recherche étendue...",
		   'rs_searchGroupDirectory' : "Groupe non répertorié ? Utilisez la recherche étendue...",
		   'rs_searchPersonAndGroupDirectory' : "Personne ou groupe non répertoriés ? Utilisez la recherche étendue...",
		   'rs_searchCommunityDirectory' : "Communauté non répertoriée ? Utilisez la recherche étendue...",
		   'rs_shadowText_searchDirectory' : "Saisissez le nom d'une personne à rechercher",
		   'rs_shadowText_searchGroupDirectory' : "Saisissez le nom d'un groupe à rechercher",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Saisissez le nom d'une personne ou d'un groupe à rechercher",
		   'rs_shadowText_searchCommunityDirectory' : "Saisissez le nom d'une communauté à rechercher",
		   'rs_listItem' : "Elément de liste",
		   'rs_noResults' : "Aucun résultat pour '${0}'",
		   'rs_today' : "Aujourd'hui",
		   'rs_tomorrow' : "Demain",
		   'rs_yesterday' : "Hier",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Flux pour ces activités",
		   'rs_externalText' : "Cette activité peut contenir des membres externes à votre organisation.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" a été déplacé dans la sous-communauté \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Afficher plus d\'informations sur cette activité',
		   'rs_hideInfo' : 'Masquer les informations supplémentaires',
		   'rs_more' : "Plus",
		   'rs_hide' : "Masquer",
		   'rs_edit' : "Editer",
		   'rs_restore' : "Restaurer",
		   'rs_deleteEntry' : "Supprimer",
		   'rs_prioritize' : "Hiérarchiser",
		   'rs_markComplete' : "Marquer comme terminé",
		   'rs_markIncomplete' : "Restaurer",
		   'rs_linkMore' : "... [plus]",
		   'rs_linkLess' : "... [moins]",
		   'rs_actUpdatedByDate' : "mis à jour par ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Mis à jour par ${0}",// Updated by (author name)
		   'rs_actDue' : "Echéance : ${0}",// Due (date)
		   'rs_actTags' : "Etiquettes : ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Démarrer une activité à partir de ce modèle",
		   'rs_favoriteTemplate' : "Marquer comme modèle favori",
		   'rs_normalTemplate' : "Marquer comme modèle normal",
		   'rs_tunedOutPri' : "Désactivé",
		   'rs_pagepos' : "${0} - ${1} sur ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Précédent",
		   'rs_navNextLabel' : "Suivant",
		   'rs_noActivities' : "Il n'y a aucune activité démarrée pour cette communauté.",
		   'rs_feedError' : "Echec du chargement du flux.",
		   'rs_highPri' : "Priorité élevée",
		   'rs_medPri' : "Priorité moyenne",
		   'rs_normalPri' : "Priorité normale (par défaut)",
		   'rs_tuneOut' : "Marquer comme désactivé",
		   'rs_startActivity' : "Démarrer une activité",
		   'rs_startFirstActivity' : "Créer votre première activité",
		   'rs_navNextLabel' : "Suivant",
		   'rs_viewAll' : "Tout afficher",
		   'rs_activityWidgetTitle' : "Activités",
		   'rs_activityWidgetBriefDescription' : "Suivez les objectifs de la communauté.  Créez des tâches et partagez des ressources.",
		   'rs_activityWidgetDescription' : "Les activités de la communauté permettent notamment de collaborer et de suivre l'avancement des projets ou initiatives de la communauté.",
		   'rs_completedActivityLink' : "Afficher les activités terminées",
		   'rs_activitiesUnavailable' : "Le service des activités n'est pas disponible.",
		   'rs_errorPersists' : "Si l'incident persiste, contactez votre administrateur système.",
		   'rs_shared' : "Partagé",
		   'rs_removeActFromComm' : "Retirer de la communauté",
		   'rs_externalLabel' : "Externe",
		   // for ActivityForm
		   'rs_templateOptions' : "Options de modèle",
		   'rs_template' : "Modèle",
		   'rs_tagsLabel' : "Etiquettes",
		   'rs_peopleLabel' : "Personnes",
		   'rs_aboutThisTemplate' : "A propos de ce modèle",
		   'rs_activity' : "Activité",
		   'rs_copyOf' : "Copie de ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Objectif de l'activité",
		   'rs_noTemplate' : "Aucun",
		   'rs_copyActivityMembers' : "Utiliser des membres de l'activité",
		   'rs_copyTemplateMembers' : "Utiliser des membres du modèle",
		   /* Forum Widget */
		   'rs_noTopics' : "Il n'y a pas encore de sujet pour cette communauté.",
		   'rs_noTopicsLoggedIn' : "Posez une question, lancez un débat d'idées, ou partagez simplement vos idées.",
		   'rs_postedBy' : "Dernier article posté par",
		   'rs_topics' : "sujets",
		   'rs_noTopicsShort' : "Aucun sujet",
		   'rs_topic' : "sujet",
		   'rs_replies' : "réponses",
		   'rs_noReplies' : "Aucune réponse",
		   'rs_reply' : "réponse",
		   'rs_startTopic' : "Démarrer un sujet",
		   'rs_startFirstTopic' : "Démarrer le premier sujet.",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Verrouillé]",
		   'rs_manageForumSetting' : "Gérer les paramètres des forums",
		   'rs_forumSettingCommunityOverviewPage' : "Page de présentation de la communauté :",
		   'rs_defaultForumList' : "Afficher la liste des forums par défaut",
		   'rs_defaultTopicList' : "Afficher la liste des sujets par défaut",
		   'rs_forumSettingApplicationView' : "Vue par défaut de l'application Forums :",
		   'rs_forumSettingNote' : "Remarque : les sujets s'affichent par défaut s'il n'y a qu'un seul forum.",
		   'rs_forumSettingSubmit' : "Soumettre",
		   'rs_forumSettingSave' : "Enregistrer",
		   'rs_forumSettingSaveAndClose' : "Enregistrer et fermer",
		   'rs_forumSettingConfirm' : "Les modifications que vous avez apportées aux forums ont été enregistrées.",
		   'rs_forumSettingError' : "Une erreur s'est produite. Contactez votre administrateur.",
		   'rs_formSettingHideMessage' : "Masquer ce message",
		   'rs_forumSettingCancel' : "Annuler",
		   'rs_forumAnsweredQuestion' : "Question répondue",
		   'rs_forumUnAnsweredQuestion' : "Questions non répondues",
		   'rs_forumSortBy' : "Trier par :",
		   'rs_forumSortByDate' : "Date",
		   'rs_forumSortByReplies' : "Réponses",
		   'rs_forumSortByTopic' : "Sujets",
		   'rs_forumSortByTopicsAndReplies' : "Sujets et réponses",
		   'rs_sortByReplies' : "Trier par réponses",
		   'rs_sortbyTopicsAndReplies' : "Trier par sujets et réponses",
		   'rs_forumOpenQuestions' : "Questions ouvertes",
		   'rs_feedOpenQuestions' : "Flux pour ces questions ouvertes",
		   'rs_feedAnsweredQuestions' : "Flux pour ces questions répondues",
		   'rs_forumMessages' : "${0} messages",
		   'rs_forumLastAddedPost' : "Dernier article posté par ${0}",
		   'rs_forumTopics' : "${0} sujets",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Créer un lien de personne",
		   'rs_quote' : "Citer",
		   'rs_labelColon' : "Libellé : ",
		   'rs_personColon' : "Personne : ",
		   'rs_personLink' : "Lien de personne",
		   'rs_replace' : "Remplacer",
		   'rs_inactivePerson' : "${0} (inactif)", // person's name (inactive)
		   'rs_PersonPicture' : "Image de ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Utilisateur externe", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (utilisateur externe)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Photo de ${0} (utilisateur externe)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Cet utilisateur a accès à des fichiers et communautés qui sont partagés en externe.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Notifier d'autres personnes",
		   'rs_messageColon' : "Message : ",
		   'rs_notifyColon' : "Notifier : ",
		   'rs_notificationConfirm' : "Le message de notification a été envoyé. ",
		   'rs_notificationFail' : "Le message de notification n'a pas été envoyé. Réessayez et contactez votre administrateur système si l'incident persiste.",
		   'rs_pickCommunity' : "Extraire de la liste de la communauté",
		   'rs_typeName' : "Entrez un nom",
		   'rs_typeToFilter' : "Pour filtrer cette liste, tapez ici",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Pour filtrer cette liste, tapez ici",
		   'rs_filterGroupLabel' : "Sélectionnez un groupe",
		   'rs_noResults' : "Aucun résultat trouvé",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Affichage de ${0} résultat(s) sur ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Retirer",
		   /* Language Selector */
		   'rs_browser_setting' : "Paramètre du navigateur",
		   'rs_customLangaugeLinkLabel' : "Langue personnalisée",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Aller à la page ${0} sur ${1}",
		   "rs_jumpPageLabel" : "Aller à la page",
		   'rs_pageNumLabel' : "Numéro de page",
		   'rs_pageLabel' : "Page :",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Etiquettes',
		   'rs_tagCloudToggleHint' : "Cliquer pour masquer ou afficher",
		   'rs_tagCloudHelpAlt' : "Obtenir de l'aide sur les étiquettes",
		   'rs_tagCloudNoTags' : "Pas encore d'étiquette.",
		   'rs_tagCloudNoRecentTags' : "Aucune étiquette récente",
		   'rs_tagCloudNoTagsProfiles' : "Effectuez une recherche dans le répertoire. Les étiquettes associées aux profils renvoyés par la recherche seront affichées ici.",
		   'rs_tagLoadingTags' : "Chargement du contenu",
		   'rs_tagCloudSelectedTags' : "Etiquettes sélectionnées",
		   'rs_tagCloudSeachDesc' : "Rechercher une étiquette",
		   'rs_tagCloudSeach' : "Rechercher",
		   'rs_tagCloudRelatedTags' : "Etiquettes associées",
		   'rs_tagCloudRelatedTagsDescription' : "Ajoutez une étiquette associée pour affiner la recherche",
		   'rs_tagCloudError' : 'Une erreur s\'est produite',
		   'rs_viewAsCloud' : "Nuage",
		   'rs_viewAsCloudTitle' : "Répertorier les étiquettes sous forme de nuage d'étiquettes",
		   'rs_viewAsCloudDescription' : "Affichage des étiquettes sous forme de nuage d'étiquettes",
		   'rs_viewAsList' : "Liste",
		   'rs_viewAsListTitle' : "Répertorier les étiquettes sous forme de liste séquentielle d'étiquettes",
		   'rs_viewAsListDescription' : "Affichage des étiquettes sous forme de liste séquentielle d'étiquettes",
		   'rs_tagCloudViewAll' : "Parcourir",
		   'rs_tagCloudViewAllTitle' : "Parcourir toutes les étiquettes",
		   'rs_normalTags' : "Etiquettes actives",
		   'rs_removeTag' : "Retirer l'étiquette des étiquettes de filtrage sélectionnées",
		   'rs_clearAll' : "Effacer tout",
		   'rs_searchInputDefault' : "Saisissez une étiquette à rechercher",
		   'rs_searchInputTagSelected' : "Entrez une autre étiquette",
		   'rs_relatedTagTitle' : "Afficher les résultats de recherche de l'étiquette ${0}, nombre ${1}",
		   'rs_removeTagTitle' : "Retirer l'étiquette ${0} des étiquettes de filtrage sélectionnées",
		   'rs_addTagTitle' : "Filtrer par étiquette ${0} avec le nombre ${1}",
		   'rs_tagDialogCloseTile' : "Fermer",
		   'rs_tagDialogTitle' : "Toutes les étiquettes",
		   'rs_tagDialogPageInfo' : "${0} - ${1} sur ${2} étiquettes",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Parcourir les groupes",
		   'rs_group_browse_groups_dialog_title' : "Parcourir les groupes",
		   'rs_group_browse_find_groups' : "Rechercher des groupes",
		   'rs_group_browse_add_button' : "Ajouter",
		   'rs_group_browse_cancel_button' : "Annuler",
		   'rs_group_browse_enter_string' : "Tapez pour trouver des groupes",
		   'rs_group_browse_group_typeahead_label' : "Entrez un nom de groupe :",
		   'rs_group_browse_group_name' : "Nom de groupe :",
		   'rs_group_browse_results_label' : "Sélectionnez un groupe correspondant :",
		   'rs_group_browse_parent_group_label' : "Vous êtes dans :",
		   'rs_group_browse_next_page' : "Page suivante",
		   'rs_group_browse_previous' : "Précédent",
		   'rs_group_browse_next' : "Suivant",
		   'rs_group_browse_paging' : "Pagination",
		   'rs_group_browse_previous_page' : "Page précédente",
		   'rs_group_browse_group_selected' : "Groupe sélectionné :",
		   'rs_group_browse_group_no_groups' : "Ce groupe ne contient pas de groupes",
		   'rs_group_browse_page_info' : "${0} - ${1} sur ${2}",
		   'rs_group_browse_page_info_alt' : "Groupes correspondants ${0} à ${1} sur ${2}",
		   'rs_group_browse_remove_selection' : 'Retirer la sélection de groupe imbriqué : ${0}',
		   'rs_group_browse_paging' : "Pagination",
		   'rs_member_groups' : "Groupes",
		   'rs_member_members' : "Membres",
		   'rs_member_no_results' : "Aucun résultat trouvé",
		   'rs_member_remove_group' : "Retirer ${0}",
		   'rs_member_add_to_community' : "Cliquez pour ajouter un membre",
		   'rs_member_remove_name' : "Cliquez pour retirer un membre",
		   'rs_group_add_to_community' : "Cliquez pour ajouter un groupe",
		   'rs_group_remove_name' : "Cliquez pour retirer un groupe",
		   'rs_group_name' : "Nom de groupe",
		   'rs_group_role' : "Rôle du groupe",
		   'rs_warning' : "Avertissement",
		   'rs_a11y_warning' : "Avertissement :",
		   'rs_messagebox_close_btn_title' : "Fermer",
		   'rs_messagebox_close_btn_alt' : "Fermer",
		   'rs_messagebox_error_icon_alt' : "Erreur",
		   'rs_messagebox_error_a11y_label' : "Erreur :",
		   'rs_messagebox_warning_icon_alt' : "Avertissement",
		   'rs_messagebox_warning_a11y_label' : "Avertissement :",
		   'rs_messagebox_info_icon_alt' : "Informations",
		   'rs_messagebox_info_a11y_label' : "Informations :",
		   'rs_messagebox_success_icon_alt' : "Opération réussie",
		   'rs_messagebox_success_a11y_label' : "Opération réussie :",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Insérer un lien vers des fichiers",
		   'rs_docpicker_label' : "Lien vers des fichiers",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Télécharger ${0}",
		   'rs_docpicker_viewdetails_text' : "Afficher les détails",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Afficher les détails de ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Retirer",
		   'rs_attachedfile_filename' : "Image ${0}",
		   'rs_feedreader_warning' : "Avertissement : ce lien est destiné aux programmes de lecture de flux et peut ne pas s'afficher correctement dans votre navigateur. Cliquez sur OK pour poursuivre ou sur Annuler pour revenir à la page.",
		   'rs_search' : "Rechercher",
		   'rs_all_connections' : "Tout Connections",
		   'rs_advanced' : "Avancé",
		   'rs_select_scope' : "Sélectionner la portée de la recherche",
		   'rs_icfixlayout' : {
		      button_label : "Remettre en forme",
		      dialog_title : "Remettre en forme le contenu",
		      warning : "Avertissement",
		      reformat_save : "Remettre en forme et enregistrer",
		      save_as_is : "Enregistrer tel quel",
		      cancel : "Annuler",
		      warn_layout : "Votre contenu dépasse la largeur maximale d'affichage.  Voulez-vous le remettre en forme automatiquement pour qu'il puisse être affiché dans l'espace disponible ?",
		      remember_decision : "Se souvenir de ma décision"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Une erreur s'est produite lors du partage des fichiers sélectionnés.",
		   'rs_sharefile_access_denied' : "Ce fichier a été supprimé ou n'est plus partagé avec vous.",
		   'rs_sharefile_invalid_request' : "Une erreur s'est produite lors du partage des fichiers sélectionnés.",
		   'rs_sharefile_sharing_intent_restriction' : "Le partage du fichier n'est possible qu'à l'intérieur de votre organisation.",
		   'rs_sharefile_error_title' : "Erreur",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'Sur l\'App Store',
		   'rs_mobileBanner_inGooglePlay' : 'Dans Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Ouvrir',
		   'rs_mobileBanner_view' : 'Afficher',
		   'rs_mobileBanner_hide' : 'Masquer',

		   'rs_empty_column_placeholder' : 'Faites glisser des applications ici.',
		   'rs_widget_loading_error_title' : 'Impossible d\'afficher le widget',
		   'rs_widget_loading_error_message' : 'Réessayez et contactez votre administrateur système si l\'incident persiste.',
		   'rs_widgets_loading_error_title' : 'Impossible d\'afficher le(s) widget(s) dans cette communauté',
		   'rs_widget_misplacement_warning' : 'Cette application ne peut pas être affichée dans cette colonne. Un propriétaire de communauté peut la déplacer dans une autre colonne ou la retirer de la page.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Le titre que vous avez entré est trop long.',
		      empty_new_title : 'Le titre que vous entrez ne peut pas être vide.',
		      default_message : 'Impossible de changer le titre pour cette application ${0}.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Titre :  ',
		   'rs_widget_title_change_direction' : 'Changer le titre de cette application ${0}.',
		   'rs_widget_title_change_title' : 'Changer le titre',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Inviter ou ajouter des membres",
		   'rs_vmmainContentDesc' : "Invitez des membres pour leur donner la possibilité de rejoindre la communauté. Ajoutez des membres pour les inclure automatiquement.",
		   'rs_vmtypeAheadLabel' : "Nom ou E-mail : ",
		   'rs_vmgroupTypeAheadLabel' : "Nom : ",
		   'rs_vmtypeAheadRoleLabel' : " en tant que ",
		   'rs_vmgroupTypeAheadRoleLabel' : " en tant que membres ",
		   'rs_vmtaNoResults' : "Aucun résultat trouvé.",
		   'rs_vmtaHeader' : "en-tête",
		   'rs_vmaddUser' : "Ajouter",
		   'rs_vmradioSectionTitle' : "Options de membre :",
		   'rs_vmradioOne' : "Envoyer des invitations à rejoindre la communauté",
		   'rs_vmradioTwo' : "Ajouter automatiquement des utilisateurs à la communauté",
		   'rs_vmtwistyA' : "Ajouter un message facultatif",
		   'rs_vmtwistyB' : "Retirer le texte supplémentaire",
		   'rs_vmmessage' : "Message :",
		   'rs_vmtextAreaStartText' : "Dire quelque chose...",
		   'rs_vmcheckboxLabel' : "M'envoyer une copie",
		   'rs_vmsave' : "Enregistrer",
		   'rs_vminvite' : "Inviter",
		   'rs_vmcancel' : "Annuler",
		   'rs_userContentTitle' : "Entrée d'informations",
		   'rs_vmaddUser' : "Créer un utilisateur",
		   'rs_vmback'	 : "Précédent",
		   'rs_vmvisitor'	 : "Visiteur",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Cliquez ici pour copier cette communauté',
			'rs_commpicker' : ''

});
