/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrér efter:",
"SHOW":"Vis:",
"ACL_FILTER_LABEL":"Filtrér efter synlighed",
"PARENT_FILTER_LABEL":"Filtrér efter opbevaringssted",
"TYPE_FILTER_LABEL":"Filtrér efter type",
"PAGING_TOP":"Primær sidestyring",
"PAGING_BOTTOM":"Sekundær sidestyring",
"PREVIOUS":"Forrige",
"NEXT":"Næste",
"PAGE":"Side {0} af {1}",
"PAGE_COLON":"Side:",
"RESULTS":"{span}{0}-{1}{/span} af {2}",
"ITEMS":"{0} elementer",
/* Application names */
"ACTIVITIES":"Aktiviteter",
"BLOGS":"Blogge",
"CALENDAR":"Kalender",
"COMMUNITIES":"Fællesskaber",
"BOOKMARKS":"Bogmærker",
"DOGEAR":"Bogmærker",
"EVENTS":"Begivenheder",
"FILES":"Filer",
"FORUMS":"Forummer",
"PROFILES":"Profiler",
"WIKI":"Wikier",
"WIKIS":"Wikier",
"FEEDS":"Feeds",
"STATUS_UPDATES":"Statusopdateringer",
"ONECOMMENT":"1 kommentar",
"COMMENTS":"{0} kommentarer",
"ONEPERSON":"1 person",
"PEOPLE":"{0} personer",
"TAGS":"Emneord:",
"TAGSMORE":"og {0} flere",
"NORESULTSMESSAGE":"Der er ikke fundet nogen resultater for denne søgning",
"JAN":"Januar",
"FEB":"Februar",
"MAR":"Marts",
"APR":"April",
"MAY":"Maj",
"JUN":"Juni",
"JUL":"Juli",
"AUG":"August",
"SEP":"September",
"OCT":"Oktober",
"NOV":"November",
"DEC":"December",
"NO_CONTACT":"Søgningen er ikke udført, fordi serveren ikke kunne kontaktes",
"SERVER_ERROR":"Søgningen er ikke udført på grund af en serverfejl",
"SORT_BY":"Sortér efter:",
"SORT_RELEVANCE":"Relevans",
"SORT_DATE":"Dato",
"SORT_LAST_UPDATED":"Sidst opdateret",
"SORT_DUE_DATE":"Tidsfrist",
"SORT_VISITS":"Besøg",
"SORT_COMMENTS":"Kommentarer",
"SORT_RECOMMENDATION":"Synes om",
"SORT_POPULARITY":"Popularitet",
"SORT_FIRSTNAME":"Fornavn",
"SORT_LASTNAME":"Efternavn",
"SORT_DOWNLOADS":"Downloadninger",
"SORT_TYPE":"Type",
"SORT_SIZE":"Størrelse",
"SORT_TITLE":"Titel",
"PRIVATE":"Privat",
"MODERATED":"Modereret",
"COMMUNITY_ACTIVITY":"Fællesskabsaktivitet",
"COMMUNITY_BLOG":"Fællesskabsblog",
"COMMUNITY_FILE":"Fællesskabsfil",
"COMMUNITY_FORUM":"Fællesskabsforum",
"COMMUNITY_WIKI":"Fællesskabswiki",
"COMMUNITY_FEED":"Fællesskabsfeed",
"COMMUNITY_BOOKMARK":"Fællesskabsbogmærke",
"NO_TAG":"Ingen emneord endnu",
"NO_DATE":"Ingen datoer endnu",
"NO_PEOPLE":"Ingen personer endnu",
"REMOVE_FILTER_LABEL":"Klik for at fjerne",
"REMOVE_FILTER_TITLE":"Fjern",
"REMOVE_FILTER_TOOLTIP":"Fjern dette filter",
"COMMENT_ON":"Kommentar til:",
"EXPAND_COLLAPSE":"Klik for at udvide eller skjule",
"EXPAND":"Udvid",
"COLLAPSE":"Skjul",
"EXPAND_MONTHS_FILTER":"Udvid månedsfilteret for år {0}",
"SORT_RELEVANCE_LABEL":"Klik for at sortere efter relevans",
"SORT_DATE_LABEL":"Klik for at sortere efter dato",
"SORT_UPDATED_LABEL":"Klik for at sortere efter sidst opdateret",
"SORT_DUE_LABEL":"Klik for at sortere efter tidsfrist",
"SORT_VISITS_LABEL":"Klik for at sortere efter antal besøg",
"SORT_COMMENTS_LABEL":"Klik for at sortere efter antal kommentarer",
"SORT_RECOMMENDATIONS_LABEL":"Klik for at sortere efter antal synes godt om-tilkendegivelser",
"SORT_POPULARITY_LABEL":"Klik for at sortere efter popularitet",
"SORT_FIRST_NAME_LABEL":"Klik for at sortere efter fornavn",
"SORT_LAST_NAME_LABEL":"Klik for at sortere efter efternavn",
"RATING":"Synes om",
"GRADUATED":"Vedtaget",
"ONEVOTE":"1 stemme",
"VOTES":"{0} stemmer",
"BOOKMARK_THIS_RESULT":"Opret bogmærke for dette",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inaktiv)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} personer oprettede bogmærke",
/* eg from an Activity */
"FROMANACTIVITY":"fra en aktivitet",
"FROMABLOG":"fra en blog",
"FROMANIDEATIONBLOG":"fra en idéblog",
"FROMANEVENT":"fra en begivenhed",
"FROMAFORUM":"fra et forum",
"FROMAWIKI":"fra en wiki",
"FROMACOMMUNITY":"fra et fællesskab",
"FROMXCOMMUNITIES":"fra {0} fællesskaber",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivitet",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Idéblog",
"ENTRY_ALONE":"Indlæg",
"EVENT_ALONE":"Begivenhed",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Fællesskab",
"XCOMMUNITIES_ALONE":"{0} fællesskaber",
"SHAREDCOMMUNITIES":"Delt med disse fællesskaber",
"INACOMMUNITY":"i et fællesskab",
"LASTUPDATED":"Søgeindeks er sidst opdateret:",
"NODESCRIPTION":"Ingen beskrivelse eller resumé for dette resultat.",
"ATTACHMENT":"Vedhæftning:",
"ACTIVITY":"Aktivitet:",
"ACTIVITYBOOKMARK":"Aktivitetsbogmærke:",
"ACTIVITYCOMMENT":"Aktivitetskommentar:",
"ACTIVITYENTRY":"Aktivitetsindgang:",
"ACTIVITYSECTION":"Aktivitetssektion:",
"ACTIVITYTODO":"Aktivitetsopgave:",
"BLOG":"Blog:",
"BLOGENTRY":"Blogindlæg:",
"BLOGCOMMENT":"Blogkommentar:",
"BOOKMARK":"Bogmærke:",
"CALENDAREVENT":"Begivenhed:",
"CATEGORY":"Kategori:",
"COMMENT":"Kommentar:",
"COMMUNITY":"Fællesskab:",
"ENTRY":"Indgang:",
"EVENTDATEON":"D. {0}",
"EVENTISALLDAY":"Heldagsbegivenhed",
"EVENTREPEATS":"Gentagelser",
"FEED":"Feed:",
"FILE":"Fil:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forumkategori:",
"FORUMTOPIC":"Forumemne:",
"IDEA":"Idé:",
"IDEACOMMENT":"Idékommentar:",
"IDEATIONBLOG":"Idéblog:",
"PAGE":"Side:",
"PROFILE":"Profil:",
"SECTION":"Sektion:",
"STATUSUPDATE":"Statusopdatering",
"STATUSUPDATE_PREFIX":"Statusopdatering:",
"TOPIC":"Emne:",
"TOPIC_WITH_ATTACHMENT":"Emne",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Wikiside:",
"WIKIFILE":"Wikivedhæftning:",
"SEARCH":"Søg:",
"TODO":"Opgave:",
"ALLRESULTS":"Alle resultater",
"PUBLICCONTENT":"Offentligt indhold",
"MYCONTENT":"Mit indhold",
"RESULTNOTFOUND":"Fandt du ikke, hvad du søgte efter?",
"TEMPDIFFICULTIES":"Bemærk: På grund af midlertidige indekseringsproblemer omfatter din søgning ikke {0}, som er ændret den eller de sidste {1} dag(e).",
"TRYLATER":"Prøv igen senere.",
"MULTIPLETEMPDIFFICULTIES":"Bemærk: På grund af midlertidige indekseringsproblemer omfatter din søgning ikke {0}, som er ændret for nylig",
"YOUAREAUTHOR":"Du er forfatter",
"YOUARECONTRIBUTOR":"Du er bidragyder",
"YOUAREOWNER":"Du er ejer",
"YOUAREMEMBER":"Du er medlem",
/* Profiles */
"MYNETWORK":"Mit netværk",
"ALLPEOPLE":"Alle personer",
"EXCLUDEINACTIVE":"Udelad inaktive personer",
"PHONE":"Telefon:",
"EMAIL":"E-mail:",
/* Communities */
"ALLCOMMUNITIES":"Alle fællesskaber",
"PUBLICCOMMUNITIES":"Offentlige fællesskaber",
"MYCOMMUNITIES":"Mine fællesskaber",
"EVERYTHINGCOMMUNITIES":"Alt fra fællesskaber",
"COMMUNITIESONLY":"Fællesskaber",
"COMMUNITIESCONTENT":"Indhold fra fællesskaber",
/* Activities */
"ALLACTIVITIES":"Alle aktiviteter",
"PUBLICACTIVITIES":"Offentlige aktiviteter",
"MYACTIVITIES":"Mine aktiviteter",
"EVERYTHINGACTIVITIES":"Alt fra aktiviteter",
"ACTIVITIESONLY":"Aktiviteter",
"SECTIONSACTIVITIES": "Sektioner fra aktiviteter",
"ENTRIESACTIVITIES":"Indgange fra aktiviteter",
"TODOSACTIVITIES":"Opgaver fra aktiviteter",
"BOOKMARKSACTIVITIES":"Bogmærker fra aktiviteter",
"FILESACTIVITIES":"Vedhæftninger fra aktiviteter",
"ALLTYPESACTIVITIES":"Alle typer aktiviteter",
"COMMUNITYACTIVITIES":"Aktiviteter fra fællesskaber",
"STANDALONEACTIVITIES":"Enkeltstående aktiviteter",
/* Forums */
"ALLFORUMS":"Alle forummer",
"PUBLICFORUMS":"Offentlige forummer",
"MYFORUMS":"Mine forummer",
"EVERYTHINGFORUMS":"Alt fra forummer",
"FORUMSONLY":"Forummer",
"TOPICSFORUMS":"Forumemner",
"FORUMCATEGORIES": "Forumkategorier",
"FILESFORUMS":"Vedhæftninger fra forummer",
"ALLTYPESFORUMS":"Alle typer forummer",
"COMMUNITYFORUMS":"Forummer fra fællesskaber",
"STANDALONEFORUMS":"Enkeltstående forummer",
/* Blogs */
"ALLBLOGS":"Alle blogge",
"PUBLICBLOGS":"Offentlige blogge",
"MYBLOGS":"Mine blogge",
"EVERYTHINGBLOGS":"Alt fra blogge",
"BLOGSONLY":"Blogge",
"ENTRIESBLOGS":"Blogindlæg",
"FILESBLOGS":"Vedhæftninger fra blogge",
"EVERYTHINGIDEATIONBLOGS":"Alt fra idéblogge",
"BLOGSIDEATIONBLOGS":"Idéblogge",
"BLOGSIDEAS":"Idéer",
"ALLTYPESBLOGS":"Alle typer blogge",
"COMMUNITYBLOGS":"Blogge fra fællesskaber",
"COMMUNITYIDEATIONBLOGS":"Idéblogge fra fællesskaber",
"STANDALONEBLOGS":"Enkeltstående blogge",
/* Bookmarks */
"ALLBOOKMARKS":"Alle bogmærker",
"PUBLICBOOKMARKS":"Offentlige bogmærker",
"MYBOOKMARKS":"Mine bogmærker",
"ALLTYPESBOOKMARKS":"Alle typer bogmærker",
"COMMUNITYBOOKMARKS":"Bogmærker fra fællesskaber",
"STANDALONEBOOKMARKS":"Enkeltstående bogmærker",
/* Files */
"ALLFILES":"Alle filer",
"PUBLICFILES":"Offentlige filer",
"MYFILES":"Mine filer",
"ALLTYPESFILES":"Alle typer filer",
"COMMUNITYFILES":"Filer fra fællesskaber",
"STANDALONEFILES":"Enkeltstående filer",
"NUMDOWNLOADS":"{0} downloadninger",
/* Wikis */
"ALLWIKIS":"Alle wikier",
"PUBLICWIKIS":"Offentlige wikier",
"MYWIKIS":"Mine wikier",
"EVERYTHINGWIKIS":"Alt fra wikier",
"WIKISONLY":"Wikier",
"PAGESWIKIS":"Wikisider",
"FILESWIKIS":"Vedhæftninger fra wikier",
"ALLTYPESWIKIS":"Alle typer wikier",
"COMMUNITYWIKIS":"Wikier fra fællesskaber",
"STANDALONEWIKIS":"Enkeltstående wikier",
/* Status Updates */
"ALLSTATUSUPDATES":"Alle statusopdateringer",
"PUBLICSTATUSUPDATES":"Offentlige statusopdateringer",
"MYSTATUSUPDATES":"Mine statusopdateringer",
"ALLTYPESSTATUSUPDATES":"Alle typer statusopdateringer",
"COMMUNITYSTATUSUPDATES":"Statusopdateringer fra Fællesskaber",
"STANDALONESTATUSUPDATES":"Statusopdateringer fra Profiler",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Et antal brugere har oprettet bogmærke for denne URL",
"BOOKMARKEDCOMMUNITY":"Et antal brugere har oprettet bogmærke for dette fællesskab",
"BOOKMARKEDPROFILE":"Et antal brugere har oprettet bogmærke for denne profil",
"BOOKMARKEDBLOG":"Et antal brugere har oprettet bogmærke for denne blog",
"COMMUNITYBLOG":"Der er en blog i et fællesskab",
"BOOKMARKEDACTIVITY":"Et antal brugere har oprettet bogmærke for denne aktivitet",
"COMMUNITYACTIVITY":"Der er en aktivitet i et fællesskab",
"BOOKMARKEDFILE":"Et antal brugere har oprettet bogmærke for denne fil",
"COMMUNITYFILE":"Der er en fil i et fællesskab",
"BOOKMARKED":"Et antal brugere har oprettet bogmærke for denne wiki",
"COMMUNITYWIKI":"Der er en wiki i et fællesskab",
"BOOKMARKEDFORUM":"Et antal brugere har oprettet bogmærke for dette forum",
"COMMUNITYFORUM":"Der er et forum i et fællesskab",
"ALLTAGANDTTILE":"Klik på denne knap for at få vist alle titler og emneord for denne URL",
"TAGS_ARE_FROM":"Søgeresultatet kan indeholde emneord fra:",
"BOOKMARKS_TITLE":"Bogmærker",
"COMMUNITIES_TITLE":"Fællesskaber",
"ACTIVITIES_TITLE":"Aktiviteter",
"HELP":"Hjælp",
"MORESTATUSUPDATES":"Vis flere statusopdateringer, som matcher",
"TITLE_PREFIX":"titel:",
"LATEST_MESSAGE":"Seneste besked",
"LATEST_STATUS_UPDATE":"Seneste statusopdatering",
"LATEST_COMMUNITY_STATUS_UPDATE":"Seneste statusopdatering i fællesskab",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Seneste statusopdatering i fællesskaber",
"SEARCH_RESULTS":"Alt indhold - søgeresultater",
"ACTIVITIES_SEARCH_RESULTS":"Aktiviteter - søgeresultater",
"BLOGS_SEARCH_RESULTS":"Blogge - søgeresultater",
"BOOKMARKS_SEARCH_RESULTS":"Bogmærker - søgeresultater",
"COMMUNITIES_SEARCH_RESULTS":"Fællesskaber - søgeresultater",
"FILES_SEARCH_RESULTS":"Filer - søgeresultater",
"FORUMS_SEARCH_RESULTS":"Forummer - søgeresultater",
"PROFILES_SEARCH_RESULTS":"Profiler - søgeresultater",
"DIRECTORY_SEARCH_RESULTS":"${orgName}-adressekartotek - søgeresultater",
"WIKIS_SEARCH_RESULTS":"Wikier - søgeresultater",
"STATUS_UPDATES_SEARCH_RESULTS":"Statusopdateringer - søgeresultater",
"VIEW_ALL":"{span}Vis alle{/span} ({0})",
"MATCHING_ONE_OF":"Matcher en af:",
"MATCHING_ALL_OF":"Matcher alle af:",
"MATCHING":"Matcher:",
"MATCHING_DOC_TYPE":"Matcher dokumenttype:",
"BOOKMARK_HELP":"Hjælp til Bogmærker",
"CLOSE_BOOKMARK_HELP":"Luk hjælpen til Bogmærker",
"DOCUMENT_TYPE_PREFIX":"Dokumenttype:",
"FILE_PREVIEW_ONLY":"(Kun forhåndsvisningstilstand)"
})

