/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Je vyžadován název.",
	nourl: "Je vyžadována adresa URL.",
	fileSchema: "Chcete-li přidat odkaz na vzdálený nebo lokální soubor, musí odpovídat jednomu z následujících formátů: file://cesta_ke_vzdálenému_souboru nebo file:///cesta_k_lokálnímu_souboru.",
	invalidUrl: "Toto není platná adresa URL komunity.",
	invalidTagChar: "Seznam značek, který jste vytvořili, obsahuje neplatný znak '&'. Odeberte tento znak ze seznamu značek.",
	txtHelp: "Nápověda",
	txtHelpTags: "Nápověda pro značky",
	txtHelpTagsClose: "Zavřít nápovědu pro značky",
	tagsall: "Vše",
	tagsyours: "Vaše",
	tagsrecent: "Nedávné: ",
	tagspopular: "Oblíbené: ",
	tagsrecommended: "Doporučené: ",
	nothingselected: "Je vyžadován výběr komunity.",
	nothingselected_activity: "Je vyžadován výběr aktivity.",
	nothingselected_blogs: "Je vyžadován výběr blogu.",
	nothingselected_all: "Není vybrána žádná služba ani položka. Záložka nebude uložena.",
	nothingFeedselected: "Není vybrána žádná služba ani položka. Kanál nebude uložen.",
	alertDialogTitle: "Zpráva",
	alertDialogOK: "OK",
	expand: "Klepnutím tuto sekci rozbalíte.",
	collapse: "Klepnutím tuto sekci sbalíte.",
	discussThis: "Diskutovat",
	by: "o:",
	posted: "Zapsáno:",
	attachments: "Přílohy",
	communityForum: "Fórum komunity",
	notCommunityPage: "Aktuální webová stránka není platnou webovou stránkou komunity. Můžete ručně zadat nadpis komunity, odkaz na ni a její popis, aby byla vytvořena související komunita.",
	privateCommunityNotice: "Tato komunita je omezená a viditelná pouze pro členy.",
	forumNameHint : "Zadejte název fóra",
	formDescriptionHint:"Popište, proč by tato související komunita mohla vaši komunitu zajímat.",
	information : "Informace",
	error : "Chyba",
	success : "Úspěch",
	warning : "Varování",
	informationColon : "Informace:",
	successColon : "Úspěch:",
	warningColon : "Varování:",
	errorColon : "Chyba:",
	feedAlreadyExist : "Kanál v komunitě již existuje.",
	bookmarkAlreadyExist : "Záložka v komunitě již existuje.",
	mentionAuthWarning:"Uvedení lidé nebudou moci zobrazit zprávu, protože nejsou členy komunity:",
	mentionAuthForumWarning:"Uvedení lidé nebudou moci zobrazit zprávu, protože nemají přístup k tomuto fóru:",
	exceedDescLength: "Zadaný popis je příliš dlouhý.",
	communities_checked:"Počet vybraných komunit: ${0}",
	activities_checked:"Počet vybraných aktivit: ${0}",
	blogs_checked:"Počet vybraných blogů: ${0}"
})
