/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informació del node: ",
	"INSTALLED": "S'estan comprovant els serveis instal·lats",
	"RESUMETOKENS": "S'estan comprovant els testimonis represos",
	"SEEDLISTS": "S'està comprovant que les llistes d'origen estiguin disponibles",
	"CALENDARS": "S'està comprovant que els calendaris de planificació s'hagin configurat correctament",
	"VARIABLES": "S'està comprovant que les variables del WebSphere s'hagin definit",
	"TASKS": "S'estan cercant tasques d'indexació habilitades",
	"INDEXFILES": "S'estan cercant els fitxers necessaris a la carpeta d'índex",
	"LOGS": "S'estan revisant els registres a la recerca d'errors",
	"CONFIGFILES": "S'estan revisant els fitxers de configuració",
	"DICTIONARIES": "S'està comprovant el nombre de diccionaris que s'han habilitat",
	"SYNC": "S'està comprovant l'estat dels nodes",
	"DBRECORDS": "S'estan comprovant els registres de base de dades",
	"INSTALLEDMSG": "S'ha instal·lat el següent servei: ",
	"RESUMETOKENSMSG": "Testimoni reprès de: ",
	"SEEDLISTSMSG": "No s'ha pogut obtenir la llista d'origen de: ",
	"CALENDARSMSG": "S'ha passat la comprovació del calendari de planificació: ",
	"VARIABLESMSG": "Variable: ",
	"TASKSMSG": "La següent tasca s'ha habilitat: ",
	"INDEXFILESMSG" : "Els següents fitxers són a la carpeta de l'índex de cerca: ",
	"LOGSMSG" : "Reviseu els següents missatges d'error: ",
	"CONFIGFILESMSG" : "S'han trobat els següents fitxers de configuració: ",
	"DICTIONARIESMSG" : "El nombre de diccionaris habilitats és: ",
	"INSYNC": "Tots els nodes estan sincronitzats",
	"OUTOFSYNC": "El nombre de nodes no sincronitzats és: ",
	"NOTBLOCKED": "No hi ha nodes bloquejats",
	"BLOCKED": "El nombre de nodes bloquejats és: ",
	"INDATE": "Tots els nodes estan actualitzats",
	"OUTOFDATE": "El nombre de nodes obsolets és: ",
	"NUMOFDOCS": "El nombre de documents a la base de dades és ",
	"FILESTOCONVERT": "El nombre de documents de fitxers per convertir és ",
	"CONVERTEDFILES": "Ell nombre de fitxers convertits és ",
	"TOTALFILES": "El nombre total de fitxers a la base de dades ",
	"ERROR":"Error",
	"ERROR_PREFIX":"Error:",
	"INFO":"Informació",
	"INFO_PREFIX":"Informació:",
	"WARNING":"Advertiment",
	"WARNING_PREFIX":"Advertiment:",
	"LOADING_MESSAGE": "Carregant",
	"SERVER_STATUS": "Estat del servidor",
	"INITIAL_INDEXING_EXCEPTIONS": "Excepcions d'indexació inicial",
	"SYS_OUT_EXCEPTIONS": "Excepcions de registre de SystemOut",
	"SEEDLIST_VALIDATE": "Validació de llistes d'origen",
	"ERRORS_DURING_INITIAL_INDEXING":"Les excepcions següents s'han produït en crear un índex inicial",
	"CRAWL_FAILED": "Les dades del servei següent no s'han pogut rastrejar: ",
	"EXCEPTION_ENCOUNTERED": "El rastrejador ha fallat amb el missatge següent: ",
	"SAND_VALIDATE": "Validació SAND",
	"CHECK_FOR_SAND_FILES":"S'estan cercant els fitxers SAND",
	"IS_FILE_AVAILABLE":"S'està comprovant que s'ha creat el fitxer: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Les excepcions següents s'han produït en crear un índex inicial",
	"CRAWL_FAILED":"Les dades del servei següent no s'han pogut rastrejar: ",
	"EXCEPTION_ENCOUNTERED":"El rastrejador ha fallat amb el missatge següent: "
})

