/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Afegeix imatge",
   newUpload : "Nova càrrega",
   URL : "URL",
   imageLibrary : "Biblioteca d'imatges",
   description : "Descripció:",
   imageFile : "Fitxers:",
   OK: "D\'acord",
   cancel: "Cancel·la",
   required: "Camp necessari",
   preview: "Visualització prèvia:",
   previewWarning: "Sembla que la imatge no s'ha pogut carregar, esteu segur que l'url d'imatge és vàlid?",
   alt: "Text alternatiu:",
   filesTab: "Des de Fitxers",
   images:"Imatges:",
   browse:"Navega...",
   imagePickerTitle:"Insereix imatges de fitxers",
   componentImagePickerTitle:" ${0} imatges carregades",
   /* New String for insert image dialog */
   title: "Insereix imatge",
   uploadBtn: "Carrega imatge",   
   insertBtn: "Insereix imatge",
   uploadTab: "Fitxers locals",
   externalTab: "URL del web",
   internalTab: "Imatges existents",
   fileFieldTip: "Arrossegueu i deixeu anar imatges des de l'escriptori directament en aquesta finestra per pujar-les.",
   AdditionalSection: "Opcions addicionals",
   ExpandSection: "Expandir les opcions addicionals",
   CloseSection: "Reduir les opcions addicionals",
   webURLPrompt: "URL d'imatge del web:",
   previewPrompt: "Àrea de visualització prèvia: les imatges grans poden trigar una estona a visualitzar-se.",
   noExistingImage: "Encara no s'ha afegit cap imatge.",
   selectExistingImage: "Seleccioneu una imatge existent:",
   urlMissing: "Introdueix un URL",
   urlInvalid: "URL no vàlid. Assegureu-vos d'introduir un URL vàlid i torneu-ho a provar.",
   previousItem: "Anterior",
   nextItem: "Següent",
   oneImageOneTime: "Ja s'ha afegit una imatge en aquesta finestra. Només podeu inserir una imatge a la vegada.",
   loadingErrorMsg: "S'ha produït un error en carregar imatges existents. Torneu a intentar-ho més tard",
   urlInputTooltip: "Escriviu l'URL web URL de la imatge"
})

