/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Kuvan lisäys",
   newUpload : "Uusi siirto palvelimeen",
   URL : "URL-osoite",
   imageLibrary : "Kuvakirjasto",
   description : "Kuvaus:",
   imageFile : "Tiedostot:",
   OK: "OK",
   cancel: "Peruuta",
   required: "Pakollinen kenttä",
   preview: "Esikatselu:",
   previewWarning: "Kuvan lataus näyttää epäonnistuneen. Onko tämä varmasti kelvollinen kuvan URL-osoite?",
   alt: "Vaihtoehtoinen teksti:",
   filesTab: "Tiedostoista",
   images:"Kuvat:",
   browse:"Selaa...",
   imagePickerTitle:"Lisää kuvia Tiedostot-sovelluksesta",
   componentImagePickerTitle:" ${0} palvelimeen siirrettyä kuvaa",
   /* New String for insert image dialog */
   title: "Lisää kuva",
   uploadBtn: "Siirrä kuva palvelimeen",   
   insertBtn: "Lisää kuva",
   uploadTab: "Paikalliset tiedostot",
   externalTab: "Web-URL-osoite",
   internalTab: "Aiemmin luodut kuvat",
   fileFieldTip: "Lataa kuvia vetämällä ne työpöydältäsi suoraan tähän ikkunaan.",
   AdditionalSection: "Lisäasetukset",
   ExpandSection: "Laajenna lisäasetukset",
   CloseSection: "Pienennä lisäasetukset",
   webURLPrompt: "Web-kuvan URL-osoite:",
   previewPrompt: "Esikatselualue: Suurien kuvien näyttäminen saattaa viedä hetken.",
   noExistingImage: "Hups! Yhtään kuvaa ei ole vielä lisätty.",
   selectExistingImage: "Valitse aiemmin luotu kuva:",
   urlMissing: "Anna URL-osoite",
   urlInvalid: "URL-osoite on virheellinen. Tarkista antamasi URL-osoite ja yritä uudelleen.",
   previousItem: "Edellinen",
   nextItem: "Seuraava",
   oneImageOneTime: "Tähän ikkunaan on jo lisätty kuva. Kuvia voi lisätä vain yhden kerrallaan.",
   loadingErrorMsg: "Aiempia kuvia ladattaessa on ilmennyt virhe. Yritä myöhemmin uudelleen.",
   urlInputTooltip: "Anna kuvan Web-URL-osoite"
})

