/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "명함을 보려면 여기를 클릭하십시오",
	"label.semtag.hover.alt" : "{0}의 명함을 보려면 클릭하십시오",
	"label.semtag.hover.altA11Y" : "명함을 보려면 여기를 클릭하거나 Control-Enter를 누르십시오",
	"label.personcard.dialog.title" : "{0}의 명함",

	"errorDefaultMsg2" : "오류가 발생했습니다. 시스템 관리자에게 문의하십시오",

	"loadingSTStatus" : "Sametime 상태 로드 중...",
	"noStatuAvailable" : "사용 가능한 Sametime 상태 없음",

	"label.personcard.cardnomarkup" : "명함을 가져올 수 없음",
	"label.inactive.user.msg" : "이 사용자는 더 이상 활성 사용자가 아닙니다",
	"label.message.information" : "정보:",
	"label.personcard.noprofilemsg" : "이 사용자의 프로파일이 존재하지 않습니다",
	"label.personcard.cardreqexpired" : "명함 가져오기 요청이 만료되었습니다",

	"label.bizcard.applinks.less" : "간단히 표시",
	"label.bizcard.applinks.more" : "자세히 표시",

	"label.personcard.activitieslink" : "활동",
	"label.personcard.activitieslink.title" : "공유 활동을 보려면 여기를 클릭하십시오",
	"label.personcard.blogslink" : "블로그",
	"label.personcard.blogslink.title" : "이 사용자의 블로그를 보려면 여기를 클릭하십시오",
	"label.personcard.communitieslink" : "커뮤니티",
	"label.personcard.communitieslink.title" : "이 사용자의 커뮤니티를 보려면 여기를 클릭하십시오",
	"label.personcard.dogearlink" : "책갈피",
	"label.personcard.dogearlink.title" : "이 사용자의 책갈피를 보려면 여기를 클릭하십시오",
	"label.personcard.fileslink" : "파일",
	"label.personcard.fileslink.title" : "이 사용자의 공유된 파일을 보려면 여기를 클릭하십시오",
	"label.personcard.forumlink" : "포럼",
	"label.personcard.forumlink.title" : "이 사용자의 포럼 게시물을 보려면 여기를 클릭하십시오",
	"label.personcard.homepagelink" : "홈",
	"label.personcard.homepagelink.title" : "이 사용자의 홈 페이지를 보려면 여기를 클릭하십시오",
	"label.personcard.mobilelink" : "모바일",
	"label.personcard.mobilelink.title" : "이 사용자의 모바일 페이지를 보려면 여기를 클릭하십시오",
	"label.personcard.newslink" : "뉴스",
	"label.personcard.newslink.title" : "이 사용자의 뉴스를 보려면 여기를 클릭하십시오",
	"label.personcard.profilelink" : "프로파일",
	"label.personcard.profilelink.title" : "이 사용자의 프로파일을 보려면 여기를 클릭하십시오",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "이 사용자의 quickr 공유를 보려면 여기를 클릭하십시오",
	"label.personcard.wikislink" : "위키",
	"label.personcard.wikislink.title" : "이 사용자의 위키를 보려면 여기를 클릭하십시오",

	"personCardMoreActions" : "추가 조치",
	"personCardMoreActionsAltText" : "조치 메뉴를 보려면 클릭",

	"label.bizcard.dismiss": "이 명함을 닫으려면 Esc를 누르십시오.",
	"label.bizcard.fullProfile": "전체 프로파일",
	"label.bizcard.activities": "활동",
	"label.bizcard.communities": "커뮤니티",
	"label.bizcard.files": "파일",
	"label.bizcard.forums": "포럼",
	"label.bizcard.bookmarks": "책갈피",
	"label.bizcard.blogs": "블로그",
	"label.bizcard.wikis": "위키",

	"personCardAddAsColleagues" : "내 네트워크에 초대",
	"personCardAddAsMyColleagues" : "내 네트워크에 초대",
	"personCardFollow" : "관심 대상으로 등록",
	"personCardUnfollow" : "관심 대상에서 제거",
	"personCardChat" : "대화",
	"personCardCall" : "통화",
	"personCardSendMail" : "이메일 발송",
	"personCardSendEMail" : "이메일 발송",
	"personCardProxyStatusAvailable" : "대화 가능",
	"personCardDownloadVCard" : "vCard 다운로드",

	"friends" : "네트워크",
	"friendsFullPageTitle" : "네트워크",
	"friendsMenuTitleAllContacts" : "모든 네트워크 대화 상대",
	"friendsMenuTitleMyContacts" : "내 네트워크 대화 상대",
	"friendsInvitations" : "초대",
	"friendsMenuTitleInCommon" : "공통되는 사용자",
	"friendsShowAllCommonFriends" : "모두 표시...",
	"friendsViewAllFriends" : "모두 보기({0})",
	"friendsSendFriendRequest" : "요청 발송",
	"friendsNoFriends" : "이 프로파일에 연결된 네트워크 대화 상대가 없습니다",
	"friendsColleaguesInvite" : "{0}을(를) 네트워크 대화 상대로 초대",
	"friendsColleaguesFor" : "{0}의 네트워크 대화 상대",
	"friendsNewInv" : "{0}개의 새 초대",
	"friendsNewInvs" : "{0}개의 새 초대",
	"friendsLoading" : "네트워크 로드 중...",
	"friendsLoadingInv" : "초대 로드 중...",
	"friendsSelectFriendForRemoval" : "먼저 제거하려면 대화 상대를 선택하십시오.",
	"friendsRemoved" : "네트워크 대화 상대를 제거했습니다.",
	"friendsInvSent" : "보류 중인 초대가 있으므로 초대가 발송되지 않았습니다.",
	"friendsRemovedSelected" : "내 네트워크에서 제거",
	"friendsSortByDisplayName" : "표시 이름",
	"friendsSortByRecent" : "최근",
	"friendsTelephone" : "전화:",
	"friendsEmail" : "이메일:",
	"friendsAltEmail" : "대체 이메일:",
	"friendsNewInvitationsCount" : "{0}개의 새 초대가 있습니다",
	"friendsNoInv" : "초대가 없습니다",
	"friendsInCommonSingle" : "{0}명의 공통의 네트워크 대화 상대가 있습니다",
	"friendsInCommonMulti" : "{0}명의 공통의 네트워크 대화 상대가 있습니다",
	"friendsIncludeMsgForInv" : "초대에 메시지 포함:",
	"friendsInitialMsgForInv" : "귀하를 제 Connections 네트워크 대화 상대 목록에 추가하려고 합니다.",
	"friendsSendInvAction" : "초대 발송",
	"friendsCancelInvAction" : "취소",
	"friendsAcceptAction" : "수락",
	"friendsIgnoreAction" : "무시",
	"friendsYouExceedTextLimit" : "초대 메시지가 너무 깁니다. 최대 길이는 {1}자입니다. 이 필드는 {0}자입니다.",
	"friendsCannotAddYourself" : "자기 자신을 네트워크 대화 상대로 추가할 수 없습니다.",
	"friendsIsYourColleague" : "{0}은(는) 귀하의 네트워크 대화 상대입니다.",
	"friendsRecentlyAdded" : "귀하가 최근에 네트워크에 추가한 사용자입니다.",
	"friendsDate" : "날짜",
	"friendsCollapseWidget" : "네트워크 섹션을 접으려면 클릭",
	"friendsExpandWidget" : "네트워크 섹션을 펼치려면 클릭",
	"friendsIsInYourNetwork" : "{0}은(는) 귀하의 네트워크에 포함되어 있습니다.",
	"friendsActionsFor" : "네트워크에 대한 조치",
	"friendsInviteFollowError" : "{0}을(를) 관심 대상으로 등록하는 중에 오류가 발생했습니다",
	"friendsInviteTagError" : "{0}을(를) 태그하는 중에 오류가 발생했습니다",
	"friendsPleaseLogIn" : "네트워크에 사용자를 초대하려면 로그인하십시오",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0}은(는) 이미 귀하의 네트워크에 포함되어 있으므로 네트워크에 초대할 수 없습니다.",
	"friendsInviteAddTagsFor" : "{0}에 대한 태그:",
	"friendsInviteAlsoFollow" : "관심 대상으로 등록",
	"friendsInviteReceiveUpdates" : "(업데이트 수신)",
	"friendsInviteUpdatesDescription" : "홈 페이지 및 이메일 요약에서 관심 대상으로 등록한 사용자에 대한 업데이트를 수신합니다.",
	"friendsInviteFollowHelp": "자세한 정보는 {0}관심 대상으로 등록{1}을 참조하십시오.",
	"friendsNetwork" : "네트워크",
	"friendsMyNetwork" : "네트워크",
	"friendsNetworkFor" : "{0}의 네트워크",
	"friendsRemoveSelected" : "선택한 항목 제거",
	"friendsRemoveSelectedTip" : "네트워크에서 선택한 사용자를 제거하려면 클릭하십시오.",
	"friendsNetworkInCommon" : "{0}개의 공통되는 네트워크 연결이 있습니다.",
	"friendsAddToMyNetwork" : "귀하를 제 Connections 네트워크에 추가하려고 합니다.",
	"friendsInvite" : "내 네트워크에 초대",
	"friendsInvitePerson" : "{0}을(를) 네트워크에 초대",
	"friendsInviteMessage" : "귀하를 제 Connections 네트워크에 추가하려고 합니다.",
	"friendsInvitedEmailSubject" : "[프로파일] 제 네트워크에 가입하도록 귀하를 초대합니다",
	"friendsInvitedEmailMsg1" : "님이 초대에 다음 메시지를 포함하여 귀하를 네트워크 대화 상대로 초대했습니다:",
	"friendsInvitedEmailMsg2" : "네트워크 초대 페이지 열기",
	"friendsInvitedEmailMsg3" : "귀하를 제 네트워크에 추가하려고 합니다.",
	"friendsInvitedEmailMsg4" : "{0}님이 귀하를 네트워크 대화 상대로 초대했습니다:",
	"friendsInvitedEmailMsg5" : "{0님이 초대에 다음 메시지를 포함하여 귀하를 네트워크 대화 상대로 초대했습니다:",
	"friendsInviteLegalNote" : "이 초대를 발송하면 {0}님이 귀하의 프로파일 보드에 댓글을 작성하도록 허용하는 데 동의하는 것으로 간주됩니다.",
	"friendsInviteFailed" : "서버 오류로 인해 초대받은 사람에게 이메일 알림이 발송되지 않았습니다. 단, 초대받은 사람은 프로파일 웹 애플리케이션을 통해 초대를 수락할 수 있습니다.",
	"personInNetwork" : "네트워크 대화 상대"
})
