define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Sulje",
		   'rs_loading' : "Lataus on meneillään...",
		   'rs_at' : "kello",
		   'rs_searchDirectory' : "Eikö henkilöä löydy luettelosta? Kokeile täyttä hakua...",
		   'rs_searchGroupDirectory' : "Eikö ryhmää löydy luettelosta? Kokeile täyttä hakua...",
		   'rs_searchPersonAndGroupDirectory' : "Eikö henkilöä tai ryhmää löydy luettelosta? Kokeile täyttä hakua...",
		   'rs_searchCommunityDirectory' : "Eikö yhteisöä löydy luettelosta? Kokeile täyttä hakua...",
		   'rs_shadowText_searchDirectory' : "Etsi henkilöä kirjoittamalla",
		   'rs_shadowText_searchGroupDirectory' : "Etsi ryhmää kirjoittamalla",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Etsi henkilöä tai ryhmää kirjoittamalla",
		   'rs_shadowText_searchCommunityDirectory' : "Etsi yhteisöä kirjoittamalla",
		   'rs_listItem' : "Luettelon kohta",
		   'rs_noResults' : "Haulle ${0} ei löytynyt tuloksia.",
		   'rs_today' : "Tänään",
		   'rs_tomorrow' : "Huomenna",
		   'rs_yesterday' : "Eilen",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Näiden aktiviteettien syöte",
		   'rs_externalText' : "Tähän aktiviteettiin voidaan lisätä organisaatiosi ulkopuolisia jäseniä.",
		   'rs_moveActivitySuccess' : 'Aktiviteetin ${activityTitle} siirto aliyhteisöön ${destCommName} on onnistunut.',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Näytä lisätietoja aktiviteetista',
		   'rs_hideInfo' : 'Piilota lisätiedot',
		   'rs_more' : "Lisää",
		   'rs_hide' : "Piilota",
		   'rs_edit' : "Muokkaa",
		   'rs_restore' : "Palauta",
		   'rs_deleteEntry' : "Poista",
		   'rs_prioritize' : "Priorisoi",
		   'rs_markComplete' : "Merkitse valmiiksi",
		   'rs_markIncomplete' : "Palauta",
		   'rs_linkMore' : "... [lisää]",
		   'rs_linkLess' : "... [vähemmän]",
		   'rs_actUpdatedByDate' : "Päivittäjä ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Päivittäjä ${0}",// Updated by (author name)
		   'rs_actDue' : "Määräpäivä: ${0}",// Due (date)
		   'rs_actTags' : "Tunnisteet: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Aloita aktiviteetti tästä mallipohjasta",
		   'rs_favoriteTemplate' : "Merkitse suosikkimallipohjaksi",
		   'rs_normalTemplate' : "Merkitse normaaliksi mallipohjaksi",
		   'rs_tunedOutPri' : "Laskettu prioriteetti",
		   'rs_pagepos' : "${0}–${1}/${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Edellinen",
		   'rs_navNextLabel' : "Seuraava",
		   'rs_noActivities' : "Yhteisössä ei ole aloitettuja aktiviteetteja.",
		   'rs_feedError' : "Syötteen lataus epäonnistui.",
		   'rs_highPri' : "Korkea prioriteetti",
		   'rs_medPri' : "Keskitason prioriteetti",
		   'rs_normalPri' : "Normaali prioriteetti (oletus)",
		   'rs_tuneOut' : "Määritä aktiviteetiksi, jonka prioriteettia on laskettu",
		   'rs_startActivity' : "Aloita aktiviteetti",
		   'rs_startFirstActivity' : "Luo ensimmäinen aktiviteettisi",
		   'rs_navNextLabel' : "Seuraava",
		   'rs_viewAll' : "Näytä kaikki",
		   'rs_activityWidgetTitle' : "Aktiviteetit",
		   'rs_activityWidgetBriefDescription' : "Seuraa yhteisön tavoitteita.  Luo tehtäviä ja jaa resursseja.",
		   'rs_activityWidgetDescription' : "Yhteisön aktiviteettien avulla voit tehdä yhteistyötä ja seurata yhteisön projektien tai hankkeiden edistymistä.",
		   'rs_completedActivityLink' : "Näytä valmiit aktiviteetit",
		   'rs_activitiesUnavailable' : "Aktiviteetit-palvelu ei ole käytettävissä.",
		   'rs_errorPersists' : "Jos ongelma ei poistu, ota yhteys järjestelmän pääkäyttäjään.",
		   'rs_shared' : "Yhteiskäytössä",
		   'rs_removeActFromComm' : "Poista yhteisöstä",
		   'rs_externalLabel' : "Ulkoinen",
		   // for ActivityForm
		   'rs_templateOptions' : "Mallipohjan asetukset",
		   'rs_template' : "Mallipohja",
		   'rs_tagsLabel' : "Tunnisteet",
		   'rs_peopleLabel' : "Henkilöt",
		   'rs_aboutThisTemplate' : "Tietoja tästä mallipohjasta",
		   'rs_activity' : "Aktiviteetti",
		   'rs_copyOf' : "Kohteen ${0} kopio",// copy of (activity name)
		   'rs_activityFormGoal' : "Aktiviteetin tavoite",
		   'rs_noTemplate' : "Ei mitään",
		   'rs_copyActivityMembers' : "Käytä aktiviteetin jäseniä",
		   'rs_copyTemplateMembers' : "Käytä mallipohjan jäseniä",
		   /* Forum Widget */
		   'rs_noTopics' : "Yhteisössä ei ole vielä aiheita.",
		   'rs_noTopicsLoggedIn' : "Voit esittää kysymyksiä, pitää aivoriihen tai vain jakaa ideoita.",
		   'rs_postedBy' : "Viimeisin lisäys, jonka on tehnyt",
		   'rs_topics' : "aihetta",
		   'rs_noTopicsShort' : "Ei aiheita",
		   'rs_topic' : "aihe",
		   'rs_replies' : "vastausta",
		   'rs_noReplies' : "Ei vastauksia",
		   'rs_reply' : "vastaus",
		   'rs_startTopic' : "Aloita aihe",
		   'rs_startFirstTopic' : "Aloita ensimmäinen aihe",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Lukittu]",
		   'rs_manageForumSetting' : "Keskusteluryhmän asetusten hallinta",
		   'rs_forumSettingCommunityOverviewPage' : "Yhteisön yleiskuvaussivu:",
		   'rs_defaultForumList' : "Näytä keskusteluryhmäluettelo oletusarvon mukaan",
		   'rs_defaultTopicList' : "Näytä aiheluettelo oletusarvon mukaan",
		   'rs_forumSettingApplicationView' : "Keskusteluryhmä-sovelluksen oletusnäkymä:",
		   'rs_forumSettingNote' : "Huomautus: Aiheet ovat näkyvissä oletusarvon mukaan, jos keskusteluryhmiä on vain yksi.",
		   'rs_forumSettingSubmit' : "Lähetä",
		   'rs_forumSettingSave' : "Tallenna",
		   'rs_forumSettingSaveAndClose' : "Tallenna ja sulje",
		   'rs_forumSettingConfirm' : "Keskusteluryhmään tehdyt muutokset on tallennettu.",
		   'rs_forumSettingError' : "On ilmennyt virhe. Ota yhteys pääkäyttäjään.",
		   'rs_formSettingHideMessage' : "Piilota tämä sanoma",
		   'rs_forumSettingCancel' : "Peruuta",
		   'rs_forumAnsweredQuestion' : "Vastattu kysymys",
		   'rs_forumUnAnsweredQuestion' : "Vastaamaton kysymys",
		   'rs_forumSortBy' : "Lajitteluperuste:",
		   'rs_forumSortByDate' : "Päivämäärä",
		   'rs_forumSortByReplies' : "Vastaukset",
		   'rs_forumSortByTopic' : "Aiheet",
		   'rs_forumSortByTopicsAndReplies' : "Aiheet ja vastaukset",
		   'rs_sortByReplies' : "Lajittele vastausten mukaan",
		   'rs_sortbyTopicsAndReplies' : "Lajittele aiheiden ja vastausten mukaan",
		   'rs_forumOpenQuestions' : "Avoimet kysymykset",
		   'rs_feedOpenQuestions' : "Näiden avoimien kysymysten syöte",
		   'rs_feedAnsweredQuestions' : "Näiden vastattujen kysymysten syöte",
		   'rs_forumMessages' : "${0} viestiä",
		   'rs_forumLastAddedPost' : "Viimeisin lisäys, jonka on tehnyt ${0}",
		   'rs_forumTopics' : "${0} aihetta",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Luo henkilölinkki",
		   'rs_quote' : "Lainaa",
		   'rs_labelColon' : "Nimiö: ",
		   'rs_personColon' : "Henkilö: ",
		   'rs_personLink' : "Henkilölinkki",
		   'rs_replace' : "Korvaa",
		   'rs_inactivePerson' : "${0} (passiivinen)", // person's name (inactive)
		   'rs_PersonPicture' : "Henkilön ${0} kuva", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Ulkoinen käyttäjä", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (ulkoinen käyttäjä)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Henkilön ${0} kuva (ulkoinen käyttäjä)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Käyttäjällä on sellaisten tiedostojen ja yhteisöjen käyttöoikeus, jotka on määritetty yhteiskäyttöön ulkopuolisten kanssa.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Ilmoita muille henkilöille",
		   'rs_messageColon' : "Viesti: ",
		   'rs_notifyColon' : "Ilmoita: ",
		   'rs_notificationConfirm' : "Ilmoitusviesti on lähetetty. ",
		   'rs_notificationFail' : "Ilmoitusviestiä ei lähetetty. Yritä uudelleen myöhemmin ja ota yhteys järjestelmän pääkäyttäjään, jos ongelma ei poistu.",
		   'rs_pickCommunity' : "Valitse yhteisöluettelosta",
		   'rs_typeName' : "Kirjoita nimi",
		   'rs_typeToFilter' : "Voit suodattaa luetteloa kirjoittamalla suodatusehdon tähän",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Voit suodattaa luetteloa kirjoittamalla suodatusehdon tähän",
		   'rs_filterGroupLabel' : "Valitse ryhmä",
		   'rs_noResults' : "Tuloksia ei löytynyt",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Näytössä on ${0} / ${1} tulosta",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Poista",
		   /* Language Selector */
		   'rs_browser_setting' : "Selainasetus",
		   'rs_customLangaugeLinkLabel' : "Mukautettu kieli",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Siirry sivulle ${0}/${1}",
		   "rs_jumpPageLabel" : "Siirry sivulle",
		   'rs_pageNumLabel' : "Sivunumero",
		   'rs_pageLabel' : "Sivu:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Tunnisteet',
		   'rs_tagCloudToggleHint' : "Näytä tai piilota napsauttamalla",
		   'rs_tagCloudHelpAlt' : "Tunnisteiden käytön ohjeet",
		   'rs_tagCloudNoTags' : "Tunnisteita ei ole vielä.",
		   'rs_tagCloudNoRecentTags' : "Äskettäin lisättyjä tunnisteita ei ole",
		   'rs_tagCloudNoTagsProfiles' : "Hae hakemistosta. Haun palauttamiin profiileihin liitetyt tunnisteet tulevat näkyviin tähän.",
		   'rs_tagLoadingTags' : "Sisällön lataus",
		   'rs_tagCloudSelectedTags' : "Valitut tunnisteet",
		   'rs_tagCloudSeachDesc' : "Etsi tunniste",
		   'rs_tagCloudSeach' : "Hae",
		   'rs_tagCloudRelatedTags' : "Liittyvät tunnisteet",
		   'rs_tagCloudRelatedTagsDescription' : "Tarkenna hakua edelleen lisäämällä liittyvä tunniste",
		   'rs_tagCloudError' : 'On ilmennyt virhe',
		   'rs_viewAsCloud' : "Tunnistejoukko",
		   'rs_viewAsCloudTitle' : "Näytä tunnisteet tunnistejoukkona",
		   'rs_viewAsCloudDescription' : "Tunnisteet näytetään tunnistejoukkona",
		   'rs_viewAsList' : "Luettelo",
		   'rs_viewAsListTitle' : "Näytä tunnisteet peräkkäisluettelona",
		   'rs_viewAsListDescription' : "Tunnisteet näytetään peräkkäisluettelona",
		   'rs_tagCloudViewAll' : "Selaa",
		   'rs_tagCloudViewAllTitle' : "Selaa kaikkia tunnisteita",
		   'rs_normalTags' : "Käytössä olevat tunnisteet",
		   'rs_removeTag' : "Poista tunniste valituista suodatintunnisteista",
		   'rs_clearAll' : "Tyhjennä kaikki",
		   'rs_searchInputDefault' : "Etsi tunnistetta kirjoittamalla",
		   'rs_searchInputTagSelected' : "Kirjoita toinen tunniste",
		   'rs_relatedTagTitle' : "Näytä tunnisteen ${0} hakutulokset. Määrä: ${1}",
		   'rs_removeTagTitle' : "Poista tunniste ${0} valituista suodatintunnisteista",
		   'rs_addTagTitle' : "Käytä suodatusperusteena tunnistetta ${0}, joka esiintyy ${1} kertaa",
		   'rs_tagDialogCloseTile' : "Sulje",
		   'rs_tagDialogTitle' : "Kaikki tunnisteet",
		   'rs_tagDialogPageInfo' : "${0} - ${1} / ${2} tunnisteesta",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Selaa ryhmiä",
		   'rs_group_browse_groups_dialog_title' : "Selaa ryhmiä",
		   'rs_group_browse_find_groups' : "Etsi ryhmiä",
		   'rs_group_browse_add_button' : "Lisää",
		   'rs_group_browse_cancel_button' : "Peruuta",
		   'rs_group_browse_enter_string' : "Etsi ryhmiä kirjoittamalla",
		   'rs_group_browse_group_typeahead_label' : "Kirjoita ryhmän nimi:",
		   'rs_group_browse_group_name' : "Ryhmän nimi:",
		   'rs_group_browse_results_label' : "Valitse vastaava ryhmä:",
		   'rs_group_browse_parent_group_label' : "Käsittelet nyt kohdetta:",
		   'rs_group_browse_next_page' : "Seuraava sivu",
		   'rs_group_browse_previous' : "Edellinen",
		   'rs_group_browse_next' : "Seuraava",
		   'rs_group_browse_paging' : "Sivunumerot",
		   'rs_group_browse_previous_page' : "Edellinen sivu",
		   'rs_group_browse_group_selected' : "Valittu ryhmä:",
		   'rs_group_browse_group_no_groups' : "Tämä ryhmä ei sisällä ryhmiä",
		   'rs_group_browse_page_info' : "${0}–${1}/${2}",
		   'rs_group_browse_page_info_alt' : "Vastaavat ryhmät ${0}–${1}/${2}",
		   'rs_group_browse_remove_selection' : 'Poista sisäkkäisen ryhmän valinta: ${0}',
		   'rs_group_browse_paging' : "Sivunumerot",
		   'rs_member_groups' : "Ryhmät",
		   'rs_member_members' : "Jäsenet",
		   'rs_member_no_results' : "Tuloksia ei löytynyt",
		   'rs_member_remove_group' : "Poista ${0}",
		   'rs_member_add_to_community' : "Lisää jäsen napsauttamalla",
		   'rs_member_remove_name' : "Poista jäsen napsauttamalla",
		   'rs_group_add_to_community' : "Lisää ryhmä napsauttamalla",
		   'rs_group_remove_name' : "Poista ryhmä napsauttamalla",
		   'rs_group_name' : "Ryhmän nimi",
		   'rs_group_role' : "Ryhmän rooli",
		   'rs_warning' : "Varoitus",
		   'rs_a11y_warning' : "Varoitus:",
		   'rs_messagebox_close_btn_title' : "Sulje",
		   'rs_messagebox_close_btn_alt' : "Sulje",
		   'rs_messagebox_error_icon_alt' : "Virhe",
		   'rs_messagebox_error_a11y_label' : "Virhe:",
		   'rs_messagebox_warning_icon_alt' : "Varoitus",
		   'rs_messagebox_warning_a11y_label' : "Varoitus:",
		   'rs_messagebox_info_icon_alt' : "Ilmoitus",
		   'rs_messagebox_info_a11y_label' : "Tiedot:",
		   'rs_messagebox_success_icon_alt' : "Onnistui",
		   'rs_messagebox_success_a11y_label' : "Onnistui:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Lisää linkki tiedostoihin",
		   'rs_docpicker_label' : "Linkki tiedostoihin",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Lataa ${0}",
		   'rs_docpicker_viewdetails_text' : "Näytä tiedot",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Näytä kohteen ${0} tiedot",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Poista",
		   'rs_attachedfile_filename' : "Kuva ${0}",
		   'rs_feedreader_warning' : "Varoitus: Tämä linkki on tarkoitettu syötteiden lukuohjelmille, eikä se ehkä näy oikein selaimessa. Jatka napsauttamalla OK-painiketta tai palaa sivulle napsauttamalla Peruuta-painiketta.",
		   'rs_search' : "Hae",
		   'rs_all_connections' : "Kaikki sisällöt",
		   'rs_advanced' : "Tarkennettu haku",
		   'rs_select_scope' : "Valitse hakualue",
		   'rs_icfixlayout' : {
		      button_label : "Muotoile uudelleen",
		      dialog_title : "Muotoile sisältö uudelleen",
		      warning : "Varoitus",
		      reformat_save : "Muotoile uudelleen ja tallenna",
		      save_as_is : "Tallenna sellaisenaan",
		      cancel : "Peruuta",
		      warn_layout : "Sisällön leveys ylittää näytön enimmäisleveyden.  Haluatko muotoilla sisällön automaattisesti uudelleen, jotta se mahtuu käytettävissä olevaan tilaan?",
		      remember_decision : "Muista valinta"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Valittujen tiedostojen määrityksessä yhteiskäyttöön on ilmennyt virhe.",
		   'rs_sharefile_access_denied' : "Tämä tiedosto on poistettu, tai se ei ole enää yhteiskäytössä kanssasi.",
		   'rs_sharefile_invalid_request' : "Valittujen tiedostojen määrityksessä yhteiskäyttöön on ilmennyt virhe.",
		   'rs_sharefile_sharing_intent_restriction' : "Tiedosto voidaan määrittää yhteiskäyttöön vain organisaation sisäisesti.",
		   'rs_sharefile_error_title' : "Virhe",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'App Storessa',
		   'rs_mobileBanner_inGooglePlay' : 'Google Playssa',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Avaa',
		   'rs_mobileBanner_view' : 'Näytä',
		   'rs_mobileBanner_hide' : 'Piilota',

		   'rs_empty_column_placeholder' : 'Vedä sovelluksia tähän.',
		   'rs_widget_loading_error_title' : 'Widget-objektin esittäminen ei onnistu',
		   'rs_widget_loading_error_message' : 'Yritä uudelleen myöhemmin ja ota yhteys järjestelmän pääkäyttäjään, jos ongelma ei poistu.',
		   'rs_widgets_loading_error_title' : 'Widget-objektien esittäminen tässä yhteisössä ei onnistu',
		   'rs_widget_misplacement_warning' : 'Sovellus ei mahdu sarakkeeseen. Yhteisön omistaja voi siirtää sen toiseen sarakkeeseen tai poistaa sen sivulta.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Annettu otsikko on liian pitkä.',
		      empty_new_title : 'Annettu otsikko ei saa olla tyhjä.',
		      default_message : 'Sovelluksen ${0} otsikon muutto ei onnistu.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Otsikko:  ',
		   'rs_widget_title_change_direction' : 'Muuta sovelluksen ${0} otsikkoa.',
		   'rs_widget_title_change_title' : 'Muuta otsikkoa',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Kutsu tai lisää jäseniä",
		   'rs_vmmainContentDesc' : "Voit myös antaa jäsenille mahdollisuuden liittyä yhteisöön kutsumalla heidät. Voit sisällyttää jäseniä automaattisesti lisäämällä heidät.",
		   'rs_vmtypeAheadLabel' : "Nimi tai sähköpostiosoite: ",
		   'rs_vmgroupTypeAheadLabel' : "Nimi: ",
		   'rs_vmtypeAheadRoleLabel' : " rooli ",
		   'rs_vmgroupTypeAheadRoleLabel' : " jäseniksi ",
		   'rs_vmtaNoResults' : "Tuloksia ei löytynyt.",
		   'rs_vmtaHeader' : "otsikko",
		   'rs_vmaddUser' : "Lisää",
		   'rs_vmradioSectionTitle' : "Jäsenen asetukset:",
		   'rs_vmradioOne' : "Lähetä kutsut liittyä yhteisöön",
		   'rs_vmradioTwo' : "Lisää käyttäjät yhteisöön automaattisesti",
		   'rs_vmtwistyA' : "Lisää valinnainen viesti",
		   'rs_vmtwistyB' : "Poista lisäteksti",
		   'rs_vmmessage' : "Viesti:",
		   'rs_vmtextAreaStartText' : "Kirjoita jotakin...",
		   'rs_vmcheckboxLabel' : "Lähetä kopio itselle",
		   'rs_vmsave' : "Tallenna",
		   'rs_vminvite' : "Kutsu",
		   'rs_vmcancel' : "Peruuta",
		   'rs_userContentTitle' : "Anna tiedot",
		   'rs_vmaddUser' : "Luo käyttäjä",
		   'rs_vmback'	 : "Edellinen",
		   'rs_vmvisitor'	 : "Vierailija",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Kopioi yhteisö napsauttamalla tätä',
			'rs_commpicker' : ''

});
