/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informações sobre o nó: ",
	"INSTALLED": "A verificar os serviços instalados",
	"RESUMETOKENS": "A verificar os símbolos de retoma",
	"SEEDLISTS": "A verificar se as seedlists estão disponíveis",
	"CALENDARS": "A verificar se as agendas foram correctamente configuradas",
	"VARIABLES": "A verificar se as variáveis do WebSphere foram definidas",
	"TASKS": "A verificar a existência de tarefas de indexação activadas",
	"INDEXFILES": "A verificar a pasta de índice para os ficheiros requeridos",
	"LOGS": "A rever os registos para os erros",
	"CONFIGFILES": "A rever os ficheiros de configuração",
	"DICTIONARIES": "A verificar o número de dicionários que foram activados",
	"SYNC": "A verificar o estado dos nós",
	"DBRECORDS": "A verificar os registos da base de dados",
	"INSTALLEDMSG": "O seguinte serviço está instalado: ",
	"RESUMETOKENSMSG": "O símbolo de restauro para: ",
	"SEEDLISTSMSG": "Não foi possível obter a seedlist para: ",
	"CALENDARSMSG": "A agenda passou na verificação: ",
	"VARIABLESMSG": "Variável: ",
	"TASKSMSG": "A seguinte tarefa está activada: ",
	"INDEXFILESMSG" : "Os seguintes ficheiros encontram-se na pasta do índice da procura: ",
	"LOGSMSG" : "Rever as seguintes mensagens de erro: ",
	"CONFIGFILESMSG" : "Foram localizados os seguintes ficheiros de configuração: ",
	"DICTIONARIESMSG" : "O número de dicionários activado é: ",
	"INSYNC": "Todos os nós estão sincronizados",
	"OUTOFSYNC": "O número de nós dessincronizados é: ",
	"NOTBLOCKED": "Nenhum nó bloqueado",
	"BLOCKED": "O número de nós bloqueados é: ",
	"INDATE": "Todos os nós estão actualizados",
	"OUTOFDATE": "O número de nós desactualizados é: ",
	"NUMOFDOCS": "O número de documentos na base de dados é ",
	"FILESTOCONVERT": "O número de documentos de ficheiro a converter é ",
	"CONVERTEDFILES": "O número de ficheiros convertidos é ",
	"TOTALFILES": "O número total de ficheiros na base de dados ",
	"ERROR":"Erro",
	"ERROR_PREFIX":"Erro:",
	"INFO":"Informações",
	"INFO_PREFIX":"Informações:",
	"WARNING":"Aviso",
	"WARNING_PREFIX":"Aviso:",
	"LOADING_MESSAGE": "Carregar",
	"SERVER_STATUS": "Estado do servidor",
	"INITIAL_INDEXING_EXCEPTIONS": "Excepções de indexação inicial",
	"SYS_OUT_EXCEPTIONS": "Excepções do registo do SystemOut",
	"SEEDLIST_VALIDATE": "Validação de seedlists",
	"ERRORS_DURING_INITIAL_INDEXING":"As excepções que se seguem ocorreram ao criar um índice inicial",
	"CRAWL_FAILED": "Não foi possível pesquisar quaisquer dados do serviço seguinte: ",
	"EXCEPTION_ENCOUNTERED": "A pesquisa falhou com a seguinte mensagem: ",
	"SAND_VALIDATE": "Validação de SAND",
	"CHECK_FOR_SAND_FILES":"A verificar a existência de ficheiros de SAND",
	"IS_FILE_AVAILABLE":"A verificar se o ficheiro foi criado: ",
	"ERRORS_DURING_INITIAL_INDEXING":"As excepções que se seguem ocorreram ao criar um índice inicial",
	"CRAWL_FAILED":"Não foi possível pesquisar quaisquer dados do serviço seguinte:",
	"EXCEPTION_ENCOUNTERED":"A pesquisa falhou com a seguinte mensagem: "
})

