/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrar por:",
"SHOW":"Mostrar:",
"ACL_FILTER_LABEL":"Filtrar por visibilidade",
"PARENT_FILTER_LABEL":"Filtrar por contentor",
"TYPE_FILTER_LABEL":"Filtrar por tipo",
"PAGING_TOP":"Paginação principal",
"PAGING_BOTTOM":"Paginação secundária",
"PREVIOUS":"Anterior",
"NEXT":"Seguinte",
"PAGE":"Página {0} de {1}",
"PAGE_COLON":"Página:",
"RESULTS":"{span}{0} - {1}{/span} de {2}",
"ITEMS":"{0} itens",
/* Application names */
"ACTIVITIES":"Actividades",
"BLOGS":"Blogues",
"CALENDAR":"Agenda",
"COMMUNITIES":"Comunidades",
"BOOKMARKS":"Marcadores",
"DOGEAR":"Marcadores",
"EVENTS":"Eventos",
"FILES":"Ficheiros",
"FORUMS":"Fóruns",
"PROFILES":"Perfis",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Feeds",
"STATUS_UPDATES":"Actualizações de estado",
"ONECOMMENT":"1 comentário",
"COMMENTS":"{0} comentários",
"ONEPERSON":"1 Pessoa",
"PEOPLE":"{0} Pessoas",
"TAGS":"Etiquetas:",
"TAGSMORE":"e {0} mais",
"NORESULTSMESSAGE":"Não foram localizados quaisquer resultados para essa procura",
"JAN":"Janeiro",
"FEB":"Fevereiro",
"MAR":"Março",
"APR":"Abril",
"MAY":"Maio",
"JUN":"Junho",
"JUL":"Julho",
"AUG":"Agosto",
"SEP":"Setembro",
"OCT":"Outubro",
"NOV":"Novembro",
"DEC":"Dezembro",
"NO_CONTACT":"A procura não foi efectuada, uma vez que não foi possível contactar o servidor",
"SERVER_ERROR":"A procura não foi efectuada, devido a um erro do servidor",
"SORT_BY":"Ordenar por:",
"SORT_RELEVANCE":"Relevância",
"SORT_DATE":"Data",
"SORT_LAST_UPDATED":"Última actualização",
"SORT_DUE_DATE":"Data de conclusão",
"SORT_VISITS":"Visitas",
"SORT_COMMENTS":"Comentários",
"SORT_RECOMMENDATION":"Gostos",
"SORT_POPULARITY":"Popularidade",
"SORT_FIRSTNAME":"Nome próprio",
"SORT_LASTNAME":"Apelido",
"SORT_DOWNLOADS":"Transferências",
"SORT_TYPE":"Tipo",
"SORT_SIZE":"Tamanho",
"SORT_TITLE":"Título",
"PRIVATE":"Particular",
"MODERATED":"Moderada",
"COMMUNITY_ACTIVITY":"Actividade da comunidade",
"COMMUNITY_BLOG":"Blogue da comunidade",
"COMMUNITY_FILE":"Ficheiro da comunidade",
"COMMUNITY_FORUM":"Fórum da comunidade",
"COMMUNITY_WIKI":"Wiki da comunidade",
"COMMUNITY_FEED":"Feed da comunidade",
"COMMUNITY_BOOKMARK":"Marcador da comunidade",
"NO_TAG":"Ainda não existem etiquetas",
"NO_DATE":"Ainda não existem datas",
"NO_PEOPLE":"Nenhuma pessoa",
"REMOVE_FILTER_LABEL":"Faça clique para remover",
"REMOVE_FILTER_TITLE":"Remover",
"REMOVE_FILTER_TOOLTIP":"Remover este filtro",
"COMMENT_ON":"Comentar:",
"EXPAND_COLLAPSE":"Faça clique para expandir/contrair",
"EXPAND":"Expandir",
"COLLAPSE":"Contrair",
"EXPAND_MONTHS_FILTER":"Expandir o filtro de meses do ano {0}",
"SORT_RELEVANCE_LABEL":"Faça clique para ordenar por relevância",
"SORT_DATE_LABEL":"Faça clique para ordenar por data",
"SORT_UPDATED_LABEL":"Faça clique para ordenar pela última actualização",
"SORT_DUE_LABEL":"Faça clique para ordenar pela data de conclusão",
"SORT_VISITS_LABEL":"Faça clique para ordenar por número de visitas",
"SORT_COMMENTS_LABEL":"Faça clique para ordenar por número de comentários",
"SORT_RECOMMENDATIONS_LABEL":"Faça clique para ordenar por número de gostos",
"SORT_POPULARITY_LABEL":"Faça clique para ordenar por popularidade",
"SORT_FIRST_NAME_LABEL":"Faça clique para ordenar por nome próprio",
"SORT_LAST_NAME_LABEL":"Faça clique para ordenar por apelido",
"RATING":"Gostos",
"GRADUATED":"Graduada",
"ONEVOTE":"1 voto",
"VOTES":"{0} votos",
"BOOKMARK_THIS_RESULT":"Marcar isto",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inactivo)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} pessoas marcadas",
/* eg from an Activity */
"FROMANACTIVITY":"a partir de uma actividade",
"FROMABLOG":"a partir de um blogue",
"FROMANIDEATIONBLOG":"a partir de um Blogue de ideias",
"FROMANEVENT":"a partir de um evento",
"FROMAFORUM":"a partir de um fórum",
"FROMAWIKI":"a partir de um wiki",
"FROMACOMMUNITY":"a partir de uma comunidade",
"FROMXCOMMUNITIES":"de {0} Comunidades",
/* For search results parentage */
"ACTIVITY_ALONE":"Actividade",
"BLOG_ALONE":"Blogue",
"IDEATIONBLOG_ALONE":"Blogue de ideias",
"ENTRY_ALONE":"Entrada",
"EVENT_ALONE":"Evento",
"FORUM_ALONE":"Fórum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Comunidade",
"XCOMMUNITIES_ALONE":"{0} Comunidades",
"SHAREDCOMMUNITIES":"Partilhado com estas comunidades",
"INACOMMUNITY":"numa comunidade",
"LASTUPDATED":"Última actualização do índice de procura:",
"NODESCRIPTION":"Não existe qualquer descrição ou resumo para este resultado.",
"ATTACHMENT":"Anexo:",
"ACTIVITY":"Actividade:",
"ACTIVITYBOOKMARK":"Marcador da actividade:",
"ACTIVITYCOMMENT":"Comentário da actividade:",
"ACTIVITYENTRY":"Entrada da actividade:",
"ACTIVITYSECTION":"Secção da actividade:",
"ACTIVITYTODO":"Tarefa da actividade:",
"BLOG":"Blogue:",
"BLOGENTRY":"Entrada do blogue:",
"BLOGCOMMENT":"Comentário do blogue:",
"BOOKMARK":"Marcador:",
"CALENDAREVENT":"Evento:",
"CATEGORY":"Categoria:",
"COMMENT":"Comentário:",
"COMMUNITY":"Comunidade:",
"ENTRY":"Entrada:",
"EVENTDATEON":"A: {0}",
"EVENTISALLDAY":"Evento para todo o dia",
"EVENTREPEATS":"Repete-se",
"FEED":"Feed:",
"FILE":"Ficheiro:",
"FORUM":"Fórum:",
"FORUMCATEGORY":"Categoria do fórum:",
"FORUMTOPIC":"Tópico do fórum:",
"IDEA":"Ideia:",
"IDEACOMMENT":"Comentário da ideia:",
"IDEATIONBLOG":"Blogue de ideias:",
"PAGE":"Página:",
"PROFILE":"Perfil:",
"SECTION":"Secção:",
"STATUSUPDATE":"Actualização do estado",
"STATUSUPDATE_PREFIX":"Actualização de estado:",
"TOPIC":"Tópico:",
"TOPIC_WITH_ATTACHMENT":"Tópico",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Página do wiki:",
"WIKIFILE":"Anexo do wiki:",
"SEARCH":"Procura:",
"TODO":"Tarefa:",
"ALLRESULTS":"Todos os resultados",
"PUBLICCONTENT":"Conteúdo público",
"MYCONTENT":"O meu conteúdo",
"RESULTNOTFOUND":"Não encontrou o que procurava?",
"TEMPDIFFICULTIES":"Nota: Devido a dificuldades de indexação temporárias, a procura não incluiu {0} que foram alterados nos últimos {1} dia(s).",
"TRYLATER":"Tente novamente mais tarde.",
"MULTIPLETEMPDIFFICULTIES":"Nota: Devido a dificuldades de indexação temporárias, a procura não incluiu {0} alterado(s) recentemente",
"YOUAREAUTHOR":"É um autor",
"YOUARECONTRIBUTOR":"É um contribuinte",
"YOUAREOWNER":"É um proprietário",
"YOUAREMEMBER":"É um membro",
/* Profiles */
"MYNETWORK":"A minha rede",
"ALLPEOPLE":"Todas as pessoas",
"EXCLUDEINACTIVE":"Excluir pessoas inactivas",
"PHONE":"Número de telefone:",
"EMAIL":"Endereço de correio electrónico:",
/* Communities */
"ALLCOMMUNITIES":"Todas as comunidades",
"PUBLICCOMMUNITIES":"Comunidades públicas",
"MYCOMMUNITIES":"As minhas comunidades",
"EVERYTHINGCOMMUNITIES":"Tudo das comunidades",
"COMMUNITIESONLY":"Comunidades",
"COMMUNITIESCONTENT":"Conteúdo das comunidades",
/* Activities */
"ALLACTIVITIES":"Todas as actividades",
"PUBLICACTIVITIES":"Actividades públicas",
"MYACTIVITIES":"As minhas actividades",
"EVERYTHINGACTIVITIES":"Tudo das actividades",
"ACTIVITIESONLY":"Actividades",
"SECTIONSACTIVITIES": "Secções das actividades",
"ENTRIESACTIVITIES":"Entradas das actividades",
"TODOSACTIVITIES":"Tarefas das actividades",
"BOOKMARKSACTIVITIES":"Marcadores das actividades",
"FILESACTIVITIES":"Anexos das actividades",
"ALLTYPESACTIVITIES":"Todos os tipos de actividades",
"COMMUNITYACTIVITIES":"Actividades das comunidades",
"STANDALONEACTIVITIES":"Actividades autónomas",
/* Forums */
"ALLFORUMS":"Todos os fóruns",
"PUBLICFORUMS":"Fóruns públicos",
"MYFORUMS":"Os meus fóruns",
"EVERYTHINGFORUMS":"Tudo dos fóruns",
"FORUMSONLY":"Fóruns",
"TOPICSFORUMS":"Tópicos de fórum",
"FORUMCATEGORIES": "Categorias dos fóruns",
"FILESFORUMS":"Anexos dos fóruns",
"ALLTYPESFORUMS":"Todos os tipos de fóruns",
"COMMUNITYFORUMS":"Fóruns das comunidades",
"STANDALONEFORUMS":"Fóruns autónomos",
/* Blogs */
"ALLBLOGS":"Todos os blogues",
"PUBLICBLOGS":"Blogues públicos",
"MYBLOGS":"Os meus blogues",
"EVERYTHINGBLOGS":"Tudo dos blogues",
"BLOGSONLY":"Blogues",
"ENTRIESBLOGS":"Entradas de blogue",
"FILESBLOGS":"Anexos dos blogues",
"EVERYTHINGIDEATIONBLOGS":"Tudo dos blogues de ideias",
"BLOGSIDEATIONBLOGS":"Blogues de ideias",
"BLOGSIDEAS":"Ideias",
"ALLTYPESBLOGS":"Todos os tipos de blogues",
"COMMUNITYBLOGS":"Blogues das comunidades",
"COMMUNITYIDEATIONBLOGS":"Blogue de ideias das comunidades",
"STANDALONEBLOGS":"Blogues autónomos",
/* Bookmarks */
"ALLBOOKMARKS":"Todos os marcadores",
"PUBLICBOOKMARKS":"Marcadores públicos",
"MYBOOKMARKS":"Os meus marcadores",
"ALLTYPESBOOKMARKS":"Todos os tipos de marcadores",
"COMMUNITYBOOKMARKS":"Marcadores das comunidades",
"STANDALONEBOOKMARKS":"Marcadores autónomos",
/* Files */
"ALLFILES":"Todos os ficheiros",
"PUBLICFILES":"Ficheiros públicos",
"MYFILES":"Os meus ficheiros",
"ALLTYPESFILES":"Todos os tipos de ficheiros",
"COMMUNITYFILES":"Ficheiros das comunidades",
"STANDALONEFILES":"Ficheiros autónomos",
"NUMDOWNLOADS":"{0} transferências",
/* Wikis */
"ALLWIKIS":"Todos os wikis",
"PUBLICWIKIS":"Wikis públicos",
"MYWIKIS":"Os meus Wikis",
"EVERYTHINGWIKIS":"Tudo dos wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Páginas do wiki",
"FILESWIKIS":"Anexos dos Wikis",
"ALLTYPESWIKIS":"Todos os tipos de wikis",
"COMMUNITYWIKIS":"Wikis das comunidades",
"STANDALONEWIKIS":"Wikis autónomos",
/* Status Updates */
"ALLSTATUSUPDATES":"Todas as actualizações de estado",
"PUBLICSTATUSUPDATES":"Actualizações de estado públicas",
"MYSTATUSUPDATES":"As minhas actualizações de estado",
"ALLTYPESSTATUSUPDATES":"Todos os tipos de actualizações de estado",
"COMMUNITYSTATUSUPDATES":"Actualizações de estado das Comunidades",
"STANDALONESTATUSUPDATES":"Actualizações de estado dos Perfis",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Foram atribuídos marcadores a este URL por vários utilizadores",
"BOOKMARKEDCOMMUNITY":"Foram atribuídos marcadores a esta comunidade por vários utilizadores",
"BOOKMARKEDPROFILE":"Foram atribuídos marcadores a este perfil por vários utilizadores",
"BOOKMARKEDBLOG":"Foram atribuídos marcadores a este blogue por vários utilizadores",
"COMMUNITYBLOG":"Trata-se de um blogue numa comunidade",
"BOOKMARKEDACTIVITY":"Foram atribuídos marcadores a esta actividade por vários utilizadores",
"COMMUNITYACTIVITY":"Trata-se de uma actividade numa comunidade",
"BOOKMARKEDFILE":"Foram atribuídos marcadores a este ficheiro por vários utilizadores",
"COMMUNITYFILE":"Trata-se de um ficheiro numa comunidade",
"BOOKMARKED":"Foram atribuídos marcadores a este wiki por vários utilizadores",
"COMMUNITYWIKI":"Trata-se de um wiki numa comunidade",
"BOOKMARKEDFORUM":"Foram atribuídos marcadores a este fórum por vários utilizadores",
"COMMUNITYFORUM":"Trata-se de um fórum numa comunidade",
"ALLTAGANDTTILE":"Para visualizar todos os títulos e etiquetas deste URL, faça clique neste botão",
"TAGS_ARE_FROM":"Este resultado da procura poderá incluir etiquetas de:",
"BOOKMARKS_TITLE":"Marcadores",
"COMMUNITIES_TITLE":"Comunidades",
"ACTIVITIES_TITLE":"Actividades",
"HELP":"Ajuda",
"MORESTATUSUPDATES":"Ver mais correspondências de actualizações de estado",
"TITLE_PREFIX":"título:",
"LATEST_MESSAGE":"Última mensagem",
"LATEST_STATUS_UPDATE":"Última actualização de estado",
"LATEST_COMMUNITY_STATUS_UPDATE":"Última actualização de estado da comunidade",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Última actualização de estado das comunidades",
"SEARCH_RESULTS":"Resultados da procura em Todo o conteúdo",
"ACTIVITIES_SEARCH_RESULTS":"Resultados da procura das Actividades",
"BLOGS_SEARCH_RESULTS":"Resultados da procura dos Blogues",
"BOOKMARKS_SEARCH_RESULTS":"Resultados da procura dos Marcadores",
"COMMUNITIES_SEARCH_RESULTS":"Resultados da procura das Comunidades",
"FILES_SEARCH_RESULTS":"Resultados da procura dos Ficheiros",
"FORUMS_SEARCH_RESULTS":"Resultados da procura dos Fóruns",
"PROFILES_SEARCH_RESULTS":"Resultados da procura dos Perfis",
"DIRECTORY_SEARCH_RESULTS":"Resultados da procura do Directório de ${orgName}",
"WIKIS_SEARCH_RESULTS":"Resultados da procura dos Wikis",
"STATUS_UPDATES_SEARCH_RESULTS":"Resultados da procura de actualizações do estado",
"VIEW_ALL":"{span}Ver tudo{/span} ({0})",
"MATCHING_ONE_OF":"Correspondente a um de:",
"MATCHING_ALL_OF":"Correspondente a todos de:",
"MATCHING":"Correspondente a:",
"MATCHING_DOC_TYPE":"Tipo de documento correspondente:",
"BOOKMARK_HELP":"Ajuda dos Marcadores",
"CLOSE_BOOKMARK_HELP":"Fechar ajuda dos Marcadores",
"DOCUMENT_TYPE_PREFIX":"Tipo de documento:",
"FILE_PREVIEW_ONLY":"(Apenas modo de pré-visualização)"
})

