/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Il titolo è obbligatorio.",
	nourl: "L'URL è obbligatorio.",
	fileSchema: "Se si desidera aggiungere un collegamento a un file locale o remoto, questo dovrà avere uno dei seguenti formati: file://percorso_remoto o file:///percorso_locale.",
	invalidUrl: "Questo non è un URL di comunità valido.",
	invalidTagChar: "L'elenco dei tag immesso contiene il carattere non valido "&". Rimuovere questo carattere dall'elenco dei tag.",
	txtHelp: "Guida",
	txtHelpTags: "Guida dei tag",
	txtHelpTagsClose: "Chiusura guida dei tag",
	tagsall: "Tutti",
	tagsyours: "Personali",
	tagsrecent: "Recente: ",
	tagspopular: "Popolare: ",
	tagsrecommended: "Consigliato: ",
	nothingselected: "È necessaria una selezione della comunità.",
	nothingselected_activity: "È necessaria una selezione dell'attività.",
	nothingselected_blogs: "È necessaria una selezione del blog.",
	nothingselected_all: "Non è stato selezionato alcun servizio o voce; il segnalibro non verrà salvato.",
	nothingFeedselected: "Non è stato selezionato alcun servizio o voce; il feed non verrà salvato.",
	alertDialogTitle: "Messaggio",
	alertDialogOK: "OK",
	expand: "Fare clic per espandere questa sezione",
	collapse: "Fare clic per comprimere questa sezione",
	discussThis: "Discuti su",
	by: "di:",
	posted: "Pubblicato:",
	attachments: "Allegati",
	communityForum: "Forum della comunità",
	notCommunityPage: "La pagina Web corrente non è una pagina Web della comunità valida. È possibile immettere manualmente il titolo della comunità, il collegamento e una descrizione per creare una comunità correlata.",
	privateCommunityNotice: "Questa comunità è limitata. È visibile solo ai membri della comunità.",
	forumNameHint : "Immettere un nome forum",
	formDescriptionHint:"Descrivere il motivo per cui questa comunità correlata dovrebbe interessare alla propria comunità.",
	information : "Informazioni",
	error : "Errore",
	success : "Riuscito",
	warning : "Avvertenza",
	informationColon : "Informazioni:",
	successColon : "Riuscito:",
	warningColon : "Avviso:",
	errorColon : "Errore:",
	feedAlreadyExist : "Il feed esiste già nella comunità.",
	bookmarkAlreadyExist : "Il segnalibro esiste già nella comunità.",
	mentionAuthWarning:"Le seguenti persone citate non potranno visualizzare il messaggio in quanto non sono membri della comunità:",
	mentionAuthForumWarning:"Le seguenti persone citate non potranno visualizzare il messaggio in quanto non possono accedere a questo forum:",
	exceedDescLength: "La descrizione immessa è troppo lunga.",
	communities_checked:"${0} comunità selezionate",
	activities_checked:"${0} attività selezionate",
	blogs_checked:"${0} blog selezionati"
})
