/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtrovat podle:",
		"SHOW":"Zobrazit:",
		"ACL_FILTER_LABEL":"Filtrovat podle viditelnosti",
		"PARENT_FILTER_LABEL":"Filtrovat podle kontejneru",
		"TYPE_FILTER_LABEL":"Filtrovat podle typu",
		"PAGING_TOP":"Primární stránkování",
		"PAGING_BOTTOM":"Sekundární stránkování",
		"PREVIOUS":"Předchozí",
		"NEXT":"Další",
		"PAGE":"Stránka {0} z {1}",
		"PAGE_COLON":"Stránka:",
		"RESULTS":"{span}{0} až {1}{/span} z {2}",
		"ITEMS":"{0} položek",
		/* Application names */
		"ACTIVITIES":"Aktivity",
		"BLOGS":"Blogy",
		"CALENDAR":"Kalendář",
		"COMMUNITIES":"Komunity",
		"BOOKMARKS":"Záložky",
		"DOGEAR":"Záložky",
		"EVENTS":"Události",
		"FILES":"Soubory",
		"FORUMS":"Fóra",
		"PROFILES":"Profily",
		"WIKI":"Wikiweby",
		"WIKIS":"Wikiweby",
		"FEEDS":"Kanály",
		"STATUS_UPDATES":"Aktualizace stavu",
		"ONECOMMENT":"1 komentář",
		"COMMENTS":"komentáře ({0})",
		"ONEPERSON":"1 osoba",
		"PEOPLE":"{0} osob",
		"TAGS":"Značky:",
		"TAGSMORE":"a další ({0})",
		"NORESULTSMESSAGE":"Pro příslušné hledání nebyly obdrženy žádné výsledky.",
		"JAN":"leden",
		"FEB":"únor",
		"MAR":"březen",
		"APR":"duben",
		"MAY":"květen",
		"JUN":"červen",
		"JUL":"červenec",
		"AUG":"srpen",
		"SEP":"září",
		"OCT":"říjen",
		"NOV":"listopad",
		"DEC":"prosinec",
		"NO_CONTACT":"Hledání nebylo provedeno, protože nebylo možné kontaktovat server.",
		"SERVER_ERROR":"Hledání nebylo provedeno vzhledem k chybě serveru.",
		"SORT_BY":"Řadit podle:",
		"SORT_RELEVANCE":"Důležitost",
		"SORT_DATE":"Datum",
		"SORT_LAST_UPDATED":"Poslední aktualizace",
		"SORT_DUE_DATE":"Termín",
		"SORT_VISITS":"Návštěvy",
		"SORT_COMMENTS":"Komentáře",
		"SORT_RECOMMENDATION":"Hodnocení Oblíbené",
		"SORT_POPULARITY":"Popularita",
		"SORT_FIRSTNAME":"Křestní jméno",
		"SORT_LASTNAME":"Příjmení",
		"SORT_DOWNLOADS":"Stažení",
		"SORT_TYPE":"Typ",
		"SORT_SIZE":"Velikost",
		"SORT_TITLE":"Nadpis",
		"PRIVATE":"Soukromé",
		"MODERATED":"Moderované",
		"COMMUNITY_ACTIVITY":"Aktivita komunity",
		"COMMUNITY_BLOG":"Blog komunity",
		"COMMUNITY_FILE":"Soubor komunity",
		"COMMUNITY_FORUM":"Fórum komunity",
		"COMMUNITY_WIKI":"Wikiweb komunity",
		"COMMUNITY_FEED":"Informační kanál komunity",
		"COMMUNITY_BOOKMARK":"Záložka komunity",
		"NO_TAG":"Dosud žádné značky",
		"NO_DATE":"Dosud žádná data",
		"NO_PEOPLE":"Dosud žádní lidé",
		"REMOVE_FILTER_LABEL":"Klepnutím odebrat",
		"REMOVE_FILTER_TITLE":"Odebrat",
		"REMOVE_FILTER_TOOLTIP":"Odebrat tento filtr",
		"COMMENT_ON":"Komentář k položce:",
		"EXPAND_COLLAPSE":"Klepnutím lze položku rozbalit či sbalit.",
		"EXPAND":"Rozbalit",
		"COLLAPSE":"Sbalit",
		"EXPAND_MONTHS_FILTER":"Rozbalit filtr měsíců roku {0}",
		"SORT_RELEVANCE_LABEL":"Klepnutím provedete řazení podle důležitosti.",
		"SORT_DATE_LABEL":"Klepnutím provedete řazení podle data.",
		"SORT_UPDATED_LABEL":"Klepnutím provedete řazení podle času poslední aktualizace.",
		"SORT_DUE_LABEL":"Klepnutím provedete řazení podle termínu.",
		"SORT_VISITS_LABEL":"Klepnutím provedete řazení podle počtu návštěv.",
		"SORT_COMMENTS_LABEL":"Klepnutím provedete řazení podle počtu komentářů.",
		"SORT_RECOMMENDATIONS_LABEL":"Klepnutím provedete řazení podle počtu hodnocení Oblíbené.",
		"SORT_POPULARITY_LABEL":"Klepnutím provedete řazení podle popularity.",
		"SORT_FIRST_NAME_LABEL":"Klepnutím provedete řazení podle křestního jména.",
		"SORT_LAST_NAME_LABEL":"Klepnutím provedete řazení podle příjmení.",
		"RATING":"Hodnocení Oblíbené",
		"GRADUATED":"Se zvýšeným hodnocením",
		"ONEVOTE":"1 hlas",
		"VOTES":"{0} hlasů",
		"BOOKMARK_THIS_RESULT":"Založit",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (neaktivní)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} založených osob",
		/* eg from an Activity */
		"FROMANACTIVITY":"z aktivity",
		"FROMABLOG":"z blogu",
		"FROMANIDEATIONBLOG":"Z blogu nápadů",
		"FROMANEVENT":"z události",
		"FROMAFORUM":"z fóra",
		"FROMAWIKI":"z wikiwebu",
		"FROMACOMMUNITY":"z komunity",
		"FROMXCOMMUNITIES":"z {0} komunit",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Aktivita",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog nápadů",
		"ENTRY_ALONE":"Položka",
		"EVENT_ALONE":"Událost",
		"FORUM_ALONE":"Fórum",
		"WIKI_ALONE":"Wikiweb",
		"COMMUNITY_ALONE":"Komunita",
		"XCOMMUNITIES_ALONE":"{0} komunit",
		"SHAREDCOMMUNITIES":"Sdíleno s těmito komunitami",
		"INACOMMUNITY":"v rámci komunity",
		"LASTUPDATED":"Poslední aktualizace vyhledávacího indexu:",
		"NODESCRIPTION":"Pro tento výsledek není k dispozici žádný popis ani souhrn.",
		"ATTACHMENT":"Příloha:",
		"ACTIVITY":"Aktivita:",
		"ACTIVITYBOOKMARK":"Záložka aktivity:",
		"ACTIVITYCOMMENT":"Komentář aktivity:",
		"ACTIVITYENTRY":"Položka aktivity:",
		"ACTIVITYSECTION":"Sekce aktivity:",
		"ACTIVITYTODO":"Úkol aktivity:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Položka blogu:",
		"BLOGCOMMENT":"Komentář k blogu:",
		"BOOKMARK":"Záložka:",
		"CALENDAREVENT":"Událost:",
		"CATEGORY":"Kategorie:",
		"COMMENT":"Komentář:",
		"COMMUNITY":"Komunita:",
		"ENTRY":"Položka:",
		"EVENTDATEON":"Dne: {0}",
		"EVENTISALLDAY":"Celodenní událost",
		"EVENTREPEATS":"Opakování",
		"FEED":"Kanál:",
		"FILE":"Soubor:",
		"FORUM":"Fórum:",
		"FORUMCATEGORY":"Kategorie fóra:",
		"FORUMTOPIC":"Téma fóra:",
		"IDEA":"Nápad:",
		"IDEACOMMENT":"Komentář k nápadu:",
		"IDEATIONBLOG":"Blog nápadů:",
		"PAGE":"Stránka:",
		"PROFILE":"Profil:",
		"SECTION":"Sekce:",
		"STATUSUPDATE":"Aktualizace stavu",
		"STATUSUPDATE_PREFIX":"Aktualizace stavu:",
		"TOPIC":"Téma:",
		"TOPIC_WITH_ATTACHMENT":"Téma",
		"WIKITYPE":"Wikiweb:",
		"WIKIPAGE":"Stránka wikiwebu:",
		"WIKIFILE":"Příloha wikiwebu:",
		"SEARCH":"Hledání:",
		"TODO":"Úkol:",
		"ALLRESULTS":"Všechny výsledky",
		"PUBLICCONTENT":"Veřejný obsah",
		"MYCONTENT":"Můj obsah",
		"RESULTNOTFOUND":"Nenašli jste to, co hledáte?",
		"TEMPDIFFICULTIES":"Poznámka: Kvůli dočasným potížím s indexováním vaše hledání nezahrnuje {0} změněné za posledních {1} dní.",
		"TRYLATER":"Zopakujte akci později.",
		"MULTIPLETEMPDIFFICULTIES":"Poznámka: Kvůli dočasným potížím s indexováním vaše hledání nezahrnuje nedávno změněné {0}.",
		"YOUAREAUTHOR":"Vy jste autorem",
		"YOUARECONTRIBUTOR":"Vy jste přispěvatelem",
		"YOUAREOWNER":"Vy jste vlastníkem",
		"YOUAREMEMBER":"Vy jste členem",
		/* Profiles */
		"MYNETWORK":"Má síť",
		"ALLPEOPLE":"Všichni lidé",
		"EXCLUDEINACTIVE":"Vyloučit neaktivní uživatele",
		"PHONE":"Telefon:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Všechny komunity",
		"PUBLICCOMMUNITIES":"Veřejné komunity",
		"MYCOMMUNITIES":"Mé komunity",
		"EVERYTHINGCOMMUNITIES":"Vše ze služby Komunity",
		"COMMUNITIESONLY":"Komunity",
		"COMMUNITIESCONTENT":"Obsah ze služby Komunity",
		/* Activities */
		"ALLACTIVITIES":"Všechny aktivity",
		"PUBLICACTIVITIES":"Veřejné aktivity",
		"MYACTIVITIES":"Mé aktivity",
		"EVERYTHINGACTIVITIES":"Vše ze služby Aktivity",
		"ACTIVITIESONLY":"Aktivity",
		"SECTIONSACTIVITIES": "Sekce ze služby Aktivity",
		"ENTRIESACTIVITIES":"Položky ze služby Aktivity",
		"TODOSACTIVITIES":"Úkoly ze služby Aktivity",
		"BOOKMARKSACTIVITIES":"Záložky ze služby Aktivity",
		"FILESACTIVITIES":"Přílohy ze služby Aktivity",
		"ALLTYPESACTIVITIES":"Všechny typy aktivit",
		"COMMUNITYACTIVITIES":"Aktivity ze služby Komunity",
		"STANDALONEACTIVITIES":"Samostatné aktivity",
		/* Forums */
		"ALLFORUMS":"Všechna fóra",
		"PUBLICFORUMS":"Veřejná fóra",
		"MYFORUMS":"Má fóra",
		"EVERYTHINGFORUMS":"Vše ze služby Fóra",
		"FORUMSONLY":"Fóra",
		"TOPICSFORUMS":"Témata fóra",
		"FORUMCATEGORIES": "Kategorie fóra",
		"FILESFORUMS":"Přílohy ze služby Fóra",
		"ALLTYPESFORUMS":"Všechny typy fór",
		"COMMUNITYFORUMS":"Fóra ze služby Komunity",
		"STANDALONEFORUMS":"Samostatná fóra",
		/* Blogs */
		"ALLBLOGS":"Všechny blogy",
		"PUBLICBLOGS":"Veřejné blogy",
		"MYBLOGS":"Mé blogy",
		"EVERYTHINGBLOGS":"Vše ze služby Blogy",
		"BLOGSONLY":"Blogy",
		"ENTRIESBLOGS":"Položky blogu",
		"FILESBLOGS":"Přílohy ze služby Blogy",
		"EVERYTHINGIDEATIONBLOGS":"Vše z blogů Ideation",
		"BLOGSIDEATIONBLOGS":"Blogy ideation",
		"BLOGSIDEAS":"Nápady",
		"ALLTYPESBLOGS":"Všechny typy blogů",
		"COMMUNITYBLOGS":"Blogy ze služby Komunity",
		"COMMUNITYIDEATIONBLOGS":"Blogy Ideation ze služby Komunity",
		"STANDALONEBLOGS":"Samostatné blogy",
		/* Bookmarks */
		"ALLBOOKMARKS":"Všechny záložky",
		"PUBLICBOOKMARKS":"Veřejné záložky",
		"MYBOOKMARKS":"Mé záložky",
		"ALLTYPESBOOKMARKS":"Všechny typy záložek",
		"COMMUNITYBOOKMARKS":"Záložky ze služby Komunity",
		"STANDALONEBOOKMARKS":"Samostatné záložky",
		/* Files */
		"ALLFILES":"Všechny soubory",
		"PUBLICFILES":"Veřejné soubory",
		"MYFILES":"Mé soubory",
		"ALLTYPESFILES":"Všechny typy souborů",
		"COMMUNITYFILES":"Soubory ze služby Komunity",
		"STANDALONEFILES":"Samostatné soubory",
		"NUMDOWNLOADS":"{0} stažení",
		/* Wikis */
		"ALLWIKIS":"Všechny wikiweby",
		"PUBLICWIKIS":"Veřejné wikiweby",
		"MYWIKIS":"Mé wikiweby",
		"EVERYTHINGWIKIS":"Vše ze služby Wikiweby",
		"WIKISONLY":"Wikiweby",
		"PAGESWIKIS":"Stránky wikiwebu",
		"FILESWIKIS":"Přílohy ze služby Wikiweby",
		"ALLTYPESWIKIS":"Všechny typy wikiwebů",
		"COMMUNITYWIKIS":"Wikiweby ze služby Komunity",
		"STANDALONEWIKIS":"Samostatné wikiweby",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Všechny aktualizace stavu",
		"PUBLICSTATUSUPDATES":"Veřejné aktualizace stavu",
		"MYSTATUSUPDATES":"Mé aktualizace stavu",
		"ALLTYPESSTATUSUPDATES":"Všechny typy aktualizací stavu",
		"COMMUNITYSTATUSUPDATES":"Aktualizace stavu z komunit",
		"STANDALONESTATUSUPDATES":"Aktualizace stavu z profilů",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Tato adresa URL byla přidána mezi záložky více uživateli.",
		"BOOKMARKEDCOMMUNITY":"Tato komunita byla přidána mezi záložky více uživateli.",
		"BOOKMARKEDPROFILE":"Tento profil byl přidán mezi záložky více uživateli.",
		"BOOKMARKEDBLOG":"Tento blog byl přidán mezi záložky více uživateli.",
		"COMMUNITYBLOG":"Toto je blog v rámci komunity.",
		"BOOKMARKEDACTIVITY":"Tuto aktivitu si přidalo mezi záložky více uživatelů.",
		"COMMUNITYACTIVITY":"Toto je aktivita v rámci komunity.",
		"BOOKMARKEDFILE":"Tento soubor byl přidán mezi záložky více uživateli.",
		"COMMUNITYFILE":"Toto je soubor v rámci komunity.",
		"BOOKMARKED":"Tento wikiweb byl přidán mezi záložky více uživateli.",
		"COMMUNITYWIKI":"Toto je wikiweb v rámci komunity.",
		"BOOKMARKEDFORUM":"Toto fórum bylo přidáno mezi záložky více uživateli.",
		"COMMUNITYFORUM":"Toto je fórum v rámci komunity.",
		"ALLTAGANDTTILE":"Chcete-li zobrazit všechny názvy a značky pro tuto adresu URL, klepněte na toto tlačítko.",
		"TAGS_ARE_FROM":"Tyto výsledky vyhledávání mohou obsahovat značky z následujících služeb:",
		"BOOKMARKS_TITLE":"Záložky",
		"COMMUNITIES_TITLE":"Komunity",
		"ACTIVITIES_TITLE":"Aktivity",
		"HELP":"Nápověda",
		"MORESTATUSUPDATES":"Zobrazit další shody aktualizace stavu",
		"TITLE_PREFIX":"Název:",
		"LATEST_MESSAGE":"Poslední zpráva",
		"LATEST_STATUS_UPDATE":"Poslední aktualizace stavu",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Poslední aktualizace stavu komunity",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Poslední aktualizace stavu komunit",
		"SEARCH_RESULTS":"Výsledky hledání v celém obsahu",
		"ACTIVITIES_SEARCH_RESULTS":"Výsledky hledání v rámci služby Aktivity",
		"BLOGS_SEARCH_RESULTS":"Výsledky hledání v rámci služby Blogy",
		"BOOKMARKS_SEARCH_RESULTS":"Výsledky hledání v rámci služby Záložky",
		"COMMUNITIES_SEARCH_RESULTS":"Výsledky hledání v rámci služby Komunity",
		"FILES_SEARCH_RESULTS":"Výsledky hledání v rámci služby Soubory",
		"FORUMS_SEARCH_RESULTS":"Výsledky hledání v rámci služby Fóra",
		"PROFILES_SEARCH_RESULTS":"Výsledky hledání v rámci služby Profily",
		"DIRECTORY_SEARCH_RESULTS":"Výsledky hledání v adresáři organizace ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Výsledky hledání v rámci služby Wikiweby",
		"STATUS_UPDATES_SEARCH_RESULTS":"Výsledky hledání v rámci aktualizací stavu",
		"VIEW_ALL":"{span}Zobrazit vše{/span} ({0})",
		"MATCHING_ONE_OF":"Vyhovující některé z podmínek:",
		"MATCHING_ALL_OF":"Vyhovující všem podmínkám:",
		"MATCHING":"Odpovídající:",
		"MATCHING_DOC_TYPE":"Vyhovující typ dokumentu:",
		"BOOKMARK_HELP":"Nápověda ke službě Záložky",
		"CLOSE_BOOKMARK_HELP":"Zavřít nápovědu ke službě Záložky",
		"DOCUMENT_TYPE_PREFIX":"Typ dokumentu:",
		"LAST_PAGE_MESSAGE": "Uf, výsledků hledání je opravdu hodně. Zkuste hledání zúžit přidáním dalších hledaných výrazů.",
		"LAST_PAGE_SUBMESSAGE": "Zobrazeno je prvních {resultNumber} relevantních výsledků."
});

