/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Un titre est obligatoire.",
	nourl: "Une Url est obligatoire.",
	fileSchema: "Si vous voulez ajouter un lien de fichier local ou distant, il doit être conforme à l'un des formats suivants : file://chemin_path ou file:///chemin_local.",
	invalidUrl: "Il ne s'agit pas d'une URL de communauté valide.",
	invalidTagChar: "La liste des étiquettes que vous avez entrée contient le caractère non valide '&'. Veuillez retirer ce caractère de la liste des étiquettes.",
	txtHelp: "Aide",
	txtHelpTags: "Aide sur les étiquettes",
	txtHelpTagsClose: "Fermer l'aide relative aux étiquettes",
	tagsall: "Tous",
	tagsyours: "Les vôtres",
	tagsrecent: "Récentes : ",
	tagspopular: "Populaires : ",
	tagsrecommended: "Recommandées : ",
	nothingselected: "Une sélection de communauté est requise.",
	nothingselected_activity: "Une sélection d'activité est requise.",
	nothingselected_blogs: "Une sélection de blogue est requise.",
	nothingselected_all: "Aucun service ou aucune entrée sélectionnée ; le signet ne sera pas enregistré.",
	nothingFeedselected: "Aucun service ou aucune entrée sélectionnée ; le flux ne sera pas enregistré.",
	alertDialogTitle: "Message",
	alertDialogOK: "OK",
	expand: "Cliquez pour développer cette section",
	collapse: "Cliquez pour réduire cette section",
	discussThis: "Discussion",
	by: "par :",
	posted: "Posté :",
	attachments: "Pièces jointes",
	communityForum: "Forum de communauté",
	notCommunityPage: "La page Web en cours n'est pas une page Web de communauté valide. Vous pouvez entrer manuellement le titre de la communauté, le lien et la description pour créer une communauté associée.",
	privateCommunityNotice: "Cette communauté est à accès restreint. Elle est visible uniquement pour les membres de la communauté.",
	forumNameHint : "Entrez un nom de forum",
	formDescriptionHint:"Décrivez pourquoi cette communauté associée est susceptible d'intéresser votre communauté.",
	information : "Informations",
	error : "Erreur",
	success : "Réussite",
	warning : "Avertissement",
	informationColon : "Informations :",
	successColon : "Réussite",
	warningColon : "Avertissement :",
	errorColon : "Erreur :",
	feedAlreadyExist : "Ce flux existe déjà dans la communauté.",
	bookmarkAlreadyExist : "Ce signet existe déjà dans la communauté.",
	mentionAuthWarning:"Les personnes mentionnées suivantes ne pourront pas voir le message car elles ne sont pas membres de la communauté :",
	mentionAuthForumWarning:"Les personnes mentionnées suivantes ne pourront pas voir le message car elles n'ont pas accès à ce forum :",
	exceedDescLength: "La description que vous avez entrée est trop longue.",
	communities_checked:"${0} communautés sélectionnées",
	activities_checked:"${0} activités sélectionnées",
	blogs_checked:"${0} blogues sélectionnés"
})
