/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filter menurut:",
		"SHOW":"Tampilkan:",
		"ACL_FILTER_LABEL":"Filter menurut visibilitas",
		"PARENT_FILTER_LABEL":"Filter menurut wadah",
		"TYPE_FILTER_LABEL":"Filter menurut tipe",
		"PAGING_TOP":"Penentuan halaman primer",
		"PAGING_BOTTOM":"Penentuan halaman sekunder",
		"PREVIOUS":"Sebelumnya",
		"NEXT":"Berikutnya",
		"PAGE":"Halaman {0} dari {1}",
		"PAGE_COLON":"Halaman:",
		"RESULTS":"{span}{0}-{1}{/span} dari {2}",
		"ITEMS":"{0} item",
		/* Application names */
		"ACTIVITIES":"Aktivitas",
		"BLOGS":"Blog",
		"CALENDAR":"Kalender",
		"COMMUNITIES":"Komunitas",
		"BOOKMARKS":"Markah",
		"DOGEAR":"Markah",
		"EVENTS":"Peristiwa",
		"FILES":"File",
		"FORUMS":"Forum",
		"PROFILES":"Profil",
		"WIKI":"Wiki",
		"WIKIS":"Wiki",
		"FEEDS":"Logo umpan",
		"STATUS_UPDATES":"Pembaharuan Status",
		"ONECOMMENT":"1 komentar",
		"COMMENTS":"{0} Komentar",
		"ONEPERSON":"1 Orang",
		"PEOPLE":"{0} Orang",
		"TAGS":"Tanda:",
		"TAGSMORE":"dan {0} lebih",
		"NORESULTSMESSAGE":"Tidak ada hasil yang ditemukan untuk pencarian tersebut",
		"JAN":"Januari",
		"FEB":"Februari",
		"MAR":"Maret",
		"APR":"April",
		"MAY":"Mei",
		"JUN":"Juni",
		"JUL":"Juli",
		"AUG":"Agustus",
		"SEP":"September",
		"OCT":"Oktober",
		"NOV":"November",
		"DEC":"Desember",
		"NO_CONTACT":"Pencarian tidak dapat dilakukan karena server tidak dapat dihubungi.",
		"SERVER_ERROR":"Pencarian tidak dilakukan karena terjadi kesalahan server",
		"SORT_BY":"Urutkan berdasarkan:",
		"SORT_RELEVANCE":"Relevansi",
		"SORT_DATE":"Tanggal",
		"SORT_LAST_UPDATED":"Diperbarui terakhir",
		"SORT_DUE_DATE":"Tanggal Tenggat",
		"SORT_VISITS":"Kunjungan",
		"SORT_COMMENTS":"Komentar",
		"SORT_RECOMMENDATION":"Suka",
		"SORT_POPULARITY":"Popularitas",
		"SORT_FIRSTNAME":"Nama Depan",
		"SORT_LASTNAME":"Nama Belakang",
		"SORT_DOWNLOADS":"Unduhan",
		"SORT_TYPE":"Tipe",
		"SORT_SIZE":"Ukuran",
		"SORT_TITLE":"Judul",
		"PRIVATE":"Pribadi",
		"MODERATED":"Moderat",
		"COMMUNITY_ACTIVITY":"Aktivitas Komunitas",
		"COMMUNITY_BLOG":"Blog Komunitas",
		"COMMUNITY_FILE":"File Komunitas",
		"COMMUNITY_FORUM":"Forum Komunitas",
		"COMMUNITY_WIKI":"Wiki Komunitas",
		"COMMUNITY_FEED":"Feed Komunitas",
		"COMMUNITY_BOOKMARK":"Markah Komunitas",
		"NO_TAG":"Belum ada label",
		"NO_DATE":"Belum ada tanggal",
		"NO_PEOPLE":"Belum ada orang",
		"REMOVE_FILTER_LABEL":"Klik untuk menghapus",
		"REMOVE_FILTER_TITLE":"Hapus",
		"REMOVE_FILTER_TOOLTIP":"Hapus filter ini",
		"COMMENT_ON":"Beri komentar pada:",
		"EXPAND_COLLAPSE":"Klik untuk memperluas / menciutkan",
		"EXPAND":"Perluas",
		"COLLAPSE":"Ciutkan",
		"EXPAND_MONTHS_FILTER":"Perluas filter bulan untuk tahun {0}",
		"SORT_RELEVANCE_LABEL":"Klik untuk mengurutkan menurut relevansi",
		"SORT_DATE_LABEL":"Klik untuk mengurutkan menurut tanggal",
		"SORT_UPDATED_LABEL":"Klik untuk mengurutkan menurut pembaruan terakhir",
		"SORT_DUE_LABEL":"Klik untuk mengurutkan menurut tanggal",
		"SORT_VISITS_LABEL":"Klik untuk mengurutkan menurut jumlah kunjungan",
		"SORT_COMMENTS_LABEL":"Klik untuk mengurutkan menurut jumlah komentar",
		"SORT_RECOMMENDATIONS_LABEL":"Klik untuk mengurutkan menurut jumlah suka",
		"SORT_POPULARITY_LABEL":"Klik untuk mengurutkan menurut popularitas",
		"SORT_FIRST_NAME_LABEL":"Klik untuk mengurutkan menurut nama yang diberikan",
		"SORT_LAST_NAME_LABEL":"Klik untuk mengurutkan menurut nama belakang",
		"RATING":"Suka",
		"GRADUATED":"Lulus",
		"ONEVOTE":"1 voting",
		"VOTES":"{0} voting",
		"BOOKMARK_THIS_RESULT":"Markahi ini",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (tidak aktif)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} orang yang dimarkahi",
		/* eg from an Activity */
		"FROMANACTIVITY":"dari Aktivitas",
		"FROMABLOG":"dari Blog",
		"FROMANIDEATIONBLOG":"dari Blog Ide",
		"FROMANEVENT":"dari Event",
		"FROMAFORUM":"dari Forum",
		"FROMAWIKI":"dari Wiki",
		"FROMACOMMUNITY":"dari Komunitas",
		"FROMXCOMMUNITIES":"dari {0} Komunitas",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Aktivitas",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog Ide",
		"ENTRY_ALONE":"Entri",
		"EVENT_ALONE":"Event",
		"FORUM_ALONE":"Forum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Komunitas",
		"XCOMMUNITIES_ALONE":"{0} Komunitas",
		"SHAREDCOMMUNITIES":"Dibagi dengan komunitas ini",
		"INACOMMUNITY":"dalam Komunitas",
		"LASTUPDATED":"Indeks Pencarian diperbarui terakhir:",
		"NODESCRIPTION":"Tidak ada deskripsi atau ringkasan untuk hasil ini.",
		"ATTACHMENT":"Lampiran:",
		"ACTIVITY":"Aktivitas:",
		"ACTIVITYBOOKMARK":"Markah Aktivitas:",
		"ACTIVITYCOMMENT":"Komentar Aktivitas:",
		"ACTIVITYENTRY":"Entri Aktivitas:",
		"ACTIVITYSECTION":"Bagian Aktivitas:",
		"ACTIVITYTODO":"Tugas Aktivitas:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Entri Blog:",
		"BLOGCOMMENT":"Komentar Blog:",
		"BOOKMARK":"Markah:",
		"CALENDAREVENT":"Event:",
		"CATEGORY":"Kategori:",
		"COMMENT":"Komentar:",
		"COMMUNITY":"Komunitas:",
		"ENTRY":"Entri:",
		"EVENTDATEON":"Pada: {0}",
		"EVENTISALLDAY":"Event Seharian",
		"EVENTREPEATS":"Berulang",
		"FEED":"Umpan:",
		"FILE":"File:",
		"FORUM":"Forum:",
		"FORUMCATEGORY":"Kategori Forum:",
		"FORUMTOPIC":"Topik Forum:",
		"IDEA":"Ide:",
		"IDEACOMMENT":"Komentar Ide:",
		"IDEATIONBLOG":"Blog Ide:",
		"PAGE":"Halaman:",
		"PROFILE":"Profil:",
		"SECTION":"Bagian:",
		"STATUSUPDATE":"Pembaruan Status",
		"STATUSUPDATE_PREFIX":"Pembaruan Status:",
		"TOPIC":"Topik:",
		"TOPIC_WITH_ATTACHMENT":"Topik",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Halaman Wiki:",
		"WIKIFILE":"Lampiran Wiki:",
		"SEARCH":"Pencarian:",
		"TODO":"Tugas:",
		"ALLRESULTS":"Semua Hasil",
		"PUBLICCONTENT":"Konten Publik",
		"MYCONTENT":"Konten Saya",
		"RESULTNOTFOUND":"Anda menemukan yang Anda cari?",
		"TEMPDIFFICULTIES":"Catatan: Dikarenakan adanya masalah pengindeksan sementara, pencarian Anda tidak menyertakan {0} yang diubah dalam {1} hari terakhir.",
		"TRYLATER":"Harap coba lagi.",
		"MULTIPLETEMPDIFFICULTIES":"Catatan: Dikarenakan adanya masalah pengindeksan sementara, pencarian Anda tidak menyertakan {0} yang baru saja diubah",
		"YOUAREAUTHOR":"Anda adalah penulis",
		"YOUARECONTRIBUTOR":"Anda adalah kontributor",
		"YOUAREOWNER":"Anda adalah pemilik",
		"YOUAREMEMBER":"Anda adalah anggota",
		/* Profiles */
		"MYNETWORK":"Jaringan Saya",
		"ALLPEOPLE":"Semua Orang",
		"EXCLUDEINACTIVE":"Tidak Termasuk Orang Yang Tidak Aktif",
		"PHONE":"Telepon:",
		"EMAIL":"Email:",
		/* Communities */
		"ALLCOMMUNITIES":"Semua Komunitas",
		"PUBLICCOMMUNITIES":"Komunitas Umum",
		"MYCOMMUNITIES":"Komunitas Saya",
		"EVERYTHINGCOMMUNITIES":"Seluruhnya dari Komunitas",
		"COMMUNITIESONLY":"Komunitas",
		"COMMUNITIESCONTENT":"Konten dari Komunitas",
		/* Activities */
		"ALLACTIVITIES":"Semua Aktivitas",
		"PUBLICACTIVITIES":"Aktivitas Publik",
		"MYACTIVITIES":"Aktivitas Saya",
		"EVERYTHINGACTIVITIES":"Seluruhnya dari Aktivitas",
		"ACTIVITIESONLY":"Aktivitas",
		"SECTIONSACTIVITIES": "Bagian dari Aktivitas",
		"ENTRIESACTIVITIES":"Entri dari Aktivitas",
		"TODOSACTIVITIES":"Tugas dari Aktivitas",
		"BOOKMARKSACTIVITIES":"Markah dari Aktivitas",
		"FILESACTIVITIES":"Lampiran dari Aktivitas",
		"ALLTYPESACTIVITIES":"Semua jenis Aktivitas",
		"COMMUNITYACTIVITIES":"Aktivitas dari Komunitas",
		"STANDALONEACTIVITIES":"Aktivitas Mandiri",
		/* Forums */
		"ALLFORUMS":"Semua Forum",
		"PUBLICFORUMS":"Forum publik",
		"MYFORUMS":"Forum Saya",
		"EVERYTHINGFORUMS":"Seluruhnya dari Forum",
		"FORUMSONLY":"Forum",
		"TOPICSFORUMS":"Topik Forum",
		"FORUMCATEGORIES": "Kategori Forum",
		"FILESFORUMS":"Lampiran dari Forum",
		"ALLTYPESFORUMS":"Semua jenis Forum",
		"COMMUNITYFORUMS":"Forum dari Komunitas",
		"STANDALONEFORUMS":"Forum Mandiri",
		/* Blogs */
		"ALLBLOGS":"Semua Blog",
		"PUBLICBLOGS":"Blog Publik",
		"MYBLOGS":"Blog Saya",
		"EVERYTHINGBLOGS":"Seluruhnya dari Blog",
		"BLOGSONLY":"Blog",
		"ENTRIESBLOGS":"Entri Blog",
		"FILESBLOGS":"Lampiran dari Blog",
		"EVERYTHINGIDEATIONBLOGS":"Seluruhnya dari Blog Ide",
		"BLOGSIDEATIONBLOGS":"Blog Ide",
		"BLOGSIDEAS":"Ide",
		"ALLTYPESBLOGS":"Semua jenis Blog",
		"COMMUNITYBLOGS":"Blog dari Komunitas",
		"COMMUNITYIDEATIONBLOGS":"Blog Ide dari Komunitas",
		"STANDALONEBLOGS":"Blog Mandiri",
		/* Bookmarks */
		"ALLBOOKMARKS":"Semua Markah",
		"PUBLICBOOKMARKS":"Markah Publik",
		"MYBOOKMARKS":"Markah Saya",
		"ALLTYPESBOOKMARKS":"Semua jenis Markah",
		"COMMUNITYBOOKMARKS":"Markah dari Komunitas",
		"STANDALONEBOOKMARKS":"Markah Mandiri",
		/* Files */
		"ALLFILES":"Semua File",
		"PUBLICFILES":"File Publik",
		"MYFILES":"File Saya",
		"ALLTYPESFILES":"Semua jenis File",
		"COMMUNITYFILES":"File dari Komunitas",
		"STANDALONEFILES":"File Mandiri",
		"NUMDOWNLOADS":"{0} Unduhan",
		/* Wikis */
		"ALLWIKIS":"Semua Wiki",
		"PUBLICWIKIS":"Wiki Publik",
		"MYWIKIS":"Wiki Saya",
		"EVERYTHINGWIKIS":"Seluruhnya dari Wiki",
		"WIKISONLY":"Wiki",
		"PAGESWIKIS":"Halaman Wiki",
		"FILESWIKIS":"Lampiran dari Wiki",
		"ALLTYPESWIKIS":"Semua jenis Wiki",
		"COMMUNITYWIKIS":"Wiki dari Komunitas",
		"STANDALONEWIKIS":"Wiki Mandiri",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Semua Pembaruan Status",
		"PUBLICSTATUSUPDATES":"Pembaruan Status Publik",
		"MYSTATUSUPDATES":"Pembaruan Status Saya",
		"ALLTYPESSTATUSUPDATES":"Semua jenis Pembaruan Status",
		"COMMUNITYSTATUSUPDATES":"Pembaruan Status dari Komunitas",
		"STANDALONESTATUSUPDATES":"Pembaruan Status dari Profil",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"URL ini ditandai oleh sejumlah pengguna",
		"BOOKMARKEDCOMMUNITY":"Komunitas ini ditandai oleh sejumlah pengguna",
		"BOOKMARKEDPROFILE":"Profil ini ditandai oleh sejumlah pengguna",
		"BOOKMARKEDBLOG":"Blog ini ditandai oleh sejumlah pengguna",
		"COMMUNITYBLOG":"Ini adalah blog di dalam komunitas",
		"BOOKMARKEDACTIVITY":"Aktivitas ini ditandai oleh sejumlah pengguna",
		"COMMUNITYACTIVITY":"Ini adalah Aktivitas di dalam komunitas",
		"BOOKMARKEDFILE":"File ini ditandai oleh sejumlah pengguna",
		"COMMUNITYFILE":"Ini adalah File di dalam komunitas",
		"BOOKMARKED":"Wiki ini ditandai oleh sejumlah pengguna",
		"COMMUNITYWIKI":"Ini adalah Wiki di dalam komunitas",
		"BOOKMARKEDFORUM":"Forum ini ditandai oleh sejumlah pengguna",
		"COMMUNITYFORUM":"Ini adalah Forum di dalam komunitas",
		"ALLTAGANDTTILE":"Untuk melihat semua judul dan tanda untuk URL ini, klik tombol ini",
		"TAGS_ARE_FROM":"Hasil pencarian ini termasuk tanda dari:",
		"BOOKMARKS_TITLE":"Markah",
		"COMMUNITIES_TITLE":"Komunitas",
		"ACTIVITIES_TITLE":"Aktivitas",
		"HELP":"Bantuan",
		"MORESTATUSUPDATES":"Lihat lebih banyak kecocokan pembaruan status",
		"TITLE_PREFIX":"judul:",
		"LATEST_MESSAGE":"Pesan Terbaru",
		"LATEST_STATUS_UPDATE":"Pembaruan Status Terbaru",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Pembaruan Status Komunitas Terbaru",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Pembaruan Status Komunitas Terbaru",
		"SEARCH_RESULTS":"Semua Hasil Pencarian Konten",
		"ACTIVITIES_SEARCH_RESULTS":"Hasil Pencarian Aktivitas",
		"BLOGS_SEARCH_RESULTS":"Hasil Pencarian Blog",
		"BOOKMARKS_SEARCH_RESULTS":"Hasil Pencarian Markah",
		"COMMUNITIES_SEARCH_RESULTS":"Hasil Pencarian Komunitas",
		"FILES_SEARCH_RESULTS":"Hasil Pencarian File",
		"FORUMS_SEARCH_RESULTS":"Hasil Pencarian Forum",
		"PROFILES_SEARCH_RESULTS":"Hasil Pencarian Profil",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} Hasil Pencarian Direktori",
		"WIKIS_SEARCH_RESULTS":"Hasil Pencarian Wiki",
		"STATUS_UPDATES_SEARCH_RESULTS":"Hasil Pencarian Pembaruan Status",
		"VIEW_ALL":"{span}Tampilkan Semua{/span} ({0})",
		"MATCHING_ONE_OF":"Mencocokkan satu dari:",
		"MATCHING_ALL_OF":"Mencocokkan semua dari:",
		"MATCHING":"Cocok:",
		"MATCHING_DOC_TYPE":"Mencocokkan Jenis Dokumen:",
		"BOOKMARK_HELP":"Bantuan Markah",
		"CLOSE_BOOKMARK_HELP":"Menutup Bantuan Markah",
		"DOCUMENT_TYPE_PREFIX":"Jenis dokumen:",
		"LAST_PAGE_MESSAGE": "Wah, hasil pencarian sangat banyak. Coba sempitkan pencarian dengan menambahkan istilah pencarian lebih banyak.",
		"LAST_PAGE_SUBMESSAGE": "Anda mendapatkan {resultNumber} hasil pencarian pertama."
});

