/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"סינון לפי:",
"SHOW":"הצגה:",
"ACL_FILTER_LABEL":"סינון לפי נראות",
"PARENT_FILTER_LABEL":"סינון לפי מכולה",
"TYPE_FILTER_LABEL":"סינון לפי סוג",
"PAGING_TOP":"דפדוף ראשי",
"PAGING_BOTTOM":"דפדוף משני",
"PREVIOUS":"הקודם",
"NEXT":"הבא",
"PAGE":"דף {0} מתוך {1}",
"PAGE_COLON":"דף:",
"RESULTS":"{span}{0} - {1}{/span} מתוך {2}",
"ITEMS":"{0} פריטים",
/* Application names */
"ACTIVITIES":"פעילויות",
"BLOGS":"בלוגים",
"CALENDAR":"יומן",
"COMMUNITIES":"קהילות",
"BOOKMARKS":"סימניות",
"DOGEAR":"סימניות",
"EVENTS":"אירועים",
"FILES":"קבצים",
"FORUMS":"פורומים",
"PROFILES":"פרופילים",
"WIKI":"אתרי ויקי",
"WIKIS":"אתרי ויקי",
"FEEDS":"ערוצי תוכן",
"STATUS_UPDATES":"עדכוני מצב",
"ONECOMMENT":"1 הערה",
"COMMENTS":"{0} הערות",
"ONEPERSON":"1 אדם",
"PEOPLE":"{0} אנשים",
"TAGS":"תגים:",
"TAGSMORE":"ועוד {0}",
"NORESULTSMESSAGE":"לא נמצאו תוצאות עבור חיפוש זה",
"JAN":"ינואר",
"FEB":"פברואר",
"MAR":"מרס",
"APR":"אפריל",
"MAY":"מאי",
"JUN":"יוני",
"JUL":"יולי",
"AUG":"אוגוסט",
"SEP":"ספטמבר",
"OCT":"אוקטובר",
"NOV":"נובמבר",
"DEC":"דצמבר",
"NO_CONTACT":"החיפוש לא בוצע מפני שלא ניתן לתקשר עם השרת",
"SERVER_ERROR":"החיפוש לא בוצע בגלל שגיאה בשרת",
"SORT_BY":"מיון לפי:",
"SORT_RELEVANCE":"רלוונטיות",
"SORT_DATE":"תאריך",
"SORT_LAST_UPDATED":"עדכון אחרון",
"SORT_DUE_DATE":"תאריך יעד",
"SORT_VISITS":"כניסות",
"SORT_COMMENTS":"הערות",
"SORT_RECOMMENDATION":"סימוני 'אהבתי'",
"SORT_POPULARITY":"פופולריות",
"SORT_FIRSTNAME":"שם פרטי",
"SORT_LASTNAME":"שם משפחה",
"SORT_DOWNLOADS":"הורדות",
"SORT_TYPE":"סוג",
"SORT_SIZE":"גודל",
"SORT_TITLE":"תואר",
"PRIVATE":"פרטי",
"MODERATED":"בפיקוח",
"COMMUNITY_ACTIVITY":"פעילות קהילה",
"COMMUNITY_BLOG":"בלוג קהילה",
"COMMUNITY_FILE":"קובץ קהילה",
"COMMUNITY_FORUM":"פורום קהילה",
"COMMUNITY_WIKI":"ויקי קהילה",
"COMMUNITY_FEED":"ערוץ תוכן של קהילה",
"COMMUNITY_BOOKMARK":"סימניית קהילה",
"NO_TAG":"עדיין אין תגים",
"NO_DATE":"עדיין אין תאריכים",
"NO_PEOPLE":"עדיין אין אנשים",
"REMOVE_FILTER_LABEL":"לחצו כדי לסלק",
"REMOVE_FILTER_TITLE":"סילוק",
"REMOVE_FILTER_TOOLTIP":"סילוק מסנן זה",
"COMMENT_ON":"הערה על:",
"EXPAND_COLLAPSE":"לחצו כדי להרחיב / לכווץ",
"EXPAND":"הרחבה",
"COLLAPSE":"כיווץ",
"EXPAND_MONTHS_FILTER":"הרחבת מסנן החודשים של השנה {0}",
"SORT_RELEVANCE_LABEL":"לחצו כדי למיין לפי רלוונטיות",
"SORT_DATE_LABEL":"לחצו כדי למיין לפי תאריך",
"SORT_UPDATED_LABEL":"לחצו כדי למיין לפי עדכון אחרון",
"SORT_DUE_LABEL":"לחצו כדי למיין לפי תאריך יעד",
"SORT_VISITS_LABEL":"לחצו כדי למיין לפי מספר כניסות",
"SORT_COMMENTS_LABEL":"לחצו כדי למיין לפי מספר הערות",
"SORT_RECOMMENDATIONS_LABEL":"לחצו כדי למיין לפי מספר סימוני 'אהבתי'",
"SORT_POPULARITY_LABEL":"לחצו כדי למיין לפי פופולריות",
"SORT_FIRST_NAME_LABEL":"לחצו כדי למיין לפי שם פרטי",
"SORT_LAST_NAME_LABEL":"לחצו כדי למיין לפי שם משפחה",
"RATING":"סימוני 'אהבתי'",
"GRADUATED":"בוגר",
"ONEVOTE":"1 הצבעה",
"VOTES":"{0} הצבעות",
"BOOKMARK_THIS_RESULT":"סימניה לכאן",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (לא פעיל)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} אנשים הוסיפו סימניה",
/* eg from an Activity */
"FROMANACTIVITY":"מפעילות",
"FROMABLOG":"מבלוג",
"FROMANIDEATIONBLOG":"מבלוג רעיונות",
"FROMANEVENT":"מאירוע",
"FROMAFORUM":"מפורום",
"FROMAWIKI":"מוויקי",
"FROMACOMMUNITY":"מקהילה",
"FROMXCOMMUNITIES":"מ-{0} קהילות",
/* For search results parentage */
"ACTIVITY_ALONE":"פעילות",
"BLOG_ALONE":"בלוג",
"IDEATIONBLOG_ALONE":"בלוג רעיונות",
"ENTRY_ALONE":"רשומה",
"EVENT_ALONE":"אירוע",
"FORUM_ALONE":"פורום",
"WIKI_ALONE":"ויקי",
"COMMUNITY_ALONE":"קהילה",
"XCOMMUNITIES_ALONE":"{0} קהילות",
"SHAREDCOMMUNITIES":"משותף עם קהילות אלה",
"INACOMMUNITY":"בקהילה",
"LASTUPDATED":"אינדקס החיפוש עודכן לאחרונה:",
"NODESCRIPTION":"אין תיאור או סיכום עבור תוצאה זו.",
"ATTACHMENT":"קובץ מצורף:",
"ACTIVITY":"פעילות:",
"ACTIVITYBOOKMARK":"סימנייית פעילות:",
"ACTIVITYCOMMENT":"הערת בפעילות:",
"ACTIVITYENTRY":"רשומת פעילות:",
"ACTIVITYSECTION":"חלק פעילות:",
"ACTIVITYTODO":"מטלת פעילות:",
"BLOG":"בלוג:",
"BLOGENTRY":"רשומת בלוג:",
"BLOGCOMMENT":"הערת בלוג:",
"BOOKMARK":"סימניה:",
"CALENDAREVENT":"אירוע:",
"CATEGORY":"סיווג:",
"COMMENT":"הערה:",
"COMMUNITY":"קהילה:",
"ENTRY":"רשומה:",
"EVENTDATEON":"בתאריך: {0}",
"EVENTISALLDAY":"אירוע ליום שלם",
"EVENTREPEATS":"חוזר",
"FEED":"ערוץ תוכן:",
"FILE":"קובץ:",
"FORUM":"פורום:",
"FORUMCATEGORY":"סיווג פורום:",
"FORUMTOPIC":"נושא פורום:",
"IDEA":"רעיון:",
"IDEACOMMENT":"הערה לרעיון:",
"IDEATIONBLOG":"בלוג רעיונות:",
"PAGE":"דף:",
"PROFILE":"פרופיל:",
"SECTION":"חלק:",
"STATUSUPDATE":"עדכון מצב",
"STATUSUPDATE_PREFIX":"עדכון מצב:",
"TOPIC":"נושא:",
"TOPIC_WITH_ATTACHMENT":"נושא",
"WIKITYPE":"ויקי:",
"WIKIPAGE":"דף ויקי:",
"WIKIFILE":"צרופת ויקי:",
"SEARCH":"חיפוש:",
"TODO":"מטלה:",
"ALLRESULTS":"כל התוצאות",
"PUBLICCONTENT":"תוכן ציבורי",
"MYCONTENT":"התוכן שלי",
"RESULTNOTFOUND":"לא מצאתם מה שחיפשתם?",
"TEMPDIFFICULTIES":"הערה: בגלל קשיי מיפתוח זמניים, החיפוש לא כלל {0} שהשתנו ב-{1} הימים האחרונים.",
"TRYLATER":"נא לנסות שוב מאוחר יותר.",
"MULTIPLETEMPDIFFICULTIES":"הערה: בגלל קשיי מיפתוח זמניים, החיפוש לא כלל {0} שהשתנו לאחרונה",
"YOUAREAUTHOR":"אתם מחברים",
"YOUARECONTRIBUTOR":"אתם תורמים",
"YOUAREOWNER":"אתם בעלים",
"YOUAREMEMBER":"אתם חברים",
/* Profiles */
"MYNETWORK":"הרשת שלי",
"ALLPEOPLE":"כל האנשים",
"EXCLUDEINACTIVE":"סינון אנשים לא-פעילים",
"PHONE":"טלפון:",
"EMAIL":"דואל:",
/* Communities */
"ALLCOMMUNITIES":"כל הקהילות",
"PUBLICCOMMUNITIES":"קהילות ציבוריות",
"MYCOMMUNITIES":"הקהילות שלי",
"EVERYTHINGCOMMUNITIES":"הכל מיישום הקהילות",
"COMMUNITIESONLY":"קהילות",
"COMMUNITIESCONTENT":"תוכן מיישום הקהילות",
/* Activities */
"ALLACTIVITIES":"כל הפעילויות",
"PUBLICACTIVITIES":"פעילויות ציבוריות",
"MYACTIVITIES":"הפעילויות שלי",
"EVERYTHINGACTIVITIES":"הכל מיישום הפעילויות",
"ACTIVITIESONLY":"פעילויות",
"SECTIONSACTIVITIES": "חלקים מיישום הפעילויות",
"ENTRIESACTIVITIES":"רשומות מיישום הפעילויות",
"TODOSACTIVITIES":"מטלות מיישום הפעילויות",
"BOOKMARKSACTIVITIES":"סימניות מיישום הפעילויות",
"FILESACTIVITIES":"צרופות מיישום הפעילויות",
"ALLTYPESACTIVITIES":"כל סוגי הפעילויות",
"COMMUNITYACTIVITIES":"פעילויות מיישום הקהילות",
"STANDALONEACTIVITIES":"פעילויות עצמאיות",
/* Forums */
"ALLFORUMS":"כל הפורומים",
"PUBLICFORUMS":"פורומים ציבוריים",
"MYFORUMS":"הפורומים שלי",
"EVERYTHINGFORUMS":"הכל מיישום הפורומים",
"FORUMSONLY":"פורומים",
"TOPICSFORUMS":"נושאי פורום",
"FORUMCATEGORIES": "סיווגי פורום",
"FILESFORUMS":"צרופות מיישום הפורומים",
"ALLTYPESFORUMS":"כל סוגי הפורומים",
"COMMUNITYFORUMS":"פורומים הקהילות",
"STANDALONEFORUMS":"פורומים עצמאיים",
/* Blogs */
"ALLBLOGS":"כל הבלוגים",
"PUBLICBLOGS":"בלוגים ציבוריים",
"MYBLOGS":"הבלוגים שלי",
"EVERYTHINGBLOGS":"הכל מיישום הבלוגים",
"BLOGSONLY":"בלוגים",
"ENTRIESBLOGS":"רשומות בלוג",
"FILESBLOGS":"צרופות מיישום הבלוגים",
"EVERYTHINGIDEATIONBLOGS":"הכל מבלוגי רעיונות",
"BLOGSIDEATIONBLOGS":"בלוגי רעיונות",
"BLOGSIDEAS":"רעיונות",
"ALLTYPESBLOGS":"כל סוגי הבלוגים",
"COMMUNITYBLOGS":"בלוגים מיישום הקהילות",
"COMMUNITYIDEATIONBLOGS":"בלוגי רעיונות מיישום הקהילות",
"STANDALONEBLOGS":"בלוגים עצמאיים",
/* Bookmarks */
"ALLBOOKMARKS":"כל הסימניות",
"PUBLICBOOKMARKS":"סימניות ציבוריות",
"MYBOOKMARKS":"הסימניות שלי",
"ALLTYPESBOOKMARKS":"כל סוגי הסימניות",
"COMMUNITYBOOKMARKS":"סימניות מיישום הקהילות",
"STANDALONEBOOKMARKS":"סימניות עצמאיות",
/* Files */
"ALLFILES":"כל הקבצים",
"PUBLICFILES":"קבצים ציבוריים",
"MYFILES":"הקבצים שלי",
"ALLTYPESFILES":"כל סוגי הקבצים",
"COMMUNITYFILES":"קבצים מיישום הקהילות",
"STANDALONEFILES":"קבצים עצמאיים",
"NUMDOWNLOADS":"{0} הורדות",
/* Wikis */
"ALLWIKIS":"כל אתרי הוויקי",
"PUBLICWIKIS":"אתרי ויקי ציבוריים",
"MYWIKIS":"אתרי הוויקי שלי",
"EVERYTHINGWIKIS":"הכל מרכיב אתרי הוויקי",
"WIKISONLY":"אתרי ויקי",
"PAGESWIKIS":"דפי ויקי",
"FILESWIKIS":"צרופות מרכיב אתרי הוויקי",
"ALLTYPESWIKIS":"כל סוגי אתרי הוויקי",
"COMMUNITYWIKIS":"אתרי ויקי מיישום הקהילות",
"STANDALONEWIKIS":"אתרי ויקי עצמאיים",
/* Status Updates */
"ALLSTATUSUPDATES":"כל עדכוני המצב",
"PUBLICSTATUSUPDATES":"עדכוני מצב ציבוריים",
"MYSTATUSUPDATES":"עדכוני המצב שלי",
"ALLTYPESSTATUSUPDATES":"כל סוגי עדכוני המצב",
"COMMUNITYSTATUSUPDATES":"עדכוני מצב מיישום הקהילות",
"STANDALONESTATUSUPDATES":"עדכוני מצב מיישום הפרופילים",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"URL זה סומן בסימניה על ידי מספר משתמשים",
"BOOKMARKEDCOMMUNITY":"קהילה זו סומנה בסימניה על ידי מספר משתמשים",
"BOOKMARKEDPROFILE":"פרופיל זה סומן בסימניה על ידי מספר משתמשים",
"BOOKMARKEDBLOG":"בלוג זה סומן בסימניה על ידי מספר משתמשים",
"COMMUNITYBLOG":"זהו בלוג בתוך קהילה",
"BOOKMARKEDACTIVITY":"פעילות זו זה סומנה בסימניה על ידי מספר משתמשים",
"COMMUNITYACTIVITY":"זוהי פעילות בתוך קהילה",
"BOOKMARKEDFILE":"קובץ זה סומן בסימניה על ידי מספר משתמשים",
"COMMUNITYFILE":"זהו קובץ בתוך קהילה",
"BOOKMARKED":"ויקי זה סומן בסימניה על ידי מספר משתמשים",
"COMMUNITYWIKI":"זהו ויקי בתוך קהילה",
"BOOKMARKEDFORUM":"פורום זה סומן בסימניה על ידי מספר משתמשים",
"COMMUNITYFORUM":"זהו פורום בתוך קהילה",
"ALLTAGANDTTILE":"כדי לראות את כל הכותרות והתגים עבור URL זה לחצו על הלחצן",
"TAGS_ARE_FROM":"תוצאת חיפוש זו כוללת תגים מתוך:",
"BOOKMARKS_TITLE":"סימניות",
"COMMUNITIES_TITLE":"קהילות",
"ACTIVITIES_TITLE":"פעילויות",
"HELP":"עזרה",
"MORESTATUSUPDATES":"הצגת עוד התאמות של עדכוני מצב",
"TITLE_PREFIX":"כותרת:",
"LATEST_MESSAGE":"הודעה אחרונה",
"LATEST_STATUS_UPDATE":"עדכון מצב אחרון",
"LATEST_COMMUNITY_STATUS_UPDATE":"עדכון מצב אחרון של קהילה",
"LATEST_COMMUNITIES_STATUS_UPDATE":"עדכוני מצב אחרונים של קהילות",
"SEARCH_RESULTS":"תוצאות חיפוש בכל התוכן",
"ACTIVITIES_SEARCH_RESULTS":"תוצאות חיפוש בפעילויות",
"BLOGS_SEARCH_RESULTS":"תוצאות חיפוש בבלוגים",
"BOOKMARKS_SEARCH_RESULTS":"תוצאות חיפוש בסימניות",
"COMMUNITIES_SEARCH_RESULTS":"תוצאות חיפוש בקהילות",
"FILES_SEARCH_RESULTS":"תוצאות חיפוש בקבצים",
"FORUMS_SEARCH_RESULTS":"תוצאות חיפוש בפורומים",
"PROFILES_SEARCH_RESULTS":"תוצאות חיפוש בפרופילים",
"DIRECTORY_SEARCH_RESULTS":"תוצאות חיפוש במדריך ${orgName}",
"WIKIS_SEARCH_RESULTS":"תוצאות חיפוש באתרי ויקי",
"STATUS_UPDATES_SEARCH_RESULTS":"תוצאות חיפוש בעדכוני מצב",
"VIEW_ALL":"{span}הצגת הכל{/span} ({0})",
"MATCHING_ONE_OF":"התאמה לאחד מתוך:",
"MATCHING_ALL_OF":"התאמה לכל:",
"MATCHING":"התאמות:",
"MATCHING_DOC_TYPE":"סוג מסמך תואם:",
"BOOKMARK_HELP":"עזרה לסימניות",
"CLOSE_BOOKMARK_HELP":"סגירת העזרה לסימניות",
"DOCUMENT_TYPE_PREFIX":"סוג מסמך:",
"FILE_PREVIEW_ONLY":"(מצב תצוגה מקדימה בלבד)"
})

