/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Изисква се заглавие.",
	nourl: "Изисква се Url адрес.",
	fileSchema: "Ако желаете да добавите връзка към отдалечен или локален файл, тя трябва да съответства на един от следните формати: file://remote_path or file:///local_path.",
	invalidUrl: "Това не е валиден общностен URL адрес.",
	invalidTagChar: "Списъкът с етикети, който въведохте, съдържа невалидния знак „&“. Премахнете този знак от списъка с етикети.",
	txtHelp: "Помощ",
	txtHelpTags: "Помощ за етикети",
	txtHelpTagsClose: "Етикети Помощ Затваряне",
	tagsall: "Всички",
	tagsyours: "Ваши",
	tagsrecent: "Скорошни: ",
	tagspopular: "Популярни: ",
	tagsrecommended: "Препоръчани: ",
	nothingselected: "Изисква се избор на общност.",
	nothingselected_activity: "Изисква се избор на дейност.",
	nothingselected_blogs: "Изисква се избор на блог.",
	nothingselected_all: "Не са избрани услуга или запис, отметката няма да бъде запазена.",
	nothingFeedselected: "Не са избрани услуга или запис, информационният канал няма да бъде запазен.",
	alertDialogTitle: "Съобщение",
	alertDialogOK: "OK",
	expand: "Щракнете, за да разгънете този раздел",
	collapse: "Щракнете, за да сгънете този раздел",
	discussThis: "Дискутирайте това",
	by: "от:",
	posted: "Публикувано:",
	attachments: "Приложения",
	communityForum: "Форум на общността",
	notCommunityPage: "Текущата уеб страница не е валидна уеб страница на общност. Можете ръчно да въведете заглавието на общността, връзката и описанието за създаване на свързана общност.",
	privateCommunityNotice: "Тази общност е ограничена. Видима е само за членове на общността.",
	forumNameHint : "Въведете име на форум",
	formDescriptionHint:"Опишете защо тази свързана общност представлява интерес за общността Ви.",
	information : "Информация",
	error : "Грешка",
	success : "Успех",
	warning : "Предупреждение",
	informationColon : "Информация:",
	successColon : "Успешни:",
	warningColon : "Предупреждение:",
	errorColon : "Грешка:",
	feedAlreadyExist : "Информационният канал вече съществува в общността.",
	bookmarkAlreadyExist : "Отметката вече съществува в общността.",
	mentionAuthWarning:"Следните споменати лица няма да могат да видят съобщението, защото не са членове на общността:",
	mentionAuthForumWarning:"Следните споменати лица няма да могат да видят съобщението, защото нямат достъп до този форум:",
	exceedDescLength: "Описанието, което сте въвели, е твърде дълго.",
	communities_checked:"${0} избрани общности",
	activities_checked:"${0} избрани дейности",
	blogs_checked:"${0} избрани блога"
})
