/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknite ovdje kako biste vidjeli posjetnicu",
	"label.semtag.hover.alt" : "Kliknite kako biste vidjeli posjetnicu za {0}",
	"label.semtag.hover.altA11Y" : "Kliknite ovdje ili pritisnite tipke control i enter kako biste vidjeli posjetnicu",
	"label.personcard.dialog.title" : "Posjetnica za {0}",

	"errorDefaultMsg2" : "Dogodila se greška, kontaktirajte vašeg administratora sustava",

	"loadingSTStatus" : "Učitavanje statusa aplikacije Sametime...",
	"noStatuAvailable" : "Nema dostupnog statusa aplikacije Sametime",

	"label.personcard.cardnomarkup" : "Posjetnica se nije mogla dohvatiti",
	"label.inactive.user.msg" : "Ova osoba više nije aktivan korisnik",
	"label.message.information" : "Informacije:",
	"label.personcard.noprofilemsg" : "Profil za ovu osobu ne postoji",
	"label.personcard.cardreqexpired" : "Zahtjev za dobivanjem posjetnice je istekao",

	"label.bizcard.applinks.less" : "Pokaži manje",
	"label.bizcard.applinks.more" : "Pokaži više",

	"label.personcard.activitieslink" : "Aktivnosti",
	"label.personcard.activitieslink.title" : "Kliknite ovdje da vidite dijeljene aktivnosti",
	"label.personcard.blogslink" : "Blogovi",
	"label.personcard.blogslink.title" : "Kliknite ovdje da vidite blog ove osobe",
	"label.personcard.communitieslink" : "Zajednice",
	"label.personcard.communitieslink.title" : "Kliknite ovdje da vidite zajednice ove osobe",
	"label.personcard.dogearlink" : "Knjiške oznake",
	"label.personcard.dogearlink.title" : "Kliknite ovdje da vidite knjiške oznake ove osobe",
	"label.personcard.fileslink" : "Datoteke",
	"label.personcard.fileslink.title" : "Kliknite ovdje da vidite dijeljene datoteke ove osobe",
	"label.personcard.forumlink" : "Forumi",
	"label.personcard.forumlink.title" : "Kliknite ovdje da vidite objave na forumu ove osobe",
	"label.personcard.homepagelink" : "Početna stranica",
	"label.personcard.homepagelink.title" : "Kliknite ovdje da vidite početnu stranicu ove osobe",
	"label.personcard.mobilelink" : "Mobitel",
	"label.personcard.mobilelink.title" : "Kliknite ovdje da vidite prijenosnu stranicu ove osobe",
	"label.personcard.newslink" : "Novosti",
	"label.personcard.newslink.title" : "Kliknite ovdje da vidite novosti ove osobe",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknite ovdje da vidite profil ove osobe",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknite ovdje da vidite quickr dijeljenja ove osobe",
	"label.personcard.wikislink" : "Wikiji",
	"label.personcard.wikislink.title" : "Kliknite ovdje da vidite Wikije ove osobe",

	"personCardMoreActions" : "Više akcija",
	"personCardMoreActionsAltText" : "Kliknite za izbornik akcija",

	"label.bizcard.dismiss": "Pritisnite escape da biste odbacili ovu posjetnicu",
	"label.bizcard.fullProfile": "Potpuni profil",
	"label.bizcard.activities": "Aktivnosti",
	"label.bizcard.communities": "Zajednice",
	"label.bizcard.files": "Datoteke",
	"label.bizcard.forums": "Forumi",
	"label.bizcard.bookmarks": "Knjiške oznake",
	"label.bizcard.blogs": "Blogovi",
	"label.bizcard.wikis": "Wikiji",

	"personCardAddAsColleagues" : "Poziv u Moju mrežu",
	"personCardAddAsMyColleagues" : "Poziv u Moju mrežu",
	"personCardFollow" : "Prati",
	"personCardUnfollow" : "Zaustavi praćenje",
	"personCardChat" : "Razgovor",
	"personCardCall" : "Pozovi",
	"personCardSendMail" : "Pošalji e-poštu",
	"personCardSendEMail" : "Pošalji e-poštu",
	"personCardProxyStatusAvailable" : "Dostupan/na sam",
	"personCardDownloadVCard" : "Preuzmi vCard",

	"friends" : "Mreža",
	"friendsFullPageTitle" : "Mreža",
	"friendsMenuTitleAllContacts" : "Svi mrežni kontakti",
	"friendsMenuTitleMyContacts" : "Moji mrežni kontakti",
	"friendsInvitations" : "Pozivnice",
	"friendsMenuTitleInCommon" : "Zajedničke osobe",
	"friendsShowAllCommonFriends" : "Pokaži sve...",
	"friendsViewAllFriends" : "Pregledaj sve ({0})",
	"friendsSendFriendRequest" : "Pošalji zahtjev",
	"friendsNoFriends" : "Nema mrežnih kontakata pridruženih ovom profilu",
	"friendsColleaguesInvite" : "Pozovite {0} da bude vaš mrežni kontakt",
	"friendsColleaguesFor" : "Mrežni kontakti za {0}",
	"friendsNewInv" : "{0} nova pozivnica",
	"friendsNewInvs" : "{0} novih pozivnica",
	"friendsLoading" : "Učitavanje mreže...",
	"friendsLoadingInv" : "Učitavanje pozivnica---",
	"friendsSelectFriendForRemoval" : "Odaberite kontakte koje prve želite ukloniti.",
	"friendsRemoved" : "Mrežni kontakt(i) uklonjen(i).",
	"friendsInvSent" : "Nisu poslane pozivnice jer je pozivnica već na čekanju.",
	"friendsRemovedSelected" : "Ukloni iz moje mreže",
	"friendsSortByDisplayName" : "Ime prikaza",
	"friendsSortByRecent" : "Nedavno",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-pošta:",
	"friendsAltEmail" : "Alternativna e-pošta:",
	"friendsNewInvitationsCount" : "Imate sljedeći broj novih pozivnica: {0}",
	"friendsNoInv" : "Nema pozivnica",
	"friendsInCommonSingle" : "Imate {0} zajedničkih kontakata",
	"friendsInCommonMulti" : "Imate {0} zajedničkih kontakata",
	"friendsIncludeMsgForInv" : "Uključite poruku uz vašu pozivnicu:",
	"friendsInitialMsgForInv" : "Želim te dodati na listu kontakata u mreži aplikacije Connections.",
	"friendsSendInvAction" : "Pošalji pozivnicu",
	"friendsCancelInvAction" : "Otkaži",
	"friendsAcceptAction" : "Prihvati",
	"friendsIgnoreAction" : "Zanemari",
	"friendsYouExceedTextLimit" : "Vaša je poruka poziva predugačka. Može biti najviše {1} znakova. Ima {0} znakova u ovom polju.",
	"friendsCannotAddYourself" : "Ne možete sami sebe dodati kao mrežni kontakt.",
	"friendsIsYourColleague" : "{0} je vaš mrežni kontakt",
	"friendsRecentlyAdded" : "Ljudi koje ste nedavno dodali u vašu mrežu.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Kliknite da skupite ovaj odjeljak mreže",
	"friendsExpandWidget" : "Kliknite da proširite ovaj odjeljak mreže",
	"friendsIsInYourNetwork" : "{0} je u vašoj mreži",
	"friendsActionsFor" : "Akcije za mrežu",
	"friendsInviteFollowError" : "Dogodila se greška pri pokušaju praćenja {0}",
	"friendsInviteTagError" : "Dogodila se greška pri pokušaju označavanja {0}",
	"friendsPleaseLogIn" : "Prijavite se da biste pozvali ljude u vašu mrežu",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Poziv u vašu mrežu nije moguć jer je {0} već u vašoj mreži.",
	"friendsInviteAddTagsFor" : "Dodaj oznake za {0}:",
	"friendsInviteAlsoFollow" : "Također prati",
	"friendsInviteReceiveUpdates" : "(primaj ažuriranja)",
	"friendsInviteUpdatesDescription" : "Primite ažuriranja o osobama koje pratite na početnoj stranici i u sažetku e-pošte.",
	"friendsInviteFollowHelp": "Za više informacija pogledajte {0}Praćenje ljudi{1}.",
	"friendsNetwork" : "Mreža",
	"friendsMyNetwork" : "Mreža",
	"friendsNetworkFor" : "Mreža za {0}",
	"friendsRemoveSelected" : "Ukloni odabrano",
	"friendsRemoveSelectedTip" : "Kliknite za uklanjanje odabranih ljudi iz vaše mreže.",
	"friendsNetworkInCommon" : "Imate {0} zajedničkih mrežnih veza.",
	"friendsAddToMyNetwork" : "Želim te dodati na svoju mrežu aplikacije Connections.",
	"friendsInvite" : "Poziv u Moju mrežu",
	"friendsInvitePerson" : "Pozovite {0} u vašu mrežu",
	"friendsInviteMessage" : "Želim te dodati na svoju mrežu aplikacije Connections.",
	"friendsInvitedEmailSubject" : "[Profili] Pozvani ste da se pridružite mojoj mreži",
	"friendsInvitedEmailMsg1" : "vas je pozvao da postanete mrežni kontakt sa sljedećom porukom uključenom u pozivnicu:",
	"friendsInvitedEmailMsg2" : "Otvorite svoju stranicu Poziv s mreže",
	"friendsInvitedEmailMsg3" : "Želim vas dodati u svoju mrežu.",
	"friendsInvitedEmailMsg4" : "{0} vas je pozvao da postanete mrežni kontakt:",
	"friendsInvitedEmailMsg5" : "{0} vas je pozvao da postanete mrežni kontakt sa sljedećom porukom uključenom u pozivnicu:",
	"friendsInviteLegalNote" : "Slanjem ove pozivnice slažete se da {0} ima dozvolu komentiranja na vašoj ploči profila.",
	"friendsInviteFailed" : "Zbog greške poslužitelja obavijest e-pošte nije poslana pozvanoj osobi. Međutim, pozvana će osoba i dalje moći prihvatiti vašu pozivnicu kroz mrežnu aplikaciju Profili.",
	"personInNetwork" : "Mrežni kontakt"
})
