/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtrar por:",
		"SHOW":"Mostrar:",
		"ACL_FILTER_LABEL":"Filtrar por visibilidade",
		"PARENT_FILTER_LABEL":"Filtrar por contêiner",
		"TYPE_FILTER_LABEL":"Filtrar por tipo",
		"PAGING_TOP":"Paginação primária",
		"PAGING_BOTTOM":"Paginação secundária",
		"PREVIOUS":"Voltar",
		"NEXT":"Próximo",
		"PAGE":"Página {0} de {1}",
		"PAGE_COLON":"Página:",
		"RESULTS":"{span}{0}-{1}{/span} de {2}",
		"ITEMS":"{0} itens",
		/* Application names */
		"ACTIVITIES":"Atividades",
		"BLOGS":"Blogs",
		"CALENDAR":"Calendário",
		"COMMUNITIES":"Comunidades",
		"BOOKMARKS":"Favoritos",
		"DOGEAR":"Favoritos",
		"EVENTS":"Eventos",
		"FILES":"Arquivos",
		"FORUMS":"Fóruns",
		"PROFILES":"Perfis",
		"WIKI":"Wikis",
		"WIKIS":"Wikis",
		"FEEDS":"Feeds",
		"STATUS_UPDATES":"Atualizações de Status",
		"ONECOMMENT":"1 comentário",
		"COMMENTS":"{0} comentários",
		"ONEPERSON":"1 Pessoa",
		"PEOPLE":"{0} Pessoas",
		"TAGS":"Marcações:",
		"TAGSMORE":"e {0} mais",
		"NORESULTSMESSAGE":"Nenhum resultado foi localizado para essa procura",
		"JAN":"Janeiro",
		"FEB":"Fevereiro",
		"MAR":"Março",
		"APR":"Abril",
		"MAY":"Maio",
		"JUN":"Junho",
		"JUL":"Julho",
		"AUG":"Agosto",
		"SEP":"Setembro",
		"OCT":"Outubro",
		"NOV":"Novembro",
		"DEC":"Dezembro",
		"NO_CONTACT":"A procura não foi executada porque o servidor não pôde ser contatado",
		"SERVER_ERROR":"A procura não foi executada devido a um erro do servidor",
		"SORT_BY":"Classificar por:",
		"SORT_RELEVANCE":"Relevância",
		"SORT_DATE":"Data",
		"SORT_LAST_UPDATED":"Última Atualização",
		"SORT_DUE_DATE":"Prazo Final",
		"SORT_VISITS":"Visitas",
		"SORT_COMMENTS":"Comentários",
		"SORT_RECOMMENDATION":"Curtir",
		"SORT_POPULARITY":"Popularidade",
		"SORT_FIRSTNAME":"Nome",
		"SORT_LASTNAME":"Sobrenome",
		"SORT_DOWNLOADS":"Downloads",
		"SORT_TYPE":"Tipo",
		"SORT_SIZE":"Tamanho",
		"SORT_TITLE":"Posição",
		"PRIVATE":"Privado",
		"MODERATED":"Moderador",
		"COMMUNITY_ACTIVITY":"Atividade da Comunidade",
		"COMMUNITY_BLOG":"Blog da Comunidade",
		"COMMUNITY_FILE":"Arquivo da Comunidade",
		"COMMUNITY_FORUM":"Fórum da Comunidade",
		"COMMUNITY_WIKI":"Wiki da Comunidade",
		"COMMUNITY_FEED":"Feed da Comunidade",
		"COMMUNITY_BOOKMARK":"Favorito da Comunidade",
		"NO_TAG":"Nenhuma marcação ainda",
		"NO_DATE":"Nenhuma data ainda",
		"NO_PEOPLE":"Ninguém ainda",
		"REMOVE_FILTER_LABEL":"Clique para Remover",
		"REMOVE_FILTER_TITLE":"Remover",
		"REMOVE_FILTER_TOOLTIP":"Remover este Filtro",
		"COMMENT_ON":"Comentar:",
		"EXPAND_COLLAPSE":"Clique para expandir / reduzir",
		"EXPAND":"Expandir",
		"COLLAPSE":"Reduzir",
		"EXPAND_MONTHS_FILTER":"Expandir o filtro de meses do ano {0}",
		"SORT_RELEVANCE_LABEL":"Clique para classificar por relevância",
		"SORT_DATE_LABEL":"Clique para classificar por data",
		"SORT_UPDATED_LABEL":"Clique para classificar pela última atualização",
		"SORT_DUE_LABEL":"Clique para classificar por prazo final",
		"SORT_VISITS_LABEL":"Clique para classificar por número de visitas",
		"SORT_COMMENTS_LABEL":"Clique para classificar por número de comentários",
		"SORT_RECOMMENDATIONS_LABEL":"Clique para classificar por número de itens com curtir",
		"SORT_POPULARITY_LABEL":"Clique para classificar por popularidade",
		"SORT_FIRST_NAME_LABEL":"Clique para classificar por nome",
		"SORT_LAST_NAME_LABEL":"Clique para classificar por sobrenome",
		"RATING":"Curtir",
		"GRADUATED":"Graduado",
		"ONEVOTE":"1 voto",
		"VOTES":"{0} votos",
		"BOOKMARK_THIS_RESULT":"Incluir aos Favoritos",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (inativo)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} pessoas incluídas como favoritos",
		/* eg from an Activity */
		"FROMANACTIVITY":"de uma Atividade",
		"FROMABLOG":"de um Blog",
		"FROMANIDEATIONBLOG":"de um Blog de ideias",
		"FROMANEVENT":"a partir de um Evento",
		"FROMAFORUM":"de um Fórum",
		"FROMAWIKI":"de uma Wiki",
		"FROMACOMMUNITY":"de uma Comunidade",
		"FROMXCOMMUNITIES":"de {0} Comunidades",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Atividade",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog de ideias",
		"ENTRY_ALONE":"Entrada",
		"EVENT_ALONE":"Evento",
		"FORUM_ALONE":"Fórum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Comunidade",
		"XCOMMUNITIES_ALONE":"{0} Comunidades",
		"SHAREDCOMMUNITIES":"Compartilhado com essas comunidades",
		"INACOMMUNITY":"em uma Comunidade",
		"LASTUPDATED":"O índice de procura foi recém-atualizado:",
		"NODESCRIPTION":"Nenhuma descrição ou resumo para este resultado.",
		"ATTACHMENT":"Anexo:",
		"ACTIVITY":"Atividade:",
		"ACTIVITYBOOKMARK":"Favorito de atividade:",
		"ACTIVITYCOMMENT":"Comentário da atividade:",
		"ACTIVITYENTRY":"Entrada de atividade:",
		"ACTIVITYSECTION":"Seção da atividade:",
		"ACTIVITYTODO":"Tarefas pendentes da atividade:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Entrada de blog:",
		"BLOGCOMMENT":"Comentário do Blog",
		"BOOKMARK":"Favorito:",
		"CALENDAREVENT":"Evento:",
		"CATEGORY":"Categoria:",
		"COMMENT":"Comentário:",
		"COMMUNITY":"Comunidade:",
		"ENTRY":"Entrada:",
		"EVENTDATEON":"Em: {0}",
		"EVENTISALLDAY":"Evento de dia inteiro",
		"EVENTREPEATS":"Repetir",
		"FEED":"Feed:",
		"FILE":"Arquivo:",
		"FORUM":"Fórum:",
		"FORUMCATEGORY":"Categoria do fórum:",
		"FORUMTOPIC":"Tópico do fórum:",
		"IDEA":"Ideia:",
		"IDEACOMMENT":"Comentário da ideia:",
		"IDEATIONBLOG":"Blog de ideias:",
		"PAGE":"Página:",
		"PROFILE":"Perfil:",
		"SECTION":"Seção:",
		"STATUSUPDATE":"Atualização de Status",
		"STATUSUPDATE_PREFIX":"Atualização de Status:",
		"TOPIC":"Tópico:",
		"TOPIC_WITH_ATTACHMENT":"Tópico",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Página da wiki:",
		"WIKIFILE":"Anexo da wiki:",
		"SEARCH":"Procurar:",
		"TODO":"Pendência:",
		"ALLRESULTS":"Todos os Resultados",
		"PUBLICCONTENT":"Conteúdo Público",
		"MYCONTENT":"Meu Conteúdo",
		"RESULTNOTFOUND":"Não encontrou o que estava procurando?",
		"TEMPDIFFICULTIES":"Nota: Devido a dificuldades temporárias de indexação, sua procura não incluiu {0} que foram alteradas nos últimos {1} dia(s).",
		"TRYLATER":"Tente novamente mais tarde.",
		"MULTIPLETEMPDIFFICULTIES":"Nota: Devido a dificuldades temporárias de indexação, sua procura não incluiu {0} que foram alterados recentemente",
		"YOUAREAUTHOR":"Você é um autor",
		"YOUARECONTRIBUTOR":"Você é um contribuidor",
		"YOUAREOWNER":"Você é um proprietário",
		"YOUAREMEMBER":"Você é um membro",
		/* Profiles */
		"MYNETWORK":"Minha Rede",
		"ALLPEOPLE":"Todas as Pessoas",
		"EXCLUDEINACTIVE":"Excluir Pessoas Inativas",
		"PHONE":"Telefone:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Todas as Comunidades",
		"PUBLICCOMMUNITIES":"Comunidades Públicas",
		"MYCOMMUNITIES":"Minhas Comunidades",
		"EVERYTHINGCOMMUNITIES":"Tudo das Comunidades",
		"COMMUNITIESONLY":"Comunidades",
		"COMMUNITIESCONTENT":"Conteúdo das Comunidades",
		/* Activities */
		"ALLACTIVITIES":"Todas as Atividades",
		"PUBLICACTIVITIES":"Atividades Públicas",
		"MYACTIVITIES":"Minhas Atividades",
		"EVERYTHINGACTIVITIES":"Tudo das Atividades",
		"ACTIVITIESONLY":"Atividades",
		"SECTIONSACTIVITIES": "Seções de Atividades",
		"ENTRIESACTIVITIES":"Entradas das Atividades",
		"TODOSACTIVITIES":"Tarefas das Atividades",
		"BOOKMARKSACTIVITIES":"Favoritos das Atividades",
		"FILESACTIVITIES":"Anexos das Atividades",
		"ALLTYPESACTIVITIES":"Todos os Tipos de Atividades",
		"COMMUNITYACTIVITIES":"Atividades das Comunidades",
		"STANDALONEACTIVITIES":"Atividades Independentes",
		/* Forums */
		"ALLFORUMS":"Todos os Fóruns",
		"PUBLICFORUMS":"Fóruns Públicos",
		"MYFORUMS":"Meus Fóruns",
		"EVERYTHINGFORUMS":"Tudo dos Fóruns",
		"FORUMSONLY":"Fóruns",
		"TOPICSFORUMS":"Tópicos do Fórum",
		"FORUMCATEGORIES": "Categorias do Fórum",
		"FILESFORUMS":"Anexos dos Fóruns",
		"ALLTYPESFORUMS":"Todos os Tipos de Fóruns",
		"COMMUNITYFORUMS":"Fóruns das Comunidades",
		"STANDALONEFORUMS":"Fóruns Independentes",
		/* Blogs */
		"ALLBLOGS":"Todos os Blogs",
		"PUBLICBLOGS":"Blogs Públicos",
		"MYBLOGS":"Meus Blogs",
		"EVERYTHINGBLOGS":"Tudo dos Blogs",
		"BLOGSONLY":"Blogs",
		"ENTRIESBLOGS":"Entradas do Blog",
		"FILESBLOGS":"Anexos dos Blogs",
		"EVERYTHINGIDEATIONBLOGS":"Tudo de Blogs de Ideias",
		"BLOGSIDEATIONBLOGS":"Blogs de Ideias",
		"BLOGSIDEAS":"Ideias",
		"ALLTYPESBLOGS":"Todos os Tipos de Blogs",
		"COMMUNITYBLOGS":"Blogs das Comunidades",
		"COMMUNITYIDEATIONBLOGS":"Blogs de Ideias de Comunidades",
		"STANDALONEBLOGS":"Blogs Independentes",
		/* Bookmarks */
		"ALLBOOKMARKS":"Todos os Favoritos",
		"PUBLICBOOKMARKS":"Favoritos Públicos",
		"MYBOOKMARKS":"Meus Favoritos",
		"ALLTYPESBOOKMARKS":"Todos os Tipos de Favoritos",
		"COMMUNITYBOOKMARKS":"Favoritos das Comunidades",
		"STANDALONEBOOKMARKS":"Favoritos Independentes",
		/* Files */
		"ALLFILES":"Todos os arquivos",
		"PUBLICFILES":"Arquivos Públicos",
		"MYFILES":"Meus Arquivos",
		"ALLTYPESFILES":"Todos os Tipos de Arquivos",
		"COMMUNITYFILES":"Arquivos das Comunidades",
		"STANDALONEFILES":"Arquivos Independentes",
		"NUMDOWNLOADS":"{0} downloads",
		/* Wikis */
		"ALLWIKIS":"Todas as Wikis",
		"PUBLICWIKIS":"Wikis Públicas",
		"MYWIKIS":"Minhas Wikis",
		"EVERYTHINGWIKIS":"Tudo das Wikis",
		"WIKISONLY":"Wikis",
		"PAGESWIKIS":"Páginas da Wiki",
		"FILESWIKIS":"Anexos das Wikis",
		"ALLTYPESWIKIS":"Todos os Tipos de Wikis",
		"COMMUNITYWIKIS":"Wikis das Comunidades",
		"STANDALONEWIKIS":"Wikis Independentes",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Todas as Atualizações de Status",
		"PUBLICSTATUSUPDATES":"Atualizações de Status Públicas",
		"MYSTATUSUPDATES":"Minhas Atualizações de Status",
		"ALLTYPESSTATUSUPDATES":"Todos os Tipos de Atualizações de Status",
		"COMMUNITYSTATUSUPDATES":"Atualizações de Status a partir das Comunidades",
		"STANDALONESTATUSUPDATES":"Atualizações de Status a partir dos Perfis",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Esta URL foi incluída nos favoritos por vários usuários",
		"BOOKMARKEDCOMMUNITY":"Esta comunidade foi incluída nos favoritos por vários usuários",
		"BOOKMARKEDPROFILE":"Este Perfil foi incluído nos favoritos por vários usuários",
		"BOOKMARKEDBLOG":"Este Blog foi incluído nos favoritos por vários usuários",
		"COMMUNITYBLOG":"Este é um blog em uma comunidade",
		"BOOKMARKEDACTIVITY":"Esta Atividade foi incluída nos favoritos por vários usuários",
		"COMMUNITYACTIVITY":"Esta é uma Atividade em uma comunidade",
		"BOOKMARKEDFILE":"Este arquivo foi incluído nos favoritos por vários usuários",
		"COMMUNITYFILE":"Este é um Arquivo em uma comunidade",
		"BOOKMARKED":"Esta Wiki foi incluído nos favoritos por vários usuários",
		"COMMUNITYWIKI":"Esta é uma Wiki em uma comunidade",
		"BOOKMARKEDFORUM":"Este Fórum foi incluído nos favoritos por vários usuários",
		"COMMUNITYFORUM":"Este é um Fórum em uma comunidade",
		"ALLTAGANDTTILE":"Para ver todos os títulos e marcações desta URL, clique neste botão",
		"TAGS_ARE_FROM":"Este resultado da procura pode incluir marcações de:",
		"BOOKMARKS_TITLE":"Favoritos",
		"COMMUNITIES_TITLE":"Comunidades",
		"ACTIVITIES_TITLE":"Atividades",
		"HELP":"Ajuda",
		"MORESTATUSUPDATES":"Visualizar mais correspondências de atualização de status",
		"TITLE_PREFIX":"título:",
		"LATEST_MESSAGE":"Mensagem Mais Recente",
		"LATEST_STATUS_UPDATE":"Atualização de Status Mais Recente",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Atualização de Status Mais Recente da Comunidade",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Atualização de Status Mais Recente das Comunidades",
		"SEARCH_RESULTS":"Resultados da Procura de Todo o Conteúdo",
		"ACTIVITIES_SEARCH_RESULTS":"Resultados da Procura de Atividades",
		"BLOGS_SEARCH_RESULTS":"Resultados da Procura de Blogs",
		"BOOKMARKS_SEARCH_RESULTS":"Resultados da Procura de Favoritos",
		"COMMUNITIES_SEARCH_RESULTS":"Resultados da Procura de Comunidades",
		"FILES_SEARCH_RESULTS":"Resultados da Procura de Arquivos",
		"FORUMS_SEARCH_RESULTS":"Resultados da Procura de Fóruns",
		"PROFILES_SEARCH_RESULTS":"Resultados da Procura de Perfis",
		"DIRECTORY_SEARCH_RESULTS":"Resultados da Procura de Diretórios ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Resultados da Procura de Wikis",
		"STATUS_UPDATES_SEARCH_RESULTS":"Resultados da Procura de Atualizações de Status",
		"VIEW_ALL":"{span}Visualizar tudo{/span} ({0})",
		"MATCHING_ONE_OF":"Correspondendo um de:",
		"MATCHING_ALL_OF":"Correspondendo todos de:",
		"MATCHING":"Correspondendo a:",
		"MATCHING_DOC_TYPE":"Tipo de Documento Correspondente:",
		"BOOKMARK_HELP":"Ajuda de Favorito",
		"CLOSE_BOOKMARK_HELP":"Fechar Ajuda de Favorito",
		"DOCUMENT_TYPE_PREFIX":"Tipo de documento:",
		"LAST_PAGE_MESSAGE": "Há muitos resultados da procura. Tente limitar sua procura incluindo mais termos de procura.",
		"LAST_PAGE_SUBMESSAGE": "Você está obtendo os primeiros {resultNumber} resultados relevantes."
});

