/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "노드에 대한 정보: ",
	"INSTALLED": "설치된 서비스 확인",
	"RESUMETOKENS": "재개 토큰 확인",
	"SEEDLISTS": "시드 목록 사용 가능 여부 확인",
	"CALENDARS": "스케줄 일정관리가 올바르게 구성되었는지 확인",
	"VARIABLES": "WebSphere 변수가 설정되었는지 확인",
	"TASKS": "확인 태스크 사용 확인",
	"INDEXFILES": "필수 파일에 대한 색인 폴더 확인",
	"LOGS": "오류에 대한 로그 검토",
	"CONFIGFILES": "구성 파일 검토",
	"DICTIONARIES": "사용 가능한 사전 수 확인",
	"SYNC": "노드의 상태 확인 중",
	"DBRECORDS": "데이터베이스 레코드 확인",
	"INSTALLEDMSG": "다음 서비스가 설치되었습니다. ",
	"RESUMETOKENSMSG": "재개 토큰: ",
	"SEEDLISTSMSG": "시드 목록을 가져올 수 없습니다. ",
	"CALENDARSMSG": "스케줄 일정관리 확인 성공: ",
	"VARIABLESMSG": "변수: ",
	"TASKSMSG": "다음 태스크를 사용할 수 있음: ",
	"INDEXFILESMSG" : "다음은 검색 색인 폴더에 있는 파일입니다. ",
	"LOGSMSG" : "다음 오류 메시지를 검토하십시오. ",
	"CONFIGFILESMSG" : "다음 구성 파일이 발견되었습니다. ",
	"DICTIONARIESMSG" : "사용 가능한 사전 수: ",
	"INSYNC": "모든 노드가 동기화 상태임",
	"OUTOFSYNC": "동기화 상태가 아닌 노드 수: ",
	"NOTBLOCKED": "차단된 노드가 없음",
	"BLOCKED": "차단된 노드 수: ",
	"INDATE": "모든 노드가 최신 상태임",
	"OUTOFDATE": "오래된 노드 수: ",
	"NUMOFDOCS": "데이터베이스 내에 있는 문서의 수 ",
	"FILESTOCONVERT": "변환할 파일 문서의 수 ",
	"CONVERTEDFILES": "변환된 파일 수",
	"TOTALFILES": "데이터베이스 내에 있는 파일의 전체 수",
	"ERROR":"오류",
	"ERROR_PREFIX":"오류:",
	"INFO":"정보",
	"INFO_PREFIX":"정보:",
	"WARNING":"경고",
	"WARNING_PREFIX":"경고: ",
	"LOADING_MESSAGE": "로드 중",
	"SERVER_STATUS": "서버 상태",
	"INITIAL_INDEXING_EXCEPTIONS": "색인 작성 예외",
	"SYS_OUT_EXCEPTIONS": "SystemOut 로그 예외",
	"SEEDLIST_VALIDATE": "시드 목록 유효성 검증",
	"ERRORS_DURING_INITIAL_INDEXING":"초기 색인을 작성하는 중에 다음 예외가 발생했습니다.",
	"CRAWL_FAILED": "관심 사용자 등록 서비스에 필요한 모든 데이터를 크롤링할 수 없습니다.",
	"EXCEPTION_ENCOUNTERED": "다음 메시지가 표시되면서 크롤링이 실패했습니다.",
	"SAND_VALIDATE": "SAND 유효성 검증",
	"CHECK_FOR_SAND_FILES":"SAND 파일 검사 중",
	"IS_FILE_AVAILABLE":"파일이 작성되었는지 확인 중",
	"ERRORS_DURING_INITIAL_INDEXING":"초기 색인을 작성하는 중에 다음 예외가 발생했습니다.",
	"CRAWL_FAILED":"관심 사용자 등록 서비스에 필요한 모든 데이터를 크롤링할 수 없습니다.",
	"EXCEPTION_ENCOUNTERED":"다음 메시지가 표시되면서 크롤링이 실패했습니다."
})

