/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknutím tu zobrazíte vizitku",
	"label.semtag.hover.alt" : "Kliknutím tu zobrazíte vizitku používateľa {0}",
	"label.semtag.hover.altA11Y" : "Kliknutím tu alebo stlačením Ctrl+Enter zobrazíte vizitku",
	"label.personcard.dialog.title" : "Vizitka používateľa {0}",

	"errorDefaultMsg2" : "Vyskytla sa chyba. Kontaktujte správcu systému.",

	"loadingSTStatus" : "Načítava sa stav Sametime...",
	"noStatuAvailable" : "Stav Sametime nie je k dispozícii",

	"label.personcard.cardnomarkup" : "Vizitka sa nedá načítať",
	"label.inactive.user.msg" : "Táto osoba už nie je aktívnym používateľom",
	"label.message.information" : "Informácie:",
	"label.personcard.noprofilemsg" : "Pre túto osobu neexistuje profil",
	"label.personcard.cardreqexpired" : "Platnosť žiadosti o získanie vizitky vypršala",

	"label.bizcard.applinks.less" : "Zobraziť menej",
	"label.bizcard.applinks.more" : "Zobraziť viac",

	"label.personcard.activitieslink" : "Aktivity",
	"label.personcard.activitieslink.title" : "Kliknutím tu zobrazíte zdieľané aktivity",
	"label.personcard.blogslink" : "Blogy",
	"label.personcard.blogslink.title" : "Kliknutím tu zobrazíte blog tejto osoby",
	"label.personcard.communitieslink" : "Komunity",
	"label.personcard.communitieslink.title" : "Kliknutím tu zobrazíte komunity tejto osoby",
	"label.personcard.dogearlink" : "Záložky",
	"label.personcard.dogearlink.title" : "Kliknutím tu zobrazíte pridáte túto stránku ako záložku",
	"label.personcard.fileslink" : "Súbory",
	"label.personcard.fileslink.title" : "Kliknutím tu zobrazíte zdieľané súbory tejto osoby",
	"label.personcard.forumlink" : "Fóra",
	"label.personcard.forumlink.title" : "Kliknutím tu zobrazíte príspevky fóra tejto osoby",
	"label.personcard.homepagelink" : "Domov",
	"label.personcard.homepagelink.title" : "Kliknutím tu zobrazíte domovskú stránku tejto osoby",
	"label.personcard.mobilelink" : "Mobilné",
	"label.personcard.mobilelink.title" : "Kliknutím tu zobrazíte mobilnú stránku tejto osoby",
	"label.personcard.newslink" : "Správy",
	"label.personcard.newslink.title" : "Kliknutím tu zobrazíte novinky tejto osoby",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknutím tu zobrazíte profil tejto osoby",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknutím tu zobrazíte zdieľania quickr tejto osoby",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "Kliknutím tu zobrazíte stránky wiki tejto osoby",

	"personCardMoreActions" : "Viac akcií",
	"personCardMoreActionsAltText" : "Kliknutím zobrazíte ponuku akcií",

	"label.bizcard.dismiss": "Ak chcete zatvoriť vizitku, stlačte kláves Esc.",
	"label.bizcard.fullProfile": "Úplný profil",
	"label.bizcard.activities": "Aktivity",
	"label.bizcard.communities": "Komunity",
	"label.bizcard.files": "Súbory",
	"label.bizcard.forums": "Fóra",
	"label.bizcard.bookmarks": "Záložky",
	"label.bizcard.blogs": "Blogy",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "Pozvať do mojej siete",
	"personCardAddAsMyColleagues" : "Pozvať do mojej siete",
	"personCardFollow" : "Sledovať",
	"personCardUnfollow" : "Zastaviť sledovanie",
	"personCardChat" : "Rozhovor",
	"personCardCall" : "Volať",
	"personCardSendMail" : "Poslať e-mail",
	"personCardSendEMail" : "Poslať e-mail",
	"personCardProxyStatusAvailable" : "Som k dispozícii",
	"personCardDownloadVCard" : "Prevziať vCard",

	"friends" : "Sieť",
	"friendsFullPageTitle" : "Sieť",
	"friendsMenuTitleAllContacts" : "Všetky sieťové kontakty",
	"friendsMenuTitleMyContacts" : "Moje sieťové kontakty",
	"friendsInvitations" : "Pozvánky",
	"friendsMenuTitleInCommon" : "Spoloční ľudia",
	"friendsShowAllCommonFriends" : "Zobraziť všetky...",
	"friendsViewAllFriends" : "Zobraziť všetky ({0})",
	"friendsSendFriendRequest" : "Odoslať žiadosť",
	"friendsNoFriends" : "S týmto profilom nie sú spojené žiadne sieťové kontakty",
	"friendsColleaguesInvite" : "Pozvite používateľa {0}, aby sa stal vaším sieťovým kontaktom",
	"friendsColleaguesFor" : "Sieťové kontakty pre {0}",
	"friendsNewInv" : "{0} nová pozvánka",
	"friendsNewInvs" : "Nové pozvánky: {0}",
	"friendsLoading" : "Načítava sa sieť...",
	"friendsLoadingInv" : "Načítajú sa pozvánky...",
	"friendsSelectFriendForRemoval" : "Vyberte kontakty, ktoré chcete odstrániť ako prvé.",
	"friendsRemoved" : "Sieťové kontakty boli odstránené.",
	"friendsInvSent" : "Pozvánka sa neodoslala, pretože už čaká na odpoveď.",
	"friendsRemovedSelected" : "Odstrániť z mojej siete",
	"friendsSortByDisplayName" : "Zobrazované meno",
	"friendsSortByRecent" : "Posledné",
	"friendsTelephone" : "Telefón:",
	"friendsEmail" : "E-mailová adresa:",
	"friendsAltEmail" : "Alternatívna e-mailová adresa:",
	"friendsNewInvitationsCount" : "Počet vašich nových pozvánok je {0}",
	"friendsNoInv" : "Žiadne pozvánky",
	"friendsInCommonSingle" : "Máte spoločný {0} sieťový kontakt",
	"friendsInCommonMulti" : "Počet vašich spoločných sieťových kontaktov je {0}",
	"friendsIncludeMsgForInv" : "Zahrnúť správu s pozvánkou:",
	"friendsInitialMsgForInv" : "Chcem si vás pridať do môjho zoznamu sieťových kontaktov Connections.",
	"friendsSendInvAction" : "Odoslať pozvánku",
	"friendsCancelInvAction" : "Zrušiť",
	"friendsAcceptAction" : "Prijať",
	"friendsIgnoreAction" : "Ignorovať",
	"friendsYouExceedTextLimit" : "Text pozvánky je príliš dlhý. Môže obsahovať maximálne {1} znakov. V tomto poli je {0} znakov.",
	"friendsCannotAddYourself" : "Sami seba nemôžete pridať ako sieťový kontakt.",
	"friendsIsYourColleague" : "{0} je váš sieťový kontakt",
	"friendsRecentlyAdded" : "Ľudia, ktorých ste naposledy pridali do svojej siete.",
	"friendsDate" : "Dátum",
	"friendsCollapseWidget" : "Kliknutím zviniete sekciu siete",
	"friendsExpandWidget" : "Kliknutím rozviniete sekciu siete",
	"friendsIsInYourNetwork" : "{0} je vo vašej sieti.",
	"friendsActionsFor" : "Akcie pre sieť",
	"friendsInviteFollowError" : "Pri pokuse o sledovanie položky {0} sa vyskytla chyba",
	"friendsInviteTagError" : "Pri pokuse o označenie položky {0} sa vyskytla chyba",
	"friendsPleaseLogIn" : "Ak chcete pozvať ľudí do svojej siete, prihláste sa",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Pozvanie do vašej siete nie je možné, pretože {0} už je vo vašej sieti.",
	"friendsInviteAddTagsFor" : "Pridať značky pre {0}:",
	"friendsInviteAlsoFollow" : "Tiež sledovať",
	"friendsInviteReceiveUpdates" : "(prijať aktualizácie)",
	"friendsInviteUpdatesDescription" : "Aktivujte si príjem aktualizácií o ľuďoch, ktorých sledujete, na domovskej stránke a v e-mailovom súhrne.",
	"friendsInviteFollowHelp": "Viac informácií nájdete v časti {0}Sledovanie ľudí{1}.",
	"friendsNetwork" : "Sieť",
	"friendsMyNetwork" : "Sieť",
	"friendsNetworkFor" : "Sieť pre {0}",
	"friendsRemoveSelected" : "Odstrániť vybraté",
	"friendsRemoveSelectedTip" : "Kliknutím odstránite vybratých ľudí zo siete.",
	"friendsNetworkInCommon" : "Počet vašich spoločných sieťových pripojení je {0}.",
	"friendsAddToMyNetwork" : "Chcem si vás pridať do mojej siete Connections.",
	"friendsInvite" : "Pozvať do mojej siete",
	"friendsInvitePerson" : "Pozvať používateľa {0} do vašej siete",
	"friendsInviteMessage" : "Chcem si vás pridať do mojej siete Connections.",
	"friendsInvitedEmailSubject" : "[Profily] Pozývam vás, aby ste sa pripojili do mojej siete",
	"friendsInvitedEmailMsg1" : "vás pozval(a), aby ste sa stali sieťovým kontaktom. V pozvánke bola uvedená táto správa:",
	"friendsInvitedEmailMsg2" : "Otvoriť stránku Pozvanie do siete",
	"friendsInvitedEmailMsg3" : "Chcem si vás pridať do mojej siete.",
	"friendsInvitedEmailMsg4" : "Používateľ {0} vás pozval, aby ste sa stali sieťovým kontaktom:",
	"friendsInvitedEmailMsg5" : "Používateľ {0} vás pozval, aby ste sa stali sieťovým kontaktom. V pozvánke bola uvedená táto správa:",
	"friendsInviteLegalNote" : "Odoslaním tejto pozvánky súhlasíte s tým, že {0} bude môcť komentovať nástenku vo vašom profile.",
	"friendsInviteFailed" : "Z dôvodu chyby servera sa e-mailové upozornenie neodoslalo pozvanému používateľovi. Pozvaný používateľ však napriek tomu môže prijať vaše pozvanie prostredníctvom webovej aplikácie Profily.",
	"personInNetwork" : "Sieťový kontakt"
})
