/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informasi untuk simpul: ",
	"INSTALLED": "Mengecek layanan yang terinstal",
	"RESUMETOKENS": "Memeriksa token resume",
	"SEEDLISTS": "Memeriksa bahwa seedlist tersedia",
	"CALENDARS": "Memeriksa bahwa kalender jadwal telah dikonfigurasi dengan benar",
	"VARIABLES": "Memeriksa bahwa variabel WebSphere diatur",
	"TASKS": "Memeriksa tugas pengindeksan yang diaktifkan",
	"INDEXFILES": "Memeriksa folder indeks untuk file yang diperlukan",
	"LOGS": "Meninjau log dari kesalahan",
	"CONFIGFILES": "Meninjau file konfigurasi",
	"DICTIONARIES": "Memeriksa jumlah kamus yang telah diaktifkan",
	"SYNC": "Memeriksa status node",
	"DBRECORDS": "Mengecek catatan basis data",
	"INSTALLEDMSG": "Layanan berikut telah diinstal: ",
	"RESUMETOKENSMSG": "Token resume untuk: ",
	"SEEDLISTSMSG": "Seedlist tidak dapat diperoleh untuk: ",
	"CALENDARSMSG": "Telah lolos pengecekan kalender jadwal: ",
	"VARIABLESMSG": "Variabel: ",
	"TASKSMSG": "Task berikut telah diaktifkan: ",
	"INDEXFILESMSG" : "File berikut berada di folder indeks pencarian: ",
	"LOGSMSG" : "Tinjau pesan kesalahan berikut: ",
	"CONFIGFILESMSG" : "File konfigurasi berikut telah ditemukan: ",
	"DICTIONARIESMSG" : "Jumlah kamus yang diaktifkan adalah: ",
	"INSYNC": "Semua simpul sinkron",
	"OUTOFSYNC": "Jumlah simpul yang tidak sinkron adalah: ",
	"NOTBLOCKED": "Tidak ada simpul yang diblokir",
	"BLOCKED": "Jumlah simpul yang diblokir adalah: ",
	"INDATE": "Semua simpul masih berlaku",
	"OUTOFDATE": "Jumlah simpul yang kedaluwarsa adalah: ",
	"NUMOFDOCS": "Jumlah dokumen dalam basis data adalah ",
	"FILESTOCONVERT": "Jumlah file dokumen yang akan dikonversi ",
	"CONVERTEDFILES": "Jumlah file yang dikonversi adalah ",
	"TOTALFILES": "Total jumlah file dalam basis data ",
	"ERROR":"Terjadi Kesalahan",
	"ERROR_PREFIX":"Kesalahan:",
	"INFO":"Informasi",
	"INFO_PREFIX":"Informasi:",
	"WARNING":"Peringatan",
	"WARNING_PREFIX":"Peringatan:",
	"LOADING_MESSAGE": "Memuat",
	"SERVER_STATUS": "Status Server",
	"INITIAL_INDEXING_EXCEPTIONS": "Pengecualian Pengindeksan Awal",
	"SYS_OUT_EXCEPTIONS": "Pengecualian Log SystemOut",
	"SEEDLIST_VALIDATE": "Validasi Seedlist",
	"ERRORS_DURING_INITIAL_INDEXING":"Pengecualian berikut terjadi ketika membuat sebuah indeks awal",
	"CRAWL_FAILED": "Semua data untuk layanan berikut tidak dapat dirangkakkan: ",
	"EXCEPTION_ENCOUNTERED": "Perayap gagal dengan pesan berikut: ",
	"SAND_VALIDATE": "Validasi SAND",
	"CHECK_FOR_SAND_FILES":"Memeriksa untuk file SAND",
	"IS_FILE_AVAILABLE":"Memeriksa apakah file telah dibuat: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Pengecualian berikut terjadi ketika membuat sebuah indeks awal",
	"CRAWL_FAILED":"Semua data untuk layanan berikut tidak dapat dirangkakkan: ",
	"EXCEPTION_ENCOUNTERED":"Perayap gagal dengan pesan berikut: "
})

