define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Închidere",
		   'rs_loading' : "Încărcare...",
		   'rs_at' : "la",
		   'rs_searchDirectory' : "Persoană nelistată? Utilizaţi căutarea completă...",
		   'rs_searchGroupDirectory' : "Grupul nu este menţionat? Utilizaţi căutarea completă...",
		   'rs_searchPersonAndGroupDirectory' : "Persoana sau grupul nu sunt menţionate? Utilizaţi căutarea completă...",
		   'rs_searchCommunityDirectory' : "Comunitatea nu este menţionată? Utilizaţi căutarea completă...",
		   'rs_shadowText_searchDirectory' : "Tastaţi pentru a găsi persoana",
		   'rs_shadowText_searchGroupDirectory' : "Tastaţi pentru a găsi grupul",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Tastaţi pentru a găsi persoana sau grupul",
		   'rs_shadowText_searchCommunityDirectory' : "Tastaţi pentru a găsi comunitatea",
		   'rs_listItem' : "Componentă listă",
		   'rs_noResults' : "Niciun rezultat pentru '${0}'",
		   'rs_today' : "Astăzi",
		   'rs_tomorrow' : "Mâine",
		   'rs_yesterday' : "Ieri",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Alimentare pentru aceste activităţi",
		   'rs_externalText' : "Această activitate poate avea membri din afara organizaţiei dumneavoastră.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" s-a mutat cu succes la subcomunitatea \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Afişare informaţii suplimentare despre această activitate',
		   'rs_hideInfo' : 'Ascundere informaţii suplimentare',
		   'rs_more' : "Mai multe",
		   'rs_hide' : "Ascundere",
		   'rs_edit' : "Editare",
		   'rs_restore' : "Restaurare",
		   'rs_deleteEntry' : "Ştergere",
		   'rs_prioritize' : "Prioritizare",
		   'rs_markComplete' : "Marcare finalizată",
		   'rs_markIncomplete' : "Restaurare",
		   'rs_linkMore' : "... [mai mult]",
		   'rs_linkLess' : "... [mai puţin]",
		   'rs_actUpdatedByDate' : "Actualizat de ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Actualizat de ${0}",// Updated by (author name)
		   'rs_actDue' : "Scadent ${0}",// Due (date)
		   'rs_actTags' : "Taguri: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Pornire activitate din acest Şablon",
		   'rs_favoriteTemplate' : "Marcare ca şablon favorit",
		   'rs_normalTemplate' : "Marcare ca şablon normal",
		   'rs_tunedOutPri' : "Grad redus de interes",
		   'rs_pagepos' : "${0}-${1} din ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Anterior",
		   'rs_navNextLabel' : "Următor",
		   'rs_noActivities' : "Nu există activităţi pornite pentru această comunitate.",
		   'rs_feedError' : "Eşuare la încărcarea alimentării.",
		   'rs_highPri' : "Prioritate înaltă",
		   'rs_medPri' : "Prioritate medie",
		   'rs_normalPri' : "Prioritate normală (Implicit)",
		   'rs_tuneOut' : "Marcare ca grad redus de interes",
		   'rs_startActivity' : "Pornire activitate",
		   'rs_startFirstActivity' : "Creaţi-vă prima activitate",
		   'rs_navNextLabel' : "Următor",
		   'rs_viewAll' : "Vizualizare toate",
		   'rs_activityWidgetTitle' : "Activităţi",
		   'rs_activityWidgetBriefDescription' : "Urmăriţi obiectivele comunităţii.  Creaţi taskuri de făcut şi partajaţi resurse.",
		   'rs_activityWidgetDescription' : "Activităţile comunităţii pot fi utilizate pentru colaborare şi urmărirea progresului la proiectele sau iniţiativele comunităţii.",
		   'rs_completedActivityLink' : "Afişaţi Activităţile finalizate",
		   'rs_activitiesUnavailable' : "Serviciul Activităţi nu este disponibil.",
		   'rs_errorPersists' : "Dacă problema persistă, contactaţi administratorul dumneavoastră de sistem.",
		   'rs_shared' : "Partajat",
		   'rs_removeActFromComm' : "Înlăturaţi din comunitate",
		   'rs_externalLabel' : "Extern",
		   // for ActivityForm
		   'rs_templateOptions' : "Opţiuni şablon",
		   'rs_template' : "Şablon",
		   'rs_tagsLabel' : "Taguri",
		   'rs_peopleLabel' : "Persoane",
		   'rs_aboutThisTemplate' : "Despre acest şablon",
		   'rs_activity' : "Activitate",
		   'rs_copyOf' : "Copie a ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Obiective activitate",
		   'rs_noTemplate' : "Fără",
		   'rs_copyActivityMembers' : "Utilizare membri din activitate",
		   'rs_copyTemplateMembers' : "Utilizare membri din şablon",
		   /* Forum Widget */
		   'rs_noTopics' : "Deocamdată nu există subiecte pentru această comunitate.",
		   'rs_noTopicsLoggedIn' : "Puneţi o întrebare, faceţi brainstorming sau pur şi simplu împărtăşiţi-vă ideile.",
		   'rs_postedBy' : "Postat cel mai recent de",
		   'rs_topics' : "subiecte",
		   'rs_noTopicsShort' : "Nu există subiecte",
		   'rs_topic' : "subiect",
		   'rs_replies' : "replici",
		   'rs_noReplies' : "Fără replici",
		   'rs_reply' : "replică",
		   'rs_startTopic' : "Porniţi un subiect",
		   'rs_startFirstTopic' : "Porniţi primul subiect",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Blocat]",
		   'rs_manageForumSetting' : "Gestionare Setări de forum",
		   'rs_forumSettingCommunityOverviewPage' : "Pagina de privire generală asupra comunităţii:",
		   'rs_defaultForumList' : "Afişare listă de forumuri implicit",
		   'rs_defaultTopicList' : "Afişare listă de subiecte implicit",
		   'rs_forumSettingApplicationView' : "Vizualizare implicită a aplicaţiilor de forum:",
		   'rs_forumSettingNote' : "Notă: Subiectele sunt afişate implicit dacă există un singur forum.",
		   'rs_forumSettingSubmit' : "Trimitere",
		   'rs_forumSettingSave' : "Salvare",
		   'rs_forumSettingSaveAndClose' : "Salvare şi închidere",
		   'rs_forumSettingConfirm' : "Modificările dumneavoastră din Forumuri au fost salvate.",
		   'rs_forumSettingError' : "A apărut o eroare. Contactaţi-vă administratorul.",
		   'rs_formSettingHideMessage' : "Ascundeţi acest mesaj",
		   'rs_forumSettingCancel' : "Anulare",
		   'rs_forumAnsweredQuestion' : "Întrebări la care s-a răspuns",
		   'rs_forumUnAnsweredQuestion' : "Întrebări la care nu s-a răspuns",
		   'rs_forumSortBy' : "Sortare după:",
		   'rs_forumSortByDate' : "Dată",
		   'rs_forumSortByReplies' : "Replici",
		   'rs_forumSortByTopic' : "Subiecte",
		   'rs_forumSortByTopicsAndReplies' : "Subiecte şi replici",
		   'rs_sortByReplies' : "Sortare după replici",
		   'rs_sortbyTopicsAndReplies' : "Sortare după subiecte şi replici",
		   'rs_forumOpenQuestions' : "Întrebări deschise",
		   'rs_feedOpenQuestions' : "Alimentare pentru aceste întrebări deschise",
		   'rs_feedAnsweredQuestions' : "Alimentare pentru aceste întrebări cu răspuns",
		   'rs_forumMessages' : "${0} mesaje",
		   'rs_forumLastAddedPost' : "Postarea cea mai recentă de către ${0}",
		   'rs_forumTopics' : "${0} subiecte",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Creează legătură personală",
		   'rs_quote' : "Ghilimele",
		   'rs_labelColon' : "Etichetă: ",
		   'rs_personColon' : "Persoană: ",
		   'rs_personLink' : "Legătură persoană",
		   'rs_replace' : "Înlocuire",
		   'rs_inactivePerson' : "${0} (inactiv)", // person's name (inactive)
		   'rs_PersonPicture' : "Poza lui ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Utilizator extern", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (Utilizator extern)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Fotografie ${0} (utilizator extern)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Acest utilizator are acces la fişiere şi comunităţi partajate extern.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Notificare alte persoane",
		   'rs_messageColon' : "Mesaj: ",
		   'rs_notifyColon' : "Notificare: ",
		   'rs_notificationConfirm' : "Mesajul de notificare a fost trimis cu succes. ",
		   'rs_notificationFail' : "Mesajul de notificare nu a fost trimis. Încercaţi din nou mai târziu şi contactaţi-vă administratorul dacă problema persistă.",
		   'rs_pickCommunity' : "Alegeţi din lista de Comunităţi",
		   'rs_typeName' : "Tastaţi un nume",
		   'rs_typeToFilter' : "Tastaţi pentru a filtra această listă",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Tastaţi pentru a filtra această listă",
		   'rs_filterGroupLabel' : "Selectaţi Grupul",
		   'rs_noResults' : "Niciun rezultat găsit",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Afişare ${0} rezultate din ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Înlăturare",
		   /* Language Selector */
		   'rs_browser_setting' : "Setări Browser",
		   'rs_customLangaugeLinkLabel' : "Limb personalizată",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Salt la pagina ${0} din ${1}",
		   "rs_jumpPageLabel" : "Salt la pagină",
		   'rs_pageNumLabel' : "Număr pagină",
		   'rs_pageLabel' : "Pagină:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Taguri',
		   'rs_tagCloudToggleHint' : "Faceţi clic pentru ascundere sau afişare",
		   'rs_tagCloudHelpAlt' : "Obţineţi ajutor cu tagurile",
		   'rs_tagCloudNoTags' : "Niciun tag încă.",
		   'rs_tagCloudNoRecentTags' : "Nu există taguri recente",
		   'rs_tagCloudNoTagsProfiles' : "Căutaţi în director. Tagurile asociate cu profilurile returnate de căutare vor fi afişate aici.",
		   'rs_tagLoadingTags' : "Încărcare conţinut",
		   'rs_tagCloudSelectedTags' : "Taguri selectate",
		   'rs_tagCloudSeachDesc' : "Găsiţi un tag",
		   'rs_tagCloudSeach' : "Căutare",
		   'rs_tagCloudRelatedTags' : "Taguri înrudite",
		   'rs_tagCloudRelatedTagsDescription' : "Adăugaţi un tag înrudit pentru a rafina mai mult căutarea",
		   'rs_tagCloudError' : 'A fost o eroare',
		   'rs_viewAsCloud' : "Nor",
		   'rs_viewAsCloudTitle' : "Listaţi tagurile ca şi nor de taguri",
		   'rs_viewAsCloudDescription' : "Vizualizarea tagurilor ca şi nor de taguri",
		   'rs_viewAsList' : "Listă",
		   'rs_viewAsListTitle' : "Listaţi tagurile sub formă de listă secvenţială de taguri",
		   'rs_viewAsListDescription' : "Vizualizarea tagurilor sub formă de listă secvenţială de taguri",
		   'rs_tagCloudViewAll' : "Răsfoire",
		   'rs_tagCloudViewAllTitle' : "Răsfoiţi toate tagurile",
		   'rs_normalTags' : "Taguri active",
		   'rs_removeTag' : "Înlăturaţi tagul din filtrul de taguri selectat",
		   'rs_clearAll' : "Curăţaţi tot",
		   'rs_searchInputDefault' : "Tastaţi pentru a găsi un tag",
		   'rs_searchInputTagSelected' : "Tastaţi un alt tag",
		   'rs_relatedTagTitle' : "Afişarea rezultatelor căutării pentru tagul ${0}, număr de rezultate ${1}",
		   'rs_removeTagTitle' : "Înlăturaţi tagul ${0} din tagurile de filtrare selectate",
		   'rs_addTagTitle' : "Filtrare după tagul ${0} cu numărul ${1}",
		   'rs_tagDialogCloseTile' : "Închidere",
		   'rs_tagDialogTitle' : "Toate tagurile",
		   'rs_tagDialogPageInfo' : "${0} - ${1} din ${2} taguri",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Răsfoire grupuri",
		   'rs_group_browse_groups_dialog_title' : "Răsfoire grupuri",
		   'rs_group_browse_find_groups' : "Găsiţi grupuri",
		   'rs_group_browse_add_button' : "Adăugare",
		   'rs_group_browse_cancel_button' : "Anulare",
		   'rs_group_browse_enter_string' : "Tastaţi pentru a găsi grupuri",
		   'rs_group_browse_group_typeahead_label' : "Tastaţi un nume de grup:",
		   'rs_group_browse_group_name' : "Nume grup:",
		   'rs_group_browse_results_label' : "Selectaţi un grup potrivit:",
		   'rs_group_browse_parent_group_label' : "Sunteţi în:",
		   'rs_group_browse_next_page' : "Pagina următoare",
		   'rs_group_browse_previous' : "Anterior",
		   'rs_group_browse_next' : "Următor",
		   'rs_group_browse_paging' : "Paginare",
		   'rs_group_browse_previous_page' : "Pagina anterioară",
		   'rs_group_browse_group_selected' : "Grup selectat:",
		   'rs_group_browse_group_no_groups' : "Acest grup nu conţine grupuri",
		   'rs_group_browse_page_info' : "${0}-${1} din ${2}",
		   'rs_group_browse_page_info_alt' : "Potrivire grupuri ${0} până la ${1} din ${2}",
		   'rs_group_browse_remove_selection' : 'Înlăturaţi selecţia de grup imbricat: ${0}',
		   'rs_group_browse_paging' : "Paginare",
		   'rs_member_groups' : "Grupuri",
		   'rs_member_members' : "Membri",
		   'rs_member_no_results' : "Niciun rezultat găsit",
		   'rs_member_remove_group' : "Înlăturare ${0}",
		   'rs_member_add_to_community' : "Faceţi clic pentru a adăuga un membru",
		   'rs_member_remove_name' : "Faceţi clic pentru a înlătura un membru",
		   'rs_group_add_to_community' : "Faceţi clic pentru a adăuga un grup",
		   'rs_group_remove_name' : "Faceţi clic pentru a înlătura un grup",
		   'rs_group_name' : "Nume grup",
		   'rs_group_role' : "Rol grup",
		   'rs_warning' : "Avertisment",
		   'rs_a11y_warning' : "Avertisment:",
		   'rs_messagebox_close_btn_title' : "Închidere",
		   'rs_messagebox_close_btn_alt' : "Închidere",
		   'rs_messagebox_error_icon_alt' : "Eroare",
		   'rs_messagebox_error_a11y_label' : "Eroare:",
		   'rs_messagebox_warning_icon_alt' : "Avertisment",
		   'rs_messagebox_warning_a11y_label' : "Avertisment:",
		   'rs_messagebox_info_icon_alt' : "Informaţii",
		   'rs_messagebox_info_a11y_label' : "Informaţii:",
		   'rs_messagebox_success_icon_alt' : "Succes",
		   'rs_messagebox_success_a11y_label' : "Succes:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Inserare legătură la fişiere",
		   'rs_docpicker_label' : "Legătură la fişiere",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Descărcare ${0}",
		   'rs_docpicker_viewdetails_text' : "Vizualizare detalii",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Vizualizare detalii ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Înlăturare",
		   'rs_attachedfile_filename' : "Imagine ${0}",
		   'rs_feedreader_warning' : "Avertisment: Această legătură este pentru cititorii alimentare şi e posibil să se afişeze incorect în browser. Apăsaţi OK pentru a continua sau Anulare pentru a reveni la pagină.",
		   'rs_search' : "Căutare",
		   'rs_all_connections' : "Tot Connections",
		   'rs_advanced' : "Avansată",
		   'rs_select_scope' : "Selectaţi domeniul de căutare",
		   'rs_icfixlayout' : {
		      button_label : "Reformatare",
		      dialog_title : "Reformatare conţinut",
		      warning : "Avertisment",
		      reformat_save : "Reformatare şi salvare",
		      save_as_is : "Salvare cum este",
		      cancel : "Anulare",
		      warn_layout : "Conţinutul dumneavoastră depăşeşte lăţimea maximă de afişare.  Doriţi să reformataţi automat pentru potrivirea la spaţiul disponibil?",
		      remember_decision : "Să fie memorată decizia mea"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "A apărut o eroare în timpul partajării fişierelor selectate.",
		   'rs_sharefile_access_denied' : "Acest fişier a fost ştes sau nu mai este partajat cu dumneavoastră.",
		   'rs_sharefile_invalid_request' : "A apărut o eroare în timpul partajării fişierelor selectate.",
		   'rs_sharefile_sharing_intent_restriction' : "Fişierul poate fi partajat numai în organizaţia dumneavoastră.",
		   'rs_sharefile_error_title' : "Eroare",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'În App Store',
		   'rs_mobileBanner_inGooglePlay' : 'În Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Deschidere',
		   'rs_mobileBanner_view' : 'Vizualizare',
		   'rs_mobileBanner_hide' : 'Ascundere',

		   'rs_empty_column_placeholder' : 'Trageţi aplicaţiile aici.',
		   'rs_widget_loading_error_title' : 'Nu se poate afişa widget-ul',
		   'rs_widget_loading_error_message' : 'Încercaţi din nou mai târziu şi contactaţi-vă administratorul dacă problema persistă.',
		   'rs_widgets_loading_error_title' : 'Nu se poate afişa widget-ul în această comunitate',
		   'rs_widget_misplacement_warning' : 'Această aplicaţie nu se potriveşte în această coloană. Un proprietar de comunitate o poate muta în altă coloană sau o poate înlătura de pe pagină.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Titlul pe care l-aţi introdus este prea lung.',
		      empty_new_title : 'Titlul pe care l-aţi introdus nu poate fi gol.',
		      default_message : 'Nu se poate schimba titlul pentru această aplicaţie ${0}.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Titlu:  ',
		   'rs_widget_title_change_direction' : 'Modificaţi titlul pentru această aplicaţie ${0}.',
		   'rs_widget_title_change_title' : 'Modificare titlu',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Invitare sau adăugare membri",
		   'rs_vmmainContentDesc' : "Invitaţi membrii pentru a le acorda oportunitatea să se alăture comunităţii. Adăugaţi membrii de inclus automat.",
		   'rs_vmtypeAheadLabel' : "Nume sau e-mail: ",
		   'rs_vmgroupTypeAheadLabel' : "Nume: ",
		   'rs_vmtypeAheadRoleLabel' : " ca ",
		   'rs_vmgroupTypeAheadRoleLabel' : " ca Membri ",
		   'rs_vmtaNoResults' : "Nu au fost găsite rezultate.",
		   'rs_vmtaHeader' : "antet",
		   'rs_vmaddUser' : "Adăugare",
		   'rs_vmradioSectionTitle' : "Opţiuni membru:",
		   'rs_vmradioOne' : "Trimitere invitaţii pentru alăturare comunitate",
		   'rs_vmradioTwo' : "Adăugare automată membri la comunitate",
		   'rs_vmtwistyA' : "Adăugaţi un mesaj opţional",
		   'rs_vmtwistyB' : "Înlăturare text adiţional",
		   'rs_vmmessage' : "Mesaj:",
		   'rs_vmtextAreaStartText' : "Spuneţi ceva...",
		   'rs_vmcheckboxLabel' : "Trimiteţi-mi o copie",
		   'rs_vmsave' : "Salvare",
		   'rs_vminvite' : "Invitaţie",
		   'rs_vmcancel' : "Anulare",
		   'rs_userContentTitle' : "Introduceţi informaţiile",
		   'rs_vmaddUser' : "Creare utilizator",
		   'rs_vmback'	 : "Înapoi",
		   'rs_vmvisitor'	 : "Vizitator",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Faceţi clic aici pentru a copia această comunitate',
			'rs_commpicker' : ''

});
