/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Haga clic aquí para ver la tarjeta de presentación",
	"label.semtag.hover.alt" : "Haga clic para ver la tarjeta de presentación para {0}",
	"label.semtag.hover.altA11Y" : "Haga clic aquí o pulse control-intro para ver la tarjeta de presentación",
	"label.personcard.dialog.title" : "Tarjeta de presentación para {0}",

	"errorDefaultMsg2" : "Se ha producido un error; póngase en contacto con el administrador del sistema",

	"loadingSTStatus" : "Cargando estado de Sametime...",
	"noStatuAvailable" : "No hay estado de Sametime disponible",

	"label.personcard.cardnomarkup" : "No se ha podido recuperar la tarjeta de visita",
	"label.inactive.user.msg" : "Esta persona ya no es un usuario activo",
	"label.message.information" : "InformaciÃ³n:",
	"label.personcard.noprofilemsg" : "No existe un perfil para esta persona",
	"label.personcard.cardreqexpired" : "La solicitud para obtener la tarjeta de visita ha caducado",

	"label.bizcard.applinks.less" : "Mostrar menos",
	"label.bizcard.applinks.more" : "Mostrar más",

	"label.personcard.activitieslink" : "Actividades",
	"label.personcard.activitieslink.title" : "Pulse aquí para ver las actividades compartidas",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Pulse aquí para ver este blog de persona",
	"label.personcard.communitieslink" : "Comunidades",
	"label.personcard.communitieslink.title" : "Pulse aquí para ver estas comunidades de personas.",
	"label.personcard.dogearlink" : "Marcadores",
	"label.personcard.dogearlink.title" : "Pulse aquí para ver los marcadores de esta persona",
	"label.personcard.fileslink" : "Archivos",
	"label.personcard.fileslink.title" : "Pulse aquí para ver los archivos compartidos de esta persona",
	"label.personcard.forumlink" : "Foros",
	"label.personcard.forumlink.title" : "Pulse aquí para ver las publicaciones del foro de esta persona",
	"label.personcard.homepagelink" : "Particular",
	"label.personcard.homepagelink.title" : "Pulse aquí para ver la página inicial de esta persona",
	"label.personcard.mobilelink" : "Móvil",
	"label.personcard.mobilelink.title" : "Pulse aquí para ver la página de móvil de esta persona",
	"label.personcard.newslink" : "Noticias",
	"label.personcard.newslink.title" : "Pulse aquí para ver las noticias de esta persona",
	"label.personcard.profilelink" : "Perfil",
	"label.personcard.profilelink.title" : "Pulse aquí para ver el perfil de esta persona",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Pulse aquí para ver los archivos compartidos de quickr de esta persona",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Pulse aquí para ver las wikis de esta persona",

	"personCardMoreActions" : "Más acciones",
	"personCardMoreActionsAltText" : "Pulse aquí para ver el menú de acciones",

	"label.bizcard.dismiss": "Pulse escape para descartar esta tarjeta de visita.",
	"label.bizcard.fullProfile": "Perfil completo",
	"label.bizcard.activities": "Actividades",
	"label.bizcard.communities": "Comunidades",
	"label.bizcard.files": "Archivos",
	"label.bizcard.forums": "Foros",
	"label.bizcard.bookmarks": "Marcadores",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Invitar a Mi red",
	"personCardAddAsMyColleagues" : "Invitar a Mi red",
	"personCardFollow" : "Seguir",
	"personCardUnfollow" : "Dejar de seguir",
	"personCardChat" : "Conversación",
	"personCardCall" : "Llamar",
	"personCardSendMail" : "Enviar correo electrónico",
	"personCardSendEMail" : "Enviar correo electrónico",
	"personCardProxyStatusAvailable" : "Estoy disponible",
	"personCardDownloadVCard" : "Descargar vCard",

	"friends" : "Red",
	"friendsFullPageTitle" : "Red",
	"friendsMenuTitleAllContacts" : "Todos los contactos de red",
	"friendsMenuTitleMyContacts" : "Mis contactos de red",
	"friendsInvitations" : "Invitaciones",
	"friendsMenuTitleInCommon" : "Gente en común",
	"friendsShowAllCommonFriends" : "Mostrar todo...",
	"friendsViewAllFriends" : "Ver todos ({0})",
	"friendsSendFriendRequest" : "Enviar solicitud",
	"friendsNoFriends" : "No hay contactos de red asociados a este perfil",
	"friendsColleaguesInvite" : "Invitar a {0} para que sea su contacto de red",
	"friendsColleaguesFor" : "Contactos de red para {0}",
	"friendsNewInv" : "{0} invitación nueva",
	"friendsNewInvs" : "{0} invitaciones nuevas",
	"friendsLoading" : "Cargando red...",
	"friendsLoadingInv" : "Cargando invitaciones...",
	"friendsSelectFriendForRemoval" : "Seleccione primero los contactos que desee eliminar.",
	"friendsRemoved" : "Contactos de red eliminados.",
	"friendsInvSent" : "No se ha enviado ninguna invitación porque todavía hay una pendiente.",
	"friendsRemovedSelected" : "Suprimir de Mi red",
	"friendsSortByDisplayName" : "Mostrar nombre",
	"friendsSortByRecent" : "Recientes",
	"friendsTelephone" : "Teléfono:",
	"friendsEmail" : "Correo electrónico:",
	"friendsAltEmail" : "Correo electrónico alternativo:",
	"friendsNewInvitationsCount" : "Tiene {0} invitaciones nuevas",
	"friendsNoInv" : "Ninguna invitación",
	"friendsInCommonSingle" : "Tiene {0} contacto de red en común.",
	"friendsInCommonMulti" : "Tiene {0} contactos de red en común.",
	"friendsIncludeMsgForInv" : "Incluir un mensaje con la invitación:",
	"friendsInitialMsgForInv" : "Me gustaría añadirle a mi lista de contactos de red de Connections.",
	"friendsSendInvAction" : "Enviar invitación",
	"friendsCancelInvAction" : "Cancelar",
	"friendsAcceptAction" : "Aceptar",
	"friendsIgnoreAction" : "Ignorar",
	"friendsYouExceedTextLimit" : "El mensaje de invitación es demasiado largo. Puede tener un máximo de {1} caracteres. Hay {0} caracteres en este campo.",
	"friendsCannotAddYourself" : "No puede añadirse a sí mismo como contacto de red.",
	"friendsIsYourColleague" : "{0} es su contacto de red",
	"friendsRecentlyAdded" : "Personas que ha añadido recientemente a su red.",
	"friendsDate" : "Fecha",
	"friendsCollapseWidget" : "Pulse aquí­ para contraer la sección de red",
	"friendsExpandWidget" : "Pulse aquí para expandir la sección de red",
	"friendsIsInYourNetwork" : "{0} está en su red.",
	"friendsActionsFor" : "Acciones de Red",
	"friendsInviteFollowError" : "Se ha producido un error al intentar seguir a {0}",
	"friendsInviteTagError" : "Se ha producido un error al intentar etiquetar a {0}",
	"friendsPleaseLogIn" : "Inicie sesión para invitar a personas a su red",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "La invitación a su red no es posible porque {0} ya está en su red.",
	"friendsInviteAddTagsFor" : "Añadir etiquetas para {0}:",
	"friendsInviteAlsoFollow" : "También seguir",
	"friendsInviteReceiveUpdates" : "(recibir actualizaciones)",
	"friendsInviteUpdatesDescription" : "Recibir actualizaciones sobre personas que está siguiendo en la página de inicio y en un resumen de correo electrónico.",
	"friendsInviteFollowHelp": "Para obtener más información, consulte {0}Seguir a personas{1}.",
	"friendsNetwork" : "Red",
	"friendsMyNetwork" : "Red",
	"friendsNetworkFor" : "Red de {0}",
	"friendsRemoveSelected" : "Eliminar seleccionado",
	"friendsRemoveSelectedTip" : "Pulse aquí para suprimir las personas seleccionadas de la red.",
	"friendsNetworkInCommon" : "Tiene {0} conexiones de red en común.",
	"friendsAddToMyNetwork" : "Me gustaría añadirle a mi red de Connections.",
	"friendsInvite" : "Invitar a Mi red",
	"friendsInvitePerson" : "Invitar a {0} a su red",
	"friendsInviteMessage" : "Me gustaría añadirle a mi red de Connections.",
	"friendsInvitedEmailSubject" : "[Perfiles] Está invitado a unirse a mi red.",
	"friendsInvitedEmailMsg1" : "le ha invitado a ser un contacto de su red con el siguiente mensaje incluido en la invitación:",
	"friendsInvitedEmailMsg2" : "Abra la página Invitación de red",
	"friendsInvitedEmailMsg3" : "Me gustaría añadirle a mi red.",
	"friendsInvitedEmailMsg4" : "{0} le ha invitado a convertirse en un contacto de red:",
	"friendsInvitedEmailMsg5" : "{0} le ha invitado a ser un contacto de su red con el siguiente mensaje incluido en la invitación:",
	"friendsInviteLegalNote" : "Si envía esta invitación estará permitiendo que {0} pueda realizar comentarios en su pizarra.",
	"friendsInviteFailed" : "Debido a un error del servidor, no se ha enviado la notificación por correo electrónico al invitado. Sin embargo, el invitado todavía podrá aceptar su invitación a través de la aplicación web Perfiles.",
	"personInNetwork" : "Contacto de red"
})
