/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Fai clic qui per visualizzare il biglietto da visita",
	"label.semtag.hover.alt" : "Fai clic per visualizzare il biglietto da visita di {0}",
	"label.semtag.hover.altA11Y" : "Fai clic qui o premi CTRL+INVIO per visualizzare il biglietto da visita",
	"label.personcard.dialog.title" : "Biglietto da visita di {0}",

	"errorDefaultMsg2" : "Si è verificato un errore, contatta l'amministratore di sistema.",

	"loadingSTStatus" : "Caricamento stato Sametime…",
	"noStatuAvailable" : "Nessuno stato Sametime disponibile",

	"label.personcard.cardnomarkup" : "Impossibile recuperare il biglietto da visita",
	"label.inactive.user.msg" : "Questa persona non è più un utente attivo.",
	"label.message.information" : "Informazioni:",
	"label.personcard.noprofilemsg" : "Non esiste un profilo per questa persona.",
	"label.personcard.cardreqexpired" : "La richiesta per ottenere il biglietto da visita è scaduta.",

	"label.bizcard.applinks.less" : "Mostra meno",
	"label.bizcard.applinks.more" : "Mostra di più",

	"label.personcard.activitieslink" : "Attività",
	"label.personcard.activitieslink.title" : "Fai clic qui per visualizzare le attività condivise",
	"label.personcard.blogslink" : "Blog",
	"label.personcard.blogslink.title" : "Fai clic qui per visualizzare il blog di questa persona",
	"label.personcard.communitieslink" : "Comunità",
	"label.personcard.communitieslink.title" : "Fai clic qui per visualizzare le comunità di questa persona",
	"label.personcard.dogearlink" : "Segnalibri",
	"label.personcard.dogearlink.title" : "Fai clic qui per visualizzare i segnalibri di questa persona",
	"label.personcard.fileslink" : "File",
	"label.personcard.fileslink.title" : "Fai clic qui per visualizzare i file condivisi di questa persona",
	"label.personcard.forumlink" : "Forum",
	"label.personcard.forumlink.title" : "Fai clic qui per visualizzare i post del forum di questa persona",
	"label.personcard.homepagelink" : "Pagina iniziale",
	"label.personcard.homepagelink.title" : "Fai clic qui per visualizzare l'home page di questa persona",
	"label.personcard.mobilelink" : "Cellulare",
	"label.personcard.mobilelink.title" : "Fai clic qui per visualizzare la pagina mobile di questa persona",
	"label.personcard.newslink" : "Novità",
	"label.personcard.newslink.title" : "Fai clic qui per visualizzare le novità di questa persona",
	"label.personcard.profilelink" : "Profilo",
	"label.personcard.profilelink.title" : "Fai clic qui per visualizzare il profilo di questa persona",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Fai clic qui per visualizzare le condivisioni Quickr di questa persona",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "Fai clic qui per visualizzare i wiki di questa persona",

	"personCardMoreActions" : "Altre azioni",
	"personCardMoreActionsAltText" : "Fai clic per il menu azioni",

	"label.bizcard.dismiss": "Premi ESC per ignorare questo biglietto da visita.",
	"label.bizcard.fullProfile": "Profilo completo",
	"label.bizcard.activities": "Attività",
	"label.bizcard.communities": "Comunità",
	"label.bizcard.files": "File",
	"label.bizcard.forums": "Forum",
	"label.bizcard.bookmarks": "Segnalibri",
	"label.bizcard.blogs": "Blog",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "Invita alla rete personale",
	"personCardAddAsMyColleagues" : "Invita alla rete personale",
	"personCardFollow" : "Segui",
	"personCardUnfollow" : "Non seguire più",
	"personCardChat" : "Chat",
	"personCardCall" : "Chiama",
	"personCardSendMail" : "Invia email",
	"personCardSendEMail" : "Invia email",
	"personCardProxyStatusAvailable" : "Sono disponibile",
	"personCardDownloadVCard" : "Scarica vCard",

	"friends" : "Rete",
	"friendsFullPageTitle" : "Rete",
	"friendsMenuTitleAllContacts" : "Tutti i contatti di rete",
	"friendsMenuTitleMyContacts" : "Contatti di rete personali",
	"friendsInvitations" : "Inviti",
	"friendsMenuTitleInCommon" : "Persone in comune",
	"friendsShowAllCommonFriends" : "Mostra tutto…",
	"friendsViewAllFriends" : "Visualizza tutto ({0})",
	"friendsSendFriendRequest" : "Invia richiesta",
	"friendsNoFriends" : "Non ci sono contatti di rete associati a questo profilo.",
	"friendsColleaguesInvite" : "Invita {0} a diventare un tuo contatto di rete.",
	"friendsColleaguesFor" : "Contatti di rete di {0}",
	"friendsNewInv" : "{0} nuovo invito",
	"friendsNewInvs" : "{0} nuovi inviti",
	"friendsLoading" : "Caricamento rete…",
	"friendsLoadingInv" : "Caricamento inviti…",
	"friendsSelectFriendForRemoval" : "Prima seleziona i contatti che desideri rimuovere.",
	"friendsRemoved" : "Contatti di rete rimossi",
	"friendsInvSent" : "Non è stato possibile inviare inviti poiché è già presente un invito in sospeso.",
	"friendsRemovedSelected" : "Rimuovi dalla rete personale",
	"friendsSortByDisplayName" : "Nome visualizzato",
	"friendsSortByRecent" : "Recenti",
	"friendsTelephone" : "Telefono:",
	"friendsEmail" : "Email:",
	"friendsAltEmail" : "Email alternativa:",
	"friendsNewInvitationsCount" : "Hai {0} nuovi inviti",
	"friendsNoInv" : "Nessun invito",
	"friendsInCommonSingle" : "Avete {0} contatto di rete in comune.",
	"friendsInCommonMulti" : "Avete {0} contatti di rete in comune.",
	"friendsIncludeMsgForInv" : "Includi un messaggio nell'invito:",
	"friendsInitialMsgForInv" : "Vorrei aggiungerti al mio elenco di contatti di rete su Connections.",
	"friendsSendInvAction" : "Invia invito",
	"friendsCancelInvAction" : "Annulla",
	"friendsAcceptAction" : "Accetta",
	"friendsIgnoreAction" : "Ignora",
	"friendsYouExceedTextLimit" : "Il messaggio di invito è troppo lungo. Può avere al massimo {1} caratteri. Sono presenti {0} caratteri in questo campo.",
	"friendsCannotAddYourself" : "Impossibile aggiungere se stessi come contatto di rete",
	"friendsIsYourColleague" : "{0} è un contatto della tua rete.",
	"friendsRecentlyAdded" : "Persone che hai aggiunto di recente alla tua rete.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Fai clic per comprimere la sezione Rete",
	"friendsExpandWidget" : "Fai clic per espandere la sezione Rete",
	"friendsIsInYourNetwork" : "{0} è nella tua rete.",
	"friendsActionsFor" : "Azioni per rete",
	"friendsInviteFollowError" : "Si è verificato un errore durante il tentativo di seguire {0}.",
	"friendsInviteTagError" : "Si è verificato un errore durante il tentativo di taggare {0}.",
	"friendsPleaseLogIn" : "Accedi per invitare le persone alla tua rete.",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Non è possibile invitare {0} alla tua rete personale poiché è già nella tua rete.",
	"friendsInviteAddTagsFor" : "Aggiungi tag per {0}:",
	"friendsInviteAlsoFollow" : "Segui anche",
	"friendsInviteReceiveUpdates" : "(ricevere aggiornamenti)",
	"friendsInviteUpdatesDescription" : "Ricevi aggiornamenti sulle persone che stai seguendo nell'home page e in un'email di riepilogo.",
	"friendsInviteFollowHelp": "Per ulteriori informazioni, vedi {0}Persone seguite{1}.",
	"friendsNetwork" : "Rete",
	"friendsMyNetwork" : "Rete",
	"friendsNetworkFor" : "Rete per {0}",
	"friendsRemoveSelected" : "Rimuovi selezionati",
	"friendsRemoveSelectedTip" : "Fai clic per rimuovere le persone selezionate dalla tua rete.",
	"friendsNetworkInCommon" : "Avete {0} connessioni di rete in comune.",
	"friendsAddToMyNetwork" : "Vorrei aggiungerti alla mia rete personale su Connections.",
	"friendsInvite" : "Invita alla rete personale",
	"friendsInvitePerson" : "Invita {0} alla rete personale",
	"friendsInviteMessage" : "Vorrei aggiungerti alla mia rete personale su Connections.",
	"friendsInvitedEmailSubject" : "[Profili] Ti ho invitato a entrare nella mia rete",
	"friendsInvitedEmailMsg1" : "ti ha invitato a diventare un contatto di rete con il seguente messaggio incluso nell'invito:",
	"friendsInvitedEmailMsg2" : "Apri la pagina di invito alla rete.",
	"friendsInvitedEmailMsg3" : "Vorrei aggiungerti alla mia rete.",
	"friendsInvitedEmailMsg4" : "{0} ti ha invitato a diventare un contatto di rete:",
	"friendsInvitedEmailMsg5" : "{0} ti ha invitato a diventare un contatto di rete con il seguente messaggio incluso nell'invito:",
	"friendsInviteLegalNote" : "Inviando questo invito, consenti a {0} di aggiungere commenti nella bacheca del tuo profilo.",
	"friendsInviteFailed" : "A causa di un errore del server, la notifica email non è stata inviata all'invitato. Tuttavia, l'invitato potrà comunque accettare il tuo invito tramite l'applicazione web Profili.",
	"personInNetwork" : "Contatto di rete"
})
