/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kartviziti görüntülemek için burayı tıklatın",
	"label.semtag.hover.alt" : "{0} için kartviziti görüntülemek için burayı tıklatın",
	"label.semtag.hover.altA11Y" : "Kartviziti görüntülemek için burayı tıklatın veya control ve enter tuşlarına basın",
	"label.personcard.dialog.title" : "{0} için kartvizit",

	"errorDefaultMsg2" : "Bir hata oluştu, sistem yöneticinize başvurun",

	"loadingSTStatus" : "Sametime durumu yükleniyor...",
	"noStatuAvailable" : "Kullanılabilir Sametime durumu yok",

	"label.personcard.cardnomarkup" : "Kartvizit alınamadı",
	"label.inactive.user.msg" : "Bu kişi artık etkin bir kullanıcı değil",
	"label.message.information" : "Bilgi:",
	"label.personcard.noprofilemsg" : "Bu kişi için profil yok",
	"label.personcard.cardreqexpired" : "Kartvizit alma isteğinin süresi doldu",

	"label.bizcard.applinks.less" : "Daha az göster",
	"label.bizcard.applinks.more" : "Daha fazla göster",

	"label.personcard.activitieslink" : "Etkinlikler",
	"label.personcard.activitieslink.title" : "Paylaşılan etkinlikleri görmek için burayı tıklatın",
	"label.personcard.blogslink" : "Web Günlükleri",
	"label.personcard.blogslink.title" : "Bu kişinin web günlüğünü görmek için burayı tıklatın",
	"label.personcard.communitieslink" : "Topluluklar",
	"label.personcard.communitieslink.title" : "Bu kişinin topluluklarını görmek için burayı tıklatın",
	"label.personcard.dogearlink" : "Yer işaretleri",
	"label.personcard.dogearlink.title" : "Bu kişinin yer işaretlerini görmek için burayı tıklatın",
	"label.personcard.fileslink" : "Dosyalar",
	"label.personcard.fileslink.title" : "Bu kişinin paylaşılan dosyalarını görmek için burayı tıklatın",
	"label.personcard.forumlink" : "Forumlar",
	"label.personcard.forumlink.title" : "Bu kişinin forum gönderilerini görmek için burayı tıklatın",
	"label.personcard.homepagelink" : "Giriş",
	"label.personcard.homepagelink.title" : "Bu kişinin giriş sayfasını görmek için burayı tıklatın",
	"label.personcard.mobilelink" : "Mobil İletişim",
	"label.personcard.mobilelink.title" : "Bu kişinin mobil iletişim sayfasını görmek için burayı tıklatın",
	"label.personcard.newslink" : "Haberler",
	"label.personcard.newslink.title" : "Bu kişinin haberlerini görmek için burayı tıklatın",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Bu kişinin profilini görmek için burayı tıklatın",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Bu kişinin quickr paylaşımlarını görmek için burayı tıklatın",
	"label.personcard.wikislink" : "Vikiler",
	"label.personcard.wikislink.title" : "Bu kişinin vikilerini görmek için burayı tıklatın",

	"personCardMoreActions" : "Diğer Eylemler",
	"personCardMoreActionsAltText" : "Eylem menüsü için tıklatın",

	"label.bizcard.dismiss": "Bu kartviziti bırakmak için Escape tuşuna basın.",
	"label.bizcard.fullProfile": "Tam Profil",
	"label.bizcard.activities": "Etkinlikler",
	"label.bizcard.communities": "Topluluklar",
	"label.bizcard.files": "Dosyalar",
	"label.bizcard.forums": "Forumlar",
	"label.bizcard.bookmarks": "Yer işaretleri",
	"label.bizcard.blogs": "Web Günlükleri",
	"label.bizcard.wikis": "Vikiler",

	"personCardAddAsColleagues" : "Ağıma Davet Et",
	"personCardAddAsMyColleagues" : "Ağıma Davet Et",
	"personCardFollow" : "Takip Et",
	"personCardUnfollow" : "Takibi Durdur",
	"personCardChat" : "Sohbet",
	"personCardCall" : "Ara",
	"personCardSendMail" : "E-posta Gönder",
	"personCardSendEMail" : "E-posta Gönder",
	"personCardProxyStatusAvailable" : "Uygunum",
	"personCardDownloadVCard" : "vCard'ı Yükle",

	"friends" : "Ağ",
	"friendsFullPageTitle" : "Ağ",
	"friendsMenuTitleAllContacts" : "Tüm Ağ Kişileri",
	"friendsMenuTitleMyContacts" : "Ağ Kişilerim",
	"friendsInvitations" : "Davetler",
	"friendsMenuTitleInCommon" : "Ortak Kişiler",
	"friendsShowAllCommonFriends" : "Tümünü göster...",
	"friendsViewAllFriends" : "Tümünü Görüntüle ({0})",
	"friendsSendFriendRequest" : "İstek gönder",
	"friendsNoFriends" : "Bu profille ilişkilendirilen ağ kişisi yok",
	"friendsColleaguesInvite" : "{0} kullanıcısını ağ kişiniz olmaya davet edin",
	"friendsColleaguesFor" : "{0} için Ağ Kişileri",
	"friendsNewInv" : "{0} yeni davet",
	"friendsNewInvs" : "{0} yeni davet",
	"friendsLoading" : "Ağ Yükleniyor...",
	"friendsLoadingInv" : "Davetiyeler yükleniyor...",
	"friendsSelectFriendForRemoval" : "Öncelikle kaldırmak istediğiniz kişileri seçin.",
	"friendsRemoved" : "Ağ kişileri kaldırıldı.",
	"friendsInvSent" : "Önceden beklemede olan bir davet olduğu için yeni davet gönderilmedi.",
	"friendsRemovedSelected" : "Ağımdan Kaldır",
	"friendsSortByDisplayName" : "Ekran Adı",
	"friendsSortByRecent" : "Yeni",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-posta:",
	"friendsAltEmail" : "Diğer E-posta:",
	"friendsNewInvitationsCount" : "{0} yeni davetiniz var",
	"friendsNoInv" : "Davet yok",
	"friendsInCommonSingle" : "Ortak {0} ağ kişiniz var",
	"friendsInCommonMulti" : "Ortak {0} ağ kişiniz var",
	"friendsIncludeMsgForInv" : "Davetinize bir ileti ekleyin:",
	"friendsInitialMsgForInv" : "Sizi Connections ağ kişileri listeme eklemek istiyorum.",
	"friendsSendInvAction" : "Davet Gönder",
	"friendsCancelInvAction" : "İptal",
	"friendsAcceptAction" : "Kabul Et",
	"friendsIgnoreAction" : "Yoksay",
	"friendsYouExceedTextLimit" : "Davet iletiniz çok uzun. Açıklama en fazla {1} karakter uzunluğunda olabilir. Bu alanda {0} karakter var.",
	"friendsCannotAddYourself" : "Kendinizi bir ağ kişisi olarak ekleyemezsiniz.",
	"friendsIsYourColleague" : "{0}, sizin ağ kişiniz",
	"friendsRecentlyAdded" : "Ağınıza yeni eklediğiniz kişiler.",
	"friendsDate" : "Tarih",
	"friendsCollapseWidget" : "Ağ bölümünü daraltmak için tıklatın",
	"friendsExpandWidget" : "Ağ bölümünü genişletmek için tıklatın",
	"friendsIsInYourNetwork" : "{0} ağınızda yer alıyor.",
	"friendsActionsFor" : "Ağa İlişkin Eylemler",
	"friendsInviteFollowError" : "{0} takip edilmeye çalışılırken bir hata oluştu",
	"friendsInviteTagError" : "{0} etiketlenmeye çalışılırken bir hata oluştu",
	"friendsPleaseLogIn" : "Lütfen kişileri ağınıza davet etmek için oturum açın",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0} zaten ağınızda olduğu için, ağınıza davet edilemez.",
	"friendsInviteAddTagsFor" : "{0} için etiket ekle:",
	"friendsInviteAlsoFollow" : "Ayrıca İzle",
	"friendsInviteReceiveUpdates" : "(güncelleştirmeleri al)",
	"friendsInviteUpdatesDescription" : "Giriş Sayfasında ve e-posta özetinde izlediğiniz kişilere ilişkin güncelleştirmeleri alın.",
	"friendsInviteFollowHelp": "Daha fazla bilgi için bkz. {0}Kişileri izleme{1}.",
	"friendsNetwork" : "Ağ",
	"friendsMyNetwork" : "Ağ",
	"friendsNetworkFor" : "{0} için Ağ",
	"friendsRemoveSelected" : "Seçileni Kaldır",
	"friendsRemoveSelectedTip" : "Seçilen kişileri ağınızdan kaldırmak için tıklatın.",
	"friendsNetworkInCommon" : "Ortak {0} ağ bağlantınız var.",
	"friendsAddToMyNetwork" : "Sizi Connections ağıma eklemek istiyorum.",
	"friendsInvite" : "Ağıma Davet Et",
	"friendsInvitePerson" : "{0} kullanıcısını ağınıza davet edin",
	"friendsInviteMessage" : "Sizi Connections ağıma eklemek istiyorum.",
	"friendsInvitedEmailSubject" : "[Profiller] Ağıma katılmak için davet edildiniz",
	"friendsInvitedEmailMsg1" : "davette yer alan aşağıdaki iletiyle sizi ağ kişisi olmaya davet etti:",
	"friendsInvitedEmailMsg2" : "Ağ Davetleri sayfanızı açın",
	"friendsInvitedEmailMsg3" : "Sizi ağıma eklemek istiyorum.",
	"friendsInvitedEmailMsg4" : "{0} sizi bir ağ kişisi olmaya davet etti:",
	"friendsInvitedEmailMsg5" : "{0}, davette yer alan aşağıdaki iletiyle sizi ağ kişisi olmaya davet etti:",
	"friendsInviteLegalNote" : "Bu daveti göndererek, {0} adlı kullanıcının profil panonuzda yorum yapmasına izin verdiğinizi kabul ediyorsunuz.",
	"friendsInviteFailed" : "Bir sunucu hatası nedeniyle, davetliye e-posta bildirimi gönderilmedi. Ancak yine de, davetli, Profiller web uygulaması üzerinden davetinizi kabul edebilir.",
	"personInNetwork" : "Ağ Kişisi"
})
