/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Atualizado por ${author}",
		PREVIEW_MODE_ONLY: "(Modo de visualização apenas)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Comunidade visualizada hoje",
		COMMUNITY_VIEWED_YESTERDAY: "Comunidade visualizada ontem",
		COMMUNITY_VIEWED_HOURS_AGO: "Comunidade visualizada há ${hours} horas",
		COMMUNITY_VIEWED_MINUTES_AGO: "Comunidade visualizada há ${minutes} minutos",
		COMMUNITY_VIEWED_SECONDS_AGO: "Comunidade visualizada há ${seconds} segundos",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Comunidade visualizada há uma hora",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Comunidade visualizada há um minuto",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Comunidade visualizada há um segundo",
		COMMUNITY_VIEWED_AT_DATE: "Comunidade visualizada ${date}",
		//File
		FILE_VIEWED_TODAY: "Arquivo visualizado hoje",
		FILE_VIEWED_YESTERDAY: "Arquivo visualizado ontem",
		FILE_VIEWED_HOURS_AGO: "Arquivo visualizado há ${hours} horas",
		FILE_VIEWED_MINUTES_AGO: "Arquivo visualizado há ${minutes} minutos",
		FILE_VIEWED_SECONDS_AGO: "Arquivo visualizado há ${seconds} segundos",
		FILE_VIEWED_1_HOUR_AGO: "Arquivo visualizado há uma hora",
		FILE_VIEWED_1_MINUTE_AGO: "Arquivo visualizado há um minuto",
		FILE_VIEWED_1_SECOND_AGO: "Arquivo visualizado há um segundo",
		FILE_VIEWED_AT_DATE: "Arquivo visualizado ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Perfil visualizado hoje",
		PROFILE_VIEWED_YESTERDAY: "Perfil visualizado ontem",
		PROFILE_VIEWED_HOURS_AGO: "Perfil visualizado há ${hours} horas",
		PROFILE_VIEWED_MINUTES_AGO: "Perfil visualizado há ${minutes} minutos",
		PROFILE_VIEWED_SECONDS_AGO: "Perfil visualizado há ${seconds} segundos",
		PROFILE_VIEWED_1_HOUR_AGO: "Perfil visualizado há uma hora",
		PROFILE_VIEWED_1_MINUTE_AGO: "Perfil visualizado há um minuto",
		PROFILE_VIEWED_1_SECOND_AGO: "Perfil visualizado há um segundo",
		PROFILE_VIEWED_AT_DATE: "Perfil visualizado ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Atividade visualizada hoje",
		ACTIVITY_VIEWED_YESTERDAY: "Atividade visualizada ontem",
		ACTIVITY_VIEWED_HOURS_AGO: "Atividade visualizada há ${hours} horas",
		ACTIVITY_VIEWED_MINUTES_AGO: "Atividade visualizada há ${minutes} minutos",
		ACTIVITY_VIEWED_SECONDS_AGO: "Atividade visualizada há ${seconds} segundos",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Atividade visualizada há uma hora",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Atividade visualizada há um minuto",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Atividade visualizada há um segundo",
		ACTIVITY_VIEWED_AT_DATE: "Atividade visualizada ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Favorito visualizado hoje",
		BOOKMARK_VIEWED_YESTERDAY: "Favorito visualizado ontem",
		BOOKMARK_VIEWED_HOURS_AGO: "Favorito visualizado há ${hours} horas",
		BOOKMARK_VIEWED_MINUTES_AGO: "Favorito visualizado há ${minutes} minutos",
		BOOKMARK_VIEWED_SECONDS_AGO: "Favorito visualizado há ${seconds} segundos",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Favorito visualizado há uma hora",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Favorito visualizado há um minuto",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Favorito visualizado há um segundo",
		BOOKMARK_VIEWED_AT_DATE: "Favorito visualizado ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Blog visualizado hoje",
		BLOG_VIEWED_YESTERDAY: "Blog visualizado ontem",
		BLOG_VIEWED_HOURS_AGO: "Blog visualizado há ${hours} horas",
		BLOG_VIEWED_MINUTES_AGO: "Blog visualizado há ${minutes} minutos",
		BLOG_VIEWED_SECONDS_AGO: "Blog visualizado há ${seconds} segundos",
		BLOG_VIEWED_1_HOUR_AGO: "Blog visualizado há uma hora",
		BLOG_VIEWED_1_MINUTE_AGO: "Blog visualizado há um minuto",
		BLOG_VIEWED_1_SECOND_AGO: "Blog visualizado há um segundo",
		BLOG_VIEWED_AT_DATE: "Blog visualizado ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Fórum visualizado hoje",
		FORUM_VIEWED_YESTERDAY: "Fórum visualizado ontem",
		FORUM_VIEWED_HOURS_AGO: "Fórum visualizado há ${hours} horas",
		FORUM_VIEWED_MINUTES_AGO: "Fórum visualizado há ${minutes} minutos",
		FORUM_VIEWED_SECONDS_AGO: "Fórum visualizado há ${seconds} segundos",
		FORUM_VIEWED_1_HOUR_AGO: "Fórum visualizado há uma hora",
		FORUM_VIEWED_1_MINUTE_AGO: "Fórum visualizado há um minuto",
		FORUM_VIEWED_1_SECOND_AGO: "Fórum visualizado há um segundo",
		FORUM_VIEWED_AT_DATE: "Fórum visualizado ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Wiki visualizada hoje",
		WIKI_VIEWED_YESTERDAY: "Wiki visualizada ontem",
		WIKI_VIEWED_HOURS_AGO: "Wiki visualizada há ${hours} horas",
		WIKI_VIEWED_MINUTES_AGO: "Wiki visualizada há ${minutes} minutos",
		WIKI_VIEWED_SECONDS_AGO: "Wiki visualizada há ${seconds} segundos",
		WIKI_VIEWED_1_HOUR_AGO: "Wiki visualizada há uma hora",
		WIKI_VIEWED_1_MINUTE_AGO: "Wiki visualizada há um minuto",
		WIKI_VIEWED_1_SECOND_AGO: "Wiki visualizada há um segundo",
		WIKI_VIEWED_AT_DATE: "Wiki visualizada ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Evento visualizado hoje",
		EVENT_VIEWED_YESTERDAY: "Evento visualizado ontem",
		EVENT_VIEWED_HOURS_AGO: "Evento visualizado há ${hours} horas",
		EVENT_VIEWED_MINUTES_AGO: "Evento visualizado há ${minutes} minutos",
		EVENT_VIEWED_SECONDS_AGO: "Evento visualizado há ${seconds} segundos",
		EVENT_VIEWED_1_HOUR_AGO: "Evento visualizado há 1 hora",
		EVENT_VIEWED_1_MINUTE_AGO: "Evento visualizado há 1 minuto",
		EVENT_VIEWED_1_SECOND_AGO: "Evento visualizado há 1 segundo",
		EVENT_VIEWED_AT_DATE: "Evento visualizado ${date}",
		//To Do
		TODO_VIEWED_TODAY: "Tarefas Pendentes visualizadas hoje",
		TODO_VIEWED_YESTERDAY: "Tarefas Pendentes visualizadas ontem",
		TODO_VIEWED_HOURS_AGO: "Tarefas Pendentes visualizadas há ${hours} horas",
		TODO_VIEWED_MINUTES_AGO: "Tarefas Pendentes visualizadas há ${minutes} minutos",
		TODO_VIEWED_SECONDS_AGO: "Tarefas Pendentes visualizadas há ${seconds} segundos",
		TODO_VIEWED_1_HOUR_AGO: "Tarefas Pendentes visualizadas há uma hora",
		TODO_VIEWED_1_MINUTE_AGO: "Tarefas Pendentes visualizadas há um minuto",
		TODO_VIEWED_1_SECOND_AGO: "Tarefas Pendentes visualizadas há um segundo",
		TODO_VIEWED_AT_DATE: "Tarefas Pendentes visualizadas ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "A pesquisa de opinião foi visualizada hoje",
		SURVEY_VIEWED_YESTERDAY: "A pesquisa de opinião foi visualizada ontem",
		SURVEY_VIEWED_HOURS_AGO: "A pesquisa de opinião foi visualizada há ${hours} horas",
		SURVEY_VIEWED_MINUTES_AGO: "A pesquisa de opinião foi visualizada há ${minutes} minutos",
		SURVEY_VIEWED_SECONDS_AGO: "A pesquisa de opinião foi visualizada há ${seconds} segundos",
		SURVEY_VIEWED_1_HOUR_AGO: "A pesquisa de opinião foi visualizada há 1 hora",
		SURVEY_VIEWED_1_MINUTE_AGO: "A pesquisa de opinião foi visualizada há 1 minuto",
		SURVEY_VIEWED_1_SECOND_AGO: "A pesquisa de opinião foi visualizada há 1 segundo",
		SURVEY_VIEWED_AT_DATE: "A pesquisa de opinião foi visualizada em ${date}",
		//Survey
		GENERIC_VIEWED_TODAY: "Visualizado hoje",
		GENERIC_VIEWED_YESTERDAY: "Visualizado ontem",
		GENERIC_VIEWED_HOURS_AGO: "Visualizado há ${hours} horas",
		GENERIC_VIEWED_MINUTES_AGO: "Visualizado há ${minutes} minutos",
		GENERIC_VIEWED_SECONDS_AGO: "Visualizado há ${seconds} segundos",
		GENERIC_VIEWED_1_HOUR_AGO: "Visualizado há 1 hora",
		GENERIC_VIEWED_1_MINUTE_AGO: "Visualizado há 1 minuto",
		GENERIC_VIEWED_1_SECOND_AGO: "Visualizado há 1 segundo",
		GENERIC_VIEWED_AT_DATE: "Visualizado em ${date}"
});

