/* Copyright IBM Corp. 2011, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Кликнете тука за да ја видите визит картата",
	"label.semtag.hover.alt" : "Кликнете за ја видите визит картата за {0}",
	"label.semtag.hover.altA11Y" : "Кликнете тука или притиснете на control-enter за да ја видите визит картата",
	"label.personcard.dialog.title" : "Визит карта за {0}",

	"errorDefaultMsg2" : "Се појави грешка, контактирајте го системскиот администратор",

	"loadingSTStatus" : "Вчитување на статусот на Sametime... ",
	"noStatuAvailable" : "Не е достапен статус на Sametime",

	"label.personcard.cardnomarkup" : "Визит картата не можеше да се пронајде",
	"label.inactive.user.msg" : "Лицето повеќе не е активен корисник",
	"label.message.information" : "Информации:",
	"label.personcard.noprofilemsg" : "Не постои профил за лицето",
	"label.personcard.cardreqexpired" : "Барањето за добивање на визит картата е истечено",

	"label.bizcard.applinks.less" : "Покажи помалку",
	"label.bizcard.applinks.more" : "Покажи повеќе",

	"label.personcard.activitieslink" : "Активности",
	"label.personcard.activitieslink.title" : "Кликнете тука за да видите споделени активности",
	"label.personcard.blogslink" : "Блогови",
	"label.personcard.blogslink.title" : "Кликнете тука за да го видите блогот на лицето",
	"label.personcard.communitieslink" : "Заедници",
	"label.personcard.communitieslink.title" : "Кликнете тука за да ги видите заедниците на лицето",
	"label.personcard.dogearlink" : "Обележувачи",
	"label.personcard.dogearlink.title" : "Кликнете тука за да ги видите обележувачите на лицето",
	"label.personcard.fileslink" : "Датотеки",
	"label.personcard.fileslink.title" : "Кликнете тука за да ги видите споделените датотеки на лицето",
	"label.personcard.forumlink" : "Форуми",
	"label.personcard.forumlink.title" : "Кликнете тука за да ги видите објавите на форуми на лицето",
	"label.personcard.homepagelink" : "Почетна страница",
	"label.personcard.homepagelink.title" : "Кликнете тука за да ја видите почетната страница на лицето",
	"label.personcard.mobilelink" : "Мобилен апарат",
	"label.personcard.mobilelink.title" : "Кликнете тука за да ја видите страницата за мобилен апарат на лицето",
	"label.personcard.newslink" : "Вести",
	"label.personcard.newslink.title" : "Кликнете тука за да ги видите вестите на лицето",
	"label.personcard.profilelink" : "Профил",
	"label.personcard.profilelink.title" : "Кликнете тука за да го видите профилот на лицето",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Кликнете тука за да ги видите споделувањата на quickr на лицето",
	"label.personcard.wikislink" : "Wiki-ја?",
	"label.personcard.wikislink.title" : "Кликнете тука за да ги видите wiki-јата на лицето",

	"personCardMoreActions" : "Повеќе дејства",
	"personCardMoreActionsAltText" : "Кликнете за мени дејства",

	"label.bizcard.dismiss": "Притиснете на escape за да ја отфрлите визит картата.",

	"personCardAddAsColleagues" : "Покани во Моја мрежа",
	"personCardAddAsMyColleagues" : "Покани во Моја мрежа",
	"personCardFollow" : "Следи",
	"personCardUnfollow" : "Престани да следиш",
	"personCardChat" : "Разговор",
	"personCardCall" : "Повик",
	"personCardSendMail" : "Испрати е-пошта",
	"personCardSendEMail" : "Испрати е-пошта",
	"personCardProxyStatusAvailable" : "Достапен сум",
	"personCardDownloadVCard" : "Преземи vCard",

	"friends" : "Мрежа",
	"friendsFullPageTitle" : "Мрежа",
	"friendsMenuTitleAllContacts" : "Сите мрежни контакти",
	"friendsMenuTitleMyContacts" : "Моите мрежни контакти",
	"friendsInvitations" : "Покани",
	"friendsMenuTitleInCommon" : "Заеднички лица",
	"friendsShowAllCommonFriends" : "Покажи ги сите...",
	"friendsViewAllFriends" : "Прикажи ги сите ({0})",
	"friendsSendFriendRequest" : "Испрати барање",
	"friendsNoFriends" : "Нема мрежни контакти кои се поврзани со профилов",
	"friendsColleaguesInvite" : "Поканете го {0} да биде ваш мрежен контакт",
	"friendsColleaguesFor" : "Мрежни контакти за {0}",
	"friendsNewInv" : "{0} нова покана",
	"friendsNewInvs" : "{0} нови покани",
	"friendsLoading" : "Вчитување на мрежата...",
	"friendsLoadingInv" : "Вчитување на поканите...",
	"friendsSelectFriendForRemoval" : "Изберете ги контактите кои сакате да ги отстраните први.",
	"friendsRemoved" : "Отстранет контакт(и).",
	"friendsInvSent" : "Не е испратена ниту една покана бидејќи една покана сè уште чека.",
	"friendsRemovedSelected" : "Отстрани од Моја мрежа",
	"friendsSortByDisplayName" : "Приказ на име",
	"friendsSortByRecent" : "Најнови",
	"friendsTelephone" : "Телефонски број:",
	"friendsEmail" : "Е-пошта:",
	"friendsAltEmail" : "Алтернативна е-пошта:",
	"friendsNewInvitationsCount" : "Имате {0} нови покани.",
	"friendsNoInv" : "Нема покани",
	"friendsInCommonSingle" : "Имате {0} заеднички мрежен контакт",
	"friendsInCommonMulti" : "Имате {0} заеднички мрежни контакти",
	"friendsIncludeMsgForInv" : "Вклучете порака со поканата:",
	"friendsInitialMsgForInv" : "Би сакал да те додадам на мојата листа на контакти во мрежата на Connections.",
	"friendsSendInvAction" : "Испрати покана",
	"friendsCancelInvAction" : "Откажи",
	"friendsAcceptAction" : "Прифати",
	"friendsIgnoreAction" : "Игнорирај",
	"friendsYouExceedTextLimit" : "Пораката за поканување е премногу долга. Може да содржи најмногу {1} карактер. Има {0} карактери во ова поле.",
	"friendsCannotAddYourself" : "Не можете да се додадете себеси како мрежен контакт.",
	"friendsIsYourColleague" : "{0} е ваш мрежен контакт",
	"friendsRecentlyAdded" : "Лица кои неодамна ги имате додадено на вашата мрежа.",
	"friendsDate" : "Датум",
	"friendsCollapseWidget" : "Кликни за да се намали делот на мрежата",
	"friendsExpandWidget" : "Кликни за да се прошири делот на мрежата",
	"friendsIsInYourNetwork" : "{0} е во вашата мрежа.",
	"friendsActionsFor" : "Дејства за мрежа",
	"friendsInviteFollowError" : "Се појави грешка при обидот да го/ја следите {0}",
	"friendsInviteTagError" : "Се појави грешка при обидот да го/ја означите {0}",
	"friendsPleaseLogIn" : "Најавете се за да поканувате лица во вашата мрежа",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Покана за вашата мрежа не е возможна бидејќи {0} веќе е во вашата мрежа.",
	"friendsInviteAddTagsFor" : "Додај ознаки за {0}:",
	"friendsInviteAlsoFollow" : "Исто така следи",
	"friendsInviteReceiveUpdates" : "(добивај новости)",
	"friendsInviteUpdatesDescription" : "Добивајте новости за лицата кои ги следите на Почетната страница и во резимето за е-пошта.",
	"friendsInviteFollowHelp": "За повеќе информации, погледнете, {0}Следење на лица{1}.",
	"friendsNetwork" : "Мрежа",
	"friendsMyNetwork" : "Мрежа",
	"friendsNetworkFor" : "Мрежа за {0}",
	"friendsRemoveSelected" : "Отстрани ги избраните",
	"friendsRemoveSelectedTip" : "Кликнете за да ги отстраните избраните лица од вашата мрежа.",
	"friendsNetworkInCommon" : "Имате {0} заеднички мрежни контакти.",
	"friendsAddToMyNetwork" : "Би сакал да те додадам во мојата мрежа на Connections.",
	"friendsInvite" : "Покани во Моја мрежа",
	"friendsInvitePerson" : "Поканете го {0} во вашата мрежа",
	"friendsInviteMessage" : "Би сакал да те додадам во мојата мрежа на Connections.",
	"friendsInvitedEmailSubject" : "[Профили] Поканети сте да ѝ се приклучите на мојата мрежа",
	"friendsInvitedEmailMsg1" : "ве покани да станете мрежен контакт со следната порака вклучена во поканата:",
	"friendsInvitedEmailMsg2" : "Отворете ја страницата Покана за мрежа",
	"friendsInvitedEmailMsg3" : "Би сакал да те додадам во мојата мрежа.",
	"friendsInvitedEmailMsg4" : "{0} ве покани да станете мрежен контакт:",
	"friendsInvitedEmailMsg5" : "{0} ве покани да станете мрежен контакт со следната порака вклучена во поканата:",
	"friendsInviteLegalNote" : "Со испраќање на пораката, се согласувате да му/ѝ дозволите на {0} да коментира на вашата профилна табла.",
	"friendsInviteFailed" : "Поради грешка на серверот, не му беше испратено известување по е-пошта на поканетото лице. Сепак, поканетото лице сè уште ќе може да ја прифати поканата преку веб-апликацијата Профили."
})

