/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Dodavanje slike",
   newUpload : "Novo otpremanje",
   URL : "URL",
   imageLibrary : "Biblioteka slika",
   description : "Opis:",
   imageFile : "Datoteke:",
   OK: "U redu",
   cancel: "Otkaži",
   required: "Potrebno polje",
   preview: "Pregled:",
   previewWarning: "Izgleda da učitavanje slike nije uspelo, da li ste sigurni da je ovo važeći url slike?",
   alt: "Izmenite tekst:",
   filesTab: "Iz aplikacije Datoteke",
   images:"Slike:",
   browse:"Pregledaj...",
   imagePickerTitle:"Umetni slike iz aplikacije Datoteke",
   componentImagePickerTitle:" ${0} otpremljene slike",
   /* New String for insert image dialog */
   title: "Umetni sliku",
   uploadBtn: "Otpremi sliku",   
   insertBtn: "Umetni sliku",
   uploadTab: "Lokalne datoteke",
   externalTab: "Veb URL",
   internalTab: "Postojeće slike",
   fileFieldTip: "Povucite i pustite slike sa radne površine direktno u ovaj prozor da biste ih otpremili.",
   AdditionalSection: "Dodatne opcije",
   ExpandSection: "Proširi dodatne opcije",
   CloseSection: "Skupi dodatne opcije",
   webURLPrompt: "URL veb slike:",
   previewPrompt: "Oblast pregleda: velikim slikama je možda potrebno više vremena da se prikažu.",
   noExistingImage: "Hopa! Još nije dodata ni jedna slika.",
   selectExistingImage: "Izaberite postojeću sliku:",
   urlMissing: "Unesite URL adresu",
   urlInvalid: "URL adresa nije važeća. Uverite se da unosite važeći URL i pokušajte ponovo.",
   previousItem: "Prethodno",
   nextItem: "Sledeće",
   oneImageOneTime: "Slika je već dodana na ovaj prozor. Slike je moguće dodati samo jednu po jednu.",
   loadingErrorMsg: "Došlo je do greške prilikom učitavanja postojeće slike. Pokušajte ponovo kasnije",
   urlInputTooltip: "Unesite veb URL slike"
})

