/* Copyright IBM Corp. 2011, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Egin klik hemen bisita-txartela ikusteko",
	"label.semtag.hover.alt" : "Egin klik {0}(r)en bisita-txartela ikusteko",
	"label.semtag.hover.altA11Y" : "Egin klik hemen edo sakatu ktrl-sartu bisita-txartela ikusteko.",
	"label.personcard.dialog.title" : "{0}(r)en bisita-txartela",

	"errorDefaultMsg2" : "Errore bat gertatu da; jarri harremanetan zure sistemaren administratzailearekin.",

	"loadingSTStatus" : "Sametime egoera kargatzen...",
	"noStatuAvailable" : "Ez dago Sametime egoerarik erabilgarri",

	"label.personcard.cardnomarkup" : "Ezin izan da bisita-txartela berreskuratu",
	"label.inactive.user.msg" : "Pertsona hau ez da erabiltzaile aktiboa jada",
	"label.message.information" : "Informazioa:",
	"label.personcard.noprofilemsg" : "Ez dago pertsona honentzako profilik",
	"label.personcard.cardreqexpired" : "Bisita-txartela eskuratzeko eskaeraren epea amaitu da",

	"label.bizcard.applinks.less" : "Erakutsi gutxiago",
	"label.bizcard.applinks.more" : "Erakutsi gehiago",

	"label.personcard.activitieslink" : "Jarduerak",
	"label.personcard.activitieslink.title" : "Egin klik hemen partekatutako jarduerak ikusteko",
	"label.personcard.blogslink" : "Blogak",
	"label.personcard.blogslink.title" : "Egin klik hemen pertsona honen bloga ikusteko",
	"label.personcard.communitieslink" : "Komunitateak",
	"label.personcard.communitieslink.title" : "Egin klik hemen pertsona honen komunitateak ikusteko",
	"label.personcard.dogearlink" : "Laster-markak",
	"label.personcard.dogearlink.title" : "Egin klik hemen pertsona honen laster-markak ikusteko",
	"label.personcard.fileslink" : "Fitxategiak",
	"label.personcard.fileslink.title" : "Egin klik hemen pertsona honen partekatutako fitxategiak ikusteko",
	"label.personcard.forumlink" : "Foroak",
	"label.personcard.forumlink.title" : "Egin klik hemen pertsona honen foro-mezuak ikusteko",
	"label.personcard.homepagelink" : "Hasierako orria",
	"label.personcard.homepagelink.title" : "Egin klik hemen pertsona honen hasierako orria ikusteko",
	"label.personcard.mobilelink" : "Mugikorra",
	"label.personcard.mobilelink.title" : "Egin klik hemen pertsona honen mugikorrerako orria ikusteko",
	"label.personcard.newslink" : "Berriak",
	"label.personcard.newslink.title" : "Egin klik hemen pertsona honen berriak ikusteko",
	"label.personcard.profilelink" : "Profila",
	"label.personcard.profilelink.title" : "Egin klik hemen pertsona honen profila ikusteko",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Egin klik hemen pertsona honen quickr partekatzeak ikusteko",
	"label.personcard.wikislink" : "Wikiak",
	"label.personcard.wikislink.title" : "Egin klik hemen pertsona honen wikiak ikusteko",

	"personCardMoreActions" : "Ekintza gehiago",
	"personCardMoreActionsAltText" : "Egin klik ekintzen menua ikusteko",

	"label.bizcard.dismiss": "Sakatu ihes bisita-txartel hau baztertzeko.",

	"personCardAddAsColleagues" : "Gonbidatu nire sarera",
	"personCardAddAsMyColleagues" : "Gonbidatu nire sarera",
	"personCardFollow" : "Jarraitu",
	"personCardUnfollow" : "Utzi jarraitzeari",
	"personCardChat" : "Txata",
	"personCardCall" : "Deitu",
	"personCardSendMail" : "Bidali mezu elektronikoa",
	"personCardSendEMail" : "Bidali mezu elektronikoa",
	"personCardProxyStatusAvailable" : "Libre nago",
	"personCardDownloadVCard" : "Deskargatu vCard",

	"friends" : "Sarea",
	"friendsFullPageTitle" : "Sarea",
	"friendsMenuTitleAllContacts" : "Sareko kontaktu guztiak",
	"friendsMenuTitleMyContacts" : "Nire sareko kontaktuak",
	"friendsInvitations" : "Gonbidapenak",
	"friendsMenuTitleInCommon" : "Amankomuneko jendea",
	"friendsShowAllCommonFriends" : "Erakutsi guztiak...",
	"friendsViewAllFriends" : "Ikusi guztiak ({0})",
	"friendsSendFriendRequest" : "Bidali eskaera",
	"friendsNoFriends" : "Ez dago profil honi lotutako sareko kontakturik",
	"friendsColleaguesInvite" : "Gonbidatu {0} zure sareko kontaktu izatera",
	"friendsColleaguesFor" : "{0}(e)ko sareko kontaktuak",
	"friendsNewInv" : "Gonbidapen berri {0}",
	"friendsNewInvs" : "{0} gonbidapen berri",
	"friendsLoading" : "Sarea kargatzen...",
	"friendsLoadingInv" : "Gonbidapenak kargatzen...",
	"friendsSelectFriendForRemoval" : "Hautatu lehenbizi kendu nahi dituzun kontaktuak.",
	"friendsRemoved" : "Sareko kontaktua(k) kendu dira.",
	"friendsInvSent" : "Ez da gonbidapenik bidali beste bat dagoelako zain.",
	"friendsRemovedSelected" : "Kendu nire saretik",
	"friendsSortByDisplayName" : "Bistaratu izena",
	"friendsSortByRecent" : "Duela gutxikoak",
	"friendsTelephone" : "Telefonoa:",
	"friendsEmail" : "Helbide elektronikoa:",
	"friendsAltEmail" : "Ordezko helbide elektronikoa:",
	"friendsNewInvitationsCount" : "{0} gonbidapen berri d(it)uzu.",
	"friendsNoInv" : "Ez dago gonbidapenik",
	"friendsInCommonSingle" : "Sareko kontaktu {0} duzue amankomunean",
	"friendsInCommonMulti" : "Sareko {0} kontaktu dituzue amankomunean",
	"friendsIncludeMsgForInv" : "Erantsi mezu bat gonbidapenari:",
	"friendsInitialMsgForInv" : "Connections-eko nire sareko kontaktuen zerrendan gehitu nahi zaitut.",
	"friendsSendInvAction" : "Bidali gonbidapena",
	"friendsCancelInvAction" : "Utzi",
	"friendsAcceptAction" : "Onartu",
	"friendsIgnoreAction" : "Baztertu",
	"friendsYouExceedTextLimit" : "Zure gonbidapen-mezua luzeegia da. Gehienez {1} karaktere izan ditzake. {0} karaktere daude eremu honetan.",
	"friendsCannotAddYourself" : "Ezin duzu sareko kontaktu gisa zure burua gehitu.",
	"friendsIsYourColleague" : "{0} zure sareko kontaktua da",
	"friendsRecentlyAdded" : "Zure sareari duela gutxi gehitutako jendea.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Egin klik sarearen sekzioa tolesteko",
	"friendsExpandWidget" : "Egin klik sarearen sekzioa zabaltzeko",
	"friendsIsInYourNetwork" : "{0} zure sarean dago.",
	"friendsActionsFor" : "Sarerako ekintzak",
	"friendsInviteFollowError" : "Errore bat gertatu da {0} jarraitzen saiatzean",
	"friendsInviteTagError" : "Errore bat gertatu da {0} etiketatzen saiatzean",
	"friendsPleaseLogIn" : "Hasi saioa jendea zure sarera gonbidatzeko",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Ezin da zure sarera gonbidapena burutu, {0} zure sarean baitago jada.",
	"friendsInviteAddTagsFor" : "Esleitu etiketak {0}(r)i:",
	"friendsInviteAlsoFollow" : "Halaber, jarraitu",
	"friendsInviteReceiveUpdates" : "(jaso eguneratzeak)",
	"friendsInviteUpdatesDescription" : "Jaso jarraitutako pertsonei buruzko eguneratzeak hasierako orrian eta posta elektroniko bidezko mezuetan.",
	"friendsInviteFollowHelp": "Informazio gehiago eskuratzeko, ikusi {0}Jarraitutako jendea{1}.",
	"friendsNetwork" : "Sarea",
	"friendsMyNetwork" : "Sarea",
	"friendsNetworkFor" : "{0}(r)entzako sarea",
	"friendsRemoveSelected" : "Kendu hautatutakoak",
	"friendsRemoveSelectedTip" : "Egin klik hautatutako jendea zure saretik kentzeko.",
	"friendsNetworkInCommon" : "{0} sare-konexio dituzue amankomunean.",
	"friendsAddToMyNetwork" : "Connections-eko nire sarean gehitu nahi zaitut.",
	"friendsInvite" : "Gonbidatu nire sarera",
	"friendsInvitePerson" : "Gonbidatu {0} zure sarera",
	"friendsInviteMessage" : "Connections-eko nire sarean gehitu nahi zaitut.",
	"friendsInvitedEmailSubject" : "[Profilak] Nire sarearekin bat egitera gonbidatuta zaude",
	"friendsInvitedEmailMsg1" : "(e)k sareko kontaktu izatera gonbidatu zaitu hurrengo mezuarekin:",
	"friendsInvitedEmailMsg2" : "Ireki zure sareko gonbidapen-orria",
	"friendsInvitedEmailMsg3" : "Nire sarean gehitu nahi zaitut.",
	"friendsInvitedEmailMsg4" : "{0}(e)k sareko kontaktu izatera gonbidatu zaitu:",
	"friendsInvitedEmailMsg5" : "{0}(e)k sareko kontaktu izatera gonbidatu zaitu hurrengo mezuarekin:",
	"friendsInviteLegalNote" : "Gonbidapen hau bidaliz gero, {0}(e)k zure profilaren panelean iruzkinak idaztea baimenduko duzu.",
	"friendsInviteFailed" : "Zerbitzariaren errore bat dela eta, ez zaio gonbidatuari jakinarazpen-mezua bidali. Halere, gonbidatuak zure gonbidapena onartu ahal izango du Profilak web-aplikazioaren bidez."
})

