/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "节点的信息： ",
	"INSTALLED": "正在检查已安装的服务",
	"RESUMETOKENS": "正在检查恢复标记",
	"SEEDLISTS": "正在检查种子列表是否可用",
	"CALENDARS": "正在检查是否已正确配置调度日历",
	"VARIABLES": "正在检查是否已设置 WebSphere 变量",
	"TASKS": "正在检查已启用的索引任务",
	"INDEXFILES": "正在检查所需文件的索引文件夹",
	"LOGS": "正在复审日志以获取关于错误的信息",
	"CONFIGFILES": "正在复审配置文件",
	"DICTIONARIES": "正在检查已启用的字典数",
	"SYNC": "正在检查节点状态",
	"DBRECORDS": "正在检查数据库记录",
	"INSTALLEDMSG": "已安装以下服务： ",
	"RESUMETOKENSMSG": "以下内容的恢复标记： ",
	"SEEDLISTSMSG": "无法为以下内容获取种子列表： ",
	"CALENDARSMSG": "已通过调度日历检查： ",
	"VARIABLESMSG": "变量： ",
	"TASKSMSG": "已启用以下任务： ",
	"INDEXFILESMSG" : "以下文件在搜索索引文件夹中： ",
	"LOGSMSG" : "复审以下错误消息： ",
	"CONFIGFILESMSG" : "已找到以下配置文件： ",
	"DICTIONARIESMSG" : "已启用的字典为： ",
	"INSYNC": "所有节点都处于同步状态",
	"OUTOFSYNC": "不同步的节点数为： ",
	"NOTBLOCKED": "未阻塞任何节点",
	"BLOCKED": "阻塞的节点数为： ",
	"INDATE": "所有节点都在有效期内",
	"OUTOFDATE": "过期的节点数为： ",
	"NUMOFDOCS": "数据库中的文档数为 ",
	"FILESTOCONVERT": "要转换的文件文档数为 ",
	"CONVERTEDFILES": "已转换的文件数 ",
	"TOTALFILES": "数据库中的文件总数 ",
	"ERROR":"错误",
	"ERROR_PREFIX":"错误：",
	"INFO":"信息",
	"INFO_PREFIX":"信息：",
	"WARNING":"警告",
	"WARNING_PREFIX":"警告：",
	"LOADING_MESSAGE": "正在装入",
	"SERVER_STATUS": "服务器状态",
	"INITIAL_INDEXING_EXCEPTIONS": "初始索引建议异常",
	"SYS_OUT_EXCEPTIONS": "SystemOut 日志异常",
	"SEEDLIST_VALIDATE": "种子列表验证",
	"ERRORS_DURING_INITIAL_INDEXING":"创建初始索引时发生以下异常",
	"CRAWL_FAILED": "无法搜寻以下服务的所有数据： ",
	"EXCEPTION_ENCOUNTERED": "搜寻失败，返回以下消息： ",
	"SAND_VALIDATE": "SAND 验证",
	"CHECK_FOR_SAND_FILES":"正在检查 SAND 文件",
	"IS_FILE_AVAILABLE":"正在检查是否已创建文件： ",
	"ERRORS_DURING_INITIAL_INDEXING":"创建初始索引时发生以下异常",
	"CRAWL_FAILED":"无法搜寻以下服务的所有数据： ",
	"EXCEPTION_ENCOUNTERED":"搜寻失败，返回以下消息： "
})

