/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"过滤条件：",
"SHOW":"显示：",
"ACL_FILTER_LABEL":"按可视性过滤",
"PARENT_FILTER_LABEL":"按容器过滤",
"TYPE_FILTER_LABEL":"按类型过滤",
"PAGING_TOP":"主要页面调度",
"PAGING_BOTTOM":"辅助页面调度",
"PREVIOUS":"上一页",
"NEXT":"下一页",
"PAGE":"第 {0} 页（共 {1} 页）",
"PAGE_COLON":"页码：",
"RESULTS":"{span}{0} - {1}{/span}/{2}",
"ITEMS":"{0} 个项目",
/* Application names */
"ACTIVITIES":"活动",
"BLOGS":"博客",
"CALENDAR":"日历",
"COMMUNITIES":"社区",
"BOOKMARKS":"书签",
"DOGEAR":"书签",
"EVENTS":"事件",
"FILES":"文件",
"FORUMS":"论坛",
"PROFILES":"个人档案",
"WIKI":"Wiki",
"WIKIS":"Wiki",
"FEEDS":"订阅源",
"STATUS_UPDATES":"状态更新",
"ONECOMMENT":"1 条评论",
"COMMENTS":"{0} 条评论",
"ONEPERSON":"1 人",
"PEOPLE":"{0} 人",
"TAGS":"标签：",
"TAGSMORE":"以及 {0} 个以上",
"NORESULTSMESSAGE":"此搜索找不到任何结果",
"JAN":"一月",
"FEB":"二月",
"MAR":"三月",
"APR":"四月",
"MAY":"五月",
"JUN":"六月",
"JUL":"七月",
"AUG":"八月",
"SEP":"九月",
"OCT":"十月",
"NOV":"十一月",
"DEC":"十二月",
"NO_CONTACT":"因为无法联系服务器，所以未执行搜索",
"SERVER_ERROR":"由于服务器错误，因此未执行搜索",
"SORT_BY":"排序依据：",
"SORT_RELEVANCE":"相关性",
"SORT_DATE":"日期",
"SORT_LAST_UPDATED":"上次更新时间",
"SORT_DUE_DATE":"到期日期",
"SORT_VISITS":"访问次数",
"SORT_COMMENTS":"评论",
"SORT_RECOMMENDATION":"点赞数",
"SORT_POPULARITY":"热门程度",
"SORT_FIRSTNAME":"名字",
"SORT_LASTNAME":"姓氏",
"SORT_DOWNLOADS":"下载次数",
"SORT_TYPE":"类型",
"SORT_SIZE":"大小",
"SORT_TITLE":"标题",
"PRIVATE":"私有",
"MODERATED":"需审核",
"COMMUNITY_ACTIVITY":"社区活动",
"COMMUNITY_BLOG":"社区博客",
"COMMUNITY_FILE":"社区文件",
"COMMUNITY_FORUM":"社区论坛",
"COMMUNITY_WIKI":"社区 Wiki",
"COMMUNITY_FEED":"社区订阅源",
"COMMUNITY_BOOKMARK":"社区书签",
"NO_TAG":"尚无标签",
"NO_DATE":"尚无日期",
"NO_PEOPLE":"尚无人员",
"REMOVE_FILTER_LABEL":"单击以除去",
"REMOVE_FILTER_TITLE":"除去",
"REMOVE_FILTER_TOOLTIP":"除去此过滤条件",
"COMMENT_ON":"评论：",
"EXPAND_COLLAPSE":"单击以展开/折叠",
"EXPAND":"展开",
"COLLAPSE":"折叠",
"EXPAND_MONTHS_FILTER":"展开年份 {0} 的月份过滤器",
"SORT_RELEVANCE_LABEL":"单击以按相关性排序",
"SORT_DATE_LABEL":"单击此项按日期排序",
"SORT_UPDATED_LABEL":"单击此项按上次更新时间排序",
"SORT_DUE_LABEL":"单击此项按到期日期排序",
"SORT_VISITS_LABEL":"单击此项按访问数排序",
"SORT_COMMENTS_LABEL":"单击此项按评论数排序",
"SORT_RECOMMENDATIONS_LABEL":"单击此项按点赞次数进行排序",
"SORT_POPULARITY_LABEL":"单击此项按热门程度排序",
"SORT_FIRST_NAME_LABEL":"单击此项按名字排序",
"SORT_LAST_NAME_LABEL":"单击此项按姓氏排序",
"RATING":"点赞数",
"GRADUATED":"已采纳",
"ONEVOTE":"1 张投票",
"VOTES":"{0} 张投票",
"BOOKMARK_THIS_RESULT":"为页面设置书签",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0}（未激活）",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"已为 {0} 人设置书签",
/* eg from an Activity */
"FROMANACTIVITY":"来自“活动”",
"FROMABLOG":"来自“博客”",
"FROMANIDEATIONBLOG":"来自构想博客",
"FROMANEVENT":"来自“事件”",
"FROMAFORUM":"来自“论坛”",
"FROMAWIKI":"来自 Wiki",
"FROMACOMMUNITY":"来自“社区”",
"FROMXCOMMUNITIES":"来自 {0} 社区",
/* For search results parentage */
"ACTIVITY_ALONE":"活动",
"BLOG_ALONE":"博客",
"IDEATIONBLOG_ALONE":"构想博客",
"ENTRY_ALONE":"条目",
"EVENT_ALONE":"事件",
"FORUM_ALONE":"论坛",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"社区",
"XCOMMUNITIES_ALONE":"{0} 社区",
"SHAREDCOMMUNITIES":"与这些社区共享",
"INACOMMUNITY":"位于“社区”中",
"LASTUPDATED":"搜索索引最近更新：",
"NODESCRIPTION":"此结果没有描述或摘要。",
"ATTACHMENT":"附件：",
"ACTIVITY":"活动：",
"ACTIVITYBOOKMARK":"活动书签：",
"ACTIVITYCOMMENT":"活动评论：",
"ACTIVITYENTRY":"活动条目",
"ACTIVITYSECTION":"活动区段：",
"ACTIVITYTODO":"活动待办事宜：",
"BLOG":"博客：",
"BLOGENTRY":"博客条目：",
"BLOGCOMMENT":"博客评论：",
"BOOKMARK":"书签：",
"CALENDAREVENT":"事件：",
"CATEGORY":"类别：",
"COMMENT":"评论：",
"COMMUNITY":"社区：",
"ENTRY":"条目：",
"EVENTDATEON":"关于：{0}",
"EVENTISALLDAY":"全天事件",
"EVENTREPEATS":"重复频率",
"FEED":"订阅源：",
"FILE":"文件：",
"FORUM":"论坛：",
"FORUMCATEGORY":"论坛类别：",
"FORUMTOPIC":"论坛主题：",
"IDEA":"构想：",
"IDEACOMMENT":"构想评论：",
"IDEATIONBLOG":"构想博客：",
"PAGE":"页码：",
"PROFILE":"个人档案：",
"SECTION":"区段：",
"STATUSUPDATE":"状态更新",
"STATUSUPDATE_PREFIX":"状态更新：",
"TOPIC":"主题：",
"TOPIC_WITH_ATTACHMENT":"主题",
"WIKITYPE":"Wiki：",
"WIKIPAGE":"Wiki 页面：",
"WIKIFILE":"Wiki 附件：",
"SEARCH":"搜索：",
"TODO":"待办事宜：",
"ALLRESULTS":"所有结果",
"PUBLICCONTENT":"公共内容",
"MYCONTENT":"我的内容",
"RESULTNOTFOUND":"未找到您要找的内容？",
"TEMPDIFFICULTIES":"注：由于临时建立索引有困难，因此搜索结果不包含最近 {1} 天内更改的 {0}。",
"TRYLATER":"请稍后重试。",
"MULTIPLETEMPDIFFICULTIES":"注：由于临时建立索引有困难，因此搜索结果不包含最近更改的 {0}",
"YOUAREAUTHOR":"您是作者",
"YOUARECONTRIBUTOR":"您是内容添加者",
"YOUAREOWNER":"您是所有者",
"YOUAREMEMBER":"您是成员",
/* Profiles */
"MYNETWORK":"我的网络",
"ALLPEOPLE":"所有人员",
"EXCLUDEINACTIVE":"排除未激活人员",
"PHONE":"电话：",
"EMAIL":"电子邮件地址：",
/* Communities */
"ALLCOMMUNITIES":"所有社区",
"PUBLICCOMMUNITIES":"公共社区",
"MYCOMMUNITIES":"我的社区",
"EVERYTHINGCOMMUNITIES":"社区的所有内容",
"COMMUNITIESONLY":"社区",
"COMMUNITIESCONTENT":"来自社区的内容",
/* Activities */
"ALLACTIVITIES":"所有活动",
"PUBLICACTIVITIES":"公共活动",
"MYACTIVITIES":"我的活动",
"EVERYTHINGACTIVITIES":"活动的所有内容",
"ACTIVITIESONLY":"活动",
"SECTIONSACTIVITIES": "来自活动的区段",
"ENTRIESACTIVITIES":"来自活动的条目",
"TODOSACTIVITIES":"来自活动的待办事宜",
"BOOKMARKSACTIVITIES":"来自活动的书签",
"FILESACTIVITIES":"活动的附件",
"ALLTYPESACTIVITIES":"所有类型的活动",
"COMMUNITYACTIVITIES":"来自社区的活动",
"STANDALONEACTIVITIES":"单机活动",
/* Forums */
"ALLFORUMS":"所有论坛",
"PUBLICFORUMS":"公共论坛",
"MYFORUMS":"我的论坛",
"EVERYTHINGFORUMS":"论坛的所有内容",
"FORUMSONLY":"论坛",
"TOPICSFORUMS":"论坛主题",
"FORUMCATEGORIES": "论坛类别",
"FILESFORUMS":"论坛的附件",
"ALLTYPESFORUMS":"所有类型的论坛",
"COMMUNITYFORUMS":"来自社区的论坛",
"STANDALONEFORUMS":"单机论坛",
/* Blogs */
"ALLBLOGS":"所有博客",
"PUBLICBLOGS":"公共博客",
"MYBLOGS":"我的博客",
"EVERYTHINGBLOGS":"博客的所有内容",
"BLOGSONLY":"博客",
"ENTRIESBLOGS":"博客条目",
"FILESBLOGS":"博客的附件",
"EVERYTHINGIDEATIONBLOGS":"构想博客的所有内容",
"BLOGSIDEATIONBLOGS":"构想博客",
"BLOGSIDEAS":"构想",
"ALLTYPESBLOGS":"所有类型的博客",
"COMMUNITYBLOGS":"来自社区的博客",
"COMMUNITYIDEATIONBLOGS":"来自社区的构想博客",
"STANDALONEBLOGS":"单机博客",
/* Bookmarks */
"ALLBOOKMARKS":"所有书签",
"PUBLICBOOKMARKS":"公共书签",
"MYBOOKMARKS":"我的书签",
"ALLTYPESBOOKMARKS":"所有类型的书签",
"COMMUNITYBOOKMARKS":"来自社区的书签",
"STANDALONEBOOKMARKS":"单机书签",
/* Files */
"ALLFILES":"所有文件",
"PUBLICFILES":"公共文件",
"MYFILES":"我的文件",
"ALLTYPESFILES":"所有类型的文件",
"COMMUNITYFILES":"来自社区的文件",
"STANDALONEFILES":"单机文件",
"NUMDOWNLOADS":"下载 {0} 次",
/* Wikis */
"ALLWIKIS":"全部 Wiki",
"PUBLICWIKIS":"公共 Wiki",
"MYWIKIS":"我的 Wiki",
"EVERYTHINGWIKIS":"Wiki 的所有内容",
"WIKISONLY":"Wiki",
"PAGESWIKIS":"Wiki 页面",
"FILESWIKIS":"Wiki 的附件",
"ALLTYPESWIKIS":"所有类型的 Wiki",
"COMMUNITYWIKIS":"来自社区的 Wiki",
"STANDALONEWIKIS":"单机 Wiki",
/* Status Updates */
"ALLSTATUSUPDATES":"所有状态更新",
"PUBLICSTATUSUPDATES":"公共状态更新",
"MYSTATUSUPDATES":"我的状态更新",
"ALLTYPESSTATUSUPDATES":"所有类型的状态更新",
"COMMUNITYSTATUSUPDATES":"来自社区的状态更新",
"STANDALONESTATUSUPDATES":"来自个人档案的状态更新",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"此 URL 已被多个用户标记为书签",
"BOOKMARKEDCOMMUNITY":"此社区已被多个用户标记为书签",
"BOOKMARKEDPROFILE":"该个人档案已被多个用户标记为书签",
"BOOKMARKEDBLOG":"该博客已被多个用户标记为书签",
"COMMUNITYBLOG":"此为社区中的博客",
"BOOKMARKEDACTIVITY":"该活动已被多个用户标记为书签",
"COMMUNITYACTIVITY":"此为社区中的活动",
"BOOKMARKEDFILE":"该文件已被多个用户标记为书签",
"COMMUNITYFILE":"此为社区中的文件",
"BOOKMARKED":"该 Wiki 已被多个用户标记为书签",
"COMMUNITYWIKI":"此为社区中的 Wiki",
"BOOKMARKEDFORUM":"该论坛已被多个用户标记为书签",
"COMMUNITYFORUM":"此为社区中的论坛",
"ALLTAGANDTTILE":"要查看此 URL 的所有标题和标签，单击此按钮",
"TAGS_ARE_FROM":"此搜索结果可能包含来自以下来源的标签：",
"BOOKMARKS_TITLE":"书签",
"COMMUNITIES_TITLE":"社区",
"ACTIVITIES_TITLE":"活动",
"HELP":"帮助",
"MORESTATUSUPDATES":"查看更多状态更新匹配项",
"TITLE_PREFIX":"标题：",
"LATEST_MESSAGE":"最新消息",
"LATEST_STATUS_UPDATE":"最新状态更新",
"LATEST_COMMUNITY_STATUS_UPDATE":"最新社区状态更新",
"LATEST_COMMUNITIES_STATUS_UPDATE":"最新社区状态更新",
"SEARCH_RESULTS":"所有内容搜索结果",
"ACTIVITIES_SEARCH_RESULTS":"活动搜索结果",
"BLOGS_SEARCH_RESULTS":"博客搜索结果",
"BOOKMARKS_SEARCH_RESULTS":"书签搜索结果",
"COMMUNITIES_SEARCH_RESULTS":"社区搜索结果",
"FILES_SEARCH_RESULTS":"文件搜索结果",
"FORUMS_SEARCH_RESULTS":"论坛搜索结果",
"PROFILES_SEARCH_RESULTS":"个人档案搜索结果",
"DIRECTORY_SEARCH_RESULTS":"${orgName} 目录搜索结果",
"WIKIS_SEARCH_RESULTS":"Wiki 搜索结果",
"STATUS_UPDATES_SEARCH_RESULTS":"状态更新搜索结果",
"VIEW_ALL":"{span}查看全部{/span} ({0})",
"MATCHING_ONE_OF":"匹配下列其中一项：",
"MATCHING_ALL_OF":"匹配下列全部：",
"MATCHING":"匹配项：",
"MATCHING_DOC_TYPE":"匹配的文档类型：",
"BOOKMARK_HELP":"“书签”帮助",
"CLOSE_BOOKMARK_HELP":"关闭“书签”帮助",
"DOCUMENT_TYPE_PREFIX":"文档类型：",
"FILE_PREVIEW_ONLY":"（仅限预览方式）"
})

