/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Information for node: ",
	"INSTALLED": "Checking the installed services",
	"RESUMETOKENS": "Checking the resume tokens",
	"SEEDLISTS": "Checking that the seedlists are available",
	"CALENDARS": "Checking that the schedule calendars have been configured correctly",
	"VARIABLES": "Checking that the WebSphere variables have been set",
	"TASKS": "Checking for enabled indexing tasks",
	"INDEXFILES": "Checking the index folder for required files",
	"LOGS": "Reviewing the logs for errors",
	"CONFIGFILES": "Reviewing the configuration files",
	"DICTIONARIES": "Checking the number of dictionaries that have been enabled",
	"SYNC": "Checking the status of the nodes",
	"DBRECORDS": "Checking the database records",
	"INSTALLEDMSG": "The following service is installed: ",
	"RESUMETOKENSMSG": "The resume token for: ",
	"SEEDLISTSMSG": "The seedlist could not be obtained for: ",
	"CALENDARSMSG": "Schedule calendar check passed: ",
	"VARIABLESMSG": "Variable: ",
	"TASKSMSG": "The following task is enabled: ",
	"INDEXFILESMSG" : "The following files are in the search index folder: ",
	"LOGSMSG" : "Review the following error messages: ",
	"CONFIGFILESMSG" : "The following configuration files have been found: ",
	"DICTIONARIESMSG" : "The number of dictionaries enabled is: ",
	"INSYNC": "All nodes are in sync",
	"OUTOFSYNC": "The number of nodes out of sync is: ",
	"NOTBLOCKED": "No nodes are blocked",
	"BLOCKED": "The number of blocked nodes is: ",
	"INDATE": "All the nodes are in date",
	"OUTOFDATE": "The number of nodes out of date is: ",
	"NUMOFDOCS": "The number of documents in the database is ",
	"FILESTOCONVERT": "The number of file documents to convert is ",
	"CONVERTEDFILES": "The number of files converted is ",
	"TOTALFILES": "The total number of files in the database ",
	"ERROR":"Error",
	"ERROR_PREFIX":"Error:",
	"INFO":"Information",
	"INFO_PREFIX":"Information:",
	"WARNING":"Warning",
	"WARNING_PREFIX":"Warning:",
	"LOADING_MESSAGE": "Loading",
	"SERVER_STATUS": "Server Status",
	"INITIAL_INDEXING_EXCEPTIONS": "Initial Indexing Exceptions",
	"SYS_OUT_EXCEPTIONS": "SystemOut Log Exceptions",
	"SEEDLIST_VALIDATE": "Seedlists Validation",
	"ERRORS_DURING_INITIAL_INDEXING":"The following exceptions occurred while creating an initial index",
	"CRAWL_FAILED": "All the data for the following service could not be crawled: ",
	"EXCEPTION_ENCOUNTERED": "The crawl failed with the following message: ",
	"SAND_VALIDATE": "SAND Validation",
	"CHECK_FOR_SAND_FILES":"Checking for the SAND files",
	"IS_FILE_AVAILABLE":"Checking that the file has been created: ",
	"ERRORS_DURING_INITIAL_INDEXING":"The following exceptions occurred while creating an initial index",
	"CRAWL_FAILED":"All the data for the following service could not be crawled: ",
	"EXCEPTION_ENCOUNTERED":"The crawl failed with the following message: "
})
