/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filter by:",
"SHOW":"Show:",
"ACL_FILTER_LABEL":"Filter by visibility",
"PARENT_FILTER_LABEL":"Filter by container",
"TYPE_FILTER_LABEL":"Filter by type",
"PAGING_TOP":"Primary paging",
"PAGING_BOTTOM":"Secondary paging",
"PREVIOUS":"Previous",
"NEXT":"Next",
"PAGE":"Page {0} of {1}",
"PAGE_COLON":"Page:",
"RESULTS":"{span}{0}-{1}{/span} of {2}",
"ITEMS":"{0} items",
/* Application names */
"ACTIVITIES":"Activities",
"BLOGS":"Blogs",
"CALENDAR":"Calendar",
"COMMUNITIES":"Communities",
"BOOKMARKS":"Bookmarks",
"DOGEAR":"Bookmarks",
"EVENTS":"Events",
"FILES":"Files",
"FORUMS":"Forums",
"PROFILES":"Profiles",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Feeds",
"STATUS_UPDATES":"Status Updates",
"ONECOMMENT":"1 comment",
"COMMENTS":"{0} comments",
"ONEPERSON":"1 Person",
"PEOPLE":"{0} People",
"TAGS":"Tags:",
"TAGSMORE":"and {0} more",
"NORESULTSMESSAGE":"No results were found for that search",
"JAN":"January",
"FEB":"February",
"MAR":"March",
"APR":"April",
"MAY":"May",
"JUN":"June",
"JUL":"July",
"AUG":"August",
"SEP":"September",
"OCT":"October",
"NOV":"November",
"DEC":"December",
"NO_CONTACT":"The search was not performed because the server could not be contacted",
"SERVER_ERROR":"The search was not performed due to a server error",
"SORT_BY":"Sort by:",
"SORT_RELEVANCE":"Relevance",
"SORT_DATE":"Date",
"SORT_LAST_UPDATED":"Last Updated",
"SORT_DUE_DATE":"Due Date",
"SORT_VISITS":"Visits",
"SORT_COMMENTS":"Comments",
"SORT_RECOMMENDATION":"Likes",
"SORT_POPULARITY":"Popularity",
"SORT_FIRSTNAME":"First Name",
"SORT_LASTNAME":"Last Name",
"SORT_DOWNLOADS":"Downloads",
"SORT_TYPE":"Type",
"SORT_SIZE":"Size",
"SORT_TITLE":"Title",
"PRIVATE":"Private",
"MODERATED":"Moderated",
"COMMUNITY_ACTIVITY":"Community Activity",
"COMMUNITY_BLOG":"Community Blog",
"COMMUNITY_FILE":"Community File",
"COMMUNITY_FORUM":"Community Forum",
"COMMUNITY_WIKI":"Community Wiki",
"COMMUNITY_FEED":"Community Feed",
"COMMUNITY_BOOKMARK":"Community Bookmark",
"NO_TAG":"No tags yet",
"NO_DATE":"No dates yet",
"NO_PEOPLE":"No people yet",
"REMOVE_FILTER_LABEL":"Click to remove",
"REMOVE_FILTER_TITLE":"Remove",
"REMOVE_FILTER_TOOLTIP":"Remove this filter",
"COMMENT_ON":"Comment on:",
"EXPAND_COLLAPSE":"Click to expand / collapse",
"EXPAND":"Expand",
"COLLAPSE":"Collapse",
"EXPAND_MONTHS_FILTER":"Expand the months filter of year {0}",
"SORT_RELEVANCE_LABEL":"Click to sort by relevance",
"SORT_DATE_LABEL":"Click to sort by date",
"SORT_UPDATED_LABEL":"Click to sort by last updated",
"SORT_DUE_LABEL":"Click to sort by due date",
"SORT_VISITS_LABEL":"Click to sort by number of visits",
"SORT_COMMENTS_LABEL":"Click to sort by number of comments",
"SORT_RECOMMENDATIONS_LABEL":"Click to sort by number of likes",
"SORT_POPULARITY_LABEL":"Click to sort by popularity",
"SORT_FIRST_NAME_LABEL":"Click to sort by given name",
"SORT_LAST_NAME_LABEL":"Click to sort by last name",
"RATING":"Likes",
"GRADUATED":"Graduated",
"ONEVOTE":"1 vote",
"VOTES":"{0} votes",
"BOOKMARK_THIS_RESULT":"Bookmark this",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inactive)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} people bookmarked",
/* eg from an Activity */
"FROMANACTIVITY":"from an Activity",
"FROMABLOG":"from a Blog",
"FROMANIDEATIONBLOG":"from an Ideation Blog",
"FROMANEVENT":"from an Event",
"FROMAFORUM":"from a Forum",
"FROMAWIKI":"from a Wiki",
"FROMACOMMUNITY":"from a Community",
"FROMXCOMMUNITIES":"from {0} Communities",
/* For search results parentage */
"ACTIVITY_ALONE":"Activity",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Ideation Blog",
"ENTRY_ALONE":"Entry",
"EVENT_ALONE":"Event",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Community",
"XCOMMUNITIES_ALONE":"{0} Communities",
"SHAREDCOMMUNITIES":"Shared with these communities",
"INACOMMUNITY":"in a Community",
"LASTUPDATED":"Search index was last updated:",
"NODESCRIPTION":"No description or summary for this result.",
"ATTACHMENT":"Attachment:",
"ACTIVITY":"Activity:",
"ACTIVITYBOOKMARK":"Activity bookmark:",
"ACTIVITYCOMMENT":"Activity comment:",
"ACTIVITYENTRY":"Activity entry:",
"ACTIVITYSECTION":"Activity section:",
"ACTIVITYTODO":"Activity to-do:",
"BLOG":"Blog:",
"BLOGENTRY":"Blog entry:",
"BLOGCOMMENT":"Blog comment:",
"BOOKMARK":"Bookmark:",
"CALENDAREVENT":"Event:",
"CATEGORY":"Category:",
"COMMENT":"Comment:",
"COMMUNITY":"Community:",
"ENTRY":"Entry:",
"EVENTDATEON":"On: {0}",
"EVENTISALLDAY":"All-day event",
"EVENTREPEATS":"Repeats",
"FEED":"Feed:",
"FILE":"File:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forum category:",
"FORUMTOPIC":"Forum topic:",
"IDEA":"Idea:",
"IDEACOMMENT":"Idea comment:",
"IDEATIONBLOG":"Ideation Blog:",
"PAGE":"Page:",
"PROFILE":"Profile:",
"SECTION":"Section:",
"STATUSUPDATE":"Status Update",
"STATUSUPDATE_PREFIX":"Status Update:",
"TOPIC":"Topic:",
"TOPIC_WITH_ATTACHMENT":"Topic",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Wiki page:",
"WIKIFILE":"Wiki attachment:",
"SEARCH":"Search:",
"TODO":"To Do:",
"ALLRESULTS":"All Results",
"PUBLICCONTENT":"Public Content",
"MYCONTENT":"My Content",
"RESULTNOTFOUND":"Didn't find what you were looking for?",
"TEMPDIFFICULTIES":"Note: Due to temporary indexing difficulties, your search didn't include {0} that were changed in the last {1} day(s).",
"TRYLATER":"Please try again later.",
"MULTIPLETEMPDIFFICULTIES":"Note: Due to temporary indexing difficulties, your search didn't include {0} that were recently changed",
"YOUAREAUTHOR":"You are an author",
"YOUARECONTRIBUTOR":"You are a contributor",
"YOUAREOWNER":"You are an owner",
"YOUAREMEMBER":"You are a member",
/* Profiles */
"MYNETWORK":"My Network",
"ALLPEOPLE":"All People",
"EXCLUDEINACTIVE":"Exclude Inactive People",
"PHONE":"Phone:",
"EMAIL":"Email:",
/* Communities */
"ALLCOMMUNITIES":"All Communities",
"PUBLICCOMMUNITIES":"Public Communities",
"MYCOMMUNITIES":"My Communities",
"EVERYTHINGCOMMUNITIES":"Everything from Communities",
"COMMUNITIESONLY":"Communities",
"COMMUNITIESCONTENT":"Content from Communities",
/* Activities */
"ALLACTIVITIES":"All Activities",
"PUBLICACTIVITIES":"Public Activities",
"MYACTIVITIES":"My Activities",
"EVERYTHINGACTIVITIES":"Everything from Activities",
"ACTIVITIESONLY":"Activities",
"SECTIONSACTIVITIES": "Sections from Activities",
"ENTRIESACTIVITIES":"Entries from Activities",
"TODOSACTIVITIES":"To Dos from Activities",
"BOOKMARKSACTIVITIES":"Bookmarks from Activities",
"FILESACTIVITIES":"Attachments from Activities",
"ALLTYPESACTIVITIES":"All Types of Activities",
"COMMUNITYACTIVITIES":"Activities from Communities",
"STANDALONEACTIVITIES":"Stand-alone Activities",
/* Forums */
"ALLFORUMS":"All Forums",
"PUBLICFORUMS":"Public Forums",
"MYFORUMS":"My Forums",
"EVERYTHINGFORUMS":"Everything from Forums",
"FORUMSONLY":"Forums",
"TOPICSFORUMS":"Forum Topics",
"FORUMCATEGORIES": "Forum Categories",
"FILESFORUMS":"Attachments from Forums",
"ALLTYPESFORUMS":"All Types of Forums",
"COMMUNITYFORUMS":"Forums from Communities",
"STANDALONEFORUMS":"Stand-alone Forums",
/* Blogs */
"ALLBLOGS":"All Blogs",
"PUBLICBLOGS":"Public Blogs",
"MYBLOGS":"My Blogs",
"EVERYTHINGBLOGS":"Everything from Blogs",
"BLOGSONLY":"Blogs",
"ENTRIESBLOGS":"Blog Entries",
"FILESBLOGS":"Attachments from Blogs",
"EVERYTHINGIDEATIONBLOGS":"Everything from Ideation Blogs",
"BLOGSIDEATIONBLOGS":"Ideation Blogs",
"BLOGSIDEAS":"Ideas",
"ALLTYPESBLOGS":"All Types of Blogs",
"COMMUNITYBLOGS":"Blogs from Communities",
"COMMUNITYIDEATIONBLOGS":"Ideation Blogs from Communities",
"STANDALONEBLOGS":"Stand-alone Blogs",
/* Bookmarks */
"ALLBOOKMARKS":"All Bookmarks",
"PUBLICBOOKMARKS":"Public Bookmarks",
"MYBOOKMARKS":"My Bookmarks",
"ALLTYPESBOOKMARKS":"All Types of Bookmarks",
"COMMUNITYBOOKMARKS":"Bookmarks from Communities",
"STANDALONEBOOKMARKS":"Stand-alone Bookmarks",
/* Files */
"ALLFILES":"All Files",
"PUBLICFILES":"Public Files",
"MYFILES":"My Files",
"ALLTYPESFILES":"All Types of Files",
"COMMUNITYFILES":"Files from Communities",
"STANDALONEFILES":"Stand-alone Files",
"NUMDOWNLOADS":"{0} Downloads",
/* Wikis */
"ALLWIKIS":"All Wikis",
"PUBLICWIKIS":"Public Wikis",
"MYWIKIS":"My Wikis",
"EVERYTHINGWIKIS":"Everything from Wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Wiki Pages",
"FILESWIKIS":"Attachments from Wikis",
"ALLTYPESWIKIS":"All Types of Wikis",
"COMMUNITYWIKIS":"Wikis from Communities",
"STANDALONEWIKIS":"Stand-alone Wikis",
/* Status Updates */
"ALLSTATUSUPDATES":"All Status Updates",
"PUBLICSTATUSUPDATES":"Public Status Updates",
"MYSTATUSUPDATES":"My Status Updates",
"ALLTYPESSTATUSUPDATES":"All Types of Status Updates",
"COMMUNITYSTATUSUPDATES":"Status Updates from Communities",
"STANDALONESTATUSUPDATES":"Status Updates from Profiles",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"This URL was bookmarked by a number of users",
"BOOKMARKEDCOMMUNITY":"This community was bookmarked by a number of users",
"BOOKMARKEDPROFILE":"This Profile was bookmarked by a number of users",
"BOOKMARKEDBLOG":"This Blog was bookmarked by a number of users",
"COMMUNITYBLOG":"This is a blog within a community",
"BOOKMARKEDACTIVITY":"This Activity was bookmarked by a number of users",
"COMMUNITYACTIVITY":"This is an Activity within a community",
"BOOKMARKEDFILE":"This File was bookmarked by a number of users",
"COMMUNITYFILE":"This is an File within a community",
"BOOKMARKED":"This Wiki was bookmarked by a number of users",
"COMMUNITYWIKI":"This is a Wiki within a community",
"BOOKMARKEDFORUM":"This Forum was bookmarked by a number of users",
"COMMUNITYFORUM":"This is a Forum within a community",
"ALLTAGANDTTILE":"To see all titles and tags for this URL click this button",
"TAGS_ARE_FROM":"This search result may include tags from:",
"BOOKMARKS_TITLE":"Bookmarks",
"COMMUNITIES_TITLE":"Communities",
"ACTIVITIES_TITLE":"Activities",
"HELP":"Help",
"MORESTATUSUPDATES":"View more status update matches",
"TITLE_PREFIX":"title:",
"LATEST_MESSAGE":"Latest Message",
"LATEST_STATUS_UPDATE":"Latest Status Update",
"LATEST_COMMUNITY_STATUS_UPDATE":"Latest Community Status Update",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Latest Communities Status Update",
"SEARCH_RESULTS":"All Content Search Results",
"ACTIVITIES_SEARCH_RESULTS":"Activities Search Results",
"BLOGS_SEARCH_RESULTS":"Blogs Search Results",
"BOOKMARKS_SEARCH_RESULTS":"Bookmarks Search Results",
"COMMUNITIES_SEARCH_RESULTS":"Communities Search Results",
"FILES_SEARCH_RESULTS":"Files Search Results",
"FORUMS_SEARCH_RESULTS":"Forums Search Results",
"PROFILES_SEARCH_RESULTS":"Profiles Search Results",
"DIRECTORY_SEARCH_RESULTS":"${orgName} Directory Search Results",
"WIKIS_SEARCH_RESULTS":"Wikis Search Results",
"STATUS_UPDATES_SEARCH_RESULTS":"Status Updates Search Results",
"VIEW_ALL":"{span}View All{/span} ({0})",
"MATCHING_ONE_OF":"Matching one of:",
"MATCHING_ALL_OF":"Matching all of:",
"MATCHING":"Matching:",
"MATCHING_DOC_TYPE":"Matching Document Type:",
"BOOKMARK_HELP":"Bookmark Help",
"CLOSE_BOOKMARK_HELP":"Close Bookmark Help",
"DOCUMENT_TYPE_PREFIX":"Document type:",
"FILE_PREVIEW_ONLY":"(Preview Mode Only)"
})
