/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Ажурирано од ${author}",
		PREVIEW_MODE_ONLY: "(Само режим на преглед)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Заедницата е видена денеска",
		COMMUNITY_VIEWED_YESTERDAY: "Заедницата е видена вчера",
		COMMUNITY_VIEWED_HOURS_AGO: "Заедницата е видена пред ${hours} часа",
		COMMUNITY_VIEWED_MINUTES_AGO: "Заедницата е видена пред ${minutes} минути",
		COMMUNITY_VIEWED_SECONDS_AGO: "Заедницата е видена пред ${seconds} секунди",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Заедницата е видена пред 1 час",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Заедницата е видена пред 1 минута",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Заедницата е видена пред 1 секунда",
		COMMUNITY_VIEWED_AT_DATE: "Заедницата е видена на ${date}",
		//File
		FILE_VIEWED_TODAY: "Датотеката е видена денеска",
		FILE_VIEWED_YESTERDAY: "Датотеката е видена вчера",
		FILE_VIEWED_HOURS_AGO: "Датотеката е видена пред ${hours} часа",
		FILE_VIEWED_MINUTES_AGO: "Датотеката е видена пред ${minutes} минути",
		FILE_VIEWED_SECONDS_AGO: "Датотеката е видена пред ${seconds} секунди",
		FILE_VIEWED_1_HOUR_AGO: "Датотеката е видена пред 1 час",
		FILE_VIEWED_1_MINUTE_AGO: "Датотеката е видена пред 1 минута",
		FILE_VIEWED_1_SECOND_AGO: "Датотеката е видена пред 1 секунда",
		FILE_VIEWED_AT_DATE: "Датотеката е видена на ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Профилот е виден денеска",
		PROFILE_VIEWED_YESTERDAY: "Профилот е виден вчера",
		PROFILE_VIEWED_HOURS_AGO: "Профилот е виден пред ${hours} часа",
		PROFILE_VIEWED_MINUTES_AGO: "Профилот е виден пред ${minutes} минути",
		PROFILE_VIEWED_SECONDS_AGO: "Профилот е виден пред ${seconds} секунди",
		PROFILE_VIEWED_1_HOUR_AGO: "Профилот е виден пред 1 час",
		PROFILE_VIEWED_1_MINUTE_AGO: "Профилот е виден пред 1 минута",
		PROFILE_VIEWED_1_SECOND_AGO: "Профилот е виден пред 1 секунда",
		PROFILE_VIEWED_AT_DATE: "Профилот е виден на ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Активноста е видена денеска",
		ACTIVITY_VIEWED_YESTERDAY: "Активноста е видена вчера",
		ACTIVITY_VIEWED_HOURS_AGO: "Активноста е видена пред ${hours} часа",
		ACTIVITY_VIEWED_MINUTES_AGO: "Активноста е видена пред ${minutes} минути",
		ACTIVITY_VIEWED_SECONDS_AGO: "Активноста е видена пред ${seconds} секунди",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Активноста е видена пред 1 час",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Активноста е видена пред 1 минута",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Активноста е видена пред 1 секунда",
		ACTIVITY_VIEWED_AT_DATE: "Активноста е видена на ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Обележувачот е виден денеска",
		BOOKMARK_VIEWED_YESTERDAY: "Обележувачот е виден вчера",
		BOOKMARK_VIEWED_HOURS_AGO: "Обележувачот е виден пред ${hours} часа",
		BOOKMARK_VIEWED_MINUTES_AGO: "Обележувачот е виден пред ${minutes} минути",
		BOOKMARK_VIEWED_SECONDS_AGO: "Обележувачот е виден пред ${seconds} секунди",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Обележувачот е виден пред 1 час",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Обележувачот е виден пред 1 минута",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Обележувачот е виден пред 1 секунда",
		BOOKMARK_VIEWED_AT_DATE: "Обележувачот е виден на ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Блогот е виден денеска",
		BLOG_VIEWED_YESTERDAY: "Блогот е виден вчера",
		BLOG_VIEWED_HOURS_AGO: "Блогот е виден пред ${hours} часа",
		BLOG_VIEWED_MINUTES_AGO: "Блогот е виден пред ${minutes} минути",
		BLOG_VIEWED_SECONDS_AGO: "Блогот е виден пред ${seconds} секунди",
		BLOG_VIEWED_1_HOUR_AGO: "Блогот е виден пред 1 час",
		BLOG_VIEWED_1_MINUTE_AGO: "Блогот е виден пред 1 минута",
		BLOG_VIEWED_1_SECOND_AGO: "Блогот е виден пред 1 секунда",
		BLOG_VIEWED_AT_DATE: "Блогот е виден на ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Форумот е виден денеска",
		FORUM_VIEWED_YESTERDAY: "Форумот е виден вчера",
		FORUM_VIEWED_HOURS_AGO: "Форумот е виден пред ${hours} часа",
		FORUM_VIEWED_MINUTES_AGO: "Форумот е виден пред ${minutes} минути",
		FORUM_VIEWED_SECONDS_AGO: "Форумот е виден пред ${seconds} секунди",
		FORUM_VIEWED_1_HOUR_AGO: "Форумот е виден пред 1 час",
		FORUM_VIEWED_1_MINUTE_AGO: "Форумот е виден пред 1 минута",
		FORUM_VIEWED_1_SECOND_AGO: "Форумот е виден пред 1 секунда",
		FORUM_VIEWED_AT_DATE: "Форумот е виден на ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Wiki е видена денеска",
		WIKI_VIEWED_YESTERDAY: "Wiki е видена вчера",
		WIKI_VIEWED_HOURS_AGO: "Wiki е видена пред ${hours} часа",
		WIKI_VIEWED_MINUTES_AGO: "Wiki е видена пред ${minutes} минути",
		WIKI_VIEWED_SECONDS_AGO: "Wiki е видена пред ${seconds} секунди",
		WIKI_VIEWED_1_HOUR_AGO: "Wiki е видена пред 1 час",
		WIKI_VIEWED_1_MINUTE_AGO: "Wiki е видена пред 1 минута",
		WIKI_VIEWED_1_SECOND_AGO: "Wiki е видена пред 1 секунда",
		WIKI_VIEWED_AT_DATE: "Wiki е видена на ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Настанот е виден денеска",
		EVENT_VIEWED_YESTERDAY: "Настанот е виден вчера",
		EVENT_VIEWED_HOURS_AGO: "Настанот е виден пред ${hours} часа",
		EVENT_VIEWED_MINUTES_AGO: "Настанот е виден пред ${minutes} минути",
		EVENT_VIEWED_SECONDS_AGO: "Настанот е виден пред ${seconds} секунди",
		EVENT_VIEWED_1_HOUR_AGO: "пастанот е виден пред 1 час",
		EVENT_VIEWED_1_MINUTE_AGO: "Настанот е виден пред 1 минута",
		EVENT_VIEWED_1_SECOND_AGO: "Настанот е виден пред 1 секунда",
		EVENT_VIEWED_AT_DATE: "Настанот е виден на ${date}",
		//To Do
		TODO_VIEWED_TODAY: "Ставките што треба да се извршат се видени денеска",
		TODO_VIEWED_YESTERDAY: "Ставките што треба да се извршат се видени вчера",
		TODO_VIEWED_HOURS_AGO: "Ставките што треба да се извршат се видени пред ${hours} часа",
		TODO_VIEWED_MINUTES_AGO: "Ставките што треба да се извршат се видени пред ${minutes} минути",
		TODO_VIEWED_SECONDS_AGO: "Ставките што треба да се извршат се видени пред ${seconds} секунди",
		TODO_VIEWED_1_HOUR_AGO: "Ставките што треба да се извршат се видени пред 1 час",
		TODO_VIEWED_1_MINUTE_AGO: "Ставките што треба да се извршат се видени пред 1 минута",
		TODO_VIEWED_1_SECOND_AGO: "Ставките што треба да се извршат се видени пред 1 секунда",
		TODO_VIEWED_AT_DATE: "Ставките што треба да се извршат се видени на ${date}"
});

