/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Titel ist erforderlich.",
	nourl: "URL ist erforderlich.",
	fileSchema: "Wenn Sie eine ferne oder lokale Dateiverbindung hinzufügen möchten, müssen Sie eines der folgenden Formate einhalten: Datei://ferner_Pfad oder Datei:///lokaler_Pfad",
	invalidUrl: "Dies ist keine gültige Community-URL.",
	invalidTagChar: "Die von Ihnen eingegebene Tag-Liste enthält das ungültige Zeichen '&'.  Bitte entfernen Sie dieses Zeichen aus der Tag-Liste.",
	txtHelp: "Hilfe",
	txtHelpTags: "Hilfe zu Tags ",
	txtHelpTagsClose: "Hilfe zu Tags schließen",
	tagsall: "Alle",
	tagsyours: "Eigene",
	tagsrecent: "Neue:",
	tagspopular: "Beliebte:",
	tagsrecommended: "Empfohlene: ",
	nothingselected: "Die Auswahl einer Community ist erforderlich.",
	nothingselected_activity: "Die Auswahl einer Aktivität ist erforderlich.",
	nothingselected_blogs: "Die Auswahl eines Blogs ist erforderlich.",
	nothingselected_all: "Es ist kein Service oder Eintrag ausgewählt. Das Lesezeichen wird nicht gespeichert.",
	nothingFeedselected: "Es ist kein Service oder Eintrag ausgewählt. Der Feed wird nicht gespeichert.",
	alertDialogTitle: "Nachricht",
	alertDialogOK: "OK",
	expand: "Zum Einblenden dieses Abschnitts hier klicken",
	collapse: "Zum Ausblenden dieses Abschnitts hier klicken",
	discussThis: "Diskutieren ",
	by: "Von: ",
	posted: "Veröffentlicht: ",
	attachments: "Anhänge",
	communityForum: "Community-Forum",
	notCommunityPage: "Die aktuelle Webseite ist keine gültige Community-Webseite. Sie können den Titel, den Link und die Beschreibung der Community manuell eingeben, um eine zugehörige Community zu erstellen. ",
	privateCommunityNotice: "Diese Community ist beschränkt und nur für ihre Mitglieder sichtbar. ",
	forumNameHint : "Geben Sie einen Forennamen ein",
	formDescriptionHint:"Beschreiben Sie, warum diese zugehörige  Community für Ihre Community von Interesse sein könnte.",
	information : "Information ",
	error : "Fehler",
	success : "Erfolg ",
	warning : "Warnung ",
	informationColon : "Information: ",
	successColon : "Erfolg:",
	warningColon : "Warnung:",
	errorColon : "Fehler:",
	feedAlreadyExist : "Feed ist bereits in dieser Community vorhanden. ",
	bookmarkAlreadyExist : "Lesezeichen ist bereits in dieser Community vorhanden. ",
	mentionAuthWarning:"Die folgenden erwähnten Personen können die Nachricht nicht anzeigen, da sie keine Mitglieder der Community sind: ",
	mentionAuthForumWarning:"Die folgenden erwähnten Personen können die Nachricht nicht anzeigen, weil sie nicht auf dieses Forum zugreifen können.",
	exceedDescLength: "Die eingegebene Beschreibung ist zu lang.",
	communities_checked:"${0} Communitys ausgewählt",
	activities_checked:"${0} Aktivitäten ausgewählt",
	blogs_checked:"${0} Blogs ausgewählt"
})
