define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Zatvori",
		   'rs_loading' : "Učitavanje...",
		   'rs_at' : "na",
		   'rs_searchDirectory' : "Osoba nije navedena? Koristi punu pretragu ...",
		   'rs_searchGroupDirectory' : "Grupa nije navedena? Koristi punu pretragu ...",
		   'rs_searchPersonAndGroupDirectory' : "Osoba ili grupa nije navedena? Koristi punu pretragu ...",
		   'rs_searchCommunityDirectory' : "Zajednica nije navedena? Koristi punu pretragu ...",
		   'rs_shadowText_searchDirectory' : "Upišite da biste pronašli osobu",
		   'rs_shadowText_searchGroupDirectory' : "Upišite da biste našli grupu",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Upišite da biste pronašli osobu ili grupu",
		   'rs_shadowText_searchCommunityDirectory' : "Upišite da biste pronašli zajednicu",
		   'rs_listItem' : "Stavka na listi",
		   'rs_noResults' : "Nema rezultata za '&${0}'",
		   'rs_today' : "Danas",
		   'rs_tomorrow' : "Sutra",
		   'rs_yesterday' : "Juče",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Fid za ove aktivnosti",
		   'rs_externalText' : "Ova aktivnost može imati članove van vaše organizacije.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" je uspešno premeštena u \"${destCommName}\" podzajednicu.',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Prikaži više informacija o ovoj aktivnosti',
		   'rs_hideInfo' : 'Sakrij dodatne informacije',
		   'rs_more' : "Više",
		   'rs_hide' : "Sakrij",
		   'rs_edit' : "Uredi",
		   'rs_restore' : "Vrati",
		   'rs_deleteEntry' : "Izbriši",
		   'rs_prioritize' : "Odredi prioritet",
		   'rs_markComplete' : "Označi kao dovršeno",
		   'rs_markIncomplete' : "Vrati",
		   'rs_linkMore' : "... [više]",
		   'rs_linkLess' : "... [manje]",
		   'rs_actUpdatedByDate' : "Ažurirao/la ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Ažurirao/la ${0}",// Updated by (author name)
		   'rs_actDue' : "Rok ${0}",// Due (date)
		   'rs_actTags' : "Oznake: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Pokretanje aktivnosti iz ovog predloška",
		   'rs_favoriteTemplate' : "Obeleži kao omiljeni predložak",
		   'rs_normalTemplate' : "Obeleži kao standardni predložak",
		   'rs_tunedOutPri' : "Isključeno",
		   'rs_pagepos' : "${0} - ${1} od ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Prethodno",
		   'rs_navNextLabel' : "Sledeće",
		   'rs_noActivities' : "Nema započetih aktivnosti u ovoj zajednici.",
		   'rs_feedError' : "Učitavanje fida nije uspelo.",
		   'rs_highPri' : "Visoki prioritet",
		   'rs_medPri' : "Srednji prioritet",
		   'rs_normalPri' : "Normalan prioritet (podrazumevano)",
		   'rs_tuneOut' : "Označi kao isključeno",
		   'rs_startActivity' : "Pokretanje aktivnosti",
		   'rs_startFirstActivity' : "Kreirajte vašu prvu aktivnost",
		   'rs_navNextLabel' : "Sledeće",
		   'rs_viewAll' : "Prikaži sve",
		   'rs_activityWidgetTitle' : "Aktivnosti",
		   'rs_activityWidgetBriefDescription' : "Pratite ciljeve zajednice.  Kreirajte obaveze i delite resurse.",
		   'rs_activityWidgetDescription' : "Aktivnosti zajednice se mogu koristiti za saradnju i praćenje napretka projekata i inicijativa zajednice.",
		   'rs_completedActivityLink' : "Prikaži završene Aktivnosti",
		   'rs_activitiesUnavailable' : "Usluga Aktivnosti nije dostupna.",
		   'rs_errorPersists' : "Ako problem i dalje postoji kontaktirajte administratora sistema.",
		   'rs_shared' : "Deljeno",
		   'rs_removeActFromComm' : "Ukloni iz zajednice",
		   'rs_externalLabel' : "Eksterno",
		   // for ActivityForm
		   'rs_templateOptions' : "Opcije predloška",
		   'rs_template' : "Predložak",
		   'rs_tagsLabel' : "Oznake",
		   'rs_peopleLabel' : "Osobe",
		   'rs_aboutThisTemplate' : "O ovom predlošku",
		   'rs_activity' : "Aktivnost",
		   'rs_copyOf' : "Kopija aktivnosti ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Cilj aktivnosti",
		   'rs_noTemplate' : "Nema",
		   'rs_copyActivityMembers' : "Koristi članove iz aktivnosti",
		   'rs_copyTemplateMembers' : "Koristi članove iz predloška",
		   /* Forum Widget */
		   'rs_noTopics' : "Ova zajednica još nema tema.",
		   'rs_noTopicsLoggedIn' : "Postavite pitanje, raspravljajte ili podelite ideje.",
		   'rs_postedBy' : "Poslednju objavu postavio/la",
		   'rs_topics' : "teme",
		   'rs_noTopicsShort' : "Nema tema",
		   'rs_topic' : "tema",
		   'rs_replies' : "odgovori",
		   'rs_noReplies' : "Nema odgovora",
		   'rs_reply' : "odgovor",
		   'rs_startTopic' : "Pokreni Temu",
		   'rs_startFirstTopic' : "Pokrenite Prvu temu",
		   'rs_ok' : "U redu",
		   'rs_locked' : "[Zaključano]",
		   'rs_manageForumSetting' : "Upravljanje postavkama foruma",
		   'rs_forumSettingCommunityOverviewPage' : "Stranica Pregled zajednice:",
		   'rs_defaultForumList' : "Podrazumevano prikaži listu foruma",
		   'rs_defaultTopicList' : "Podrazumevano prikaži listu tema",
		   'rs_forumSettingApplicationView' : "Podrazumevani prikaz aplikacija foruma:",
		   'rs_forumSettingNote' : "Napomena: Ukoliko postoji samo jedan forum, podrazumevano se prikazuju teme.",
		   'rs_forumSettingSubmit' : "Podnesi",
		   'rs_forumSettingSave' : "Sačuvaj",
		   'rs_forumSettingSaveAndClose' : "Sačuvaj i zatvori",
		   'rs_forumSettingConfirm' : "Promene za Forum su sačuvane.",
		   'rs_forumSettingError' : "Došlo je do greške. Kontaktirajte administratora.",
		   'rs_formSettingHideMessage' : "Sakrij ovu poruku",
		   'rs_forumSettingCancel' : "Otkaži",
		   'rs_forumAnsweredQuestion' : "Pitanje s odgovorom",
		   'rs_forumUnAnsweredQuestion' : "Pitanje bez odgovora",
		   'rs_forumSortBy' : "Sortiraj prema:",
		   'rs_forumSortByDate' : "Datum",
		   'rs_forumSortByReplies' : "Odgovori",
		   'rs_forumSortByTopic' : "Teme",
		   'rs_forumSortByTopicsAndReplies' : "Teme i odgovori",
		   'rs_sortByReplies' : "Sortiraj po odgovorima",
		   'rs_sortbyTopicsAndReplies' : "Sortiraj po temama i odgovorima",
		   'rs_forumOpenQuestions' : "Otvorena pitanja",
		   'rs_feedOpenQuestions' : "Fid za ova otvorena pitanja",
		   'rs_feedAnsweredQuestions' : "Fid za ova pitanja s odgovorom",
		   'rs_forumMessages' : "${0} poruka",
		   'rs_forumLastAddedPost' : "Poslednja objava od strane ${0}",
		   'rs_forumTopics' : "${0} tema",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Kreiraj Lnnk ka osobi",
		   'rs_quote' : "Citiraj",
		   'rs_labelColon' : "Označi: ",
		   'rs_personColon' : "Osoba: ",
		   'rs_personLink' : "Link ka osobi",
		   'rs_replace' : "Zameni",
		   'rs_inactivePerson' : "${0} (neaktivno)", // person's name (inactive)
		   'rs_PersonPicture' : "${0} slika", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Eksterni korisnik", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (Eksterni korisnik)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "${0} slika (spoljni korisnik)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Ovaj korisnik ima pristup Datotekama i Zajednicama koje se dele spoljno.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Obavesti druge osobe",
		   'rs_messageColon' : "Poruka: ",
		   'rs_notifyColon' : "Obavesti: ",
		   'rs_notificationConfirm' : "Poruka obaveštenja je uspešno poslata. ",
		   'rs_notificationFail' : "Poruka obaveštenja nije poslata. Pokušajte ponovo kasnije ili kontaktirajte administratora sistema ako problem i dalje postoji.",
		   'rs_pickCommunity' : "Izaberi sa liste Zajednice",
		   'rs_typeName' : "Upišite ime",
		   'rs_typeToFilter' : "Upišite da biste filtrirali ovu listu",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Upišite da biste filtrirali ovu listu",
		   'rs_filterGroupLabel' : "Izaberite grupu",
		   'rs_noResults' : "Nema rezultata",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Prikaz ${0} rezultata od ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Ukloni",
		   /* Language Selector */
		   'rs_browser_setting' : "Podešavanje pretraživača",
		   'rs_customLangaugeLinkLabel' : "Jezik po izboru",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Idi na stranicu ${0} od ${1}",
		   "rs_jumpPageLabel" : "Idi na stranicu",
		   'rs_pageNumLabel' : "Broj stranice",
		   'rs_pageLabel' : "Stranica:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Oznake',
		   'rs_tagCloudToggleHint' : "Kliknite da biste sakrili ili pokazali",
		   'rs_tagCloudHelpAlt' : "Potražite pomoć sa oznakama",
		   'rs_tagCloudNoTags' : "Još nema oznaka.",
		   'rs_tagCloudNoRecentTags' : "Nema skorijih oznaka",
		   'rs_tagCloudNoTagsProfiles' : "Pretražite direktorijum. Oznake povezane sa profilima pronađenim u pretrazi će biti prikazane ovde.",
		   'rs_tagLoadingTags' : "Učitavanje sadržaja",
		   'rs_tagCloudSelectedTags' : "Izabrane oznake",
		   'rs_tagCloudSeachDesc' : "Pronađi oznaku",
		   'rs_tagCloudSeach' : "Pretraga",
		   'rs_tagCloudRelatedTags' : "Povezane oznake",
		   'rs_tagCloudRelatedTagsDescription' : "Dodajte povezanu oznaku da biste detaljnije precizirali vašu pretragu",
		   'rs_tagCloudError' : 'Došlo je do greške',
		   'rs_viewAsCloud' : "Oblak",
		   'rs_viewAsCloudTitle' : "Navedi oznake kao oblak oznaka",
		   'rs_viewAsCloudDescription' : "Prikazivanje oznaka u vidu oblaka oznaka",
		   'rs_viewAsList' : "Lista",
		   'rs_viewAsListTitle' : "Navedi oznake kao uzastopnu listu oznaka",
		   'rs_viewAsListDescription' : "Prikazivanje oznaka u vidu uzastopne liste oznaka",
		   'rs_tagCloudViewAll' : "Pregledaj",
		   'rs_tagCloudViewAllTitle' : "Pregledaj sve oznake",
		   'rs_normalTags' : "Aktivne oznake",
		   'rs_removeTag' : "Ukloni oznaku sa liste odabranih oznaka za filtriranje",
		   'rs_clearAll' : "Obriši sve",
		   'rs_searchInputDefault' : "Upišite da biste pronašli oznaku",
		   'rs_searchInputTagSelected' : "Upišite još jednu oznaku",
		   'rs_relatedTagTitle' : "Prikaži rezultate pretrage za oznaku ${0}, broj ${1}",
		   'rs_removeTagTitle' : "Ukloni oznaku ${0} sa liste odabranih oznaka za filtriranje",
		   'rs_addTagTitle' : "Filtriraj prema oznaci ${0} sa brojem ${1}",
		   'rs_tagDialogCloseTile' : "Zatvori",
		   'rs_tagDialogTitle' : "Sve oznake",
		   'rs_tagDialogPageInfo' : "o${0} - ${1} od ${2}oznaka",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Pregledaj Grupe",
		   'rs_group_browse_groups_dialog_title' : "Pregledaj Grupe",
		   'rs_group_browse_find_groups' : "Pronađi Grupe",
		   'rs_group_browse_add_button' : "Dodaj",
		   'rs_group_browse_cancel_button' : "Otkaži",
		   'rs_group_browse_enter_string' : "Upiši da pronađeš grupe",
		   'rs_group_browse_group_typeahead_label' : "Upiši ime grupe :",
		   'rs_group_browse_group_name' : "Ime grupe:",
		   'rs_group_browse_results_label' : "Izaberi odgovarajuću grupu:",
		   'rs_group_browse_parent_group_label' : "Ušli ste u:",
		   'rs_group_browse_next_page' : "Sledeća stranica",
		   'rs_group_browse_previous' : "Prethodno",
		   'rs_group_browse_next' : "Sledeće",
		   'rs_group_browse_paging' : "Stranice",
		   'rs_group_browse_previous_page' : "Prethodna stranica",
		   'rs_group_browse_group_selected' : "Izabrana grupa:",
		   'rs_group_browse_group_no_groups' : "Ova grupa ne sadrži nijednu grupu",
		   'rs_group_browse_page_info' : "${0} - ${1} od ${2}",
		   'rs_group_browse_page_info_alt' : "Upoređivanje grupa od ${0} do ${1} od ${2}",
		   'rs_group_browse_remove_selection' : 'Ukloni umetnuti grupni izbor: ${0}',
		   'rs_group_browse_paging' : "Stranice",
		   'rs_member_groups' : "Grupe",
		   'rs_member_members' : "Članovi",
		   'rs_member_no_results' : "Nema rezultata",
		   'rs_member_remove_group' : "Ukloni ${0}",
		   'rs_member_add_to_community' : "Klikni da dodaš člana",
		   'rs_member_remove_name' : "Klikni da ukloniš člana",
		   'rs_group_add_to_community' : "Klikni da dodaš grupu",
		   'rs_group_remove_name' : "Klikni da ukloniš grupu",
		   'rs_group_name' : "Ime grupe",
		   'rs_group_role' : "Uloga grupe",
		   'rs_warning' : "Upozorenje",
		   'rs_a11y_warning' : "Upozorenje:",
		   'rs_messagebox_close_btn_title' : "Zatvori",
		   'rs_messagebox_close_btn_alt' : "Zatvori",
		   'rs_messagebox_error_icon_alt' : "Greška",
		   'rs_messagebox_error_a11y_label' : "Greška:",
		   'rs_messagebox_warning_icon_alt' : "Upozorenje",
		   'rs_messagebox_warning_a11y_label' : "Upozorenje:",
		   'rs_messagebox_info_icon_alt' : "Informacije",
		   'rs_messagebox_info_a11y_label' : "Informacije:",
		   'rs_messagebox_success_icon_alt' : "Uspešno",
		   'rs_messagebox_success_a11y_label' : "Uspešno:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Ubaci link ka Datoteke",
		   'rs_docpicker_label' : "Link ka Datoteke",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Preuzmi ${0}",
		   'rs_docpicker_viewdetails_text' : "Prikaži detalje",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Prikaži detalje za ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Ukloni",
		   'rs_attachedfile_filename' : "Slika ${0}",
		   'rs_feedreader_warning' : "Upozorenje: ovaj link je predviđen za čitače fidova i moguće je da nije ispravno prikazan u vašem pretraživaču. Kliknite na „U redu“ za nastavak ili na „Otkaži“ za povratak na stranu.",
		   'rs_search' : "Pretraga",
		   'rs_all_connections' : "Sve Connections usluge",
		   'rs_advanced' : "Napredno",
		   'rs_select_scope' : "Izaberi opseg pretrage",
		   'rs_icfixlayout' : {
		      button_label : "Formatiraj ponovo",
		      dialog_title : "Ponovo formatiraj sadržaj",
		      warning : "Upozorenje",
		      reformat_save : "Formatiraj ponovo i sačuvaj",
		      save_as_is : "Sačuvaj postojeće",
		      cancel : "Otkaži",
		      warn_layout : "Vaš sadržaj prekoračuje maksimalnu širinu prikaza.  Želite li da ga automatski ponovo formatirate kako bi se uklopio u dostupan prostor?",
		      remember_decision : "Zapamti moju odluku"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Došlo je do greške prilikom deljenja izabrane datoteke.",
		   'rs_sharefile_access_denied' : "Ova datoteka je izbrisana ili se više ne deli sa vama.",
		   'rs_sharefile_invalid_request' : "Došlo je do greške prilikom deljenja izabrane datoteke.",
		   'rs_sharefile_sharing_intent_restriction' : "Datoteku ne možete deliti unutar vaše organizacije.",
		   'rs_sharefile_error_title' : "Greška",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'U App radnji',
		   'rs_mobileBanner_inGooglePlay' : 'U Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Otvori',
		   'rs_mobileBanner_view' : 'Prikaži',
		   'rs_mobileBanner_hide' : 'Sakrij',

		   'rs_empty_column_placeholder' : 'Prevucite aplikacije ovde.',
		   'rs_widget_loading_error_title' : 'Nije moguće prikazati vidžet',
		   'rs_widget_loading_error_message' : 'Pokušajte ponovo kasnije ili kontaktirajte administratora sistema ako problem i dalje postoji.',
		   'rs_widgets_loading_error_title' : 'Nije moguće prikazati vidžet(e)u ovoj zajednici',
		   'rs_widget_misplacement_warning' : 'Ova aplikacija se ne uklapa u ovu kolonu. Vlasnik zajednice može da je premesti u drugu kolonu ili da je ukloni sa strane.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Naslov koji ste uneli je predugačak.',
		      empty_new_title : 'Naslov ne može biti prazan.',
		      default_message : 'Nije moguće promeniti naslov za ovu ${0} aplikaciju.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Naslov:  ',
		   'rs_widget_title_change_direction' : 'Promenite naslov za ovu ${0} aplikaciju.',
		   'rs_widget_title_change_title' : 'Promena naslova',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Pozovi ili dodaj članove",
		   'rs_vmmainContentDesc' : "Pozovite članove i pružite im priliku da se pridruže zajednici. Dodajte članove da biste ih automatski uključili u zajednicu.",
		   'rs_vmtypeAheadLabel' : "Ime ili e-pošta: ",
		   'rs_vmgroupTypeAheadLabel' : "Ime: ",
		   'rs_vmtypeAheadRoleLabel' : " kao ",
		   'rs_vmgroupTypeAheadRoleLabel' : " kao Članovi ",
		   'rs_vmtaNoResults' : "Nije pronađen ni jedan rezultat.",
		   'rs_vmtaHeader' : "zaglavlje",
		   'rs_vmaddUser' : "Dodaj",
		   'rs_vmradioSectionTitle' : "Opcije člana:",
		   'rs_vmradioOne' : "Pošalji pozivnicu za pridruživanje zajednici",
		   'rs_vmradioTwo' : "Automatski dodaj korisnike u zajednicu",
		   'rs_vmtwistyA' : "Dodajte opcionu poruku",
		   'rs_vmtwistyB' : "Ukloni dodatni tekst",
		   'rs_vmmessage' : "Poruka:",
		   'rs_vmtextAreaStartText' : "Recite nešto...",
		   'rs_vmcheckboxLabel' : "Pošalji mi kopiju",
		   'rs_vmsave' : "Sačuvaj",
		   'rs_vminvite' : "Pozovi",
		   'rs_vmcancel' : "Otkaži",
		   'rs_userContentTitle' : "Unesi informaciju",
		   'rs_vmaddUser' : "Kreiraj korisnika",
		   'rs_vmback'	 : "Nazad",
		   'rs_vmvisitor'	 : "Posetilac",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Kliknite ovde da biste kopirali ovu zajednicu',
			'rs_commpicker' : ''

});
