define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Luk",
		   'rs_loading' : "Indlæser...",
		   'rs_at' : "kl.",
		   'rs_searchDirectory' : "Findes personen ikke? Brug fuld søgning...",
		   'rs_searchGroupDirectory' : "Findes gruppen ikke? Brug fuld søgning...",
		   'rs_searchPersonAndGroupDirectory' : "Findes personen eller gruppen ikke? Brug fuld søgning...",
		   'rs_searchCommunityDirectory' : "Findes fællesskabet ikke? Brug fuld søgning...",
		   'rs_shadowText_searchDirectory' : "Skriv for at søge efter en person",
		   'rs_shadowText_searchGroupDirectory' : "Skriv for søge efter en gruppe",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Skriv for at søge efter en person eller gruppe",
		   'rs_shadowText_searchCommunityDirectory' : "Skriv for at søge efter et fællesskab",
		   'rs_listItem' : "Vis element",
		   'rs_noResults' : "Ingen resultater for '${0}'",
		   'rs_today' : "I dag",
		   'rs_tomorrow' : "I morgen",
		   'rs_yesterday' : "I går",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Feed for disse aktiviteter",
		   'rs_externalText' : "Denne aktivitet kan have medlemmer uden for organisationen.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" er flyttet til underfællesskabet \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Vis flere oplysninger om denne aktivitet',
		   'rs_hideInfo' : 'Skjul ekstra oplysninger',
		   'rs_more' : "Mere",
		   'rs_hide' : "Skjul",
		   'rs_edit' : "Redigér",
		   'rs_restore' : "Gendan",
		   'rs_deleteEntry' : "Slet",
		   'rs_prioritize' : "Prioritér",
		   'rs_markComplete' : "Markér som udført",
		   'rs_markIncomplete' : "Gendan",
		   'rs_linkMore' : "... [mere]",
		   'rs_linkLess' : "... [mindre]",
		   'rs_actUpdatedByDate' : "Opdateret af ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Opdateret af ${0}",// Updated by (author name)
		   'rs_actDue' : "Tidsfrist ${0}",// Due (date)
		   'rs_actTags' : "Emneord: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Start aktivitet fra denne skabelon",
		   'rs_favoriteTemplate' : "Markér som foretrukken skabelon",
		   'rs_normalTemplate' : "Markér som normal skabelon",
		   'rs_tunedOutPri' : "Frasorteret",
		   'rs_pagepos' : "${0}-${1} af ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Forrige",
		   'rs_navNextLabel' : "Næste",
		   'rs_noActivities' : "Der er ikke startet nogen aktiviteter for dette fællesskab.",
		   'rs_feedError' : "Fejl under indlæsning af feed.",
		   'rs_highPri' : "Høj prioritet",
		   'rs_medPri' : "Medium prioritet",
		   'rs_normalPri' : "Normal prioritet (standard)",
		   'rs_tuneOut' : "Markér som frasorteret",
		   'rs_startActivity' : "Start en aktivitet",
		   'rs_startFirstActivity' : "Opret din første aktivitet",
		   'rs_navNextLabel' : "Næste",
		   'rs_viewAll' : "Vis alle",
		   'rs_activityWidgetTitle' : "Aktiviteter",
		   'rs_activityWidgetBriefDescription' : "Hold øje med fællesskabsmål.  Opret opgaver, og del ressourcer.",
		   'rs_activityWidgetDescription' : "Fællesskabsaktiviteter kan bruges til at samarbejde og holde øje med status på fællesskabsprojekter eller initiativer.",
		   'rs_completedActivityLink' : "Vis færdige aktiviteter",
		   'rs_activitiesUnavailable' : "Aktivitetsfunktionen er ikke tilgængelig.",
		   'rs_errorPersists' : "Kontakt systemadministratoren, hvis problemet ikke er løst.",
		   'rs_shared' : "Delt",
		   'rs_removeActFromComm' : "Fjern fra fællesskab",
		   'rs_externalLabel' : "Ekstern",
		   // for ActivityForm
		   'rs_templateOptions' : "Skabelonindstillinger",
		   'rs_template' : "Skabelon",
		   'rs_tagsLabel' : "Emneord",
		   'rs_peopleLabel' : "Personer",
		   'rs_aboutThisTemplate' : "Om skabelonen",
		   'rs_activity' : "Aktivitet",
		   'rs_copyOf' : "Kopi af ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Aktivitetsmål",
		   'rs_noTemplate' : "Ingen",
		   'rs_copyActivityMembers' : "Brug medlemmer fra aktivitet",
		   'rs_copyTemplateMembers' : "Brug medlemmer fra skabelon",
		   /* Forum Widget */
		   'rs_noTopics' : "Der er endnu ingen emner for dette fællesskab.",
		   'rs_noTopicsLoggedIn' : "Stil et spørgsmål, foretag brainstorming, eller del dine idéer med andre",
		   'rs_postedBy' : "Seneste indlæg af",
		   'rs_topics' : "emner",
		   'rs_noTopicsShort' : "Ingen emner",
		   'rs_topic' : "emne",
		   'rs_replies' : "svar",
		   'rs_noReplies' : "Ingen svar",
		   'rs_reply' : "svar",
		   'rs_startTopic' : "Start et emne",
		   'rs_startFirstTopic' : "Start det første emne",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Låst]",
		   'rs_manageForumSetting' : "Administrér forumindstillinger",
		   'rs_forumSettingCommunityOverviewPage' : "Oversigtsside for fællesskab:",
		   'rs_defaultForumList' : "Vis forumliste som standard",
		   'rs_defaultTopicList' : "Vis emneliste som standard",
		   'rs_forumSettingApplicationView' : "Standardoversigt for forumapplikation:",
		   'rs_forumSettingNote' : "Bemærk: Emner vises som standard, hvis der kun er ét forum.",
		   'rs_forumSettingSubmit' : "Afsend",
		   'rs_forumSettingSave' : "Gem",
		   'rs_forumSettingSaveAndClose' : "Gem og luk",
		   'rs_forumSettingConfirm' : "Ændringerne af forummer er gemt.",
		   'rs_forumSettingError' : "Der er opstået en fejl. Kontakt administratoren.",
		   'rs_formSettingHideMessage' : "Skjul denne meddelelse",
		   'rs_forumSettingCancel' : "Annullér",
		   'rs_forumAnsweredQuestion' : "Besvaret spørgsmål",
		   'rs_forumUnAnsweredQuestion' : "Ubesvaret spørgsmål",
		   'rs_forumSortBy' : "Sortér efter:",
		   'rs_forumSortByDate' : "Dato",
		   'rs_forumSortByReplies' : "Svar",
		   'rs_forumSortByTopic' : "Emner",
		   'rs_forumSortByTopicsAndReplies' : "Emner og svar",
		   'rs_sortByReplies' : "Sortér efter svar",
		   'rs_sortbyTopicsAndReplies' : "Sortér efter emner og svar",
		   'rs_forumOpenQuestions' : "Åbne spørgsmål",
		   'rs_feedOpenQuestions' : "Feed for disse åbne spørgsmål",
		   'rs_feedAnsweredQuestions' : "Feed for disse besvarede spørgsmål",
		   'rs_forumMessages' : "${0} beskeder",
		   'rs_forumLastAddedPost' : "Seneste indlæg af ${0}",
		   'rs_forumTopics' : "${0} emner",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Opret personlink",
		   'rs_quote' : "Citat",
		   'rs_labelColon' : "Etiket: ",
		   'rs_personColon' : "Person: ",
		   'rs_personLink' : "Personlink",
		   'rs_replace' : "Erstat",
		   'rs_inactivePerson' : "${0} (inaktiv)", // person's name (inactive)
		   'rs_PersonPicture' : "${0}s billede", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Ekstern bruger", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (ekstern bruger)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Billede af ${0} (ekstern bruger)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Denne bruger har adgang til filer og fællesskaber, som er delt eksternt.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Advisér andre personer",
		   'rs_messageColon' : "Besked: ",
		   'rs_notifyColon' : "Advisér: ",
		   'rs_notificationConfirm' : "Notifikationsbeskeden er sendt. ",
		   'rs_notificationFail' : "Notifikationsbeskeden er ikke sendt. Prøv igen senere, eller kontakt systemadministratoren, hvis problemet fortsætter.",
		   'rs_pickCommunity' : "Hent fra fællesskabsliste",
		   'rs_typeName' : "Skriv et navn",
		   'rs_typeToFilter' : "Skriv for at filtrere denne liste",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Skriv for at filtrere denne liste",
		   'rs_filterGroupLabel' : "Vælg gruppe",
		   'rs_noResults' : "Ingen resultater",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Viser ${0} resultater af ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Fjern",
		   /* Language Selector */
		   'rs_browser_setting' : "Browserindstilling",
		   'rs_customLangaugeLinkLabel' : "Tilpasset sprog",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Skift til side ${0} af ${1}",
		   "rs_jumpPageLabel" : "Skift til side",
		   'rs_pageNumLabel' : "Sidetal",
		   'rs_pageLabel' : "Side:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Emneord',
		   'rs_tagCloudToggleHint' : "Klik for at skjule eller vise",
		   'rs_tagCloudHelpAlt' : "Hjælp til emneord",
		   'rs_tagCloudNoTags' : "Ingen emneord endnu.",
		   'rs_tagCloudNoRecentTags' : "Ingen nylige emneord",
		   'rs_tagCloudNoTagsProfiles' : "Søg i adressekartoteket. Emneord, der er knyttet til de profiler, som søgningen returnerer, vil blive vist her.",
		   'rs_tagLoadingTags' : "Indlæser indhold",
		   'rs_tagCloudSelectedTags' : "Valgte emneord",
		   'rs_tagCloudSeachDesc' : "Søg efter et emneord",
		   'rs_tagCloudSeach' : "Søg",
		   'rs_tagCloudRelatedTags' : "Relaterede emneord",
		   'rs_tagCloudRelatedTagsDescription' : "Tilføj et relateret emneord for at indsnævre søgningen yderligere",
		   'rs_tagCloudError' : 'Der er opstået en fejl',
		   'rs_viewAsCloud' : "Sky",
		   'rs_viewAsCloudTitle' : "Vis emneord som en emnesky",
		   'rs_viewAsCloudDescription' : "Viser emneord som en emnesky",
		   'rs_viewAsList' : "Liste",
		   'rs_viewAsListTitle' : "Vis emneord opstillet i rækkefølge på en liste",
		   'rs_viewAsListDescription' : "Viser emneord opstillet i rækkefølge på en liste",
		   'rs_tagCloudViewAll' : "Gennemse",
		   'rs_tagCloudViewAllTitle' : "Gennemse alle emneord",
		   'rs_normalTags' : "Aktive emneord",
		   'rs_removeTag' : "Fjern emneordet fra de valgte filteremneord",
		   'rs_clearAll' : "Ryd alt",
		   'rs_searchInputDefault' : "Skriv for at søge efter et emneord",
		   'rs_searchInputTagSelected' : "Skriv et andet emneord",
		   'rs_relatedTagTitle' : "Vis søgeresultatet af emneordet ${0} med antallet ${1}",
		   'rs_removeTagTitle' : "Fjern emneordet ${0} fra de valgte filteremneord",
		   'rs_addTagTitle' : "Filtrér efter emneordet ${0} med antallet ${1}",
		   'rs_tagDialogCloseTile' : "Luk",
		   'rs_tagDialogTitle' : "Alle emneord",
		   'rs_tagDialogPageInfo' : "${0} - ${1} af ${2} emneord",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Gennemse grupper",
		   'rs_group_browse_groups_dialog_title' : "Gennemse grupper",
		   'rs_group_browse_find_groups' : "Søg efter grupper",
		   'rs_group_browse_add_button' : "Tilføj",
		   'rs_group_browse_cancel_button' : "Annullér",
		   'rs_group_browse_enter_string' : "Skriv for søge efter grupper",
		   'rs_group_browse_group_typeahead_label' : "Skriv et gruppenavn:",
		   'rs_group_browse_group_name' : "Gruppenavn:",
		   'rs_group_browse_results_label' : "Vælg en matchende gruppe:",
		   'rs_group_browse_parent_group_label' : "Du er i:",
		   'rs_group_browse_next_page' : "Næste side",
		   'rs_group_browse_previous' : "Forrige",
		   'rs_group_browse_next' : "Næste",
		   'rs_group_browse_paging' : "Side",
		   'rs_group_browse_previous_page' : "Forrige side",
		   'rs_group_browse_group_selected' : "Valgt gruppe:",
		   'rs_group_browse_group_no_groups' : "Denne gruppe indeholder ingen grupper",
		   'rs_group_browse_page_info' : "${0}-${1} af ${2}",
		   'rs_group_browse_page_info_alt' : "Matchende grupper ${0}-${1} af ${2}",
		   'rs_group_browse_remove_selection' : 'Fjern valg af indlejret gruppe: ${0}',
		   'rs_group_browse_paging' : "Side",
		   'rs_member_groups' : "Grupper",
		   'rs_member_members' : "Medlemmer",
		   'rs_member_no_results' : "Ingen resultater",
		   'rs_member_remove_group' : "Fjern ${0}",
		   'rs_member_add_to_community' : "Klik for at tilføje medlem",
		   'rs_member_remove_name' : "Klik for at fjerne medlem",
		   'rs_group_add_to_community' : "Klik for at tilføje gruppe",
		   'rs_group_remove_name' : "Klik for at fjerne gruppe",
		   'rs_group_name' : "Gruppenavn",
		   'rs_group_role' : "Grupperolle",
		   'rs_warning' : "Advarsel",
		   'rs_a11y_warning' : "Advarsel:",
		   'rs_messagebox_close_btn_title' : "Luk",
		   'rs_messagebox_close_btn_alt' : "Luk",
		   'rs_messagebox_error_icon_alt' : "Fejl",
		   'rs_messagebox_error_a11y_label' : "Fejl:",
		   'rs_messagebox_warning_icon_alt' : "Advarsel",
		   'rs_messagebox_warning_a11y_label' : "Advarsel:",
		   'rs_messagebox_info_icon_alt' : "Information",
		   'rs_messagebox_info_a11y_label' : "Information:",
		   'rs_messagebox_success_icon_alt' : "Udført",
		   'rs_messagebox_success_a11y_label' : "Udført:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Indsæt link til filer",
		   'rs_docpicker_label' : "Link til filer",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Download ${0}",
		   'rs_docpicker_viewdetails_text' : "Vis detaljer",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Vis detaljer om ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Fjern",
		   'rs_attachedfile_filename' : "Billede ${0}",
		   'rs_feedreader_warning' : "Advarsel: Dette link er beregnet til feedlæsere og vises muligvis forkert i din browser. Klik på OK for at fortsætte eller på Annullér for at vende tilbage til siden.",
		   'rs_search' : "Søg",
		   'rs_all_connections' : "Alt Connections-indhold",
		   'rs_advanced' : "Avanceret",
		   'rs_select_scope' : "Vælg søgeomfang",
		   'rs_icfixlayout' : {
		      button_label : "Omformatér",
		      dialog_title : "Omformatér indhold",
		      warning : "Advarsel",
		      reformat_save : "Omformatér og gem",
		      save_as_is : "Gem som det er",
		      cancel : "Annullér",
		      warn_layout : "Indholdet overskrider den maksimale skærmbredde.  Vil du omformatere automatisk til den tilgængelige plads?",
		      remember_decision : "Husk mit valg"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Der er opstået en fejl under deling af de valgte filer.",
		   'rs_sharefile_access_denied' : "Filen er slettet eller er ikke længere delt med dig.",
		   'rs_sharefile_invalid_request' : "Der er opstået en fejl under deling af de valgte filer.",
		   'rs_sharefile_sharing_intent_restriction' : "Filen kan kun deles inden for din organisation.",
		   'rs_sharefile_error_title' : "Fejl",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'I App Store',
		   'rs_mobileBanner_inGooglePlay' : 'I Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Åbn',
		   'rs_mobileBanner_view' : 'Vis',
		   'rs_mobileBanner_hide' : 'Skjul',

		   'rs_empty_column_placeholder' : 'Træk apps hertil.',
		   'rs_widget_loading_error_title' : 'Kan ikke vise widgetten',
		   'rs_widget_loading_error_message' : 'Prøv igen senere, eller kontakt systemadministratoren, hvis problemet fortsætter.',
		   'rs_widgets_loading_error_title' : 'Kan ikke vise widgetten eller widgetterne i dette fællesskab',
		   'rs_widget_misplacement_warning' : 'Denne app passer ikke til kolonnen. En fællesskabsejer kan flytte den til en anden kolonne eller fjerne den fra siden.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Titlen er for lang.',
		      empty_new_title : 'Titlen må ikke være tom.',
		      default_message : 'Kan ikke ændre titel på denne ${0}-app.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Titel:  ',
		   'rs_widget_title_change_direction' : 'Revidér titlen på denne ${0}-app.',
		   'rs_widget_title_change_title' : 'Revidér titel',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Invitér eller tilføj medlemmer",
		   'rs_vmmainContentDesc' : "Invitér medlemmer for at give dem mulighed for at deltage i fællesskabet. Tilføj medlemmer for at inkludere dem automatisk.",
		   'rs_vmtypeAheadLabel' : "Navn eller e-mail: ",
		   'rs_vmgroupTypeAheadLabel' : "Navn: ",
		   'rs_vmtypeAheadRoleLabel' : " som ",
		   'rs_vmgroupTypeAheadRoleLabel' : " som medlem ",
		   'rs_vmtaNoResults' : "Ingen resultater.",
		   'rs_vmtaHeader' : "sidehoved",
		   'rs_vmaddUser' : "Tilføj",
		   'rs_vmradioSectionTitle' : "Medlemsindstillinger:",
		   'rs_vmradioOne' : "Send invitation til at deltage i fællesskabet",
		   'rs_vmradioTwo' : "Tilføj automatisk brugere til fællesskab",
		   'rs_vmtwistyA' : "Tilføj en valgfri besked",
		   'rs_vmtwistyB' : "Fjern yderligere tekst",
		   'rs_vmmessage' : "Besked:",
		   'rs_vmtextAreaStartText' : "Skriv noget...",
		   'rs_vmcheckboxLabel' : "Send en kopi til mig",
		   'rs_vmsave' : "Gem",
		   'rs_vminvite' : "Invitér",
		   'rs_vmcancel' : "Annullér",
		   'rs_userContentTitle' : "Indtast oplysninger",
		   'rs_vmaddUser' : "Opret bruger",
		   'rs_vmback'	 : "Tilbage",
		   'rs_vmvisitor'	 : "Besøgende",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Klik her for at kopiere dette fællesskab',
			'rs_commpicker' : ''

});
