/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Csomópont információi: ",
	"INSTALLED": "A telepített szolgáltatások ellenőrzése",
	"RESUMETOKENS": "A folytatási tokenek ellenőrzése",
	"SEEDLISTS": "A kezdőértéklisták elérhetőségének ellenőrzése",
	"CALENDARS": "Az ütemezési naptárak megfelelő beállításának ellenőrzése",
	"VARIABLES": "A WebSphere változók beállításának ellenőrzése",
	"TASKS": "Engedélyezett indexelési feladatok ellenőrzése",
	"INDEXFILES": "Szükséges fájlok indexmappájának ellenőrzése",
	"LOGS": "Hibanaplók áttekintése",
	"CONFIGFILES": "Konfigurációs fájlok áttekintése",
	"DICTIONARIES": "Az engedélyezett szótárak számának ellenőrzése",
	"SYNC": "A csomópontok állapotának ellenőrzése",
	"DBRECORDS": "Az adatbázisrekordok ellenőrzése",
	"INSTALLEDMSG": "Az alábbi szolgáltatás telepítve van: ",
	"RESUMETOKENSMSG": "A következő folytatási tokenje: ",
	"SEEDLISTSMSG": "Nem lehetett beolvasni a következő kezdőértéklistáját: ",
	"CALENDARSMSG": "Naptárütemezés ellenőrzése sikeres volt: ",
	"VARIABLESMSG": "Változó: ",
	"TASKSMSG": "A következő feladat engedélyezett: ",
	"INDEXFILESMSG" : "A következő fájlok szerepelnek a keresési indexmappában: ",
	"LOGSMSG" : "Az alábbi hibaüzenetek áttekintése: ",
	"CONFIGFILESMSG" : "A következő konfigurációs fájlok találhatók: ",
	"DICTIONARIESMSG" : "Az engedélyezett szótárak száma: ",
	"INSYNC": "Minden csomópont szinkronban van",
	"OUTOFSYNC": "A nem szinkronban lévő csomópontok száma: ",
	"NOTBLOCKED": "Nincs blokkolt csomópont",
	"BLOCKED": "A blokkolt csomópontok száma: ",
	"INDATE": "Minden csomópont aktuális",
	"OUTOFDATE": "Az elavult csomópontok száma: ",
	"NUMOFDOCS": "Az adatbázisban lévő dokumentumok száma ",
	"FILESTOCONVERT": "Az átalakítandó fájldokumentumok száma ",
	"CONVERTEDFILES": "Az átalakított fájlok száma ",
	"TOTALFILES": "Az adatbázisban lévő összes fájl száma ",
	"ERROR":"Hiba",
	"ERROR_PREFIX":"Hiba:",
	"INFO":"Információk",
	"INFO_PREFIX":"Információk:",
	"WARNING":"Figyelmeztetés",
	"WARNING_PREFIX":"Figyelmeztetés:",
	"LOADING_MESSAGE": "Betöltés",
	"SERVER_STATUS": "Szerverállapot",
	"INITIAL_INDEXING_EXCEPTIONS": "Kezdeti indexelési kivételek",
	"SYS_OUT_EXCEPTIONS": "SystemOut napló kivételek",
	"SEEDLIST_VALIDATE": "Kezdőértéklisták érvényesítése",
	"ERRORS_DURING_INITIAL_INDEXING":"Az alábbi kivételek történtek a kezdeti index létrehozása közben",
	"CRAWL_FAILED": "A következő szolgáltatásnak nem járható be minden adata: ",
	"EXCEPTION_ENCOUNTERED": "A bejárás a következő üzenettel meghiúsult: ",
	"SAND_VALIDATE": "SAND érvényesítés",
	"CHECK_FOR_SAND_FILES":"A SAND fájlok keresése",
	"IS_FILE_AVAILABLE":"A fájl létrehozásának ellenőrzése: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Az alábbi kivételek történtek a kezdeti index létrehozása közben",
	"CRAWL_FAILED":"A következő szolgáltatásnak nem járható be minden adata: ",
	"EXCEPTION_ENCOUNTERED":"A bejárás a következő üzenettel meghiúsult: "
})

