/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informacije za čvor: ",
		"INSTALLED": "Proveravanje instaliranih usluga",
		"RESUMETOKENS": "Proveravanje tokena za nastavljanje",
		"SEEDLISTS": "Proveravanje da su dostupne liste početnih vrednosti",
		"CALENDARS": "Proveravanje da su kalendari rasporeda ispravno konfigurisani",
		"VARIABLES": "Proveravanje da su podešene promenljive WebSphere",
		"TASKS": "Proveravanje omogućenih zadataka indeksiranja",
		"INDEXFILES": "Proveravanje fascikle indeksa za potrebne datoteke",
		"LOGS": "Redigovanje evidencija zbog grešaka",
		"CONFIGFILES": "Redigovanje datoteka konfiguracije",
		"DICTIONARIES": "Proveravanje broja rečnika koji su omogućeni",
		"SYNC": "Proveravanje statusa čvorova",
		"DBRECORDS": "Proveravanje zapisa baze podataka",
		"INSTALLEDMSG": "Instalirana je sledeća usluga: ",
		"RESUMETOKENSMSG": "Token za nastavljanje za: ",
		"SEEDLISTSMSG": "Nije bilo moguće nabaviti listu početnih vrednosti za: ",
		"CALENDARSMSG": "Obavljena provera kalendara rasporeda: ",
		"VARIABLESMSG": "Promenljiva: ",
		"TASKSMSG": "Sledeći zadatak je omogućen: ",
		"INDEXFILESMSG" : "Sledeće datoteke nalaze se u fascikli indeksa pretrage: ",
		"LOGSMSG" : "Pregledaj sledeće poruke o grešci: ",
		"CONFIGFILESMSG" : "Pronađene su sledeće datoteke konfiguracije: ",
		"DICTIONARIESMSG" : "Broj omogućenih rečnika je: ",
		"INSYNC": "Svi čvorovi se sinhronizuju",
		"OUTOFSYNC": "Broj čvorova van sinhronizacije je: ",
		"NOTBLOCKED": "Nema blokiranih čvorova",
		"BLOCKED": "Broj blokiranih čvorova je: ",
		"INDATE": "Svi čvorovi su ažurirani",
		"OUTOFDATE": "Broj čvorova koji nisu ažurirani je: ",
		"NUMOFDOCS": "Broj dokumenata u bazi podataka je ",
		"FILESTOCONVERT": "Broj dokumenata datoteke za konvertovanje je ",
		"CONVERTEDFILES": "Broj konvertovanih datoteka je ",
		"TOTALFILES": "Ukupan broj datoteka u bazi podataka ",
		"ERROR":"Greška",
		"ERROR_PREFIX":"Greška:",
		"INFO":"Informacije",
		"INFO_PREFIX":"Informacije:",
		"WARNING":"Upozorenje",
		"WARNING_PREFIX":"Upozorenje:",
		"LOADING_MESSAGE": "Učitava se…",
		"SERVER_STATUS": "Status servera",
		"INITIAL_INDEXING_EXCEPTIONS": "Izuzeci inicijalnog indeksiranja",
		"SYS_OUT_EXCEPTIONS": "Izuzeci evidencije SystemOut",
		"SEEDLIST_VALIDATE": "Validacija lista početnih vrednosti",
		"ERRORS_DURING_INITIAL_INDEXING":"Tokom kreiranja inicijalnog indeksa došlo je do sledećih izuzetaka",
		"CRAWL_FAILED": "Nijedan podatak za sledeću uslugu nije mogao biti pretražen na vebu: ",
		"EXCEPTION_ENCOUNTERED": "Pretraga na vebu nije uspela za sledeću poruku: ",
		"SAND_VALIDATE": "SAND validacija",
		"CHECK_FOR_SAND_FILES":"Proveravanje SAND datoteka",
		"IS_FILE_AVAILABLE":"Proveravanje da li je datoteka kreirana: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Tokom kreiranja inicijalnog indeksa došlo je do sledećih izuzetaka",
		"CRAWL_FAILED":"Nijedan podatak za sledeću uslugu nije mogao biti pretražen na vebu: ",
		"EXCEPTION_ENCOUNTERED":"Pretraga na vebu nije uspela za sledeću poruku: "
});

