/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "A cím megadása kötelező.",
	nourl: "Az URL megadása kötelező.",
	fileSchema: "Ha távoli vagy helyi fájlhivatkozást kíván hozzáadni, akkor a következő formátumoknak kell megfelelni: file://remote_path vagy file:///local_path.",
	invalidUrl: "Ez nem érvényes közösségi URL.",
	invalidTagChar: "A megadott címkelista a következő érvénytelen karaktert tartalmazza: &. Távolítsa el ezt a karaktert a címkelistából.",
	txtHelp: "Súgó",
	txtHelpTags: "Címkék súgó",
	txtHelpTagsClose: "Címkék súgójának bezárása",
	tagsall: "Mind",
	tagsyours: "Saját",
	tagsrecent: "Friss: ",
	tagspopular: "Népszerű: ",
	tagsrecommended: "Ajánlott: ",
	nothingselected: "Ki kell választani egy közösséget.",
	nothingselected_activity: "Ki kell választani egy tevékenységet.",
	nothingselected_blogs: "Ki kell választania egy blogot.",
	nothingselected_all: "Nincs kiválasztva szolgáltatás vagy bejegyzés, a könyvjelző nem lesz mentve.",
	nothingFeedselected: "Nincs kiválasztva szolgáltatás vagy bejegyzés, a hírfolyam nem lesz mentve.",
	alertDialogTitle: "Üzenet",
	alertDialogOK: "OK",
	expand: "Kattintson ide a szakasz kibontásához",
	collapse: "Kattintson ide a szakasz összezárásához",
	discussThis: "Megvitatás",
	by: "szerző:",
	posted: "Beküldve:",
	attachments: "Mellékletek",
	communityForum: "Közösségi fórum",
	notCommunityPage: "Az aktuális weboldal nem érvényes közösségi weboldal. Kapcsolódó közösség létrehozásához a közösség címét, hivatkozását és leírását megadhatja saját kezűleg.",
	privateCommunityNotice: "Ez a közösség zárt, és csak a tagjai láthatják.",
	forumNameHint : "Írjon be egy fórumnevet",
	formDescriptionHint:"Írja le, hogy ez a kapcsolódó közösség miért lehet érdekes a közössége számára.",
	information : "Információk",
	error : "Hiba",
	success : "Sikerült",
	warning : "Figyelmeztetés",
	informationColon : "Információk:",
	successColon : "Sikerült:",
	warningColon : "Figyelem:",
	errorColon : "Hiba:",
	feedAlreadyExist : "A hírfolyam már létezik a közösségben.",
	bookmarkAlreadyExist : "A könyvjelző már létezik a közösségben.",
	mentionAuthWarning:"A következő említett személyek nem tekinthetik meg az üzenetet, mert nem tagjai a közösségnek:",
	mentionAuthForumWarning:"A következő említett személyek nem tekinthetik meg az üzenetet, mert nem férnek hozzá a fórumhoz:",
	exceedDescLength: "A megadott leírás túl hosszú.",
	communities_checked:"${0} közösség kiválasztva",
	activities_checked:"${0} tevékenység kiválasztva",
	blogs_checked:"${0} blog kiválasztva"
})
