/* Copyright IBM Corp. 2011, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknite ovdje za pregled podsjetnice",
	"label.semtag.hover.alt" : "Kliknite za pregled podsjetnice za {0}",
	"label.semtag.hover.altA11Y" : "Kliknite ovdje ili pritisnite control-enter za pregled podsjetnice",
	"label.personcard.dialog.title" : "Podsjetnica za {0}",

	"errorDefaultMsg2" : "Došlo je do greške, kontaktirajte vašeg sistemskog administratora",

	"loadingSTStatus" : "Učitavanje Sametime statusa...",
	"noStatuAvailable" : "Nema dostupnog Sametime statusa",

	"label.personcard.cardnomarkup" : "Podsjetnici se nije moglo pristupiti",
	"label.inactive.user.msg" : "Ova osoba više nije aktivan korisnik",
	"label.message.information" : "Informacije:",
	"label.personcard.noprofilemsg" : "Profil ne postoji za ovu osobu",
	"label.personcard.cardreqexpired" : "Zahtjev za dobivanjem podsjetnice je istekao",

	"label.bizcard.applinks.less" : "Pokaži manje",
	"label.bizcard.applinks.more" : "Pokaži više",

	"label.personcard.activitieslink" : "Aktivnosti",
	"label.personcard.activitieslink.title" : "Kliknite ovdje da vidite dijeljene aktivnosti",
	"label.personcard.blogslink" : "Blogovi",
	"label.personcard.blogslink.title" : "Kliknite ovdje da vidite blog ove osobe",
	"label.personcard.communitieslink" : "Zajednice",
	"label.personcard.communitieslink.title" : "Kliknite ovdje da vidite zajednice ove osobe",
	"label.personcard.dogearlink" : "Bukmarci",
	"label.personcard.dogearlink.title" : "Kliknite ovdje da vidite bukmarke ove osobe",
	"label.personcard.fileslink" : "Datoteke",
	"label.personcard.fileslink.title" : "Kliknite ovdje da vidite dijeljene datoteke ove osobe",
	"label.personcard.forumlink" : "Forumi",
	"label.personcard.forumlink.title" : "Kliknite ovdje da vidite objave ove osobe na forumu",
	"label.personcard.homepagelink" : "Dom",
	"label.personcard.homepagelink.title" : "Kliknite ovdje da vidite početnu stranicu ove osobe",
	"label.personcard.mobilelink" : "Prenosno",
	"label.personcard.mobilelink.title" : "Kliknite ovdje da vidite prenosnu stranicu ove osobe",
	"label.personcard.newslink" : "Novosti",
	"label.personcard.newslink.title" : "Kliknite ovdje da vidite novosti za ovu osobu",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknite ovdje da vidite profil ove osobe",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknite ovdje da vidite quickr dijeljenja ove osobe",
	"label.personcard.wikislink" : "Wikiji",
	"label.personcard.wikislink.title" : "Kliknite ovdje da vidite wikije ove osobe",

	"personCardMoreActions" : "Više akcija",
	"personCardMoreActionsAltText" : "Kliknite za izbornik akcija",

	"label.bizcard.dismiss": "Pritisnite escape da biste odbacili ovu podsjetnicu.",

	"personCardAddAsColleagues" : "Poziv u moju mrežu",
	"personCardAddAsMyColleagues" : "Poziv u moju mrežu",
	"personCardFollow" : "Prati",
	"personCardUnfollow" : "Zaustavi praćenje",
	"personCardChat" : "Razgovor",
	"personCardCall" : "Poziv",
	"personCardSendMail" : "Pošalji e-mail",
	"personCardSendEMail" : "Pošalji e-mail",
	"personCardProxyStatusAvailable" : "Dostupan sam",
	"personCardDownloadVCard" : "Preuzmi vCard",

	"friends" : "Mreža",
	"friendsFullPageTitle" : "Mreža",
	"friendsMenuTitleAllContacts" : "Svi mrežni kontakti",
	"friendsMenuTitleMyContacts" : "Moji mrežni kontakti",
	"friendsInvitations" : "Pozivnice",
	"friendsMenuTitleInCommon" : "Zajednički ljudi",
	"friendsShowAllCommonFriends" : "Pokaži sve...",
	"friendsViewAllFriends" : "Pregled svih ({0})",
	"friendsSendFriendRequest" : "Pošalji zahtjev",
	"friendsNoFriends" : "Nema mrežnih kontakata pridruženih ovom profilu",
	"friendsColleaguesInvite" : "Pozovite {0} da bude vaš mrežni kontakt",
	"friendsColleaguesFor" : "Mrežni kontakti za {0}",
	"friendsNewInv" : "{0} nova pozivnica",
	"friendsNewInvs" : "{0} novih pozivnica",
	"friendsLoading" : "Učitavanje mreže...",
	"friendsLoadingInv" : "Učitavanje pozivnica...",
	"friendsSelectFriendForRemoval" : "Izaberite kontakte koje želite najprije ukloniti.",
	"friendsRemoved" : "Mrežni kontakt(i) uklonjeni.",
	"friendsInvSent" : "Nisu poslate pozivnice jer je pozivnica već na čekanju.",
	"friendsRemovedSelected" : "Ukloni iz moje mreže",
	"friendsSortByDisplayName" : "Ime za prikaz",
	"friendsSortByRecent" : "Nedavno",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "Alternativni e-mail:",
	"friendsNewInvitationsCount" : "Imate {0} novih pozivnica",
	"friendsNoInv" : "Nema pozivnica",
	"friendsInCommonSingle" : "Imate {0} zajednički mrežni kontakt",
	"friendsInCommonMulti" : "Imate {0} zajedničkih mrežnih kontakata",
	"friendsIncludeMsgForInv" : "Uključite poruku uz vašu pozivnicu:",
	"friendsInitialMsgForInv" : "Želim vas dodati na listu kontakata mreže mojih veza.",
	"friendsSendInvAction" : "Pošalji pozivnicu",
	"friendsCancelInvAction" : "Odustani",
	"friendsAcceptAction" : "Prihvati",
	"friendsIgnoreAction" : "Zanemari",
	"friendsYouExceedTextLimit" : "Vaša poruka poziva je predugačka. Može biti najviše {1} znakova. U ovom polju ima {0} znakova.",
	"friendsCannotAddYourself" : "Ne možete sami sebe dodati kao mrežni kontakt.",
	"friendsIsYourColleague" : "{0} je vaš mrežni kontakt",
	"friendsRecentlyAdded" : "Osobe koje ste nedavno dodali u vašu mrežu.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Kliknite da biste srušili sekciju mreže",
	"friendsExpandWidget" : "Kliknite da biste proširili sekciju mreže",
	"friendsIsInYourNetwork" : "{0} je u vašoj mreži.",
	"friendsActionsFor" : "Akcije za mrežu",
	"friendsInviteFollowError" : "Došlo je do greške za vrijeme pokušaja praćenja {0}",
	"friendsInviteTagError" : "Došlo je do greške za vrijeme pokušaja označavanja {0}",
	"friendsPleaseLogIn" : "Molim, prijavite se da biste pozvali ljude u vašu mrežu",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Poziv u vašu mrežu nije moguć jer je {0} već u vašoj mreži.",
	"friendsInviteAddTagsFor" : "Dodaj oznake za {0}:",
	"friendsInviteAlsoFollow" : "Takođe prati",
	"friendsInviteReceiveUpdates" : "(primaj ažuriranja)",
	"friendsInviteUpdatesDescription" : "Primite ažuriranja o osobama koje pratite na početnoj stranici i u sažetku e-mailova.",
	"friendsInviteFollowHelp": "Za više informacija pogledajte {0}Praćenje osoba{1}.",
	"friendsNetwork" : "Mreža",
	"friendsMyNetwork" : "Mreža",
	"friendsNetworkFor" : "Mreža za {0}",
	"friendsRemoveSelected" : "Ukloni izabrano",
	"friendsRemoveSelectedTip" : "Kliknite za uklanjanje izabranih ljudi iz vaše mreže.",
	"friendsNetworkInCommon" : "Imate {0} zajedničkih mrežnih veza.",
	"friendsAddToMyNetwork" : "Želim vas dodati u mrežu mojih veza.",
	"friendsInvite" : "Poziv u moju mrežu",
	"friendsInvitePerson" : "Pozovite {0} u svoju mrežu",
	"friendsInviteMessage" : "Želim vas dodati u mrežu mojih veza.",
	"friendsInvitedEmailSubject" : "[Profili] Pozvani ste da pristupite mojoj mreži",
	"friendsInvitedEmailMsg1" : "vas je pozvao da postanete mrežni kontakt sa sljedećom porukom uključenom u pozivnicu:",
	"friendsInvitedEmailMsg2" : "Otvorite svoju stranicu Poziv s mreže",
	"friendsInvitedEmailMsg3" : "Želim vas dodati u moju mrežu.",
	"friendsInvitedEmailMsg4" : "{0} vas je pozvao da postanete mrežni kontakt:",
	"friendsInvitedEmailMsg5" : "{0} vas je pozvao da postanete mrežni kontakt sa sljedećom porukom uključenom u pozivnicu:",
	"friendsInviteLegalNote" : "Slanjem ove pozivnice, slažete se da {0} može komentirati na vašoj ploči profila.",
	"friendsInviteFailed" : "Zbog greške na serveru, gostu nije poslana e-mail obavijest. Međutim, gost će i dalje moći prihvatiti vašu pozivnicu kroz Web aplikaciju Profili."
})

