/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Филтриране по:",
		"SHOW":"Показване:",
		"ACL_FILTER_LABEL":"Филтриране по видимост",
		"PARENT_FILTER_LABEL":"Филтриране по контейнер",
		"TYPE_FILTER_LABEL":"Филтриране по тип",
		"PAGING_TOP":"Основно страниране",
		"PAGING_BOTTOM":"Вторично страниране",
		"PREVIOUS":"Назад",
		"NEXT":"Напред",
		"PAGE":"Страница {0} от {1}",
		"PAGE_COLON":"Страница:",
		"RESULTS":"{span}{0}-{1}{/span} от {2}",
		"ITEMS":"{0} елемента",
		/* Application names */
		"ACTIVITIES":"Дейности",
		"BLOGS":"Блогове",
		"CALENDAR":"Календар",
		"COMMUNITIES":"Общности",
		"BOOKMARKS":"Отметки",
		"DOGEAR":"Отметки",
		"EVENTS":"Събития",
		"FILES":"Файлове",
		"FORUMS":"Форуми",
		"PROFILES":"Профили",
		"WIKI":"Wiki модули",
		"WIKIS":"Wiki модули",
		"FEEDS":"Информационни канали",
		"STATUS_UPDATES":"Актуализации на състоянието",
		"ONECOMMENT":"1 коментар",
		"COMMENTS":"{0} коментара",
		"ONEPERSON":"1 лице",
		"PEOPLE":"{0} Лица",
		"TAGS":"Етикети:",
		"TAGSMORE":"и още {0}",
		"NORESULTSMESSAGE":"Няма намерени резултати за това търсене",
		"JAN":"януари",
		"FEB":"февруари",
		"MAR":"март",
		"APR":"април",
		"MAY":"май",
		"JUN":"юни",
		"JUL":"юли",
		"AUG":"август",
		"SEP":"септември",
		"OCT":"октомври",
		"NOV":"ноември",
		"DEC":"декември",
		"NO_CONTACT":"Търсенето не е изпълнено, защото няма връзка със сървъра",
		"SERVER_ERROR":"Търсенето не е изпълнено поради грешка в сървъра",
		"SORT_BY":"Сортиране по:",
		"SORT_RELEVANCE":"Съответствие",
		"SORT_DATE":"Дата",
		"SORT_LAST_UPDATED":"Последно актуализирано",
		"SORT_DUE_DATE":"Краен срок",
		"SORT_VISITS":"Посещения",
		"SORT_COMMENTS":"Коментари",
		"SORT_RECOMMENDATION":"Харесвания",
		"SORT_POPULARITY":"Популярност",
		"SORT_FIRSTNAME":"Име",
		"SORT_LASTNAME":"Фамилия",
		"SORT_DOWNLOADS":"Изтегляния",
		"SORT_TYPE":"Тип",
		"SORT_SIZE":"Размер",
		"SORT_TITLE":"Заглавие",
		"PRIVATE":"Частни",
		"MODERATED":"Модерирано",
		"COMMUNITY_ACTIVITY":"Дейности на общността",
		"COMMUNITY_BLOG":"Блог на общност",
		"COMMUNITY_FILE":"Общностен файл",
		"COMMUNITY_FORUM":"Форум на общност",
		"COMMUNITY_WIKI":"Wiki модул на общност",
		"COMMUNITY_FEED":"Информационен канал на общност",
		"COMMUNITY_BOOKMARK":"Отметка на общност",
		"NO_TAG":"Все още няма етикети",
		"NO_DATE":"Още няма дати",
		"NO_PEOPLE":"Още няма лица",
		"REMOVE_FILTER_LABEL":"Щракнете за премахване",
		"REMOVE_FILTER_TITLE":"Премахване",
		"REMOVE_FILTER_TOOLTIP":"Премахване на този филтър",
		"COMMENT_ON":"Коментиране на:",
		"EXPAND_COLLAPSE":"Щракнете, за да разгънете/сгънете",
		"EXPAND":"Разгъване",
		"COLLAPSE":"Сгъване",
		"EXPAND_MONTHS_FILTER":"Разгъване на филтъра за месеци за година {0}",
		"SORT_RELEVANCE_LABEL":"Щракнете, за да сортирате по съответствие",
		"SORT_DATE_LABEL":"Щракнете за сортиране по дата",
		"SORT_UPDATED_LABEL":"Щракнете, за да сортирате по последни актуализации",
		"SORT_DUE_LABEL":"Щракнете, за да сортирате по краен срок",
		"SORT_VISITS_LABEL":"Щракнете, за да сортирате по брой посещения",
		"SORT_COMMENTS_LABEL":"Щракнете, за да сортирате по брой коментари",
		"SORT_RECOMMENDATIONS_LABEL":"Щракнете, за да сортирате по брой харесвания",
		"SORT_POPULARITY_LABEL":"Щракнете за сортиране по популярност",
		"SORT_FIRST_NAME_LABEL":"Щракнете, за да сортирате по дадено име",
		"SORT_LAST_NAME_LABEL":"Щракнете, за да сортирате по фамилия",
		"RATING":"Харесвания",
		"GRADUATED":"Завършили",
		"ONEVOTE":"1 глас",
		"VOTES":"{0} гласа",
		"BOOKMARK_THIS_RESULT":"Добавяне в отметка",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (неактивен)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} добавени в отметка лица",
		/* eg from an Activity */
		"FROMANACTIVITY":"от дейност",
		"FROMABLOG":"от блог",
		"FROMANIDEATIONBLOG":"от блог за идеация",
		"FROMANEVENT":"от събитие",
		"FROMAFORUM":"от форум",
		"FROMAWIKI":"от Wiki модул",
		"FROMACOMMUNITY":"от общност",
		"FROMXCOMMUNITIES":"от {0} Общности",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Дейност",
		"BLOG_ALONE":"Блог",
		"IDEATIONBLOG_ALONE":"Блог за идеация",
		"ENTRY_ALONE":"Запис",
		"EVENT_ALONE":"Събитие",
		"FORUM_ALONE":"Форум",
		"WIKI_ALONE":"Wiki модул",
		"COMMUNITY_ALONE":"Общност",
		"XCOMMUNITIES_ALONE":"{0} Общности",
		"SHAREDCOMMUNITIES":"Споделено с тези общности",
		"INACOMMUNITY":"в общност",
		"LASTUPDATED":"Индексът на търсенето последно е актуализиран:",
		"NODESCRIPTION":"Няма описание или резюме за този резултат.",
		"ATTACHMENT":"Прикачен файл:",
		"ACTIVITY":"Дейност:",
		"ACTIVITYBOOKMARK":"Отметка за дейността:",
		"ACTIVITYCOMMENT":"Коментар за дейността:",
		"ACTIVITYENTRY":"Запис от дейността:",
		"ACTIVITYSECTION":"Раздел от дейността:",
		"ACTIVITYTODO":"Задача в дейността:",
		"BLOG":"Блог:",
		"BLOGENTRY":"Запис в блога:",
		"BLOGCOMMENT":"Коментар в блога:",
		"BOOKMARK":"Отметка:",
		"CALENDAREVENT":"Събитие:",
		"CATEGORY":"Категория:",
		"COMMENT":"Коментар:",
		"COMMUNITY":"Общност:",
		"ENTRY":"Запис:",
		"EVENTDATEON":"На: {0}",
		"EVENTISALLDAY":"Целодневно събитие",
		"EVENTREPEATS":"Повторения",
		"FEED":"Информационен канал:",
		"FILE":"Файл:",
		"FORUM":"Форум:",
		"FORUMCATEGORY":"Категория във форума:",
		"FORUMTOPIC":"Тема във форум:",
		"IDEA":"Идея:",
		"IDEACOMMENT":"Коментар за идея:",
		"IDEATIONBLOG":"Блог за идеация:",
		"PAGE":"Страница:",
		"PROFILE":"Профил:",
		"SECTION":"Раздел:",
		"STATUSUPDATE":"Актуализация на състоянието",
		"STATUSUPDATE_PREFIX":"Актуализация на състоянието:",
		"TOPIC":"Тема:",
		"TOPIC_WITH_ATTACHMENT":"Тема",
		"WIKITYPE":"Wiki модул:",
		"WIKIPAGE":"Wiki страница:",
		"WIKIFILE":"Wiki прикачен файл:",
		"SEARCH":"Търсене:",
		"TODO":"Задачи:",
		"ALLRESULTS":"Всички резултати",
		"PUBLICCONTENT":"Публично съдържание",
		"MYCONTENT":"Моето съдържание",
		"RESULTNOTFOUND":"Не намерихте това, което търсите?",
		"TEMPDIFFICULTIES":"Бележка: Поради временни трудности при индексиране, Вашето търсене не включи {0}, които бяха променени през последния(ите) {1} ден(дни).",
		"TRYLATER":"Моля, опитайте отново по-късно.",
		"MULTIPLETEMPDIFFICULTIES":"Бележка: Поради временни трудности при индексиране, Вашето търсене не включи {0}, които бяха променени наскоро",
		"YOUAREAUTHOR":"Вие не сте автор",
		"YOUARECONTRIBUTOR":"Вие сте сътрудник",
		"YOUAREOWNER":"Вие сте собственик",
		"YOUAREMEMBER":"Вие сте член",
		/* Profiles */
		"MYNETWORK":"Моята мрежа",
		"ALLPEOPLE":"Всички лица",
		"EXCLUDEINACTIVE":"Изключи неактивните лица",
		"PHONE":"Телефон:",
		"EMAIL":"Имейл:",
		/* Communities */
		"ALLCOMMUNITIES":"Всички общности",
		"PUBLICCOMMUNITIES":"Публични общности",
		"MYCOMMUNITIES":"Моите общности",
		"EVERYTHINGCOMMUNITIES":"Всичко от общностите",
		"COMMUNITIESONLY":"Общности",
		"COMMUNITIESCONTENT":"Съдържание от общностите",
		/* Activities */
		"ALLACTIVITIES":"Всички дейности",
		"PUBLICACTIVITIES":"Публични дейности",
		"MYACTIVITIES":"Моите дейности",
		"EVERYTHINGACTIVITIES":"Всичко от дейностите",
		"ACTIVITIESONLY":"Дейности",
		"SECTIONSACTIVITIES": "Раздели от дейностите",
		"ENTRIESACTIVITIES":"Записи от дейностите",
		"TODOSACTIVITIES":"Задачи от дейностите",
		"BOOKMARKSACTIVITIES":"Отметки от дейностите",
		"FILESACTIVITIES":"Прикачени файлове от дейностите",
		"ALLTYPESACTIVITIES":"Всички типове дейности",
		"COMMUNITYACTIVITIES":"Дейности от общностите",
		"STANDALONEACTIVITIES":"Самостоятелни дейности",
		/* Forums */
		"ALLFORUMS":"Всички форуми",
		"PUBLICFORUMS":"Публични форуми",
		"MYFORUMS":"Моите форуми",
		"EVERYTHINGFORUMS":"Всичко от форуми",
		"FORUMSONLY":"Форуми",
		"TOPICSFORUMS":"Теми във форума",
		"FORUMCATEGORIES": "Категории на форума",
		"FILESFORUMS":"Прикачени файлове от форуми",
		"ALLTYPESFORUMS":"Всички типове форуми",
		"COMMUNITYFORUMS":"Форуми от общности",
		"STANDALONEFORUMS":"Самостоятелни форуми",
		/* Blogs */
		"ALLBLOGS":"Всички блогове",
		"PUBLICBLOGS":"Публични блогове",
		"MYBLOGS":"Моите блогове",
		"EVERYTHINGBLOGS":"Всичко от блогове",
		"BLOGSONLY":"Блогове",
		"ENTRIESBLOGS":"Записи в блог",
		"FILESBLOGS":"Прикачени файлове от блогове",
		"EVERYTHINGIDEATIONBLOGS":"Всичко от блоговете за идеация",
		"BLOGSIDEATIONBLOGS":"Блогове за идеация",
		"BLOGSIDEAS":"Идеи",
		"ALLTYPESBLOGS":"Всички типове блогове",
		"COMMUNITYBLOGS":"Блогове от общности",
		"COMMUNITYIDEATIONBLOGS":"Блогове за идеация от общности",
		"STANDALONEBLOGS":"Самостоятелни блогове",
		/* Bookmarks */
		"ALLBOOKMARKS":"Всички отметки",
		"PUBLICBOOKMARKS":"Публични отметки",
		"MYBOOKMARKS":"Моите отметки",
		"ALLTYPESBOOKMARKS":"Всички типове отметки",
		"COMMUNITYBOOKMARKS":"Отметки от общности",
		"STANDALONEBOOKMARKS":"Самостоятелни отметки",
		/* Files */
		"ALLFILES":"Всички файлове",
		"PUBLICFILES":"Публични файлове",
		"MYFILES":"Моите файлове",
		"ALLTYPESFILES":"Всички типове файлове",
		"COMMUNITYFILES":"Файлове от общности",
		"STANDALONEFILES":"Самостоятелни файлове",
		"NUMDOWNLOADS":"{0} Изтегляния",
		/* Wikis */
		"ALLWIKIS":"Всички Wiki модули",
		"PUBLICWIKIS":"Публични Wiki модули",
		"MYWIKIS":"Моите Wiki модули",
		"EVERYTHINGWIKIS":"Всички от Wiki модулите",
		"WIKISONLY":"Wiki модули",
		"PAGESWIKIS":"Wiki модули",
		"FILESWIKIS":"Прикачени файлове от Wiki модулите",
		"ALLTYPESWIKIS":"Всички типове Wiki модули",
		"COMMUNITYWIKIS":"Wiki модули от общности",
		"STANDALONEWIKIS":"Самостоятелни Wiki модули",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Всички актуализации на състоянието",
		"PUBLICSTATUSUPDATES":"Публични актуализации на състоянието",
		"MYSTATUSUPDATES":"Моите актуализации на състоянието",
		"ALLTYPESSTATUSUPDATES":"Всички типове актуализации на състоянието",
		"COMMUNITYSTATUSUPDATES":"Актуализации на състоянието от общностите",
		"STANDALONESTATUSUPDATES":"Актуализации на състоянието от профилите",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Този URL адрес е добавен в отметки от брой потребители",
		"BOOKMARKEDCOMMUNITY":"Тази общност е добавена в отметки от брой потребители",
		"BOOKMARKEDPROFILE":"Този профил е добавен в отметки от брой потребители",
		"BOOKMARKEDBLOG":"Този блог е добавен в отметки от брой потребители",
		"COMMUNITYBLOG":"Това е блог в рамките на общност",
		"BOOKMARKEDACTIVITY":"Тази дейност е добавена в отметки от брой потребители",
		"COMMUNITYACTIVITY":"Това е дейност в рамките на общност",
		"BOOKMARKEDFILE":"Този файл е добавен в отметки от брой потребители",
		"COMMUNITYFILE":"Това е файл в рамките на общност",
		"BOOKMARKED":"Този Wiki модул е добавен в отметки от брой потребители",
		"COMMUNITYWIKI":"Това е Wiki модул в рамките на общност",
		"BOOKMARKEDFORUM":"Този форум е добавен в отметки от брой потребители",
		"COMMUNITYFORUM":"Това е форум в рамките на общност",
		"ALLTAGANDTTILE":"За да видите всички заглавия и етикети за този URL адрес, щракнете върху този бутон",
		"TAGS_ARE_FROM":"Резултатът от търсенето може да включва етикети от:",
		"BOOKMARKS_TITLE":"Отметки",
		"COMMUNITIES_TITLE":"Общности",
		"ACTIVITIES_TITLE":"Дейности",
		"HELP":"Помощ",
		"MORESTATUSUPDATES":"Преглед на повече съвпадения на актуализации на състоянието",
		"TITLE_PREFIX":"заглавие:",
		"LATEST_MESSAGE":"Последно съобщение",
		"LATEST_STATUS_UPDATE":"Последно актуализиране на състоянието",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Последно актуализиране на състоянието на общност",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Последно актуализиране на състоянието на общности",
		"SEARCH_RESULTS":"Резултати от търсене в цялото съдържание",
		"ACTIVITIES_SEARCH_RESULTS":"Резултати от търсене в дейности",
		"BLOGS_SEARCH_RESULTS":"Резултати от търсене в блогове",
		"BOOKMARKS_SEARCH_RESULTS":"Резултати от търсене в отметки",
		"COMMUNITIES_SEARCH_RESULTS":"Резултати от търсене в общности",
		"FILES_SEARCH_RESULTS":"Резултати от търсене във файлове",
		"FORUMS_SEARCH_RESULTS":"Резултати от търсене във форуми",
		"PROFILES_SEARCH_RESULTS":"Резултати от търсене в профили",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} Резултати от търсене в директория",
		"WIKIS_SEARCH_RESULTS":"Резултати от търсене в Wiki модули",
		"STATUS_UPDATES_SEARCH_RESULTS":"Резултати от търсене в актуализациите на състоянието",
		"VIEW_ALL":"{span}Преглед на всички{/span} ({0})",
		"MATCHING_ONE_OF":"Съвпадения на един от:",
		"MATCHING_ALL_OF":"Съвпадения на всички от:",
		"MATCHING":"Съвпадения:",
		"MATCHING_DOC_TYPE":"Съответстващ тип документ:",
		"BOOKMARK_HELP":"Помощ за отметка",
		"CLOSE_BOOKMARK_HELP":"Затваряне на помощ за отметка",
		"DOCUMENT_TYPE_PREFIX":"Тип документ:",
		"LAST_PAGE_MESSAGE": "Това са много резултати от търсенето. Опитайте да прецизирате своето търсене като добавите повече термини за търсене.",
		"LAST_PAGE_SUBMESSAGE": "Ще получите първите {resultNumber} най-съществени резултата."
});

