/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Clique aqui para ver o cartão de visita",
	"label.semtag.hover.alt" : "Clique aqui para ver o cartão de visita de {0}",
	"label.semtag.hover.altA11Y" : "Clique aqui ou prima ctrl+enter para ver o cartão de visita",
	"label.personcard.dialog.title" : "Cartão de visita de {0}",

	"errorDefaultMsg2" : "Ocorreu um erro, contacte o administrador do sistema",

	"loadingSTStatus" : "A carregar o estado do Sametime...",
	"noStatuAvailable" : "Não existe qualquer estado do Sametime disponível",

	"label.personcard.cardnomarkup" : "Não foi possível obter o cartão de visita",
	"label.inactive.user.msg" : "Esta pessoa já não é um utilizador ativo",
	"label.message.information" : "Informações:",
	"label.personcard.noprofilemsg" : "Não existe um perfil para esta pessoa",
	"label.personcard.cardreqexpired" : "O pedido para obter o cartão de visita expirou",

	"label.bizcard.applinks.less" : "Mostrar menos",
	"label.bizcard.applinks.more" : "Mostrar mais",

	"label.personcard.activitieslink" : "Atividades",
	"label.personcard.activitieslink.title" : "Clique aqui para visualizar as atividades partilhadas",
	"label.personcard.blogslink" : "Blogues",
	"label.personcard.blogslink.title" : "Clique aqui para visualizar o blogue desta pessoa",
	"label.personcard.communitieslink" : "Comunidades",
	"label.personcard.communitieslink.title" : "Clique aqui para visualizar as comunidades desta pessoa",
	"label.personcard.dogearlink" : "Marcadores",
	"label.personcard.dogearlink.title" : "Clique aqui para ver os marcadores desta pessoa",
	"label.personcard.fileslink" : "Ficheiros",
	"label.personcard.fileslink.title" : "Clique aqui para visualizar os ficheiros partilhados desta pessoa",
	"label.personcard.forumlink" : "Fóruns",
	"label.personcard.forumlink.title" : "Clique aqui para visualizar as publicações de fórum desta pessoa",
	"label.personcard.homepagelink" : "Página inicial",
	"label.personcard.homepagelink.title" : "Clique aqui para visualizar a página inicial desta pessoa",
	"label.personcard.mobilelink" : "Móvel",
	"label.personcard.mobilelink.title" : "Clique aqui para visualizar a página móvel desta pessoa",
	"label.personcard.newslink" : "Notícias",
	"label.personcard.newslink.title" : "Clique aqui para visualizar as notícias desta pessoa",
	"label.personcard.profilelink" : "Perfil",
	"label.personcard.profilelink.title" : "Clique aqui para visualizar o perfil desta pessoa",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Clique aqui para visualizar as partilhas do Quickr desta pessoa",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Clique aqui para visualizar os wikis desta pessoa",

	"personCardMoreActions" : "Mais acções",
	"personCardMoreActionsAltText" : "Clique para o menu de ações",

	"label.bizcard.dismiss": "Prima a tecla Escape para ignorar este cartão de visita.",
	"label.bizcard.fullProfile": "Perfil completo",
	"label.bizcard.activities": "Atividades",
	"label.bizcard.communities": "Comunidades",
	"label.bizcard.files": "Ficheiros",
	"label.bizcard.forums": "Fóruns",
	"label.bizcard.bookmarks": "Marcadores",
	"label.bizcard.blogs": "Blogues",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Convidar para A minha rede",
	"personCardAddAsMyColleagues" : "Convidar para A minha rede",
	"personCardFollow" : "Acompanhar",
	"personCardUnfollow" : "Parar de acompanhar",
	"personCardChat" : "Conversação",
	"personCardCall" : "Ligar",
	"personCardSendMail" : "Enviar correio eletrónico",
	"personCardSendEMail" : "Enviar correio eletrónico",
	"personCardProxyStatusAvailable" : "Estou disponível",
	"personCardDownloadVCard" : "Descarregar vCard",

	"friends" : "Rede",
	"friendsFullPageTitle" : "Rede",
	"friendsMenuTitleAllContacts" : "Todos os contactos de rede",
	"friendsMenuTitleMyContacts" : "Os meus contactos de rede",
	"friendsInvitations" : "Convites",
	"friendsMenuTitleInCommon" : "Pessoas em comum",
	"friendsShowAllCommonFriends" : "Mostrar tudo...",
	"friendsViewAllFriends" : "Ver tudo ({0})",
	"friendsSendFriendRequest" : "Enviar pedido",
	"friendsNoFriends" : "Não existem quaisquer contactos de rede associados a este perfil",
	"friendsColleaguesInvite" : "Convidar {0} para ser seu contacto de rede",
	"friendsColleaguesFor" : "Contactos de rede para {0}",
	"friendsNewInv" : "{0} novo convite",
	"friendsNewInvs" : "{0} novos convites",
	"friendsLoading" : "A carregar a rede...",
	"friendsLoadingInv" : "A carregar convites...",
	"friendsSelectFriendForRemoval" : "Selecione os contactos que pretende remover primeiro.",
	"friendsRemoved" : "Contacto(s) de rede removido(s).",
	"friendsInvSent" : "Não foi enviado qualquer convite porque já existe um convite pendente.",
	"friendsRemovedSelected" : "Remover de A minha rede",
	"friendsSortByDisplayName" : "Nome de apresentação",
	"friendsSortByRecent" : "Recentes",
	"friendsTelephone" : "Telefone:",
	"friendsEmail" : "Correio eletrónico:",
	"friendsAltEmail" : "Endereço de correio eletrónico alternativo:",
	"friendsNewInvitationsCount" : "Tem {0} convites novos",
	"friendsNoInv" : "Sem convites",
	"friendsInCommonSingle" : "Tem {0} contacto de rede em comum",
	"friendsInCommonMulti" : "Tem {0} contactos de rede em comum",
	"friendsIncludeMsgForInv" : "Incluir uma mensagem no convite:",
	"friendsInitialMsgForInv" : "Gostava de o adicionar à minha lista de contactos de rede do Connections.",
	"friendsSendInvAction" : "Enviar convite",
	"friendsCancelInvAction" : "Cancelar",
	"friendsAcceptAction" : "Aceitar",
	"friendsIgnoreAction" : "Ignorar",
	"friendsYouExceedTextLimit" : "A mensagem de convite é demasiado extensa. Pode ter um máximo de {1} caracteres. Existem {0} caracteres neste campo.",
	"friendsCannotAddYourself" : "Não é possível adicionar-se como contacto de rede.",
	"friendsIsYourColleague" : "{0} é o seu contacto de rede",
	"friendsRecentlyAdded" : "Pessoas que adicionou recentemente à rede.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Clique para contrair a secção de rede",
	"friendsExpandWidget" : "Clique para expandir a secção de rede",
	"friendsIsInYourNetwork" : "{0} está na sua rede.",
	"friendsActionsFor" : "Ações para Rede",
	"friendsInviteFollowError" : "Ocorreu um erro ao tentar acompanhar {0}",
	"friendsInviteTagError" : "Ocorreu um erro ao tentar identificar {0}",
	"friendsPleaseLogIn" : "Inicie sessão para convidar pessoas para a sua rede",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Não é possível convidar para a sua rede, uma vez que {0} já se encontra na sua rede.",
	"friendsInviteAddTagsFor" : "Adicionar etiquetas para {0}:",
	"friendsInviteAlsoFollow" : "Também acompanhar",
	"friendsInviteReceiveUpdates" : "(receber atualizações)",
	"friendsInviteUpdatesDescription" : "Receba atualizações sobre as pessoas que está a acompanhar na página inicial e num resumo de correio eletrónico.",
	"friendsInviteFollowHelp": "Para obter mais informações, consulte o tópico {0}Acompanhar pessoas{1}.",
	"friendsNetwork" : "Rede",
	"friendsMyNetwork" : "Rede",
	"friendsNetworkFor" : "Rede para {0}",
	"friendsRemoveSelected" : "Remover selecionados",
	"friendsRemoveSelectedTip" : "Faça clique para remover as pessoas selecionadas da rede.",
	"friendsNetworkInCommon" : "Tem {0} ligações de rede em comum.",
	"friendsAddToMyNetwork" : "Gostava de o adicionar à minha rede do Connections.",
	"friendsInvite" : "Convidar para A minha rede",
	"friendsInvitePerson" : "Convidar {0} para a sua rede",
	"friendsInviteMessage" : "Gostava de o adicionar à minha rede do Connections.",
	"friendsInvitedEmailSubject" : "[Perfis] Está convidado para participar na minha rede",
	"friendsInvitedEmailMsg1" : "convidou-o(a) para se tornar num contacto da rede com a seguinte mensagem incluída no convite:",
	"friendsInvitedEmailMsg2" : "Abrir a página de convites da rede",
	"friendsInvitedEmailMsg3" : "Gostava de o adicionar à minha rede.",
	"friendsInvitedEmailMsg4" : "{0} convidou-o para se tornar num contacto de rede:",
	"friendsInvitedEmailMsg5" : "{0} convidou-o para se tornar num contacto de rede com a seguinte mensagem incluída no convite:",
	"friendsInviteLegalNote" : "Ao enviar este convite, permite que {0} comente o seu quadro de perfil.",
	"friendsInviteFailed" : "Devido a um erro de servidor, uma notificação por correio eletrónico não foi enviada ao convidado. No entanto, o convidado continuará a poder aceitar o convite através da aplicação da Web Perfis.",
	"personInNetwork" : "Contacto de rede"
})
