/* Copyright IBM Corp. 2011, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Деректеме кәртішкесін көру үшін, осы жерді нұқыңыз",
	"label.semtag.hover.alt" : "{0} бизнес картасын көру үшін басыңыз",
	"label.semtag.hover.altA11Y" : "Бизнес картаны көру үшін осы жерді немесе control-Енгізу пернелерін басыңыз",
	"label.personcard.dialog.title" : "{0} үшін бизнес карта",

	"errorDefaultMsg2" : "Қате орын алды, жүйелік әкімшіңізге хабарласыңыз.",

	"loadingSTStatus" : "Sametime күйі жүктеп алу",
	"noStatuAvailable" : "Sametime күйі қол жетімді емес",

	"label.personcard.cardnomarkup" : "Бизнес картаны шығарып алу мүмкін емес",
	"label.inactive.user.msg" : "Бұл тұлға енді белсенді пайдаланушы емес",
	"label.message.information" : "Ақпарат:",
	"label.personcard.noprofilemsg" : "Бұл тұлғаның профилі жоқ",
	"label.personcard.cardreqexpired" : "Бизнес картаны алу сұрауының мерзімі бітті",

	"label.bizcard.applinks.less" : "Азырақ көрсету",
	"label.bizcard.applinks.more" : "Қосымша көрсету",

	"label.personcard.activitieslink" : "Әрекеттер",
	"label.personcard.activitieslink.title" : "Бөліскен әрекеттерді көру үшін осы жерді басыңыз",
	"label.personcard.blogslink" : "Блогтар",
	"label.personcard.blogslink.title" : "Бұл адамның блогын көру үшін осы жерді басыңыз",
	"label.personcard.communitieslink" : "Қауымдастықтар",
	"label.personcard.communitieslink.title" : "Бұл адамның қауымдастықтарын көру үшін осы жерді басыңыз",
	"label.personcard.dogearlink" : "Бетбелгілер",
	"label.personcard.dogearlink.title" : "Бұл адамның бетбелгілерін көру үшін осы жерді басыңыз",
	"label.personcard.fileslink" : "Файлдар",
	"label.personcard.fileslink.title" : "Бұл адамның бөліскен файлдарын көру үшін осы жерді басыңыз",
	"label.personcard.forumlink" : "Форумдар",
	"label.personcard.forumlink.title" : "Бұл адамның форумға жіберген жолдауларын көру үшін осы жерді басыңыз",
	"label.personcard.homepagelink" : "Басты",
	"label.personcard.homepagelink.title" : "Осы адамның басты бетін қарау үшін осы жерді нұқыңыз",
	"label.personcard.mobilelink" : "Мобильді",
	"label.personcard.mobilelink.title" : "Бұл адамның мобильдік бетін көру үшін осы жерді басыңыз",
	"label.personcard.newslink" : "Жаңалықтар",
	"label.personcard.newslink.title" : "Бұл адамның жаңалықтарын көру үшін осы жерді басыңыз",
	"label.personcard.profilelink" : "Профиль",
	"label.personcard.profilelink.title" : "Бұл адамның профилін көру үшін осы жерді басыңыз",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Бұл адамның quickr бөлісулерін көру үшін осы жерді басыңыз",
	"label.personcard.wikislink" : "Викилер",
	"label.personcard.wikislink.title" : "Бұл адамның викилерін көру үшін осы жерді басыңыз",

	"personCardMoreActions" : "Қосымша Әрекеттер",
	"personCardMoreActionsAltText" : "Әрекеттер мәзіріне өту үшін нұқыңыз",

	"label.bizcard.dismiss": "Бұл бизнес картадан бас тарту үшін Escape пернесін басыңыз.",

	"personCardAddAsColleagues" : "Менің желіме шақыру",
	"personCardAddAsMyColleagues" : "Менің желіме шақыру",
	"personCardFollow" : "Бақылау",
	"personCardUnfollow" : "Бақылауды тоқтату",
	"personCardChat" : "Сөйлесу",
	"personCardCall" : "Қоңырау шалу",
	"personCardSendMail" : "Электрондық хабарлама жіберу",
	"personCardSendEMail" : "Электрондық хабарлама жіберу",
	"personCardProxyStatusAvailable" : "Мен қосылдым",
	"personCardDownloadVCard" : "vCard жүктеп алу",

	"friends" : "Желі",
	"friendsFullPageTitle" : "Желі",
	"friendsMenuTitleAllContacts" : "Барлық желі контактілері",
	"friendsMenuTitleMyContacts" : "Менің желімдегі контактілер",
	"friendsInvitations" : "Шақырулар",
	"friendsMenuTitleInCommon" : "Жалпы адамдар",
	"friendsShowAllCommonFriends" : "Барлығын көрсету...",
	"friendsViewAllFriends" : "Барлығын қарау ({0})",
	"friendsSendFriendRequest" : "Сұрау жіберу",
	"friendsNoFriends" : "Осы профильге қатысты желі байланыстары жоқ",
	"friendsColleaguesInvite" : "{0} атты пайдаланушыны сіздің желі контактіңіз болуға шақыру жіберу",
	"friendsColleaguesFor" : "{0} желі контактілері",
	"friendsNewInv" : "{0} жаңа шақырту",
	"friendsNewInvs" : "{0} жаңа шақыртулар",
	"friendsLoading" : "Желі жүктеп алу",
	"friendsLoadingInv" : "Шақырулар жүктеп алу",
	"friendsSelectFriendForRemoval" : "Алдымен өшіру керек контактілерді таңдаңыз.",
	"friendsRemoved" : "Желі контакт(лер)і өшірілді.",
	"friendsInvSent" : "Шақыру бұрыннан күтіліп жатқаннан кейін ешқандай шақыру жіберілген жоқ.",
	"friendsRemovedSelected" : "Менің желімнен жою",
	"friendsSortByDisplayName" : "Атты көрсету",
	"friendsSortByRecent" : "Соңғы",
	"friendsTelephone" : "Телефон:",
	"friendsEmail" : "Электрондық пошта:",
	"friendsAltEmail" : "Балама электрондық пошта:",
	"friendsNewInvitationsCount" : "Сізде {0} жаңа шақырту бар",
	"friendsNoInv" : "Шақыртулар жоқ",
	"friendsInCommonSingle" : "Сіздің жалпы {0} желі контактіңіз бар",
	"friendsInCommonMulti" : "Сіздің жалпы {0} желі контактіңіз бар",
	"friendsIncludeMsgForInv" : "Шақыруыңызбен бірге хабарламаны қосу:",
	"friendsInitialMsgForInv" : "Сізді Connections желісіндегі контактілер тізіміне қосуды қалаймын.",
	"friendsSendInvAction" : "Шақырту жіберу",
	"friendsCancelInvAction" : "Болдырмау",
	"friendsAcceptAction" : "Қабылдау",
	"friendsIgnoreAction" : "Елемеу",
	"friendsYouExceedTextLimit" : "Шақыру хабарыңыз тым ұзақ. Оның ұзындығы {1} таңбадан аспауы керек. Өрісте {0} таңба бар.",
	"friendsCannotAddYourself" : "Өзіңізді желі контактісі ретінде қосу мүмкін емес.",
	"friendsIsYourColleague" : "{0} сіздің желі контактіңіз",
	"friendsRecentlyAdded" : "Жақында желіңізге қосқан адамдар.",
	"friendsDate" : "Күн",
	"friendsCollapseWidget" : "Желі бөлімін тасалау үшін басыңыз",
	"friendsExpandWidget" : "Желі бөлімін ашу үшін басыңыз",
	"friendsIsInYourNetwork" : "{0} сіздің желіңізде.",
	"friendsActionsFor" : "Желі әрекеттері",
	"friendsInviteFollowError" : "{0} оқырманы болуға әрекеттену барысында қате орын алды",
	"friendsInviteTagError" : "{0} үшін тэг қоюға әрекеттену барысында қате орын алды",
	"friendsPleaseLogIn" : "Адамдарды желіңізге қосу үшін кіріңіз",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0} бұрыннан желіңізде бар болғандықтан оны желіге шақыру мүмкін емес.",
	"friendsInviteAddTagsFor" : "{0} үшін тэгтер қосу:",
	"friendsInviteAlsoFollow" : "Сондай-ақ, оқырманы болу",
	"friendsInviteReceiveUpdates" : "(жаңартуларды алып тұру)",
	"friendsInviteUpdatesDescription" : "Басты беттегі және электрондық пошта қорытындысында қосылатын адамдар туралы жаңартуларды алыңыз.",
	"friendsInviteFollowHelp": "Толық ақпарат үшін, {0}Қосылатын адамдар{1} қараңыз.",
	"friendsNetwork" : "Желі",
	"friendsMyNetwork" : "Желі",
	"friendsNetworkFor" : "{0} желісі",
	"friendsRemoveSelected" : "Таңдалғанды жою",
	"friendsRemoveSelectedTip" : "Таңдалған адамдарды желіден жою үшін басыңыз.",
	"friendsNetworkInCommon" : "Жалпы {0} желі қосылымдарыңыз бар.",
	"friendsAddToMyNetwork" : "Сізді өзімнің Connections желіме қосқым келеді.",
	"friendsInvite" : "Менің желіме шақыру",
	"friendsInvitePerson" : "Желіге шақыру жіберу: {0}",
	"friendsInviteMessage" : "Сізді өзімнің Connections желіме қосқым келеді.",
	"friendsInvitedEmailSubject" : "[Профильдер] Сіз менің желіме қосылуға шақырылдыңыз",
	"friendsInvitedEmailMsg1" : "шақырумен келесі хабарды жіберу арқылы сізді желі контактісі болуға шақырды:",
	"friendsInvitedEmailMsg2" : "Желі шақыруының бетін ашыңыз",
	"friendsInvitedEmailMsg3" : "Сізді желіме қосқым келеді.",
	"friendsInvitedEmailMsg4" : "{0} сізді желі контактісі болуға шақырды:",
	"friendsInvitedEmailMsg5" : "{0} шақырумен келесі хабарды жіберу арқылы сізді желі контактісі болуға шақырды:",
	"friendsInviteLegalNote" : "Осы шақыруды жіберу арқылы, {0} сіздің профильдер тақтаңызға пікірлер жазуына келісесіз.",
	"friendsInviteFailed" : "Сервер қатесіне байланысты, электрондық-пошта хабарландыруы шақыру алушыға жіберілді. Алайда, шақыру алушы шақыруыңызды Профильдер веб бағдарламасы арқылы ала алады."
})

