/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Feu clic aquí per veure la targeta de presentació",
	"label.semtag.hover.alt" : "Feu clic per veure la targeta de presentació {0}",
	"label.semtag.hover.altA11Y" : "Feu clic aquí o premeu control-intro per veure la targeta de presentació",
	"label.personcard.dialog.title" : "Targeta de presentació per a {0}",

	"errorDefaultMsg2" : "S'ha produït un error; poseu-vos en contacte amb l'administrador del sistema",

	"loadingSTStatus" : "S'està carregant l'estat del Sametime...",
	"noStatuAvailable" : "No hi ha cap estat del Sametime disponible",

	"label.personcard.cardnomarkup" : "No s'ha pogut recuperar la targeta de presentació",
	"label.inactive.user.msg" : "Aquesta persona ja no és un usuari actiu",
	"label.message.information" : "Informació:",
	"label.personcard.noprofilemsg" : "No existeix un perfil per a aquesta persona",
	"label.personcard.cardreqexpired" : "La sol·licitud per obtenir la targeta de presentació ha caducat",

	"label.bizcard.applinks.less" : "Mostra menys",
	"label.bizcard.applinks.more" : "Mostra més",

	"label.personcard.activitieslink" : "Activitats",
	"label.personcard.activitieslink.title" : "Feu clic aquí per veure les activitats compartides",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Feu clic aquí per veure el blog d'aquesta persona",
	"label.personcard.communitieslink" : "Comunitats",
	"label.personcard.communitieslink.title" : "Feu clic aquí per veure les comunitats d'aquesta persona",
	"label.personcard.dogearlink" : "Adreces d'interès",
	"label.personcard.dogearlink.title" : "Feu clic aquí per veure les adreces d'interès d'aquesta persona",
	"label.personcard.fileslink" : "Fitxers",
	"label.personcard.fileslink.title" : "Feu clic aquí per veure els fitxers compartits d'aquesta persona",
	"label.personcard.forumlink" : "Fòrums",
	"label.personcard.forumlink.title" : "Feu clic aquí per veure les publicacions de fòrum d'aquesta persona",
	"label.personcard.homepagelink" : "Inici",
	"label.personcard.homepagelink.title" : "Feu clic aquí per veure la pàgina inicial d'aquesta persona",
	"label.personcard.mobilelink" : "Mòbil",
	"label.personcard.mobilelink.title" : "Feu clic aquí per veure la pàgina mòbil d'aquesta persona",
	"label.personcard.newslink" : "Notícies",
	"label.personcard.newslink.title" : "Feu clic aquí per veure les notícies d'aquesta persona",
	"label.personcard.profilelink" : "Perfil",
	"label.personcard.profilelink.title" : "Feu clic aquí per veure el perfil d'aquesta persona",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Feu clic aquí per veure els recursos compartits quickr d'aquesta persona",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Feu clic aquí per veure els wikis d'aquesta persona",

	"personCardMoreActions" : "Més accions",
	"personCardMoreActionsAltText" : "Feu clic al menú d'acció",

	"label.bizcard.dismiss": "Premeu la tecla d'escapament per descartar la targeta de presentació.",
	"label.bizcard.fullProfile": "Perfil complet",
	"label.bizcard.activities": "Activitats",
	"label.bizcard.communities": "Comunitats",
	"label.bizcard.files": "Fitxers",
	"label.bizcard.forums": "Fòrums",
	"label.bizcard.bookmarks": "Adreces d'interès",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Convida a la meva xarxa",
	"personCardAddAsMyColleagues" : "Convida a la meva xarxa",
	"personCardFollow" : "Segueix",
	"personCardUnfollow" : "Deixa de seguir",
	"personCardChat" : "Xat",
	"personCardCall" : "Truca",
	"personCardSendMail" : "Envia un correu electrònic",
	"personCardSendEMail" : "Envia un correu electrònic",
	"personCardProxyStatusAvailable" : "Estic disponible",
	"personCardDownloadVCard" : "Descarrega la vCard",

	"friends" : "Xarxa",
	"friendsFullPageTitle" : "Xarxa",
	"friendsMenuTitleAllContacts" : "Tots els contactes de la xarxa",
	"friendsMenuTitleMyContacts" : "Els meus contactes de la xarxa",
	"friendsInvitations" : "Invitacions",
	"friendsMenuTitleInCommon" : "Persones en comú",
	"friendsShowAllCommonFriends" : "Mostra-ho tot...",
	"friendsViewAllFriends" : "Visualitza-ho tot ({0})",
	"friendsSendFriendRequest" : "Envia una sol·licitud",
	"friendsNoFriends" : "No hi ha cap contacte de xarxa associat amb aquest perfil",
	"friendsColleaguesInvite" : "Convideu {0} perquè sigui un contacte de la vostra xarxa",
	"friendsColleaguesFor" : "Contactes de xarxa de {0}",
	"friendsNewInv" : "{0} invitació nova",
	"friendsNewInvs" : "{0} invitacions noves",
	"friendsLoading" : "S'està carregant la xarxa...",
	"friendsLoadingInv" : "S'estan carregant les invitacions...",
	"friendsSelectFriendForRemoval" : "Seleccioneu primer els contactes que voleu eliminar.",
	"friendsRemoved" : "S'ha eliminat contactes de xarxa.",
	"friendsInvSent" : "No s'ha enviat cap invitació perquè ja n'hi ha una de pendent.",
	"friendsRemovedSelected" : "Elimina de La meva xarxa",
	"friendsSortByDisplayName" : "Nom de visualització",
	"friendsSortByRecent" : "Recent",
	"friendsTelephone" : "Telèfon:",
	"friendsEmail" : "Adreça electrònica:",
	"friendsAltEmail" : "Adreça electrònica alternativa:",
	"friendsNewInvitationsCount" : "Teniu {0} invitacions noves",
	"friendsNoInv" : "Sense invitacions",
	"friendsInCommonSingle" : "Teniu {0} contacte de xarxa en comú",
	"friendsInCommonMulti" : "Teniu {0} contactes de xarxa en comú",
	"friendsIncludeMsgForInv" : "Incloeu un missatge amb la vostra invitació:",
	"friendsInitialMsgForInv" : "M'agradaria afegir-vos a la meva llista de contactes de xarxa del Connections.",
	"friendsSendInvAction" : "Envia una invitació",
	"friendsCancelInvAction" : "Cancel·la",
	"friendsAcceptAction" : "Accepta",
	"friendsIgnoreAction" : "Ignora",
	"friendsYouExceedTextLimit" : "El vostre missatge d''invitació és massa llarg. Pot tenir un màxim de {1} caràcters. Hi ha {0} caràcters en aquest camp.",
	"friendsCannotAddYourself" : "No podeu afegir-vos com a contacte de xarxa.",
	"friendsIsYourColleague" : "{0} és el vostre contacte de xarxa",
	"friendsRecentlyAdded" : "Persones que heu afegit recentment a la xarxa.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Feu clic per reduir aquesta secció de xarxa",
	"friendsExpandWidget" : "Feu clic per ampliar aquesta secció de la xarxa",
	"friendsIsInYourNetwork" : "{0} és a la vostra xarxa.",
	"friendsActionsFor" : "Acciones de xarxa",
	"friendsInviteFollowError" : "S'ha produït un error en intentar seguir {0}",
	"friendsInviteTagError" : "S'ha produït un error en intentar etiquetar {0}",
	"friendsPleaseLogIn" : "Inicieu la sessió per invitar persones a la xarxa",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "La invitació a la vostra xarxa no és possible perquè {0} ja es troba a la xarxa.",
	"friendsInviteAddTagsFor" : "Afegiu etiquetes de {0}:",
	"friendsInviteAlsoFollow" : "També segueix",
	"friendsInviteReceiveUpdates" : "(rebre actualitzacions)",
	"friendsInviteUpdatesDescription" : "Rebeu actualitzacions sobre persones que seguiu a la pàgina inicial i al resum del correu electrònic.",
	"friendsInviteFollowHelp": "Per obtenir més informació, consulteu {0}Com seguir persones{1}.",
	"friendsNetwork" : "Xarxa",
	"friendsMyNetwork" : "Xarxa",
	"friendsNetworkFor" : "Xarxa de {0}",
	"friendsRemoveSelected" : "Elimina els elements seleccionats",
	"friendsRemoveSelectedTip" : "Feu clic per eliminar les persones seleccionades de la xarxa.",
	"friendsNetworkInCommon" : "Teniu {0} connexions de xarxa en comú.",
	"friendsAddToMyNetwork" : "M'agradaria afegir-vos a la meva xarxa de Connections.",
	"friendsInvite" : "Convida a la meva xarxa",
	"friendsInvitePerson" : "Convideu {0} a la vostra xarxa",
	"friendsInviteMessage" : "M'agradaria afegir-vos a la meva xarxa de Connections.",
	"friendsInvitedEmailSubject" : "[Perfils] Se us ha convidat a unir-vos a la meva xarxa",
	"friendsInvitedEmailMsg1" : "us ha convidat a ser un contacte de xarxa amb el missatge següent inclòs a la invitació:",
	"friendsInvitedEmailMsg2" : "Obriu la pàgina d'invitació de xarxa",
	"friendsInvitedEmailMsg3" : "M'agradaria afegir-vos a la meva xarxa.",
	"friendsInvitedEmailMsg4" : "{0} us ha convidat a convertir-vos en un contacte de xarxa:",
	"friendsInvitedEmailMsg5" : "{0} us ha convidat a ser un contacte de xarxa amb el missatge següent inclòs a la invitació:",
	"friendsInviteLegalNote" : "En enviar aquesta invitació, esteu d'acord en permetre a {0} fer comentaris al taulell del vostre perfil.",
	"friendsInviteFailed" : "A causa d'un error del servidor, no s'ha enviat una notificació per correu electrònic al convidat. Tanmateix, aquest podrà acceptar la invitació a través de l'aplicació web Perfils.",
	"personInNetwork" : "Contacte de xarxa"
})
