/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Vyžaduje sa nadpis.",
	nourl: "Vyžaduje sa adresa URL.",
	fileSchema: "Ak chcete pridať odkaz na vzdialený alebo lokálny súbor, musí vyhovovať jednému z týchto formátov: file://vzdialená_cesta alebo file:///lokálna_cesta.",
	invalidUrl: "Toto nie je platná adresa URL komunity.",
	invalidTagChar: "Zoznam značiek, ktorý ste zadali, obsahuje neplatný znak „&“. Odstráňte tento znak zo zoznamu značiek.",
	txtHelp: "Pomoc",
	txtHelpTags: "Pomoc k značkám",
	txtHelpTagsClose: "Zatvoriť pomoc k značkám",
	tagsall: "Všetky",
	tagsyours: "Vaše",
	tagsrecent: "Posledné: ",
	tagspopular: "Populárne: ",
	tagsrecommended: "Odporúčané: ",
	nothingselected: "Vyžaduje sa výber komunity.",
	nothingselected_activity: "Vyžaduje sa výber aktivity.",
	nothingselected_blogs: "Vyžaduje sa výber blogu.",
	nothingselected_all: "Nie je vybratá žiadna služba ani položka, záložka sa neuloží.",
	nothingFeedselected: "Nie je vybratá žiadna služba ani položka, informačný kanál sa neuloží.",
	alertDialogTitle: "Správa",
	alertDialogOK: "OK",
	expand: "Kliknutím rozviniete túto sekciu",
	collapse: "Kliknutím zviniete túto sekciu",
	discussThis: "Diskutovať o tomto",
	by: "od:",
	posted: "Zverejnené:",
	attachments: "Prílohy",
	communityForum: "Fórum komunity",
	notCommunityPage: "Aktuálna webová stránka nie je platná webová stránka komunity. Ak chcete vytvoriť súvisiacu komunitu, môžete manuálne zadať nadpis komunity, odkaz a opis.",
	privateCommunityNotice: "Táto komunita je obmedzená. Je viditeľná iba pre členov komunity.",
	forumNameHint : "Napíšte názov fóra",
	formDescriptionHint:"Opíšte, prečo by táto komunita mala zaujímať vašu komunitu.",
	information : "Informácie",
	error : "Chyba",
	success : "Úspech",
	warning : "Upozornenie",
	informationColon : "Informácie:",
	successColon : "Úspech:",
	warningColon : "Varovanie:",
	errorColon : "Chyba:",
	feedAlreadyExist : "Informačný kanál už existuje v komunite.",
	bookmarkAlreadyExist : "Záložka už existuje v komunite.",
	mentionAuthWarning:"Nasledujúci spomenutí ľudia nemôžu zobraziť správu, pretože nie sú členmi komunity:",
	mentionAuthForumWarning:"Nasledujúci spomenutí ľudia nemôžu zobraziť správu, pretože nemajú prístup k tomuto fóru:",
	exceedDescLength: "Zadaný opis je pridlhý.",
	communities_checked:"Vybraté komunity: ${0}",
	activities_checked:"Vybraté aktivity: ${0}",
	blogs_checked:"Vybraté blogy: ${0}"
})
