/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtern nach:",
"SHOW":"Anzeigen:",
"ACL_FILTER_LABEL":"Nach Sichtbarkeit filtern",
"PARENT_FILTER_LABEL":"Nach Container filtern",
"TYPE_FILTER_LABEL":"Nach Typ filtern",
"PAGING_TOP":"Primärer Seitenwechsel",
"PAGING_BOTTOM":"Sekundärer Seitenwechsel",
"PREVIOUS":"Zurück",
"NEXT":"Weiter",
"PAGE":"Seite {0} von {1}",
"PAGE_COLON":"Seite:",
"RESULTS":"{span}{0}-{1}{/span} von {2}",
"ITEMS":"{0} Elemente",
/* Application names */
"ACTIVITIES":"Aktivitäten",
"BLOGS":"Blogs ",
"CALENDAR":"Kalender",
"COMMUNITIES":"Communitys ",
"BOOKMARKS":"Lesezeichen ",
"DOGEAR":"Lesezeichen ",
"EVENTS":"Ereignisse",
"FILES":"Dateien",
"FORUMS":"Foren",
"PROFILES":"Profile",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Feeds",
"STATUS_UPDATES":"Statusaktualisierungen",
"ONECOMMENT":"1 Kommentar",
"COMMENTS":"{0} Kommentare",
"ONEPERSON":"1 Person",
"PEOPLE":"{0} Personen",
"TAGS":"Tags:",
"TAGSMORE":"und {0} weitere",
"NORESULTSMESSAGE":"Diese Suche brachte keine Ergebnisse.",
"JAN":"Januar",
"FEB":"Februar",
"MAR":"März",
"APR":"April",
"MAY":"Mai",
"JUN":"Juni",
"JUL":"Juli",
"AUG":"August",
"SEP":"September",
"OCT":"Oktober",
"NOV":"November",
"DEC":"Dezember",
"NO_CONTACT":"Die Suche wurde nicht durchgeführt, weil keine Verbindung mit dem Server hergestellt werden konnte.",
"SERVER_ERROR":"Die Suche wurde aufgrund eines Serverfehlers nicht durchgeführt.",
"SORT_BY":"Sortieren nach:",
"SORT_RELEVANCE":"Relevanz ",
"SORT_DATE":"Datum",
"SORT_LAST_UPDATED":"Letzte Aktualisierung",
"SORT_DUE_DATE":"Fälligkeitsdatum ",
"SORT_VISITS":"Besuche",
"SORT_COMMENTS":"Kommentare ",
"SORT_RECOMMENDATION":"Empfehlungen ",
"SORT_POPULARITY":"Beliebtheit",
"SORT_FIRSTNAME":"Vorname ",
"SORT_LASTNAME":"Nachname ",
"SORT_DOWNLOADS":"Downloads ",
"SORT_TYPE":"Typ",
"SORT_SIZE":"Größe",
"SORT_TITLE":"Titel",
"PRIVATE":"Privat",
"MODERATED":"Moderiert",
"COMMUNITY_ACTIVITY":"Community-Aktivität",
"COMMUNITY_BLOG":"Community-Blog",
"COMMUNITY_FILE":"Community-Datei",
"COMMUNITY_FORUM":"Community-Forum",
"COMMUNITY_WIKI":"Community-Wiki",
"COMMUNITY_FEED":"Community-Feed",
"COMMUNITY_BOOKMARK":"Community-Lesezeichen",
"NO_TAG":"Noch keine Tags",
"NO_DATE":"Noch keine Daten ",
"NO_PEOPLE":"Noch keine Personen",
"REMOVE_FILTER_LABEL":"Zum Entfernen hier klicken ",
"REMOVE_FILTER_TITLE":"Entfernen",
"REMOVE_FILTER_TOOLTIP":"Diesen Filter entfernen ",
"COMMENT_ON":"Kommentar zu:",
"EXPAND_COLLAPSE":"Klicken Sie hier, um einzublenden / auszublenden",
"EXPAND":"Erweitern",
"COLLAPSE":"Ausblenden",
"EXPAND_MONTHS_FILTER":"Monatsfilter für Jahr {0} einblenden ",
"SORT_RELEVANCE_LABEL":"Klicken Sie hier, um nach Relevanz zu sortieren",
"SORT_DATE_LABEL":"Klicken Sie hier, um nach Datum zu sortieren",
"SORT_UPDATED_LABEL":"Klicken Sie hier, um nach der letzten Aktualisierung zu sortieren",
"SORT_DUE_LABEL":"Klicken Sie hier, um nach Fälligkeitsdatum zu sortieren",
"SORT_VISITS_LABEL":"Klicken Sie hier, um nach Anzahl der Besuche zu sortieren",
"SORT_COMMENTS_LABEL":"Klicken Sie hier, um nach Anzahl der Kommentare zu sortieren",
"SORT_RECOMMENDATIONS_LABEL":"Klicken Sie hier, um nach Anzahl der Empfehlungen zu sortieren ",
"SORT_POPULARITY_LABEL":"Klicken Sie hier, um nach Beliebtheit zu sortieren",
"SORT_FIRST_NAME_LABEL":"Klicken Sie hier, um nach Vornamen zu sortieren",
"SORT_LAST_NAME_LABEL":"Klicken Sie hier, um nach Nachnamen zu sortieren",
"RATING":"Empfehlungen ",
"GRADUATED":"Hochgestuft",
"ONEVOTE":"1 Stimme",
"VOTES":"{0} Stimmen",
"BOOKMARK_THIS_RESULT":"Lesezeichen setzen",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inaktiv)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} Personen mit Lesezeichen versehen",
/* eg from an Activity */
"FROMANACTIVITY":"von einer Aktivität",
"FROMABLOG":"von einem Blog",
"FROMANIDEATIONBLOG":"aus einem Ideen-Blog",
"FROMANEVENT":"von einem Ereignis ",
"FROMAFORUM":"von einem Forum",
"FROMAWIKI":"von einem Wiki",
"FROMACOMMUNITY":"von einer Community",
"FROMXCOMMUNITIES":"von {0} Communitys",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivität ",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Ideen-Blog",
"ENTRY_ALONE":"Eintrag",
"EVENT_ALONE":"Ereignis ",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki ",
"COMMUNITY_ALONE":"Community ",
"XCOMMUNITIES_ALONE":"{0} Communitys",
"SHAREDCOMMUNITIES":"Mit diesen Communitys geteilt",
"INACOMMUNITY":"in einer Community",
"LASTUPDATED":"Suchindex wurde zuletzt aktualisiert:",
"NODESCRIPTION":"Keine Beschreibung oder Zusammenfassung für dieses Ergebnis.",
"ATTACHMENT":"Anhang:",
"ACTIVITY":"Aktivität: ",
"ACTIVITYBOOKMARK":"Aktivitätslesezeichen:",
"ACTIVITYCOMMENT":"Aktivitätskommentar: ",
"ACTIVITYENTRY":"Aktivitätseintrag:",
"ACTIVITYSECTION":"Aktivitätsabschnitt:",
"ACTIVITYTODO":"Aktivitätsaufgabe:",
"BLOG":"Blog:",
"BLOGENTRY":"Blog-Eintrag:",
"BLOGCOMMENT":"Blogkommentar:",
"BOOKMARK":"Lesezeichen:",
"CALENDAREVENT":"Ereignis: ",
"CATEGORY":"Kategorie:",
"COMMENT":"Kommentar: ",
"COMMUNITY":"Community: ",
"ENTRY":"Eintrag:",
"EVENTDATEON":"Am: {0}",
"EVENTISALLDAY":"Ganztägiges Ereignis",
"EVENTREPEATS":"Wiederholungen",
"FEED":"Feed:",
"FILE":"Datei: ",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forenkategorie:",
"FORUMTOPIC":"Forenthema:",
"IDEA":"Idee:",
"IDEACOMMENT":"Kommentar zur Idee:",
"IDEATIONBLOG":"Ideen-Blog:",
"PAGE":"Seite:",
"PROFILE":"Profil:",
"SECTION":"Abschnitt:",
"STATUSUPDATE":"Statusaktualisierung ",
"STATUSUPDATE_PREFIX":"Statusaktualisierung:",
"TOPIC":"Thema:",
"TOPIC_WITH_ATTACHMENT":"Thema",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Wiki-Seite:",
"WIKIFILE":"Wiki-Anhang:",
"SEARCH":"Suche:",
"TODO":"Aufgabe: ",
"ALLRESULTS":"Alle Ergebnisse",
"PUBLICCONTENT":"Öffentlicher Inhalt",
"MYCONTENT":"Meine Inhalte",
"RESULTNOTFOUND":"Sie haben das Gesuchte nicht gefunden?",
"TEMPDIFFICULTIES":"Hinweis: Aufgrund von temporären Schwierigkeiten bei der Indexierung fehlen in Ihrer Suche {0}, die in den letzten {1} Tagen geändert wurden.",
"TRYLATER":"Versuchen Sie es später erneut.",
"MULTIPLETEMPDIFFICULTIES":"Hinweis: Aufgrund von temporären Schwierigkeiten bei der Indexierung fehlen in Ihrer Suche {0}, die kürzlich geändert wurden.",
"YOUAREAUTHOR":"Sie sind Autor",
"YOUARECONTRIBUTOR":"Sie sind Mitwirkender",
"YOUAREOWNER":"Sie sind Eigentümer",
"YOUAREMEMBER":"Sie sind Mitglied",
/* Profiles */
"MYNETWORK":"Mein Netzwerk",
"ALLPEOPLE":"Alle Personen",
"EXCLUDEINACTIVE":"Inaktive Personen ausschließen",
"PHONE":"Telefon: ",
"EMAIL":"E-Mail: ",
/* Communities */
"ALLCOMMUNITIES":"Alle Communitys",
"PUBLICCOMMUNITIES":"Öffentliche Communitys ",
"MYCOMMUNITIES":"Meine Communitys ",
"EVERYTHINGCOMMUNITIES":"Alles von Communitys",
"COMMUNITIESONLY":"Communitys ",
"COMMUNITIESCONTENT":"Inhalte von Communitys",
/* Activities */
"ALLACTIVITIES":"Alle Aktivitäten",
"PUBLICACTIVITIES":"Öffentliche Aktivitäten ",
"MYACTIVITIES":"Meine Aktivitäten ",
"EVERYTHINGACTIVITIES":"Alles von Aktivitäten",
"ACTIVITIESONLY":"Aktivitäten",
"SECTIONSACTIVITIES": "Abschnitte von Aktivitäten",
"ENTRIESACTIVITIES":"Einträge von Aktivitäten",
"TODOSACTIVITIES":"Aufgaben von Aktivitäten",
"BOOKMARKSACTIVITIES":"Lesezeichen von Aktivitäten",
"FILESACTIVITIES":"Anhänge von Aktivitäten",
"ALLTYPESACTIVITIES":"Alle Typen von Aktivitäten",
"COMMUNITYACTIVITIES":"Aktivitäten von Communitys",
"STANDALONEACTIVITIES":"Eigenständige Aktivitäten",
/* Forums */
"ALLFORUMS":"Alle Foren",
"PUBLICFORUMS":"Öffentliche Foren",
"MYFORUMS":"Meine Foren",
"EVERYTHINGFORUMS":"Alles von Foren",
"FORUMSONLY":"Foren",
"TOPICSFORUMS":"Forenthemen",
"FORUMCATEGORIES": "Forenkategorien",
"FILESFORUMS":"Anhänge von Foren",
"ALLTYPESFORUMS":"Alle Typen von Foren",
"COMMUNITYFORUMS":"Foren von Communitys",
"STANDALONEFORUMS":"Eigenständige Foren",
/* Blogs */
"ALLBLOGS":"Alle Blogs",
"PUBLICBLOGS":"Öffentliche Blogs",
"MYBLOGS":"Meine Blogs",
"EVERYTHINGBLOGS":"Alles von Blogs",
"BLOGSONLY":"Blogs ",
"ENTRIESBLOGS":"Blog-Einträge",
"FILESBLOGS":"Anhänge von Blogs",
"EVERYTHINGIDEATIONBLOGS":"Alles von Ideen-Blogs",
"BLOGSIDEATIONBLOGS":"Ideen-Blogs",
"BLOGSIDEAS":"Ideen",
"ALLTYPESBLOGS":"Alle Typen von Blogs",
"COMMUNITYBLOGS":"Blogs von Communitys",
"COMMUNITYIDEATIONBLOGS":"Ideen-Blogs von Communitys",
"STANDALONEBLOGS":"Eigenständige Blogs",
/* Bookmarks */
"ALLBOOKMARKS":"Alle Lesezeichen",
"PUBLICBOOKMARKS":"Öffentliche Lesezeichen",
"MYBOOKMARKS":"Meine Lesezeichen",
"ALLTYPESBOOKMARKS":"Alle Typen von Lesezeichen",
"COMMUNITYBOOKMARKS":"Lesezeichen von Communitys",
"STANDALONEBOOKMARKS":"Eigenständige Lesezeichen",
/* Files */
"ALLFILES":"Alle Dateien ",
"PUBLICFILES":"Öffentliche Dateien ",
"MYFILES":"Meine Dateien",
"ALLTYPESFILES":"Alle Dateitypen",
"COMMUNITYFILES":"Dateien von Communitys",
"STANDALONEFILES":"Eigenständige Dateien",
"NUMDOWNLOADS":"{0} Downloads",
/* Wikis */
"ALLWIKIS":"Alle Wikis",
"PUBLICWIKIS":"Öffentliche Wikis",
"MYWIKIS":"Meine Wikis",
"EVERYTHINGWIKIS":"Alles von Wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Wiki-Seiten",
"FILESWIKIS":"Anhänge von Wikis",
"ALLTYPESWIKIS":"Alle Typen von Wikis",
"COMMUNITYWIKIS":"Wikis von Communitys",
"STANDALONEWIKIS":"Eigenständige Wikis",
/* Status Updates */
"ALLSTATUSUPDATES":"Alle Statusaktualisierungen",
"PUBLICSTATUSUPDATES":"Öffentliche Statusaktualisierungen",
"MYSTATUSUPDATES":"Meine Statusaktualisierungen",
"ALLTYPESSTATUSUPDATES":"Alle Typen von Statusaktualisierungen",
"COMMUNITYSTATUSUPDATES":"Statusaktualisierungen aus Communitys",
"STANDALONESTATUSUPDATES":"Statusaktualisierung aus Profile",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Diese URL wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"BOOKMARKEDCOMMUNITY":"Diese Community wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"BOOKMARKEDPROFILE":"Dieses Profil wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"BOOKMARKEDBLOG":"Dieses Blog wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"COMMUNITYBLOG":"Dies ist ein Blog in einer Community.",
"BOOKMARKEDACTIVITY":"Diese Aktivität wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen",
"COMMUNITYACTIVITY":"Dies ist eine Aktivität in einer Community.",
"BOOKMARKEDFILE":"Diese Datei wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"COMMUNITYFILE":"Dies ist eine Datei in einer Community.",
"BOOKMARKED":"Dieses Wiki wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"COMMUNITYWIKI":"Dies ist ein Wiki in einer Community.",
"BOOKMARKEDFORUM":"Dieses Forum wurde von einer Anzahl von Benutzern mit einem Lesezeichen versehen.",
"COMMUNITYFORUM":"Dies ist ein Forum in einer Community.",
"ALLTAGANDTTILE":"Klicken Sie auf diese Schaltfläche, um alle Titel und Tags für diese URL anzuzeigen",
"TAGS_ARE_FROM":"Dieses Suchergebnis enthält möglicherweise Tags aus:",
"BOOKMARKS_TITLE":"Lesezeichen ",
"COMMUNITIES_TITLE":"Communitys ",
"ACTIVITIES_TITLE":"Aktivitäten",
"HELP":"Hilfe",
"MORESTATUSUPDATES":"Weitere Übereinstimmungen für Statusaktualisierungen anzeigen",
"TITLE_PREFIX":"Titel:",
"LATEST_MESSAGE":"Neueste Nachricht",
"LATEST_STATUS_UPDATE":"Neueste Statusaktualisierung",
"LATEST_COMMUNITY_STATUS_UPDATE":"Neueste Community-Statusaktualisierung",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Neueste Communitys-Statusaktualisierung",
"SEARCH_RESULTS":"Suchergebnisse für gesamten Inhalt ",
"ACTIVITIES_SEARCH_RESULTS":"Suchergebnisse für Aktivitäten",
"BLOGS_SEARCH_RESULTS":"Suchergebnisse für Blogs",
"BOOKMARKS_SEARCH_RESULTS":"Suchergebnisse für Lesezeichen",
"COMMUNITIES_SEARCH_RESULTS":"Suchergebnisse für Communitys",
"FILES_SEARCH_RESULTS":"Suchergebnisse für Dateien",
"FORUMS_SEARCH_RESULTS":"Suchergebnisse für Foren",
"PROFILES_SEARCH_RESULTS":"Suchergebnisse für Profile",
"DIRECTORY_SEARCH_RESULTS":"Suchergebnisse für ${orgName}-Verzeichnis",
"WIKIS_SEARCH_RESULTS":"Suchergebnisse für Wikis",
"STATUS_UPDATES_SEARCH_RESULTS":"Suchergebnisse für Statusaktualisierungen",
"VIEW_ALL":"{span}Alle anzeigen{/span} ({0})",
"MATCHING_ONE_OF":"Übereinstimmend mit einem von:",
"MATCHING_ALL_OF":"Mit allen übereinstimmend:",
"MATCHING":"Übereinstimmend mit:",
"MATCHING_DOC_TYPE":"Übereinstimmend mit Dokumenttyp:",
"BOOKMARK_HELP":"Hilfe zu Lesezeichen",
"CLOSE_BOOKMARK_HELP":"Hilfe zu Lesezeichen schließen",
"DOCUMENT_TYPE_PREFIX":"Dokumenttyp: ",
"FILE_PREVIEW_ONLY":"(Nur Vorschaumodus)"
})

