/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informacije za vozlišče: ",
	"INSTALLED": "Preverjanje nameščenih storitev",
	"RESUMETOKENS": "Preverjanje nadaljevalnih žetonov",
	"SEEDLISTS": "Preverjanje razpoložljivosti seznamov semen",
	"CALENDARS": "Preverjanje pravilne konfiguracije koledarjev za urnik",
	"VARIABLES": "Preverjanje nastavljanja spremenljivk WebSphere",
	"TASKS": "Preverjanje omogočenih indeksirnih nalog",
	"INDEXFILES": "Preverjanje obstoja obveznih datotek v mapi indeksa",
	"LOGS": "Pregledovanje napak v dnevnikih",
	"CONFIGFILES": "Pregledovanje konfiguracijskih datotek",
	"DICTIONARIES": "Preverjanje števila omogočenih slovarjev",
	"SYNC": "Preverjanje statusa vozlišč.",
	"DBRECORDS": "Preverjanje zapisov baze podatkov",
	"INSTALLEDMSG": "Nameščena je naslednja storitev: ",
	"RESUMETOKENSMSG": "Nadaljevalni žeton za: ",
	"SEEDLISTSMSG": "Seznama semen ni mogoče pridobiti za: ",
	"CALENDARSMSG": "Preverjanje koledarja urnika je bilo uspešno prestano: ",
	"VARIABLESMSG": "Spremenljivka: ",
	"TASKSMSG": "Naslednja naloga je omogočena: ",
	"INDEXFILESMSG" : "V mapi iskalnega indeksa so naslednje datoteke: ",
	"LOGSMSG" : "Preglejte naslednja sporočila o napakah: ",
	"CONFIGFILESMSG" : "Najdene so bile naslednje konfiguracijske datoteke: ",
	"DICTIONARIESMSG" : "Število omogočenih slovarjev: ",
	"INSYNC": "Vsa vozlišča so usklajena",
	"OUTOFSYNC": "Število neusklajenih vozlišč: ",
	"NOTBLOCKED": "Ni blokiranih vozlišč",
	"BLOCKED": "Število blokiranih vozlišč: ",
	"INDATE": "Vsa vozlišča so ažurna",
	"OUTOFDATE": "Število zastarelih vozlišč: ",
	"NUMOFDOCS": "Število dokumentov v bazi podatkov: ",
	"FILESTOCONVERT": "Število datotečnih dokumentov za pretvorbo: ",
	"CONVERTEDFILES": "Število pretvorjenih datotek: ",
	"TOTALFILES": "Skupno število datotek v bazi podatkov: ",
	"ERROR":"Napaka",
	"ERROR_PREFIX":"Napaka:",
	"INFO":"Informacije",
	"INFO_PREFIX":"Informacije:",
	"WARNING":"Opozorilo",
	"WARNING_PREFIX":"Opozorilo:",
	"LOADING_MESSAGE": "Nalaganje",
	"SERVER_STATUS": "Status strežnika",
	"INITIAL_INDEXING_EXCEPTIONS": "Izjemna stanja pri začetnem indeksiranju",
	"SYS_OUT_EXCEPTIONS": "Izjemna stanja v dnevniku SystemOut",
	"SEEDLIST_VALIDATE": "Preverjanje seznamov semen",
	"ERRORS_DURING_INITIAL_INDEXING":"Med ustvarjanjem začetnega indeksa je prišlo do naslednjih izjemnih stanj",
	"CRAWL_FAILED": "Vseh podatkov naslednje storitve ni bilo mogoče pajkati: ",
	"EXCEPTION_ENCOUNTERED": "Pajkanje ni uspelo. Sistem je vrnil sporočilo: ",
	"SAND_VALIDATE": "Preverjanje SAND",
	"CHECK_FOR_SAND_FILES":"Preverjanje datotek SAND",
	"IS_FILE_AVAILABLE":"Preverjanje ustvarjanja datoteke: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Med ustvarjanjem začetnega indeksa je prišlo do naslednjih izjemnih stanj",
	"CRAWL_FAILED":"Vseh podatkov naslednje storitve ni bilo mogoče pajkati: ",
	"EXCEPTION_ENCOUNTERED":"Pajkanje ni uspelo. Sistem je vrnil sporočilo: "
})

