/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtriraj po:",
"SHOW":"Pokaži:",
"ACL_FILTER_LABEL":"Filtriraj po vidnosti",
"PARENT_FILTER_LABEL":"Filtriraj po vsebniku",
"TYPE_FILTER_LABEL":"Filtriraj po vrsti",
"PAGING_TOP":"Primarno ostranjevanje",
"PAGING_BOTTOM":"Sekundarno ostranjevanje",
"PREVIOUS":"Nazaj",
"NEXT":"Naprej",
"PAGE":"Stran {0} od {1}",
"PAGE_COLON":"Stran:",
"RESULTS":"{span}{0}-{1}{/span} od {2}",
"ITEMS":"{0} postavk",
/* Application names */
"ACTIVITIES":"Dejavnosti",
"BLOGS":"Blogi",
"CALENDAR":"Koledar",
"COMMUNITIES":"Skupnosti",
"BOOKMARKS":"Zaznamki",
"DOGEAR":"Zaznamki",
"EVENTS":"Dogodki",
"FILES":"Datoteke",
"FORUMS":"Forumi",
"PROFILES":"Profili",
"WIKI":"Wikiji",
"WIKIS":"Wikiji",
"FEEDS":"Viri",
"STATUS_UPDATES":"Posodobitve statusov",
"ONECOMMENT":"1 komentar",
"COMMENTS":"Št. komentarjev: {0}",
"ONEPERSON":"Št. oseb: 1",
"PEOPLE":"Št. oseb: {0}",
"TAGS":"Oznake:",
"TAGSMORE":"in {0} več",
"NORESULTSMESSAGE":"Za to iskanje ni rezultatov",
"JAN":"Januar",
"FEB":"Februar",
"MAR":"Marec",
"APR":"April",
"MAY":"Maj",
"JUN":"Junij",
"JUL":"Julij",
"AUG":"Avgust",
"SEP":"September",
"OCT":"Oktober",
"NOV":"November",
"DEC":"December",
"NO_CONTACT":"Iskanje ni bilo izvedeno, ker se ni bilo mogoče povezati s strežnikom.",
"SERVER_ERROR":"Iskanje ni bilo izvedeno zaradi napake na strežniku.",
"SORT_BY":"Razvrsti po:",
"SORT_RELEVANCE":"Relevantnost",
"SORT_DATE":"Datum",
"SORT_LAST_UPDATED":"Zadnja posodobitev",
"SORT_DUE_DATE":"Datum zapadlosti",
"SORT_VISITS":"Obiski",
"SORT_COMMENTS":"Komentarji",
"SORT_RECOMMENDATION":"Všečnosti",
"SORT_POPULARITY":"Popularnost",
"SORT_FIRSTNAME":"Ime",
"SORT_LASTNAME":"Priimek",
"SORT_DOWNLOADS":"Prenosi",
"SORT_TYPE":"Vrsta",
"SORT_SIZE":"Velikost",
"SORT_TITLE":"Naslov",
"PRIVATE":"Zasebno",
"MODERATED":"Moderirano",
"COMMUNITY_ACTIVITY":"Dejavnost skupnosti",
"COMMUNITY_BLOG":"Blog skupnosti",
"COMMUNITY_FILE":"Datoteka skupnosti",
"COMMUNITY_FORUM":"Forum skupnosti",
"COMMUNITY_WIKI":"Wiki skupnosti",
"COMMUNITY_FEED":"Vir skupnosti",
"COMMUNITY_BOOKMARK":"Zaznamek skupnosti",
"NO_TAG":"Trenutno še ni nobene oznake",
"NO_DATE":"Ni še datumov",
"NO_PEOPLE":"Trenutno še ni oseb",
"REMOVE_FILTER_LABEL":"Kliknite, da odstranite",
"REMOVE_FILTER_TITLE":"Odstrani",
"REMOVE_FILTER_TOOLTIP":"Odstrani ta filter",
"COMMENT_ON":"Komentar na:",
"EXPAND_COLLAPSE":"Kliknite za razširitev/strnitev",
"EXPAND":"Razširi",
"COLLAPSE":"Strni",
"EXPAND_MONTHS_FILTER":"Razširi filter mesecev za leto {0}",
"SORT_RELEVANCE_LABEL":"Kliknite za razvrstitev po relevantnosti",
"SORT_DATE_LABEL":"Kliknite za razvrstitev po datumu",
"SORT_UPDATED_LABEL":"Kliknite za razvrstitev po zadnji posodobitvi",
"SORT_DUE_LABEL":"Kliknite za razvrstitev po datumu zapadlosti",
"SORT_VISITS_LABEL":"Kliknite za razvrstitev po številu obiskov",
"SORT_COMMENTS_LABEL":"Kliknite za razvrstitev po številu komentarjev",
"SORT_RECOMMENDATIONS_LABEL":"Kliknite za razvrstitev po številu všečnosti",
"SORT_POPULARITY_LABEL":"Kliknite za razvrstitev po popularnosti",
"SORT_FIRST_NAME_LABEL":"Kliknite za razvrstitev po imenu",
"SORT_LAST_NAME_LABEL":"Kliknite za razvrstitev po priimku",
"RATING":"Všečnosti",
"GRADUATED":"Odlikovana",
"ONEVOTE":"1 glas",
"VOTES":"{0} glasov",
"BOOKMARK_THIS_RESULT":"Dodaj to med zaznamke",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (neaktiven)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} oseb je dodalo zaznamek",
/* eg from an Activity */
"FROMANACTIVITY":"iz dejavnosti",
"FROMABLOG":"iz bloga",
"FROMANIDEATIONBLOG":"iz idejnega bloga",
"FROMANEVENT":"iz dogodka",
"FROMAFORUM":"iz foruma",
"FROMAWIKI":"iz wikija",
"FROMACOMMUNITY":"iz skupnosti",
"FROMXCOMMUNITIES":"iz {0} skupnosti",
/* For search results parentage */
"ACTIVITY_ALONE":"Dejavnost",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Idejni blog",
"ENTRY_ALONE":"Vnos",
"EVENT_ALONE":"Dogodek",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Skupnost",
"XCOMMUNITIES_ALONE":"{0} skupnosti",
"SHAREDCOMMUNITIES":"V skupni rabi s temi skupnostmi",
"INACOMMUNITY":"v skupnosti",
"LASTUPDATED":"Iskalni indeks je bil nazadnje posodobljen:",
"NODESCRIPTION":"Za ta rezultat ni opisa ali povzetka.",
"ATTACHMENT":"Priloga:",
"ACTIVITY":"Dejavnost:",
"ACTIVITYBOOKMARK":"Zaznamek dejavnosti:",
"ACTIVITYCOMMENT":"Komentar dejavnosti:",
"ACTIVITYENTRY":"Vnos dejavnosti:",
"ACTIVITYSECTION":"Razdelek dejavnosti:",
"ACTIVITYTODO":"Opravilo dejavnosti:",
"BLOG":"Blog:",
"BLOGENTRY":"Vnos v blog:",
"BLOGCOMMENT":"Komentar bloga:",
"BOOKMARK":"Zaznamek:",
"CALENDAREVENT":"Dogodek:",
"CATEGORY":"Kategorija:",
"COMMENT":"Komentar:",
"COMMUNITY":"Skupnost:",
"ENTRY":"Vnos:",
"EVENTDATEON":"Dne: {0}",
"EVENTISALLDAY":"Celodnevni dogodek",
"EVENTREPEATS":"Ponovitve",
"FEED":"Vir:",
"FILE":"Datoteka:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Kategorija foruma:",
"FORUMTOPIC":"Tema na forumu:",
"IDEA":"Ideja:",
"IDEACOMMENT":"Komentarji idej:",
"IDEATIONBLOG":"Idejni blog:",
"PAGE":"Stran:",
"PROFILE":"Profil:",
"SECTION":"Razdelek:",
"STATUSUPDATE":"Posodobitev statusa",
"STATUSUPDATE_PREFIX":"Posodobitev statusa:",
"TOPIC":"Tema:",
"TOPIC_WITH_ATTACHMENT":"Tema",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Stran wiki:",
"WIKIFILE":"Priloga wikija:",
"SEARCH":"Iskanje:",
"TODO":"Opravilo:",
"ALLRESULTS":"Vsi rezultati",
"PUBLICCONTENT":"Javna vsebina",
"MYCONTENT":"Moja vsebina",
"RESULTNOTFOUND":"Ali niste našli tistega, kar ste iskali?",
"TEMPDIFFICULTIES":"Opomba: Zaradi začasnih težav z indeksiranjem vaše iskanje ni vključevalo {0}, kar je bilo spremenjeno v zadnjih {1} dnevih.",
"TRYLATER":"Poskusite znova pozneje.",
"MULTIPLETEMPDIFFICULTIES":"Opomba: Zaradi začasnih težav z indeksiranjem vaše iskanje ni vključevalo {0}, kar je bilo nedavno spremenjeno",
"YOUAREAUTHOR":"Ste avtor",
"YOUARECONTRIBUTOR":"Ste kontributor",
"YOUAREOWNER":"Ste lastnik",
"YOUAREMEMBER":"Ste član",
/* Profiles */
"MYNETWORK":"Moje omrežje",
"ALLPEOPLE":"Vse osebe",
"EXCLUDEINACTIVE":"Izvzemi nedejavne osebe",
"PHONE":"Telefon:",
"EMAIL":"Elektronska pošta:",
/* Communities */
"ALLCOMMUNITIES":"Vse skupnosti",
"PUBLICCOMMUNITIES":"Javne skupnosti",
"MYCOMMUNITIES":"Moje skupnosti",
"EVERYTHINGCOMMUNITIES":"Vse iz skupnosti",
"COMMUNITIESONLY":"Skupnosti",
"COMMUNITIESCONTENT":"Vsebina iz skupnosti",
/* Activities */
"ALLACTIVITIES":"Vse dejavnosti",
"PUBLICACTIVITIES":"Javne dejavnosti",
"MYACTIVITIES":"Moje dejavnosti",
"EVERYTHINGACTIVITIES":"Vse iz dejavnosti",
"ACTIVITIESONLY":"Dejavnosti",
"SECTIONSACTIVITIES": "Razdelki iz dejavnosti",
"ENTRIESACTIVITIES":"Vnosi iz dejavnosti",
"TODOSACTIVITIES":"Opravila iz dejavnosti",
"BOOKMARKSACTIVITIES":"Zaznamki iz dejavnosti",
"FILESACTIVITIES":"Priloge iz dejavnosti",
"ALLTYPESACTIVITIES":"Vse vrste iz dejavnosti",
"COMMUNITYACTIVITIES":"Dejavnosti iz skupnosti",
"STANDALONEACTIVITIES":"Samostojne dejavnosti",
/* Forums */
"ALLFORUMS":"Vsi forumi",
"PUBLICFORUMS":"Javni forumi",
"MYFORUMS":"Moji forumi",
"EVERYTHINGFORUMS":"Vse iz forumov",
"FORUMSONLY":"Forumi",
"TOPICSFORUMS":"Teme na forumu",
"FORUMCATEGORIES": "Kategorije foruma",
"FILESFORUMS":"Priloge iz forumov",
"ALLTYPESFORUMS":"Vse vrste forumov",
"COMMUNITYFORUMS":"Forumi iz skupnosti",
"STANDALONEFORUMS":"Samostojni forumi",
/* Blogs */
"ALLBLOGS":"Vsi blogi",
"PUBLICBLOGS":"Javni blogi",
"MYBLOGS":"Moji blogi",
"EVERYTHINGBLOGS":"Vse iz blogov",
"BLOGSONLY":"Blogi",
"ENTRIESBLOGS":"Vnosi v blog",
"FILESBLOGS":"Priloge iz blogov",
"EVERYTHINGIDEATIONBLOGS":"Vse iz idejnih blogov",
"BLOGSIDEATIONBLOGS":"Idejni blogi",
"BLOGSIDEAS":"Ideje",
"ALLTYPESBLOGS":"Vse vrste blogov",
"COMMUNITYBLOGS":"Blogi iz skupnosti",
"COMMUNITYIDEATIONBLOGS":"Idejni blogi iz Skupnosti",
"STANDALONEBLOGS":"Samostojni blogi",
/* Bookmarks */
"ALLBOOKMARKS":"Vsi zaznamki",
"PUBLICBOOKMARKS":"Javni zaznamki",
"MYBOOKMARKS":"Moji zaznamki",
"ALLTYPESBOOKMARKS":"Vse vrste zaznamkov",
"COMMUNITYBOOKMARKS":"Zaznamki iz skupnosti",
"STANDALONEBOOKMARKS":"Samostojni zaznamki",
/* Files */
"ALLFILES":"Vse datoteke",
"PUBLICFILES":"Javne datoteke",
"MYFILES":"Moje datoteke",
"ALLTYPESFILES":"Vse vrste datotek",
"COMMUNITYFILES":"Datoteke iz skupnosti",
"STANDALONEFILES":"Samostojne datoteke",
"NUMDOWNLOADS":"Št. prenosov: {0}",
/* Wikis */
"ALLWIKIS":"Vsi wikiji",
"PUBLICWIKIS":"Javni wikiji",
"MYWIKIS":"Moji wikiji",
"EVERYTHINGWIKIS":"Vse iz wikijev",
"WIKISONLY":"Wikiji",
"PAGESWIKIS":"Strani wiki",
"FILESWIKIS":"Priloge iz wikijev",
"ALLTYPESWIKIS":"Vse vrste wikijev",
"COMMUNITYWIKIS":"Wikiji iz skupnosti",
"STANDALONEWIKIS":"Samostojni wikiji",
/* Status Updates */
"ALLSTATUSUPDATES":"Posodobitve vseh statusov",
"PUBLICSTATUSUPDATES":"Posodobitve javnih statusov",
"MYSTATUSUPDATES":"Posodobitve mojih statusov",
"ALLTYPESSTATUSUPDATES":"Vse vrste posodobitev statusov",
"COMMUNITYSTATUSUPDATES":"Posodobitve statusov iz skupnosti",
"STANDALONESTATUSUPDATES":"Posodobitve statusov iz profilov",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Ta URL je zaznamovalo več uporabnikov",
"BOOKMARKEDCOMMUNITY":"To skupnost je zaznamovalo več uporabnikov",
"BOOKMARKEDPROFILE":"Ta profil je zaznamovalo več uporabnikov",
"BOOKMARKEDBLOG":"Ta blog je zaznamovalo več uporabnikov",
"COMMUNITYBLOG":"To je blog znotraj skupnosti",
"BOOKMARKEDACTIVITY":"To dejavnost je zaznamovalo več uporabnikov",
"COMMUNITYACTIVITY":"To je dejavnost znotraj skupnosti",
"BOOKMARKEDFILE":"To datoteko je zaznamovalo več uporabnikov",
"COMMUNITYFILE":"To je datoteka znotraj skupnosti",
"BOOKMARKED":"Ta wiki je zaznamovalo več uporabnikov",
"COMMUNITYWIKI":"To je wiki znotraj skupnosti",
"BOOKMARKEDFORUM":"Ta forum je zaznamovalo več uporabnikov",
"COMMUNITYFORUM":"To je forum znotraj skupnosti",
"ALLTAGANDTTILE":"Če želite prikazati vse naslove in oznake za ta URL, kliknite ta gumb",
"TAGS_ARE_FROM":"Ta rezultat iskanja lahko vključuje oznake iz:",
"BOOKMARKS_TITLE":"Zaznamki",
"COMMUNITIES_TITLE":"Skupnosti",
"ACTIVITIES_TITLE":"Dejavnosti",
"HELP":"Pomoč",
"MORESTATUSUPDATES":"Pokaži več ujemanj za posodobitve statusov",
"TITLE_PREFIX":"naslov:",
"LATEST_MESSAGE":"Najnovejše sporočilo",
"LATEST_STATUS_UPDATE":"Najnovejša posodobitev statusa",
"LATEST_COMMUNITY_STATUS_UPDATE":"Najnovejša posodobitev statusa skupnosti",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Najnovejša posodobitev statusa skupnosti",
"SEARCH_RESULTS":"Vsi rezultati iskanja vsebine",
"ACTIVITIES_SEARCH_RESULTS":"Rezultati iskanja Dejavnosti",
"BLOGS_SEARCH_RESULTS":"Rezultati iskanja Blogov",
"BOOKMARKS_SEARCH_RESULTS":"Rezultati iskanja Zaznamkov",
"COMMUNITIES_SEARCH_RESULTS":"Rezultati iskanja Skupnosti",
"FILES_SEARCH_RESULTS":"Rezultati iskanja Datotek",
"FORUMS_SEARCH_RESULTS":"Rezultati iskanja Forumov",
"PROFILES_SEARCH_RESULTS":"Rezultati iskanja Profilov",
"DIRECTORY_SEARCH_RESULTS":"Rezultati iskanja imenika organizacije ${orgName}",
"WIKIS_SEARCH_RESULTS":"Rezultati iskanja Wikijev",
"STATUS_UPDATES_SEARCH_RESULTS":"Rezultati iskanja posodobitev statusov",
"VIEW_ALL":"{span}Prikaži vse{/span} ({0})",
"MATCHING_ONE_OF":"Ujemanje enega od:",
"MATCHING_ALL_OF":"Ujemanje vseh od:",
"MATCHING":"Ujemanje:",
"MATCHING_DOC_TYPE":"Vrsta ujemajočega se dokumenta:",
"BOOKMARK_HELP":"Pomoč za zaznamke",
"CLOSE_BOOKMARK_HELP":"Zapri pomoč za zaznamke",
"DOCUMENT_TYPE_PREFIX":"Vrsta dokumenta:",
"FILE_PREVIEW_ONLY":"(Samo način predogleda)"
})

