/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Келесі бойынша сүзу:",
		"SHOW":"Көрсету:",
		"ACL_FILTER_LABEL":"Көрінуі бойынша сүзгілеу",
		"PARENT_FILTER_LABEL":"Контейнер бойынша сүзгілеу",
		"TYPE_FILTER_LABEL":"Түрі бойынша сүзгілеуe",
		"PAGING_TOP":"Бастапқы беттеу",
		"PAGING_BOTTOM":"Қосымша бет",
		"PREVIOUS":"Алдыңғы",
		"NEXT":"Келесі",
		"PAGE":"{1} беттің {0} беті",
		"PAGE_COLON":"Беті:",
		"RESULTS":"{span}{0}-{1}{/span} қатысты {2}",
		"ITEMS":"{0} элементтер",
		/* Application names */
		"ACTIVITIES":"Әрекеттер",
		"BLOGS":"Блогтар",
		"CALENDAR":"Күнтізбе",
		"COMMUNITIES":"Қауымдастықтар",
		"BOOKMARKS":"Бетбелгілер",
		"DOGEAR":"Бетбелгілер",
		"EVENTS":"Оқиғалар",
		"FILES":"Файлдар",
		"FORUMS":"Форумдар",
		"PROFILES":"Профильдер",
		"WIKI":"Викилер",
		"WIKIS":"Викилер",
		"FEEDS":"Веб-арналар",
		"STATUS_UPDATES":"Күйі жаңартулары",
		"ONECOMMENT":"1 пікір",
		"COMMENTS":"{0} аңғартпалар",
		"ONEPERSON":"1 адам",
		"PEOPLE":"{0} адамдар",
		"TAGS":"Тегтер:",
		"TAGSMORE":"және тағы {0}",
		"NORESULTSMESSAGE":"Бұл іздеуге сәйкес нәтижелер табылмады",
		"JAN":"Қаңтар",
		"FEB":"Ақпан",
		"MAR":"Наурыз",
		"APR":"Сәуір",
		"MAY":"Мамыр",
		"JUN":"Маусым",
		"JUL":"Шілде",
		"AUG":"Тамыз",
		"SEP":"Қыркүйек",
		"OCT":"Қазан",
		"NOV":"Қараша",
		"DEC":"Желтоқсан",
		"NO_CONTACT":"Сервер байланыссыз болғандықтан, іздеу орындалмады",
		"SERVER_ERROR":"Сервер қателігінен іздеу орындалмады",
		"SORT_BY":"Сұрыптау жолы:",
		"SORT_RELEVANCE":"Қатыстылық",
		"SORT_DATE":"Күн",
		"SORT_LAST_UPDATED":"Соңғы жаңартылған",
		"SORT_DUE_DATE":"Орындалу күні",
		"SORT_VISITS":"Кірулер",
		"SORT_COMMENTS":"Пікірлер",
		"SORT_RECOMMENDATION":"Ұнатулар",
		"SORT_POPULARITY":"Танымалдылығы",
		"SORT_FIRSTNAME":"Аты",
		"SORT_LASTNAME":"Тегі",
		"SORT_DOWNLOADS":"Жүктемелер",
		"SORT_TYPE":"Түр",
		"SORT_SIZE":"Өлшемі",
		"SORT_TITLE":"Тақырып",
		"PRIVATE":"Жеке",
		"MODERATED":"Модератормен басқарылады",
		"COMMUNITY_ACTIVITY":"Қауымдастық әрекеті",
		"COMMUNITY_BLOG":"Қауымдастық блогы",
		"COMMUNITY_FILE":"Қауымдастық файлы",
		"COMMUNITY_FORUM":"Қауымдастық форумы",
		"COMMUNITY_WIKI":"Қауымдастық викиі",
		"COMMUNITY_FEED":"Қауымдастық арнасы",
		"COMMUNITY_BOOKMARK":"Қауымдастық бетбелгісі",
		"NO_TAG":"Тегтер әлі жоқ",
		"NO_DATE":"Әлі күндер жоқ",
		"NO_PEOPLE":"Әлі адамдарсыз",
		"REMOVE_FILTER_LABEL":"Жою үшін нұқу",
		"REMOVE_FILTER_TITLE":"Жою",
		"REMOVE_FILTER_TOOLTIP":"Бұл сүзгіні алып тастау",
		"COMMENT_ON":"Пікір беру:",
		"EXPAND_COLLAPSE":"Ашу немесе тасалау үшін нұқу",
		"EXPAND":"Ашу",
		"COLLAPSE":"Тасалау",
		"EXPAND_MONTHS_FILTER":"{0} жылдың айлар сүзгісін ашу",
		"SORT_RELEVANCE_LABEL":"Маңыздылығы бойынша сұрыптау үшін басу",
		"SORT_DATE_LABEL":"Күн бойынша сұрыптау үшін нұқу",
		"SORT_UPDATED_LABEL":"Соңғы жаңартылғандар бойынша сұрыптау үшін басу",
		"SORT_DUE_LABEL":"Орындалу күні бойынша сұрыптау үшін нұқу",
		"SORT_VISITS_LABEL":"Кірулердің саны бойынша сұрыптау үшін нұқу",
		"SORT_COMMENTS_LABEL":"Анғартпалар саны бойынша сұрыптау үшін нұқу",
		"SORT_RECOMMENDATIONS_LABEL":"Ұнатулар саны бойынша сұрыптау үшін басыңыз",
		"SORT_POPULARITY_LABEL":"Танымалдығы бойынша сұрыптау үшін нұқу",
		"SORT_FIRST_NAME_LABEL":"Берілген ат бойынша сұрыптауды басыңыз",
		"SORT_LAST_NAME_LABEL":"Тегі бойынша сұрыптау үшін нұқу",
		"RATING":"Ұнатулар",
		"GRADUATED":"Біткен",
		"ONEVOTE":"1 дауыс",
		"VOTES":"{0} дауыс",
		"BOOKMARK_THIS_RESULT":"Мынаны белгілеу",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (белсенді емес)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} бет белгі қойылған адамдар",
		/* eg from an Activity */
		"FROMANACTIVITY":"Әрекеттен",
		"FROMABLOG":"Блогтан",
		"FROMANIDEATIONBLOG":"Ой мүмкіндігі блогынан",
		"FROMANEVENT":"Оқиғадан",
		"FROMAFORUM":"Форумнан",
		"FROMAWIKI":"Викиден",
		"FROMACOMMUNITY":"Қауымдастықтан",
		"FROMXCOMMUNITIES":"{0} қауымдастықтарынан",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Әрекет",
		"BLOG_ALONE":"Блог",
		"IDEATIONBLOG_ALONE":"Ой блогы",
		"ENTRY_ALONE":"Жазба",
		"EVENT_ALONE":"Оқиға",
		"FORUM_ALONE":"Форум",
		"WIKI_ALONE":"Вики",
		"COMMUNITY_ALONE":"Қауымдастық",
		"XCOMMUNITIES_ALONE":"{0} қауымдастықтар",
		"SHAREDCOMMUNITIES":"Осы қауымдастықтармен ортақтасқан",
		"INACOMMUNITY":"Қауымдастықта",
		"LASTUPDATED":"Іздеу реттеуіші соңғы рет жаңартылған:",
		"NODESCRIPTION":"Бұл нәтиже үшін сипаттама немесе бұлт жоқ.",
		"ATTACHMENT":"Тіркеме:",
		"ACTIVITY":"Әрекет:",
		"ACTIVITYBOOKMARK":"Әрекет бетбелгісі:",
		"ACTIVITYCOMMENT":"Белсенді пікір:",
		"ACTIVITYENTRY":"Әрекет жазбасы:",
		"ACTIVITYSECTION":"Әрекет бөлімі:",
		"ACTIVITYTODO":"Әрекет іс тізімі:",
		"BLOG":"Блог:",
		"BLOGENTRY":"Блог жазбасы:",
		"BLOGCOMMENT":"Блог пікірі:",
		"BOOKMARK":"Бетбелгі:",
		"CALENDAREVENT":"Оқиға:",
		"CATEGORY":"Санат:",
		"COMMENT":"Аңғартпа:",
		"COMMUNITY":"Қауымдастық:",
		"ENTRY":"Жазба:",
		"EVENTDATEON":"{0}: мәнінде",
		"EVENTISALLDAY":"Толық күн оқиғасы",
		"EVENTREPEATS":"Қайталаулар",
		"FEED":"Қоректендіру жүйесі:",
		"FILE":"Файл:",
		"FORUM":"Форум:",
		"FORUMCATEGORY":"Форум санаты:",
		"FORUMTOPIC":"Форум тақырыбы:",
		"IDEA":"Ой:",
		"IDEACOMMENT":"Ой пікірі:",
		"IDEATIONBLOG":"Ой жасау блогы:",
		"PAGE":"Беті:",
		"PROFILE":"Профиль:",
		"SECTION":"Білім:",
		"STATUSUPDATE":"Жаңарту күйі",
		"STATUSUPDATE_PREFIX":"Күй жаңартуы:",
		"TOPIC":"Тақырып:",
		"TOPIC_WITH_ATTACHMENT":"Тақырып",
		"WIKITYPE":"Вики:",
		"WIKIPAGE":"Вики беті:",
		"WIKIFILE":"Вики тіркемесі:",
		"SEARCH":"Іздеу:",
		"TODO":"Іс тізімі:",
		"ALLRESULTS":"Барлық нәтижелер",
		"PUBLICCONTENT":"Жалпы мазмұн",
		"MYCONTENT":"Менің мазмұным",
		"RESULTNOTFOUND":"Іздеген затыңызды табу мүмкін болмады ма?",
		"TEMPDIFFICULTIES":"Ескерту: Уақытша индекстеу ауыртпашылықтарына байланыст, іздеуіңіз соңғы {1} күнде өзгертілген {0} қамтымайды.",
		"TRYLATER":"Әрекетті кейін қайталап көріңіз.",
		"MULTIPLETEMPDIFFICULTIES":"Ескертпе: уақытша индекстеу қиыншылықтарына байланысты іздеуде жуырда ғана өзгертілген {0} қамтылмайды",
		"YOUAREAUTHOR":"Авторсыз",
		"YOUARECONTRIBUTOR":"Қатысушысыз",
		"YOUAREOWNER":"Сіз иеленушісіз",
		"YOUAREMEMBER":"Сіз мүшесіз",
		/* Profiles */
		"MYNETWORK":"Менің желім",
		"ALLPEOPLE":"Барлық адамдар",
		"EXCLUDEINACTIVE":"Әрекетсіз адамдарды шығару",
		"PHONE":"Телефон:",
		"EMAIL":"Электрондық пошта:",
		/* Communities */
		"ALLCOMMUNITIES":"Барлық қауымдастықтар",
		"PUBLICCOMMUNITIES":"Жалпы қауымдастықтар",
		"MYCOMMUNITIES":"Қауымдастықтарым",
		"EVERYTHINGCOMMUNITIES":"Барлығын қауымдастықтардан",
		"COMMUNITIESONLY":"Қауымдастықтар",
		"COMMUNITIESCONTENT":"Мазмұн қауымдастықтардан",
		/* Activities */
		"ALLACTIVITIES":"Барлық әрекеттер",
		"PUBLICACTIVITIES":"Ортақтандырылған әрекеттер",
		"MYACTIVITIES":"Менің әрекеттерім",
		"EVERYTHINGACTIVITIES":"Барлығы қауымдастықтардан",
		"ACTIVITIESONLY":"Әрекеттер",
		"SECTIONSACTIVITIES": "Әректтегі бөлімдер",
		"ENTRIESACTIVITIES":"Әрекеттегі жазбалар",
		"TODOSACTIVITIES":"Әрекеттердегі іс тізімдер",
		"BOOKMARKSACTIVITIES":"Әрекеттердегі бетбелгілер",
		"FILESACTIVITIES":"Әрекеттердегі тіркемелер",
		"ALLTYPESACTIVITIES":"Әрекеттердің барлық түрлері",
		"COMMUNITYACTIVITIES":"Қауымдастықтардағы әрекеттер",
		"STANDALONEACTIVITIES":"Бөлек әрекеттер",
		/* Forums */
		"ALLFORUMS":"Барлық форумдар",
		"PUBLICFORUMS":"Жалпы форумдар",
		"MYFORUMS":"Менің форумдарым",
		"EVERYTHINGFORUMS":"Барлығы форумдардан",
		"FORUMSONLY":"Форумдар",
		"TOPICSFORUMS":"Форум тақырыптары",
		"FORUMCATEGORIES": "Форум санаттары",
		"FILESFORUMS":"Форумдағы тіркемелер",
		"ALLTYPESFORUMS":"Форумдардың барлық түрлері",
		"COMMUNITYFORUMS":"Қауымдастықтардағы форумдар",
		"STANDALONEFORUMS":"Бөлек форумдар",
		/* Blogs */
		"ALLBLOGS":"Барлық блогтар",
		"PUBLICBLOGS":"Жалпы блогтар",
		"MYBLOGS":"Менің блогтарым",
		"EVERYTHINGBLOGS":"Барлығы блогтардан",
		"BLOGSONLY":"Блогтар",
		"ENTRIESBLOGS":"Блог жазбалары",
		"FILESBLOGS":"Блогтардағы тіркемелер",
		"EVERYTHINGIDEATIONBLOGS":"Ойластыру блогынан кез келген мән",
		"BLOGSIDEATIONBLOGS":"Ой мүмкіндік блогтары",
		"BLOGSIDEAS":"Ойлар",
		"ALLTYPESBLOGS":"Блогтардың барлық түрлері",
		"COMMUNITYBLOGS":"Қауымдастықтағы блогтар",
		"COMMUNITYIDEATIONBLOGS":"Қауымдастықтардағы Ой мүмкіндік блогтары",
		"STANDALONEBLOGS":"Бөлек блогтар",
		/* Bookmarks */
		"ALLBOOKMARKS":"Барлық бетбелгілер",
		"PUBLICBOOKMARKS":"Жалпы бетбелгілер",
		"MYBOOKMARKS":"Менің Бетбелгілерім",
		"ALLTYPESBOOKMARKS":"Бетбелгілердің барлық түрлері",
		"COMMUNITYBOOKMARKS":"Қауымдастықтағы бетбелгілер",
		"STANDALONEBOOKMARKS":"Бөлек бетбелгілер",
		/* Files */
		"ALLFILES":"Барлық файлдар",
		"PUBLICFILES":"Жалпы файлдар",
		"MYFILES":"Менің файлдарым",
		"ALLTYPESFILES":"Файлдардың барлық түрлері",
		"COMMUNITYFILES":"Қауымдастықтағы файлдар",
		"STANDALONEFILES":"Бөлек файлдар",
		"NUMDOWNLOADS":"{0} жүктемелер",
		/* Wikis */
		"ALLWIKIS":"Барлық вики-сайттар",
		"PUBLICWIKIS":"Ортақтандырылған викилер",
		"MYWIKIS":"Менің викилерім",
		"EVERYTHINGWIKIS":"Барлығы викиден",
		"WIKISONLY":"Викилер",
		"PAGESWIKIS":"Вики беттері",
		"FILESWIKIS":"Викидегі сілтемелер",
		"ALLTYPESWIKIS":"Викидің барлық түрлері",
		"COMMUNITYWIKIS":"Қауымдастықтағы викилер",
		"STANDALONEWIKIS":"Бөлек викилер",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Барлық күй жаңартулары",
		"PUBLICSTATUSUPDATES":"Жалпы күй жаңартулары",
		"MYSTATUSUPDATES":"Менің күй жаңартуларым",
		"ALLTYPESSTATUSUPDATES":"Күй жаңартуларының барлық түрлері",
		"COMMUNITYSTATUSUPDATES":"Қауымдастықтардагы күй жаңартулары",
		"STANDALONESTATUSUPDATES":"Профильдердегі күй жаңартулары",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Бұл URL мекен-жайы бірнеше пайдаланушылармен белгіленген",
		"BOOKMARKEDCOMMUNITY":"Осы қауымдастық бірнеше пайдаланушылармен белгіленген",
		"BOOKMARKEDPROFILE":"Бұл профиль бірнеше пайдаланушылармен белгіленген",
		"BOOKMARKEDBLOG":"Бұл блог бірнеше пайдаланушылармен белгіленген",
		"COMMUNITYBLOG":"Осы қауымдастық ішіндегі блог",
		"BOOKMARKEDACTIVITY":"Бұл әрекет бірнеше пайдаланушылармен белгіленген",
		"COMMUNITYACTIVITY":"Осы қауымдастық ішіндегі әрекет",
		"BOOKMARKEDFILE":"Бұл файл бірнеше пайдаланушылармен белгіленген",
		"COMMUNITYFILE":"Осы қауымдастық ішіндегі файл",
		"BOOKMARKED":"Бұл вики бірнеше пайдаланушылармен белгіленген",
		"COMMUNITYWIKI":"Осы қауымдастық ішіндегі вики",
		"BOOKMARKEDFORUM":"Бұл форум бірнеше пайдаланушылармен белгіленген",
		"COMMUNITYFORUM":"Осы қауымдастық ішіндегі форум",
		"ALLTAGANDTTILE":"Осы URL мекен-жайы үшін барлық атаулар мен тегтерді көру үшін осы батырманы басыңыз",
		"TAGS_ARE_FROM":"Бұл іздеу нәтижеде тегтер болуы мүмкін:",
		"BOOKMARKS_TITLE":"Бетбелгілер",
		"COMMUNITIES_TITLE":"Қауымдастықтар",
		"ACTIVITIES_TITLE":"Әрекеттер",
		"HELP":"Анықтама",
		"MORESTATUSUPDATES":"Қосымша күй жаңарту сәйкестіктерін көру",
		"TITLE_PREFIX":"тақырыбы:",
		"LATEST_MESSAGE":"Кейінгі хабарлама",
		"LATEST_STATUS_UPDATE":"Кейінгі күй жаңартуы",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Кейінгі қауымдастықтың күй жаңартуы",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Кейінгі қауымдастықтардың күй жаңартуы",
		"SEARCH_RESULTS":"Мазмұнды іздеудің барлық нәтижелері",
		"ACTIVITIES_SEARCH_RESULTS":"Әрекеттер бойынша іздеудің нәтижелері",
		"BLOGS_SEARCH_RESULTS":"Блогтар бойынша іздеудің нәтижелері",
		"BOOKMARKS_SEARCH_RESULTS":"Бетбелгілер іздеу нәтижелері",
		"COMMUNITIES_SEARCH_RESULTS":"Қауымдастықтар бойынша іздеудің нәтижелері",
		"FILES_SEARCH_RESULTS":"Файлдар бойынша іздеудің нәтижелері",
		"FORUMS_SEARCH_RESULTS":"Форумдар бойынша іздеудің нәтижелері",
		"PROFILES_SEARCH_RESULTS":"Профильдер бойынша іздеудің нәтижелері",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} каталогын іздеу нәтижелері",
		"WIKIS_SEARCH_RESULTS":"Викилер бойынша іздеудің нәтижелері",
		"STATUS_UPDATES_SEARCH_RESULTS":"Күй жаңартуларының іздеу нәтижелері",
		"VIEW_ALL":"{span}Барлығын Көру{/span} ({0})",
		"MATCHING_ONE_OF":"Келесінің біреуіне сәйкес келу:",
		"MATCHING_ALL_OF":"Барлығына сәйкес келу:",
		"MATCHING":"Сәйкестендіру:",
		"MATCHING_DOC_TYPE":"Құжат түрін салыстыру:",
		"BOOKMARK_HELP":"Бетбелгі анықтамасы",
		"CLOSE_BOOKMARK_HELP":"Бетбелгі анықтамасын жабу",
		"DOCUMENT_TYPE_PREFIX":"Құжат түрі:",
		"LAST_PAGE_MESSAGE": "Уау, бұл іздеу нәтижелері тым көп. Қосымша іздеу терминдерін енгізу арқылы іздеуіңізді тарлауға әрекет жасаңыз.",
		"LAST_PAGE_SUBMESSAGE": "Алғаш {resultNumber} байланысты нәтижелерді алудасыз."
});

