/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kattintson ide a névjegykártya megtekintéséhez",
	"label.semtag.hover.alt" : "Kattintson ide {0} névjegykártyájának megtekintéséhez",
	"label.semtag.hover.altA11Y" : "Kattintson ide vagy használja a Control+Enter billentyűkombinációt a névjegykártya megtekintéséhez",
	"label.personcard.dialog.title" : "{0} névjegykártyája",

	"errorDefaultMsg2" : "Hiba történt, forduljon a rendszergazdához.",

	"loadingSTStatus" : "Sametime-állapot betöltése...",
	"noStatuAvailable" : "A Sametime-állapot nem érhető el",

	"label.personcard.cardnomarkup" : "A névjegykártyát nem lehetett beolvasni",
	"label.inactive.user.msg" : "Ez a személy már nem aktív felhasználó",
	"label.message.information" : "Információk:",
	"label.personcard.noprofilemsg" : "Ehhez a személyhez nem létezik profil",
	"label.personcard.cardreqexpired" : "A névjegykártya beolvasási kérése lejárt",

	"label.bizcard.applinks.less" : "Részletek elrejtése",
	"label.bizcard.applinks.more" : "Részletek megjelenítése",

	"label.personcard.activitieslink" : "Tevékenységek",
	"label.personcard.activitieslink.title" : "Kattintson ide a megosztott tevékenységek megtekintéséhez",
	"label.personcard.blogslink" : "Blogok",
	"label.personcard.blogslink.title" : "Kattintson ide a személy blogjának megtekintéséhez",
	"label.personcard.communitieslink" : "Közösségek",
	"label.personcard.communitieslink.title" : "Kattintson ide a személy közösségeinek megtekintéséhez",
	"label.personcard.dogearlink" : "Könyvjelzők",
	"label.personcard.dogearlink.title" : "Kattintson ide a személy könyvjelzőinek megtekintéséhez",
	"label.personcard.fileslink" : "Fájlok",
	"label.personcard.fileslink.title" : "Kattintson ide a személy megosztott fájljainak megtekintéséhez",
	"label.personcard.forumlink" : "Fórumok",
	"label.personcard.forumlink.title" : "Kattintson ide a személy fórumbejegyzéseinek megtekintéséhez",
	"label.personcard.homepagelink" : "Kezdőlap",
	"label.personcard.homepagelink.title" : "Kattintson ide a személy kezdőlapjának megtekintéséhez",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Kattintson ide a személy mobiloldalának megtekintéséhez",
	"label.personcard.newslink" : "Hírek",
	"label.personcard.newslink.title" : "Kattintson ide a személy híreinek megtekintéséhez",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kattintson ide a személy profiljának megtekintéséhez",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kattintson ide a személy quickr megosztásainak megtekintéséhez",
	"label.personcard.wikislink" : "Wikik",
	"label.personcard.wikislink.title" : "Kattintson ide a személy wiki oldalainak megtekintéséhez",

	"personCardMoreActions" : "További műveletek",
	"personCardMoreActionsAltText" : "Kattintson ide a műveletmenü megjelenítéséhez",

	"label.bizcard.dismiss": "Nyomja meg az escape gombot a névjegykártya bezárásához.",
	"label.bizcard.fullProfile": "Teljes profil",
	"label.bizcard.activities": "Tevékenységek",
	"label.bizcard.communities": "Közösségek",
	"label.bizcard.files": "Fájlok",
	"label.bizcard.forums": "Fórumok",
	"label.bizcard.bookmarks": "Könyvjelzők",
	"label.bizcard.blogs": "Blogok",
	"label.bizcard.wikis": "Wikik",

	"personCardAddAsColleagues" : "Meghívás saját hálózatba",
	"personCardAddAsMyColleagues" : "Meghívás saját hálózatba",
	"personCardFollow" : "Követés",
	"personCardUnfollow" : "Követés leállítása",
	"personCardChat" : "Csevegés",
	"personCardCall" : "Hívás",
	"personCardSendMail" : "E-mail küldése",
	"personCardSendEMail" : "E-mail küldése",
	"personCardProxyStatusAvailable" : "Elérhető vagyok",
	"personCardDownloadVCard" : "vCard letöltése",

	"friends" : "Hálózat",
	"friendsFullPageTitle" : "Hálózat",
	"friendsMenuTitleAllContacts" : "Minden hálózati kapcsolattartó",
	"friendsMenuTitleMyContacts" : "Saját hálózati kapcsolattartók",
	"friendsInvitations" : "Meghívások",
	"friendsMenuTitleInCommon" : "Közös személyek",
	"friendsShowAllCommonFriends" : "Összes megjelenítése...",
	"friendsViewAllFriends" : "Összes megtekintése ({0})",
	"friendsSendFriendRequest" : "Kérés küldése",
	"friendsNoFriends" : "Nem tartoznak hálózati kapcsolatok ehhez a profilhoz",
	"friendsColleaguesInvite" : "{0} meghívása a hálózati kapcsolataihoz",
	"friendsColleaguesFor" : "{0} hálózati kapcsolatai",
	"friendsNewInv" : "{0} új meghívás",
	"friendsNewInvs" : "{0} új meghívás",
	"friendsLoading" : "Hálózat betöltése...",
	"friendsLoadingInv" : "Meghívások betöltése...",
	"friendsSelectFriendForRemoval" : "Először válassza ki az eltávolítandó névjegyeket.",
	"friendsRemoved" : "A hálózati kapcsolatok eltávolítása sikeres.",
	"friendsInvSent" : "A program nem küldött meghívást, mert egy meghívás már függőben van.",
	"friendsRemovedSelected" : "Eltávolítás a saját hálózatból",
	"friendsSortByDisplayName" : "Megjelenő név",
	"friendsSortByRecent" : "Új",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "Másodlagos e-mail-cím:",
	"friendsNewInvitationsCount" : "{0} új meghívást kapott",
	"friendsNoInv" : "Nincs meghívás",
	"friendsInCommonSingle" : "{0} közös hálózati kapcsolat található",
	"friendsInCommonMulti" : "{0} közös hálózati kapcsolat található",
	"friendsIncludeMsgForInv" : "Üzenet csatolása a meghíváshoz:",
	"friendsInitialMsgForInv" : "Fel szeretném venni a Connections rendszerbeli hálózati kapcsolatlistámba.",
	"friendsSendInvAction" : "Meghívás küldése",
	"friendsCancelInvAction" : "Mégse",
	"friendsAcceptAction" : "Elfogadás",
	"friendsIgnoreAction" : "Mellőzés",
	"friendsYouExceedTextLimit" : "A meghívási üzenete túl hosszú, legfeljebb {1} karakter lehet. {0} karakter szerepel ebben a mezőben.",
	"friendsCannotAddYourself" : "Nem veheti fel saját magát hálózati kapcsolatként.",
	"friendsIsYourColleague" : "{0} a hálózati kapcsolata",
	"friendsRecentlyAdded" : "A hálózatba nemrég felvett személyek.",
	"friendsDate" : "Dátum",
	"friendsCollapseWidget" : "Kattintson ide a hálózati szakasz összecsukásához",
	"friendsExpandWidget" : "Kattintson ide a hálózati szakasz kibontásához",
	"friendsIsInYourNetwork" : "{0} a hálózatában van.",
	"friendsActionsFor" : "Hálózat műveletei",
	"friendsInviteFollowError" : "Hiba történt {0} követésére tett kísérlet során",
	"friendsInviteTagError" : "Hiba történt {0} címkézésére tett kísérlet során",
	"friendsPleaseLogIn" : "Jelentkezzen be személyek meghívásához a hálózatába",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "A meghívás a hálózatába nem lehetséges, mert {0} már a hálózatában van.",
	"friendsInviteAddTagsFor" : "Címkék hozzáadása a következőhöz: {0}",
	"friendsInviteAlsoFollow" : "Ugyancsak kövesse",
	"friendsInviteReceiveUpdates" : "(frissítések fogadása)",
	"friendsInviteUpdatesDescription" : "Frissítések fogadása a követett személyekről a Kezdőlapon és e-mail-összegzésben.",
	"friendsInviteFollowHelp": "További információkat itt talál: {0}Személyek követése{1}.",
	"friendsNetwork" : "Hálózat",
	"friendsMyNetwork" : "Hálózat",
	"friendsNetworkFor" : "{0} hálózata",
	"friendsRemoveSelected" : "Kijelöltek eltávolítása",
	"friendsRemoveSelectedTip" : "Kattintson ide a kijelölt személyek eltávolításához a hálózatából.",
	"friendsNetworkInCommon" : "{0} közös hálózati kapcsolatuk van.",
	"friendsAddToMyNetwork" : "Szeretném felvenni Önt a Connections hálózatomba.",
	"friendsInvite" : "Meghívás saját hálózatba",
	"friendsInvitePerson" : "{0} meghívása a hálózatába",
	"friendsInviteMessage" : "Szeretném felvenni Önt a Connections hálózatomba.",
	"friendsInvitedEmailSubject" : "[Profilok] Meghívom Önt a hálózatomba",
	"friendsInvitedEmailMsg1" : "meghívta a hálózatába, és a következő üzenetet tartalmazta a meghívás:",
	"friendsInvitedEmailMsg2" : "A Hálózati meghívás oldal megnyitása",
	"friendsInvitedEmailMsg3" : "Szeretném felvenni Önt a hálózatomba.",
	"friendsInvitedEmailMsg4" : "{0} meghívta a hálózatába:",
	"friendsInvitedEmailMsg5" : "{0} meghívta a hálózatába, és a következő üzenetet tartalmazta a meghívás:",
	"friendsInviteLegalNote" : "A meghívás elküldésével hozzájárul, hogy {0} megjegyzést írjon a profilja üzenőfalára.",
	"friendsInviteFailed" : "Szerverhiba miatt nem kapott e-mail-értesítést a meghívott. A Profilok webalkalmazáson keresztül a meghívottak azonban elfogadhatják a meghívást.",
	"personInNetwork" : "Hálózati kapcsolat"
})
