/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Нажмите здесь для просмотра визитной карточки",
	"label.semtag.hover.alt" : "Нажмите здесь для просмотра визитной карточки ({0})",
	"label.semtag.hover.altA11Y" : "Щелкните здесь или нажмите Ctrl+ВВОД для просмотра визитной карточки",
	"label.personcard.dialog.title" : "Визитная карточку для {0}",

	"errorDefaultMsg2" : "Возникла ошибка, обратитесь к системному администратору",

	"loadingSTStatus" : "Загрузка состояния Sametime...",
	"noStatuAvailable" : "Состояние Sametime недоступно",

	"label.personcard.cardnomarkup" : "Не удалось извлечь визитную карточку",
	"label.inactive.user.msg" : "Этот пользователь больше неактивен",
	"label.message.information" : "Информационное сообщение:",
	"label.personcard.noprofilemsg" : "Нет профиля этого пользователя",
	"label.personcard.cardreqexpired" : "Запрос на получение визитной карточки с истекшим сроком",

	"label.bizcard.applinks.less" : "Показать меньше",
	"label.bizcard.applinks.more" : "Показать больше",

	"label.personcard.activitieslink" : "Операции",
	"label.personcard.activitieslink.title" : "Нажмите здесь для просмотра общих операций",
	"label.personcard.blogslink" : "Блоги",
	"label.personcard.blogslink.title" : "Нажмите здесь для просмотра блога этого пользователя",
	"label.personcard.communitieslink" : "Сообщества",
	"label.personcard.communitieslink.title" : "Нажмите здесь для просмотра сообществ этого пользователя",
	"label.personcard.dogearlink" : "Закладки",
	"label.personcard.dogearlink.title" : "Нажмите здесь для просмотра закладок этого пользователя",
	"label.personcard.fileslink" : "Файлы",
	"label.personcard.fileslink.title" : "Нажмите здесь для просмотра общих файлов этого пользователя",
	"label.personcard.forumlink" : "Форумы",
	"label.personcard.forumlink.title" : "Нажмите здесь для просмотра постов на форуме этого пользователя",
	"label.personcard.homepagelink" : "Домашняя страница",
	"label.personcard.homepagelink.title" : "Нажмите здесь для просмотра домашней страницы этого пользователя",
	"label.personcard.mobilelink" : "Страница для мобильных устройств",
	"label.personcard.mobilelink.title" : "Нажмите здесь для просмотра страницы этого пользователя для мобильных устройств",
	"label.personcard.newslink" : "Новости",
	"label.personcard.newslink.title" : "Нажмите здесь для просмотра новостей этого пользователя",
	"label.personcard.profilelink" : "Профиль",
	"label.personcard.profilelink.title" : "Нажмите здесь для просмотра профиля этого пользователя",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Нажмите здесь для просмотра общих ресурсов Quickr этого пользователя",
	"label.personcard.wikislink" : "Вики",
	"label.personcard.wikislink.title" : "Нажмите здесь для просмотра вики этого пользователя",

	"personCardMoreActions" : "Дополнительные действия",
	"personCardMoreActionsAltText" : "Щелкните для просмотра меню действий",

	"label.bizcard.dismiss": "Для того чтобы закрыть визитную карточку, нажмите клавишу Esc.",
	"label.bizcard.fullProfile": "Полный профиль",
	"label.bizcard.activities": "Операции",
	"label.bizcard.communities": "Сообщества",
	"label.bizcard.files": "Файлы",
	"label.bizcard.forums": "Форумы",
	"label.bizcard.bookmarks": "Закладки",
	"label.bizcard.blogs": "Блоги",
	"label.bizcard.wikis": "Вики",

	"personCardAddAsColleagues" : "Пригласить в мою сеть",
	"personCardAddAsMyColleagues" : "Пригласить в мою сеть",
	"personCardFollow" : "Отслеживать",
	"personCardUnfollow" : "Прекратить отслеживание",
	"personCardChat" : "Разговор",
	"personCardCall" : "Вызов",
	"personCardSendMail" : "Отправить письмо",
	"personCardSendEMail" : "Отправить письмо",
	"personCardProxyStatusAvailable" : "Доступен",
	"personCardDownloadVCard" : "Загрузить визитную карточку",

	"friends" : "Сеть",
	"friendsFullPageTitle" : "Сеть",
	"friendsMenuTitleAllContacts" : "Все сетевые контакты",
	"friendsMenuTitleMyContacts" : "Мои сетевые контакты",
	"friendsInvitations" : "Приглашения",
	"friendsMenuTitleInCommon" : "Общие контакты",
	"friendsShowAllCommonFriends" : "Показать все...",
	"friendsViewAllFriends" : "Показать все ({0})",
	"friendsSendFriendRequest" : "Отправить запрос",
	"friendsNoFriends" : "С этим профилем не связаны контакты",
	"friendsColleaguesInvite" : "Пригласить {0} в вашу сеть",
	"friendsColleaguesFor" : "Контакты пользователя {0}",
	"friendsNewInv" : "{0} новое приглашение",
	"friendsNewInvs" : "Новых приглашений: {0}",
	"friendsLoading" : "Загружается сеть...",
	"friendsLoadingInv" : "Загрузка приглашений...",
	"friendsSelectFriendForRemoval" : "Сначала выберите контакты, которые хотите удалить.",
	"friendsRemoved" : "Контакты удалены.",
	"friendsInvSent" : "Приглашение не отправлено, так как оно уже находится в состоянии ожидания.",
	"friendsRemovedSelected" : "Удалить из моей сети",
	"friendsSortByDisplayName" : "Отображаемое имя",
	"friendsSortByRecent" : "Последние",
	"friendsTelephone" : "Телефон:",
	"friendsEmail" : "Электронный адрес:",
	"friendsAltEmail" : "Альтернативный электронный адрес:",
	"friendsNewInvitationsCount" : "У вас есть новые приглашения ({0})",
	"friendsNoInv" : "Нет приглашений",
	"friendsInCommonSingle" : "У вас {0} общий контакт",
	"friendsInCommonMulti" : "У вас {0} общих контактов",
	"friendsIncludeMsgForInv" : "Добавить сообщение в приглашение:",
	"friendsInitialMsgForInv" : "Мне бы хотелось добавить вас в мой список контактов Connections.",
	"friendsSendInvAction" : "Отправить приглашение",
	"friendsCancelInvAction" : "Отмена",
	"friendsAcceptAction" : "Принять",
	"friendsIgnoreAction" : "Игнорировать",
	"friendsYouExceedTextLimit" : "Слишком длинное приглашение. Допускается не более {1} символов. Это поле содержит {0} символов.",
	"friendsCannotAddYourself" : "Невозможно добавить себя в список своих контактов",
	"friendsIsYourColleague" : "{0} является вашим контактом",
	"friendsRecentlyAdded" : "Пользователи, которых вы недавно добавили в свою сеть.",
	"friendsDate" : "Дата",
	"friendsCollapseWidget" : "Нажмите для свертывания раздела сети",
	"friendsExpandWidget" : "Нажмите для развертывания раздела сети",
	"friendsIsInYourNetwork" : "{0} из вашей сети.",
	"friendsActionsFor" : "Действия для сети",
	"friendsInviteFollowError" : "При попытке начать отслеживание пользователя {0} произошла ошибка",
	"friendsInviteTagError" : "При попытке отметить пользователя {0} произошла ошибка",
	"friendsPleaseLogIn" : "Для того чтобы пригласить других пользователей в свою сеть, необходимо войти в систему.",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0} невозможно пригласить в сеть, так как он уже является ее участником.",
	"friendsInviteAddTagsFor" : "Добавить теги для пользователя {0}:",
	"friendsInviteAlsoFollow" : "Также отслеживать",
	"friendsInviteReceiveUpdates" : "(получать обновления)",
	"friendsInviteUpdatesDescription" : "Получать обновления информации о пользователях, которых вы отслеживаете, на домашней странице и по электронной почте.",
	"friendsInviteFollowHelp": "Дополнительная информация приведена в разделе {0}Отслеживание пользователей{1}.",
	"friendsNetwork" : "Сеть",
	"friendsMyNetwork" : "Сеть",
	"friendsNetworkFor" : "Сеть {0}",
	"friendsRemoveSelected" : "Удалить выбранное",
	"friendsRemoveSelectedTip" : "Щелкните для удаления выбранных пользователей из вашей сети.",
	"friendsNetworkInCommon" : "У вас {0} общих сетевых контактов.",
	"friendsAddToMyNetwork" : "Мне бы хотелось добавить вас в мою сеть Connections.",
	"friendsInvite" : "Пригласить в мою сеть",
	"friendsInvitePerson" : "Пригласить {0} в вашу сеть",
	"friendsInviteMessage" : "Мне бы хотелось добавить вас в мою сеть Connections.",
	"friendsInvitedEmailSubject" : "[Профили] Вы приглашены в мою сеть",
	"friendsInvitedEmailMsg1" : "пригласил вас в свою сеть, указав в приглашении следующее:",
	"friendsInvitedEmailMsg2" : "Открыть страницу приглашения в сеть",
	"friendsInvitedEmailMsg3" : "Мне бы хотелось добавить вас в сеть.",
	"friendsInvitedEmailMsg4" : "Пользователь {0} пригласил вас в свою сеть контактов:",
	"friendsInvitedEmailMsg5" : "Пользователь {0} пригласил вас в свою сеть контактов и включил в приглашение следующее сообщение:",
	"friendsInviteLegalNote" : "Отправляя это приглашение, вы даете свое согласие на то, чтобы {0} размещал комментарии на доске объявлений вашего профиля.",
	"friendsInviteFailed" : "Уведомление не было отправлено приглашенному по электронной почте из-за ошибки сервера. Однако приглашенный сможет принять ваше приглашение через веб-приложение \"Профили\".",
	"personInNetwork" : "Контакт"
})
