/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Information för följande nod: ",
	"INSTALLED": "Kontrollerar de installerade tjänsterna",
	"RESUMETOKENS": "Kontrollerar fortsättningselementen",
	"SEEDLISTS": "Kontrollerar att startlistorna är tillgängliga",
	"CALENDARS": "Kontrollerar att schemaläggningskalendrarna har konfigurerats på rätt sätt",
	"VARIABLES": "Kontrollerar att WebSphere-variablerna har angetts",
	"TASKS": "Kontrollerar om det finns några aktiverade indexeringsuppgifter",
	"INDEXFILES": "Kontrollerar att de obligatoriska filerna finns i indexmappen",
	"LOGS": "Kontrollerar om det finns några fel i loggarna",
	"CONFIGFILES": "Kontrollerar konfigurationsfilerna",
	"DICTIONARIES": "Kontrollerar antalet aktiverade ordlistor",
	"SYNC": "Kontrollerar nodstatus",
	"DBRECORDS": "Kontrollerar databasposterna",
	"INSTALLEDMSG": "Följande tjänst är installerad: ",
	"RESUMETOKENSMSG": "Fortsättningselement för följande: ",
	"SEEDLISTSMSG": "Det gick inte att hämta startlistan för följande: ",
	"CALENDARSMSG": "Kontrollerar schemaläggningskalendern: ",
	"VARIABLESMSG": "Variabel: ",
	"TASKSMSG": "Följande uppgift är aktiverad: ",
	"INDEXFILESMSG" : "Följande filer finns i sökindexmappen: ",
	"LOGSMSG" : "Granska följande felmeddelanden: ",
	"CONFIGFILESMSG" : "Följande konfigurationsfiler hittades: ",
	"DICTIONARIESMSG" : "Antal aktiverade ordlistor: ",
	"INSYNC": "Alla noder är synkroniserade",
	"OUTOFSYNC": "Antal osynkroniserade noder: ",
	"NOTBLOCKED": "Inga noder är blockerade",
	"BLOCKED": "Antal blockerade noder: ",
	"INDATE": "Alla noder är aktuella",
	"OUTOFDATE": "Antal inaktuella noder: ",
	"NUMOFDOCS": "Antal dokument i databasen: ",
	"FILESTOCONVERT": "Antalet konverterade fildokument är ",
	"CONVERTEDFILES": "Antal konverterade filer: ",
	"TOTALFILES": "Totalt antal filer i databasen: ",
	"ERROR":"Fel",
	"ERROR_PREFIX":"Fel:",
	"INFO":"Information",
	"INFO_PREFIX":"Information:",
	"WARNING":"Varning",
	"WARNING_PREFIX":"Varning!",
	"LOADING_MESSAGE": "Läser in",
	"SERVER_STATUS": "Serverstatus",
	"INITIAL_INDEXING_EXCEPTIONS": "Indexeringsstartsundantag",
	"SYS_OUT_EXCEPTIONS": "SystemOut-loggundantag",
	"SEEDLIST_VALIDATE": "Startlistvalidering",
	"ERRORS_DURING_INITIAL_INDEXING":"Följande undantag inträffade när initialt index skapades",
	"CRAWL_FAILED": "Det gick inte att samla in all information om följande tjänst: ",
	"EXCEPTION_ENCOUNTERED": "Insamlingen misslyckades med följande fel: ",
	"SAND_VALIDATE": "SAND-validering",
	"CHECK_FOR_SAND_FILES":"Kontrollerar om det finns några SAND-filer",
	"IS_FILE_AVAILABLE":"Kontrollerar att filen har skapats: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Följande undantag inträffade när initialt index skapades",
	"CRAWL_FAILED":"Det gick inte att samla in all information om följande tjänst: ",
	"EXCEPTION_ENCOUNTERED":"Insamlingen misslyckades med följande fel: "
})

