/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrera efter:",
"SHOW":"Visa:",
"ACL_FILTER_LABEL":"Filtrera efter synlighet",
"PARENT_FILTER_LABEL":"Filtrera efter behållare",
"TYPE_FILTER_LABEL":"Filtrera efter typ",
"PAGING_TOP":"Primära sidnavigeringskontroller",
"PAGING_BOTTOM":"Sekundära sidnavigeringskontroller",
"PREVIOUS":"Föregående",
"NEXT":"Nästa",
"PAGE":"Sida {0} av {1}",
"PAGE_COLON":"Sida:",
"RESULTS":"{span}{0} - {1}{/span} av {2}",
"ITEMS":"{0} objekt",
/* Application names */
"ACTIVITIES":"Aktiviteter",
"BLOGS":"Bloggar",
"CALENDAR":"Kalender",
"COMMUNITIES":"Gemenskaper",
"BOOKMARKS":"Bokmärken",
"DOGEAR":"Bokmärken",
"EVENTS":"Händelser",
"FILES":"Filer",
"FORUMS":"Forum",
"PROFILES":"Profiler",
"WIKI":"Wikier",
"WIKIS":"Wikier",
"FEEDS":"Flöden",
"STATUS_UPDATES":"Statusuppdateringar",
"ONECOMMENT":"1 kommentar",
"COMMENTS":"{0} kommentarer",
"ONEPERSON":"1 person",
"PEOPLE":"{0} personer",
"TAGS":"Taggar:",
"TAGSMORE":"och {0} till",
"NORESULTSMESSAGE":"Det gick inte att hitta några resultat för sökningen",
"JAN":"januari",
"FEB":"februari",
"MAR":"mars",
"APR":"april",
"MAY":"maj",
"JUN":"juni",
"JUL":"juli",
"AUG":"augusti",
"SEP":"september",
"OCT":"oktober",
"NOV":"november",
"DEC":"december",
"NO_CONTACT":"Det gick inte att ansluta till servern. Det gick inte att utföra sökningen.",
"SERVER_ERROR":"Det uppstod ett serverfel. Det gick inte att utföra sökningen.",
"SORT_BY":"Sortera efter:",
"SORT_RELEVANCE":"Relevans",
"SORT_DATE":"Datum",
"SORT_LAST_UPDATED":"Uppdaterades",
"SORT_DUE_DATE":"Slutdatum",
"SORT_VISITS":"Besök",
"SORT_COMMENTS":"Kommentarer",
"SORT_RECOMMENDATION":"Gillanden",
"SORT_POPULARITY":"Popularitet",
"SORT_FIRSTNAME":"Förnamn",
"SORT_LASTNAME":"Efternamn",
"SORT_DOWNLOADS":"Nedladdningar",
"SORT_TYPE":"Typ",
"SORT_SIZE":"Storlek",
"SORT_TITLE":"Namn",
"PRIVATE":"Privat",
"MODERATED":"Modererad",
"COMMUNITY_ACTIVITY":"Gemenskapsaktivitet",
"COMMUNITY_BLOG":"Gemenskapsblogg",
"COMMUNITY_FILE":"Gemenskapsfil",
"COMMUNITY_FORUM":"Gemenskapsforum",
"COMMUNITY_WIKI":"Gemenskapswiki",
"COMMUNITY_FEED":"Gemenskapsflöde",
"COMMUNITY_BOOKMARK":"Gemenskapsbokmärke",
"NO_TAG":"Det finns inga taggar",
"NO_DATE":"Det finns inga datum",
"NO_PEOPLE":"Det finns inga personer ännu",
"REMOVE_FILTER_LABEL":"Klicka här om du vill ta bort",
"REMOVE_FILTER_TITLE":"Ta bort",
"REMOVE_FILTER_TOOLTIP":"Ta bort det här filtret",
"COMMENT_ON":"Kommentar till:",
"EXPAND_COLLAPSE":"Klicka här om du vill expandera/komprimera",
"EXPAND":"Expandera",
"COLLAPSE":"Komprimera",
"EXPAND_MONTHS_FILTER":"Expandera månadsfiltret för år {0}",
"SORT_RELEVANCE_LABEL":"Klicka här om du vill sortera efter relevans",
"SORT_DATE_LABEL":"Klicka här om du vill sortera efter datum",
"SORT_UPDATED_LABEL":"Klicka här om du vill sortera efter uppdateringsdatum",
"SORT_DUE_LABEL":"Klicka här om du vill sortera efter slutdatum",
"SORT_VISITS_LABEL":"Klicka här om du vill sortera efter antal besök",
"SORT_COMMENTS_LABEL":"Klicka här om du vill sortera efter antal kommentarer",
"SORT_RECOMMENDATIONS_LABEL":"Klicka här om du vill sortera efter antal gillanden",
"SORT_POPULARITY_LABEL":"Klicka här om du vill sortera efter popularitet",
"SORT_FIRST_NAME_LABEL":"Klicka här om du vill sortera efter förnamn",
"SORT_LAST_NAME_LABEL":"Klicka här om du vill sortera efter efternamn",
"RATING":"Gillanden",
"GRADUATED":"Utvecklad",
"ONEVOTE":"1 röst",
"VOTES":"{0} röster",
"BOOKMARK_THIS_RESULT":"Lägg till ett bokmärke",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inaktiv)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} bokmärkta personer",
/* eg from an Activity */
"FROMANACTIVITY":"från en aktivitet",
"FROMABLOG":"från en blogg",
"FROMANIDEATIONBLOG":"från en idéblogg",
"FROMANEVENT":"från en händelse",
"FROMAFORUM":"från ett forum",
"FROMAWIKI":"från en wiki",
"FROMACOMMUNITY":"från en gemenskap",
"FROMXCOMMUNITIES":"från {0} gemenskaper",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivitet",
"BLOG_ALONE":"Blogg",
"IDEATIONBLOG_ALONE":"Idéblogg",
"ENTRY_ALONE":"Inlägg",
"EVENT_ALONE":"Händelse",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Gemenskap",
"XCOMMUNITIES_ALONE":"{0} gemenskaper",
"SHAREDCOMMUNITIES":"Delat med följande gemenskaper",
"INACOMMUNITY":"i en gemenskap",
"LASTUPDATED":"Sökindexet uppdaterades:",
"NODESCRIPTION":"Det finns ingen beskrivning eller sammanfattning för det här resultatet.",
"ATTACHMENT":"Bilaga:",
"ACTIVITY":"Aktivitet:",
"ACTIVITYBOOKMARK":"Aktivitetsbokmärke:",
"ACTIVITYCOMMENT":"Aktivitetskommentar:",
"ACTIVITYENTRY":"Aktivitetspost:",
"ACTIVITYSECTION":"Aktivitetsavsnitt:",
"ACTIVITYTODO":"Att göra-uppgift för aktivitet:",
"BLOG":"Blogg:",
"BLOGENTRY":"Blogginlägg:",
"BLOGCOMMENT":"Bloggkommentar:",
"BOOKMARK":"Bokmärke:",
"CALENDAREVENT":"Händelse:",
"CATEGORY":"Kategori:",
"COMMENT":"Kommentar:",
"COMMUNITY":"Gemenskap:",
"ENTRY":"Inlägg:",
"EVENTDATEON":"{0}",
"EVENTISALLDAY":"Heldagshändelse",
"EVENTREPEATS":"Upprepas",
"FEED":"Flöde:",
"FILE":"Fil:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forumkategori:",
"FORUMTOPIC":"Forumämne:",
"IDEA":"Idé:",
"IDEACOMMENT":"Idékommentar:",
"IDEATIONBLOG":"Idéblogg:",
"PAGE":"Sida:",
"PROFILE":"Profil:",
"SECTION":"Avsnitt:",
"STATUSUPDATE":"Statusuppdatering",
"STATUSUPDATE_PREFIX":"Statusuppdatering:",
"TOPIC":"Ämne:",
"TOPIC_WITH_ATTACHMENT":"Ämne",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Wikisida:",
"WIKIFILE":"Wikibilaga:",
"SEARCH":"Sök efter:",
"TODO":"Att göra-uppgift:",
"ALLRESULTS":"Alla resultat",
"PUBLICCONTENT":"Gemensamt innehåll",
"MYCONTENT":"Mitt innehåll",
"RESULTNOTFOUND":"Visades inte det du sökte efter?",
"TEMPDIFFICULTIES":"Anm. På grund av tillfälliga indexeringsproblem ingår inte {0} som har ändrats under de senaste {1} dagarna i din sökning.",
"TRYLATER":"Försök igen senare.",
"MULTIPLETEMPDIFFICULTIES":"Anm. På grund av tillfälliga indexeringsproblem ingår inte {0} som nyligen har ändrats i din sökning.",
"YOUAREAUTHOR":"Du är författare",
"YOUARECONTRIBUTOR":"Du är medverkande",
"YOUAREOWNER":"Du är ägare",
"YOUAREMEMBER":"Du är medlem",
/* Profiles */
"MYNETWORK":"Mitt nätverk",
"ALLPEOPLE":"Alla personer",
"EXCLUDEINACTIVE":"Ta inte med inaktiva personer",
"PHONE":"Telefonnummer:",
"EMAIL":"Mejladress:",
/* Communities */
"ALLCOMMUNITIES":"Alla gemenskaper",
"PUBLICCOMMUNITIES":"Gemensamma gemenskaper",
"MYCOMMUNITIES":"Mina gemenskaper",
"EVERYTHINGCOMMUNITIES":"Allt från Gemenskaper",
"COMMUNITIESONLY":"Gemenskaper",
"COMMUNITIESCONTENT":"Innehåll från Gemenskaper",
/* Activities */
"ALLACTIVITIES":"Alla aktiviteter",
"PUBLICACTIVITIES":"Gemensamma aktiviteter",
"MYACTIVITIES":"Mina aktiviteter",
"EVERYTHINGACTIVITIES":"Allt från Aktiviteter",
"ACTIVITIESONLY":"Aktiviteter",
"SECTIONSACTIVITIES": "Avsnitt från Aktiviteter",
"ENTRIESACTIVITIES":"Poster från Aktiviteter",
"TODOSACTIVITIES":"Att göra-uppgifter från Aktiviteter",
"BOOKMARKSACTIVITIES":"Bokmärken från Aktiviteter",
"FILESACTIVITIES":"Bilagor från Aktiviteter",
"ALLTYPESACTIVITIES":"Alla typer av aktiviteter",
"COMMUNITYACTIVITIES":"Aktiviteter från Gemenskaper",
"STANDALONEACTIVITIES":"Fristående aktiviteter",
/* Forums */
"ALLFORUMS":"Alla forum",
"PUBLICFORUMS":"Gemensamma forum",
"MYFORUMS":"Mina forum",
"EVERYTHINGFORUMS":"Allt från Forum",
"FORUMSONLY":"Forum",
"TOPICSFORUMS":"Forumämnen",
"FORUMCATEGORIES": "Forumkategorier",
"FILESFORUMS":"Bilagor från Forum",
"ALLTYPESFORUMS":"Alla typer av forum",
"COMMUNITYFORUMS":"Forum från Gemenskaper",
"STANDALONEFORUMS":"Fristående forum",
/* Blogs */
"ALLBLOGS":"Alla bloggar",
"PUBLICBLOGS":"Gemensamma bloggar",
"MYBLOGS":"Mina bloggar",
"EVERYTHINGBLOGS":"Allt från Bloggar",
"BLOGSONLY":"Bloggar",
"ENTRIESBLOGS":"Blogginlägg",
"FILESBLOGS":"Bilagor från Bloggar",
"EVERYTHINGIDEATIONBLOGS":"Allt från Idébloggar",
"BLOGSIDEATIONBLOGS":"Idébloggar",
"BLOGSIDEAS":"Idéer",
"ALLTYPESBLOGS":"Alla typer av bloggar",
"COMMUNITYBLOGS":"Bloggar från Gemenskaper",
"COMMUNITYIDEATIONBLOGS":"Idébloggar från Gemenskaper",
"STANDALONEBLOGS":"Fristående bloggar",
/* Bookmarks */
"ALLBOOKMARKS":"Alla bokmärken",
"PUBLICBOOKMARKS":"Gemensamma bokmärken",
"MYBOOKMARKS":"Mina bokmärken",
"ALLTYPESBOOKMARKS":"Alla typer av bokmärken",
"COMMUNITYBOOKMARKS":"Bokmärken från Gemenskaper",
"STANDALONEBOOKMARKS":"Fristående bokmärken",
/* Files */
"ALLFILES":"Alla filer",
"PUBLICFILES":"Gemensamma filer",
"MYFILES":"Mina filer",
"ALLTYPESFILES":"Alla typer av filer",
"COMMUNITYFILES":"Filer från Gemenskaper",
"STANDALONEFILES":"Fristående filer",
"NUMDOWNLOADS":"{0} nedladdningar",
/* Wikis */
"ALLWIKIS":"Alla wikier",
"PUBLICWIKIS":"Gemensamma wikier",
"MYWIKIS":"Mina wikier",
"EVERYTHINGWIKIS":"Allt från Wikier",
"WIKISONLY":"Wikier",
"PAGESWIKIS":"Wikisidor",
"FILESWIKIS":"Bilagor från Wikier",
"ALLTYPESWIKIS":"Alla typer av wikier",
"COMMUNITYWIKIS":"Wikier från Gemenskaper",
"STANDALONEWIKIS":"Fristående wikier",
/* Status Updates */
"ALLSTATUSUPDATES":"Alla statusuppdateringar",
"PUBLICSTATUSUPDATES":"Gemensamma statusuppdateringar",
"MYSTATUSUPDATES":"Mina statusuppdateringar",
"ALLTYPESSTATUSUPDATES":"Alla typer av statusuppdateringar",
"COMMUNITYSTATUSUPDATES":"Statusuppdateringar från Gemenskaper",
"STANDALONESTATUSUPDATES":"Statusuppdateringar från Profiler",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Det finns ett antal användare som har lagt till bokmärken för den här URL-adressen",
"BOOKMARKEDCOMMUNITY":"Det finns ett antal användare som har lagt till bokmärken för den här gemenskapen",
"BOOKMARKEDPROFILE":"Det finns ett antal användare som har lagt till bokmärken för den här profilen",
"BOOKMARKEDBLOG":"Det finns ett antal användare som har lagt till bokmärken för den här bloggen",
"COMMUNITYBLOG":"Det här är en blogg i en gemenskap",
"BOOKMARKEDACTIVITY":"Det finns ett antal användare som har lagt till bokmärken för den här aktiviteten",
"COMMUNITYACTIVITY":"Det här är en aktivitet i en gemenskap",
"BOOKMARKEDFILE":"Det finns ett antal användare som har lagt till bokmärken för den här filen",
"COMMUNITYFILE":"Det här är en fil i en gemenskap",
"BOOKMARKED":"Det finns ett antal användare som har lagt till bokmärken för den här wikin",
"COMMUNITYWIKI":"Det här är en wiki i en gemenskap",
"BOOKMARKEDFORUM":"Det finns ett antal användare som har lagt till bokmärken för det här forumet",
"COMMUNITYFORUM":"Det här är ett forum i en gemenskap",
"ALLTAGANDTTILE":"Om du vill se alla namn och taggar för URL-adressen klickar du på den här knappen",
"TAGS_ARE_FROM":"Det kan finnas taggar från följande i det här sökresultatet:",
"BOOKMARKS_TITLE":"Bokmärken",
"COMMUNITIES_TITLE":"Gemenskaper",
"ACTIVITIES_TITLE":"Aktiviteter",
"HELP":"Hjälp",
"MORESTATUSUPDATES":"Visa fler statusuppdateringsmatchningar",
"TITLE_PREFIX":"namn:",
"LATEST_MESSAGE":"Senaste meddelande",
"LATEST_STATUS_UPDATE":"Senaste statusuppdatering",
"LATEST_COMMUNITY_STATUS_UPDATE":"Senaste gemenskapsstatusuppdatering",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Senaste statusuppdatering för Gemenskaper",
"SEARCH_RESULTS":"Sökresultat för allt innehåll",
"ACTIVITIES_SEARCH_RESULTS":"Sökresultat för Aktiviteter",
"BLOGS_SEARCH_RESULTS":"Sökresultat för Bloggar",
"BOOKMARKS_SEARCH_RESULTS":"Sökresultat för Bokmärken",
"COMMUNITIES_SEARCH_RESULTS":"Sökresultat för Gemenskaper",
"FILES_SEARCH_RESULTS":"Sökresultat för Filer",
"FORUMS_SEARCH_RESULTS":"Sökresultat för Forum",
"PROFILES_SEARCH_RESULTS":"Sökresultat för Profiler",
"DIRECTORY_SEARCH_RESULTS":"Sökresultat för ${orgName}-katalogen",
"WIKIS_SEARCH_RESULTS":"Sökresultat för Wikier",
"STATUS_UPDATES_SEARCH_RESULTS":"Sökresultat för Statusuppdateringar",
"VIEW_ALL":"{span}Visa alla{/span} ({0})",
"MATCHING_ONE_OF":"Överensstämmer med något av följande:",
"MATCHING_ALL_OF":"Överensstämmer med alla följande:",
"MATCHING":"Som överensstämmer med följande:",
"MATCHING_DOC_TYPE":"Som överensstämmer med följande dokumenttyp:",
"BOOKMARK_HELP":"Hjälp för bokmärken",
"CLOSE_BOOKMARK_HELP":"Stäng hjälpen för bokmärken",
"DOCUMENT_TYPE_PREFIX":"Dokumenttyp:",
"FILE_PREVIEW_ONLY":"(Endast förhandsgranskningsläge)"
})

