/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Añadir imagen",
   newUpload : "Nueva carga",
   URL : "URL",
   imageLibrary : "Biblioteca de imágenes",
   description : "Descripción:",
   imageFile : "Archivos:",
   OK: "Aceptar",
   cancel: "Cancelar",
   required: "Campo obligatorio",
   preview: "Vista previa:",
   previewWarning: "Parece que la imagen no se ha podido cargar, ¿está seguro de que el url de imagen es válido?",
   alt: "Texto alternativo:",
   filesTab: "Desde Archivos",
   images:"Imágenes:",
   browse:"Examinar...",
   imagePickerTitle:"Insertar imágenes de archivos",
   componentImagePickerTitle:" ${0} imágenes subidas",
   /* New String for insert image dialog */
   title: "Insertar imagen",
   uploadBtn: "Cargar imagen",   
   insertBtn: "Insertar imagen",
   uploadTab: "Archivos locales",
   externalTab: "URL de web",
   internalTab: "Imágenes existentes",
   fileFieldTip: "Arrastre y suelte las imágenes de su escritorio directamente en esta ventana para subirlas.",
   AdditionalSection: "Opciones adicionales",
   ExpandSection: "Expandir opciones adicionales",
   CloseSection: "Contraer opciones adicionales",
   webURLPrompt: "URL de imagen web:",
   previewPrompt: "Área de vista previa: es posible que las imágenes grandes tarden un rato en visualizarse.",
   noExistingImage: "¡Uy! No se ha añadido ninguna imagen todavía.",
   selectExistingImage: "Seleccione una imagen existente:",
   urlMissing: "Indique un URL",
   urlInvalid: "URL no válido. Asegúrese de especificar un URL válido y pruebe de nuevo.",
   previousItem: "Anterior",
   nextItem: "Siguiente",
   oneImageOneTime: "Ya se ha añadido una imagen a esta ventana. Solo puede insertar una imagen a la vez.",
   loadingErrorMsg: "Se ha producido un error al cargar imágenes existentes. Inténtelo de nuevo más tarde",
   urlInputTooltip: "Especifique el URL web de la imagen."
})

