/* Copyright IBM Corp. 2011, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknite ovde da biste prikazali vizitkartu",
	"label.semtag.hover.alt" : "Kliknite da biste prikazali vizitkartu za {0}",
	"label.semtag.hover.altA11Y" : "Kliknite ovde ili pritisnite kombinaciju tastera control-enter da biste prikazali vizitkartu",
	"label.personcard.dialog.title" : "Vizitkarta za {0}",

	"errorDefaultMsg2" : "Došlo je do greške, kontaktirajte administratora sistema",

	"loadingSTStatus" : "Učitavanje Sametime statusa...",
	"noStatuAvailable" : "Nije dostupan Sametime status",

	"label.personcard.cardnomarkup" : "Nije moguće preuzeti vizitkartu",
	"label.inactive.user.msg" : "Osoba više nije aktivni korisnik",
	"label.message.information" : "Informacije:",
	"label.personcard.noprofilemsg" : "Profil ne postoji za ovu osobu",
	"label.personcard.cardreqexpired" : "Zahtev za nabavljanje vizitkarte je istekao",

	"label.bizcard.applinks.less" : "Prikaži manje",
	"label.bizcard.applinks.more" : "Prikaži više",

	"label.personcard.activitieslink" : "Aktivnosti",
	"label.personcard.activitieslink.title" : "Kliknite ovde da biste videli deljene aktivnosti",
	"label.personcard.blogslink" : "Blogovi",
	"label.personcard.blogslink.title" : "Kliknite ovde da biste videli blog osobe",
	"label.personcard.communitieslink" : "Zajednice",
	"label.personcard.communitieslink.title" : "Kliknite ovde da biste videli zajednice osobe",
	"label.personcard.dogearlink" : "Obeleživači",
	"label.personcard.dogearlink.title" : "Kliknite ovde da biste videli obeleživače osobe",
	"label.personcard.fileslink" : "Datoteke",
	"label.personcard.fileslink.title" : "Kliknite ovde da biste videli deljene datoteke osobe",
	"label.personcard.forumlink" : "Forumi",
	"label.personcard.forumlink.title" : "Kliknite ovde da biste videli postove na forumu osobe",
	"label.personcard.homepagelink" : "Početna stranica",
	"label.personcard.homepagelink.title" : "Kliknite ovde da biste videli početnu stranicu osobe",
	"label.personcard.mobilelink" : "Mobilni uređaj",
	"label.personcard.mobilelink.title" : "Kliknite ovde da biste videli stranicu mobilnog uređaja osobe",
	"label.personcard.newslink" : "Novine",
	"label.personcard.newslink.title" : "Kliknite ovde da biste videli novine osobe",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknite ovde da biste videli profil osobe",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknite ovde da biste videli quickr deljenja osobe",
	"label.personcard.wikislink" : "Vikiji",
	"label.personcard.wikislink.title" : "Kliknite ovde da biste videli vikije osobe",

	"personCardMoreActions" : "Više radnji",
	"personCardMoreActionsAltText" : "Kliknite za meni radnji",

	"label.bizcard.dismiss": "Pritisnite taster escape da biste odbacili vizitkartu.",

	"personCardAddAsColleagues" : "Pozovi u aplikaciju Moja mreža",
	"personCardAddAsMyColleagues" : "Pozovi u aplikaciju Moja mreža",
	"personCardFollow" : "Prati",
	"personCardUnfollow" : "Prekini praćenje",
	"personCardChat" : "Ćaskanje",
	"personCardCall" : "Poziv",
	"personCardSendMail" : "Pošalji e-poštu",
	"personCardSendEMail" : "Pošalji e-poštu",
	"personCardProxyStatusAvailable" : "Dostupna sam",
	"personCardDownloadVCard" : "Preuzmi vCard",

	"friends" : "Mreža",
	"friendsFullPageTitle" : "Mreža",
	"friendsMenuTitleAllContacts" : "Svi kontakti na mreži",
	"friendsMenuTitleMyContacts" : "Moji kontakti na mreži",
	"friendsInvitations" : "Pozivi",
	"friendsMenuTitleInCommon" : "Zajedničke osobe",
	"friendsShowAllCommonFriends" : "Prikaži sve...",
	"friendsViewAllFriends" : "Prikaži sve ({0})",
	"friendsSendFriendRequest" : "Pošalji zahtev",
	"friendsNoFriends" : "Nijedan kontakt na mreži nije pridružen ovom profilu",
	"friendsColleaguesInvite" : "Pozovite {0} da bude kontakt na mreži",
	"friendsColleaguesFor" : "Kontakti na mreži za {0}",
	"friendsNewInv" : "{0} novi poziv",
	"friendsNewInvs" : "{0} novi pozivi",
	"friendsLoading" : "Učitavanje mreže...",
	"friendsLoadingInv" : "Učitavanje poziva...",
	"friendsSelectFriendForRemoval" : "Izaberite kontakte koje prvo želite da uklonite.",
	"friendsRemoved" : "Uklonjeni kontakt(i) na mreži.",
	"friendsInvSent" : "Nijedan poziv nije poslat jer je poziv već na čekanju.",
	"friendsRemovedSelected" : "Ukloni iz moje mreže",
	"friendsSortByDisplayName" : "Prikaži ime",
	"friendsSortByRecent" : "Nedavno",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-pošta:",
	"friendsAltEmail" : "Alternativna e-pošta:",
	"friendsNewInvitationsCount" : "Imate {0} novi(h) poziv(a)",
	"friendsNoInv" : "Nema poziva",
	"friendsInCommonSingle" : "Imate {0} zajednički kontakt na mreži",
	"friendsInCommonMulti" : "Imate {0} zajedničkih kontakata na mreži",
	"friendsIncludeMsgForInv" : "Pozivom obuhvatite poruku:",
	"friendsInitialMsgForInv" : "Želeo bih da vas dodam u svoju listu kontakata na mreži Connections.",
	"friendsSendInvAction" : "Pošalji poziv",
	"friendsCancelInvAction" : "Otkaži",
	"friendsAcceptAction" : "Prihvati",
	"friendsIgnoreAction" : "Zanemari",
	"friendsYouExceedTextLimit" : "Poruka poziva je predugačka. Ona može imati maksimalno {1} znakova. U ovom polju ima {0} znakova.",
	"friendsCannotAddYourself" : "Nije moguće da dodate sebe kao kontakta na mreži.",
	"friendsIsYourColleague" : "{0} je vaš kontakt na mreži",
	"friendsRecentlyAdded" : "Osobe koje ste nedavno dodali u svoju mrežu.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Kliknite da biste skupili odeljak mreža",
	"friendsExpandWidget" : "Kliknite da biste proširili odeljak mreža",
	"friendsIsInYourNetwork" : "{0} nalazi se u vašoj mreži.",
	"friendsActionsFor" : "Radnje za mrežu",
	"friendsInviteFollowError" : "Došlo je do greške tokom pokušaja da pratite {0}",
	"friendsInviteTagError" : "Došlo je do greške tokom pokušaja da označite {0}",
	"friendsPleaseLogIn" : "Prijavite se da biste pozvali osobe u vašu mrežu",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Nije moguće poslati poziv u vašu mrežu jer se {0} već nalazi u vašoj mreži.",
	"friendsInviteAddTagsFor" : "Dodaj oznake za {0}:",
	"friendsInviteAlsoFollow" : "Takođe prati",
	"friendsInviteReceiveUpdates" : "(primajte novosti)",
	"friendsInviteUpdatesDescription" : "Primajte novosti o osobama koje pratite na početnoj stranici i u rezimeu e-pošte.",
	"friendsInviteFollowHelp": "Za više informacija, videti odeljak {0}Praćenje osoba{1}.",
	"friendsNetwork" : "Mreža",
	"friendsMyNetwork" : "Mreža",
	"friendsNetworkFor" : "Mreža za {0}",
	"friendsRemoveSelected" : "Ukloni izabrano",
	"friendsRemoveSelectedTip" : "Kliknite da biste uklonili izabrane osobe iz vaše mreže.",
	"friendsNetworkInCommon" : "Imate {0} zajedničkih konekcija na mreži.",
	"friendsAddToMyNetwork" : "Voleo bih da te dodam u mrežu mojih konekcija.",
	"friendsInvite" : "Pozivanje u moju mrežu",
	"friendsInvitePerson" : "Pozovite {0} u svoju mrežu",
	"friendsInviteMessage" : "Voleo bih da te dodam u mrežu mojih konekcija.",
	"friendsInvitedEmailSubject" : "[Profili] Pozvani ste da se pridružite mojoj mreži",
	"friendsInvitedEmailMsg1" : "vas je pozvao da postanete kontakt na mreži sledećom porukom u pozivu:",
	"friendsInvitedEmailMsg2" : "Otvorite svoju stranicu Poziv na mreži",
	"friendsInvitedEmailMsg3" : "Želeo bih da vas dodam u svoju mrežu.",
	"friendsInvitedEmailMsg4" : "{0} vas je pozvao da postanete kontakt na mreži:",
	"friendsInvitedEmailMsg5" : "{0} vas je pozvao da postanete kontakt na mreži sledećom porukom u pozivu:",
	"friendsInviteLegalNote" : "Slanjem ovog poziva, slažete se da omogućavate {0} komentarisanje na tabli profila.",
	"friendsInviteFailed" : "Zbog greške na serveru, obaveštenje e-pošte nije poslato pozvanom korisniku. Međutim, pozvani korisnik još uvek je u mogućnosti da prihvati vaš poziv preko veb aplikacije Profili."
})

