/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrovať podľa:",
"SHOW":"Zobraziť:",
"ACL_FILTER_LABEL":"Filtrovať podľa viditeľnosti",
"PARENT_FILTER_LABEL":"Filtrovať podľa kontajnera",
"TYPE_FILTER_LABEL":"Filtrovať podľa typu",
"PAGING_TOP":"Primárne stránkovanie",
"PAGING_BOTTOM":"Sekundárne stránkovanie",
"PREVIOUS":"Predchádzajúci",
"NEXT":"Ďalší",
"PAGE":"Stránka {0} z {1}",
"PAGE_COLON":"Stránka:",
"RESULTS":"{span}{0} - {1}{/span} z {2}",
"ITEMS":"{0} položiek",
/* Application names */
"ACTIVITIES":"Aktivity",
"BLOGS":"Blogy",
"CALENDAR":"Kalendár",
"COMMUNITIES":"Komunity",
"BOOKMARKS":"Záložky",
"DOGEAR":"Záložky",
"EVENTS":"Udalosti",
"FILES":"Súbory",
"FORUMS":"Fóra",
"PROFILES":"Profily",
"WIKI":"Wiki",
"WIKIS":"Wiki",
"FEEDS":"Informačné kanály",
"STATUS_UPDATES":"Aktualizácie stavu",
"ONECOMMENT":"Jeden komentár",
"COMMENTS":"{0} komentárov",
"ONEPERSON":"Jedna osoba",
"PEOPLE":"{0} osôb",
"TAGS":"Značky:",
"TAGSMORE":"a {0} ďalších",
"NORESULTSMESSAGE":"Pre dané vyhľadávanie sa nenašli žiadne výsledky",
"JAN":"Január",
"FEB":"Február",
"MAR":"Marec",
"APR":"Apríl",
"MAY":"Máj",
"JUN":"Jún",
"JUL":"Júl",
"AUG":"August",
"SEP":"September",
"OCT":"Október",
"NOV":"November",
"DEC":"December",
"NO_CONTACT":"Vyhľadávanie nebolo vykonané, pretože nebolo možné kontaktovať server",
"SERVER_ERROR":"Vyhľadávanie sa nevykonalo pre chybu servera",
"SORT_BY":"Zoradiť podľa:",
"SORT_RELEVANCE":"Relevancia",
"SORT_DATE":"Dátum",
"SORT_LAST_UPDATED":"Posledná aktualizácia",
"SORT_DUE_DATE":"Termín",
"SORT_VISITS":"Návštevy",
"SORT_COMMENTS":"Komentáre",
"SORT_RECOMMENDATION":"Páči sa mi",
"SORT_POPULARITY":"Popularita",
"SORT_FIRSTNAME":"Krstné meno",
"SORT_LASTNAME":"Priezvisko",
"SORT_DOWNLOADS":"Prevzatia",
"SORT_TYPE":"Typ",
"SORT_SIZE":"Veľkosť",
"SORT_TITLE":"Nadpis",
"PRIVATE":"Súkromné",
"MODERATED":"Moderovaná",
"COMMUNITY_ACTIVITY":"Aktivita komunity",
"COMMUNITY_BLOG":"Blog komunity",
"COMMUNITY_FILE":"Súbor komunity",
"COMMUNITY_FORUM":"Fórum komunity",
"COMMUNITY_WIKI":"Wiki komunity",
"COMMUNITY_FEED":"Informačný kanál komunity",
"COMMUNITY_BOOKMARK":"Záložka komunity",
"NO_TAG":"Zatiaľ žiadne značky",
"NO_DATE":"Zatiaľ žiadne dátumy",
"NO_PEOPLE":"Zatiaľ žiadni ľudia",
"REMOVE_FILTER_LABEL":"Kliknutím odstránite položku",
"REMOVE_FILTER_TITLE":"Odstrániť",
"REMOVE_FILTER_TOOLTIP":"Odstrániť tento filter",
"COMMENT_ON":"Komentár k:",
"EXPAND_COLLAPSE":"Kliknutím rozviniete/zviniete",
"EXPAND":"Rozvinúť",
"COLLAPSE":"Zvinúť",
"EXPAND_MONTHS_FILTER":"Rozvinúť filter mesiacov roka {0}",
"SORT_RELEVANCE_LABEL":"Kliknutím aktivujete zoradenie podľa relevancie",
"SORT_DATE_LABEL":"Kliknutím aktivujete zoradenie podľa dátumu",
"SORT_UPDATED_LABEL":"Kliknutím aktivujete zoradenie podľa poslednej aktualizácie",
"SORT_DUE_LABEL":"Kliknutím aktivujete zoradenie podľa termínu",
"SORT_VISITS_LABEL":"Kliknutím aktivujete zoradenie podľa počtu návštev",
"SORT_COMMENTS_LABEL":"Kliknutím aktivujete zoradenie podľa počtu komentárov",
"SORT_RECOMMENDATIONS_LABEL":"Kliknutím aktivujete zoradenie podľa počtu označení páči sa",
"SORT_POPULARITY_LABEL":"Kliknutím aktivujete zoradenie podľa popularity",
"SORT_FIRST_NAME_LABEL":"Kliknutím aktivujete zoradenie podľa krstného mena",
"SORT_LAST_NAME_LABEL":"Kliknutím aktivujete zoradenie podľa priezviska",
"RATING":"Páči sa mi",
"GRADUATED":"Graduovaný",
"ONEVOTE":"Jeden hlas",
"VOTES":"{0} hlasov",
"BOOKMARK_THIS_RESULT":"Vytvoriť záložku pre toto",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (neaktívny)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"Vytvorená záložka pre {0} osôb",
/* eg from an Activity */
"FROMANACTIVITY":"z aktivity",
"FROMABLOG":"z blogu",
"FROMANIDEATIONBLOG":"z blogu nápadov",
"FROMANEVENT":"z udalosti",
"FROMAFORUM":"z fóra",
"FROMAWIKI":"z wiki",
"FROMACOMMUNITY":"z komunity",
"FROMXCOMMUNITIES":"z {0} komunít",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivita",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Blog nápadov",
"ENTRY_ALONE":"Položka",
"EVENT_ALONE":"Udalosť",
"FORUM_ALONE":"Fórum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Komunita",
"XCOMMUNITIES_ALONE":"{0} komunít",
"SHAREDCOMMUNITIES":"Zdieľané s týmito komunitami",
"INACOMMUNITY":"v komunite",
"LASTUPDATED":"Posledná aktualizácia vyhľadávacieho indexu:",
"NODESCRIPTION":"Žiadny opis alebo súhrn pre tento výsledok.",
"ATTACHMENT":"Príloha:",
"ACTIVITY":"Aktivita:",
"ACTIVITYBOOKMARK":"Záložka pre aktivitu:",
"ACTIVITYCOMMENT":"Komentár k aktivite:",
"ACTIVITYENTRY":"Položka aktivity:",
"ACTIVITYSECTION":"Sekcia aktivity:",
"ACTIVITYTODO":"Položka zoznamu úloh aktivity:",
"BLOG":"Blog:",
"BLOGENTRY":"Položka blogu:",
"BLOGCOMMENT":"Komentár k blogu:",
"BOOKMARK":"Záložka:",
"CALENDAREVENT":"Udalosť:",
"CATEGORY":"Kategória:",
"COMMENT":"Komentár:",
"COMMUNITY":"Komunita:",
"ENTRY":"Položka:",
"EVENTDATEON":"Dňa: {0}",
"EVENTISALLDAY":"Celodenná udalosť",
"EVENTREPEATS":"Opakovanie",
"FEED":"Informačný kanál:",
"FILE":"Súbor:",
"FORUM":"Fórum:",
"FORUMCATEGORY":"Kategória fóra:",
"FORUMTOPIC":"Téma fóra:",
"IDEA":"Nápad:",
"IDEACOMMENT":"Komentár k nápadu:",
"IDEATIONBLOG":"Blog nápadov:",
"PAGE":"Stránka:",
"PROFILE":"Profil:",
"SECTION":"Sekcia:",
"STATUSUPDATE":"Aktualizácia stavu",
"STATUSUPDATE_PREFIX":"Aktualizácia stavu:",
"TOPIC":"Téma:",
"TOPIC_WITH_ATTACHMENT":"Téma",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Stránka wiki:",
"WIKIFILE":"Príloha wiki:",
"SEARCH":"Hľadať.",
"TODO":"Položka zoznamu úloh:",
"ALLRESULTS":"Všetky výsledky",
"PUBLICCONTENT":"Verejný obsah",
"MYCONTENT":"Môj obsah",
"RESULTNOTFOUND":"Nenašli ste to, čo ste hľadali?",
"TEMPDIFFICULTIES":"Poznámka: Z dôvodu dočasných problémov pri indexovaní vaše vyhľadávanie nezahrnulo {0}, ktoré boli zmenené v posledných {1} dňoch.",
"TRYLATER":"Skúste to znova neskôr.",
"MULTIPLETEMPDIFFICULTIES":"Poznámka: Z dôvodu dočasných problémov pri indexovaní vaše vyhľadávanie nezahrnulo {0}, ktoré boli naposledy zmenené",
"YOUAREAUTHOR":"Ste autor",
"YOUARECONTRIBUTOR":"Ste prispievateľ",
"YOUAREOWNER":"Ste vlastník",
"YOUAREMEMBER":"Ste člen",
/* Profiles */
"MYNETWORK":"Moja sieť",
"ALLPEOPLE":"Všetci ľudia",
"EXCLUDEINACTIVE":"Vylúčiť neaktívnych ľudí",
"PHONE":"Telefónne číslo:",
"EMAIL":"E-mailová adresa:",
/* Communities */
"ALLCOMMUNITIES":"Všetky komunity",
"PUBLICCOMMUNITIES":"Verejné komunity",
"MYCOMMUNITIES":"Moje komunity",
"EVERYTHINGCOMMUNITIES":"Všetko z Komunít",
"COMMUNITIESONLY":"Komunity",
"COMMUNITIESCONTENT":"Obsah z Komunít",
/* Activities */
"ALLACTIVITIES":"Všetky aktivity",
"PUBLICACTIVITIES":"Verejné aktivity",
"MYACTIVITIES":"Moje aktivity",
"EVERYTHINGACTIVITIES":"Všetko z Komunít",
"ACTIVITIESONLY":"Aktivity",
"SECTIONSACTIVITIES": "Sekcie z Aktivít",
"ENTRIESACTIVITIES":"Položky z Aktivít",
"TODOSACTIVITIES":"Položky zoznam úloh z Aktivít",
"BOOKMARKSACTIVITIES":"Záložky z Aktivít",
"FILESACTIVITIES":"Prílohy z Aktivít",
"ALLTYPESACTIVITIES":"Všetky typ aktivít",
"COMMUNITYACTIVITIES":"Aktivity z Komunít",
"STANDALONEACTIVITIES":"Samostatné aktivity",
/* Forums */
"ALLFORUMS":"Všetky fóra",
"PUBLICFORUMS":"Verejné fóra",
"MYFORUMS":"Moje fóra",
"EVERYTHINGFORUMS":"Všetko z Fór",
"FORUMSONLY":"Fóra",
"TOPICSFORUMS":"Témy fóra",
"FORUMCATEGORIES": "Kategórie fóra",
"FILESFORUMS":"Prílohy z Fór",
"ALLTYPESFORUMS":"Všetky typy fór",
"COMMUNITYFORUMS":"Fóra z Komunít",
"STANDALONEFORUMS":"Samostatné fóra",
/* Blogs */
"ALLBLOGS":"Všetky blogy",
"PUBLICBLOGS":"Verejné blogy",
"MYBLOGS":"Moje blogy",
"EVERYTHINGBLOGS":"Všetko z Blogov",
"BLOGSONLY":"Blogy",
"ENTRIESBLOGS":"Položky blogu",
"FILESBLOGS":"Prílohy z Blogov",
"EVERYTHINGIDEATIONBLOGS":"Všetko z Blogov nápadov",
"BLOGSIDEATIONBLOGS":"Blogy nápadov",
"BLOGSIDEAS":"Nápady",
"ALLTYPESBLOGS":"Všetky typy blogov",
"COMMUNITYBLOGS":"Blogy z Komunít",
"COMMUNITYIDEATIONBLOGS":"Blogy nápadov z Komunít",
"STANDALONEBLOGS":"Samostatné Blogy",
/* Bookmarks */
"ALLBOOKMARKS":"Všetky záložky",
"PUBLICBOOKMARKS":"Verejné záložky",
"MYBOOKMARKS":"Moje záložky",
"ALLTYPESBOOKMARKS":"Všetky typy záložiek",
"COMMUNITYBOOKMARKS":"Záložky z komunít",
"STANDALONEBOOKMARKS":"Samostatné záložky",
/* Files */
"ALLFILES":"Všetky súbory",
"PUBLICFILES":"Verejné súbory",
"MYFILES":"Moje súbory",
"ALLTYPESFILES":"Všetky typy súborov",
"COMMUNITYFILES":"Súbory z Komunít",
"STANDALONEFILES":"Samostatné súbory",
"NUMDOWNLOADS":"{0} prevzatí",
/* Wikis */
"ALLWIKIS":"Všetky wiki",
"PUBLICWIKIS":"Verejné wiki",
"MYWIKIS":"Moje wiki",
"EVERYTHINGWIKIS":"Všetko z Wiki",
"WIKISONLY":"Wiki",
"PAGESWIKIS":"Stránky Wiki",
"FILESWIKIS":"Prílohy z Wiki",
"ALLTYPESWIKIS":"Všetky typy wiki",
"COMMUNITYWIKIS":"Wiki z Komunít",
"STANDALONEWIKIS":"Samostatné wiki",
/* Status Updates */
"ALLSTATUSUPDATES":"Všetky aktualizácie stavu",
"PUBLICSTATUSUPDATES":"Verejné aktualizácie stavu",
"MYSTATUSUPDATES":"Moje aktualizácie stavu",
"ALLTYPESSTATUSUPDATES":"Všetky typy aktualizácií stavu",
"COMMUNITYSTATUSUPDATES":"Aktualizácie stavu z Komunít",
"STANDALONESTATUSUPDATES":"Aktualizácie stavu z Profilov",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Pre túto adresu URL vytvorili záložku viacerí používatelia",
"BOOKMARKEDCOMMUNITY":"Pre túto komunitu vytvorili záložku viacerí používatelia",
"BOOKMARKEDPROFILE":"Pre tento profil vytvorili záložku viacerí používatelia",
"BOOKMARKEDBLOG":"Pre tento blog vytvorili záložku viacerí používatelia",
"COMMUNITYBLOG":"Toto je blog v komunite",
"BOOKMARKEDACTIVITY":"Pre túto aktivitu vytvorili záložku viacerí používatelia",
"COMMUNITYACTIVITY":"Toto je aktivita v komunite",
"BOOKMARKEDFILE":"Pre tento súbor vytvorili záložku viacerí používatelia",
"COMMUNITYFILE":"Toto je súbor v komunite",
"BOOKMARKED":"Pre toto wiki vytvorili záložku viacerí používatelia",
"COMMUNITYWIKI":"Toto je wiki v komunite",
"BOOKMARKEDFORUM":"Pre toto fórum vytvorili záložku viacerí používatelia",
"COMMUNITYFORUM":"Toto je fórum v komunite",
"ALLTAGANDTTILE":"Ak chcete zobraziť všetky nadpisy a značky pre túto adresu URL, kliknite na toto tlačidlo",
"TAGS_ARE_FROM":"Tento výsledok vyhľadávania môže zahŕňať značky z:",
"BOOKMARKS_TITLE":"Záložky",
"COMMUNITIES_TITLE":"Komunity",
"ACTIVITIES_TITLE":"Aktivity",
"HELP":"Pomoc",
"MORESTATUSUPDATES":"Zobraziť viac zhôd aktualizácií stavu",
"TITLE_PREFIX":"nadpis:",
"LATEST_MESSAGE":"Najnovšia správa",
"LATEST_STATUS_UPDATE":"Najnovšia aktualizácia stavu",
"LATEST_COMMUNITY_STATUS_UPDATE":"Najnovšia aktualizácia stavu komunity",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Najnovšia aktualizácia stavu komunít",
"SEARCH_RESULTS":"Výsledky vyhľadávania v Celom obsahu",
"ACTIVITIES_SEARCH_RESULTS":"Výsledky vyhľadávania v Aktivitách",
"BLOGS_SEARCH_RESULTS":"Výsledky vyhľadávania v Blogoch",
"BOOKMARKS_SEARCH_RESULTS":"Výsledky vyhľadávania v Záložkách",
"COMMUNITIES_SEARCH_RESULTS":"Výsledky vyhľadávania v Komunitách",
"FILES_SEARCH_RESULTS":"Výsledky vyhľadávania v Súboroch",
"FORUMS_SEARCH_RESULTS":"Výsledky vyhľadávania vo Fórach",
"PROFILES_SEARCH_RESULTS":"Výsledky vyhľadávania v Profiloch",
"DIRECTORY_SEARCH_RESULTS":"Výsledky vyhľadávania v adresári ${orgName}",
"WIKIS_SEARCH_RESULTS":"Výsledky vyhľadávania vo Wiki",
"STATUS_UPDATES_SEARCH_RESULTS":"Výsledky vyhľadávania v Aktualizáciách stavu",
"VIEW_ALL":"{span}Zobraziť všetko{/span} ({0})",
"MATCHING_ONE_OF":"Zhoda s jedným z:",
"MATCHING_ALL_OF":"Zhoda so všetkým:",
"MATCHING":"Zhoda:",
"MATCHING_DOC_TYPE":"Vyhovujúci typ dokumentu:",
"BOOKMARK_HELP":"Pomoc k záložke",
"CLOSE_BOOKMARK_HELP":"Zatvoriť pomoc k záložke",
"DOCUMENT_TYPE_PREFIX":"Typ dokumentu:",
"FILE_PREVIEW_ONLY":"(Iba režim náhľadu)"
})

