/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Informácie pre uzol: ",
	"INSTALLED": "Kontrolujú sa nainštalované služby",
	"RESUMETOKENS": "Kontrolujú sa symboly obnovenia",
	"SEEDLISTS": "Kontroluje sa, či sú k dispozícii zoznamy štartovacích bodov",
	"CALENDARS": "Kontroluje sa, či boli správne nakonfigurované kalendáre rozvrhu",
	"VARIABLES": "Kontrolujte, či boli nastavené premenné WebSphere",
	"TASKS": "Hľadajú sa povolené úlohy indexovania",
	"INDEXFILES": "V zložke indexu sa hľadajú vyžadované súbory",
	"LOGS": "Hľadajú sa chyby v protokoloch",
	"CONFIGFILES": "Kontrolujú sa konfiguračné súbory",
	"DICTIONARIES": "Kontroluje sa počet slovníkov, ktoré sú povolené",
	"SYNC": "Kontroluje sa stav uzlov",
	"DBRECORDS": "Kontrolujú sa databázové záznamy",
	"INSTALLEDMSG": "Je nainštalovaná táto služba: ",
	"RESUMETOKENSMSG": "Symbol obnovenia pre: ",
	"SEEDLISTSMSG": "Nebolo možné získať zoznam štartovacích bodov pre: ",
	"CALENDARSMSG": "Kalendár rozvrhu prešiel kontrolou: ",
	"VARIABLESMSG": "Premenná: ",
	"TASKSMSG": "Nasledujúca úloha je povolená: ",
	"INDEXFILESMSG" : "Nasledujúce súbory sú v zložke vyhľadávacieho indexu: ",
	"LOGSMSG" : "Skontrolujte tieto chybové správy: ",
	"CONFIGFILESMSG" : "Našli sa tieto konfiguračné súbory: ",
	"DICTIONARIESMSG" : "Počet povolených slovníkov je: ",
	"INSYNC": "Všetky uzly sú synchronizované",
	"OUTOFSYNC": "Počet uzlov, ktoré nie sú synchronizované: ",
	"NOTBLOCKED": "Nie sú zablokované žiadne uzly",
	"BLOCKED": "Počet zablokovaných uzlov je: ",
	"INDATE": "Všetky uzly sú aktuálne",
	"OUTOFDATE": "Počet uzlov, ktoré nie sú aktuálne, je: ",
	"NUMOFDOCS": "Počet dokumentov v databáze je ",
	"FILESTOCONVERT": "Počet súborových dokumentov na skonvertovanie je ",
	"CONVERTEDFILES": "Počet skonvertovaných súborov je ",
	"TOTALFILES": "Celkový počet súborov v databáze ",
	"ERROR":"Chyba",
	"ERROR_PREFIX":"Chyba:",
	"INFO":"Informácie",
	"INFO_PREFIX":"Informácie:",
	"WARNING":"Varovanie",
	"WARNING_PREFIX":"Varovanie:",
	"LOADING_MESSAGE": "Načítava sa",
	"SERVER_STATUS": "Stav servera",
	"INITIAL_INDEXING_EXCEPTIONS": "Výnimky pri počiatočnom indexovaní",
	"SYS_OUT_EXCEPTIONS": "Výnimky v protokole SystemOut",
	"SEEDLIST_VALIDATE": "Validácia zoznamov začiatočných pozícií",
	"ERRORS_DURING_INITIAL_INDEXING":"Počas vytvárania počiatočného indexu nastali nasledujúce výnimky",
	"CRAWL_FAILED": "Nebolo možné prehľadať všetky údaje pre nasledujúcu službu: ",
	"EXCEPTION_ENCOUNTERED": "Prehľadávanie zlyhalo s touto správou: ",
	"SAND_VALIDATE": "Validácia SAND",
	"CHECK_FOR_SAND_FILES":"Kontrolujú sa súbory SAND",
	"IS_FILE_AVAILABLE":"Kontroluje sa, či bol vytvorený súbor: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Počas vytvárania počiatočného indexu nastali nasledujúce výnimky",
	"CRAWL_FAILED":"Nebolo možné prehľadať všetky údaje pre nasledujúcu službu: ",
	"EXCEPTION_ENCOUNTERED":"Prehľadávanie zlyhalo s touto správou: "
})

