/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Det kreves en tittel.",
	nourl: "Det kreves en URL.",
	fileSchema: "Hvis du vil legge til en kobling til en ekstern eller lokal fil, må den ha ett av følgende formater: file://ekstern_bane eller file:///lokal_bane.",
	invalidUrl: "Dette er ikke en gyldig fellesskaps-URL.",
	invalidTagChar: "Listen over merker du skrev inn, inneholder det ugyldige tegnet &. Fjern dette tegnet fra listen over merker.",
	txtHelp: "Hjelp",
	txtHelpTags: "Hjelp til Tagger",
	txtHelpTagsClose: "Lukk hjelp til Tagger",
	tagsall: "Alle",
	tagsyours: "Dine",
	tagsrecent: "Nylig: ",
	tagspopular: "Populær: ",
	tagsrecommended: "Anbefalt: ",
	nothingselected: "Det kreves et fellesskapsvalg.",
	nothingselected_activity: "Det kreves et aktivitetsvalg.",
	nothingselected_blogs: "Det kreves et bloggvalg.",
	nothingselected_all: "Det er ikke valgt tjeneste eller oppføring. Bokmerket blir ikke lagret.",
	nothingFeedselected: "Det er ikke valgt tjeneste eller oppføring. Kanalen blir ikke lagret.",
	alertDialogTitle: "Melding",
	alertDialogOK: "OK",
	expand: "Klikk for å utvide denne seksjonen",
	collapse: "Klikk for å trekke sammen denne seksjonen",
	discussThis: "Diskuter dette",
	by: "av:",
	posted: "Lagt inn:",
	attachments: "Vedlegg",
	communityForum: "Fellesskapsforum",
	notCommunityPage: "Den gjeldende websiden er ikke en gyldig webside for fellesskapet. Du kan skrive inn fellesskapstittel, kobling og beskrivelse manuelt for å opprette et beslektet fellesskap.",
	privateCommunityNotice: "Dette fellesskapet er begrenset. Det er bare synlig for medlemmer av dette fellesskapet.",
	forumNameHint : "Skriv et forumnavn",
	formDescriptionHint:"Beskriv hvorfor dette beslektede fellesskapet vil være av interesse for fellesskapet ditt.",
	information : "Informasjon",
	error : "Feil",
	success : "Vellykket",
	warning : "Advarsel",
	informationColon : "Informasjon:",
	successColon : "Vellykket:",
	warningColon : "Advarsel:",
	errorColon : "Feil:",
	feedAlreadyExist : "Kanalen finnes allerede i fellesskapet.",
	bookmarkAlreadyExist : "Bokmerket finnes allerede i fellesskapet.",
	mentionAuthWarning:"Følgende personer som er omtalt, vil ikke kunne vise meldingen fordi de ikke er medlemmer av fellesskapet:",
	mentionAuthForumWarning:"Følgende personer som er omtalt, vil ikke kunne vise meldingen fordi de ikke har tilgang til dette forumet:",
	exceedDescLength: "Beskrivelsen du angav, er for lang.",
	communities_checked:"${0} fellesskap valgt",
	activities_checked:"${0} aktiviteter valgt",
	blogs_checked:"${0} blogger valgt"
})
