/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Güncelleştiren: ${author}",
		PREVIEW_MODE_ONLY: "(Salt Önizleme Modu)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Topluluk bugün görüntülendi",
		COMMUNITY_VIEWED_YESTERDAY: "Topluluk dün görüntülendi",
		COMMUNITY_VIEWED_HOURS_AGO: "Topluluk ${hours} saat önce görüntülendi",
		COMMUNITY_VIEWED_MINUTES_AGO: "Topluluk ${minutes} dakika önce görüntülendi",
		COMMUNITY_VIEWED_SECONDS_AGO: "Topluluk ${seconds} saniye önce görüntülendi",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Topluluk 1 saat önce görüntülendi",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Topluluk 1 dakika önce görüntülendi",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Topluluk 1 saniye önce görüntülendi",
		COMMUNITY_VIEWED_AT_DATE: "Topluluk şu tarihte/saatte görüntülendi: ${date}",
		//File
		FILE_VIEWED_TODAY: "Dosya bugün görüntülendi",
		FILE_VIEWED_YESTERDAY: "Dosya dün görüntülendi",
		FILE_VIEWED_HOURS_AGO: "Dosya ${hours} saat önce görüntülendi",
		FILE_VIEWED_MINUTES_AGO: "Dosya ${minutes} dakika önce görüntülendi",
		FILE_VIEWED_SECONDS_AGO: "Dosya ${seconds} saniye önce görüntülendi",
		FILE_VIEWED_1_HOUR_AGO: "Dosya 1 saat önce görüntülendi",
		FILE_VIEWED_1_MINUTE_AGO: "Dosya 1 dakika önce görüntülendi",
		FILE_VIEWED_1_SECOND_AGO: "Dosya 1 saniye önce görüntülendi",
		FILE_VIEWED_AT_DATE: "Dosya şu tarihte/saatte görüntülendi: ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Profil bugün görüntülendi",
		PROFILE_VIEWED_YESTERDAY: "Profil dün görüntülendi",
		PROFILE_VIEWED_HOURS_AGO: "Profil ${hours} saat önce görüntülendi",
		PROFILE_VIEWED_MINUTES_AGO: "Profil ${minutes} dakika önce görüntülendi",
		PROFILE_VIEWED_SECONDS_AGO: "Profil ${seconds} saniye önce görüntülendi",
		PROFILE_VIEWED_1_HOUR_AGO: "Profil 1 saat önce görüntülendi",
		PROFILE_VIEWED_1_MINUTE_AGO: "Profil 1 dakika önce görüntülendi",
		PROFILE_VIEWED_1_SECOND_AGO: "Profil 1 saniye önce görüntülendi",
		PROFILE_VIEWED_AT_DATE: "Profil şu tarihte/saatte görüntülendi: ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Etkinlik bugün görüntülendi",
		ACTIVITY_VIEWED_YESTERDAY: "Etkinlik dün görüntülendi",
		ACTIVITY_VIEWED_HOURS_AGO: "Etkinlik ${hours} saat önce görüntülendi",
		ACTIVITY_VIEWED_MINUTES_AGO: "Etkinlik ${minutes} dakika önce görüntülendi",
		ACTIVITY_VIEWED_SECONDS_AGO: "Etkinlik ${seconds} saniye önce görüntülendi",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Etkinlik 1 saat önce görüntülendi",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Etkinlik 1 dakika önce görüntülendi",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Etkinlik 1 saniye önce görüntülendi",
		ACTIVITY_VIEWED_AT_DATE: "Etkinlik şu tarihte/saatte görüntülendi: ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Yer İşareti bugün görüntülendi",
		BOOKMARK_VIEWED_YESTERDAY: "Yer İşareti dün görüntülendi",
		BOOKMARK_VIEWED_HOURS_AGO: "Yer İşareti ${hours} saat önce görüntülendi",
		BOOKMARK_VIEWED_MINUTES_AGO: "Yer İşareti ${minutes} dakika önce görüntülendi",
		BOOKMARK_VIEWED_SECONDS_AGO: "Yer İşareti ${seconds} saniye önce görüntülendi",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Yer İşareti 1 saat önce görüntülendi",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Yer İşareti 1 saat önce görüntülendi",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Yer İşareti 1 saniye önce görüntülendi",
		BOOKMARK_VIEWED_AT_DATE: "Yer İşareti şu tarihte/saatte görüntülendi: ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Web Günlüğü bugün görüntülendi",
		BLOG_VIEWED_YESTERDAY: "Web Günlüğü dün görüntülendi",
		BLOG_VIEWED_HOURS_AGO: "Web Günlüğü ${hours} saat önce görüntülendi",
		BLOG_VIEWED_MINUTES_AGO: "Web Günlüğü ${minutes} dakika önce görüntülendi",
		BLOG_VIEWED_SECONDS_AGO: "Web Günlüğü ${seconds} saniye önce görüntülendi",
		BLOG_VIEWED_1_HOUR_AGO: "Web Günlüğü 1 saat önce görüntülendi",
		BLOG_VIEWED_1_MINUTE_AGO: "Web Günlüğü 1 dakika önce görüntülendi",
		BLOG_VIEWED_1_SECOND_AGO: "Web Günlüğü 1 saniye önce görüntülendi",
		BLOG_VIEWED_AT_DATE: "Web Günlüğü şu tarihte/saatte görüntülendi: ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Forum bugün görüntülendi",
		FORUM_VIEWED_YESTERDAY: "Forum dün görüntülendi",
		FORUM_VIEWED_HOURS_AGO: "Forum ${hours} saat önce görüntülendi",
		FORUM_VIEWED_MINUTES_AGO: "Forum ${minutes} dakika önce görüntülendi",
		FORUM_VIEWED_SECONDS_AGO: "Forum ${seconds} saniye önce görüntülendi",
		FORUM_VIEWED_1_HOUR_AGO: "Forum 1 saat önce görüntülendi",
		FORUM_VIEWED_1_MINUTE_AGO: "Forum 1 dakika önce görüntülendi",
		FORUM_VIEWED_1_SECOND_AGO: "Forum 1 saniye önce görüntülendi",
		FORUM_VIEWED_AT_DATE: "Forum şu tarihte/saatte görüntülendi: ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Viki bugün görüntülendi",
		WIKI_VIEWED_YESTERDAY: "Viki dün görüntülendi",
		WIKI_VIEWED_HOURS_AGO: "Viki ${hours} saat önce görüntülendi",
		WIKI_VIEWED_MINUTES_AGO: "Viki ${minutes} dakika önce görüntülendi",
		WIKI_VIEWED_SECONDS_AGO: "Viki ${seconds} saniye önce görüntülendi",
		WIKI_VIEWED_1_HOUR_AGO: "Viki 1 saat önce görüntülendi",
		WIKI_VIEWED_1_MINUTE_AGO: "Viki 1 dakika önce görüntülendi",
		WIKI_VIEWED_1_SECOND_AGO: "Viki 1 saniye önce görüntülendi",
		WIKI_VIEWED_AT_DATE: "Viki şu tarihte/saatte görüntülendi: ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Etkinlik bugün görüntülendi",
		EVENT_VIEWED_YESTERDAY: "Etkinlik dün görüntülendi",
		EVENT_VIEWED_HOURS_AGO: "Etkinlik ${hours} saat önce görüntülendi",
		EVENT_VIEWED_MINUTES_AGO: "Etkinlik ${minutes} dakika önce görüntülendi",
		EVENT_VIEWED_SECONDS_AGO: "Etkinlik ${seconds} saniye önce görüntülendi",
		EVENT_VIEWED_1_HOUR_AGO: "Etkinlik 1 saat önce görüntülendi",
		EVENT_VIEWED_1_MINUTE_AGO: "Etkinlik 1 dakika önce görüntülendi",
		EVENT_VIEWED_1_SECOND_AGO: "Etkinlik 1 saniye önce görüntülendi",
		EVENT_VIEWED_AT_DATE: "Etkinlik ${date} tarihinde görüntülendi",
		//To Do
		TODO_VIEWED_TODAY: "Yapılacak İş bugün görüntülendi",
		TODO_VIEWED_YESTERDAY: "Yapılacak İş dün görüntülendi",
		TODO_VIEWED_HOURS_AGO: "Yapılacak İş ${hours} saat önce görüntülendi",
		TODO_VIEWED_MINUTES_AGO: "Yapılacak İş ${minutes} dakika önce görüntülendi",
		TODO_VIEWED_SECONDS_AGO: "Yapılacak İş ${seconds} saniye önce görüntülendi",
		TODO_VIEWED_1_HOUR_AGO: "Yapılacak İş 1 saat önce görüntülendi",
		TODO_VIEWED_1_MINUTE_AGO: "Yapılacak İş 1 dakika önce görüntülendi",
		TODO_VIEWED_1_SECOND_AGO: "Yapılacak İş 1 saniye önce görüntülendi",
		TODO_VIEWED_AT_DATE: "Yapılacak İş şu tarihte/saatte görüntülendi: ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "Anket bugün görüntülendi",
		SURVEY_VIEWED_YESTERDAY: "Anket dün görüntülendi",
		SURVEY_VIEWED_HOURS_AGO: "Anket ${hours} saat önce görüntülendi",
		SURVEY_VIEWED_MINUTES_AGO: "Anket ${minutes} dakika önce görüntülendi",
		SURVEY_VIEWED_SECONDS_AGO: "Anket ${seconds} saniye önce görüntülendi",
		SURVEY_VIEWED_1_HOUR_AGO: "Anket 1 saat önce görüntülendi",
		SURVEY_VIEWED_1_MINUTE_AGO: "Anket 1 dakika önce görüntülendi",
		SURVEY_VIEWED_1_SECOND_AGO: "Anket 1 saniye önce görüntülendi",
		SURVEY_VIEWED_AT_DATE: "Anket ${date} tarihinde görüntülendi",
		//Survey
		GENERIC_VIEWED_TODAY: "Bugün görüntülendi",
		GENERIC_VIEWED_YESTERDAY: "Dün görüntülendi",
		GENERIC_VIEWED_HOURS_AGO: "${hours} saat önce görüntülendi",
		GENERIC_VIEWED_MINUTES_AGO: "${minutes} dakika önce görüntülendi",
		GENERIC_VIEWED_SECONDS_AGO: "${seconds} saniye önce görüntülendi",
		GENERIC_VIEWED_1_HOUR_AGO: "1 saat önce görüntülendi",
		GENERIC_VIEWED_1_MINUTE_AGO: "1 dakika önce görüntülendi",
		GENERIC_VIEWED_1_SECOND_AGO: "1 saniye önce görüntülendi",
		GENERIC_VIEWED_AT_DATE: "${date} tarihinde görüntülendi"
});

