/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"ترشيح بواسطة:",
"SHOW":"عرض:",
"ACL_FILTER_LABEL":"ترشيح بواسطة الرؤية",
"PARENT_FILTER_LABEL":"ترشيح بواسطة الحاوية",
"TYPE_FILTER_LABEL":"ترشيح بواسطة النوع",
"PAGING_TOP":"التصفح الأولي",
"PAGING_BOTTOM":"التصفح الثانوي",
"PREVIOUS":"‏سابق‏",
"NEXT":"‏تالي‏",
"PAGE":"صفحة {0} من {1}",
"PAGE_COLON":"الصفحة:",
"RESULTS":"{span}{0}-{1}{/span} من {2}",
"ITEMS":"{0} بنود",
/* Application names */
"ACTIVITIES":"المهام",
"BLOGS":"المدونات",
"CALENDAR":"التقويم",
"COMMUNITIES":"المجتمعات",
"BOOKMARKS":"علامات التوقف",
"DOGEAR":"علامات التوقف",
"EVENTS":"الأحداث",
"FILES":"ملفات",
"FORUMS":"منتدى المناقشات",
"PROFILES":"ملفات بيانات التعريف",
"WIKI":"صفحات Wikis",
"WIKIS":"صفحات Wikis",
"FEEDS":"المعلومات المسترجعة",
"STATUS_UPDATES":"تحديثات الحالة",
"ONECOMMENT":"تعقيب واحد",
"COMMENTS":"{0} تعقيبات",
"ONEPERSON":"شخص واحد",
"PEOPLE":"{0} أشخاص",
"TAGS":"شارات التعليم:",
"TAGSMORE":"و{0} أيضا",
"NORESULTSMESSAGE":"لم يتم ايجاد أية نتائج لعملية البحث هذه",
"JAN":"يناير",
"FEB":"فبراير",
"MAR":"مارس",
"APR":"أبريل",
"MAY":"‏مايو‏",
"JUN":"‏يونيو‏",
"JUL":"‏يوليو‏",
"AUG":"أغسطس",
"SEP":"سبتمبر",
"OCT":"أكتوبر",
"NOV":"نوفمبر",
"DEC":"ديسمبر",
"NO_CONTACT":"لم يتم تنفيذ البحث لأنه لم يمكن الاتصال بوحدة الخدمة.",
"SERVER_ERROR":"لم يتم تنفيذ البحث بسبب خطأ بوحدة الخدمة",
"SORT_BY":"الفرز بواسطة:",
"SORT_RELEVANCE":"الارتباط بالموضوع",
"SORT_DATE":"التاريخ",
"SORT_LAST_UPDATED":"آخر تعديل",
"SORT_DUE_DATE":"تاريخ الاستحقاق",
"SORT_VISITS":"الزيارات",
"SORT_COMMENTS":"التعقيبات",
"SORT_RECOMMENDATION":"يفضل",
"SORT_POPULARITY":"كثرة الاستخدام",
"SORT_FIRSTNAME":"الاسم",
"SORT_LASTNAME":"اسم العائلة",
"SORT_DOWNLOADS":"تنزيل",
"SORT_TYPE":"النوع",
"SORT_SIZE":"الحجم",
"SORT_TITLE":"العنوان",
"PRIVATE":"خاص",
"MODERATED":"منسق",
"COMMUNITY_ACTIVITY":"نشاط المجتمع",
"COMMUNITY_BLOG":"مدونة المجتمع",
"COMMUNITY_FILE":"ملف المجتمع",
"COMMUNITY_FORUM":"منتدى مناقشات المجتمع",
"COMMUNITY_WIKI":"صفحة Wiki الخاصة بالمجتمع",
"COMMUNITY_FEED":"وحدة معلومات مسترجعة للمجتمع",
"COMMUNITY_BOOKMARK":"علامة توقف المجتمع",
"NO_TAG":"لا توجد شارات تعليم",
"NO_DATE":"لا توجد تواريخ بعد",
"NO_PEOPLE":"لا يوجد أشخاص بعد",
"REMOVE_FILTER_LABEL":"اضغط للازالة",
"REMOVE_FILTER_TITLE":"‏ازالة‏",
"REMOVE_FILTER_TOOLTIP":"ازالة مرشح البيانات هذا",
"COMMENT_ON":"التعقيب على:",
"EXPAND_COLLAPSE":"اضغط للعرض / الطي",
"EXPAND":"توسيع",
"COLLAPSE":"طي",
"EXPAND_MONTHS_FILTER":"عرض مرشح بيانات الشهور للسنة {0}",
"SORT_RELEVANCE_LABEL":"اضغط للترتيب وفقا للارتباط بالموضوع",
"SORT_DATE_LABEL":"اضغط للترتيب وفقا للتاريخ",
"SORT_UPDATED_LABEL":"اضغط للفرز وفقا لتاريخ آخر تعديل",
"SORT_DUE_LABEL":"اضغط للفرز بواسطة تاريخ الاستحقاق",
"SORT_VISITS_LABEL":"اضغط للفرز وفقا لعدد الزيارات",
"SORT_COMMENTS_LABEL":"اضغط للفرز وفقا لعدد التعقيبات",
"SORT_RECOMMENDATIONS_LABEL":"اضغط للفرز وفقا لعدد الاعجاب",
"SORT_POPULARITY_LABEL":"اضغط للفرز وفقا لكثرة الاستخدام",
"SORT_FIRST_NAME_LABEL":"اضغط للفرز وفقا لاسم محدد",
"SORT_LAST_NAME_LABEL":"اضغط للفرز وفقا للقب",
"RATING":"يفضل",
"GRADUATED":"محدد التدرج",
"ONEVOTE":"1 تصويت",
"VOTES":"{0} تصويت",
"BOOKMARK_THIS_RESULT":"تحديد علامة توقف لهذا",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (غير فعال)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"تم تعليم {0} أشخاص بعلامة توقف",
/* eg from an Activity */
"FROMANACTIVITY":"من نشاط",
"FROMABLOG":"من مدونة",
"FROMANIDEATIONBLOG":"من مدونة الأفكار",
"FROMANEVENT":"من أحد الأحداث",
"FROMAFORUM":"من منتدى",
"FROMAWIKI":"من صفحة Wiki",
"FROMACOMMUNITY":"من مجتمع",
"FROMXCOMMUNITIES":"من {0} مجتمعات",
/* For search results parentage */
"ACTIVITY_ALONE":"المهمة",
"BLOG_ALONE":"المدونة",
"IDEATIONBLOG_ALONE":"مدونة الأفكار",
"ENTRY_ALONE":"الادخال",
"EVENT_ALONE":"الحدث",
"FORUM_ALONE":"منتدى مناقشات",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"المجتمع",
"XCOMMUNITIES_ALONE":"{0} مجتمعات",
"SHAREDCOMMUNITIES":"مشاركة في هذه المجتمعات",
"INACOMMUNITY":"في مجتمع",
"LASTUPDATED":"تاريخ آخر تحديث لفهرس البحث:",
"NODESCRIPTION":"لا يوجد وصف أو ملخص لهذه النتيجة.",
"ATTACHMENT":"الملحقات:",
"ACTIVITY":"النشاط:",
"ACTIVITYBOOKMARK":"علامة توقف النشاط:",
"ACTIVITYCOMMENT":"تعقيب النشاط:",
"ACTIVITYENTRY":"ادخال النشاط:",
"ACTIVITYSECTION":"قسم النشاط:",
"ACTIVITYTODO":"المهام الواجبة للنشاط:",
"BLOG":"المدونة:",
"BLOGENTRY":"ادخال المدونة:",
"BLOGCOMMENT":"تعقيب مدونة:",
"BOOKMARK":"علامة التوقف:",
"CALENDAREVENT":"الحدث:",
"CATEGORY":"التصنيف:",
"COMMENT":"التعقيب:",
"COMMUNITY":"المجتمع:",
"ENTRY":"الادخال:",
"EVENTDATEON":"في: {0}",
"EVENTISALLDAY":"أحداث كل الأيام",
"EVENTREPEATS":"التكرارات",
"FEED":"المعلومات المسترجعة:",
"FILE":"‏ملف‏:",
"FORUM":"منتدى المناقشة:",
"FORUMCATEGORY":"فئة منتدى المناقشات:",
"FORUMTOPIC":"موضوع منتدى المناقشات:",
"IDEA":"الفكرة:",
"IDEACOMMENT":"تعقيب مدونة:",
"IDEATIONBLOG":"مدونة الأفكار:",
"PAGE":"الصفحة:",
"PROFILE":"ملف بيانات التعريف:",
"SECTION":"القسم:",
"STATUSUPDATE":"تحديث الحالة",
"STATUSUPDATE_PREFIX":"تحديث الحالة:",
"TOPIC":"الموضوع:",
"TOPIC_WITH_ATTACHMENT":"الموضوع",
"WIKITYPE":"صفحة Wiki:",
"WIKIPAGE":"صفحة Wiki:",
"WIKIFILE":"ملحقات Wiki:",
"SEARCH":"بحث:",
"TODO":"بند مهام:",
"ALLRESULTS":"كل النتائج",
"PUBLICCONTENT":"المحتويات العامة",
"MYCONTENT":"المحتويات الخاصة بي",
"RESULTNOTFOUND":"لم يتم ايجاد ما كان يتم البحث عنه؟",
"TEMPDIFFICULTIES":"ملحوظة: نتيجة للصعوبات في الفهرسة المؤقتة، لا تتضمن عملية البحث الخاصة بك {0} الذي تم تغييره في أخر {1} يوم (أيام).",
"TRYLATER":"برجاء اعادة المحاولة فيما بعد.",
"MULTIPLETEMPDIFFICULTIES":"ملحوظة: بسبب صعوبات الفهرسة المؤقتة، لا تتضمن عملية البحث الخاصة بك {0} الذي تم تغييره مؤخرا.",
"YOUAREAUTHOR":"تعد مؤلف",
"YOUARECONTRIBUTOR":"تعد مشارك",
"YOUAREOWNER":"تعد مالك",
"YOUAREMEMBER":"تعد عضو",
/* Profiles */
"MYNETWORK":"شبكة الاتصال الخاصة بي",
"ALLPEOPLE":"كل الأشخاص",
"EXCLUDEINACTIVE":"استبعاد الأشخاص غير الفعالين",
"PHONE":"التليفون:",
"EMAIL":"البريد الالكتروني:",
/* Communities */
"ALLCOMMUNITIES":"كل المجتمعات",
"PUBLICCOMMUNITIES":"المجتمعات العامة",
"MYCOMMUNITIES":"المجتمعات الخاصة بي",
"EVERYTHINGCOMMUNITIES":"كل شيء من المجتمعات",
"COMMUNITIESONLY":"المجتمعات",
"COMMUNITIESCONTENT":"المحتويات من المجتمعات",
/* Activities */
"ALLACTIVITIES":"كل الأنشطة",
"PUBLICACTIVITIES":"الأنشطة العامة",
"MYACTIVITIES":"الأنشطة الخاصة بي",
"EVERYTHINGACTIVITIES":"كل شيء من الأنشطة",
"ACTIVITIESONLY":"المهام",
"SECTIONSACTIVITIES": "الأقسام من الأنشطة",
"ENTRIESACTIVITIES":"الادخالات من الأنشطة",
"TODOSACTIVITIES":"المهام الواجبة من الأنشطة",
"BOOKMARKSACTIVITIES":"علامات التوقف من الأنشطة",
"FILESACTIVITIES":"الملحقات من الأنشطة",
"ALLTYPESACTIVITIES":"كل أنواع الأنشطة",
"COMMUNITYACTIVITIES":"الأنشطة من المجتمعات",
"STANDALONEACTIVITIES":"الأنشطة المستقلة",
/* Forums */
"ALLFORUMS":"كل منتديات المناقشة",
"PUBLICFORUMS":"منتديات المناقشة العامة",
"MYFORUMS":"منتديات المناقشة الخاصة بي",
"EVERYTHINGFORUMS":"كل شيء من منتديات المناقشة",
"FORUMSONLY":"منتدى المناقشات",
"TOPICSFORUMS":"موضوعات منتدى المناقشات",
"FORUMCATEGORIES": "فئات منتدى المناقشات",
"FILESFORUMS":"الملحقات من منتديات المناقشة",
"ALLTYPESFORUMS":"كل أنواع منتديات المناقشة",
"COMMUNITYFORUMS":"منتديات المناقشة من المجتمعات",
"STANDALONEFORUMS":"منتديات المناقشة المستقلة",
/* Blogs */
"ALLBLOGS":"كل المدونات",
"PUBLICBLOGS":"المدونات العامة",
"MYBLOGS":"المدونات الخاصة بي",
"EVERYTHINGBLOGS":"كل شيء من المدو نات",
"BLOGSONLY":"المدونات",
"ENTRIESBLOGS":"ادخالات المدونة",
"FILESBLOGS":"الملحقات من المدونات",
"EVERYTHINGIDEATIONBLOGS":"كل شيء من مدونات الأفكار",
"BLOGSIDEATIONBLOGS":"مدونات الأفكار",
"BLOGSIDEAS":"الأفكار",
"ALLTYPESBLOGS":"كل أنواع المدونات",
"COMMUNITYBLOGS":"المدونات من المجتمعات",
"COMMUNITYIDEATIONBLOGS":"مدونات الأفكار من المجتمعات",
"STANDALONEBLOGS":"المدونات المستقلة",
/* Bookmarks */
"ALLBOOKMARKS":"كل علامات التوقف",
"PUBLICBOOKMARKS":"علامات التوقف العامة",
"MYBOOKMARKS":"علامات التوقف الخاصة بي",
"ALLTYPESBOOKMARKS":"كل أنواع علامات التوقف",
"COMMUNITYBOOKMARKS":"علامات التوقف من المجتمعات",
"STANDALONEBOOKMARKS":"علامات التوقف المستقلة",
/* Files */
"ALLFILES":"كل الملفات",
"PUBLICFILES":"الملفات العامة",
"MYFILES":"الملفات الخاصة بي",
"ALLTYPESFILES":"كل أنواع الملفات",
"COMMUNITYFILES":"الملفات من المجتمعات",
"STANDALONEFILES":"الملفات المستقلة",
"NUMDOWNLOADS":"{0} عمليات تنزيل",
/* Wikis */
"ALLWIKIS":"كل صفحات Wiki",
"PUBLICWIKIS":"صفحات Wikis العامة",
"MYWIKIS":"صفحات Wiki الخاصة بي",
"EVERYTHINGWIKIS":"كل شيء من صفحات Wikis",
"WIKISONLY":"صفحات Wikis",
"PAGESWIKIS":"صفحات Wiki",
"FILESWIKIS":"الملحقات من صفحات Wikis",
"ALLTYPESWIKIS":"كل أنواع صفحات Wikis",
"COMMUNITYWIKIS":"صفحات Wikis من المجتمعات",
"STANDALONEWIKIS":"صفحات Wikis المستقلة",
/* Status Updates */
"ALLSTATUSUPDATES":"كل تحديثات الحالة",
"PUBLICSTATUSUPDATES":"تحديثات الحالة العامة",
"MYSTATUSUPDATES":"تحديثات الحالة الخاصة بي",
"ALLTYPESSTATUSUPDATES":"كل أنواع تحديثات الحالة",
"COMMUNITYSTATUSUPDATES":"تحديثات الحالة من المجتمعات",
"STANDALONESTATUSUPDATES":"تحديثات الحالة من ملفات بيانات التعريف",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"تم تعليم عنوان URL هذا بعلامة توقف بواسطة عدد من المستخدمين",
"BOOKMARKEDCOMMUNITY":"تم تعليم هذا المجتمع بعلامة توقف بواسطة عدد من المستخدمين",
"BOOKMARKEDPROFILE":"تم تعليم ملف بيانات التعريف هذا بعلامة توقف بواسطة عدد من المستخدمين",
"BOOKMARKEDBLOG":"تم تعليم هذه المدونة بعلامة توقف بواسطة عدد من المستخدمين",
"COMMUNITYBLOG":"توجد هذه المدونة في مجتمع",
"BOOKMARKEDACTIVITY":"تم تعليم هذا النشاط بعلامة توقف بواسطة عدد من المستخدمين",
"COMMUNITYACTIVITY":"يعد هذا نشاط في المجتمع",
"BOOKMARKEDFILE":"تم تعليم هذا الملف بعلامة توقف بواسطة عدد من المستخدمين",
"COMMUNITYFILE":"يعد هذا ملف في المجتمع",
"BOOKMARKED":"تم تعليم صفحة wiki هذه بعلامة توقف بواسطة عدد من المستخدمين",
"COMMUNITYWIKI":"تعد هذه صفحة wiki في مجتمع",
"BOOKMARKEDFORUM":"تم تعليم منتدى المناقشات هذا بواسطة عدد من المستخدمين",
"COMMUNITYFORUM":"يعد هذا منتدى مناقشات في المجتمع",
"ALLTAGANDTTILE":"لمشاهدة كل العناوين وشارات التعليم لعنوان URL هذا، اضغط على هذا الاختيار",
"TAGS_ARE_FROM":"قد تتضمن نتيجة البحث هذه شارات تعليم من:",
"BOOKMARKS_TITLE":"علامات التوقف",
"COMMUNITIES_TITLE":"المجتمعات",
"ACTIVITIES_TITLE":"المهام",
"HELP":"‏مساعدة‏",
"MORESTATUSUPDATES":"مشاهدة المزيد من مطابقات تحديثات الحالة",
"TITLE_PREFIX":"العنوان:",
"LATEST_MESSAGE":"أحدث رسالة",
"LATEST_STATUS_UPDATE":"آخر تحديث للحالة",
"LATEST_COMMUNITY_STATUS_UPDATE":"آخر تحديث لحالة المجتمع",
"LATEST_COMMUNITIES_STATUS_UPDATE":"آخر تحديث لحالات المجتمعات",
"SEARCH_RESULTS":"كل نتائج بحث المحتويات",
"ACTIVITIES_SEARCH_RESULTS":"نتائج البحث للأنشطة",
"BLOGS_SEARCH_RESULTS":"نتائج البحث للمدونات",
"BOOKMARKS_SEARCH_RESULTS":"نتائج البحث لعلامات التوقف",
"COMMUNITIES_SEARCH_RESULTS":"نتائج البحث للمجتمعات",
"FILES_SEARCH_RESULTS":"نتائج البحث للملفات",
"FORUMS_SEARCH_RESULTS":"نتائج البحث لمنتديات المناقشات",
"PROFILES_SEARCH_RESULTS":"نتائج البحث لملفات بيانات التعريف",
"DIRECTORY_SEARCH_RESULTS":"نتائج بحث الدليل ${orgName}",
"WIKIS_SEARCH_RESULTS":"نتائج بحث Wikis",
"STATUS_UPDATES_SEARCH_RESULTS":"نتائج البحث لتحديثات الحالة",
"VIEW_ALL":"{span}مشاهدة كل{/span} ({0})",
"MATCHING_ONE_OF":"مطابقة واحد من:",
"MATCHING_ALL_OF":"مطابقة كل:",
"MATCHING":"المطابقة:",
"MATCHING_DOC_TYPE":"مطابقة نوع الوثيقة:",
"BOOKMARK_HELP":"مساعدة عن علامة التوقف",
"CLOSE_BOOKMARK_HELP":"اغلاق المساعدة عن علامة التوقف",
"DOCUMENT_TYPE_PREFIX":"نوع الوثيقة:",
"FILE_PREVIEW_ONLY":"(نمط المعاينة فقط)"
})

