/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Φιλτράρισμα κατά:",
"SHOW":"Εμφάνιση:",
"ACL_FILTER_LABEL":"Φιλτράρισμα κατά ορατότητα",
"PARENT_FILTER_LABEL":"Φιλτράρισμα κατά θέση υποδοχής",
"TYPE_FILTER_LABEL":"Φιλτράρισμα κατά είδος",
"PAGING_TOP":"Κύρια σελιδοποίηση",
"PAGING_BOTTOM":"Δευτερεύουσα σελιδοποίηση",
"PREVIOUS":"Προηγούμενη",
"NEXT":"Επόμενη",
"PAGE":"Σελίδα {0} από {1}",
"PAGE_COLON":"Σελίδα:",
"RESULTS":"{span}{0}-{1}{/span} από {2}",
"ITEMS":"{0}στοιχεία",
/* Application names */
"ACTIVITIES":"Δραστηριότητες",
"BLOGS":"Ιστολόγια",
"CALENDAR":"Ημερολόγιο",
"COMMUNITIES":"Κοινότητες",
"BOOKMARKS":"Σελιδοδείκτες",
"DOGEAR":"Σελιδοδείκτες",
"EVENTS":"Συμβάντα",
"FILES":"Αρχεία",
"FORUMS":"Φόρουμ",
"PROFILES":"Προφίλ",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Υπηρεσίες διανομής",
"STATUS_UPDATES":"Ενημερώσεις κατάστασης",
"ONECOMMENT":"1 σχόλιο",
"COMMENTS":"{0} σχόλια",
"ONEPERSON":"1 πρόσωπο",
"PEOPLE":"{0} πρόσωπα",
"TAGS":"Προσδιοριστικά:",
"TAGSMORE":"και {0} άλλοι",
"NORESULTSMESSAGE":"Δεν εντοπίστηκαν αποτελέσματα για αυτή την αναζήτηση.",
"JAN":"Ιανουάριος",
"FEB":"Φεβρουάριος",
"MAR":"Μάρτιος",
"APR":"Απρίλιος",
"MAY":"Μάιος",
"JUN":"Ιούνιος",
"JUL":"Ιούλιος",
"AUG":"Αύγουστος",
"SEP":"Σεπτέμβριος",
"OCT":"Οκτώβριος",
"NOV":"Νοέμβριος",
"DEC":"Δεκέμβριος",
"NO_CONTACT":"Η αναζήτηση δεν εκτελέστηκε επειδή δεν ήταν δυνατή η επικοινωνία με τον εξυπηρετητή",
"SERVER_ERROR":"Η αναζήτηση δεν εκτελέστηκε εξαιτίας κάποιου σφάλματος στον εξυπηρετητή",
"SORT_BY":"Ταξινόμηση κατά:",
"SORT_RELEVANCE":"Βαθμός σχετικότητας",
"SORT_DATE":"Ημερομηνία",
"SORT_LAST_UPDATED":"Τελευταία ενημέρωση",
"SORT_DUE_DATE":"Λήξη προθεσμίας",
"SORT_VISITS":"Επισκέψεις",
"SORT_COMMENTS":"Σχόλια",
"SORT_RECOMMENDATION":"Θετικές γνώμες",
"SORT_POPULARITY":"Δημοτικότητα",
"SORT_FIRSTNAME":"Όνομα",
"SORT_LASTNAME":"Επώνυμο",
"SORT_DOWNLOADS":"Μεταφορτώσεις",
"SORT_TYPE":"Είδος",
"SORT_SIZE":"Μέγεθος",
"SORT_TITLE":"Τίτλος",
"PRIVATE":"Ιδιωτικό",
"MODERATED":"Επιτηρούμενη",
"COMMUNITY_ACTIVITY":"Δραστηριότητα κοινότητας",
"COMMUNITY_BLOG":"Ιστολόγιο κοινότητας",
"COMMUNITY_FILE":"Αρχείο κοινότητας",
"COMMUNITY_FORUM":"Φόρουμ κοινότητας",
"COMMUNITY_WIKI":"Wiki κοινότητας",
"COMMUNITY_FEED":"Υπηρεσία διανομής κοινότητας",
"COMMUNITY_BOOKMARK":"Σελιδοδείκτης κοινότητας",
"NO_TAG":"Κανένα προσδιοριστικό",
"NO_DATE":"Δεν υπάρχουν ακόμα ημερομηνίες",
"NO_PEOPLE":"Δεν υπάρχουν πρόσωπα ακόμα",
"REMOVE_FILTER_LABEL":"Πατήστε για αφαίρεση",
"REMOVE_FILTER_TITLE":"Αφαίρεση",
"REMOVE_FILTER_TOOLTIP":"Αφαίρεση αυτού του φίλτρου",
"COMMENT_ON":"Σχόλιο για:",
"EXPAND_COLLAPSE":"Πατήστε για ανάπτυξη/σύμπτυξη",
"EXPAND":"Ανάπτυξη",
"COLLAPSE":"Σύμπτυξη",
"EXPAND_MONTHS_FILTER":"Ανάπτυξη του φίλτρου μηνών για το έτος {0}",
"SORT_RELEVANCE_LABEL":"Πατήστε για ταξινόμηση κατά βαθμό σχετικότητας",
"SORT_DATE_LABEL":"Πατήστε για ταξινόμηση κατά ημερομηνία",
"SORT_UPDATED_LABEL":"Πατήστε για ταξινόμηση κατά ημερομηνία τελευταίας ενημέρωσης",
"SORT_DUE_LABEL":"Πατήστε για ταξινόμηση κατά ημερομηνία λήξης προθεσμίας",
"SORT_VISITS_LABEL":"Πατήστε για ταξινόμηση κατά αριθμό επισκέψεων",
"SORT_COMMENTS_LABEL":"Πατήστε για ταξινόμηση κατά αριθμό σχολίων",
"SORT_RECOMMENDATIONS_LABEL":"Πατήστε για ταξινόμηση κατά αριθμό θετικών γνωμών",
"SORT_POPULARITY_LABEL":"Πατήστε για ταξινόμηση κατά δημοτικότητα",
"SORT_FIRST_NAME_LABEL":"Πατήστε για ταξινόμηση με βάση το όνομα",
"SORT_LAST_NAME_LABEL":"Πατήστε για ταξινόμηση με βάση το επώνυμο",
"RATING":"Θετικές γνώμες",
"GRADUATED":"Προβιβάστηκε",
"ONEVOTE":"1 ψήφος",
"VOTES":"{0} ψήφοι",
"BOOKMARK_THIS_RESULT":"Ορισμός σελιδοδείκτη",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (ανενεργός)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"Ορίστηκαν σελιδοδείκτες για {0} πρόσωπα",
/* eg from an Activity */
"FROMANACTIVITY":"από δραστηριότητα",
"FROMABLOG":"από ιστολόγιο",
"FROMANIDEATIONBLOG":"από ιστολόγιο ιδεών",
"FROMANEVENT":"από συμβάν",
"FROMAFORUM":"από φόρουμ",
"FROMAWIKI":"από wiki",
"FROMACOMMUNITY":"από κοινότητα",
"FROMXCOMMUNITIES":"από {0} κοινότητες",
/* For search results parentage */
"ACTIVITY_ALONE":"Δραστηριότητα",
"BLOG_ALONE":"Ιστολόγιο",
"IDEATIONBLOG_ALONE":"Ιστολόγιο ιδεών",
"ENTRY_ALONE":"Καταχώρηση",
"EVENT_ALONE":"Συμβάν",
"FORUM_ALONE":"Φόρουμ",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Κοινότητα",
"XCOMMUNITIES_ALONE":"{0} κοινότητες",
"SHAREDCOMMUNITIES":"Διατέθηκαν για κοινή χρήση σε αυτές τις κοινότητες",
"INACOMMUNITY":"σε κοινότητα",
"LASTUPDATED":"Τελευταία ενημέρωση ευρετηρίου αναζήτησης:",
"NODESCRIPTION":"Δεν υπάρχει περιγραφή ή περίληψη για αυτό το αποτέλεσμα.",
"ATTACHMENT":"Συνημμένο:",
"ACTIVITY":"Δραστηριότητα:",
"ACTIVITYBOOKMARK":"Σελιδοδείκτης δραστηριότητας:",
"ACTIVITYCOMMENT":"Σχόλιο δραστηριότητας:",
"ACTIVITYENTRY":"Καταχώρηση δραστηριότητας:",
"ACTIVITYSECTION":"Ενότητα δραστηριότητας:",
"ACTIVITYTODO":"Εκκρεμής εργασία δραστηριότητας:",
"BLOG":"Ιστολόγιο:",
"BLOGENTRY":"Καταχώρηση ιστολογίου:",
"BLOGCOMMENT":"Σχόλιο ιστολογίου:",
"BOOKMARK":"Σελιδοδείκτης:",
"CALENDAREVENT":"Συμβάν:",
"CATEGORY":"Κατηγορία:",
"COMMENT":"Σχόλιο:",
"COMMUNITY":"Κοινότητα:",
"ENTRY":"Καταχώρηση:",
"EVENTDATEON":"Ημέρα: {0}",
"EVENTISALLDAY":"Ολοήμερο συμβάν",
"EVENTREPEATS":"Επαναλήψεις",
"FEED":"Υπηρεσία διανομής:",
"FILE":"Αρχείο:",
"FORUM":"Φόρουμ:",
"FORUMCATEGORY":"Κατηγορία φόρουμ:",
"FORUMTOPIC":"Θέμα φόρουμ:",
"IDEA":"Ιδέα:",
"IDEACOMMENT":"Σχόλιο ιδέας:",
"IDEATIONBLOG":"Ιστολόγιο ιδεών:",
"PAGE":"Σελίδα:",
"PROFILE":"Προφίλ:",
"SECTION":"Ενότητα:",
"STATUSUPDATE":"Ενημέρωση κατάστασης",
"STATUSUPDATE_PREFIX":"Ενημέρωση κατάστασης:",
"TOPIC":"Θέμα:",
"TOPIC_WITH_ATTACHMENT":"Θέμα",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Σελίδα wiki:",
"WIKIFILE":"Συνημμένο wiki:",
"SEARCH":"Αναζήτηση:",
"TODO":"Εκκρεμής εργασία:",
"ALLRESULTS":"Όλα τα αποτελέσματα",
"PUBLICCONTENT":"Δημόσιο περιεχόμενο",
"MYCONTENT":"Το περιεχόμενό μου",
"RESULTNOTFOUND":"Δεν εντοπίσατε τις επιθυμητές πληροφορίες;",
"TEMPDIFFICULTIES":"Σημείωση: Εξαιτίας προσωρινών δυσκολιών στην ευρετηριοποίηση, στην αναζήτησή σας δεν συμπεριλήφθηκαν τα ακόλουθα στοιχεία που άλλαξαν τις τελευταίες {1} ημέρες: {0}.",
"TRYLATER":"Προσπαθήστε ξανά αργότερα.",
"MULTIPLETEMPDIFFICULTIES":"Σημείωση: Εξαιτίας προσωρινών δυσκολιών στην ευρετηριοποίηση, στην αναζήτησή σας δεν συμπεριλήφθηκαν τα ακόλουθα στοιχεία που άλλαξαν πρόσφατα: {0}.",
"YOUAREAUTHOR":"Είστε συντάκτης",
"YOUARECONTRIBUTOR":"Είστε συνεισφέρων",
"YOUAREOWNER":"Είστε κάτοχος",
"YOUAREMEMBER":"Είστε μέλος",
/* Profiles */
"MYNETWORK":"Το δίκτυό μου",
"ALLPEOPLE":"Όλα τα πρόσωπα",
"EXCLUDEINACTIVE":"Εξαίρεση ανενεργών προσώπων",
"PHONE":"Τηλέφωνο:",
"EMAIL":"Διεύθυνση e-mail:",
/* Communities */
"ALLCOMMUNITIES":"Όλες οι κοινότητες",
"PUBLICCOMMUNITIES":"Δημόσιες κοινότητες",
"MYCOMMUNITIES":"Οι κοινότητές μου",
"EVERYTHINGCOMMUNITIES":"Όλα τα στοιχεία στις Κοινότητες",
"COMMUNITIESONLY":"Κοινότητες",
"COMMUNITIESCONTENT":"Περιεχόμενο από τις Κοινότητες",
/* Activities */
"ALLACTIVITIES":"Όλες οι δραστηριότητες",
"PUBLICACTIVITIES":"Δημόσιες δραστηριότητες",
"MYACTIVITIES":"Οι δραστηριότητές μου",
"EVERYTHINGACTIVITIES":"Όλα τα στοιχεία στις Δραστηριότητες",
"ACTIVITIESONLY":"Δραστηριότητες",
"SECTIONSACTIVITIES": "Ενότητες από τις Δραστηριότητες",
"ENTRIESACTIVITIES":"Καταχωρήσεις από τις Δραστηριότητες",
"TODOSACTIVITIES":"Εκκρεμείς εργασίες από τις Δραστηριότητες",
"BOOKMARKSACTIVITIES":"Σελιδοδείκτες από τις Δραστηριότητες",
"FILESACTIVITIES":"Συνημμένα από τις Δραστηριότητες",
"ALLTYPESACTIVITIES":"Όλα τα είδη δραστηριοτήτων",
"COMMUNITYACTIVITIES":"Δραστηριότητες από τις Κοινότητες",
"STANDALONEACTIVITIES":"Ανεξάρτητες δραστηριότητες",
/* Forums */
"ALLFORUMS":"Όλα τα φόρουμ",
"PUBLICFORUMS":"Δημόσια φόρουμ",
"MYFORUMS":"Τα φόρουμ μου",
"EVERYTHINGFORUMS":"Όλα τα στοιχεία στα Φόρουμ",
"FORUMSONLY":"Φόρουμ",
"TOPICSFORUMS":"Θέματα του φόρουμ",
"FORUMCATEGORIES": "Κατηγορίες φόρουμ",
"FILESFORUMS":"Συνημμένα από τα Φόρουμ",
"ALLTYPESFORUMS":"Όλα τα είδη φόρουμ",
"COMMUNITYFORUMS":"Φόρουμ από τις Κοινότητες",
"STANDALONEFORUMS":"Ανεξάρτητα φόρουμ",
/* Blogs */
"ALLBLOGS":"Όλα τα ιστολόγια",
"PUBLICBLOGS":"Δημόσια ιστολόγια",
"MYBLOGS":"Τα ιστολόγιά μου",
"EVERYTHINGBLOGS":"Όλα τα στοιχεία στα Ιστολόγια",
"BLOGSONLY":"Ιστολόγια",
"ENTRIESBLOGS":"Καταχωρήσεις ιστολογίου",
"FILESBLOGS":"Συνημμένα από τα Ιστολόγια",
"EVERYTHINGIDEATIONBLOGS":"Όλα τα στοιχεία στα Ιστολόγια ιδεών",
"BLOGSIDEATIONBLOGS":"Ιστολόγια ιδεών",
"BLOGSIDEAS":"Ιδέες",
"ALLTYPESBLOGS":"Όλα τα είδη ιστολογίων",
"COMMUNITYBLOGS":"Ιστολόγια από τις Κοινότητες",
"COMMUNITYIDEATIONBLOGS":"Ιστολόγια ιδεών από τις Κοινότητες",
"STANDALONEBLOGS":"Ανεξάρτητα ιστολόγια",
/* Bookmarks */
"ALLBOOKMARKS":"Όλοι οι σελιδοδείκτες",
"PUBLICBOOKMARKS":"Δημόσιοι σελιδοδείκτες",
"MYBOOKMARKS":"Οι σελιδοδείκτες μου",
"ALLTYPESBOOKMARKS":"Όλα τα είδη σελιδοδεικτών",
"COMMUNITYBOOKMARKS":"Σελιδοδείκτες από τις Κοινότητες",
"STANDALONEBOOKMARKS":"Ανεξάρτητοι σελιδοδείκτες",
/* Files */
"ALLFILES":"Όλα τα αρχεία",
"PUBLICFILES":"Δημόσια αρχεία",
"MYFILES":"Τα αρχεία μου",
"ALLTYPESFILES":"Όλα τα είδη αρχείων",
"COMMUNITYFILES":"Αρχεία από τις Κοινότητες",
"STANDALONEFILES":"Ανεξάρτητα αρχεία",
"NUMDOWNLOADS":"{0} μεταφορτώσεις",
/* Wikis */
"ALLWIKIS":"Όλα τα wikis",
"PUBLICWIKIS":"Δημόσια wikis",
"MYWIKIS":"Τα wikis μου",
"EVERYTHINGWIKIS":"Όλα τα στοιχεία στα Wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Σελίδες wiki",
"FILESWIKIS":"Συνημμένα από τα Wikis",
"ALLTYPESWIKIS":"Όλα τα είδη wikis",
"COMMUNITYWIKIS":"Wikis από τις Κοινότητες",
"STANDALONEWIKIS":"Ανεξάρτητα wikis",
/* Status Updates */
"ALLSTATUSUPDATES":"Όλες οι ενημερώσεις κατάστασης",
"PUBLICSTATUSUPDATES":"Δημόσιες ενημερώσεις κατάστασης",
"MYSTATUSUPDATES":"Ενημερώσεις κατάστασης για το προφίλ μου",
"ALLTYPESSTATUSUPDATES":"Όλα τα είδη ενημερώσεων κατάστασης",
"COMMUNITYSTATUSUPDATES":"Ενημερώσεις κατάστασης από την εφαρμογή Κοινότητες",
"STANDALONESTATUSUPDATES":"Ενημερώσεις κατάστασης από την εφαρμογή Προφίλ",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Για αυτή τη διεύθυνση URL έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"BOOKMARKEDCOMMUNITY":"Για αυτή την κοινότητα έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"BOOKMARKEDPROFILE":"Για αυτό το προφίλ έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"BOOKMARKEDBLOG":"Για αυτό το ιστολόγιο έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"COMMUNITYBLOG":"Αυτό το ιστολόγιο ανήκει σε μια κοινότητα",
"BOOKMARKEDACTIVITY":"Για αυτή τη δραστηριότητα έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"COMMUNITYACTIVITY":"Αυτή η δραστηριότητα ανήκει σε μια κοινότητα",
"BOOKMARKEDFILE":"Για αυτό το αρχείο έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"COMMUNITYFILE":"Αυτό το αρχείο ανήκει σε μια κοινότητα",
"BOOKMARKED":"Για αυτό το wiki έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"COMMUNITYWIKI":"Αυτό το wiki ανήκει σε μια κοινότητα",
"BOOKMARKEDFORUM":"Για αυτό το φόρουμ έχουν δημιουργηθεί σελιδοδείκτες από πολλούς χρήστες",
"COMMUNITYFORUM":"Αυτό το φόρουμ ανήκει σε μια κοινότητα",
"ALLTAGANDTTILE":"Για να δείτε όλους τους τίτλους και τα προσδιοριστικά για αυτή τη διεύθυνση URL πατήστε αυτό το κουμπί",
"TAGS_ARE_FROM":"Το αποτέλεσμα της αναζήτησης μπορεί να περιέχει προσδιοριστικά από:",
"BOOKMARKS_TITLE":"Σελιδοδείκτες",
"COMMUNITIES_TITLE":"Κοινότητες",
"ACTIVITIES_TITLE":"Δραστηριότητες",
"HELP":"Βοήθεια",
"MORESTATUSUPDATES":"Προβολή περισσότερων αποτελεσμάτων για ενημερώσεις κατάστασης",
"TITLE_PREFIX":"τίτλος:",
"LATEST_MESSAGE":"Τελευταίο μήνυμα",
"LATEST_STATUS_UPDATE":"Τελευταία ενημέρωση κατάστασης",
"LATEST_COMMUNITY_STATUS_UPDATE":"Τελευταία ενημέρωση κατάστασης για κοινότητα",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Τελευταία ενημέρωση κατάστασης για κοινότητες",
"SEARCH_RESULTS":"Όλο το περιεχόμενο - Αποτελέσματα αναζήτησης",
"ACTIVITIES_SEARCH_RESULTS":"Δραστηριότητες - Αποτελέσματα αναζήτησης",
"BLOGS_SEARCH_RESULTS":"Ιστολόγια - Αποτελέσματα αναζήτησης",
"BOOKMARKS_SEARCH_RESULTS":"Σελιδοδείκτες - Αποτελέσματα αναζήτησης",
"COMMUNITIES_SEARCH_RESULTS":"Κοινότητες - Αποτελέσματα αναζήτησης",
"FILES_SEARCH_RESULTS":"Αρχεία - Αποτελέσματα αναζήτησης",
"FORUMS_SEARCH_RESULTS":"Φόρουμ - Αποτελέσματα αναζήτησης",
"PROFILES_SEARCH_RESULTS":"Προφίλ - Αποτελέσματα αναζήτησης",
"DIRECTORY_SEARCH_RESULTS":"Αποτελέσματα αναζήτησης στον κατάλογο ${orgName}",
"WIKIS_SEARCH_RESULTS":"Wikis - Αποτελέσματα αναζήτησης",
"STATUS_UPDATES_SEARCH_RESULTS":"Ενημερώσεις κατάστασης - Αποτελέσματα αναζήτησης",
"VIEW_ALL":"{span}Προβολή όλων{/span} ({0})",
"MATCHING_ONE_OF":"Συμφωνεί με ένα από:",
"MATCHING_ALL_OF":"Συμφωνεί με όλα:",
"MATCHING":"Συμφωνεί με:",
"MATCHING_DOC_TYPE":"Συμφωνεί με είδος εγγράφου:",
"BOOKMARK_HELP":"Βοήθεια για τους σελιδοδείκτες",
"CLOSE_BOOKMARK_HELP":"Κλείσιμο βοήθειας για τους σελιδοδείκτες",
"DOCUMENT_TYPE_PREFIX":"Είδος εγγράφου:",
"FILE_PREVIEW_ONLY":"(Μόνο κατάσταση προεπισκόπησης)"
})

