/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "タイトルは必須です。",
	nourl: "URL は必須です。",
	fileSchema: "リモートまたはローカルのファイル・リンクを追加する場合は、以下のいずれかの形式にしてください: file://remote_path または file:///local_path",
	invalidUrl: "これは有効なコミュニティー URL ではありません。",
	invalidTagChar: "入力したタグ・リストに、無効な文字「&」が含まれています。タグ・リストからこの文字を削除してください。",
	txtHelp: "ヘルプ",
	txtHelpTags: "タグのヘルプ",
	txtHelpTagsClose: "タグのヘルプを閉じる",
	tagsall: "すべて",
	tagsyours: "ユーザー用",
	tagsrecent: "最新: ",
	tagspopular: "人気: ",
	tagsrecommended: "推奨: ",
	nothingselected: "コミュニティーの選択は必須です。",
	nothingselected_activity: "アクティビティーの選択は必須です。",
	nothingselected_blogs: "ブログの選択は必須です。",
	nothingselected_all: "サービスまたはエントリーが選択されていません。ブックマークは保存されません。",
	nothingFeedselected: "サービスまたはエントリーが選択されていません。フィードは保存されません。",
	alertDialogTitle: "メッセージ",
	alertDialogOK: "OK",
	expand: "クリックしてこのセクションを展開",
	collapse: "クリックしてこのセクションを省略表示",
	discussThis: "ディスカッション:",
	by: "投稿者:",
	posted: "投稿日時:",
	attachments: "添付ファイル",
	communityForum: "コミュニティー・フォーラム",
	notCommunityPage: "現在の Web ページは、有効なコミュニティー Web ページではありません。 手動でコミュニティーのタイトル、リンク、説明を入力して、関連コミュニティーを作成できます。",
	privateCommunityNotice: "これは制限付きコミュニティーです。コミュニティーのメンバーのみが表示できます。",
	forumNameHint : "フォーラム名の入力",
	formDescriptionHint:"この関連コミュニティーが自分のコミュニティーにとって価値があると考える理由を説明します。",
	information : "情報",
	error : "エラー",
	success : "成功",
	warning : "警告",
	informationColon : "情報:",
	successColon : "成功:",
	warningColon : "警告:",
	errorColon : "エラー:",
	feedAlreadyExist : "フィードは既にコミュニティーに存在しています。",
	bookmarkAlreadyExist : "ブックマークは既にコミュニティーに存在しています。",
	mentionAuthWarning:"言及されている以下のユーザーは、コミュニティーのメンバーではないため、このメッセージを表示できません。",
	mentionAuthForumWarning:"言及されている以下のユーザーは、このフォーラムにアクセスできないため、このメッセージを表示できません:",
	exceedDescLength: "入力した説明が長すぎます。",
	communities_checked:"${0} コミュニティーが選択されました",
	activities_checked:"${0} アクティビティーが選択されました",
	blogs_checked:"${0} ブログが選択されました"
})
