/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Uppdaterades av ${author}",
		PREVIEW_MODE_ONLY: "(Endast förhandsgranskningsläge)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Gemenskapen visades i dag",
		COMMUNITY_VIEWED_YESTERDAY: "Gemenskapen visades i går",
		COMMUNITY_VIEWED_HOURS_AGO: "Gemenskapen visades för ${hours} timmar sedan",
		COMMUNITY_VIEWED_MINUTES_AGO: "Gemenskapen visades för ${minutes} minuter sedan",
		COMMUNITY_VIEWED_SECONDS_AGO: "Gemenskapen visades för ${seconds} sekunder sedan",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Gemenskapen visades för 1 timme sedan",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Gemenskapen visades för 1 minut sedan",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Gemenskapen visades för 1 sekund sedan",
		COMMUNITY_VIEWED_AT_DATE: "Gemenskapen visades ${date}",
		//File
		FILE_VIEWED_TODAY: "Filen visades i dag",
		FILE_VIEWED_YESTERDAY: "Filen visades i går",
		FILE_VIEWED_HOURS_AGO: "Filen visades för ${hours} timmar sedan",
		FILE_VIEWED_MINUTES_AGO: "Filen visades för ${minutes} minuter sedan",
		FILE_VIEWED_SECONDS_AGO: "Filen visades för ${seconds} sekunder sedan",
		FILE_VIEWED_1_HOUR_AGO: "Filen visades för 1 timme sedan",
		FILE_VIEWED_1_MINUTE_AGO: "Filen visades för 1 minut sedan",
		FILE_VIEWED_1_SECOND_AGO: "Filen visades för 1 sekund sedan",
		FILE_VIEWED_AT_DATE: "Filen visades ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Profilen visades i dag",
		PROFILE_VIEWED_YESTERDAY: "Profilen visades i går",
		PROFILE_VIEWED_HOURS_AGO: "Profilen visades för ${hours} timmar sedan",
		PROFILE_VIEWED_MINUTES_AGO: "Profilen visades för ${minutes} minuter sedan",
		PROFILE_VIEWED_SECONDS_AGO: "Profilen visades för ${seconds} sekunder sedan",
		PROFILE_VIEWED_1_HOUR_AGO: "Profilen visades för 1 timme sedan",
		PROFILE_VIEWED_1_MINUTE_AGO: "Profilen visades för 1 minut sedan",
		PROFILE_VIEWED_1_SECOND_AGO: "Profilen visades för 1 sekund sedan",
		PROFILE_VIEWED_AT_DATE: "Profilen visades ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Aktiviteten visades i dag",
		ACTIVITY_VIEWED_YESTERDAY: "Aktiviteten visades i går",
		ACTIVITY_VIEWED_HOURS_AGO: "Aktiviteten visades för ${hours} timmar sedan",
		ACTIVITY_VIEWED_MINUTES_AGO: "Aktiviteten visades för ${minutes} minuter sedan",
		ACTIVITY_VIEWED_SECONDS_AGO: "Aktiviteten visades för ${seconds} sekunder sedan",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Aktiviteten visades för 1 timme sedan",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Aktiviteten visades för 1 minut sedan",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Aktiviteten visades för 1 sekund sedan",
		ACTIVITY_VIEWED_AT_DATE: "Aktiviteten visades ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Bokmärket visades i dag",
		BOOKMARK_VIEWED_YESTERDAY: "Bokmärket visades i går",
		BOOKMARK_VIEWED_HOURS_AGO: "Bokmärket visades för ${hours} timmar sedan",
		BOOKMARK_VIEWED_MINUTES_AGO: "Bokmärket visades för ${minutes} minuter sedan",
		BOOKMARK_VIEWED_SECONDS_AGO: "Bokmärket visades för ${seconds} sekunder sedan",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Bokmärket visades för 1 timme sedan",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Bokmärket visades för 1 minut sedan",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Bokmärket visades för 1 sekund sedan",
		BOOKMARK_VIEWED_AT_DATE: "Bokmärket visades ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Bloggen visades i dag",
		BLOG_VIEWED_YESTERDAY: "Bloggen visades i går",
		BLOG_VIEWED_HOURS_AGO: "Bloggen visades för ${hours} timmar sedan",
		BLOG_VIEWED_MINUTES_AGO: "Bloggen visades för ${minutes} minuter sedan",
		BLOG_VIEWED_SECONDS_AGO: "Bloggen visades för ${seconds} sekunder sedan",
		BLOG_VIEWED_1_HOUR_AGO: "Bloggen visades för 1 timme sedan",
		BLOG_VIEWED_1_MINUTE_AGO: "Bloggen visades för 1 minut sedan",
		BLOG_VIEWED_1_SECOND_AGO: "Bloggen visades för 1 sekund sedan",
		BLOG_VIEWED_AT_DATE: "Bloggen visades ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Forumet visades i dag",
		FORUM_VIEWED_YESTERDAY: "Forumet visades i går",
		FORUM_VIEWED_HOURS_AGO: "Forumet visades för ${hours} timmar sedan",
		FORUM_VIEWED_MINUTES_AGO: "Forumet visades för ${minutes} minuter sedan",
		FORUM_VIEWED_SECONDS_AGO: "Forumet visades för ${seconds} sekunder sedan",
		FORUM_VIEWED_1_HOUR_AGO: "Forumet visades för 1 timme sedan",
		FORUM_VIEWED_1_MINUTE_AGO: "Forumet visades för 1 minut sedan",
		FORUM_VIEWED_1_SECOND_AGO: "Forumet visades för 1 sekund sedan",
		FORUM_VIEWED_AT_DATE: "Forumet visades ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Wikin visades i dag",
		WIKI_VIEWED_YESTERDAY: "Wikin visades i går",
		WIKI_VIEWED_HOURS_AGO: "Wikin visades för ${hours} timmar sedan",
		WIKI_VIEWED_MINUTES_AGO: "Wikin visades för ${minutes} minuter sedan",
		WIKI_VIEWED_SECONDS_AGO: "Wikin visades för ${seconds} sekunder sedan",
		WIKI_VIEWED_1_HOUR_AGO: "Wikin visades för 1 timme sedan",
		WIKI_VIEWED_1_MINUTE_AGO: "Wikin visades för 1 minut sedan",
		WIKI_VIEWED_1_SECOND_AGO: "Wikin visades för 1 sekund sedan",
		WIKI_VIEWED_AT_DATE: "Wikin visades ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Händelsen visades i dag",
		EVENT_VIEWED_YESTERDAY: "Händelsen visades i går",
		EVENT_VIEWED_HOURS_AGO: "Händelsen visades för ${hours} timmar sedan",
		EVENT_VIEWED_MINUTES_AGO: "Händelsen visades för ${minutes} minuter sedan",
		EVENT_VIEWED_SECONDS_AGO: "Händelsen visades för ${seconds} sekunder sedan",
		EVENT_VIEWED_1_HOUR_AGO: "Händelsen visades för 1 timme sedan",
		EVENT_VIEWED_1_MINUTE_AGO: "Händelsen visades för 1 minut sedan",
		EVENT_VIEWED_1_SECOND_AGO: "Händelsen visades för 1 sekund sedan",
		EVENT_VIEWED_AT_DATE: "Händelsen visades ${date}",
		//To Do
		TODO_VIEWED_TODAY: "Att göra visades i dag",
		TODO_VIEWED_YESTERDAY: "Att göra visades i går",
		TODO_VIEWED_HOURS_AGO: "Att göra visades för ${hours} timmar sedan",
		TODO_VIEWED_MINUTES_AGO: "Att göra visades för ${minutes} minuter sedan",
		TODO_VIEWED_SECONDS_AGO: "Att göra visades för ${seconds} sekunder sedan",
		TODO_VIEWED_1_HOUR_AGO: "Att göra visades för 1 timme sedan",
		TODO_VIEWED_1_MINUTE_AGO: "Att göra visades för 1 minut sedan",
		TODO_VIEWED_1_SECOND_AGO: "Att göra visades för 1 sekund sedan",
		TODO_VIEWED_AT_DATE: "Att göra visades ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "Enkäten visades i dag",
		SURVEY_VIEWED_YESTERDAY: "Enkäten visades i går",
		SURVEY_VIEWED_HOURS_AGO: "Enkäten visades för ${hours} timmar sedan",
		SURVEY_VIEWED_MINUTES_AGO: "Enkäten visades för ${minutes} minuter sedan ",
		SURVEY_VIEWED_SECONDS_AGO: "Enkäten visades för ${seconds} sekunder sedan ",
		SURVEY_VIEWED_1_HOUR_AGO: "Enkäten visades för 1 timme sedan ",
		SURVEY_VIEWED_1_MINUTE_AGO: "Enkäten visades för 1 minut sedan ",
		SURVEY_VIEWED_1_SECOND_AGO: "Enkäten visades för 1 sekund sedan ",
		SURVEY_VIEWED_AT_DATE: "Enkäten visades ${date}",
		//Survey
		GENERIC_VIEWED_TODAY: "Visades i dag",
		GENERIC_VIEWED_YESTERDAY: "Visades i går",
		GENERIC_VIEWED_HOURS_AGO: "Visades för ${hours} timmar sedan",
		GENERIC_VIEWED_MINUTES_AGO: "Visades för ${minutes} minuter sedan",
		GENERIC_VIEWED_SECONDS_AGO: "Visades för ${seconds} sekunder sedan ",
		GENERIC_VIEWED_1_HOUR_AGO: "Visades för 1 timme sedan ",
		GENERIC_VIEWED_1_MINUTE_AGO: "Visades för 1 minut sedan ",
		GENERIC_VIEWED_1_SECOND_AGO: "Visades för 1 sekund sedan ",
		GENERIC_VIEWED_AT_DATE: "Visades ${date}"
});

