/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknite tukaj za prikaz vizitke",
	"label.semtag.hover.alt" : "Kliknite za prikaz vizitke za {0}",
	"label.semtag.hover.altA11Y" : "Kliknite tukaj ali pritisnite Ctrl + Enter za prikaz vizitke",
	"label.personcard.dialog.title" : "Vizitka za {0}",

	"errorDefaultMsg2" : "Prišlo je do napake, obrnite se na skrbnika sistema",

	"loadingSTStatus" : "Nalaganje Sametimovega statusa ...",
	"noStatuAvailable" : "Noben Sametimov status ni na voljo",

	"label.personcard.cardnomarkup" : "Vizitke ni bilo mogoče pridobiti",
	"label.inactive.user.msg" : "Ta oseba ni več aktivni uporabnik",
	"label.message.information" : "Informacije:",
	"label.personcard.noprofilemsg" : "Profil za to osebo ne obstaja",
	"label.personcard.cardreqexpired" : "Zahteva za pridobitev vizitke je potekla",

	"label.bizcard.applinks.less" : "Pokaži manj",
	"label.bizcard.applinks.more" : "Pokaži več",

	"label.personcard.activitieslink" : "Dejavnosti",
	"label.personcard.activitieslink.title" : "Kliknite tukaj, da si ogledate dejavnosti v skupni rabi",
	"label.personcard.blogslink" : "Blogi",
	"label.personcard.blogslink.title" : "Kliknite tukaj, da si ogledate blog te osebe",
	"label.personcard.communitieslink" : "Skupnosti",
	"label.personcard.communitieslink.title" : "Kliknite tukaj, da si ogledate skupnosti te osebe",
	"label.personcard.dogearlink" : "Zaznamki",
	"label.personcard.dogearlink.title" : "Kliknite tukaj, da si ogledate zaznamke te osebe",
	"label.personcard.fileslink" : "Datoteke",
	"label.personcard.fileslink.title" : "Kliknite tukaj, da si ogledate datoteke v skupni rabi te osebe",
	"label.personcard.forumlink" : "Forumi",
	"label.personcard.forumlink.title" : "Kliknite tukaj, da si ogledate objave na forumih te osebe",
	"label.personcard.homepagelink" : "Domača stran",
	"label.personcard.homepagelink.title" : "Kliknite tukaj, da si ogledate domačo stran te osebe",
	"label.personcard.mobilelink" : "Mobilno",
	"label.personcard.mobilelink.title" : "Kliknite tukaj, da si ogledate mobilno stran te osebe",
	"label.personcard.newslink" : "Novice",
	"label.personcard.newslink.title" : "Kliknite tukaj, da si ogledate novice te osebe",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknite tukaj, da si ogledate profil te osebe",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknite tukaj, da si ogledate skupne rabe Quickr te osebe",
	"label.personcard.wikislink" : "Wikiji",
	"label.personcard.wikislink.title" : "Kliknite tukaj, da si ogledate wikije te osebe",

	"personCardMoreActions" : "Več dejanj",
	"personCardMoreActionsAltText" : "Kliknite za meni z dejanji",

	"label.bizcard.dismiss": "Pritisnite tipko Escape, da zavržete to vizitko.",
	"label.bizcard.fullProfile": "Celoten profil",
	"label.bizcard.activities": "Dejavnosti",
	"label.bizcard.communities": "Skupnosti",
	"label.bizcard.files": "Datoteke",
	"label.bizcard.forums": "Forumi",
	"label.bizcard.bookmarks": "Zaznamki",
	"label.bizcard.blogs": "Blogi",
	"label.bizcard.wikis": "Wikiji",

	"personCardAddAsColleagues" : "Povabi v moje omrežje",
	"personCardAddAsMyColleagues" : "Povabi v moje omrežje",
	"personCardFollow" : "Spremljaj",
	"personCardUnfollow" : "Ustavi spremljanje",
	"personCardChat" : "Klepet",
	"personCardCall" : "Klic",
	"personCardSendMail" : "Pošlji e-pošto",
	"personCardSendEMail" : "Pošlji e-pošto",
	"personCardProxyStatusAvailable" : "Sem dosegljiv",
	"personCardDownloadVCard" : "Prenesi kartico vCard",

	"friends" : "Omrežje",
	"friendsFullPageTitle" : "Omrežje",
	"friendsMenuTitleAllContacts" : "Vsi omrežni stiki",
	"friendsMenuTitleMyContacts" : "Moji omrežni stiki",
	"friendsInvitations" : "Povabila",
	"friendsMenuTitleInCommon" : "Skupne osebe",
	"friendsShowAllCommonFriends" : "Pokaži vse ...",
	"friendsViewAllFriends" : "Prikaži vse ({0})",
	"friendsSendFriendRequest" : "Pošlji zahtevo",
	"friendsNoFriends" : "S tem profilom ni povezan noben omrežni stik",
	"friendsColleaguesInvite" : "Povabite osebo {0}, da bo postala vaš omrežni stik",
	"friendsColleaguesFor" : "Omrežni stiki za osebo {0}",
	"friendsNewInv" : "{0} novo vabilo",
	"friendsNewInvs" : "Št. novih vabil: {0}",
	"friendsLoading" : "Nalaganje omrežja ...",
	"friendsLoadingInv" : "Nalaganje povabil ...",
	"friendsSelectFriendForRemoval" : "Izberite stike, ki jih želite najprej odstraniti.",
	"friendsRemoved" : "Omrežni stiki so bili odstranjeni.",
	"friendsInvSent" : "Povabilo ni bilo poslano, saj je eno povabilo že na čakanju.",
	"friendsRemovedSelected" : "Odstrani iz mojega omrežja",
	"friendsSortByDisplayName" : "Ime za prikaz",
	"friendsSortByRecent" : "Nedavno",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-pošta:",
	"friendsAltEmail" : "Nadomestna e-pošta:",
	"friendsNewInvitationsCount" : "Število novih povabil: {0}",
	"friendsNoInv" : "Ni povabil",
	"friendsInCommonSingle" : "{0} skupni omrežni stik",
	"friendsInCommonMulti" : "Št. skupnih omrežnih stikov: {0}",
	"friendsIncludeMsgForInv" : "V povabilo vključite sporočilo:",
	"friendsInitialMsgForInv" : "Želim vas dodati na svoj seznam stikov v omrežju Connections.",
	"friendsSendInvAction" : "Pošlji povabilo",
	"friendsCancelInvAction" : "Prekliči",
	"friendsAcceptAction" : "Sprejmi",
	"friendsIgnoreAction" : "Prezri",
	"friendsYouExceedTextLimit" : "Vaše sporočilo s povabilom je predolgo. Največje dovoljeno število znakov: {1}. Število znakov v tem polju: {0}.",
	"friendsCannotAddYourself" : "Sebe ne morete dodati kot omrežni stik.",
	"friendsIsYourColleague" : "{0} je vaš omrežni stik",
	"friendsRecentlyAdded" : "Osebe, ki ste jih pred kratkim dodali v svoje omrežje.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Kliknite, da strnete omrežni razdelek",
	"friendsExpandWidget" : "Kliknite, da razširite omrežni razdelek",
	"friendsIsInYourNetwork" : "{0} je v vašem omrežju.",
	"friendsActionsFor" : "Dejanja za omrežje",
	"friendsInviteFollowError" : "Med poskusom sledenja elementu {0} je prišlo do napake",
	"friendsInviteTagError" : "Med poskusom označevanja elementa {0} je prišlo do napake",
	"friendsPleaseLogIn" : "Prijavite se, če želite osebe povabiti v svoje omrežje",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Povabilo v vaše omrežje ni mogoče, ker je oseba {0} že v vašem omrežju.",
	"friendsInviteAddTagsFor" : "Dodaj oznake za {0}:",
	"friendsInviteAlsoFollow" : "Tudi spremljaj",
	"friendsInviteReceiveUpdates" : "(prejmi posodobitve)",
	"friendsInviteUpdatesDescription" : "Prejemajte posodobitve o osebah, ki jih spremljate, na domači strani in v e-poštnem povzetku.",
	"friendsInviteFollowHelp": "Za več informacij glejte {0}Spremljanje oseb{1}.",
	"friendsNetwork" : "Omrežje",
	"friendsMyNetwork" : "Omrežje",
	"friendsNetworkFor" : "Omrežje za {0}",
	"friendsRemoveSelected" : "Odstrani izbrano",
	"friendsRemoveSelectedTip" : "Kliknite za odstranitev izbranih oseb iz svojega omrežja.",
	"friendsNetworkInCommon" : "Št. skupnih omrežnih povezav: {0}.",
	"friendsAddToMyNetwork" : "Želim vas dodati v svoje omrežje Connections.",
	"friendsInvite" : "Povabi v moje omrežje",
	"friendsInvitePerson" : "Povabite osebo {0} v svoje omrežje",
	"friendsInviteMessage" : "Želim vas dodati v svoje omrežje Connections.",
	"friendsInvitedEmailSubject" : "[Profili] Vabljeni ste, da se pridružite mojemu omrežju",
	"friendsInvitedEmailMsg1" : "vas je povabil(-a), da postanete omrežni stik, z naslednjim sporočilom v povabilu:",
	"friendsInvitedEmailMsg2" : "Odprite stran s povabili v omrežje",
	"friendsInvitedEmailMsg3" : "Želim vas dodati v svoje omrežje.",
	"friendsInvitedEmailMsg4" : "Oseba {0} vas je povabila, da postanete omrežni stik:",
	"friendsInvitedEmailMsg5" : "Oseba {0} vas je povabila, da postanete omrežni stik, z naslednjim sporočilom v vabilu:",
	"friendsInviteLegalNote" : "S pošiljanjem tega povabila soglašate, da lahko oseba {0} objavlja komentarje na vaši profilni plošči.",
	"friendsInviteFailed" : "Zaradi napake strežnika e-poštno obvestilo ni bilo poslano povabljeni osebi. Vendar pa bo povabljena oseba še vedno lahko sprejela vaše povabilo prek spletne aplikacije Profili.",
	"personInNetwork" : "Omrežni stik"
})
