/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klik hier om het visitekaartje te bekijken",
	"label.semtag.hover.alt" : "Klik om visitekaartje voor {0} te bekijken",
	"label.semtag.hover.altA11Y" : "Klik hier of druk op Ctrl + Enter om het visitekaartje te bekijken",
	"label.personcard.dialog.title" : "Visitekaartje voor {0}",

	"errorDefaultMsg2" : "Er is een fout opgetreden. Neem contact op met de systeembeheerder",

	"loadingSTStatus" : "Sametime-status wordt geladen...",
	"noStatuAvailable" : "Geen Sametime-status beschikbaar",

	"label.personcard.cardnomarkup" : "Het visitekaartje kan niet worden opgehaald",
	"label.inactive.user.msg" : "Deze persoon is geen actieve gebruiker meer",
	"label.message.information" : "Informatie:",
	"label.personcard.noprofilemsg" : "Er bestaat geen profiel voor deze persoon",
	"label.personcard.cardreqexpired" : "De opdracht om het visitekaartje op te halen is vervallen",

	"label.bizcard.applinks.less" : "Minder weergeven",
	"label.bizcard.applinks.more" : "Meer weergeven",

	"label.personcard.activitieslink" : "Activiteiten",
	"label.personcard.activitieslink.title" : "Klik hier om gemeenschappelijke activiteiten te zien",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Klik hier om de blog van deze persoon te zien",
	"label.personcard.communitieslink" : "Community's",
	"label.personcard.communitieslink.title" : "Klik hier om de community's van deze persoon te zien",
	"label.personcard.dogearlink" : "Bladwijzers",
	"label.personcard.dogearlink.title" : "Klik hier om de bladwijzers van deze persoon weer te geven",
	"label.personcard.fileslink" : "Bestanden",
	"label.personcard.fileslink.title" : "Klik hier om de gedeelde bestanden van deze persoon te zien",
	"label.personcard.forumlink" : "Forums",
	"label.personcard.forumlink.title" : "Klik hier om de forumposts van deze persoon te bekijken",
	"label.personcard.homepagelink" : "Home",
	"label.personcard.homepagelink.title" : "Klik hier om de startpagina van deze persoon te zien",
	"label.personcard.mobilelink" : "Mobiel",
	"label.personcard.mobilelink.title" : "Klik hier om de mobiele pagina van deze persoon te bekijken",
	"label.personcard.newslink" : "Nieuws",
	"label.personcard.newslink.title" : "Klik hier om het nieuws van deze persoon te zien",
	"label.personcard.profilelink" : "Profiel",
	"label.personcard.profilelink.title" : "Klik hier om het profiel van deze persoon te zien",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klik hier om de Quickr-shares van deze persoon te zien",
	"label.personcard.wikislink" : "Wiki's",
	"label.personcard.wikislink.title" : "Klik hier om de wiki's van deze persoon te zien",

	"personCardMoreActions" : "Meer acties",
	"personCardMoreActionsAltText" : "Klik voor actiemenu",

	"label.bizcard.dismiss": "Druk op Escape om dit visitekaartje te verwerpen.",
	"label.bizcard.fullProfile": "Volledig profiel",
	"label.bizcard.activities": "Activiteiten",
	"label.bizcard.communities": "Community's",
	"label.bizcard.files": "Bestanden",
	"label.bizcard.forums": "Forums",
	"label.bizcard.bookmarks": "Bladwijzers",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wiki's",

	"personCardAddAsColleagues" : "Uitnodigen voor Mijn netwerk",
	"personCardAddAsMyColleagues" : "Uitnodigen voor Mijn netwerk",
	"personCardFollow" : "Volgen",
	"personCardUnfollow" : "Volgen stoppen",
	"personCardChat" : "Chatten",
	"personCardCall" : "Bellen",
	"personCardSendMail" : "E-mail verzenden",
	"personCardSendEMail" : "E-mail verzenden",
	"personCardProxyStatusAvailable" : "Ik ben bereikbaar",
	"personCardDownloadVCard" : "vCard downloaden",

	"friends" : "Netwerk",
	"friendsFullPageTitle" : "Netwerk",
	"friendsMenuTitleAllContacts" : "Alle netwerkcontacten",
	"friendsMenuTitleMyContacts" : "Mijn netwerkcontacten",
	"friendsInvitations" : "Uitnodigingen",
	"friendsMenuTitleInCommon" : "Gemeenschappelijke personen",
	"friendsShowAllCommonFriends" : "Alle weergeven...",
	"friendsViewAllFriends" : "Alle weergeven ({0})",
	"friendsSendFriendRequest" : "Aanvraag verzenden",
	"friendsNoFriends" : "Er zijn geen netwerkcontacten gekoppeld aan dit profiel",
	"friendsColleaguesInvite" : "{0} uitnodigen als contactpersoon in uw netwerk",
	"friendsColleaguesFor" : "Netwerkcontacten voor {0}",
	"friendsNewInv" : "{0} nieuwe uitnodiging",
	"friendsNewInvs" : "{0} nieuwe uitnodigingen",
	"friendsLoading" : "Netwerk wordt geladen...",
	"friendsLoadingInv" : "Uitnodigingen laden...",
	"friendsSelectFriendForRemoval" : "Selecteer eerst de contacten die u wilt verwijderen.",
	"friendsRemoved" : "Netwerkcontact(en) verwijderd.",
	"friendsInvSent" : "Geen uitnodiging verzonden want er is er al een onderweg.",
	"friendsRemovedSelected" : "Verwijderen uit Mijn netwerk",
	"friendsSortByDisplayName" : "Weergavenaam",
	"friendsSortByRecent" : "Recent",
	"friendsTelephone" : "Telefoon:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "Alternatief e-mailadres:",
	"friendsNewInvitationsCount" : "U hebt {0} nieuwe uitnodiging(en)",
	"friendsNoInv" : "Geen uitnodigingen",
	"friendsInCommonSingle" : "U hebt {0} gemeenschappelijk netwerkcontact",
	"friendsInCommonMulti" : "U hebt {0} gemeenschappelijke netwerkcontacten",
	"friendsIncludeMsgForInv" : "Voeg een bericht toe aan de uitnodiging:",
	"friendsInitialMsgForInv" : "Ik wil u graag toevoegen aan mijn lijst van Connections-netwerkcontacten.",
	"friendsSendInvAction" : "Uitnodiging verzenden",
	"friendsCancelInvAction" : "Annuleren",
	"friendsAcceptAction" : "Accepteren",
	"friendsIgnoreAction" : "Negeren",
	"friendsYouExceedTextLimit" : "Uw uitnodiging is te lang. Deze mag niet langer zijn dan {1} tekens. Dit veld bevat {0} tekens.",
	"friendsCannotAddYourself" : "U kunt uzelf niet toevoegen als netwerkcontact.",
	"friendsIsYourColleague" : "{0} is contactpersoon in uw netwerk",
	"friendsRecentlyAdded" : "Er zijn onlangs nieuwe gebruikers aan uw netwerk toegevoegd.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Klik hier om de netwerksectie samen te vouwen",
	"friendsExpandWidget" : "Klik hier om de netwerksectie uit te vouwen",
	"friendsIsInYourNetwork" : "{0} zit in uw netwerk.",
	"friendsActionsFor" : "Acties voor netwerk",
	"friendsInviteFollowError" : "Er is een fout opgetreden bij volgen van {0}",
	"friendsInviteTagError" : "Er is een fout opgetreden bij het voorzien van een tag voor {0}",
	"friendsPleaseLogIn" : "Meld u aan om personen uit te nodigen voor uw netwerk",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "De uitnodiging voor uw netwerk is niet mogelijk, omdat de {0} al deel uitmaakt van uw netwerk.",
	"friendsInviteAddTagsFor" : "Tags toevoegen voor {0}:",
	"friendsInviteAlsoFollow" : "Volg ook",
	"friendsInviteReceiveUpdates" : "(updates ontvangen)",
	"friendsInviteUpdatesDescription" : "U ontvangt updates over de personen die u volgt op de pagina Homepage en in een e-mailoverzicht.",
	"friendsInviteFollowHelp": "Raadpleeg {0}Personen volgen{1} voor meer informatie.",
	"friendsNetwork" : "Netwerk",
	"friendsMyNetwork" : "Netwerk",
	"friendsNetworkFor" : "Netwerk voor {0}",
	"friendsRemoveSelected" : "Selectie verwijderen",
	"friendsRemoveSelectedTip" : "Klik hier om de geselecteerde personen uit uw netwerk te verwijderen.",
	"friendsNetworkInCommon" : "U hebt {0} gemeenschappelijke netwerkconnecties.",
	"friendsAddToMyNetwork" : "Ik wil u graag toevoegen aan mijn Connections-netwerk.",
	"friendsInvite" : "Uitnodigen voor Mijn netwerk",
	"friendsInvitePerson" : "{0} uitnodigen voor uw netwerk",
	"friendsInviteMessage" : "Ik wil u graag toevoegen Connections-netwerk.",
	"friendsInvitedEmailSubject" : "[Profielen] U wordt uitgenodigd om deel te nemen aan mijn netwerk",
	"friendsInvitedEmailMsg1" : "heeft u uitgenodigd om contactpersoon in zijn/haar netwerk te worden. De uitnodiging bevat het volgende bericht:",
	"friendsInvitedEmailMsg2" : "Pagina met netwerkuitnodigingen openen",
	"friendsInvitedEmailMsg3" : "Ik wil u graag toevoegen aan mijn netwerk.",
	"friendsInvitedEmailMsg4" : "{0} heeft u uitgenodigd als netwerkcontact:",
	"friendsInvitedEmailMsg5" : "{0} heeft u uitgenodigd om een contactpersoon in zijn/haar netwerk te worden. De uitnodiging bevat het volgende bericht:",
	"friendsInviteLegalNote" : "Als u deze uitnodiging verzendt, staat u {0} toe om te reageren op uw profielboard.",
	"friendsInviteFailed" : "Vanwege een serverfout is een e-mailbericht niet verzonden naar de uitgenodigde persoon. Deze kan uw uitnodiging echter toch accepteren via de webtoepassing Profielen.",
	"personInNetwork" : "Netwerkcontactpersoon"
})
