/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtrare după:",
		"SHOW":"Afişare:",
		"ACL_FILTER_LABEL":"Filtrare după vizibilitate",
		"PARENT_FILTER_LABEL":"Filtrare după container",
		"TYPE_FILTER_LABEL":"Filtrare după tip",
		"PAGING_TOP":"Paginare primară",
		"PAGING_BOTTOM":"Paginare secundară",
		"PREVIOUS":"Anterior",
		"NEXT":"Următoare",
		"PAGE":"Pagina {0} din {1}",
		"PAGE_COLON":"Pagină:",
		"RESULTS":"{span}{0}-{1}{/span} din {2}",
		"ITEMS":"{0} articole",
		/* Application names */
		"ACTIVITIES":"Activităţi",
		"BLOGS":"Bloguri",
		"CALENDAR":"Calendar",
		"COMMUNITIES":"Comunităţi",
		"BOOKMARKS":"Semne de carte",
		"DOGEAR":"Semne de carte",
		"EVENTS":"Evenimente",
		"FILES":"Fişiere",
		"FORUMS":"Forumuri",
		"PROFILES":"Profiluri",
		"WIKI":"Wiki-uri",
		"WIKIS":"Wiki-uri",
		"FEEDS":"Alimentări",
		"STATUS_UPDATES":"Actualizări status",
		"ONECOMMENT":"1 comentariu",
		"COMMENTS":"{0} comentarii",
		"ONEPERSON":"1 persoană",
		"PEOPLE":"{0} persoane",
		"TAGS":"Taguri:",
		"TAGSMORE":"şi încă {0}",
		"NORESULTSMESSAGE":"Nu au fost găsite rezultate pentru acea căutare",
		"JAN":"Ianuarie",
		"FEB":"Februarie",
		"MAR":"Martie",
		"APR":"Aprilie",
		"MAY":"Mai",
		"JUN":"Iunie",
		"JUL":"Iulie",
		"AUG":"August",
		"SEP":"Septembrie",
		"OCT":"Octombrie",
		"NOV":"Noiembrie",
		"DEC":"Decembrie",
		"NO_CONTACT":"Căutarea nu a fost efectuată deoarece serverul nu a putut fi contactat",
		"SERVER_ERROR":"Căutarea nu a fost efectuată datorită unei erori de server",
		"SORT_BY":"Sortare după:",
		"SORT_RELEVANCE":"Relevanţă",
		"SORT_DATE":"Dată",
		"SORT_LAST_UPDATED":"Ultima actualizare",
		"SORT_DUE_DATE":"Dată scadenţă",
		"SORT_VISITS":"Vizite",
		"SORT_COMMENTS":"Comentarii",
		"SORT_RECOMMENDATION":"Aprecieri",
		"SORT_POPULARITY":"Popularitate",
		"SORT_FIRSTNAME":"Prenume",
		"SORT_LASTNAME":"Nume",
		"SORT_DOWNLOADS":"Descărcări",
		"SORT_TYPE":"Tip",
		"SORT_SIZE":"Dimensiune",
		"SORT_TITLE":"Titlu",
		"PRIVATE":"Privat",
		"MODERATED":"Moderat",
		"COMMUNITY_ACTIVITY":"Activitate comunitate",
		"COMMUNITY_BLOG":"Blog comunitate",
		"COMMUNITY_FILE":"Fişier Comunitate",
		"COMMUNITY_FORUM":"Forum Comunitate",
		"COMMUNITY_WIKI":"Wiki comunitate",
		"COMMUNITY_FEED":"Alimentare Comunitate",
		"COMMUNITY_BOOKMARK":"Semne de carte Comunitate",
		"NO_TAG":"Niciun tag încă",
		"NO_DATE":"Nu sunt date încă",
		"NO_PEOPLE":"Nu sunt persoane încă",
		"REMOVE_FILTER_LABEL":"Faceţi clic pentru înlăturare",
		"REMOVE_FILTER_TITLE":"Înlăturare",
		"REMOVE_FILTER_TOOLTIP":"Înlăturaţi acest filtru",
		"COMMENT_ON":"Comentariu la",
		"EXPAND_COLLAPSE":"Faceţi clic pentru expandare / restrângere",
		"EXPAND":"Expandare",
		"COLLAPSE":"Restrângere",
		"EXPAND_MONTHS_FILTER":"Expandare filtrul luni din anul {0}",
		"SORT_RELEVANCE_LABEL":"Faceţi clic pentru a sorta după relevanţă",
		"SORT_DATE_LABEL":"Faceţi clic pentru a sorta după dată",
		"SORT_UPDATED_LABEL":"Faceţi clic pentru a sorta după ultimul actualizat",
		"SORT_DUE_LABEL":"Faceţi clic pentru a sorta după data de scadenţă",
		"SORT_VISITS_LABEL":"Faceţi clic pentru a sorta numărul de vizite",
		"SORT_COMMENTS_LABEL":"Faceţi clic pentru a sorta după numărul de comentarii",
		"SORT_RECOMMENDATIONS_LABEL":"Faceţi clic pentru sortare după numărul de aprecieri",
		"SORT_POPULARITY_LABEL":"Faceţi clic pentru a sorta după popularitate",
		"SORT_FIRST_NAME_LABEL":"Faceţi clic pentru sortare după numele dat",
		"SORT_LAST_NAME_LABEL":"Faceţi clic pentru sortare după numele de familie",
		"RATING":"Aprecieri",
		"GRADUATED":"Promovată",
		"ONEVOTE":"1 vot",
		"VOTES":"{0} voturi",
		"BOOKMARK_THIS_RESULT":"Puneţi un semn de carete la acesta",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (inactiv)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} persoane marcate",
		/* eg from an Activity */
		"FROMANACTIVITY":"dintr-o Activitate",
		"FROMABLOG":"dintr-un Blog",
		"FROMANIDEATIONBLOG":"dintr-un Blog de ideaţie",
		"FROMANEVENT":"dintr-un Eveniment",
		"FROMAFORUM":"dintr-un Forum",
		"FROMAWIKI":"dintr-un Wiki",
		"FROMACOMMUNITY":"dintr-o Comunitate",
		"FROMXCOMMUNITIES":"din {0} Comunităţi",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Activitate",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog de ideaţie",
		"ENTRY_ALONE":"Intrare",
		"EVENT_ALONE":"Eveniment",
		"FORUM_ALONE":"Forum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Comunitate",
		"XCOMMUNITIES_ALONE":"{0} Comunităţi",
		"SHAREDCOMMUNITIES":"Partajat cu aceste comunităţi",
		"INACOMMUNITY":"într-o Comunitate",
		"LASTUPDATED":"indexul de căutare a fost actualizat ultima dată:",
		"NODESCRIPTION":"Nu există descriere sau sumar pentru acest rezultat.",
		"ATTACHMENT":"Ataşament:",
		"ACTIVITY":"Activitate:",
		"ACTIVITYBOOKMARK":"Semn de carte pentru Activitate:",
		"ACTIVITYCOMMENT":"Comentariu pentru Activitate:",
		"ACTIVITYENTRY":"Intrare Activitate:",
		"ACTIVITYSECTION":"Secţiune Activitate:",
		"ACTIVITYTODO":"De făcut în Activitate:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Intrare Blog:",
		"BLOGCOMMENT":"Comentariu pe Blog:",
		"BOOKMARK":"Semn de carte:",
		"CALENDAREVENT":"Eveniment:",
		"CATEGORY":"Categorie:",
		"COMMENT":"Comentariu:",
		"COMMUNITY":"Comunitate:",
		"ENTRY":"Intrare:",
		"EVENTDATEON":"Pe: {0}",
		"EVENTISALLDAY":"Eveniment Toată ziua",
		"EVENTREPEATS":"Repetări",
		"FEED":"Alimentare:",
		"FILE":"Fişier:",
		"FORUM":"Forum:",
		"FORUMCATEGORY":"Categorie de Forum:",
		"FORUMTOPIC":"Subiect forum:",
		"IDEA":"Idee:",
		"IDEACOMMENT":"Comentariu la Idee:",
		"IDEATIONBLOG":"Blog de ideaţie:",
		"PAGE":"Pagină:",
		"PROFILE":"Profil:",
		"SECTION":"Secţiune:",
		"STATUSUPDATE":"Actualizare de stare",
		"STATUSUPDATE_PREFIX":"Actualizare de stare:",
		"TOPIC":"Subiect:",
		"TOPIC_WITH_ATTACHMENT":"Subiect",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Pagină de Wiki:",
		"WIKIFILE":"Ataşament Wiki:",
		"SEARCH":"Căutare:",
		"TODO":"De făcut:",
		"ALLRESULTS":"Toate rezultatele",
		"PUBLICCONTENT":"Conţinut Public",
		"MYCONTENT":"Conţinutul meu",
		"RESULTNOTFOUND":"Nu aţi găsit ceea ce căutaţi?",
		"TEMPDIFFICULTIES":"Notă: Din cauza unor dificultăţi temporare privind indexarea, căutarea dumneavoastră nu a inclus {0}, care a suferit modificări în ultimele {1} zile.",
		"TRYLATER":"Vă rugăm să încercaţi din nou mai târziu.",
		"MULTIPLETEMPDIFFICULTIES":"Notă: Din cauza unor dificultăţi de indexare temporare, căutarea nu a inclus {0} care au fost modificate recent.",
		"YOUAREAUTHOR":"Sunteţi autorul",
		"YOUARECONTRIBUTOR":"Sunteţi un contribuitor",
		"YOUAREOWNER":"Sunteţi un proprietar",
		"YOUAREMEMBER":"Sunteţi un membru",
		/* Profiles */
		"MYNETWORK":"Reţeaua mea",
		"ALLPEOPLE":"Toate persoanele",
		"EXCLUDEINACTIVE":"Excludere Persoane inactive",
		"PHONE":"Telefon:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Toate comunităţile",
		"PUBLICCOMMUNITIES":"Comunităţi publice",
		"MYCOMMUNITIES":"Comunităţile mele",
		"EVERYTHINGCOMMUNITIES":"Totul din Comunităţi",
		"COMMUNITIESONLY":"Comunităţi",
		"COMMUNITIESCONTENT":"Conţinut din Comunităţi",
		/* Activities */
		"ALLACTIVITIES":"Toate activităţile",
		"PUBLICACTIVITIES":"Activităţi publice",
		"MYACTIVITIES":"Activităţile mele",
		"EVERYTHINGACTIVITIES":"Totul din Activităţi",
		"ACTIVITIESONLY":"Activităţi",
		"SECTIONSACTIVITIES": "Secţiuni din Activităţi",
		"ENTRIESACTIVITIES":"Intrări din Activităţi",
		"TODOSACTIVITIES":"De făcut din Activităţi",
		"BOOKMARKSACTIVITIES":"Semne de carte din Activităţi",
		"FILESACTIVITIES":"Ataşamente din activităţi",
		"ALLTYPESACTIVITIES":"Toate tipurile din Activităţi",
		"COMMUNITYACTIVITIES":"Activităţi din Comunităţi",
		"STANDALONEACTIVITIES":"Activităţi autonome",
		/* Forums */
		"ALLFORUMS":"Toate forumurile",
		"PUBLICFORUMS":"Forumuri publice",
		"MYFORUMS":"Forumurile mele",
		"EVERYTHINGFORUMS":"Totul din Forumuri",
		"FORUMSONLY":"Forumuri",
		"TOPICSFORUMS":"Subiecte de Forum",
		"FORUMCATEGORIES": "Categorii de Forum",
		"FILESFORUMS":"Ataşamente din Forumuri",
		"ALLTYPESFORUMS":"Toate tipurile din Forumuri",
		"COMMUNITYFORUMS":"Forumuri din Comunităţi",
		"STANDALONEFORUMS":"Forumuri autonome",
		/* Blogs */
		"ALLBLOGS":"Toate blogurile",
		"PUBLICBLOGS":"Bloguri publice",
		"MYBLOGS":"Blogurile mele",
		"EVERYTHINGBLOGS":"Totul din Bloguri",
		"BLOGSONLY":"Bloguri",
		"ENTRIESBLOGS":"Intrări blog",
		"FILESBLOGS":"Ataşamente din Bloguri",
		"EVERYTHINGIDEATIONBLOGS":"Totul din Bloguri de ideaţie",
		"BLOGSIDEATIONBLOGS":"Bloguri de ideaţie",
		"BLOGSIDEAS":"Idei",
		"ALLTYPESBLOGS":"Toate tipurile de bloguri",
		"COMMUNITYBLOGS":"Bloguri din Comunităţi",
		"COMMUNITYIDEATIONBLOGS":"Bloguri de ideaţie din Comunităţi",
		"STANDALONEBLOGS":"Bloguri autonome",
		/* Bookmarks */
		"ALLBOOKMARKS":"Toate Semnele de carte",
		"PUBLICBOOKMARKS":"Semne de carte publice",
		"MYBOOKMARKS":"Semnele mele de carte",
		"ALLTYPESBOOKMARKS":"Toate tipurile de Semne de carte",
		"COMMUNITYBOOKMARKS":"Semne de carte din Comunităţi",
		"STANDALONEBOOKMARKS":"Semne de carte autonome",
		/* Files */
		"ALLFILES":"Toate fişierele",
		"PUBLICFILES":"Fişiere publice",
		"MYFILES":"Fişierele mele",
		"ALLTYPESFILES":"Toate tipurile din Fişiere",
		"COMMUNITYFILES":"Fişiere din Comunităţi",
		"STANDALONEFILES":"Fişiere autonome",
		"NUMDOWNLOADS":"{0} descărcări",
		/* Wikis */
		"ALLWIKIS":"Toate Wiki-urile",
		"PUBLICWIKIS":"Wiki-uri publice",
		"MYWIKIS":"Wiki-urile mele",
		"EVERYTHINGWIKIS":"Totul din Wiki-uri",
		"WIKISONLY":"Wiki-uri",
		"PAGESWIKIS":"Pagini de Wiki",
		"FILESWIKIS":"Ataşamente din Wiki-uri",
		"ALLTYPESWIKIS":"Toate tipurile de Wiki-uri",
		"COMMUNITYWIKIS":"Wiki-uri din Comunităţi",
		"STANDALONEWIKIS":"Wiki-uri autonome",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Actualizări pentru toate stările",
		"PUBLICSTATUSUPDATES":"Actualizări ale stării publice",
		"MYSTATUSUPDATES":"Actualizările mele de status",
		"ALLTYPESSTATUSUPDATES":"Toate tipurile de Actualizări de status",
		"COMMUNITYSTATUSUPDATES":"Actualizări de status din Comunităţi",
		"STANDALONESTATUSUPDATES":"Actualizări de status din Profiluri",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Acest URL a primit semn de carte de la un număr de utilizatori",
		"BOOKMARKEDCOMMUNITY":"Această comunitate a primit semn de carte de la un număr de utilizatori",
		"BOOKMARKEDPROFILE":"Acest Profil a primit semn de carte de la un număr de utilizatori",
		"BOOKMARKEDBLOG":"Acest Blog a primit semn de carte de la un număr de utilizatori",
		"COMMUNITYBLOG":"Acesta este un blog ce conţine o comunitate",
		"BOOKMARKEDACTIVITY":"Această Activitate a primit semn de carte de la un număr de utilizatori",
		"COMMUNITYACTIVITY":"Aceasta este o Activitate dintr-o comunitate",
		"BOOKMARKEDFILE":"Acest fişier a primit semn de carte de la un număr de utilizatori",
		"COMMUNITYFILE":"Acesta este un Fişier dintr-o comunitate",
		"BOOKMARKED":"Acest Wiki a primit semnd e carte de la un număr de utilizatori",
		"COMMUNITYWIKI":"Acesta este un Wiki dintr-o  comunitate",
		"BOOKMARKEDFORUM":"Acest Forum a primit semn de carte de la un număr de utilizatori",
		"COMMUNITYFORUM":"Acesta este un Forum dintr-o comunitate",
		"ALLTAGANDTTILE":"Pentru a vedea toate titlurile şi tagurile pentru acest URL, faceţi clic pe acest buton",
		"TAGS_ARE_FROM":"Acest rezultat de căutare poate include taguri din:",
		"BOOKMARKS_TITLE":"Semne de carte",
		"COMMUNITIES_TITLE":"Comunităţi",
		"ACTIVITIES_TITLE":"Activităţi",
		"HELP":"Ajutor",
		"MORESTATUSUPDATES":"Vizualizaţi mai multe potriviri de actualizări de status",
		"TITLE_PREFIX":"titlu",
		"LATEST_MESSAGE":"Cel mai recent Mesaj",
		"LATEST_STATUS_UPDATE":"Cea mai recentă actualizare de stare",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Cea mai recentă actualizare de stare a Comunităţii",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"cea mai recentă actualizare de stare a Comunităţilor",
		"SEARCH_RESULTS":"Rezultate căutare în tot conţinutul",
		"ACTIVITIES_SEARCH_RESULTS":"Rezultate ale căutării Activităţi",
		"BLOGS_SEARCH_RESULTS":"Rezultate ale căutării Bloguri",
		"BOOKMARKS_SEARCH_RESULTS":"Rezultate de căutare Semne de carte",
		"COMMUNITIES_SEARCH_RESULTS":"Rezultate de căutare Comunităţi",
		"FILES_SEARCH_RESULTS":"Rezultate de căutare Fişiere",
		"FORUMS_SEARCH_RESULTS":"Rezultate de căutare Forumuri",
		"PROFILES_SEARCH_RESULTS":"Rezultate de căutare Profiluri",
		"DIRECTORY_SEARCH_RESULTS":"Rezultatele de căutare director ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Rezultate de căutare Wiki-uri",
		"STATUS_UPDATES_SEARCH_RESULTS":"Rezultate de căutare Actualizări status",
		"VIEW_ALL":"{span}View All{/span} ({0})",
		"MATCHING_ONE_OF":"Potrivire cu una dintre:",
		"MATCHING_ALL_OF":"Potrivire cu toate dintre:",
		"MATCHING":"Potrivire:",
		"MATCHING_DOC_TYPE":"Potrivire Tip de document:",
		"BOOKMARK_HELP":"Ajutor Semne de carte",
		"CLOSE_BOOKMARK_HELP":"Închidere ajutor Semne de carte",
		"DOCUMENT_TYPE_PREFIX":"Tip document:",
		"LAST_PAGE_MESSAGE": "Hopa! Sunt foarte multe rezultate ale căutării. Încercaţi să îngustaţi căutarea prin adăugarea mai multor termeni de căutare.",
		"LAST_PAGE_SUBMESSAGE": "Obţineţi primele {resultNumber} de rezultate relevante."
});

