/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Düğüme ilişkin bilgiler: ",
		"INSTALLED": "Kurulu hizmetler denetleniyor",
		"RESUMETOKENS": "Sürdürme simgeleri denetleniyor",
		"SEEDLISTS": "Çekirdek listelerinin kullanılabilirliği denetleniyor",
		"CALENDARS": "Zamanlama takvimlerinin düzgün yapılandırılıp yapılandırılmadığı denetleniyor",
		"VARIABLES": "WebSphere değişkenlerinin ayarlanıp ayarlanmadığı denetleniyor",
		"TASKS": "Etkinleştirilmiş dizinleme görevleri denetleniyor",
		"INDEXFILES": "Zorunlu dosyalar için dizin klasörü denetleniyor",
		"LOGS": "Hatalar için günlükler inceleniyor",
		"CONFIGFILES": "Yapılandırma dosyaları inceleniyor",
		"DICTIONARIES": "Etkinleştirilen sözlük sayıları denetleniyor",
		"SYNC": "Düğümlerin durumu denetleniyor",
		"DBRECORDS": "Veritabanı kayıtları denetleniyor",
		"INSTALLEDMSG": "Aşağıdaki hizmet kurulu: ",
		"RESUMETOKENSMSG": "Sürdürme simgesi: ",
		"SEEDLISTSMSG": "Çekirdek listesi şunun için alınamadı: ",
		"CALENDARSMSG": "Zamanlama takvimi denetimi başarıyla tamamlandı: ",
		"VARIABLESMSG": "Değişken: ",
		"TASKSMSG": "Şu görev etkinleştirildi: ",
		"INDEXFILESMSG" : "Şu dosyalar arama dizini klasöründe: ",
		"LOGSMSG" : "Şu hata iletilerini inceleyin: ",
		"CONFIGFILESMSG" : "Şu yapılandırma dosyaları bulundu: ",
		"DICTIONARIESMSG" : "Etkinleştirilen sözlük sayısı: ",
		"INSYNC": "Tüm düğümler eşit",
		"OUTOFSYNC": "Eşit olmayan düğüm sayısı: ",
		"NOTBLOCKED": "Engellenen düğüm yok",
		"BLOCKED": "Engellenen düğüm sayısı: ",
		"INDATE": "Tüm düğümler geçerli tarihi aralığında",
		"OUTOFDATE": "Zamanı geçmiş düğüm sayısı: ",
		"NUMOFDOCS": "Veritabanındaki belge sayısı ",
		"FILESTOCONVERT": "Dönüştürülecek dosya belgelerinin sayısı ",
		"CONVERTEDFILES": "Dönüştürülen dosya sayısı ",
		"TOTALFILES": "Veritabanındaki toplam dosya sayısı ",
		"ERROR":"Hata",
		"ERROR_PREFIX":"Hata:",
		"INFO":"Bilgi",
		"INFO_PREFIX":"Bilgi:",
		"WARNING":"Uyarı",
		"WARNING_PREFIX":"Uyarı:",
		"LOADING_MESSAGE": "Yükleniyor",
		"SERVER_STATUS": "Sunucu Durumu",
		"INITIAL_INDEXING_EXCEPTIONS": "Başlangıç Dizin Oluşturma Özel Durumları",
		"SYS_OUT_EXCEPTIONS": "SystemOut Günlüğü Özel Durumları",
		"SEEDLIST_VALIDATE": "Çekirdek Listeleri Geçerlilik Denetimi",
		"ERRORS_DURING_INITIAL_INDEXING":"Bir başlangıç dizini oluşturulurken aşağıdaki özel durumlar ortaya çıktı",
		"CRAWL_FAILED": "Aşağıdaki hizmete ilişkin tüm veriler toplanamadı: ",
		"EXCEPTION_ENCOUNTERED": "Bilgi toplama işlemi aşağıdaki iletiyle başarısız oldu: ",
		"SAND_VALIDATE": "SAND Geçerlilik Denetimi",
		"CHECK_FOR_SAND_FILES":"SAND dosyaları denetleniyor",
		"IS_FILE_AVAILABLE":"Dosyanın oluşturulup oluşturulmadığı denetleniyor: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Bir başlangıç dizini oluşturulurken aşağıdaki özel durumlar ortaya çıktı",
		"CRAWL_FAILED":"Aşağıdaki hizmete ilişkin tüm veriler toplanamadı: ",
		"EXCEPTION_ENCOUNTERED":"Bilgi toplama işlemi aşağıdaki iletiyle başarısız oldu: "
});

