/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "עודכן על ידי ${author}",
		PREVIEW_MODE_ONLY: "(מצב תצוגה מקדימה בלבד)",
		//Community
		COMMUNITY_VIEWED_TODAY: "הקהילה הוצגה היום",
		COMMUNITY_VIEWED_YESTERDAY: "הקהילה הוצגה אתמול",
		COMMUNITY_VIEWED_HOURS_AGO: "הקהילה הוצגה לפני ${hours} שעות",
		COMMUNITY_VIEWED_MINUTES_AGO: "הקהילה הוצגה לפני ${minutes} דקות",
		COMMUNITY_VIEWED_SECONDS_AGO: "הקהילה הוצגה לפני ${seconds} שניות",
		COMMUNITY_VIEWED_1_HOUR_AGO: "הקהילה הוצגה לפני 1 שעה",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "הקהילה הוצגה לפני 1 דקה",
		COMMUNITY_VIEWED_1_SECOND_AGO: "הקהילה הוצגה לפני 1 שנייה",
		COMMUNITY_VIEWED_AT_DATE: "הקהילה הוצגה ${date}",
		//File
		FILE_VIEWED_TODAY: "הקובץ הוצג היום",
		FILE_VIEWED_YESTERDAY: "הקובץ הוצג אתמול",
		FILE_VIEWED_HOURS_AGO: "הקובץ הוצג לפני ${hours} שעות",
		FILE_VIEWED_MINUTES_AGO: "הקובץ הוצג לפני ${minutes} דקות",
		FILE_VIEWED_SECONDS_AGO: "הקובץ הוצג לפני ${seconds} שניות",
		FILE_VIEWED_1_HOUR_AGO: "הקובץ הוצג לפני 1 שעה",
		FILE_VIEWED_1_MINUTE_AGO: "הקובץ הוצג לפני 1 דקה",
		FILE_VIEWED_1_SECOND_AGO: "הקובץ הוצג לפני 1 שנייה",
		FILE_VIEWED_AT_DATE: "הקובץ הוצג ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "הפרופיל הוצג היום",
		PROFILE_VIEWED_YESTERDAY: "הפרופיל הוצג אתמול",
		PROFILE_VIEWED_HOURS_AGO: "הפרופיל הוצג לפני ${hours} שעות",
		PROFILE_VIEWED_MINUTES_AGO: "הפרופיל הוצג לפני ${minutes} דקות",
		PROFILE_VIEWED_SECONDS_AGO: "הפרופיל הוצג לפני ${seconds} שניות",
		PROFILE_VIEWED_1_HOUR_AGO: "הפרופיל הוצג לפני 1 שעה",
		PROFILE_VIEWED_1_MINUTE_AGO: "הפרופיל הוצג לפני 1 דקה",
		PROFILE_VIEWED_1_SECOND_AGO: "הפרופיל הוצג לפני 1 שנייה",
		PROFILE_VIEWED_AT_DATE: "הפרופיל הוצגה ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "הפעילות הוצגה היום",
		ACTIVITY_VIEWED_YESTERDAY: "הפעילות הוצגה אתמול",
		ACTIVITY_VIEWED_HOURS_AGO: "הפעילות הוצגה לפני ${hours} שעות",
		ACTIVITY_VIEWED_MINUTES_AGO: "הפעילות הוצגה לפני ${minutes} דקות",
		ACTIVITY_VIEWED_SECONDS_AGO: "הפעילות הוצגה לפני ${seconds} שניות",
		ACTIVITY_VIEWED_1_HOUR_AGO: "הפעילות הוצגה לפני 1 שעה",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "הפעילות הוצגה לפני 1 דקה",
		ACTIVITY_VIEWED_1_SECOND_AGO: "הפעילות הוצגה לפני 1 שנייה",
		ACTIVITY_VIEWED_AT_DATE: "הפעילות הוצגה ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "הסימניה הוצגה היום",
		BOOKMARK_VIEWED_YESTERDAY: "הסימניה הוצגה אתמול",
		BOOKMARK_VIEWED_HOURS_AGO: "הסימניה הוצגה לפני ${hours} שעות",
		BOOKMARK_VIEWED_MINUTES_AGO: "הסימניה הוצגה לפני ${minutes} דקות",
		BOOKMARK_VIEWED_SECONDS_AGO: "הסימניה הוצגה לפני ${seconds} שניות",
		BOOKMARK_VIEWED_1_HOUR_AGO: "הסימניה הוצגה לפני 1 שעה",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "הסימניה הוצגה לפני 1 דקה",
		BOOKMARK_VIEWED_1_SECOND_AGO: "הסימניה הוצגה לפני 1 שנייה",
		BOOKMARK_VIEWED_AT_DATE: "הסימניה הוצגה ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "הבלוג הוצג היום",
		BLOG_VIEWED_YESTERDAY: "הבלוג הוצג אתמול",
		BLOG_VIEWED_HOURS_AGO: "הבלוג הוצג לפני ${hours} שעות",
		BLOG_VIEWED_MINUTES_AGO: "הבלוג הוצג לפני ${minutes} דקות",
		BLOG_VIEWED_SECONDS_AGO: "הבלוג הוצג לפני ${seconds} שניות",
		BLOG_VIEWED_1_HOUR_AGO: "הבלוג הוצג לפני 1 שעה",
		BLOG_VIEWED_1_MINUTE_AGO: "הבלוג הוצג לפני 1 דקה",
		BLOG_VIEWED_1_SECOND_AGO: "הבלוג הוצג לפני 1 שנייה",
		BLOG_VIEWED_AT_DATE: "הבלוג הוצג ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "הפורום הוצג היום",
		FORUM_VIEWED_YESTERDAY: "הפורום הוצג אתמול",
		FORUM_VIEWED_HOURS_AGO: "הפורום הוצג לפני ${hours} שעות",
		FORUM_VIEWED_MINUTES_AGO: "הפורום הוצג לפני ${minutes} דקות",
		FORUM_VIEWED_SECONDS_AGO: "הפורום הוצג לפני ${seconds} שניות",
		FORUM_VIEWED_1_HOUR_AGO: "הפורום הוצג לפני 1 שעה",
		FORUM_VIEWED_1_MINUTE_AGO: "הפורום הוצג לפני 1 דקה",
		FORUM_VIEWED_1_SECOND_AGO: "הפורום הוצג לפני 1 שנייה",
		FORUM_VIEWED_AT_DATE: "הפורום הוצג ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "הוויקי הוצג היום",
		WIKI_VIEWED_YESTERDAY: "הוויקי הוצג אתמול",
		WIKI_VIEWED_HOURS_AGO: "הפורום הוצג לפני ${hours} שעות",
		WIKI_VIEWED_MINUTES_AGO: "הפורום הוצג לפני ${minutes} דקות",
		WIKI_VIEWED_SECONDS_AGO: "הפורום הוצג לפני ${seconds} שניות",
		WIKI_VIEWED_1_HOUR_AGO: "הפורום הוצג לפני 1 שעה",
		WIKI_VIEWED_1_MINUTE_AGO: "הפורום הוצג לפני 1 דקה",
		WIKI_VIEWED_1_SECOND_AGO: "הפורום הוצג לפני 1 שנייה",
		WIKI_VIEWED_AT_DATE: "הפורום הוצג ${date}",
		//Event
		EVENT_VIEWED_TODAY: "האירוע הוצג היום",
		EVENT_VIEWED_YESTERDAY: "האירוע הוצג אתמול",
		EVENT_VIEWED_HOURS_AGO: "האירוע הוצג לפני ${hours} שעות",
		EVENT_VIEWED_MINUTES_AGO: "האירוע הוצג לפני ${minutes} דקות",
		EVENT_VIEWED_SECONDS_AGO: "האירוע הוצג לפני ${seconds} שניות",
		EVENT_VIEWED_1_HOUR_AGO: "האירוע הוצג לפני 1 שעה",
		EVENT_VIEWED_1_MINUTE_AGO: "האירוע הוצג לפני 1 דקה",
		EVENT_VIEWED_1_SECOND_AGO: "האירוע הוצג לפני 1 שנייה",
		EVENT_VIEWED_AT_DATE: "האירוע הוצג ${date}",
		//To Do
		TODO_VIEWED_TODAY: "המטלה הוצגה היום",
		TODO_VIEWED_YESTERDAY: "המטלה הוצגה אתמול",
		TODO_VIEWED_HOURS_AGO: "המטלה הוצגה לפני ${hours} שעות",
		TODO_VIEWED_MINUTES_AGO: "המטלה הוצגה לפני ${minutes} דקות",
		TODO_VIEWED_SECONDS_AGO: "המטלה הוצגה לפני ${seconds} שניות",
		TODO_VIEWED_1_HOUR_AGO: "המטלה הוצגה לפני 1 שעה",
		TODO_VIEWED_1_MINUTE_AGO: "המטלה הוצגה לפני 1 דקה",
		TODO_VIEWED_1_SECOND_AGO: "המטלה הוצגה לפני 1 שנייה",
		TODO_VIEWED_AT_DATE: "המטלה הוצגה ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "הסקר הוצג היום",
		SURVEY_VIEWED_YESTERDAY: "הסקר הוצג אתמול",
		SURVEY_VIEWED_HOURS_AGO: "הסקר הוצג לפני ${hours} שעות",
		SURVEY_VIEWED_MINUTES_AGO: "הסקר הוצג לפני ${minutes} דקות",
		SURVEY_VIEWED_SECONDS_AGO: "הסקר הוצג לפני ${seconds} שניות",
		SURVEY_VIEWED_1_HOUR_AGO: "הסקר הוצג לפני 1 שעה",
		SURVEY_VIEWED_1_MINUTE_AGO: "הסקר הוצג לפני 1 דקה",
		SURVEY_VIEWED_1_SECOND_AGO: "הסקר הוצג לפני 1 שנייה",
		SURVEY_VIEWED_AT_DATE: "הסקר הוצגd ${date}",
		//Survey
		GENERIC_VIEWED_TODAY: "הוצג היום",
		GENERIC_VIEWED_YESTERDAY: "הוצג אתמול",
		GENERIC_VIEWED_HOURS_AGO: "הוצג לפני ${hours} שעות",
		GENERIC_VIEWED_MINUTES_AGO: "הוצג לפני ${minutes} דקות",
		GENERIC_VIEWED_SECONDS_AGO: "הוצג לפני ${seconds} שניות",
		GENERIC_VIEWED_1_HOUR_AGO: "הוצג לפני 1 שעה",
		GENERIC_VIEWED_1_MINUTE_AGO: "הוצג לפני 1 דקה",
		GENERIC_VIEWED_1_SECOND_AGO: "הוצג לפני 1 שנייה",
		GENERIC_VIEWED_AT_DATE: "הוצג ${date}"
});

