/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Szűrés alapja:",
		"SHOW":"Megjelenítés:",
		"ACL_FILTER_LABEL":"Szűrés láthatóság szerint",
		"PARENT_FILTER_LABEL":"Szűrés tároló szerint",
		"TYPE_FILTER_LABEL":"Szűrés típus szerint",
		"PAGING_TOP":"Elsődleges lapozás",
		"PAGING_BOTTOM":"Másodlagos lapozás",
		"PREVIOUS":"Előző",
		"NEXT":"Következő",
		"PAGE":"{0} / {1} oldal",
		"PAGE_COLON":"Oldal:",
		"RESULTS":"{span}{0}-{1}{/span} / {2}",
		"ITEMS":"{0} elem",
		/* Application names */
		"ACTIVITIES":"Tevékenységek",
		"BLOGS":"Blogok",
		"CALENDAR":"Naptár",
		"COMMUNITIES":"Közösségek",
		"BOOKMARKS":"Könyvjelzők",
		"DOGEAR":"Könyvjelzők",
		"EVENTS":"Események",
		"FILES":"Fájlok",
		"FORUMS":"Fórumok",
		"PROFILES":"Profilok",
		"WIKI":"Wikik",
		"WIKIS":"Wikik",
		"FEEDS":"Hírfolyamok",
		"STATUS_UPDATES":"Állapotfrissítések",
		"ONECOMMENT":"1 megjegyzés",
		"COMMENTS":"{0} megjegyzés",
		"ONEPERSON":"1 személy",
		"PEOPLE":"{0} személy",
		"TAGS":"Címkék:",
		"TAGSMORE":"és {0} másik",
		"NORESULTSMESSAGE":"Nincs találat a keresésre",
		"JAN":"Január",
		"FEB":"Február",
		"MAR":"Március",
		"APR":"Április",
		"MAY":"Május",
		"JUN":"Június",
		"JUL":"Július",
		"AUG":"Augusztus",
		"SEP":"Szeptember",
		"OCT":"Október",
		"NOV":"November",
		"DEC":"December",
		"NO_CONTACT":"A keresés végrehajtására nem került sor, mert a szervert nem lehetett elérni",
		"SERVER_ERROR":"A keresés végrehajtására a szerver hibája miatt nem került sor.",
		"SORT_BY":"Rendezés alapja:",
		"SORT_RELEVANCE":"Helytállóság",
		"SORT_DATE":"Dátum",
		"SORT_LAST_UPDATED":"Legutóbbi frissítés",
		"SORT_DUE_DATE":"Határidő",
		"SORT_VISITS":"Látogatások",
		"SORT_COMMENTS":"Megjegyzések",
		"SORT_RECOMMENDATION":"Kedvelések",
		"SORT_POPULARITY":"Népszerűség",
		"SORT_FIRSTNAME":"Keresztnév",
		"SORT_LASTNAME":"Vezetéknév",
		"SORT_DOWNLOADS":"Letöltések",
		"SORT_TYPE":"Típus",
		"SORT_SIZE":"Méret",
		"SORT_TITLE":"Cím",
		"PRIVATE":"Személyes",
		"MODERATED":"Moderált",
		"COMMUNITY_ACTIVITY":"Közösségi tevékenység",
		"COMMUNITY_BLOG":"Közösségi blog",
		"COMMUNITY_FILE":"Közösségi fájl",
		"COMMUNITY_FORUM":"Közösségi fórum",
		"COMMUNITY_WIKI":"Közösségi Wiki",
		"COMMUNITY_FEED":"Közösségi hírfolyam",
		"COMMUNITY_BOOKMARK":"Közösségi könyvjelző",
		"NO_TAG":"Még nincsenek címkék",
		"NO_DATE":"Még nincsenek dátumok",
		"NO_PEOPLE":"Még nincsenek személyek",
		"REMOVE_FILTER_LABEL":"Kattintson ide az eltávolításhoz",
		"REMOVE_FILTER_TITLE":"Eltávolítás",
		"REMOVE_FILTER_TOOLTIP":"Szűrő eltávolítása",
		"COMMENT_ON":"Megjegyzés erre:",
		"EXPAND_COLLAPSE":"Kattintson ide a kibontáshoz/összezáráshoz",
		"EXPAND":"Kibontás",
		"COLLAPSE":"Összezárás",
		"EXPAND_MONTHS_FILTER":"{0}. év hónapszűrőjének kibontása",
		"SORT_RELEVANCE_LABEL":"Kattintson ide a helytállóság szerinti rendezéshez",
		"SORT_DATE_LABEL":"Kattintson ide a dátum szerinti rendezéshez",
		"SORT_UPDATED_LABEL":"Kattintson ide a legutóbbi frissítés szerinti rendezéshez",
		"SORT_DUE_LABEL":"Kattintson ide a határidő szerinti rendezéshez",
		"SORT_VISITS_LABEL":"Kattintson ide a megtekintések száma szerinti rendezéshez",
		"SORT_COMMENTS_LABEL":"Kattintson ide a megjegyzések száma szerinti rendezéshez",
		"SORT_RECOMMENDATIONS_LABEL":"Kattintson ide a kedvelések száma szerinti rendezéshez",
		"SORT_POPULARITY_LABEL":"Kattintson ide a népszerűség szerinti rendezéshez",
		"SORT_FIRST_NAME_LABEL":"Kattintson ide az adott név szerinti rendezéshez",
		"SORT_LAST_NAME_LABEL":"Kattintson ide a vezetéknév szerinti rendezéshez",
		"RATING":"Kedvelések",
		"GRADUATED":"Kiemelt",
		"ONEVOTE":"1 szavazat",
		"VOTES":"{0} szavazat",
		"BOOKMARK_THIS_RESULT":"Megjelölés könyvjelzővel",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (inaktív)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} személy megjelölve könyvjelzővel",
		/* eg from an Activity */
		"FROMANACTIVITY":"tevékenységből",
		"FROMABLOG":"blogból",
		"FROMANIDEATIONBLOG":"Ötletblogból",
		"FROMANEVENT":"eseményből",
		"FROMAFORUM":"fórumból",
		"FROMAWIKI":"wikiből",
		"FROMACOMMUNITY":"közösségből",
		"FROMXCOMMUNITIES":"{0} közösségből",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Tevékenység",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Ötletgyűjtő blog",
		"ENTRY_ALONE":"Bejegyzés",
		"EVENT_ALONE":"Esemény",
		"FORUM_ALONE":"Fórum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Közösség",
		"XCOMMUNITIES_ALONE":"{0} közösség",
		"SHAREDCOMMUNITIES":"Megosztva ezekkel a közösségekkel",
		"INACOMMUNITY":"közösségben",
		"LASTUPDATED":"Keresési index legutóbbi frissítése:",
		"NODESCRIPTION":"Ehhez az eredményhez nem tartozik leírás vagy összegzés.",
		"ATTACHMENT":"Melléklet:",
		"ACTIVITY":"Tevékenység:",
		"ACTIVITYBOOKMARK":"Tevékenység könyvjelző:",
		"ACTIVITYCOMMENT":"Tevékenység megjegyzés:",
		"ACTIVITYENTRY":"Tevékenységbejegyzés:",
		"ACTIVITYSECTION":"Tevékenység szakasz:",
		"ACTIVITYTODO":"Tevékenység tennivaló:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Blogbejegyzés:",
		"BLOGCOMMENT":"Blog megjegyzése:",
		"BOOKMARK":"Könyvjelző:",
		"CALENDAREVENT":"Esemény:",
		"CATEGORY":"Kategória:",
		"COMMENT":"Megjegyzés:",
		"COMMUNITY":"Közösség:",
		"ENTRY":"Bejegyzés:",
		"EVENTDATEON":"Ekkor: {0}",
		"EVENTISALLDAY":"Egész napos esemény",
		"EVENTREPEATS":"Ismétlődés",
		"FEED":"Hírfolyam:",
		"FILE":"Fájl:",
		"FORUM":"Fórum:",
		"FORUMCATEGORY":"Fórum kategória:",
		"FORUMTOPIC":"Fórum témakör:",
		"IDEA":"Ötlet:",
		"IDEACOMMENT":"Ötlet megjegyzése:",
		"IDEATIONBLOG":"Ötletblog:",
		"PAGE":"Oldal:",
		"PROFILE":"Profil:",
		"SECTION":"Szakasz:",
		"STATUSUPDATE":"Állapotfrissítés",
		"STATUSUPDATE_PREFIX":"Állapotfrissítés:",
		"TOPIC":"Téma:",
		"TOPIC_WITH_ATTACHMENT":"Téma",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Wiki oldal:",
		"WIKIFILE":"Wiki melléklet:",
		"SEARCH":"Keresés:",
		"TODO":"Tennivaló:",
		"ALLRESULTS":"Összes találat",
		"PUBLICCONTENT":"Nyilvános tartalom",
		"MYCONTENT":"Saját tartalom",
		"RESULTNOTFOUND":"Nem találta, amit keresett?",
		"TEMPDIFFICULTIES":"Megjegyzés: Ideiglenes indexelési nehézségek miatt a keresése nem tartalmazta a következőt: {0}, amik az elmúlt {1} napon módosultak.",
		"TRYLATER":"Próbálkozzon újra később.",
		"MULTIPLETEMPDIFFICULTIES":"Megjegyzés: Ideiglenes indexelési nehézségek miatt a keresés nem tartalmazta a nemrég módosult következő elemet: {0}",
		"YOUAREAUTHOR":"Ön egy szerző",
		"YOUARECONTRIBUTOR":"Ön egy közreműködő",
		"YOUAREOWNER":"Ön egy tulajdonos",
		"YOUAREMEMBER":"Ön egy tag",
		/* Profiles */
		"MYNETWORK":"Saját hálózat",
		"ALLPEOPLE":"Minden személy",
		"EXCLUDEINACTIVE":"Inaktív személyek kizárása",
		"PHONE":"Telefon:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Minden közösség",
		"PUBLICCOMMUNITIES":"Nyilvános közösségek",
		"MYCOMMUNITIES":"Saját közösségek",
		"EVERYTHINGCOMMUNITIES":"Minden a közösségekből",
		"COMMUNITIESONLY":"Közösségek",
		"COMMUNITIESCONTENT":"Tartalom a közösségekből",
		/* Activities */
		"ALLACTIVITIES":"Minden tevékenység",
		"PUBLICACTIVITIES":"Nyilvános tevékenységek",
		"MYACTIVITIES":"Saját tevékenységek",
		"EVERYTHINGACTIVITIES":"minden a tevékenységekből",
		"ACTIVITIESONLY":"Tevékenységek",
		"SECTIONSACTIVITIES": "Szakaszok a tevékenységekből",
		"ENTRIESACTIVITIES":"Bejegyzések a tevékenységekből",
		"TODOSACTIVITIES":"Tennivalók a tevékenységekből",
		"BOOKMARKSACTIVITIES":"Könyvjelzők a tevékenységekből",
		"FILESACTIVITIES":"Mellékletek a tevékenységekből",
		"ALLTYPESACTIVITIES":"Tevékenységek minden típusa",
		"COMMUNITYACTIVITIES":"Tevékenységek a közösségekből",
		"STANDALONEACTIVITIES":"Önálló tevékenységek",
		/* Forums */
		"ALLFORUMS":"Minden fórum",
		"PUBLICFORUMS":"Nyilvános fórumok",
		"MYFORUMS":"Saját fórumok",
		"EVERYTHINGFORUMS":"Minden a fórumokból",
		"FORUMSONLY":"Fórumok",
		"TOPICSFORUMS":"Fórum témák",
		"FORUMCATEGORIES": "Fórum kategóriák",
		"FILESFORUMS":"Mellékletek a fórumokból",
		"ALLTYPESFORUMS":"Fórumok minden típusa",
		"COMMUNITYFORUMS":"Fórumok a közösségekből",
		"STANDALONEFORUMS":"Önálló fórumok",
		/* Blogs */
		"ALLBLOGS":"Minden blog",
		"PUBLICBLOGS":"Nyilvános blogok",
		"MYBLOGS":"Saját blogok",
		"EVERYTHINGBLOGS":"Minden a blogokból",
		"BLOGSONLY":"Blogok",
		"ENTRIESBLOGS":"Blogbejegyzések",
		"FILESBLOGS":"Mellékletek a blogokból",
		"EVERYTHINGIDEATIONBLOGS":"Minden az ötletblogokból",
		"BLOGSIDEATIONBLOGS":"Ötletblogok",
		"BLOGSIDEAS":"Ötletek",
		"ALLTYPESBLOGS":"Blogok minden típusa",
		"COMMUNITYBLOGS":"Blogok a közösségekből",
		"COMMUNITYIDEATIONBLOGS":"Ötletblogok közösségekből",
		"STANDALONEBLOGS":"Önálló blogok",
		/* Bookmarks */
		"ALLBOOKMARKS":"Minden könyvjelző",
		"PUBLICBOOKMARKS":"Nyilvános könyvjelzők",
		"MYBOOKMARKS":"Saját könyvjelzők",
		"ALLTYPESBOOKMARKS":"Könyvjelzők minden típusa",
		"COMMUNITYBOOKMARKS":"Könyvjelzők a közösségekből",
		"STANDALONEBOOKMARKS":"Önálló könyvjelzők",
		/* Files */
		"ALLFILES":"Összes fájl",
		"PUBLICFILES":"Nyilvános fájlok",
		"MYFILES":"Saját fájlok",
		"ALLTYPESFILES":"Minden fájltípus",
		"COMMUNITYFILES":"Fájlok a közösségekből",
		"STANDALONEFILES":"Önálló fájlok",
		"NUMDOWNLOADS":"{0} letöltés",
		/* Wikis */
		"ALLWIKIS":"minden wiki",
		"PUBLICWIKIS":"Nyilvános wikik",
		"MYWIKIS":"Saját wikik",
		"EVERYTHINGWIKIS":"Minden a wikikből",
		"WIKISONLY":"Wikik",
		"PAGESWIKIS":"Wiki oldalak",
		"FILESWIKIS":"Mellékletek a wikikből",
		"ALLTYPESWIKIS":"Wikik minden típusa",
		"COMMUNITYWIKIS":"Wikik a közösségekből",
		"STANDALONEWIKIS":"Önálló wikik",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Minden állapotfrissítés",
		"PUBLICSTATUSUPDATES":"Nyilvános állapotfrissítések",
		"MYSTATUSUPDATES":"Saját állapotfrissítések",
		"ALLTYPESSTATUSUPDATES":"Minden típusú állapotfrissítés",
		"COMMUNITYSTATUSUPDATES":"Közösségek állapotfrissítései",
		"STANDALONESTATUSUPDATES":"Profilok állapotfrissítései",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Ezt az URL címet több felhasználó hozzáadta a könyvjelzőkhöz",
		"BOOKMARKEDCOMMUNITY":"Ezt a közösséget több felhasználó hozzáadta a könyvjelzőkhöz",
		"BOOKMARKEDPROFILE":"Ezt a profilt több felhasználó hozzáadta a könyvjelzőkhöz",
		"BOOKMARKEDBLOG":"Ezt a blogot több felhasználó hozzáadta a könyvjelzőkhöz",
		"COMMUNITYBLOG":"Ez egy blog egy közösségen belül",
		"BOOKMARKEDACTIVITY":"Ezt a tevékenységet több felhasználó hozzáadta a könyvjelzőkhöz",
		"COMMUNITYACTIVITY":"Ez egy tevékenység egy közösségen belül",
		"BOOKMARKEDFILE":"Ezt a fájlt több felhasználó hozzáadta a könyvjelzőkhöz",
		"COMMUNITYFILE":"Ez egy fájl egy közösségen belül",
		"BOOKMARKED":"Ezt a wikit több felhasználó hozzáadta a könyvjelzőkhöz",
		"COMMUNITYWIKI":"Ez egy wiki egy közösségen belül",
		"BOOKMARKEDFORUM":"Ezt a fórumot több felhasználó hozzáadta a könyvjelzőkhöz",
		"COMMUNITYFORUM":"Ez egy fórum egy közösségen belül",
		"ALLTAGANDTTILE":"Az URL címhez megadott összes cím és címke megtekintéséhez kattintson erre a gombra",
		"TAGS_ARE_FROM":"A keresési eredmény innen tartalmazhat címkéket:",
		"BOOKMARKS_TITLE":"Könyvjelzők",
		"COMMUNITIES_TITLE":"Közösségek",
		"ACTIVITIES_TITLE":"Tevékenységek",
		"HELP":"Súgó",
		"MORESTATUSUPDATES":"További állapotfrissítés-egyezések megtekintése",
		"TITLE_PREFIX":"cím:",
		"LATEST_MESSAGE":"Legújabb üzenet",
		"LATEST_STATUS_UPDATE":"Legutóbbi állapotfrissítés",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Legutóbbi közösségi állapotfrissítés",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Legutóbbi közösségi állapotfrissítés",
		"SEARCH_RESULTS":"Teljes tartalom keresési eredményei",
		"ACTIVITIES_SEARCH_RESULTS":"Tevékenységek keresési eredményei",
		"BLOGS_SEARCH_RESULTS":"Blogok keresési eredményei",
		"BOOKMARKS_SEARCH_RESULTS":"Könyvjelzők keresési eredményei",
		"COMMUNITIES_SEARCH_RESULTS":"Közösségek keresési eredményei",
		"FILES_SEARCH_RESULTS":"Fájlok keresési eredményei",
		"FORUMS_SEARCH_RESULTS":"Fórumok keresési eredményei",
		"PROFILES_SEARCH_RESULTS":"Profilok keresési eredményei",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} könyvtár keresési eredményei",
		"WIKIS_SEARCH_RESULTS":"Wiki keresési eredményei",
		"STATUS_UPDATES_SEARCH_RESULTS":"Állapotfrissítések keresési eredményei",
		"VIEW_ALL":"{span}Összes megjelenítése{/span} ({0})",
		"MATCHING_ONE_OF":"Egyezés a következők közül valamelyikkel:",
		"MATCHING_ALL_OF":"Egyezés a következők mindegyikével:",
		"MATCHING":"Egyezés:",
		"MATCHING_DOC_TYPE":"Egyező dokumentumtípus:",
		"BOOKMARK_HELP":"Könyvjelző súgó",
		"CLOSE_BOOKMARK_HELP":"Könyvjelző súgójának bezárása",
		"DOCUMENT_TYPE_PREFIX":"Dokumentumtípus:",
		"LAST_PAGE_MESSAGE": "Túl sok keresési eredmény. Próbálja meg szűkíteni a keresést további keresési kifejezések hozzáadásával.",
		"LAST_PAGE_SUBMESSAGE": "Az első {resultNumber} releváns eredményt kapta meg."
});

