define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Tanca",
		   'rs_loading' : "S'està carregant...",
		   'rs_at' : "a",
		   'rs_searchDirectory' : "No està inclosa aquesta persona a la llista? Utilitzeu la cerca completa...",
		   'rs_searchGroupDirectory' : "El grup no està inclòs a la llista? Utilitzeu la cerca completa...",
		   'rs_searchPersonAndGroupDirectory' : "La persona o el grup no estan inclosos a la llista? Utilitzeu la cerca completa...",
		   'rs_searchCommunityDirectory' : "No està inclosa aquesta comunitat a la llista? Utilitzeu la cerca completa...",
		   'rs_shadowText_searchDirectory' : "Escriviu per cercar una persona",
		   'rs_shadowText_searchGroupDirectory' : "Escriviu per cercar un grup",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Escriviu per cercar una persona o grup",
		   'rs_shadowText_searchCommunityDirectory' : "Escriviu per cercar una comunitat",
		   'rs_listItem' : "Element de llista",
		   'rs_noResults' : "No hi ha cap resultat per a '${0}'",
		   'rs_today' : "Avui",
		   'rs_tomorrow' : "Demà",
		   'rs_yesterday' : "Ahir",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Canal d'informació per a aquestes activitats",
		   'rs_externalText' : "Aquesta activitat pot tenir membres externs a l'organització",
		   'rs_moveActivitySuccess' : 'S\'ha mogut correctament \"${activityTitle}\" a la subcomunitat \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Mostra més informació sobre aquesta activitat',
		   'rs_hideInfo' : 'Oculta la informació addicional',
		   'rs_more' : "Més",
		   'rs_hide' : "Oculta",
		   'rs_edit' : "Edita",
		   'rs_restore' : "Restaura",
		   'rs_deleteEntry' : "Suprimeix",
		   'rs_prioritize' : "Prioritza",
		   'rs_markComplete' : "Marca com a complet",
		   'rs_markIncomplete' : "Restaura",
		   'rs_linkMore' : "... [més]",
		   'rs_linkLess' : "... [menys]",
		   'rs_actUpdatedByDate' : "Actualitzat per ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Actualitzat per ${0}",// Updated by (author name)
		   'rs_actDue' : "Venç ${0}",// Due (date)
		   'rs_actTags' : "Etiquetes: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Inicia activitat des d'aquesta plantilla",
		   'rs_favoriteTemplate' : "Marca com a plantilla preferida",
		   'rs_normalTemplate' : "Marca com a plantilla normal",
		   'rs_tunedOutPri' : "Descartat",
		   'rs_pagepos' : "${0} - ${1} de ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Anterior",
		   'rs_navNextLabel' : "Següent",
		   'rs_noActivities' : "No hi ha cap activitat iniciada per a aquesta comunitat.",
		   'rs_feedError' : "No s'ha pogut carregar el canal d'informació.",
		   'rs_highPri' : "Prioritat alta",
		   'rs_medPri' : "Prioritat mitjana",
		   'rs_normalPri' : "Prioritat normal (valor per defecte)",
		   'rs_tuneOut' : "Marca com a descartat",
		   'rs_startActivity' : "Inicia una activitat",
		   'rs_startFirstActivity' : "Crea la primera activitat",
		   'rs_navNextLabel' : "Següent",
		   'rs_viewAll' : "Visualitza-ho tot",
		   'rs_activityWidgetTitle' : "Activitats",
		   'rs_activityWidgetBriefDescription' : "Feu el seguiment dels objectius de la comunitat.  Creeu tasques a fer i compartiu recursos.",
		   'rs_activityWidgetDescription' : "Les activitats de la comunitat es poden utilitzar per col·laborar i seguir el progrés dels projectes o iniciatives de la comunitat.",
		   'rs_completedActivityLink' : "Mostra activitats completades",
		   'rs_activitiesUnavailable' : "El servei d'Activitats no està disponible.",
		   'rs_errorPersists' : "Si el problema continua, poseu-vos en contacte amb l'administrador del sistema.",
		   'rs_shared' : "Compartides",
		   'rs_removeActFromComm' : "Elimina de la comunitat",
		   'rs_externalLabel' : "Externa",
		   // for ActivityForm
		   'rs_templateOptions' : "Opcions de plantilla",
		   'rs_template' : "Plantilla",
		   'rs_tagsLabel' : "Etiquetes",
		   'rs_peopleLabel' : "Persones",
		   'rs_aboutThisTemplate' : "Quant a aquesta plantilla",
		   'rs_activity' : "Activitat",
		   'rs_copyOf' : "Còpia de ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Objectiu de l'activitat",
		   'rs_noTemplate' : "Cap",
		   'rs_copyActivityMembers' : "Utilitza membres de l'activitat",
		   'rs_copyTemplateMembers' : "Utilitza membres de la plantilla",
		   /* Forum Widget */
		   'rs_noTopics' : "Encara no hi ha cap tema per a aquesta comunitat.",
		   'rs_noTopicsLoggedIn' : "Feu una pregunta, cerqueu idees noves o simplement compartiu les vostres idees.",
		   'rs_postedBy' : "Darrera publicació de",
		   'rs_topics' : "temes",
		   'rs_noTopicsShort' : "Sense temes",
		   'rs_topic' : "tema",
		   'rs_replies' : "respostes",
		   'rs_noReplies' : "Sense respostes",
		   'rs_reply' : "resposta",
		   'rs_startTopic' : "Inicia un tema",
		   'rs_startFirstTopic' : "Inicieu el primer tema",
		   'rs_ok' : "D'acord",
		   'rs_locked' : "[Bloquejat]",
		   'rs_manageForumSetting' : "Gestiona paràmetres de fòrum",
		   'rs_forumSettingCommunityOverviewPage' : "Pàgina Visió general de la comunitat:",
		   'rs_defaultForumList' : "Mostra la llista de fòrums per defecte",
		   'rs_defaultTopicList' : "Mostra la llista de temes per defecte",
		   'rs_forumSettingApplicationView' : "Visualització per defecte d'aplicació de fòrum:",
		   'rs_forumSettingNote' : "Nota: els temes es mostren per defecte si només hi ha un fòrum.",
		   'rs_forumSettingSubmit' : "Tramet",
		   'rs_forumSettingSave' : "Desa",
		   'rs_forumSettingSaveAndClose' : "Desa i tanca",
		   'rs_forumSettingConfirm' : "Els vostres canvis als fòrums s'han desat.",
		   'rs_forumSettingError' : "S'ha produït un error. Poseu-vos en contacte amb l'administrador.",
		   'rs_formSettingHideMessage' : "Oculta aquest missatge",
		   'rs_forumSettingCancel' : "Cancel·la",
		   'rs_forumAnsweredQuestion' : "Pregunta contestada",
		   'rs_forumUnAnsweredQuestion' : "Pregunta no contestada",
		   'rs_forumSortBy' : "Ordena per:",
		   'rs_forumSortByDate' : "Data",
		   'rs_forumSortByReplies' : "Respostes",
		   'rs_forumSortByTopic' : "Temes",
		   'rs_forumSortByTopicsAndReplies' : "Temes i respostes",
		   'rs_sortByReplies' : "Ordena per respostes",
		   'rs_sortbyTopicsAndReplies' : "Ordena per temes i respostes",
		   'rs_forumOpenQuestions' : "Preguntes obertes",
		   'rs_feedOpenQuestions' : "Canal d'informació per a aquestes preguntes obertes",
		   'rs_feedAnsweredQuestions' : "Canal d'informació per a aquestes preguntes contestades",
		   'rs_forumMessages' : "${0} missatges",
		   'rs_forumLastAddedPost' : "Darrera publicació de ${0}",
		   'rs_forumTopics' : "${0} temes",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Crea enllaç de persona",
		   'rs_quote' : "Cita",
		   'rs_labelColon' : "Etiqueta: ",
		   'rs_personColon' : "Persona: ",
		   'rs_personLink' : "Enllaç de persona",
		   'rs_replace' : "Substitueix",
		   'rs_inactivePerson' : "${0} (inactiu)", // person's name (inactive)
		   'rs_PersonPicture' : "Imatge de ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Usuari extern", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (Usuari extern)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Imatge de ${0} (Usuari extern)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Aquest usuari té accés a Fitxers i Comunitats que es comparteixen externament.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Notifica altres persones",
		   'rs_messageColon' : "Missatge: ",
		   'rs_notifyColon' : "Notifica: ",
		   'rs_notificationConfirm' : "El missatge de notificació s'ha enviat satisfactòriament. ",
		   'rs_notificationFail' : "El missatge de notificació no s'ha enviat. Torneu-ho a provar més tard i poseu-vos en contacte amb l'administrador del sistema si el problema persisteix.",
		   'rs_pickCommunity' : "Selecciona de la llista de comunitats",
		   'rs_typeName' : "Escriviu un nom",
		   'rs_typeToFilter' : "Escriviu per filtrar aquesta llista",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Escriviu per filtrar aquesta llista",
		   'rs_filterGroupLabel' : "Selecciona grup",
		   'rs_noResults' : "No s'ha trobat cap resultat",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "S'estan mostrant ${0} resultats de ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Elimina",
		   /* Language Selector */
		   'rs_browser_setting' : "Valor de navegador",
		   'rs_customLangaugeLinkLabel' : "Idioma personalitzat",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Salta a la pàgina ${0} de ${1}",
		   "rs_jumpPageLabel" : "Salta a pàgina",
		   'rs_pageNumLabel' : "Número de pàgina",
		   'rs_pageLabel' : "Pàgina:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Etiquetes',
		   'rs_tagCloudToggleHint' : "Feu clic per ocultar o mostrar",
		   'rs_tagCloudHelpAlt' : "Obtingueu ajuda amb etiquetes",
		   'rs_tagCloudNoTags' : "Encara no hi ha cap etiqueta.",
		   'rs_tagCloudNoRecentTags' : "No hi ha cap etiqueta recent",
		   'rs_tagCloudNoTagsProfiles' : "Cerca al directori. Les etiquetes associades als perfils tornats per la cerca es mostraran aquí.",
		   'rs_tagLoadingTags' : "Carregant contingut",
		   'rs_tagCloudSelectedTags' : "Etiquetes seleccionades",
		   'rs_tagCloudSeachDesc' : "Cerca una etiqueta",
		   'rs_tagCloudSeach' : "Cerca",
		   'rs_tagCloudRelatedTags' : "Etiquetes relacionades",
		   'rs_tagCloudRelatedTagsDescription' : "Afegiu una etiqueta relacionada per afinar més la vostra cerca",
		   'rs_tagCloudError' : 'S\'ha produït un error',
		   'rs_viewAsCloud' : "Núvol",
		   'rs_viewAsCloudTitle' : "Llista etiquetes com a grup d'etiquetes",
		   'rs_viewAsCloudDescription' : "Visualitzant etiquetes com a núvol d'etiquetes",
		   'rs_viewAsList' : "Llista",
		   'rs_viewAsListTitle' : "Llista etiquetes com a llista seqüencial d'etiquetes",
		   'rs_viewAsListDescription' : "Visualitzant etiquetes com a llista seqüencial d'etiquetes",
		   'rs_tagCloudViewAll' : "Navega",
		   'rs_tagCloudViewAllTitle' : "Navegueu per totes les etiquetes",
		   'rs_normalTags' : "Etiquetes actives",
		   'rs_removeTag' : "Elimineu l'etiqueta de les etiquetes de filtre seleccionades",
		   'rs_clearAll' : "Esborra-ho tot",
		   'rs_searchInputDefault' : "Escriviu per cercar una etiqueta",
		   'rs_searchInputTagSelected' : "Escriviu una altra etiqueta",
		   'rs_relatedTagTitle' : "Mostra els resultats de cerca de l'etiqueta ${0}, recompte ${1}",
		   'rs_removeTagTitle' : "Elimina l'etiqueta ${0} de les etiquetes de filtre seleccionades",
		   'rs_addTagTitle' : "Filtra per l'etiqueta ${0} amb el compte ${1}",
		   'rs_tagDialogCloseTile' : "Tanca",
		   'rs_tagDialogTitle' : "Totes les etiquetes",
		   'rs_tagDialogPageInfo' : "${0} - ${1} de ${2} etiquetes",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Navega per grups",
		   'rs_group_browse_groups_dialog_title' : "Navega per grups",
		   'rs_group_browse_find_groups' : "Troba grups",
		   'rs_group_browse_add_button' : "Afegeix",
		   'rs_group_browse_cancel_button' : "Cancel·la",
		   'rs_group_browse_enter_string' : "Escriviu per cercar grups",
		   'rs_group_browse_group_typeahead_label' : "Escriviu un nom de grup:",
		   'rs_group_browse_group_name' : "Nom de grup:",
		   'rs_group_browse_results_label' : "Seleccioneu un grup coincident:",
		   'rs_group_browse_parent_group_label' : "Us trobeu a:",
		   'rs_group_browse_next_page' : "Pàgina següent",
		   'rs_group_browse_previous' : "Anterior",
		   'rs_group_browse_next' : "Següent",
		   'rs_group_browse_paging' : "Paginació",
		   'rs_group_browse_previous_page' : "Pàgina anterior",
		   'rs_group_browse_group_selected' : "Grup seleccionat:",
		   'rs_group_browse_group_no_groups' : "Aquest grup no conté cap grup",
		   'rs_group_browse_page_info' : "${0} - ${1} de ${2}",
		   'rs_group_browse_page_info_alt' : "Grups coincidents ${0} de ${1} a ${2}",
		   'rs_group_browse_remove_selection' : 'Elimina la selecció de grups imbricats: ${0}',
		   'rs_group_browse_paging' : "Paginació",
		   'rs_member_groups' : "Grups",
		   'rs_member_members' : "Membres",
		   'rs_member_no_results' : "No s'ha trobat cap resultat",
		   'rs_member_remove_group' : "Elimina ${0}",
		   'rs_member_add_to_community' : "Feu clic per afegir un membre",
		   'rs_member_remove_name' : "Feu clic per eliminar un membre",
		   'rs_group_add_to_community' : "Feu clic per afegir un grup",
		   'rs_group_remove_name' : "Feu clic per eliminar un grup",
		   'rs_group_name' : "Nom de grup",
		   'rs_group_role' : "Rol de grup",
		   'rs_warning' : "Advertiment",
		   'rs_a11y_warning' : "Advertiment:",
		   'rs_messagebox_close_btn_title' : "Tanca",
		   'rs_messagebox_close_btn_alt' : "Tanca",
		   'rs_messagebox_error_icon_alt' : "Error",
		   'rs_messagebox_error_a11y_label' : "Error:",
		   'rs_messagebox_warning_icon_alt' : "Advertiment",
		   'rs_messagebox_warning_a11y_label' : "Advertiment:",
		   'rs_messagebox_info_icon_alt' : "Informació",
		   'rs_messagebox_info_a11y_label' : "Informació:",
		   'rs_messagebox_success_icon_alt' : "Correcte",
		   'rs_messagebox_success_a11y_label' : "Correcte:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Insereix enllaç a Fitxers",
		   'rs_docpicker_label' : "Enllaç a Fitxers",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Descarrega ${0}",
		   'rs_docpicker_viewdetails_text' : "Visualitza'n els detalls",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Visualitza detalls de ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Elimina",
		   'rs_attachedfile_filename' : "Imatge ${0}",
		   'rs_feedreader_warning' : "Advertiment: aquest enllaç està pensat per lectors de canals d'informació i és possible que es visualitzi incorrectament al vostre navegador. Feu clic a D'acord per continuar, Cancel·la per torna a la pàgina.",
		   'rs_search' : "Cerca",
		   'rs_all_connections' : "Totes les connexions",
		   'rs_advanced' : "Avançat",
		   'rs_select_scope' : "Selecciona àmbit de cerca",
		   'rs_icfixlayout' : {
		      button_label : "Torna a formatar",
		      dialog_title : "Tornar a formatar el contingut",
		      warning : "Advertiment",
		      reformat_save : "Torna a formatar i desa",
		      save_as_is : "Desa tal qual",
		      cancel : "Cancel·la",
		      warn_layout : "El contingut supera l'amplada màxima de la pantalla.  Voleu modificar automàticament el format perquè encaixi a l'espai disponible?",
		      remember_decision : "Recorda la meva decisió"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "S'ha produït un error en compartir els fitxers seleccionats.",
		   'rs_sharefile_access_denied' : "S'ha suprimit aquest fitxer o ja no està compartit.",
		   'rs_sharefile_invalid_request' : "S'ha produït un error en compartir els fitxers seleccionats.",
		   'rs_sharefile_sharing_intent_restriction' : "El fitxer només es pot compartir dins de la vostra organització.",
		   'rs_sharefile_error_title' : "Error",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'A l\'App Store',
		   'rs_mobileBanner_inGooglePlay' : 'A Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Obre',
		   'rs_mobileBanner_view' : 'Visualitza',
		   'rs_mobileBanner_hide' : 'Oculta',

		   'rs_empty_column_placeholder' : 'Arrossegueu aplicacions aquí.',
		   'rs_widget_loading_error_title' : 'No es pot mostrar el widget',
		   'rs_widget_loading_error_message' : 'Torneu-ho a provar més tard i poseu-vos en contacte amb l\'administrador del sistema si el problema persisteix.',
		   'rs_widgets_loading_error_title' : 'No es poden mostrar els widgets d\'aquesta comunitat.',
		   'rs_widget_misplacement_warning' : 'Aquesta aplicació no encaixa en aquesta columna. Un propietari de comunitat la pot desplaçar a una altra columna o eliminar-la de la pàgina.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'El títol que heu introduït és massa llarga.',
		      empty_new_title : 'El títol que heu especificat no pot estar buit.',
		      default_message : 'No es pot canviar el títol per a aquesta aplicació de ${0}.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Càrrec:  ',
		   'rs_widget_title_change_direction' : 'Canvieu el títol d\'aquesta aplicació de ${0}.',
		   'rs_widget_title_change_title' : 'Canvia el títol',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Convida o afegeix membres",
		   'rs_vmmainContentDesc' : "Convideu membres per donar-los l'oportunitat d'afegir-se a la comunitat. Afegiu membres per incloure'ls automàticament.",
		   'rs_vmtypeAheadLabel' : "Nom o correu electrònic: ",
		   'rs_vmgroupTypeAheadLabel' : "Nom: ",
		   'rs_vmtypeAheadRoleLabel' : " com ",
		   'rs_vmgroupTypeAheadRoleLabel' : " com a Membres ",
		   'rs_vmtaNoResults' : "No s'ha trobat cap resultat.",
		   'rs_vmtaHeader' : "capçalera",
		   'rs_vmaddUser' : "Afegeix",
		   'rs_vmradioSectionTitle' : "Opcions per als membres:",
		   'rs_vmradioOne' : "Envia invitacions per unir-se a la comunitat",
		   'rs_vmradioTwo' : "Afegeix usuaris a la comunitat automàticament",
		   'rs_vmtwistyA' : "Afegeix un Missatge opcional",
		   'rs_vmtwistyB' : "Elimina el text addicional",
		   'rs_vmmessage' : "Missatge:",
		   'rs_vmtextAreaStartText' : "Digueu alguna cosa...",
		   'rs_vmcheckboxLabel' : "Envia'm una còpia",
		   'rs_vmsave' : "Desa",
		   'rs_vminvite' : "Convida",
		   'rs_vmcancel' : "Cancel·la",
		   'rs_userContentTitle' : "Introdueix informació",
		   'rs_vmaddUser' : "Crea usuari",
		   'rs_vmback'	 : "Enrere",
		   'rs_vmvisitor'	 : "Visitant",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Feu clic aquí per copiar aquesta comunitat',
			'rs_commpicker' : ''

});
