/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informacje dla węzła: ",
		"INSTALLED": "Sprawdzanie zainstalowanych usług",
		"RESUMETOKENS": "Sprawdzanie znaczników wznowienia",
		"SEEDLISTS": "Sprawdzanie dostępności list adresów początkowych",
		"CALENDARS": "Sprawdzanie poprawności konfiguracji kalendarzy harmonogramów",
		"VARIABLES": "Sprawdzanie, czy ustawiono zmienne produktu WebSphere",
		"TASKS": "Sprawdzanie włączonych zadań indeksowania",
		"INDEXFILES": "Sprawdzanie folderu indeksu pod kątem wymaganych plików",
		"LOGS": "Przeglądanie dzienników pod kątem błędów",
		"CONFIGFILES": "Przeglądanie plików konfiguracyjnych",
		"DICTIONARIES": "Sprawdzanie liczby włączonych słowników",
		"SYNC": "Sprawdzanie statusu węzłów",
		"DBRECORDS": "Sprawdzanie rekordów bazy danych",
		"INSTALLEDMSG": "Następująca usługa jest zainstalowana: ",
		"RESUMETOKENSMSG": "Znacznik wznowienia dla: ",
		"SEEDLISTSMSG": "Nie można uzyskać listy adresów początkowych dla: ",
		"CALENDARSMSG": "Pomyślnie zakończono sprawdzanie kalendarza harmonogramu: ",
		"VARIABLESMSG": "Zmienna: ",
		"TASKSMSG": "Następujące zadanie jest włączone: ",
		"INDEXFILESMSG" : "Następujące pliki znajdują się w folderze indeksu wyszukiwania: ",
		"LOGSMSG" : "Zapoznaj się z następującymi komunikatami o błędach: ",
		"CONFIGFILESMSG" : "Znaleziono następujące pliki konfiguracyjne: ",
		"DICTIONARIESMSG" : "Liczba włączonych słowników: ",
		"INSYNC": "Wszystkie węzły są zsynchronizowane",
		"OUTOFSYNC": "Liczba niezsynchronizowanych węzłów: ",
		"NOTBLOCKED": "Brak zablokowanych węzłów",
		"BLOCKED": "Liczba zablokowanych węzłów: ",
		"INDATE": "Wszystkie węzły są aktualne",
		"OUTOFDATE": "Liczba nieaktualnych węzłów: ",
		"NUMOFDOCS": "Liczba dokumentów w bazie danych: ",
		"FILESTOCONVERT": "Liczba dokumentów plików do przekształcenia: ",
		"CONVERTEDFILES": "Liczba przekonwertowanych plików: ",
		"TOTALFILES": "Łączna liczba plików w bazie danych: ",
		"ERROR":"Błąd",
		"ERROR_PREFIX":"Błąd:",
		"INFO":"Informacja",
		"INFO_PREFIX":"Informacja:",
		"WARNING":"Ostrzeżenie",
		"WARNING_PREFIX":"Ostrzeżenie:",
		"LOADING_MESSAGE": "Ładowanie",
		"SERVER_STATUS": "Status serwera",
		"INITIAL_INDEXING_EXCEPTIONS": "Wyjątki indeksowania początkowego",
		"SYS_OUT_EXCEPTIONS": "Wyjątki dziennika SystemOut",
		"SEEDLIST_VALIDATE": "Sprawdzanie poprawności listy adresów początkowych",
		"ERRORS_DURING_INITIAL_INDEXING":"Podczas tworzenia indeksu początkowego wystąpiły następujące wyjątki",
		"CRAWL_FAILED": "Nie można przeszukać wszystkich danych dla następującej usługi: ",
		"EXCEPTION_ENCOUNTERED": "Przeszukiwanie nie powiodło się. Zwrócono następujący komunikat: ",
		"SAND_VALIDATE": "Sprawdzanie poprawności usługi SAND",
		"CHECK_FOR_SAND_FILES":"Sprawdzanie plików SAND",
		"IS_FILE_AVAILABLE":"Sprawdzanie, czy plik został utworzony: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Podczas tworzenia indeksu początkowego wystąpiły następujące wyjątki",
		"CRAWL_FAILED":"Nie można przeszukać wszystkich danych dla następującej usługi: ",
		"EXCEPTION_ENCOUNTERED":"Przeszukiwanie nie powiodło się. Zwrócono następujący komunikat: "
});

