/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtruj wg:",
		"SHOW":"Pokaż:",
		"ACL_FILTER_LABEL":"Filtruj wg widoczności",
		"PARENT_FILTER_LABEL":"Filtruj wg kontenera",
		"TYPE_FILTER_LABEL":"Filtruj wg typu",
		"PAGING_TOP":"Podstawowe opcje stronicowania",
		"PAGING_BOTTOM":"Dodatkowe opcje stronicowania",
		"PREVIOUS":"Wstecz",
		"NEXT":"Dalej",
		"PAGE":"Strona {0} z {1}",
		"PAGE_COLON":"Strona:",
		"RESULTS":"{span}{0}–{1}{/span} z {2}",
		"ITEMS":"Liczba pozycji: {0}",
		/* Application names */
		"ACTIVITIES":"Działania",
		"BLOGS":"Blogi",
		"CALENDAR":"Kalendarz",
		"COMMUNITIES":"Społeczności",
		"BOOKMARKS":"Zakładki",
		"DOGEAR":"Zakładki",
		"EVENTS":"Zdarzenia",
		"FILES":"Pliki",
		"FORUMS":"Fora",
		"PROFILES":"Profile",
		"WIKI":"Wiki",
		"WIKIS":"Wiki",
		"FEEDS":"Kanały RSS",
		"STATUS_UPDATES":"Aktualizacje statusów",
		"ONECOMMENT":"1 komentarz",
		"COMMENTS":"Liczba komentarzy: {0}",
		"ONEPERSON":"1 osoba",
		"PEOPLE":"Liczba osób: {0}",
		"TAGS":"Znaczniki:",
		"TAGSMORE":"i jeszcze {0}",
		"NORESULTSMESSAGE":"Nie znaleziono żadnych wyników zgodnych z tymi kryteriami wyszukiwania.",
		"JAN":"styczeń",
		"FEB":"luty",
		"MAR":"marzec",
		"APR":"kwiecień",
		"MAY":"maj",
		"JUN":"czerwiec",
		"JUL":"lipiec",
		"AUG":"sierpień",
		"SEP":"wrzesień",
		"OCT":"październik",
		"NOV":"listopad",
		"DEC":"grudzień",
		"NO_CONTACT":"Nie przeprowadzono wyszukiwania, ponieważ nie można było skontaktować się z serwerem",
		"SERVER_ERROR":"Wyszukiwanie nie zostało przeprowadzone z powodu wystąpienia błędu serwera",
		"SORT_BY":"Sortuj wg:",
		"SORT_RELEVANCE":"Istotność",
		"SORT_DATE":"Data",
		"SORT_LAST_UPDATED":"Ostatnia aktualizacja",
		"SORT_DUE_DATE":"Data zakończenia",
		"SORT_VISITS":"Odwiedziny",
		"SORT_COMMENTS":"Komentarze",
		"SORT_RECOMMENDATION":"Polubienia",
		"SORT_POPULARITY":"Popularność",
		"SORT_FIRSTNAME":"Imię",
		"SORT_LASTNAME":"Nazwisko",
		"SORT_DOWNLOADS":"Pobrania",
		"SORT_TYPE":"Typ",
		"SORT_SIZE":"Wielkość",
		"SORT_TITLE":"Tytuł",
		"PRIVATE":"Prywatne",
		"MODERATED":"Moderowane",
		"COMMUNITY_ACTIVITY":"Działanie społeczności",
		"COMMUNITY_BLOG":"Blog społeczności",
		"COMMUNITY_FILE":"Plik społeczności",
		"COMMUNITY_FORUM":"Forum społeczności",
		"COMMUNITY_WIKI":"Wiki społeczności",
		"COMMUNITY_FEED":"Kanał RSS społeczności",
		"COMMUNITY_BOOKMARK":"Zakładka społeczności",
		"NO_TAG":"Nie ma jeszcze znaczników",
		"NO_DATE":"Nie ma jeszcze dat",
		"NO_PEOPLE":"Nie ma jeszcze osób",
		"REMOVE_FILTER_LABEL":"Kliknij, aby usunąć",
		"REMOVE_FILTER_TITLE":"Usuń",
		"REMOVE_FILTER_TOOLTIP":"Usuń ten filtr",
		"COMMENT_ON":"Skomentowano:",
		"EXPAND_COLLAPSE":"Kliknij, aby rozwinąć/zwinąć",
		"EXPAND":"Rozwiń",
		"COLLAPSE":"Zwiń",
		"EXPAND_MONTHS_FILTER":"Rozwiń filtr miesięcy roku {0}",
		"SORT_RELEVANCE_LABEL":"Kliknij, aby posortować według istotności",
		"SORT_DATE_LABEL":"Kliknij, aby posortować według daty",
		"SORT_UPDATED_LABEL":"Kliknij, aby posortować według ostatniej aktualizacji",
		"SORT_DUE_LABEL":"Kliknij, aby posortować według daty zakończenia",
		"SORT_VISITS_LABEL":"Kliknij, aby posortować według liczby odwiedzin",
		"SORT_COMMENTS_LABEL":"Kliknij, aby posortować według liczby komentarzy",
		"SORT_RECOMMENDATIONS_LABEL":"Kliknij, aby posortować według liczby polubień",
		"SORT_POPULARITY_LABEL":"Kliknij, aby posortować według popularności",
		"SORT_FIRST_NAME_LABEL":"Kliknij, aby posortować według imion",
		"SORT_LAST_NAME_LABEL":"Kliknij, aby posortować według nazwisk",
		"RATING":"Polubienia",
		"GRADUATED":"Awansowane",
		"ONEVOTE":"1 głos",
		"VOTES":"Liczba głosów: {0}",
		"BOOKMARK_THIS_RESULT":"Utwórz zakładkę",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (nieaktywny użytkownik)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"Liczba osób oznaczonych zakładką: {0}",
		/* eg from an Activity */
		"FROMANACTIVITY":"z działania",
		"FROMABLOG":"z bloga",
		"FROMANIDEATIONBLOG":"z bloga pomysłów",
		"FROMANEVENT":"ze zdarzenia",
		"FROMAFORUM":"z forum",
		"FROMAWIKI":"z wiki",
		"FROMACOMMUNITY":"ze społeczności",
		"FROMXCOMMUNITIES":"z {0} społeczności",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Działanie",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog pomysłów",
		"ENTRY_ALONE":"Wpis",
		"EVENT_ALONE":"Zdarzenie",
		"FORUM_ALONE":"Forum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Społeczność",
		"XCOMMUNITIES_ALONE":"{0} społeczności",
		"SHAREDCOMMUNITIES":"Udostępnione do współużytkowania dla tych społeczności",
		"INACOMMUNITY":"w społeczności",
		"LASTUPDATED":"Data ostatniej aktualizacji indeksu wyszukiwania:",
		"NODESCRIPTION":"Brak opisu lub podsumowania dla tego wyniku.",
		"ATTACHMENT":"Załącznik:",
		"ACTIVITY":"Działanie:",
		"ACTIVITYBOOKMARK":"Zakładka działania:",
		"ACTIVITYCOMMENT":"Komentarz dotyczący działania:",
		"ACTIVITYENTRY":"Wpis działania:",
		"ACTIVITYSECTION":"Sekcja działania:",
		"ACTIVITYTODO":"Czynność do wykonania działania:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Wpis w blogu:",
		"BLOGCOMMENT":"Komentarz w blogu:",
		"BOOKMARK":"Zakładka:",
		"CALENDAREVENT":"Zdarzenie:",
		"CATEGORY":"Kategoria:",
		"COMMENT":"Komentarz:",
		"COMMUNITY":"Społeczność:",
		"ENTRY":"Wpis:",
		"EVENTDATEON":"W dniu: {0}",
		"EVENTISALLDAY":"Zdarzenie całodniowe",
		"EVENTREPEATS":"Powtarzanie",
		"FEED":"Kanał RSS:",
		"FILE":"Plik:",
		"FORUM":"Forum:",
		"FORUMCATEGORY":"Kategoria forum:",
		"FORUMTOPIC":"Wątek forum:",
		"IDEA":"Pomysł:",
		"IDEACOMMENT":"Komentarz dotyczący pomysłu:",
		"IDEATIONBLOG":"Blog pomysłów:",
		"PAGE":"Strona:",
		"PROFILE":"Profil:",
		"SECTION":"Sekcja:",
		"STATUSUPDATE":"Aktualizacja statusu",
		"STATUSUPDATE_PREFIX":"Aktualizacja statusu:",
		"TOPIC":"Wątek:",
		"TOPIC_WITH_ATTACHMENT":"Wątek",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Strona wiki:",
		"WIKIFILE":"Załącznik wiki:",
		"SEARCH":"Wyszukiwanie:",
		"TODO":"Czynność do wykonania:",
		"ALLRESULTS":"Wszystkie wyniki",
		"PUBLICCONTENT":"Treść publiczna",
		"MYCONTENT":"Moja treść",
		"RESULTNOTFOUND":"Czy nie znaleziono tego, czego szukano?",
		"TEMPDIFFICULTIES":"Uwaga: Z powodu tymczasowych trudności z indeksowaniem w wynikach wyszukiwania nie uwzględniono elementów {0}, które zostały zmienione przez ostatnie {1} dn.",
		"TRYLATER":"Spróbuj ponownie później.",
		"MULTIPLETEMPDIFFICULTIES":"Uwaga: Z powodu tymczasowych trudności z indeksowaniem w wynikach wyszukiwania nie uwzględniono elementów ({0}), które zostały ostatnio zmienione.",
		"YOUAREAUTHOR":"Jesteś autorem",
		"YOUARECONTRIBUTOR":"Jesteś kontrybutorem",
		"YOUAREOWNER":"Jesteś właścicielem",
		"YOUAREMEMBER":"Jesteś członkiem",
		/* Profiles */
		"MYNETWORK":"Moja sieć",
		"ALLPEOPLE":"Wszystkie osoby",
		"EXCLUDEINACTIVE":"Wyklucz nieaktywne osoby",
		"PHONE":"Telefon:",
		"EMAIL":"Adres e-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Wszystkie społeczności",
		"PUBLICCOMMUNITIES":"Społeczności publiczne",
		"MYCOMMUNITIES":"Moje społeczności",
		"EVERYTHINGCOMMUNITIES":"Wszystko ze społeczności",
		"COMMUNITIESONLY":"Społeczności",
		"COMMUNITIESCONTENT":"Treść ze społeczności",
		/* Activities */
		"ALLACTIVITIES":"Wszystkie działania",
		"PUBLICACTIVITIES":"Działania publiczne",
		"MYACTIVITIES":"Moje działania",
		"EVERYTHINGACTIVITIES":"Wszystko z działań",
		"ACTIVITIESONLY":"Działania",
		"SECTIONSACTIVITIES": "Sekcje z działań",
		"ENTRIESACTIVITIES":"Wpisy z działań",
		"TODOSACTIVITIES":"Czynności do wykonania z działań",
		"BOOKMARKSACTIVITIES":"Zakładki z działań",
		"FILESACTIVITIES":"Załączniki z działań",
		"ALLTYPESACTIVITIES":"Wszystkie typy działań",
		"COMMUNITYACTIVITIES":"Działania ze społeczności",
		"STANDALONEACTIVITIES":"Działania autonomiczne",
		/* Forums */
		"ALLFORUMS":"Wszystkie fora",
		"PUBLICFORUMS":"Fora publiczne",
		"MYFORUMS":"Moje fora",
		"EVERYTHINGFORUMS":"Wszystko z forów",
		"FORUMSONLY":"Fora",
		"TOPICSFORUMS":"Wątki forum",
		"FORUMCATEGORIES": "Kategorie forum",
		"FILESFORUMS":"Załączniki z forów",
		"ALLTYPESFORUMS":"Wszystkie typy forów",
		"COMMUNITYFORUMS":"Fora ze społeczności",
		"STANDALONEFORUMS":"Fora autonomiczne",
		/* Blogs */
		"ALLBLOGS":"Wszystkie blogi",
		"PUBLICBLOGS":"Blogi publiczne",
		"MYBLOGS":"Moje blogi",
		"EVERYTHINGBLOGS":"Wszystko z blogów",
		"BLOGSONLY":"Blogi",
		"ENTRIESBLOGS":"Wpisy w blogu",
		"FILESBLOGS":"Załączniki z blogów",
		"EVERYTHINGIDEATIONBLOGS":"Wszystko z blogów pomysłów",
		"BLOGSIDEATIONBLOGS":"Blogi pomysłów",
		"BLOGSIDEAS":"Pomysły",
		"ALLTYPESBLOGS":"Wszystkie typy blogów",
		"COMMUNITYBLOGS":"Blogi ze społeczności",
		"COMMUNITYIDEATIONBLOGS":"Blogi pomysłów ze społeczności",
		"STANDALONEBLOGS":"Blogi autonomiczne",
		/* Bookmarks */
		"ALLBOOKMARKS":"Wszystkie zakładki",
		"PUBLICBOOKMARKS":"Publiczne zakładki",
		"MYBOOKMARKS":"Moje zakładki",
		"ALLTYPESBOOKMARKS":"Wszystkie typy zakładek",
		"COMMUNITYBOOKMARKS":"Zakładki ze społeczności",
		"STANDALONEBOOKMARKS":"Zakładki autonomiczne",
		/* Files */
		"ALLFILES":"Wszystkie pliki",
		"PUBLICFILES":"Publiczne pliki",
		"MYFILES":"Moje pliki",
		"ALLTYPESFILES":"Wszystkie typy plików",
		"COMMUNITYFILES":"Pliki ze społeczności",
		"STANDALONEFILES":"Pliki autonomiczne",
		"NUMDOWNLOADS":"Pobrania: {0}",
		/* Wikis */
		"ALLWIKIS":"Wszystkie wiki",
		"PUBLICWIKIS":"Publiczne wiki",
		"MYWIKIS":"Moje wiki",
		"EVERYTHINGWIKIS":"Wszystko z wiki",
		"WIKISONLY":"Wiki",
		"PAGESWIKIS":"Strony wiki",
		"FILESWIKIS":"Załączniki z wiki",
		"ALLTYPESWIKIS":"Wszystkie typy wiki",
		"COMMUNITYWIKIS":"Wiki ze społeczności",
		"STANDALONEWIKIS":"Autonomiczne wiki",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Wszystkie aktualizacje statusów",
		"PUBLICSTATUSUPDATES":"Publiczne aktualizacje statusów",
		"MYSTATUSUPDATES":"Moje aktualizacje statusów",
		"ALLTYPESSTATUSUPDATES":"Wszystkie typy aktualizacji statusów",
		"COMMUNITYSTATUSUPDATES":"Aktualizacje statusów ze społeczności",
		"STANDALONESTATUSUPDATES":"Aktualizacje statusów z profili",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Kilku użytkowników utworzyło zakładkę do tego adresu URL",
		"BOOKMARKEDCOMMUNITY":"Kilku użytkowników utworzyło zakładkę do tej społeczności",
		"BOOKMARKEDPROFILE":"Kilku użytkowników utworzyło zakładkę do tego profilu",
		"BOOKMARKEDBLOG":"Kilku użytkowników utworzyło zakładkę do tego bloga",
		"COMMUNITYBLOG":"To jest blog w ramach społeczności",
		"BOOKMARKEDACTIVITY":"Kilku użytkowników utworzyło zakładkę do tego działania",
		"COMMUNITYACTIVITY":"To jest działanie w ramach społeczności",
		"BOOKMARKEDFILE":"Kilku użytkowników utworzyło zakładkę do tego pliku",
		"COMMUNITYFILE":"To jest plik w ramach społeczności",
		"BOOKMARKED":"Kilku użytkowników utworzyło zakładkę do tego wiki",
		"COMMUNITYWIKI":"To jest wiki w ramach społeczności",
		"BOOKMARKEDFORUM":"Kilku użytkowników utworzyło zakładkę do tego forum",
		"COMMUNITYFORUM":"To jest forum w ramach społeczności",
		"ALLTAGANDTTILE":"Kliknij ten przycisk, aby wyświetlić wszystkie tytuły i znaczniki dla tego adresu URL",
		"TAGS_ARE_FROM":"Te wyniki wyszukiwania mogą uwzględniać znaczniki z komponentów:",
		"BOOKMARKS_TITLE":"Zakładki",
		"COMMUNITIES_TITLE":"Społeczności",
		"ACTIVITIES_TITLE":"Działania",
		"HELP":"Pomoc",
		"MORESTATUSUPDATES":"Wyświetl więcej zgodności aktualizacji statusu",
		"TITLE_PREFIX":"tytuł:",
		"LATEST_MESSAGE":"Najnowsza wiadomość",
		"LATEST_STATUS_UPDATE":"Najnowsza aktualizacja statusu",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Najnowsza aktualizacja statusu społeczności",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Najnowsza aktualizacja statusu społeczności",
		"SEARCH_RESULTS":"Wyniki wyszukiwania w całej treści",
		"ACTIVITIES_SEARCH_RESULTS":"Wyniki wyszukiwania działań",
		"BLOGS_SEARCH_RESULTS":"Wyniki wyszukiwania blogów",
		"BOOKMARKS_SEARCH_RESULTS":"Wyniki wyszukiwania zakładek",
		"COMMUNITIES_SEARCH_RESULTS":"Wyniki wyszukiwania społeczności",
		"FILES_SEARCH_RESULTS":"Wyniki wyszukiwania plików",
		"FORUMS_SEARCH_RESULTS":"Wyniki wyszukiwania forów",
		"PROFILES_SEARCH_RESULTS":"Wyniki wyszukiwania profili",
		"DIRECTORY_SEARCH_RESULTS":"Wyniki wyszukiwania w katalogu organizacji ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Wyniki wyszukiwania wiki",
		"STATUS_UPDATES_SEARCH_RESULTS":"Wyniki wyszukiwania aktualizacji statusów",
		"VIEW_ALL":"{span}Wyświetl wszystko{/span} ({0})",
		"MATCHING_ONE_OF":"Zgodne z jednym:",
		"MATCHING_ALL_OF":"Zgodne ze wszystkimi:",
		"MATCHING":"Zgodne:",
		"MATCHING_DOC_TYPE":"Zgodne z typem dokumentu:",
		"BOOKMARK_HELP":"Pomoc do zakładek",
		"CLOSE_BOOKMARK_HELP":"Zamknij pomoc do zakładek",
		"DOCUMENT_TYPE_PREFIX":"Typ dokumentu:",
		"LAST_PAGE_MESSAGE": "Znaleziono wiele wyników wyszukiwania. Spróbuj zawęzić wyszukiwanie, dodając więcej wyszukiwanych terminów.",
		"LAST_PAGE_SUBMESSAGE": "Wyświetlono pierwsze {resultNumber} pasujących wyników."
});

