/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Филтрирај според:",
"SHOW":"Покажи:",
"ACL_FILTER_LABEL":"Филтрирај според видливост",
"PARENT_FILTER_LABEL":"Филтрирај според контејнер",
"TYPE_FILTER_LABEL":"Филтрирај според тип",
"PAGING_TOP":"Примарно нумерирање страници",
"PAGING_BOTTOM":"Секундарно нумерирање страници",
"PREVIOUS":"Претходно",
"NEXT":"Следно",
"PAGE":"Страница {0} од {1}",
"PAGE_COLON":"Страница:",
"RESULTS":"{span}{0}-{1}{/span} од {2}",
"ITEMS":"{0} ставки",
/* Application names */
"ACTIVITIES":"Активности",
"BLOGS":"Блогови",
"CALENDAR":"Календар",
"COMMUNITIES":"Заедници",
"BOOKMARKS":"Обележувачи",
"DOGEAR":"Обележувачи",
"EVENTS":"Настани",
"FILES":"Датотеки",
"FORUMS":"Форуми",
"PROFILES":"Профили",
"WIKI":"Wikis?",
"WIKIS":"Wikis?",
"FEEDS":"Навестување на содржина",
"STATUS_UPDATES":"Ажурирања на статусот",
"ONECOMMENT":"1 коментар",
"COMMENTS":"{0} коментари",
"ONEPERSON":"1 лице",
"PEOPLE":"{0} лица",
"TAGS":"Ознаки:",
"TAGSMORE":"и уште {0}",
"NORESULTSMESSAGE":"Не се пронајдени резултати за тоа пребарување.",
"JAN":"Јануари",
"FEB":"Февруари",
"MAR":"Март",
"APR":"Април",
"MAY":"Мај",
"JUN":"Јуни",
"JUL":"Јули",
"AUG":"Август",
"SEP":"Септември",
"OCT":"Октомври",
"NOV":"Ноември",
"DEC":"Декември",
"NO_CONTACT":"Пребарувањето не се изврши бидејќи не можеше да се контактира со серверот",
"SERVER_ERROR":"Пребарувањето не се изврши поради грешка на серверот",
"SORT_BY":"Сортирај според:",
"SORT_RELEVANCE":"Значење",
"SORT_DATE":"Датум",
"SORT_LAST_UPDATED":"Последно ажурирање",
"SORT_DUE_DATE":"Краен датум",
"SORT_VISITS":"Посети",
"SORT_COMMENTS":"Коментари",
"SORT_RECOMMENDATION":"Допаѓања",
"SORT_POPULARITY":"Популарност",
"SORT_FIRSTNAME":"Име",
"SORT_LASTNAME":"Презиме",
"SORT_DOWNLOADS":"Преземања",
"SORT_TYPE":"Тип",
"SORT_SIZE":"Големина",
"SORT_TITLE":"Наслов",
"PRIVATE":"Приватно",
"MODERATED":"Модерирано",
"COMMUNITY_ACTIVITY":"Активност на заедницата",
"COMMUNITY_BLOG":"Блог на заедницата",
"COMMUNITY_FILE":"Датотека на заедницата",
"COMMUNITY_FORUM":"Форум на заедницата",
"COMMUNITY_WIKI":"Блог на Wiki",
"COMMUNITY_FEED":"Навестување на содржината на заедницата",
"COMMUNITY_BOOKMARK":"Ознака на заедницата",
"NO_TAG":"Уште нема ознаки",
"NO_DATE":"Уште нема датуми",
"NO_PEOPLE":"Уште нема луѓе",
"REMOVE_FILTER_LABEL":"Кликни за да се отстрани",
"REMOVE_FILTER_TITLE":"Отстрани",
"REMOVE_FILTER_TOOLTIP":"Отстрани го филтерот",
"COMMENT_ON":"Коментирај на:",
"EXPAND_COLLAPSE":"Кликни за проширување/собирање",
"EXPAND":"Прошири",
"COLLAPSE":"Собери",
"EXPAND_MONTHS_FILTER":"Прошири го филтерот за месеците во годината {0}",
"SORT_RELEVANCE_LABEL":"Кликнете за сортирање според важност",
"SORT_DATE_LABEL":"Кликнете за сортирање според датум",
"SORT_UPDATED_LABEL":"Кликнете за сортирање според последно ажурирање",
"SORT_DUE_LABEL":"Кликнете за сортирање според краен датум",
"SORT_VISITS_LABEL":"Кликнете за сортирање според број на посети",
"SORT_COMMENTS_LABEL":"Кликнете за сотирање според број на коментари",
"SORT_RECOMMENDATIONS_LABEL":"Кликнете за сортирање според број на допаѓања",
"SORT_POPULARITY_LABEL":"Кликнете за сортирање според популарност",
"SORT_FIRST_NAME_LABEL":"Кликнете за сортирање според име",
"SORT_LAST_NAME_LABEL":"Кликнете за сортирање според презиме",
"RATING":"Допаѓања",
"GRADUATED":"Градирано",
"ONEVOTE":"1 глас",
"VOTES":"{0} гласови",
"BOOKMARK_THIS_RESULT":"Означи го ова",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (неактивно)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} лица го означија",
/* eg from an Activity */
"FROMANACTIVITY":"од Активност",
"FROMABLOG":"од Блог",
"FROMANIDEATIONBLOG":"од Блог Создавање идеи",
"FROMANEVENT":"од Настан",
"FROMAFORUM":"од Форум",
"FROMAWIKI":"од Wiki",
"FROMACOMMUNITY":"од Заедница",
"FROMXCOMMUNITIES":"од {0} заедници",
/* For search results parentage */
"ACTIVITY_ALONE":"Активност",
"BLOG_ALONE":"Блог",
"IDEATIONBLOG_ALONE":"Блог Создавање идеи",
"ENTRY_ALONE":"Запис",
"EVENT_ALONE":"Настан",
"FORUM_ALONE":"Форум",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Заедница",
"XCOMMUNITIES_ALONE":"{0} заедници",
"SHAREDCOMMUNITIES":"Споделено со овие заедници",
"INACOMMUNITY":"во Заедница",
"LASTUPDATED":"Последно ажурирање на индексот за пребарување:",
"NODESCRIPTION":"Нема опис или резиме за овој резултат.",
"ATTACHMENT":"Прилог:",
"ACTIVITY":"Активност:",
"ACTIVITYBOOKMARK":"Ознака на активност",
"ACTIVITYCOMMENT":"Коментар на активност:",
"ACTIVITYENTRY":"Запис во активност:",
"ACTIVITYSECTION":"Секција на активност:",
"ACTIVITYTODO":"Список со задачи на активност:",
"BLOG":"Блог:",
"BLOGENTRY":"Запис во блог:",
"BLOGCOMMENT":"Коментар на блог:",
"BOOKMARK":"Ознака:",
"CALENDAREVENT":"Настан:",
"CATEGORY":"Категорија:",
"COMMENT":"Коментар:",
"COMMUNITY":"Заедница:",
"ENTRY":"Запис:",
"EVENTDATEON":"На: {0}",
"EVENTISALLDAY":"Целодневен настан",
"EVENTREPEATS":"Повторувања",
"FEED":"Навестување на содржина:",
"FILE":"Датотека:",
"FORUM":"Форум:",
"FORUMCATEGORY":"Категорија на форум:",
"FORUMTOPIC":"Тема на форум:",
"IDEA":"Идеја:",
"IDEACOMMENT":"Коментар на идеја:",
"IDEATIONBLOG":"Блог Создавање идеи:",
"PAGE":"Страница:",
"PROFILE":"Профил:",
"SECTION":"Секција:",
"STATUSUPDATE":"Ажурирање статус",
"STATUSUPDATE_PREFIX":"Ажурирање статус:",
"TOPIC":"Тема:",
"TOPIC_WITH_ATTACHMENT":"Тема",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Страница на Wiki:",
"WIKIFILE":"Прилог на Wiki:",
"SEARCH":"Пребарување:",
"TODO":"Список со задачи:",
"ALLRESULTS":"Сите резултати",
"PUBLICCONTENT":"Јавна содржина",
"MYCONTENT":"Моја содржина",
"RESULTNOTFOUND":"Не го најдовте тоа што го баравте?",
"TEMPDIFFICULTIES":"Забелешка: поради привремени потешкотии со индексирањето, вашето пребарување не ги вклучуваше {0} што беа изменети во последните {1} дена.",
"TRYLATER":"Обидете се повторно подоцна.",
"MULTIPLETEMPDIFFICULTIES":"Забелешка: поради привремени потешкотии со индексирањето, вашето пребарување не ги вклучуваше {0} што беа изменети неодамна.",
"YOUAREAUTHOR":"Вие сте автор",
"YOUARECONTRIBUTOR":"Вие сте соработник",
"YOUAREOWNER":"Вие сте сопственик",
"YOUAREMEMBER":"Вие сте член",
/* Profiles */
"MYNETWORK":"Моја мрежа",
"ALLPEOPLE":"Сите лица",
"EXCLUDEINACTIVE":"Исклучи ги неактивните лица",
"PHONE":"Телефон:",
"EMAIL":"Е-пошта:",
/* Communities */
"ALLCOMMUNITIES":"Сите заедници",
"PUBLICCOMMUNITIES":"Јавни заедници",
"MYCOMMUNITIES":"Мои заедници",
"EVERYTHINGCOMMUNITIES":"Се од заедници",
"COMMUNITIESONLY":"Заедници",
"COMMUNITIESCONTENT":"Содржина од заедници",
/* Activities */
"ALLACTIVITIES":"Сите активности",
"PUBLICACTIVITIES":"Јавни активности",
"MYACTIVITIES":"Мои активности",
"EVERYTHINGACTIVITIES":"Се од активности",
"ACTIVITIESONLY":"Активности",
"SECTIONSACTIVITIES": "Секции од активности",
"ENTRIESACTIVITIES":"Записи од активности",
"TODOSACTIVITIES":"Список со задачи од активности",
"BOOKMARKSACTIVITIES":"Ознаки од активности",
"FILESACTIVITIES":"Прилози од активности",
"ALLTYPESACTIVITIES":"Сите типови активности",
"COMMUNITYACTIVITIES":"Активности од заедниците",
"STANDALONEACTIVITIES":"Самостојни активности",
/* Forums */
"ALLFORUMS":"Сите форуми",
"PUBLICFORUMS":"Јавни форуми",
"MYFORUMS":"Мои форуми",
"EVERYTHINGFORUMS":"Се од форуми",
"FORUMSONLY":"Форуми",
"TOPICSFORUMS":"Теми на форуми",
"FORUMCATEGORIES": "Категории на форуми",
"FILESFORUMS":"Прилози од форуми",
"ALLTYPESFORUMS":"Сите типови форуми",
"COMMUNITYFORUMS":"Форуми од заедниците",
"STANDALONEFORUMS":"Самостојни форуми",
/* Blogs */
"ALLBLOGS":"Сите блогови",
"PUBLICBLOGS":"Јавни блогови",
"MYBLOGS":"Мои блогови",
"EVERYTHINGBLOGS":"Се од блогови",
"BLOGSONLY":"Блогови",
"ENTRIESBLOGS":"Записи во блог",
"FILESBLOGS":"Прилози од блогови",
"EVERYTHINGIDEATIONBLOGS":"Се од блоговите Создавање идеи",
"BLOGSIDEATIONBLOGS":"Блогови Создавање идеи",
"BLOGSIDEAS":"Идеи",
"ALLTYPESBLOGS":"Сите типови блогови",
"COMMUNITYBLOGS":"Блогови од заедниците",
"COMMUNITYIDEATIONBLOGS":"Блогови Создавање идеи од заедниците",
"STANDALONEBLOGS":"Самостојни блогови",
/* Bookmarks */
"ALLBOOKMARKS":"Сите обележувачи",
"PUBLICBOOKMARKS":"Јавни обележувачи",
"MYBOOKMARKS":"Мои обележувачи",
"ALLTYPESBOOKMARKS":"Сите типови обележувачи",
"COMMUNITYBOOKMARKS":"Обележувачи од заедниците",
"STANDALONEBOOKMARKS":"Самостојни обележувачи",
/* Files */
"ALLFILES":"Сите датотеки",
"PUBLICFILES":"Јавни датотеки",
"MYFILES":"Мои датотеки",
"ALLTYPESFILES":"Сите типови датотеки",
"COMMUNITYFILES":"Датотеки од заедниците",
"STANDALONEFILES":"Самостојни датотеки",
"NUMDOWNLOADS":"{0} преземања",
/* Wikis */
"ALLWIKIS":"Сите Wikis",
"PUBLICWIKIS":"Јавни Wikis",
"MYWIKIS":"Мои Wikis",
"EVERYTHINGWIKIS":"Се од Wikis",
"WIKISONLY":"Wikis?",
"PAGESWIKIS":"Страници на Wiki",
"FILESWIKIS":"Прилози од Wikis",
"ALLTYPESWIKIS":"Сите типови Wikis",
"COMMUNITYWIKIS":"Wikis од заедниците",
"STANDALONEWIKIS":"Самостојни Wikis",
/* Status Updates */
"ALLSTATUSUPDATES":"Сите ажурирања на статусот",
"PUBLICSTATUSUPDATES":"Јавни ажурирања на статусот",
"MYSTATUSUPDATES":"Мои ажурирања на статусот",
"ALLTYPESSTATUSUPDATES":"Сите типови ажурирања на статусот",
"COMMUNITYSTATUSUPDATES":"Ажурирања на статусот од заедниците",
"STANDALONESTATUSUPDATES":"Ажурирања на статусот од профилите",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Оваа УРЛ е обележана од одреден број корисници",
"BOOKMARKEDCOMMUNITY":"Оваа заедница е обележана од одреден број корисници",
"BOOKMARKEDPROFILE":"Овој профил е обележан од одреден број корисници",
"BOOKMARKEDBLOG":"Овој блог е обележан од одреден број корисници",
"COMMUNITYBLOG":"Ова е блог во рамките на заедница",
"BOOKMARKEDACTIVITY":"Оваа активност е обележана од одреден број корисници",
"COMMUNITYACTIVITY":"Ова е активност во рамките на заедница",
"BOOKMARKEDFILE":"Оваа датотека е обележана од одреден број корисници",
"COMMUNITYFILE":"Ова е датотека во рамките на заедница",
"BOOKMARKED":"Оваа Wiki е обележана од одреден број корисници",
"COMMUNITYWIKI":"Ова е Wiki во рамките на заедница",
"BOOKMARKEDFORUM":"Овој форум е обележан од одреден број корисници",
"COMMUNITYFORUM":"Ова е форум во рамките на заедница",
"ALLTAGANDTTILE":"За да ги видите сите наслови и ознаки за оваа УРЛ, кликнете  на ова копче",
"TAGS_ARE_FROM":"Овој резултат од пребарување можеби вклучува ознаки од:",
"BOOKMARKS_TITLE":"Обележувачи",
"COMMUNITIES_TITLE":"Заедници",
"ACTIVITIES_TITLE":"Активности",
"HELP":"Помош",
"MORESTATUSUPDATES":"Прикажи повеќе совпаѓања за ажурирање на статусот",
"TITLE_PREFIX":"наслов:",
"LATEST_MESSAGE":"Најнова порака",
"LATEST_STATUS_UPDATE":"Најново ажурирање на статусот",
"LATEST_COMMUNITY_STATUS_UPDATE":"Најново ажурирање на статусот на заедницата",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Најново ажурирање на статусот на заедниците",
"SEARCH_RESULTS":"Резултати од пребарувањето на Сите содржини",
"ACTIVITIES_SEARCH_RESULTS":"Резултати од пребарувањето на Активностите",
"BLOGS_SEARCH_RESULTS":"Резултати од пребарувањето на Блоговите",
"BOOKMARKS_SEARCH_RESULTS":"Резултати од пребарувањето на Обележувачите",
"COMMUNITIES_SEARCH_RESULTS":"Резултати од пребарувањето на Заедниците",
"FILES_SEARCH_RESULTS":"Резултати од пребарувањето на Датотеките",
"FORUMS_SEARCH_RESULTS":"Резултати од пребарувањето на Форумите",
"PROFILES_SEARCH_RESULTS":"Резултати од пребарувањето на Профилите",
"DIRECTORY_SEARCH_RESULTS":"Резултати од пребарувањето на именикот на ${orgName}",
"WIKIS_SEARCH_RESULTS":"Резултати од пребарувањето на Wikis",
"STATUS_UPDATES_SEARCH_RESULTS":"Резултати од пребарувањето на Ажурирањата на статусот",
"VIEW_ALL":"{span}Прикажи ги сите{/span} ({0})",
"MATCHING_ONE_OF":"Совпаѓање на еден од:",
"MATCHING_ALL_OF":"Совпаѓање на сите од:",
"MATCHING":"Совпаѓање:",
"MATCHING_DOC_TYPE":"Тип документ што се совпаѓа:",
"BOOKMARK_HELP":"Помош за обележувачи",
"CLOSE_BOOKMARK_HELP":"Затвори ја Помош за обележувачи",
"DOCUMENT_TYPE_PREFIX":"Тип документ",
"FILE_PREVIEW_ONLY":"(Само режим на преглед)"
})

