/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klikk her for å se visittkort",
	"label.semtag.hover.alt" : "Klikk her for å se visittkort for {0}",
	"label.semtag.hover.altA11Y" : "Klikk her eller trykk på Ctrl+Enter for å se visittkortet",
	"label.personcard.dialog.title" : "Visittkort for {0}",

	"errorDefaultMsg2" : "Det oppsto en feil, kontakt systemadministratoren",

	"loadingSTStatus" : "Laster inn Sametime-status...",
	"noStatuAvailable" : "Ingen Sametime-status tilgjengelig",

	"label.personcard.cardnomarkup" : "Visittkortet kunne ikke hentes",
	"label.inactive.user.msg" : "Denne personen er ikke lenger en aktiv bruker",
	"label.message.information" : "Informasjon:",
	"label.personcard.noprofilemsg" : "Det finnes ingen profil for denne personen",
	"label.personcard.cardreqexpired" : "Forespørselen om å få visittkortet utløpt",

	"label.bizcard.applinks.less" : "Vis mindre",
	"label.bizcard.applinks.more" : "Vis mer",

	"label.personcard.activitieslink" : "Aktiviteter",
	"label.personcard.activitieslink.title" : "Klikk her for å se delte aktiviteter",
	"label.personcard.blogslink" : "Blogger",
	"label.personcard.blogslink.title" : "Klikk her for å se denne personens blogg",
	"label.personcard.communitieslink" : "Fellesskap",
	"label.personcard.communitieslink.title" : "Klikk her for å se denne personens fellesskap",
	"label.personcard.dogearlink" : "Bokmerker",
	"label.personcard.dogearlink.title" : "Klikk her for å se denne personens bokmerker",
	"label.personcard.fileslink" : "Filer",
	"label.personcard.fileslink.title" : "Klikk her for å se denne personens delte filer",
	"label.personcard.forumlink" : "Fora",
	"label.personcard.forumlink.title" : "Klikk her for å se denne personens foruminnlegg",
	"label.personcard.homepagelink" : "Hjem",
	"label.personcard.homepagelink.title" : "Klikk her for å se denne personens hjemmeside",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Klikk her for å se denne personens mobilside",
	"label.personcard.newslink" : "Nyheter",
	"label.personcard.newslink.title" : "Klikk her for å se denne personens nyheter",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klikk her for å se denne personens profil",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klikk her for å se denne personens Quickr-delinger",
	"label.personcard.wikislink" : "Wikier",
	"label.personcard.wikislink.title" : "Klikk her for å se denne personens wikier",

	"personCardMoreActions" : "Flere handlinger",
	"personCardMoreActionsAltText" : "Klikk for handlingsmeny",

	"label.bizcard.dismiss": "Trykk på Esc for å lukke dette visittkortet.",
	"label.bizcard.fullProfile": "Full profil",
	"label.bizcard.activities": "Aktiviteter",
	"label.bizcard.communities": "Fellesskap",
	"label.bizcard.files": "Filer",
	"label.bizcard.forums": "Fora",
	"label.bizcard.bookmarks": "Bokmerker",
	"label.bizcard.blogs": "Blogger",
	"label.bizcard.wikis": "Wikier",

	"personCardAddAsColleagues" : "Inviter til Mitt nettverk",
	"personCardAddAsMyColleagues" : "Inviter til Mitt nettverk",
	"personCardFollow" : "Følg",
	"personCardUnfollow" : "Ikke følg lenger",
	"personCardChat" : "Samtale",
	"personCardCall" : "Ring",
	"personCardSendMail" : "Send e-post",
	"personCardSendEMail" : "Send e-post",
	"personCardProxyStatusAvailable" : "Jeg er tilgjengelig",
	"personCardDownloadVCard" : "Last ned vCard",

	"friends" : "Nettverk",
	"friendsFullPageTitle" : "Nettverk",
	"friendsMenuTitleAllContacts" : "Alle nettverkskontakter",
	"friendsMenuTitleMyContacts" : "Mine nettverkskontakter",
	"friendsInvitations" : "Invitasjoner",
	"friendsMenuTitleInCommon" : "Personer felles",
	"friendsShowAllCommonFriends" : "Vis alle...",
	"friendsViewAllFriends" : "Vis alle ({0})",
	"friendsSendFriendRequest" : "Send forespørsel",
	"friendsNoFriends" : "Ingen nettverkskontakter er tilknyttet denne profilen",
	"friendsColleaguesInvite" : "Inviter {0} til å være din nettverkskontakt",
	"friendsColleaguesFor" : "Nettverkskontakter for {0}",
	"friendsNewInv" : "{0} ny invitasjon",
	"friendsNewInvs" : "{0} nye invitasjoner",
	"friendsLoading" : "Laster inn nettverk...",
	"friendsLoadingInv" : "Laster inn invitasjoner ...",
	"friendsSelectFriendForRemoval" : "Velg kontaktene du vil fjerne først.",
	"friendsRemoved" : "Nettverkskontakt(er) fjernet.",
	"friendsInvSent" : "Ingen invitasjoner ble sendt, fordi det allerede er en invitasjon som venter.",
	"friendsRemovedSelected" : "Fjern fra Mitt nettverk",
	"friendsSortByDisplayName" : "Visningsnavn",
	"friendsSortByRecent" : "Nyeste",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-post:",
	"friendsAltEmail" : "Alternativ e-post:",
	"friendsNewInvitationsCount" : "Du har {0} ny(e) invitasjon(er)",
	"friendsNoInv" : "Ingen invitasjoner",
	"friendsInCommonSingle" : "Dere har {0} nettverkskontakt felles",
	"friendsInCommonMulti" : "Dere har {0} nettverkskontakter felles",
	"friendsIncludeMsgForInv" : "Ta med en melding i invitasjonen:",
	"friendsInitialMsgForInv" : "Jeg ønsker å legge deg inn på listen over mine Connections-nettverkskontakter.",
	"friendsSendInvAction" : "Send invitasjon",
	"friendsCancelInvAction" : "Avbryt",
	"friendsAcceptAction" : "Godta",
	"friendsIgnoreAction" : "Ignorer",
	"friendsYouExceedTextLimit" : "Invitasjonsmeldingen er for lang. Den kan inneholde opptil {1} tegn Det er {0} tegn i dette feltet.",
	"friendsCannotAddYourself" : "Du kan ikke legge til deg selv som nettverkskontakt.",
	"friendsIsYourColleague" : "{0} er din nettverkskontakt",
	"friendsRecentlyAdded" : "Personer du nylig har lagt til i nettverket ditt.",
	"friendsDate" : "Dato",
	"friendsCollapseWidget" : "Klikk for å skjule nettverksdelen",
	"friendsExpandWidget" : "Klikk for å utvide nettverksdelen",
	"friendsIsInYourNetwork" : "{0} er i nettverket ditt.",
	"friendsActionsFor" : "Handlinger for Nettverk",
	"friendsInviteFollowError" : "Det oppstod en feil ved forsøk på å følge {0}",
	"friendsInviteTagError" : "Det oppstod en feil ved forsøk på å tagge {0}",
	"friendsPleaseLogIn" : "Logg på for å invitere personer til nettverket ditt",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Invitasjon til nettverket ditt er ikke mulig fordi {0} allerede er i nettverket ditt.",
	"friendsInviteAddTagsFor" : "Legg til tagger for {0}:",
	"friendsInviteAlsoFollow" : "Følg også",
	"friendsInviteReceiveUpdates" : "(motta oppdateringer)",
	"friendsInviteUpdatesDescription" : "Motta oppdateringer om personer du følger, på hjemmesiden og i et e-postsammendrag.",
	"friendsInviteFollowHelp": "Hvis du vil ha mer informasjon, kan du lese {0}Følge personer{1}.",
	"friendsNetwork" : "Nettverk",
	"friendsMyNetwork" : "Nettverk",
	"friendsNetworkFor" : "Nettverk for {0}",
	"friendsRemoveSelected" : "Fjern valgte",
	"friendsRemoveSelectedTip" : "Klikk for å fjerne de valgte personene fra nettverket ditt.",
	"friendsNetworkInCommon" : "Dere har {0} nettverksforbindelser til felles.",
	"friendsAddToMyNetwork" : "Jeg ønsker å legge deg til i Connections-nettverket mitt.",
	"friendsInvite" : "Inviter til Mitt nettverk",
	"friendsInvitePerson" : "Inviter {0} til nettverket ditt",
	"friendsInviteMessage" : "Jeg ønsker å legge deg til i Connections-nettverket mitt.",
	"friendsInvitedEmailSubject" : "[Profiles] Du inviteres til å bli med i mitt nettverk",
	"friendsInvitedEmailMsg1" : "har invitert deg til å bli en nettverkskontakt med følgende melding inkludert i invitasjonen:",
	"friendsInvitedEmailMsg2" : "Åpne siden med nettverksinvitasjoner",
	"friendsInvitedEmailMsg3" : "Jeg ønsker å legge deg inn i mitt nettverk.",
	"friendsInvitedEmailMsg4" : "{0} inviterte deg til å bli en nettverkskontakt:",
	"friendsInvitedEmailMsg5" : "{0}har invitert deg til å bli en nettverkskontakt med følgende melding inkludert i invitasjonen:",
	"friendsInviteLegalNote" : "Ved å sende denne invitasjonen tillater du at {0} kommenterer på din profiltavle.",
	"friendsInviteFailed" : "På grunn av en serverfeil ble det ikke sendt ut e-postvarsel til den inviterte. Den inviterte vil imidlertid fortsatt kunne godta invitasjonen din gjennom webapplikasjonen Profiler.",
	"personInNetwork" : "Nettverkskontakt"
})
