/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Aktualisiert von ${author}",
		PREVIEW_MODE_ONLY: "(Nur Vorschaumodus)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Community wurde heute angezeigt",
		COMMUNITY_VIEWED_YESTERDAY: "Community wurde gestern angezeigt",
		COMMUNITY_VIEWED_HOURS_AGO: "Community wurde vor ${hours} Stunden angezeigt",
		COMMUNITY_VIEWED_MINUTES_AGO: "Community wurde vor ${minutes} Minuten angezeigt",
		COMMUNITY_VIEWED_SECONDS_AGO: "Community wurde vor ${seconds} Sekunden angezeigt",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Community wurde vor 1 Stunde angezeigt",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Community wurde vor 1 Minute angezeigt",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Community wurde vor 1 Sekunde angezeigt",
		COMMUNITY_VIEWED_AT_DATE: "Community wurde am ${date} angezeigt",
		//File
		FILE_VIEWED_TODAY: "Datei wurde heute angezeigt",
		FILE_VIEWED_YESTERDAY: "Datei wurde gestern angezeigt",
		FILE_VIEWED_HOURS_AGO: "Datei wurde vor ${hours} Stunden angezeigt",
		FILE_VIEWED_MINUTES_AGO: "Datei wurde vor ${minutes} Minuten angezeigt",
		FILE_VIEWED_SECONDS_AGO: "Datei wurde vor ${seconds} Sekunden angezeigt",
		FILE_VIEWED_1_HOUR_AGO: "Datei wurde vor 1 Stunde angezeigt",
		FILE_VIEWED_1_MINUTE_AGO: "Datei wurde vor 1 Minute angezeigt",
		FILE_VIEWED_1_SECOND_AGO: "Datei wurde vor 1 Sekunde angezeigt",
		FILE_VIEWED_AT_DATE: "Datei wurde am ${date} angezeigt",
		//Profile
		PROFILE_VIEWED_TODAY: "Profil wurde heute angezeigt",
		PROFILE_VIEWED_YESTERDAY: "Profil wurde gestern angezeigt",
		PROFILE_VIEWED_HOURS_AGO: "Profil wurde vor ${hours} Stunden angezeigt",
		PROFILE_VIEWED_MINUTES_AGO: "Profil wurde vor ${minutes} Minuten angezeigt",
		PROFILE_VIEWED_SECONDS_AGO: "Profil wurde vor ${seconds} Sekunden angezeigt",
		PROFILE_VIEWED_1_HOUR_AGO: "Profil wurde vor 1 Stunde angezeigt",
		PROFILE_VIEWED_1_MINUTE_AGO: "Profil wurde vor 1 Minute angezeigt",
		PROFILE_VIEWED_1_SECOND_AGO: "Profil wurde vor 1 Sekunde angezeigt",
		PROFILE_VIEWED_AT_DATE: "Profil wurde am ${date} angezeigt",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Aktivität wurde heute angezeigt",
		ACTIVITY_VIEWED_YESTERDAY: "Aktivität wurde gestern angezeigt",
		ACTIVITY_VIEWED_HOURS_AGO: "Aktivität wurde vor ${hours} Stunden angezeigt",
		ACTIVITY_VIEWED_MINUTES_AGO: "Aktivität wurde vor ${minutes} Minuten angezeigt",
		ACTIVITY_VIEWED_SECONDS_AGO: "Aktivität wurde vor ${seconds} Sekunden angezeigt",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Aktivität wurde vor 1 Stunde angezeigt",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Aktivität wurde vor 1 Minute angezeigt",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Aktivität wurde vor 1 Sekunde angezeigt",
		ACTIVITY_VIEWED_AT_DATE: "Aktivität wurde am ${date} angezeigt",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Lesezeichen wurde heute angezeigt",
		BOOKMARK_VIEWED_YESTERDAY: "Lesezeichen wurde gestern angezeigt",
		BOOKMARK_VIEWED_HOURS_AGO: "Lesezeichen wurde vor ${hours} Stunden angezeigt",
		BOOKMARK_VIEWED_MINUTES_AGO: "Lesezeichen wurde vor ${minutes} Minuten angezeigt",
		BOOKMARK_VIEWED_SECONDS_AGO: "Lesezeichen wurde vor ${seconds} Sekunden angezeigt",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Lesezeichen wurde vor 1 Stunde angezeigt",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Lesezeichen wurde vor 1 Minute angezeigt",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Lesezeichen wurde vor 1 Sekunde angezeigt",
		BOOKMARK_VIEWED_AT_DATE: "Lesezeichen wurde am ${date} angezeigt",
		//Blog
		BLOG_VIEWED_TODAY: "Blog wurde heute angezeigt",
		BLOG_VIEWED_YESTERDAY: "Blog wurde gestern angezeigt",
		BLOG_VIEWED_HOURS_AGO: "Blog wurde vor ${hours} Stunden angezeigt",
		BLOG_VIEWED_MINUTES_AGO: "Blog wurde vor ${minutes} Minuten angezeigt",
		BLOG_VIEWED_SECONDS_AGO: "Blog wurde vor ${seconds} Sekunden angezeigt",
		BLOG_VIEWED_1_HOUR_AGO: "Blog wurde vor 1 Stunde angezeigt",
		BLOG_VIEWED_1_MINUTE_AGO: "Blog wurde vor 1 Minute angezeigt",
		BLOG_VIEWED_1_SECOND_AGO: "Blog wurde vor 1 Sekunde angezeigt",
		BLOG_VIEWED_AT_DATE: "Blog wurde am ${date} angezeigt",
		//Forum
		FORUM_VIEWED_TODAY: "Forum wurde heute angezeigt",
		FORUM_VIEWED_YESTERDAY: "Forum wurde gestern angezeigt",
		FORUM_VIEWED_HOURS_AGO: "Forum wurde vor ${hours} Stunden angezeigt",
		FORUM_VIEWED_MINUTES_AGO: "Forum wurde vor ${minutes} Minuten angezeigt",
		FORUM_VIEWED_SECONDS_AGO: "Forum wurde vor ${seconds} Sekunden angezeigt",
		FORUM_VIEWED_1_HOUR_AGO: "Forum wurde vor 1 Stunde angezeigt",
		FORUM_VIEWED_1_MINUTE_AGO: "Forum wurde vor 1 Minute angezeigt",
		FORUM_VIEWED_1_SECOND_AGO: "Forum wurde vor 1 Sekunde angezeigt",
		FORUM_VIEWED_AT_DATE: "Forum wurde am ${date} angezeigt",
		//Wiki
		WIKI_VIEWED_TODAY: "Wiki wurde heute angezeigt",
		WIKI_VIEWED_YESTERDAY: "Wiki wurde gestern angezeigt",
		WIKI_VIEWED_HOURS_AGO: "Wiki wurde vor ${hours} Stunden angezeigt",
		WIKI_VIEWED_MINUTES_AGO: "Wiki wurde vor ${minutes} Minuten angezeigt",
		WIKI_VIEWED_SECONDS_AGO: "Wiki wurde vor ${seconds} Sekunden angezeigt",
		WIKI_VIEWED_1_HOUR_AGO: "Wiki wurde vor 1 Stunde angezeigt",
		WIKI_VIEWED_1_MINUTE_AGO: "Wiki wurde vor 1 Minute angezeigt",
		WIKI_VIEWED_1_SECOND_AGO: "Wiki wurde vor 1 Sekunde angezeigt",
		WIKI_VIEWED_AT_DATE: "Wiki wurde am ${date} angezeigt",
		//Event
		EVENT_VIEWED_TODAY: "Heute angezeigtes Ereignis",
		EVENT_VIEWED_YESTERDAY: "Gestern angezeigtes Ereignis",
		EVENT_VIEWED_HOURS_AGO: "Vor ${hours} Stunden angezeigtes Ereignis",
		EVENT_VIEWED_MINUTES_AGO: "Vor ${minutes} Minuten angezeigtes Ereignis",
		EVENT_VIEWED_SECONDS_AGO: "Vor ${seconds} Sekunden angezeigtes Ereignis",
		EVENT_VIEWED_1_HOUR_AGO: "Vor 1 Stunde angezeigtes Ereignis",
		EVENT_VIEWED_1_MINUTE_AGO: "Vor 1 Minute angezeigtes Ereignis",
		EVENT_VIEWED_1_SECOND_AGO: "Vor 1 Sekunde angezeigtes Ereignis",
		EVENT_VIEWED_AT_DATE: "Am ${date} angezeigtes Ereignis",
		//To Do
		TODO_VIEWED_TODAY: "Heute angezeigte Aufgabe",
		TODO_VIEWED_YESTERDAY: "Gestern angezeigte Aufgabe",
		TODO_VIEWED_HOURS_AGO: "Vor ${hours} angezeigte Aufgabe",
		TODO_VIEWED_MINUTES_AGO: "Vor ${minutes} Minuten angezeigte Aufgabe",
		TODO_VIEWED_SECONDS_AGO: "Vor ${seconds} Sekunden angezeigte Aufgabe",
		TODO_VIEWED_1_HOUR_AGO: "Vor 1 Stunde angezeigte Aufgabe",
		TODO_VIEWED_1_MINUTE_AGO: "Vor 1 Minute angezeigte Aufgabe",
		TODO_VIEWED_1_SECOND_AGO: "Vor 1 Sekunde angezeigte Aufgabe",
		TODO_VIEWED_AT_DATE: "Am ${date} angezeigte Aufgabe",
		//Survey
		SURVEY_VIEWED_TODAY: "Umfrage wurde heute angezeigt",
		SURVEY_VIEWED_YESTERDAY: "Umfrage wurde gestern angezeigt",
		SURVEY_VIEWED_HOURS_AGO: "Umfrage wurde vor ${hours} Stunden angezeigt",
		SURVEY_VIEWED_MINUTES_AGO: "Umfrage wurde vor ${minutes} Minuten angezeigt",
		SURVEY_VIEWED_SECONDS_AGO: "Umfrage wurde vor ${seconds} Sekunden angezeigt",
		SURVEY_VIEWED_1_HOUR_AGO: "Umfrage wurde vor 1 Stunde angezeigt",
		SURVEY_VIEWED_1_MINUTE_AGO: "Umfrage wurde vor 1 Minute angezeigt",
		SURVEY_VIEWED_1_SECOND_AGO: "Umfrage wurde vor 1 Sekunde angezeigt",
		SURVEY_VIEWED_AT_DATE: "Umfrage wurde am ${date} angezeigt",
		//Survey
		GENERIC_VIEWED_TODAY: "Heute angezeigt",
		GENERIC_VIEWED_YESTERDAY: "Gestern angezeigt",
		GENERIC_VIEWED_HOURS_AGO: "Vor ${hours} Stunden angezeigt",
		GENERIC_VIEWED_MINUTES_AGO: "Vor ${minutes} Minuten angezeigt",
		GENERIC_VIEWED_SECONDS_AGO: "Vor ${seconds} Sekunden angezeigt",
		GENERIC_VIEWED_1_HOUR_AGO: "Vor 1 Stunde angezeigt",
		GENERIC_VIEWED_1_MINUTE_AGO: "Vor 1 Minute angezeigt",
		GENERIC_VIEWED_1_SECOND_AGO: "Vor 1 Sekunde angezeigt",
		GENERIC_VIEWED_AT_DATE: "Am ${date} angezeigt"
});

