/* ***************************************************************** */
/*                                                                   */
/* IBM Confidential                                                  */
/*                                                                   */
/* OCO Source Materials                                              */
/*                                                                   */
/* Copyright IBM Corp. 2011, 2012                                    */
/*                                                                   */
/* The source code for this program is not published or otherwise    */
/* divested of its trade secrets, irrespective of what has been      */
/* deposited with the U.S. Copyright Office.                         */
/*                                                                   */
/* ***************************************************************** */

({
	"label.semtag.hover" : "לחצו כאן כדי להציג את כרטיס הביקור",
	"label.semtag.hover.alt" : "לחצו כדי להציג את כרטיס הביקור עבור {0} ",
	"label.semtag.hover.altA11Y" : "לחצו כאן או לחצו על control-enter כדי להציג את כרטיס הביקור",

	"errorDefaultMsg2" : "אירעה שגיאה, נא לפנות למנהלן המערכת",

	"loadingSTStatus" : "מצב Sametime נטען...‏",
	"noStatuAvailable" : "מצב Sametime אינו זמין",

	"label.personcard.cardnomarkup" : "לא ניתן לאחזר את כרטיס הביקור",
	"label.inactive.user.msg" : "אדם זה כבר אינו משתמש פעיל",
	"label.message.information" : "מידע:‏",
	"label.personcard.noprofilemsg" : "לא קיים פרופיל עבור אדם זה",
	"label.personcard.cardreqexpired" : "תוקף הבקשה לקבלת כרטיס הביקור פג",

	"label.bizcard.applinks.less" : "הצגת פחות",
	"label.bizcard.applinks.more" : "הצגת יותר",

	"label.personcard.activitieslink" : "פעילויות",
	"label.personcard.activitieslink.title" : "לחצו כאן כדי לראות פעילויות משותפות",
	"label.personcard.blogslink" : "בלוגים",
	"label.personcard.blogslink.title" : "לחצו כאן כדי לראות את הבלוג של אדם זה",
	"label.personcard.communitieslink" : "קהילות",
	"label.personcard.communitieslink.title" : "לחצו כאן כדי לראות את הקהילות של אדם זה",
	"label.personcard.dogearlink" : "סימניות",
	"label.personcard.dogearlink.title" : "לחצו כאן כדי לראות את הסימניות של אדם זה",
	"label.personcard.fileslink" : "קבצים",
	"label.personcard.fileslink.title" : "לחצו כאן כדי לראות את הקבצים המשותפים של אדם זה",
	"label.personcard.forumlink" : "פורומים",
	"label.personcard.forumlink.title" : "לחצו כאן כדי לראות את פרסומי הפורום של אדם זה",
	"label.personcard.homepagelink" : "דף הבית",
	"label.personcard.homepagelink.title" : "לחצו כאן כדי לראות את דף הבית של אדם זה",
	"label.personcard.mobilelink" : "נייד",
	"label.personcard.mobilelink.title" : "לחצו כאן כדי לראות את הדף הנייד של אדם זה",
	"label.personcard.newslink" : "קבוצת דיון",
	"label.personcard.newslink.title" : "לחצו כאן כדי לראות את החדשות של אדם זה",
	"label.personcard.profilelink" : "פרופיל",
	"label.personcard.profilelink.title" : "לחצו כאן כדי לראות את הפרופיל של אדם זה",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "לחצו כאן כדי לראות את שיתופי quickr של אדם זה",
	"label.personcard.wikislink" : "אתרי ויקי",
	"label.personcard.wikislink.title" : "לחצו כאן כדי לראות את אתרי הוויקי של אדם זה",

	"personCardMoreActions" : "פעולות נוספות",
	"personCardMoreActionsAltText" : "לחצו כדי להציג תפריט פעולות",

	"personCardAddAsColleagues" : "הזמנה אל 'הרשת  שלי'",
	"personCardAddAsMyColleagues" : "הזמנה אל 'הרשת  שלי'",
	"personCardFollow" : "מעקב",
	"personCardUnfollow" : "הפסקת מעקב",
	"personCardChat" : "צ'אט",
	"personCardCall" : "שיחה",
	"personCardSendMail" : "משלוח דואל",
	"personCardSendEMail" : "משלוח דואל",
	"personCardProxyStatusAvailable" : "אני זמין",
	"personCardDownloadVCard" : "הורדת vCard",

	"friends" : "רשת",
	"friendsFullPageTitle" : "רשת",
	"friendsMenuTitleAllContacts" : "כל אנשי הקשר ברשת",
	"friendsMenuTitleMyContacts" : "אנשי קשר ברשת שלי",
	"friendsInvitations" : "הזמנות",
	"friendsMenuTitleInCommon" : "אנשים משותפים",
	"friendsShowAllCommonFriends" : "הצגת הכל...‏",
	"friendsViewAllFriends" : "הצגת הכל ({0})",
	"friendsSendFriendRequest" : "משלוח בקשה",
	"friendsNoFriends" : "אין חברי רשת המשויכים לפרופיל זה",
	"friendsColleaguesInvite" : "הזמנת {0} כחבר רשת",
	"friendsColleaguesFor" : "חברי רשת עבור {0} ",
	"friendsNewInv" : "{0} הזמנה חדשה",
	"friendsNewInvs" : "{0} הזמנות חדשות ",
	"friendsLoading" : "הרשת נטענת...‏",
	"friendsLoadingInv" : "ההזמנות נטענות...‏",
	"friendsSelectFriendForRemoval" : "\u202bבחרו את חברי הרשת שברצונכם לסלק תחילה.‏\u202c",
	"friendsRemoved" : "\u202bחברי הרשת סולקו.‏\u202c",
	"friendsInvSent" : "\u202bלא נשלחו הזמנות מפני שכבר יש הזמנה ממתינה.‏\u202c",
	"friendsRemovedSelected" : "סילוק מתוך 'הרשת שלי'",
	"friendsSortByDisplayName" : "שם להצגה",
	"friendsSortByRecent" : "בשימוש לאחרונה",
	"friendsTelephone" : "טלפון:",
	"friendsEmail" : "דואל:",
	"friendsAltEmail" : "דואל חלופי:",
	"friendsNewInvitationsCount" : "יש לכם {0} הזמנות חדשות",
	"friendsNoInv" : "אין הזמנות",
	"friendsInCommonSingle" : "יש לכם {0} חבר רשת משותף.",
	"friendsInCommonMulti" : "יש לכם {0} חברי רשת משותפים.",
	"friendsIncludeMsgForInv" : "הכללת הודעה בהזמנה:",
	"friendsInitialMsgForInv" : "ברצוני להוסיף אותך אל רשימת חברי הרשת של IBM Connections.",
	"friendsSendInvAction" : "משלוח הזמנה",
	"friendsCancelInvAction" : "ביטול",
	"friendsAcceptAction" : "קבלה",
	"friendsIgnoreAction" : "התעלמות",
	"friendsYouExceedTextLimit" : "הודעת ההזמנה שלכם ארוכה מדי. האורך המרבי הוא {1} תווים. יש {0} תווים בשדה זה. ",
	"friendsCannotAddYourself" : "\u202bאינכם יכולים להוסיף את עצמכם כחברי רשת.‏\u202c",
	"friendsIsYourColleague" : "{0} הוא חבר רשת שלכם ",
	"friendsRecentlyAdded" : "אנשים שהוספתם לאחרונה לרשת שלכם",
	"friendsDate" : "תאריך",
	"friendsCollapseWidget" : "לחצו כדי לכווץ את חלק הרשת",
	"friendsExpandWidget" : "לחצו כדי להרחיב את חלק הרשת",
	"friendsIsInYourNetwork" : "{0} נמצא  ברשת שלכם. ",
	"friendsActionsFor" : "פעולות עבור 'רשת'",
	"friendsInviteFollowError" : "אירעה שגיאת רשת בנסיון לעקוב אחר {0} ",
	"friendsInviteTagError" : "אירעה שגיאת רשת בנסיון לתייג את {0} ",
	"friendsPleaseLogIn" : "התחברו כדי להזמין משתמש זה לרשת שלכם",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "לא ניתן לשלוח הזמנה לרשת שלכם כי {0} כבר נמצא ברשת שלכם. ",
	"friendsInviteAddTagsFor" : "הוספת תגים עבור {0}: ",
	"friendsInviteAlsoFollow" : "לעקוב גם אחר",
	"friendsInviteReceiveUpdates" : "(קבלת עדכונים)",
	"friendsInviteUpdatesDescription" : "קבלת עדכונים על אנשים שאתם עוקבים אחריהם בדף הבית ובסיכום בדואל. ",
	"friendsInviteFollowHelp": "כדי לקבל מידע נוסף, ראו {0}מעקב אחר אנשים{1}.",
	"friendsNetwork" : "רשת",
	"friendsMyNetwork" : "רשת",
	"friendsNetworkFor" : "רשת עבור {0}",
	"friendsRemoveSelected" : "סילוק נבחרים",
	"friendsRemoveSelectedTip" : "לחצו כדי לסלק את האנשים שנבחרו מהרשת שלכם.",
	"friendsNetworkInCommon" : "יש לכם {0} חברי רשת משותפים.",
	"friendsAddToMyNetwork" : "ברצוני להוסיף אותך לרשת 'החיבורים שלי'.",
	"friendsInvite" : "הזמנה אל 'הרשת  שלי'",
	"friendsInvitePerson" : "הזמנת {0} לרשת שלכם",
	"friendsInviteMessage" : "ברצוני להוסיף אותך לרשת 'החיבורים שלי'.",
	"friendsInvitedEmailSubject" : "[פרופילים] אתם מוזמנים להצטרף אל הרשת שלי",
	"friendsInvitedEmailMsg1" : "הזמין אותך לרשת שלו, וההזמנה כוללת את ההודעה שלהלן:",
	"friendsInvitedEmailMsg2" : "פתיחת דף הזמנות הרשת שלכם",
	"friendsInvitedEmailMsg3" : "ברצוני להוסיף אותך לרשת שלי.",
	"friendsInvitedEmailMsg4" : "{0} הזמין אותך לרשת שלו: ",
	"friendsInvitedEmailMsg5" : "{0} הזמין אותך לרשת שלו, וההזמנה כוללת את ההודעה שלהלן: ",
	"friendsInviteLegalNote" : "בכך שאתם שולחים הזמנה זו, אתם מסכימים להרשות ל-{0} להוסיף הערות ללוח הפרופיל שלכם. ",
	"friendsInviteFailed" : "בגלל שגיאה בשרת, לא נשלח דיווח בדואל למוזמן זה.  עם זאת, המוזמן יוכל להיענות להזמנתכם דרך יישום הרשת של יישום הפרופילים. "
})
