/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Dodaj sliko",
   newUpload : "Novo nalaganje",
   URL : "URL",
   imageLibrary : "Knjižnica slik",
   description : "Opis:",
   imageFile : "Datoteke:",
   OK: "V redu",
   cancel: "Prekliči",
   required: "Obvezno polje",
   preview: "Predogled:",
   previewWarning: "Slika se ni naložila. Ali ste prepričani, da je to veljaven URL slike?",
   alt: "Nadomestno besedilo",
   filesTab: "Iz datotek",
   images:"Slike:",
   browse:"Prebrskaj ...",
   imagePickerTitle:"Vstavi slike iz Datotek",
   componentImagePickerTitle:" Naloženih je ${0} slik",
   /* New String for insert image dialog */
   title: "Vstavi sliko",
   uploadBtn: "Naloži sliko",   
   insertBtn: "Vstavi sliko",
   uploadTab: "Lokalne datoteke",
   externalTab: "Spletni URL",
   internalTab: "Obstoječe slike",
   fileFieldTip: "Povlecite in spustite slike z namizja neposredno v to okno, če jih želite naložiti.",
   AdditionalSection: "Dodatne možnosti",
   ExpandSection: "Razširi dodatne možnosti",
   CloseSection: "Strni dodatne možnosti",
   webURLPrompt: "URL spletne slike:",
   previewPrompt: "Območje predogleda: da se velike slike prikažejo, lahko traja nekaj časa.",
   noExistingImage: "Ups! Nobena slika še ni dodana.",
   selectExistingImage: "Izberite obstoječo sliko:",
   urlMissing: "Vnesite URL",
   urlInvalid: "Neveljaven URL. Zagotovite, da ste vnesli veljaven URL, in poskusite znova.",
   previousItem: "Nazaj",
   nextItem: "Naprej",
   oneImageOneTime: "Slika je že dodana v to okno. Naenkrat lahko vstavite samo eno sliko.",
   loadingErrorMsg: "Med nalaganjem obstoječih slik je prišlo do napake. Poskusite znova pozneje.",
   urlInputTooltip: "Vnesite spletni URL slike"
})

