/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "De titel is vereist.",
	nourl: "De URL is vereist.",
	fileSchema: "Als u een externe of lokale bestandslink wilt toevoegen, moet deze een van de volgende indelingen hebben: bestand://extern_pad of bestand:///lokaal_pad.",
	invalidUrl: "Dit is geen geldige community-URL.",
	invalidTagChar: "De tag-lijst die u hebt ingevoerd, bevat ongeldige tekens zoals  & .  Verwijder deze tekens uit de tag-lijst.",
	txtHelp: "Help",
	txtHelpTags: "Help bij Tags",
	txtHelpTagsClose: "Help bij Tags sluiten",
	tagsall: "Alle",
	tagsyours: "Uw",
	tagsrecent: "Recent: ",
	tagspopular: "Populair: ",
	tagsrecommended: "Aanbevolen: ",
	nothingselected: "Selecteer een community.",
	nothingselected_activity: "Selecteer een activiteit.",
	nothingselected_blogs: "Selecteer een blog.",
	nothingselected_all: "Er is geen service of item geselecteerd, de bladwijzer wordt niet opgeslagen.",
	nothingFeedselected: "Er is geen service of item geselecteerd, de feed wordt niet opgeslagen.",
	alertDialogTitle: "Bericht",
	alertDialogOK: "OK",
	expand: "Klik hier om de sectie uit te vouwen",
	collapse: "Klik hier om de sectie samen te vouwen",
	discussThis: "Dit bespreken",
	by: "door:",
	posted: "Gepost:",
	attachments: "Bijlagen",
	communityForum: "Communityforum",
	notCommunityPage: "De huidige webpagina is geen geldige communitypagina. U kunt de titel, link en beschrijving van de community handmatig invoeren om een verwante community te maken.",
	privateCommunityNotice: "Dit is een besloten community. Deze is alleen zichtbaar voor leden van de community.",
	forumNameHint : "Typ een forumnaam",
	formDescriptionHint:"Beschrijf waarom deze verwante community interessant is voor uw community.",
	information : "Informatie",
	error : "Fout",
	success : "Geslaagd",
	warning : "Waarschuwing",
	informationColon : "Informatie:",
	successColon : "Geslaagd:",
	warningColon : "Waarschuwing:",
	errorColon : "Fout:",
	feedAlreadyExist : "Feed bestaat al in de community.",
	bookmarkAlreadyExist : "Bladwijzer bestaat al in de community.",
	mentionAuthWarning:"De ondervermelde personen zullen het bericht niet kunnen bekijken, want zij zijn geen lid van de community:",
	mentionAuthForumWarning:"De ondervermelde personen zullen het bericht niet kunnen bekijken, want zij hebben geen toegang tot dit forum:",
	exceedDescLength: "De opgegeven beschrijving is te lang.",
	communities_checked:"${0} community('s) geselecteerd",
	activities_checked:"${0} activiteit(en) geselecteerd",
	blogs_checked:"${0} blog(s) geselecteerd"
})
