/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informatie voor knooppunt: ",
		"INSTALLED": "De geïnstalleerde services controleren",
		"RESUMETOKENS": "De hervattingstokens controleren",
		"SEEDLISTS": "Controleren of de seedlijsten beschikbaar zijn",
		"CALENDARS": "Controleren of de planningskalenders juist zijn geconfigureerd",
		"VARIABLES": "Controleren of de WebSphere-variabelen zijn ingesteld",
		"TASKS": "Controleren op ingeschakelde indexeertaken",
		"INDEXFILES": "De indexmap controleren op vereiste bestanden",
		"LOGS": "De logboeken controleren op fouten",
		"CONFIGFILES": "De configuratiebestanden controleren",
		"DICTIONARIES": "Het aantal ingeschakelde woordenboeken controleren",
		"SYNC": "De status van de knooppunten wordt gecontroleerd",
		"DBRECORDS": "De databaserecords controleren",
		"INSTALLEDMSG": "De volgende service is geïnstalleerd: ",
		"RESUMETOKENSMSG": "De hervattingstoken voor: ",
		"SEEDLISTSMSG": "De seedlijst kan niet worden verkregen voor: ",
		"CALENDARSMSG": "Controle van planningskalender geslaagd: ",
		"VARIABLESMSG": "Variabele: ",
		"TASKSMSG": "De volgende taak is ingeschakeld: ",
		"INDEXFILESMSG" : "De volgende bestanden staan in de zoekindexmap: ",
		"LOGSMSG" : "Controleer de volgende foutberichten: ",
		"CONFIGFILESMSG" : "De volgende configuratiebestanden zijn gevonden: ",
		"DICTIONARIESMSG" : "Het aantal ingeschakelde woordenboeken is: ",
		"INSYNC": "Alle knooppunten zijn gesynchroniseerd",
		"OUTOFSYNC": "Het aantal asynchrone knooppunten is: ",
		"NOTBLOCKED": "Er zijn geen knooppunten geblokkeerd",
		"BLOCKED": "Het aantal geblokkeerde knooppunten is: ",
		"INDATE": "Alle knooppunten hebben de juiste datum",
		"OUTOFDATE": "Het aantal knooppunten met een onjuiste datum is: ",
		"NUMOFDOCS": "Het aantal documenten in de database is: ",
		"FILESTOCONVERT": "Het aantal te converteren bestandsdocumenten is ",
		"CONVERTEDFILES": "Het aantal geconverteerde bestanden is: ",
		"TOTALFILES": "Het totale aantal bestanden in de database ",
		"ERROR":"Fout",
		"ERROR_PREFIX":"Fout:",
		"INFO":"Informatie",
		"INFO_PREFIX":"Informatie:",
		"WARNING":"Waarschuwing",
		"WARNING_PREFIX":"Waarschuwing:",
		"LOADING_MESSAGE": "Laden",
		"SERVER_STATUS": "Serverstatus",
		"INITIAL_INDEXING_EXCEPTIONS": "Initiële indexeeruitzonderingen",
		"SYS_OUT_EXCEPTIONS": "SystemOut-loguitzonderingen",
		"SEEDLIST_VALIDATE": "Validatie van seedlijsten",
		"ERRORS_DURING_INITIAL_INDEXING":"De onderstaande uitzonderingsfouten zijn opgetreden bij het genereren van een initiële index.",
		"CRAWL_FAILED": "Voor de volgende service konden niet alle gegevens worden doorzocht: ",
		"EXCEPTION_ENCOUNTERED": "De crawlbewerking is mislukt met het volgende bericht: ",
		"SAND_VALIDATE": "SAND-validatie",
		"CHECK_FOR_SAND_FILES":"Controle op SAND-bestanden",
		"IS_FILE_AVAILABLE":"Controle of het bestand is gemaakt: ",
		"ERRORS_DURING_INITIAL_INDEXING":"De onderstaande uitzonderingsfouten zijn opgetreden bij het genereren van een initiële index.",
		"CRAWL_FAILED":"Voor de volgende service konden niet alle gegevens worden doorzocht: ",
		"EXCEPTION_ENCOUNTERED":"De crawlbewerking is mislukt met het volgende bericht: "
});

