/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filteren op:",
		"SHOW":"Afbeelden:",
		"ACL_FILTER_LABEL":"Filteren op tags",
		"PARENT_FILTER_LABEL":"Filteren op container",
		"TYPE_FILTER_LABEL":"Filteren op type",
		"PAGING_TOP":"Primaire paging",
		"PAGING_BOTTOM":"Secundaire paging",
		"PREVIOUS":"Vorige",
		"NEXT":"Volgende",
		"PAGE":"Pagina {0} van {1}",
		"PAGE_COLON":"Pagina:",
		"RESULTS":"{span}{0}-{1}{/span} van {2}",
		"ITEMS":"{0} items",
		/* Application names */
		"ACTIVITIES":"Activiteiten",
		"BLOGS":"Blogs",
		"CALENDAR":"Agenda",
		"COMMUNITIES":"Community's",
		"BOOKMARKS":"Bladwijzers",
		"DOGEAR":"Bladwijzers",
		"EVENTS":"Events",
		"FILES":"Bestanden",
		"FORUMS":"Forums",
		"PROFILES":"Profielen",
		"WIKI":"Wiki's",
		"WIKIS":"Wiki's",
		"FEEDS":"Feeds",
		"STATUS_UPDATES":"Statusupdates",
		"ONECOMMENT":"1 reactie",
		"COMMENTS":"{0} reacties",
		"ONEPERSON":"1 persoon",
		"PEOPLE":"{0} personen",
		"TAGS":"Tags:",
		"TAGSMORE":"en {0} meer",
		"NORESULTSMESSAGE":"Geen resultaten gevonden voor de zoekactie.",
		"JAN":"januari",
		"FEB":"februari",
		"MAR":"maart",
		"APR":"april",
		"MAY":"mei",
		"JUN":"juni",
		"JUL":"juli",
		"AUG":"augustus",
		"SEP":"september",
		"OCT":"oktober",
		"NOV":"november",
		"DEC":"december",
		"NO_CONTACT":"De zoekbewerking is niet uitgevoerd omdat er geen verbinding is met de server.",
		"SERVER_ERROR":"De zoekbewerking is niet uitgevoerd vanwege een serverfout.",
		"SORT_BY":"Sorteren op:",
		"SORT_RELEVANCE":"Relevantie",
		"SORT_DATE":"Datum",
		"SORT_LAST_UPDATED":"Laatst bijgewerkt",
		"SORT_DUE_DATE":"Actiedatum",
		"SORT_VISITS":"Bezoeken",
		"SORT_COMMENTS":"Reacties",
		"SORT_RECOMMENDATION":"Likes",
		"SORT_POPULARITY":"Populariteit",
		"SORT_FIRSTNAME":"Voornaam",
		"SORT_LASTNAME":"Achternaam",
		"SORT_DOWNLOADS":"Downloads",
		"SORT_TYPE":"Type",
		"SORT_SIZE":"Grootte",
		"SORT_TITLE":"Titel",
		"PRIVATE":"Besloten",
		"MODERATED":"Gemodereerd",
		"COMMUNITY_ACTIVITY":"Communityactiviteit",
		"COMMUNITY_BLOG":"Communityblog",
		"COMMUNITY_FILE":"Communitybestand",
		"COMMUNITY_FORUM":"Communityforum",
		"COMMUNITY_WIKI":"Communitywiki",
		"COMMUNITY_FEED":"Communityfeed",
		"COMMUNITY_BOOKMARK":"Communitybladwijzer",
		"NO_TAG":"Nog geen tags",
		"NO_DATE":"Nog geen datums",
		"NO_PEOPLE":"Nog geen personen",
		"REMOVE_FILTER_LABEL":"Klik om te verwijderen",
		"REMOVE_FILTER_TITLE":"Verwijderen",
		"REMOVE_FILTER_TOOLTIP":"Dit filter verwijderen",
		"COMMENT_ON":"Reactie op:",
		"EXPAND_COLLAPSE":"Klik hier voor uitvouwen / samenvouwen",
		"EXPAND":"Uitvouwen",
		"COLLAPSE":"Samenvouwen",
		"EXPAND_MONTHS_FILTER":"Maandfilter van jaar {0} uitvouwen",
		"SORT_RELEVANCE_LABEL":"Klik hier om te sorteren op relevantie",
		"SORT_DATE_LABEL":"Klik hier om te sorteren op datum",
		"SORT_UPDATED_LABEL":"Klik hier om te sorteren op laatst bijgewerkt",
		"SORT_DUE_LABEL":"Klik hier om te sorteren op actiedatum",
		"SORT_VISITS_LABEL":"Klik hier om te sorteren op aantal bezoeken",
		"SORT_COMMENTS_LABEL":"Klik hier om te sorteren op aantal reacties",
		"SORT_RECOMMENDATIONS_LABEL":"Klik hier om te sorteren op aantal likes",
		"SORT_POPULARITY_LABEL":"Klik hier om te sorteren op populariteit",
		"SORT_FIRST_NAME_LABEL":"Klik nier om te sorteren op voornaam",
		"SORT_LAST_NAME_LABEL":"Klik hier om te sorteren op achternaam",
		"RATING":"Likes",
		"GRADUATED":"Bevorderd",
		"ONEVOTE":"1 stem",
		"VOTES":"{0} stemmen",
		"BOOKMARK_THIS_RESULT":"Bladwijzer plaatsen",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (inactief)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} personen met bladwijzer",
		/* eg from an Activity */
		"FROMANACTIVITY":"uit een activiteit",
		"FROMABLOG":"uit een blog",
		"FROMANIDEATIONBLOG":"uit een ideatieblog",
		"FROMANEVENT":"uit een event",
		"FROMAFORUM":"uit een forum",
		"FROMAWIKI":"uit een wiki",
		"FROMACOMMUNITY":"uit een community",
		"FROMXCOMMUNITIES":"uit {0} community's",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Activiteit",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Ideatieblog",
		"ENTRY_ALONE":"Item",
		"EVENT_ALONE":"Event",
		"FORUM_ALONE":"Forum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Community",
		"XCOMMUNITIES_ALONE":"{0} community's",
		"SHAREDCOMMUNITIES":"Gedeeld met deze community's",
		"INACOMMUNITY":"in een community",
		"LASTUPDATED":"Zoekindex is laatst bijgewerkt:",
		"NODESCRIPTION":"Er is geen beschrijving of samenvatting voor dit resultaat.",
		"ATTACHMENT":"Bijlage:",
		"ACTIVITY":"Activiteit:",
		"ACTIVITYBOOKMARK":"Activiteitenbladwijzer:",
		"ACTIVITYCOMMENT":"Reactie op activiteit:",
		"ACTIVITYENTRY":"Activiteitenitem:",
		"ACTIVITYSECTION":"Activiteitensectie:",
		"ACTIVITYTODO":"Activiteitenactiepunt:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Blogitem:",
		"BLOGCOMMENT":"Blogreactie:",
		"BOOKMARK":"Bladwijzer:",
		"CALENDAREVENT":"Event:",
		"CATEGORY":"Categorie:",
		"COMMENT":"Reactie:",
		"COMMUNITY":"Community:",
		"ENTRY":"Item:",
		"EVENTDATEON":"Op: {0}",
		"EVENTISALLDAY":"Dagvullende event",
		"EVENTREPEATS":"Herhalingen",
		"FEED":"Feed:",
		"FILE":"Bestand:",
		"FORUM":"Forum:",
		"FORUMCATEGORY":"Forumcategorie:",
		"FORUMTOPIC":"Forumonderwerp:",
		"IDEA":"Idee:",
		"IDEACOMMENT":"Ideereactie:",
		"IDEATIONBLOG":"Ideatieblog:",
		"PAGE":"Pagina:",
		"PROFILE":"Profiel:",
		"SECTION":"Sectie:",
		"STATUSUPDATE":"Statusupdate",
		"STATUSUPDATE_PREFIX":"Statusupdate:",
		"TOPIC":"Onderwerp:",
		"TOPIC_WITH_ATTACHMENT":"Onderwerp",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Wikipagina:",
		"WIKIFILE":"Wikibijlage:",
		"SEARCH":"Zoeken:",
		"TODO":"Actiepunt:",
		"ALLRESULTS":"Alle resultaten",
		"PUBLICCONTENT":"Openbare content",
		"MYCONTENT":"Mijn content",
		"RESULTNOTFOUND":"Niet gevonden wat u zocht?",
		"TEMPDIFFICULTIES":"Opmerking: Vanwege tijdelijke indexeerproblemen zijn bij de zoekactie {0} items niet meegenomen die de laatste {1} dagen zijn gewijzigd.",
		"TRYLATER":"Probeer het later opnieuw.",
		"MULTIPLETEMPDIFFICULTIES":"Opmerking: Vanwege tijdelijke indexeerproblemen zijn bij de zoekactie {0} items niet meegenomen die onlangs zijn gewijzigd.",
		"YOUAREAUTHOR":"U bent auteur",
		"YOUARECONTRIBUTOR":"U bent bijdrager",
		"YOUAREOWNER":"U bent eigenaar",
		"YOUAREMEMBER":"U bent lid",
		/* Profiles */
		"MYNETWORK":"Mijn netwerk",
		"ALLPEOPLE":"Alle personen",
		"EXCLUDEINACTIVE":"Inactieve personen uitsluiten",
		"PHONE":"Telefoon:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Alle community's",
		"PUBLICCOMMUNITIES":"Openbare community's",
		"MYCOMMUNITIES":"Mijn community's",
		"EVERYTHINGCOMMUNITIES":"Alles uit Community's",
		"COMMUNITIESONLY":"Community's",
		"COMMUNITIESCONTENT":"Content uit Community's",
		/* Activities */
		"ALLACTIVITIES":"Alle activiteiten",
		"PUBLICACTIVITIES":"Openbare activiteiten",
		"MYACTIVITIES":"Mijn activiteiten",
		"EVERYTHINGACTIVITIES":"Alles uit Activiteiten",
		"ACTIVITIESONLY":"Activiteiten",
		"SECTIONSACTIVITIES": "Secties uit Activiteiten",
		"ENTRIESACTIVITIES":"Items uit Activiteiten",
		"TODOSACTIVITIES":"Actiepunten uit Activiteiten",
		"BOOKMARKSACTIVITIES":"Bladwijzers uit Activiteiten",
		"FILESACTIVITIES":"Bijlagen uit Activiteiten",
		"ALLTYPESACTIVITIES":"Alle typen activiteiten",
		"COMMUNITYACTIVITIES":"Activiteiten uit Community's",
		"STANDALONEACTIVITIES":"Stand-alone activiteiten",
		/* Forums */
		"ALLFORUMS":"Alle forums",
		"PUBLICFORUMS":"Openbare forums",
		"MYFORUMS":"Mijn forums",
		"EVERYTHINGFORUMS":"Alles uit Forums",
		"FORUMSONLY":"Forums",
		"TOPICSFORUMS":"Forumonderwerpen",
		"FORUMCATEGORIES": "Forumcategorieën",
		"FILESFORUMS":"Bijlagen uit Forums",
		"ALLTYPESFORUMS":"Alle typen forums",
		"COMMUNITYFORUMS":"Forums uit Community's",
		"STANDALONEFORUMS":"Stand-alone forums",
		/* Blogs */
		"ALLBLOGS":"Alle blogs",
		"PUBLICBLOGS":"Openbare blogs",
		"MYBLOGS":"Mijn blogs",
		"EVERYTHINGBLOGS":"Alles uit Blogs",
		"BLOGSONLY":"Blogs",
		"ENTRIESBLOGS":"Blogitems",
		"FILESBLOGS":"Bijlagen uit Blogs",
		"EVERYTHINGIDEATIONBLOGS":"Alles uit Ideatieblogs",
		"BLOGSIDEATIONBLOGS":"Ideatieblogs",
		"BLOGSIDEAS":"Ideeën",
		"ALLTYPESBLOGS":"Alle typen blogs",
		"COMMUNITYBLOGS":"Blogs uit Community's",
		"COMMUNITYIDEATIONBLOGS":"Ideatieblogs uit Community's",
		"STANDALONEBLOGS":"Stand-alone blogs",
		/* Bookmarks */
		"ALLBOOKMARKS":"Alle bladwijzers",
		"PUBLICBOOKMARKS":"Openbare bladwijzers",
		"MYBOOKMARKS":"Mijn bladwijzers",
		"ALLTYPESBOOKMARKS":"Alle typen bladwijzers",
		"COMMUNITYBOOKMARKS":"Bladwijzers uit Community's",
		"STANDALONEBOOKMARKS":"Stand-alone bladwijzers",
		/* Files */
		"ALLFILES":"Alle bestanden",
		"PUBLICFILES":"Openbare bestanden",
		"MYFILES":"Mijn bestanden",
		"ALLTYPESFILES":"Alle typen bestanden",
		"COMMUNITYFILES":"Bestanden uit Community's",
		"STANDALONEFILES":"Stand-alone bestanden",
		"NUMDOWNLOADS":"{0} downloads",
		/* Wikis */
		"ALLWIKIS":"Alle wiki's",
		"PUBLICWIKIS":"Openbare wiki's",
		"MYWIKIS":"Mijn wiki's",
		"EVERYTHINGWIKIS":"Alles uit Wiki's",
		"WIKISONLY":"Wiki's",
		"PAGESWIKIS":"Wikipagina's",
		"FILESWIKIS":"Bijlagen uit Wiki's",
		"ALLTYPESWIKIS":"Alle typen wiki's",
		"COMMUNITYWIKIS":"Wiki's uit Community's",
		"STANDALONEWIKIS":"Stand-alone wiki's",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Alle statusupdates",
		"PUBLICSTATUSUPDATES":"Openbare statusupdates",
		"MYSTATUSUPDATES":"Mijn statusupdates",
		"ALLTYPESSTATUSUPDATES":"Alle typen statusupdates",
		"COMMUNITYSTATUSUPDATES":"Statusupdates van community's",
		"STANDALONESTATUSUPDATES":"Statusupdates van profielen",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Deze URL is als bladwijzer toegevoegd door een aantal gebruikers",
		"BOOKMARKEDCOMMUNITY":"Deze community is als bladwijzer toegevoegd door een aantal gebruikers",
		"BOOKMARKEDPROFILE":"Dit profiel is als bladwijzer toegevoegd door een aantal gebruikers",
		"BOOKMARKEDBLOG":"Deze blog is als bladwijzer toegevoegd door een aantal gebruikers",
		"COMMUNITYBLOG":"Dit is een blog binnen een community",
		"BOOKMARKEDACTIVITY":"Deze activiteit is door een aantal gebruikers als bladwijzer toegevoegd",
		"COMMUNITYACTIVITY":"Dit is een activiteit binnen een community",
		"BOOKMARKEDFILE":"Dit bestand is als bladwijzer toegevoegd door een aantal gebruikers",
		"COMMUNITYFILE":"Dit is een bestand binnen een community",
		"BOOKMARKED":"Deze wiki is als bladwijzer toegevoegd door een aantal gebruikers",
		"COMMUNITYWIKI":"Dit is een wiki binnen een community",
		"BOOKMARKEDFORUM":"Dit forum is als bladwijzer toegevoegd door een aantal gebruikers",
		"COMMUNITYFORUM":"Dit is een forum binnen een community",
		"ALLTAGANDTTILE":"Klik op deze knop om alle titels en tags voor deze URL te zien",
		"TAGS_ARE_FROM":"Dit zoekresultaat kan tags bevatten uit:",
		"BOOKMARKS_TITLE":"Bladwijzers",
		"COMMUNITIES_TITLE":"Community's",
		"ACTIVITIES_TITLE":"Activiteiten",
		"HELP":"Help",
		"MORESTATUSUPDATES":"Meer statusupdatematches bekijken",
		"TITLE_PREFIX":"Titel:",
		"LATEST_MESSAGE":"Recentste bericht",
		"LATEST_STATUS_UPDATE":"Recentste statusupdate",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Recentste update van communitystatus",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Recentste update van communitystatus",
		"SEARCH_RESULTS":"Alle zoekresultaten voor content",
		"ACTIVITIES_SEARCH_RESULTS":"Activiteiten - Zoekresultaten",
		"BLOGS_SEARCH_RESULTS":"Blogs - Zoekresultaten",
		"BOOKMARKS_SEARCH_RESULTS":"Bladwijzers - Zoekresultaten",
		"COMMUNITIES_SEARCH_RESULTS":"Community's - Zoekresultaten",
		"FILES_SEARCH_RESULTS":"Bestanden - Zoekresultaten",
		"FORUMS_SEARCH_RESULTS":"Forums - Zoekresultaten",
		"PROFILES_SEARCH_RESULTS":"Profielen - Zoekresultaten",
		"DIRECTORY_SEARCH_RESULTS":"Zoekresultaten voor adresboek van ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Wiki's - Zoekresultaten",
		"STATUS_UPDATES_SEARCH_RESULTS":"Statusupdates - Zoekresultaten",
		"VIEW_ALL":"{span}Alle weergeven {/span} ({0})",
		"MATCHING_ONE_OF":"Komt overeen met een van:",
		"MATCHING_ALL_OF":"Komt overeen met alles van:",
		"MATCHING":"Overeenkomend met:",
		"MATCHING_DOC_TYPE":"Komt overeen met documenttype:",
		"BOOKMARK_HELP":"Help bij Bladwijzer",
		"CLOSE_BOOKMARK_HELP":"Help bij Bladwijzer sluiten",
		"DOCUMENT_TYPE_PREFIX":"Documenttype:",
		"LAST_PAGE_MESSAGE": "Dat zijn wel wat veel zoekresultaten. Probeer de zoekactie te verfijnen door meer zoektermen toe te voegen.",
		"LAST_PAGE_SUBMESSAGE": "U ontvangt de eerste {resultNumber} relevante zoekresultaten."
});

