/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "הכותרת דרושה.",
	nourl: "ה-URL דרוש.‏",
	fileSchema: "אם ברצונכם להוסיף קישור לקובץ מרוחק או מקומי, עליו להתאים לאחד המבנים שלהלן: file://remote_path או file:///local_path.‏",
	invalidUrl: "אינו URL קהילה חוקי.‏",
	invalidTagChar: "רשימת התגיות שציינתם מכילה תו לא חוקי '&'. סלקו תו זה מרשימת התגיות.",
	txtHelp: "עזרה",
	txtHelpTags: "עזרה לתגים",
	txtHelpTagsClose: "סגירת העזרה לתגים",
	tagsall: "הכל",
	tagsyours: "שלכם",
	tagsrecent: "עודכן לאחרונה: ",
	tagspopular: "פופולרי: ",
	tagsrecommended: "מומלץ: ",
	nothingselected: "יש לבחור קהילה.",
	nothingselected_activity: "יש לבחור פעילות.",
	nothingselected_blogs: "יש לבחור בלוג.",
	nothingselected_all: "לא בחרתם שירות או רשומה, הסימניה לא תישמר.",
	nothingFeedselected: "לא נבחר שירות או רשומה, ערוץ התוכן לא יישמר.",
	alertDialogTitle: "הודעה",
	alertDialogOK: "אישור",
	expand: "לחצו כדי להרחיב את החלק",
	collapse: "לחצו כדי לכווץ את החלק",
	discussThis: "דיון בנושא זה",
	by: "מאת:",
	posted: "פורסם:",
	attachments: "צרופות",
	communityForum: "פורום קהילה",
	notCommunityPage: "דף הרשת הנוכחי אינו דף רשת חוקי של קהילה. תוכלו לציין כותרת קהילה, קישור ותיאור באופן ידני כדי ליצור קהילה קשורה.",
	privateCommunityNotice: "קהילה זו מוגבלת. היא גלויה רק לחברי הקהילה.",
	forumNameHint : "הקלידו שם פורום",
	formDescriptionHint:"תארו מדוע קהילה קשורה זו תעניין את הקהילה שלכם.",
	information : "מידע",
	error : "שגיאה",
	success : "הצלחה",
	warning : "אזהרה",
	informationColon : "מידע:‏",
	successColon : "הצלחה:",
	warningColon : "אזהרה:",
	errorColon : "שגיאה:",
	feedAlreadyExist : "ערוץ התוכן כבר קיים בקהילה.",
	bookmarkAlreadyExist : "הסימניה כבר קיימת בקהילה.",
	mentionAuthWarning:"האנשים הבאים שאוזכרו לא יוכלו להציג את ההודעה מכיוון שאינם חברים בקהילה:",
	mentionAuthForumWarning:"האנשים המאוזכרים שלהלן לא יוכלו להציג את ההודעה מפני שאינם יכולים לגשת לפורום זה:",
	exceedDescLength: "התיאור שציינתם ארוך מדי.",
	communities_checked:"${0} קהילות נבחרו",
	activities_checked:"${0} פעילויות נבחרו",
	blogs_checked:"${0} בלוגים נבחרו"
})
