/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"過濾依據：",
"SHOW":"顯示：",
"ACL_FILTER_LABEL":"依可見性過濾",
"PARENT_FILTER_LABEL":"依儲存器過濾",
"TYPE_FILTER_LABEL":"依類型過濾",
"PAGING_TOP":"主要分頁",
"PAGING_BOTTOM":"次要分頁",
"PREVIOUS":"上一頁",
"NEXT":"下一頁",
"PAGE":"第 {0} 頁（共 {1} 頁）",
"PAGE_COLON":"頁面：",
"RESULTS":"{span}{0} - {1}{/span}/{2}",
"ITEMS":"{0} 個項目",
/* Application names */
"ACTIVITIES":"活動",
"BLOGS":"部落格",
"CALENDAR":"行事曆",
"COMMUNITIES":"社群",
"BOOKMARKS":"書籤",
"DOGEAR":"書籤",
"EVENTS":"事件",
"FILES":"檔案",
"FORUMS":"討論區",
"PROFILES":"人員資訊",
"WIKI":"Wiki",
"WIKIS":"Wiki",
"FEEDS":"資訊來源",
"STATUS_UPDATES":"狀態更新",
"ONECOMMENT":"1 個評論",
"COMMENTS":"{0} 個評論",
"ONEPERSON":"1 個人員",
"PEOPLE":"{0} 個人",
"TAGS":"標籤：",
"TAGSMORE":"再多 {0} 個",
"NORESULTSMESSAGE":"找不到該搜尋的結果",
"JAN":"1 月",
"FEB":"2 月",
"MAR":"3 月",
"APR":"4 月",
"MAY":"5 月",
"JUN":"6 月",
"JUL":"7 月",
"AUG":"8 月",
"SEP":"9 月",
"OCT":"10 月",
"NOV":"11 月",
"DEC":"12 月",
"NO_CONTACT":"因為無法聯絡伺服器，所以未執行搜尋",
"SERVER_ERROR":"由於發生伺服器錯誤，未執行搜尋",
"SORT_BY":"排序方式：",
"SORT_RELEVANCE":"相關性",
"SORT_DATE":"日期",
"SORT_LAST_UPDATED":"前次更新",
"SORT_DUE_DATE":"到期日",
"SORT_VISITS":"造訪次數",
"SORT_COMMENTS":"評論數",
"SORT_RECOMMENDATION":"按讚數",
"SORT_POPULARITY":"熱門程度",
"SORT_FIRSTNAME":"名字",
"SORT_LASTNAME":"姓氏",
"SORT_DOWNLOADS":"下載次數",
"SORT_TYPE":"類型",
"SORT_SIZE":"大小",
"SORT_TITLE":"標題",
"PRIVATE":"專用",
"MODERATED":"受控管",
"COMMUNITY_ACTIVITY":"社群活動",
"COMMUNITY_BLOG":"社群部落格",
"COMMUNITY_FILE":"社群檔案",
"COMMUNITY_FORUM":"社群討論區",
"COMMUNITY_WIKI":"社群 Wiki",
"COMMUNITY_FEED":"社群資訊來源",
"COMMUNITY_BOOKMARK":"社群書籤",
"NO_TAG":"無標籤",
"NO_DATE":"尚沒有日期",
"NO_PEOPLE":"尚未有人員",
"REMOVE_FILTER_LABEL":"按一下以移除",
"REMOVE_FILTER_TITLE":"移除",
"REMOVE_FILTER_TOOLTIP":"移除此過濾器",
"COMMENT_ON":"提供評論：",
"EXPAND_COLLAPSE":"按一下以展開/收合",
"EXPAND":"展開",
"COLLAPSE":"收合",
"EXPAND_MONTHS_FILTER":"展開 {0} 年的月份過濾器",
"SORT_RELEVANCE_LABEL":"按一下以依相關性排序",
"SORT_DATE_LABEL":"按一下以依日期排序",
"SORT_UPDATED_LABEL":"按一下依前次更新進行排序",
"SORT_DUE_LABEL":"按一下以依到期日排序",
"SORT_VISITS_LABEL":"按一下以依造訪次數排序",
"SORT_COMMENTS_LABEL":"按一下以依評論數排序",
"SORT_RECOMMENDATIONS_LABEL":"按一下以依按讚數排序",
"SORT_POPULARITY_LABEL":"按一下以依熱門程度排序",
"SORT_FIRST_NAME_LABEL":"按一下以依給定的名字排序",
"SORT_LAST_NAME_LABEL":"按一下以依姓氏排序",
"RATING":"按讚數",
"GRADUATED":"已提升",
"ONEVOTE":"1 次投票",
"VOTES":"{0} 次投票",
"BOOKMARK_THIS_RESULT":"加入書籤",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0}（非作用中）",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} 個人已加入書籤",
/* eg from an Activity */
"FROMANACTIVITY":"從活動",
"FROMABLOG":"從部落格",
"FROMANIDEATIONBLOG":"從構想部落格",
"FROMANEVENT":"從事件",
"FROMAFORUM":"從討論區",
"FROMAWIKI":"從 Wiki",
"FROMACOMMUNITY":"從 1 個社群",
"FROMXCOMMUNITIES":"從 {0} 個社群",
/* For search results parentage */
"ACTIVITY_ALONE":"活動",
"BLOG_ALONE":"部落格",
"IDEATIONBLOG_ALONE":"構想部落格",
"ENTRY_ALONE":"文章",
"EVENT_ALONE":"事件",
"FORUM_ALONE":"討論區",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"社群",
"XCOMMUNITIES_ALONE":"{0} 個社群",
"SHAREDCOMMUNITIES":"與這些社群共用",
"INACOMMUNITY":"在社群",
"LASTUPDATED":"搜尋索引前次更新時間：",
"NODESCRIPTION":"沒有此結果的任何說明或摘要。",
"ATTACHMENT":"附件：",
"ACTIVITY":"活動：",
"ACTIVITYBOOKMARK":"活動書籤：",
"ACTIVITYCOMMENT":"活動評論：",
"ACTIVITYENTRY":"活動項目：",
"ACTIVITYSECTION":"活動區段：",
"ACTIVITYTODO":"待辦事項活動：",
"BLOG":"部落格：",
"BLOGENTRY":"部落格文章：",
"BLOGCOMMENT":"部落格評論",
"BOOKMARK":"書籤：",
"CALENDAREVENT":"事件：",
"CATEGORY":"種類：",
"COMMENT":"評論：",
"COMMUNITY":"社群：",
"ENTRY":"文章：",
"EVENTDATEON":"日期：{0}",
"EVENTISALLDAY":"全天事件",
"EVENTREPEATS":"重複頻率",
"FEED":"資訊來源：",
"FILE":"檔案：",
"FORUM":"討論區：",
"FORUMCATEGORY":"討論區種類：",
"FORUMTOPIC":"討論區主題：",
"IDEA":"構想：",
"IDEACOMMENT":"構想評論：",
"IDEATIONBLOG":"構想部落格：",
"PAGE":"頁面：",
"PROFILE":"人員資訊：",
"SECTION":"區段：",
"STATUSUPDATE":"狀態更新",
"STATUSUPDATE_PREFIX":"狀態更新：",
"TOPIC":"主題：",
"TOPIC_WITH_ATTACHMENT":"主題",
"WIKITYPE":"Wiki：",
"WIKIPAGE":"Wiki 頁面：",
"WIKIFILE":"Wiki 附件：",
"SEARCH":"搜尋：",
"TODO":"待辦事項：",
"ALLRESULTS":"全部結果",
"PUBLICCONTENT":"公用內容",
"MYCONTENT":"我的內容",
"RESULTNOTFOUND":"找不到您要尋找的內容嗎？",
"TEMPDIFFICULTIES":"附註：由於暫時的檢索困難，搜尋未併入前 {1} 天所變更的 {0}。",
"TRYLATER":"請稍後重試。",
"MULTIPLETEMPDIFFICULTIES":"附註：由於暫時的檢索困難，搜尋未併入最近變更的 {0}",
"YOUAREAUTHOR":"您是作者",
"YOUARECONTRIBUTOR":"您是投稿者",
"YOUAREOWNER":"您是擁有者",
"YOUAREMEMBER":"您是成員",
/* Profiles */
"MYNETWORK":"我的網路",
"ALLPEOPLE":"全部人員",
"EXCLUDEINACTIVE":"排除非作用中人員",
"PHONE":"電話：",
"EMAIL":"電子郵件：",
/* Communities */
"ALLCOMMUNITIES":"所有社群",
"PUBLICCOMMUNITIES":"公用社群",
"MYCOMMUNITIES":"我的社群",
"EVERYTHINGCOMMUNITIES":"社群的所有內容",
"COMMUNITIESONLY":"社群",
"COMMUNITIESCONTENT":"來自社群的內容",
/* Activities */
"ALLACTIVITIES":"所有活動",
"PUBLICACTIVITIES":"公用活動",
"MYACTIVITIES":"我的活動",
"EVERYTHINGACTIVITIES":"活動的所有內容",
"ACTIVITIESONLY":"活動",
"SECTIONSACTIVITIES": "來自「活動」的區段",
"ENTRIESACTIVITIES":"來自活動的項目",
"TODOSACTIVITIES":"來自活動的待辦事項",
"BOOKMARKSACTIVITIES":"來自「活動」的書籤",
"FILESACTIVITIES":"來自活動的連接裝置",
"ALLTYPESACTIVITIES":"活動的所有類型",
"COMMUNITYACTIVITIES":"來自社群的活動",
"STANDALONEACTIVITIES":"獨立式活動",
/* Forums */
"ALLFORUMS":"所有討論區",
"PUBLICFORUMS":"公用討論區",
"MYFORUMS":"我的討論區",
"EVERYTHINGFORUMS":"討論區的所有內容",
"FORUMSONLY":"討論區",
"TOPICSFORUMS":"討論區主題",
"FORUMCATEGORIES": "討論區種類",
"FILESFORUMS":"來自討論區的連接裝置",
"ALLTYPESFORUMS":"討論區的所有類型",
"COMMUNITYFORUMS":"來自社群的討論區",
"STANDALONEFORUMS":"獨立式討論區",
/* Blogs */
"ALLBLOGS":"所有部落格",
"PUBLICBLOGS":"開放式部落格",
"MYBLOGS":"我的部落格",
"EVERYTHINGBLOGS":"部落格的所有內容",
"BLOGSONLY":"部落格",
"ENTRIESBLOGS":"部落格文章",
"FILESBLOGS":"來自部落格的連接裝置",
"EVERYTHINGIDEATIONBLOGS":"來自構想部落格的所有內容",
"BLOGSIDEATIONBLOGS":"構想部落格",
"BLOGSIDEAS":"構想",
"ALLTYPESBLOGS":"部落格的所有類型",
"COMMUNITYBLOGS":"來自社群的部落格",
"COMMUNITYIDEATIONBLOGS":"來自社群的構想部落格",
"STANDALONEBLOGS":"獨立式部落格",
/* Bookmarks */
"ALLBOOKMARKS":"所有書籤",
"PUBLICBOOKMARKS":"公用書籤",
"MYBOOKMARKS":"我的書籤",
"ALLTYPESBOOKMARKS":"書籤的所有類型",
"COMMUNITYBOOKMARKS":"來自社群的書籤",
"STANDALONEBOOKMARKS":"獨立式書籤",
/* Files */
"ALLFILES":"所有檔案",
"PUBLICFILES":"公用檔案",
"MYFILES":"我的檔案",
"ALLTYPESFILES":"檔案的所有類型",
"COMMUNITYFILES":"來自社群的檔案",
"STANDALONEFILES":"獨立式檔案",
"NUMDOWNLOADS":"{0} 項下載",
/* Wikis */
"ALLWIKIS":"所有 Wiki",
"PUBLICWIKIS":"公用 Wiki",
"MYWIKIS":"我的 Wiki",
"EVERYTHINGWIKIS":"Wiki 的所有內容",
"WIKISONLY":"Wiki",
"PAGESWIKIS":"Wiki 頁面",
"FILESWIKIS":"來自 Wiki 的連接裝置",
"ALLTYPESWIKIS":"Wiki 的所有類型",
"COMMUNITYWIKIS":"來自社群的 Wiki",
"STANDALONEWIKIS":"獨立式 Wiki",
/* Status Updates */
"ALLSTATUSUPDATES":"所有狀態更新",
"PUBLICSTATUSUPDATES":"公用狀態更新",
"MYSTATUSUPDATES":"我的狀態更新",
"ALLTYPESSTATUSUPDATES":"狀態更新的所有類型",
"COMMUNITYSTATUSUPDATES":"來自社群的狀態更新",
"STANDALONESTATUSUPDATES":"來自人員資訊的狀態更新",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"多位使用者將此 URL 加入書籤",
"BOOKMARKEDCOMMUNITY":"多位使用者將此社群加入書籤",
"BOOKMARKEDPROFILE":"多位使用者將此人員資訊加入書籤",
"BOOKMARKEDBLOG":"多位使用者將此部落格加入書籤",
"COMMUNITYBLOG":"這是位於社群中的部落格",
"BOOKMARKEDACTIVITY":"多位使用者將此活動加入書籤",
"COMMUNITYACTIVITY":"這是位於社群中的活動",
"BOOKMARKEDFILE":"多位使用者將此檔案加入書籤",
"COMMUNITYFILE":"這是位於社群中的檔案",
"BOOKMARKED":"多位使用者將此 Wiki 加入書籤",
"COMMUNITYWIKI":"這是位於社群中的 Wiki",
"BOOKMARKEDFORUM":"多位使用者將此討論區加入書籤",
"COMMUNITYFORUM":"這是位於社群中的討論區",
"ALLTAGANDTTILE":"若要查看此 URL 的所有標題及標籤，請按一下此按鈕",
"TAGS_ARE_FROM":"此搜尋結果可能包含來自下列項目的標籤：",
"BOOKMARKS_TITLE":"書籤",
"COMMUNITIES_TITLE":"社群",
"ACTIVITIES_TITLE":"活動",
"HELP":"說明",
"MORESTATUSUPDATES":"檢視其他狀態更新相符項",
"TITLE_PREFIX":"標題：",
"LATEST_MESSAGE":"最新訊息",
"LATEST_STATUS_UPDATE":"最新狀態更新",
"LATEST_COMMUNITY_STATUS_UPDATE":"最新社群狀態更新",
"LATEST_COMMUNITIES_STATUS_UPDATE":"最新社群狀態更新",
"SEARCH_RESULTS":"所有內容搜尋結果",
"ACTIVITIES_SEARCH_RESULTS":"活動搜尋結果",
"BLOGS_SEARCH_RESULTS":"部落格搜尋結果",
"BOOKMARKS_SEARCH_RESULTS":"書籤搜尋結果",
"COMMUNITIES_SEARCH_RESULTS":"社群搜尋結果",
"FILES_SEARCH_RESULTS":"檔案搜尋結果",
"FORUMS_SEARCH_RESULTS":"討論區搜尋結果",
"PROFILES_SEARCH_RESULTS":"人員資訊搜尋結果",
"DIRECTORY_SEARCH_RESULTS":"${orgName} 目錄搜尋結果",
"WIKIS_SEARCH_RESULTS":"Wiki 搜尋結果",
"STATUS_UPDATES_SEARCH_RESULTS":"狀態更新搜尋結果",
"VIEW_ALL":"{span}檢視全部{/span} ({0})",
"MATCHING_ONE_OF":"符合下列項目之一：",
"MATCHING_ALL_OF":"符合下列項目全部：",
"MATCHING":"符合：",
"MATCHING_DOC_TYPE":"符合的文件類型：",
"BOOKMARK_HELP":"書籤說明",
"CLOSE_BOOKMARK_HELP":"關閉書籤說明",
"DOCUMENT_TYPE_PREFIX":"文件類型：",
"FILE_PREVIEW_ONLY":"（僅限預覽模式）"
})

