/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Potreban je naslov.",
	nourl: "Potreban je URL.",
	fileSchema: "Ako želite dodati vezu za udaljenu ili lokalnu datoteku ona mora biti u jednom od sljedećih formata: file://remote_path ili file:///local_path.",
	invalidUrl: "Ovo nije ispravan URL zajednice.",
	invalidTagChar: "Lista oznaka koju ste unijeli sadrži nevažeći znak \"&\".  Uklonite ovaj znak s liste oznaka.",
	txtHelp: "Pomoć",
	txtHelpTags: "Pomoć za oznake",
	txtHelpTagsClose: "Zatvori pomoć za oznake",
	tagsall: "Sve",
	tagsyours: "Vaše",
	tagsrecent: "Nedavne: ",
	tagspopular: "Popularne: ",
	tagsrecommended: "Preporučene: ",
	nothingselected: "Potreban je izbor zajednice.",
	nothingselected_activity: "Potreban je izbor aktivnosti.",
	nothingselected_blogs: "Potreban je izbor bloga.",
	nothingselected_all: "Nije izabrana usluga ili unos, knjiška oznaka se neće spremiti.",
	nothingFeedselected: "Nije izabrana usluga ili unos, tekuće informacije se neće spremiti.",
	alertDialogTitle: "Poruka",
	alertDialogOK: "OK",
	expand: "Kliknite da proširite ovaj odjeljak",
	collapse: "Kliknite da skupite ovaj odjeljak",
	discussThis: "Raspravite ovo",
	by: "od:",
	posted: "Objavio:",
	attachments: "Prilozi",
	communityForum: "Forum zajednice",
	notCommunityPage: "Trenutna Web stranica nije važeća Web stranica zajednice. Ručno možete unijeti naslov zajednice te vezu i opis za kreiranje odgovarajuće zajednice.",
	privateCommunityNotice: "Ova zajednica ima ograničenja. Vidljiva je samo članovima zajednice.",
	forumNameHint : "Upišite ime foruma",
	formDescriptionHint:"Opišite zašto bi ova povezana zajednica mogla biti interesantna vašoj zajednici.",
	information : "Informacije",
	error : "Greška",
	success : "Uspjeh",
	warning : "Upozorenje",
	informationColon : "Informacije:",
	successColon : "Uspjeh:",
	warningColon : "Upozorenje:",
	errorColon : "Greška:",
	feedAlreadyExist : "U zajednici već postoji feed.",
	bookmarkAlreadyExist : "U zajednici već postoji knjiška oznaka.",
	mentionAuthWarning:"Sljedeće osobe neće moći pogledati poruku jer nisu članovi zajednice:",
	mentionAuthForumWarning:"Sljedeće osobe neće moći pogledati poruku jer ne mogu pristupiti ovom forumu:",
	exceedDescLength: "Opis koji ste unijeli je predug.",
	communities_checked:"Izabrano je ${0} zajednica",
	activities_checked:"Izabrano je ${0} aktivnosti",
	blogs_checked:"Izabrano je ${0} blogova"
})
