/* Copyright IBM Corp. 2009, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informacije za čvor: ",
		"INSTALLED": "Provjera instalisanih usluga",
		"RESUMETOKENS": "Provjera rezimiranih tokena",
		"SEEDLISTS": "Provjera da su dostupne liste izvora",
		"CALENDARS": "Provjera da su kalendari rasporeda ispravno konfigurisani",
		"VARIABLES": "Provjera da su postavljene WebSphere varijable",
		"TASKS": "Provjera omogućenih zadataka indeksiranja",
		"INDEXFILES": "Provjera foldera indeksa za potrebne datoteke",
		"LOGS": "Pregled dnevnika radi grešaka",
		"CONFIGFILES": "Pregled konfiguracijskih datoteka",
		"DICTIONARIES": "Provjera broja rječnika koji su omogućeni",
		"SYNC": "Provjera statusa čvorova",
		"DBRECORDS": "Provjera slogova baze podataka",
		"INSTALLEDMSG": "Instalirana je sljedeća usluga: ",
		"RESUMETOKENSMSG": "Oznaka rezimiranja za: ",
		"SEEDLISTSMSG": "Nije mogao biti dobiven seedlist za: ",
		"CALENDARSMSG": "Provjera kalendara rasporeda je prošla: ",
		"VARIABLESMSG": "Varijabla: ",
		"TASKSMSG": "Omogućen je sljedeći zadatak: ",
		"INDEXFILESMSG" : "Sljedeće datoteke se nalaze u folderu indeksa pretraživanja: ",
		"LOGSMSG" : "Pregledajte sljedeće poruke greške: ",
		"CONFIGFILESMSG" : "Pronađene su sljedeće konfiguracijske datoteke: ",
		"DICTIONARIESMSG" : "Broj omogućenih rječnika je: ",
		"INSYNC": "Svi čvorovi su sinhronizirani",
		"OUTOFSYNC": "Broj čvorova izvan sinhronizma je: ",
		"NOTBLOCKED": "Nema blokiranih čvorova",
		"BLOCKED": "Broj blokiranih čvorova je: ",
		"INDATE": "Svi čvorovi su važeći",
		"OUTOFDATE": "Broj čvorova koji su istekli je: ",
		"NUMOFDOCS": "Broj dokumenata u bazi podataka je ",
		"FILESTOCONVERT": "Broj dokumenata datoteke za pretvaranje je ",
		"CONVERTEDFILES": "Broj pretvorenih datoteka je ",
		"TOTALFILES": "Ukupni broj datoteka u bazi podataka ",
		"ERROR":"Greška",
		"ERROR_PREFIX":"Greška:",
		"INFO":"Informacije",
		"INFO_PREFIX":"Informacije:",
		"WARNING":"Upozorenje",
		"WARNING_PREFIX":"Upozorenje:",
		"LOADING_MESSAGE": "Učitavanje",
		"SERVER_STATUS": "Status servera",
		"INITIAL_INDEXING_EXCEPTIONS": "Izuzetak početnog indeksiranja",
		"SYS_OUT_EXCEPTIONS": "Izuzetak SystemOut zapisivanja",
		"SEEDLIST_VALIDATE": "Seedlists provjera",
		"ERRORS_DURING_INITIAL_INDEXING":"Sljedeće su se iznimke desile tokom kreiranja početnog indeksa",
		"CRAWL_FAILED": "Svi podaci za sljedeću ulogu ne mogu biti pretraženi: ",
		"EXCEPTION_ENCOUNTERED": "Pretraživanje je neuspješno sa sljedećom porukom: ",
		"SAND_VALIDATE": "SAND provjera",
		"CHECK_FOR_SAND_FILES":"Provjera za SAND datoteke",
		"IS_FILE_AVAILABLE":"Provjera da je datoteka kreirana: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Sljedeće su se iznimke desile tokom kreiranja početnog indeksa",
		"CRAWL_FAILED":"Svi podaci za sljedeću ulogu ne mogu biti pretraženi: ",
		"EXCEPTION_ENCOUNTERED":"Pretraživanje je neuspješno sa sljedećom porukom: "
});

