/* Copyright IBM Corp. 2008, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Се бара наслов",
	nourl: "Се бара Url-адреса",
	invalidUrl: "Ова не е важечка URL-адреса за заедницата.",
	txtHelp: "Помош",
	txtHelpTags: "Помош за ознаки",
	txtHelpTagsClose: "Затвори помош за ознаки",
	tagsall: "Сите",
	tagsyours: "Ваши",
	tagsrecent: "Најнови: ",
	tagspopular: "Популарни: ",
	tagsrecommended: "Препорачано: ",
	nothingselected: "Се бара избирање на заедница.",
	nothingselected_activity: "Се бара избирање на активност.",
	nothingselected_blogs: "Се бара избирање на блог.",
	nothingselected_all: "Не е избрана услуга или внес, обележувачот нема да се зачува.",
	nothingFeedselected: "Не е избрана услуга или внес, навестувањето на содржината нема да се зачува.",
	alertDialogTitle: "Порака",
	alertDialogOK: "ОК",
	expand: "Кликнете за да се прошири овој дел",
	collapse: "Кликнете за да се намали овој дел",
	discussThis: "Дискутирајте за ова",
	by: "од:",
	posted: "Објавено:",
	attachments: "Прилози",
	communityForum: "Форум на заедницата",
	notCommunityPage: "Тековната страница не е важечка веб-страница на заедницата. Може рачно да ги внесете насловот на заедницата, врската и описот за да креирате поврзана заедница.",
	privateCommunityNotice: "Оваа заедница е ограничена. Можат да ја видат само членовите на заедницата.",
	forumNameHint : "Напишете име на форум",
	formDescriptionHint:"Опишете зашто оваа поврзана заедница би била од интерес за вашата заедница.",
	information : "Информации",
	error : "Грешка",
	success : "Успех",
	warning : "Предупредување",
	informationColon : "Информации:",
	successColon : "Успех:",
	warningColon : "Предупредување:",
	errorColon : "Грешка:",
	feedAlreadyExist : "Навестувањето на содржината веќе постои во заедницата.",
	bookmarkAlreadyExist : "Обележувачот веќе постои во заедницата.",
	mentionAuthWarning:"Следниве лица кои се споменати нема да можат да ја видат пораката затоа што не се членови на заедницата:",
	mentionAuthForumWarning:"Следниве лица кои се споменати нема да можат да ја видат пораката затоа што немаат пристап до форумот:",
	exceedDescLength: "Описот кој го внесовте е премногу долг.",
	communities_checked:"${0} избрани заедници",
	activities_checked:"${0} избрани активности",
	blogs_checked:"${0} избрани блогови"
})

