define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Zatvoriť",
		   'rs_loading' : "Načítava sa...",
		   'rs_at' : "o",
		   'rs_searchDirectory' : "Osoba sa nezobrazila? Použite úplné vyhľadávanie...",
		   'rs_searchGroupDirectory' : "Skupina sa nezobrazila? Použite úplné vyhľadávanie...",
		   'rs_searchPersonAndGroupDirectory' : "Osoba alebo skupina sa nezobrazila? Použite úplné vyhľadávanie...",
		   'rs_searchCommunityDirectory' : "Komunita sa nezobrazila? Použite úplné vyhľadávanie...",
		   'rs_shadowText_searchDirectory' : "Začnite písať hľadanú osobu",
		   'rs_shadowText_searchGroupDirectory' : "Začnite písať hľadanú skupinu",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Začnite písať hľadanú osobu alebo skupinu",
		   'rs_shadowText_searchCommunityDirectory' : "Začnite písať hľadanú komunitu",
		   'rs_listItem' : "Položka zoznamu",
		   'rs_noResults' : "Žiadne výsledky pre „${0}“",
		   'rs_today' : "Dnes",
		   'rs_tomorrow' : "Zajtra",
		   'rs_yesterday' : "Včera",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Informačný kanál pre tieto aktivity",
		   'rs_externalText' : "Táto aktivita môže mať členov mimo vašej organizácie.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" bolo úspešne presunuté do podkomunity \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Zobraziť viac informácií o tejto aktivite',
		   'rs_hideInfo' : 'Skryť extra informácie',
		   'rs_more' : "Viac",
		   'rs_hide' : "Skryť",
		   'rs_edit' : "Upraviť",
		   'rs_restore' : "Obnoviť",
		   'rs_deleteEntry' : "Vymazať",
		   'rs_prioritize' : "Určiť prioritu",
		   'rs_markComplete' : "Označiť ako dokončené",
		   'rs_markIncomplete' : "Obnoviť",
		   'rs_linkMore' : "... [viac]",
		   'rs_linkLess' : "... [menej]",
		   'rs_actUpdatedByDate' : "Aktualizoval ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Aktualizoval ${0}",// Updated by (author name)
		   'rs_actDue' : "Termín ${0}",// Due (date)
		   'rs_actTags' : "Značky: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Vytvoriť aktivitu z tejto šablóny",
		   'rs_favoriteTemplate' : "Označiť ako obľúbenú šablónu",
		   'rs_normalTemplate' : "Označiť ako normálnu šablónu",
		   'rs_tunedOutPri' : "Skryté",
		   'rs_pagepos' : "${0} - ${1} z ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Predchádzajúci",
		   'rs_navNextLabel' : "Ďalší",
		   'rs_noActivities' : "Pre túto komunitu nie sú spustené žiadne aktivity.",
		   'rs_feedError' : "Zlyhalo načítavanie informačného kanála.",
		   'rs_highPri' : "Vysoká priorita",
		   'rs_medPri' : "Stredná priorita",
		   'rs_normalPri' : "Normálna priorita (predvolené)",
		   'rs_tuneOut' : "Označiť ako skryté",
		   'rs_startActivity' : "Vytvoriť aktivitu",
		   'rs_startFirstActivity' : "Vytvoriť prvú aktivitu",
		   'rs_navNextLabel' : "Ďalší",
		   'rs_viewAll' : "Zobraziť všetko",
		   'rs_activityWidgetTitle' : "Aktivity",
		   'rs_activityWidgetBriefDescription' : "Sledujte ciele komunity.  Vytvorte položky zoznamu úloh a zdieľajte prostriedky.",
		   'rs_activityWidgetDescription' : "Aktivity komunity možno použiť pri spolupráci a sledovaní priebehu projektov alebo iniciatív komunity.",
		   'rs_completedActivityLink' : "Zobraziť dokončené aktivity",
		   'rs_activitiesUnavailable' : "Služba Aktivity je nedostupná.",
		   'rs_errorPersists' : "Ak problém pretrváva, kontaktujte administrátora systému.",
		   'rs_shared' : "Zdieľané",
		   'rs_removeActFromComm' : "Odstrániť z komunity",
		   'rs_externalLabel' : "Externý",
		   // for ActivityForm
		   'rs_templateOptions' : "Možnosti šablóny",
		   'rs_template' : "Šablóna",
		   'rs_tagsLabel' : "Značky",
		   'rs_peopleLabel' : "Ľudia",
		   'rs_aboutThisTemplate' : "Informácie o tejto šablóne",
		   'rs_activity' : "Aktivita",
		   'rs_copyOf' : "Kópia ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Cieľ aktivity",
		   'rs_noTemplate' : "Žiadny",
		   'rs_copyActivityMembers' : "Použiť členov z aktivity",
		   'rs_copyTemplateMembers' : "Použiť členov zo šablóny",
		   /* Forum Widget */
		   'rs_noTopics' : "Pre túto komunitu ešte nie sú žiadne témy.",
		   'rs_noTopicsLoggedIn' : "Položte otázku, opíšte náhlu inšpiráciu alebo zdieľajte svoje nápady.",
		   'rs_postedBy' : "Najnovší príspevok od",
		   'rs_topics' : "tém",
		   'rs_noTopicsShort' : "Žiadne témy",
		   'rs_topic' : "téma",
		   'rs_replies' : "odpovede",
		   'rs_noReplies' : "Žiadne odpovede",
		   'rs_reply' : "odpoveď",
		   'rs_startTopic' : "Vytvoriť tému",
		   'rs_startFirstTopic' : "Vytvoriť prvú tému",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Zamknuté]",
		   'rs_manageForumSetting' : "Manažovať nastavenia fóra",
		   'rs_forumSettingCommunityOverviewPage' : "Stránka s prehľadom komunity:",
		   'rs_defaultForumList' : "Predvolene zobraziť zoznam fór",
		   'rs_defaultTopicList' : "Predvolene zobraziť zoznam tém",
		   'rs_forumSettingApplicationView' : "Predvolené zobrazenie aplikácie fór:",
		   'rs_forumSettingNote' : "Poznámka: Ak existuje iba jedno fórum, predvolene sa zobrazia témy.",
		   'rs_forumSettingSubmit' : "Odoslať",
		   'rs_forumSettingSave' : "Uložiť",
		   'rs_forumSettingSaveAndClose' : "Uložiť a zatvoriť",
		   'rs_forumSettingConfirm' : "Vaše zmeny pre aplikáciu Fóra sa uložili.",
		   'rs_forumSettingError' : "Nastala chyba. Kontaktujte svojho administrátora.",
		   'rs_formSettingHideMessage' : "Skryť túto správu",
		   'rs_forumSettingCancel' : "Zrušiť",
		   'rs_forumAnsweredQuestion' : "Zodpovedaná otázka",
		   'rs_forumUnAnsweredQuestion' : "Nezodpovedaná otázka",
		   'rs_forumSortBy' : "Zoradiť podľa:",
		   'rs_forumSortByDate' : "Dátum",
		   'rs_forumSortByReplies' : "Odpovede",
		   'rs_forumSortByTopic' : "Témy",
		   'rs_forumSortByTopicsAndReplies' : "Témy a odpovede",
		   'rs_sortByReplies' : "Zoradiť podľa odpovedí",
		   'rs_sortbyTopicsAndReplies' : "Zoradiť podľa tém a odpovedí",
		   'rs_forumOpenQuestions' : "Otvorené otázky",
		   'rs_feedOpenQuestions' : "Informačný kanál pre tieto otvorené otázky",
		   'rs_feedAnsweredQuestions' : "Informačný kanál pre tieto zodpovedané otázky",
		   'rs_forumMessages' : "${0} správ",
		   'rs_forumLastAddedPost' : "Najnovší príspevok od ${0}",
		   'rs_forumTopics' : "${0} tém",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Vytvoriť odkaz na osobu",
		   'rs_quote' : "Citovať",
		   'rs_labelColon' : "Označenie: ",
		   'rs_personColon' : "Osoba: ",
		   'rs_personLink' : "Odkaz na osobu",
		   'rs_replace' : "Nahradiť",
		   'rs_inactivePerson' : "${0} (neaktívny)", // person's name (inactive)
		   'rs_PersonPicture' : "Obrázok ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Externý používateľ", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (externý používateľ)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Obrázok ${0} (externý používateľ)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Tento používateľ má prístup k súborom a komunitám, ktoré sú externe zdieľané.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Upozorniť iných ľudí",
		   'rs_messageColon' : "Správa: ",
		   'rs_notifyColon' : "Oznámiť: ",
		   'rs_notificationConfirm' : "Notifikačná správa bola úspešne odoslaná. ",
		   'rs_notificationFail' : "Notifikačná správa nebola odoslaná. Skúste to znova neskôr. Ak problém pretrváva, kontaktujte svojho administrátora systému.",
		   'rs_pickCommunity' : "Vybrať zo zoznamu komunít",
		   'rs_typeName' : "Napísať meno",
		   'rs_typeToFilter' : "Začnite písať a filtrovať zoznam",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Začnite písať a filtrovať zoznam",
		   'rs_filterGroupLabel' : "Vybrať skupinu",
		   'rs_noResults' : "Nenašli sa žiadne výsledky",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Zobrazuje sa ${0} výsledkov z ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Odstrániť",
		   /* Language Selector */
		   'rs_browser_setting' : "Nastavenie prehliadača",
		   'rs_customLangaugeLinkLabel' : "Vlastný jazyk",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Prejsť na stránku ${0} z ${1}",
		   "rs_jumpPageLabel" : "Prejsť na stránku",
		   'rs_pageNumLabel' : "Číslo stránky",
		   'rs_pageLabel' : "Stránka:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Značky',
		   'rs_tagCloudToggleHint' : "Kliknutím skryjete alebo zobrazíte",
		   'rs_tagCloudHelpAlt' : "Získajte pomoc k značkám",
		   'rs_tagCloudNoTags' : "Zatiaľ žiadne značky.",
		   'rs_tagCloudNoRecentTags' : "Žiadne posledné značky",
		   'rs_tagCloudNoTagsProfiles' : "Hľadať v adresári. Zobrazia sa tu značky, ktoré sú spojené s profilmi vrátenými vyhľadávaním.",
		   'rs_tagLoadingTags' : "Načítava sa obsah",
		   'rs_tagCloudSelectedTags' : "Vybraté značky",
		   'rs_tagCloudSeachDesc' : "Nájsť značku",
		   'rs_tagCloudSeach' : "Hľadať",
		   'rs_tagCloudRelatedTags' : "Súvisiace značky",
		   'rs_tagCloudRelatedTagsDescription' : "Pridajte súvisiacu značku na ďalšie spresnenie vyhľadávania",
		   'rs_tagCloudError' : 'Nastala chyba',
		   'rs_viewAsCloud' : "Zhluk",
		   'rs_viewAsCloudTitle' : "Zobraziť značky ako zhluk značiek",
		   'rs_viewAsCloudDescription' : "Značky sa zobrazia ako zhluk značiek",
		   'rs_viewAsList' : "Zoznam",
		   'rs_viewAsListTitle' : "Zobraziť značky ako sekvenčný zoznam značiek",
		   'rs_viewAsListDescription' : "Značky sa zobrazia ako sekvenčný zoznam",
		   'rs_tagCloudViewAll' : "Prehľadávať",
		   'rs_tagCloudViewAllTitle' : "Prehľadávať všetky značky",
		   'rs_normalTags' : "Aktívne značky",
		   'rs_removeTag' : "Odstrániť značku z vybratých značiek filtra",
		   'rs_clearAll' : "Vyčistiť všetko",
		   'rs_searchInputDefault' : "Začnite písať značku",
		   'rs_searchInputTagSelected' : "Napíšte ďalšiu značku",
		   'rs_relatedTagTitle' : "Zobraziť výsledky vyhľadávania značky ${0}, počet ${1}",
		   'rs_removeTagTitle' : "Odstrániť značku ${0} z vybratých značiek filtra",
		   'rs_addTagTitle' : "Filtrovať podľa značky ${0} s počtom ${1}",
		   'rs_tagDialogCloseTile' : "Zatvoriť",
		   'rs_tagDialogTitle' : "Všetky značky",
		   'rs_tagDialogPageInfo' : "Značky ${0} - ${1} z ${2}",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Prehľadávať skupiny",
		   'rs_group_browse_groups_dialog_title' : "Prehľadávať skupiny",
		   'rs_group_browse_find_groups' : "Nájsť skupiny",
		   'rs_group_browse_add_button' : "Pridať",
		   'rs_group_browse_cancel_button' : "Zrušiť",
		   'rs_group_browse_enter_string' : "Začnite písať hľadané skupiny",
		   'rs_group_browse_group_typeahead_label' : "Napíšte názov skupiny:",
		   'rs_group_browse_group_name' : "Názov skupiny:",
		   'rs_group_browse_results_label' : "Vybrať vyhovujúcu skupinu:",
		   'rs_group_browse_parent_group_label' : "Nachádzate sa v:\u00a0",
		   'rs_group_browse_next_page' : "Ďalšia stránka",
		   'rs_group_browse_previous' : "Predchádzajúci",
		   'rs_group_browse_next' : "Ďalší",
		   'rs_group_browse_paging' : "Stránkovanie",
		   'rs_group_browse_previous_page' : "Predchádzajúca stránka",
		   'rs_group_browse_group_selected' : "Vybratá skupina:",
		   'rs_group_browse_group_no_groups' : "Táto skupina neobsahuje žiadne skupiny",
		   'rs_group_browse_page_info' : "${0} - ${1} z ${2}",
		   'rs_group_browse_page_info_alt' : "Vyhovujúce skupiny ${0} - ${1} z ${2}",
		   'rs_group_browse_remove_selection' : 'Odstrániť výber vnorených skupín: ${0}',
		   'rs_group_browse_paging' : "Stránkovanie",
		   'rs_member_groups' : "Skupiny",
		   'rs_member_members' : "Členovia",
		   'rs_member_no_results' : "Nenašli sa žiadne výsledky",
		   'rs_member_remove_group' : "Odstrániť ${0}",
		   'rs_member_add_to_community' : "Kliknutím pridáte člena",
		   'rs_member_remove_name' : "Kliknutím odstránite člena",
		   'rs_group_add_to_community' : "Kliknutím pridáte skupinu",
		   'rs_group_remove_name' : "Kliknutím odstránite skupinu",
		   'rs_group_name' : "Názov skupiny",
		   'rs_group_role' : "Rola skupiny",
		   'rs_warning' : "Upozornenie",
		   'rs_a11y_warning' : "Varovanie:",
		   'rs_messagebox_close_btn_title' : "Zatvoriť",
		   'rs_messagebox_close_btn_alt' : "Zatvoriť",
		   'rs_messagebox_error_icon_alt' : "Chyba",
		   'rs_messagebox_error_a11y_label' : "Chyba:",
		   'rs_messagebox_warning_icon_alt' : "Upozornenie",
		   'rs_messagebox_warning_a11y_label' : "Varovanie:",
		   'rs_messagebox_info_icon_alt' : "Informácie",
		   'rs_messagebox_info_a11y_label' : "Informácie:",
		   'rs_messagebox_success_icon_alt' : "Úspech",
		   'rs_messagebox_success_a11y_label' : "Úspech:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Vložiť odkaz na Súbory",
		   'rs_docpicker_label' : "Odkaz na Súbory",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Prevziať ${0}",
		   'rs_docpicker_viewdetails_text' : "Zobraziť podrobnosti",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Zobraziť podrobnosti ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Odstrániť",
		   'rs_attachedfile_filename' : "Obrázok ${0}",
		   'rs_feedreader_warning' : "Varovanie: Tento odkaz je určený pre čítačky informačných kanálov a vo vašom prehliadači sa môže zobraziť nesprávne. Ak chcete pokračovať, kliknite na položku OK. Ak sa chcete vrátiť na stránku, kliknite na položku Zrušiť.",
		   'rs_search' : "Hľadať",
		   'rs_all_connections' : "Všetky pripojenia",
		   'rs_advanced' : "Rozšírené",
		   'rs_select_scope' : "Vybrať rozsah vyhľadávania",
		   'rs_icfixlayout' : {
		      button_label : "Preformátovať",
		      dialog_title : "Preformátovať obsah",
		      warning : "Upozornenie",
		      reformat_save : "Preformátovať a uložiť",
		      save_as_is : "Uložiť ako je",
		      cancel : "Zrušiť",
		      warn_layout : "Váš obsah prekračuje maximálnu šírku zobrazenia.  Má sa automaticky preformátovať a prispôsobiť dostupnému priestoru?",
		      remember_decision : "Zapamätať si moje rozhodnutie"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Nastala chyba počas zdieľania vybratých súborov.",
		   'rs_sharefile_access_denied' : "Tento súbor bol vymazaný alebo už s vami nie je zdieľaný.",
		   'rs_sharefile_invalid_request' : "Nastala chyba počas zdieľania vybratých súborov.",
		   'rs_sharefile_sharing_intent_restriction' : "Súbor sa dá zdieľať iba vnútri vašej organizácie.",
		   'rs_sharefile_error_title' : "Chyba",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'V obchode App Store',
		   'rs_mobileBanner_inGooglePlay' : 'V obchode Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Otvoriť',
		   'rs_mobileBanner_view' : 'Zobraziť',
		   'rs_mobileBanner_hide' : 'Skryť',

		   'rs_empty_column_placeholder' : 'Sem potiahnite appky.',
		   'rs_widget_loading_error_title' : 'Nemožno zobraziť widget',
		   'rs_widget_loading_error_message' : 'Skúste to znova neskôr. Ak problém pretrváva, kontaktujte svojho administrátora systému.',
		   'rs_widgets_loading_error_title' : 'Nemožno zobraziť widgety v tejto komunite',
		   'rs_widget_misplacement_warning' : 'Táto aplikácia sa nezmestí do tohto stĺpca. Vlastník komunity ju môže presunúť do iného stĺpca alebo ju odstrániť zo stránky.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Nadpis, ktorý ste zadali, je pridlhý.',
		      empty_new_title : 'Nadpis, ktorý ste zadali, nemôže byť prázdny.',
		      default_message : 'Nemožno zmeniť nadpis pre túto aplikáciu ${0}.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Nadpis:  ',
		   'rs_widget_title_change_direction' : 'Zmeňte nadpis pre túto aplikáciu ${0}.',
		   'rs_widget_title_change_title' : 'Zmeniť nadpis',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Pozvať alebo pridať členov",
		   'rs_vmmainContentDesc' : "Pozvite členov, aby ste im dali príležitosť pripojiť sa do komunity. Pridajte členov, ak ich chcete automaticky zahrnúť.",
		   'rs_vmtypeAheadLabel' : "Meno alebo e-mailová adresa: ",
		   'rs_vmgroupTypeAheadLabel' : "Názov: ",
		   'rs_vmtypeAheadRoleLabel' : " ako ",
		   'rs_vmgroupTypeAheadRoleLabel' : " ako členovia ",
		   'rs_vmtaNoResults' : "Nenašli sa žiadne výsledky.",
		   'rs_vmtaHeader' : "hlavička",
		   'rs_vmaddUser' : "Pridať",
		   'rs_vmradioSectionTitle' : "Voľby pre člena:",
		   'rs_vmradioOne' : "Poslať pozvania na pripojenie do komunity",
		   'rs_vmradioTwo' : "Automaticky pridať používateľov do komunity",
		   'rs_vmtwistyA' : "Pridať voliteľnú správu",
		   'rs_vmtwistyB' : "Odstrániť ďalší text",
		   'rs_vmmessage' : "Správa:",
		   'rs_vmtextAreaStartText' : "Povedzte niečo...",
		   'rs_vmcheckboxLabel' : "Poslať mi kópiu",
		   'rs_vmsave' : "Uložiť",
		   'rs_vminvite' : "Pozvať",
		   'rs_vmcancel' : "Zrušiť",
		   'rs_userContentTitle' : "Zadajte informácie",
		   'rs_vmaddUser' : "Vytvoriť používateľa",
		   'rs_vmback'	 : "Späť",
		   'rs_vmvisitor'	 : "Návštevník",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Kliknite tu, ak chcete kopírovať túto komunitu',
			'rs_commpicker' : ''

});
