/* Copyright IBM Corp. 2014, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8

define({
		UPDATED_BY: "Ažurirao korisnik ${author}",
		PREVIEW_MODE_ONLY: "(Samo režim pregleda)",
		//Community
		COMMUNITY_VIEWED_TODAY: "Zajednica pregledana danas",
		COMMUNITY_VIEWED_YESTERDAY: "Zajednica pregledana juče",
		COMMUNITY_VIEWED_HOURS_AGO: "Zajednica pregledana pre ${hours} sati",
		COMMUNITY_VIEWED_MINUTES_AGO: "Zajednica pregledana pre ${minutes} minuta",
		COMMUNITY_VIEWED_SECONDS_AGO: "Zajednica pregledana pre ${seconds} sekundi",
		COMMUNITY_VIEWED_1_HOUR_AGO: "Zajednica pregledana pre 1 sat",
		COMMUNITY_VIEWED_1_MINUTE_AGO: "Zajednica pregledana pre 1 minut",
		COMMUNITY_VIEWED_1_SECOND_AGO: "Zajednica pregledana pre 1 sekundu",
		COMMUNITY_VIEWED_AT_DATE: "Zajednica pregledana dana ${date}",
		//File
		FILE_VIEWED_TODAY: "Datoteka pregledana danas",
		FILE_VIEWED_YESTERDAY: "Datoteka pregledana juče",
		FILE_VIEWED_HOURS_AGO: "Datoteka pregledana pre ${hours} sati",
		FILE_VIEWED_MINUTES_AGO: "Datoteka pregledana pre ${minutes} minuta",
		FILE_VIEWED_SECONDS_AGO: "Datoteka pregledana pre ${seconds} sekundi",
		FILE_VIEWED_1_HOUR_AGO: "Datoteka pregledana pre 1 sat",
		FILE_VIEWED_1_MINUTE_AGO: "Datoteka pregledana pre 1 minut",
		FILE_VIEWED_1_SECOND_AGO: "Datoteka pregledana pre 1 sekundu",
		FILE_VIEWED_AT_DATE: "Datoteka pregledana dana ${date}",
		//Profile
		PROFILE_VIEWED_TODAY: "Profil pregledan danas",
		PROFILE_VIEWED_YESTERDAY: "Profil pregledan juče",
		PROFILE_VIEWED_HOURS_AGO: "Profil pregledan pre ${hours} sati",
		PROFILE_VIEWED_MINUTES_AGO: "Profil pregledan pre ${minutes} minuta",
		PROFILE_VIEWED_SECONDS_AGO: "Profil pregledan pre ${seconds} sekundi",
		PROFILE_VIEWED_1_HOUR_AGO: "Profil pregledan pre 1 sat",
		PROFILE_VIEWED_1_MINUTE_AGO: "Profil pregledan pre 1 minut",
		PROFILE_VIEWED_1_SECOND_AGO: "Profil pregledan pre 1 sekundu",
		PROFILE_VIEWED_AT_DATE: "Profil pregledan dana ${date}",
		//Activity
		ACTIVITY_VIEWED_TODAY: "Aktivnost pregledana danas",
		ACTIVITY_VIEWED_YESTERDAY: "Aktivnost pregledana juče",
		ACTIVITY_VIEWED_HOURS_AGO: "Aktivnost pregledana pre ${hours} sati",
		ACTIVITY_VIEWED_MINUTES_AGO: "Aktivnost pregledana pre ${minutes} minuta",
		ACTIVITY_VIEWED_SECONDS_AGO: "Aktivnost pregledana pre ${seconds} sekundi",
		ACTIVITY_VIEWED_1_HOUR_AGO: "Aktivnost pregledana pre 1 sat",
		ACTIVITY_VIEWED_1_MINUTE_AGO: "Aktivnost pregledana pre 1 minut",
		ACTIVITY_VIEWED_1_SECOND_AGO: "Aktivnost pregledana pre 1 sekundu",
		ACTIVITY_VIEWED_AT_DATE: "Aktivnost pregledana dana ${date}",
		//Bookmark
		BOOKMARK_VIEWED_TODAY: "Obeleživač pregledan danas",
		BOOKMARK_VIEWED_YESTERDAY: "Obeleživač pregledan juče",
		BOOKMARK_VIEWED_HOURS_AGO: "Obeleživač pregledan pre ${hours} sati",
		BOOKMARK_VIEWED_MINUTES_AGO: "Obeleživač pregledan pre ${minutes} minuta",
		BOOKMARK_VIEWED_SECONDS_AGO: "Obeleživač pregledan pre ${seconds} sekundi",
		BOOKMARK_VIEWED_1_HOUR_AGO: "Obeleživač pregledan pre 1 sat",
		BOOKMARK_VIEWED_1_MINUTE_AGO: "Obeleživač pregledan pre 1 minut",
		BOOKMARK_VIEWED_1_SECOND_AGO: "Obeleživač pregledan pre 1 sekundu",
		BOOKMARK_VIEWED_AT_DATE: "Obeleživač pregledan dana ${date}",
		//Blog
		BLOG_VIEWED_TODAY: "Blog pregledan danas",
		BLOG_VIEWED_YESTERDAY: "Blog pregledan juče",
		BLOG_VIEWED_HOURS_AGO: "Blog pregledan pre ${hours} sati",
		BLOG_VIEWED_MINUTES_AGO: "Blog pregledan pre ${minutes} minuta",
		BLOG_VIEWED_SECONDS_AGO: "Blog pregledan pre ${seconds} sekundi",
		BLOG_VIEWED_1_HOUR_AGO: "Blog pregledan pre 1 sat",
		BLOG_VIEWED_1_MINUTE_AGO: "Blog pregledan pre 1 minut",
		BLOG_VIEWED_1_SECOND_AGO: "Blog pregledan pre 1 sekundu",
		BLOG_VIEWED_AT_DATE: "Blog pregledan dana ${date}",
		//Forum
		FORUM_VIEWED_TODAY: "Forum pregledan danas",
		FORUM_VIEWED_YESTERDAY: "Forum pregledan juče",
		FORUM_VIEWED_HOURS_AGO: "Forum pregledan pre ${hours} sati",
		FORUM_VIEWED_MINUTES_AGO: "Forum pregledan pre ${minutes} minuta",
		FORUM_VIEWED_SECONDS_AGO: "Forum pregledan pre ${seconds} sekundi",
		FORUM_VIEWED_1_HOUR_AGO: "Forum pregledan pre 1 sat",
		FORUM_VIEWED_1_MINUTE_AGO: "Forum pregledan pre 1 minut",
		FORUM_VIEWED_1_SECOND_AGO: "Forum pregledan pre 1 sekundu",
		FORUM_VIEWED_AT_DATE: "Forum pregledan dana ${date}",
		//Wiki
		WIKI_VIEWED_TODAY: "Viki pregledana danas",
		WIKI_VIEWED_YESTERDAY: "Viki pregledana juče",
		WIKI_VIEWED_HOURS_AGO: "Viki pregledana pre ${hours} sati",
		WIKI_VIEWED_MINUTES_AGO: "Viki pregledana pre ${minutes} minuta",
		WIKI_VIEWED_SECONDS_AGO: "Viki pregledana pre ${seconds} sekundi",
		WIKI_VIEWED_1_HOUR_AGO: "Viki pregledana pre 1 sat",
		WIKI_VIEWED_1_MINUTE_AGO: "Viki pregledana pre 1 minut",
		WIKI_VIEWED_1_SECOND_AGO: "Viki pregledana pre 1 sekundu",
		WIKI_VIEWED_AT_DATE: "Viki pregledana dana ${date}",
		//Event
		EVENT_VIEWED_TODAY: "Događaj pregledan danas",
		EVENT_VIEWED_YESTERDAY: "Događaj pregledan juče",
		EVENT_VIEWED_HOURS_AGO: "Događaj pregledan pre ${hours} sati",
		EVENT_VIEWED_MINUTES_AGO: "Događaj pregledan pre ${minutes} minuta",
		EVENT_VIEWED_SECONDS_AGO: "Događaj pregledan pre ${seconds} sekundi",
		EVENT_VIEWED_1_HOUR_AGO: "Događaj pregledan pre 1 sat",
		EVENT_VIEWED_1_MINUTE_AGO: "Događaj pregledan pre 1 minut",
		EVENT_VIEWED_1_SECOND_AGO: "Događaj pregledan pre 1 sekundu",
		EVENT_VIEWED_AT_DATE: "Događaj pregledan dana ${date}",
		//To Do
		TODO_VIEWED_TODAY: "Zadata stavka pregledana danas",
		TODO_VIEWED_YESTERDAY: "Zadata stavka pregledana juče",
		TODO_VIEWED_HOURS_AGO: "Zadata stavka pregledana pre ${hours} sati",
		TODO_VIEWED_MINUTES_AGO: "Zadata stavka pregledana pre ${minutes} minuta",
		TODO_VIEWED_SECONDS_AGO: "Zadata stavka pregledana pre ${seconds} sekundi",
		TODO_VIEWED_1_HOUR_AGO: "Zadata stavka pregledana pre 1 sat",
		TODO_VIEWED_1_MINUTE_AGO: "Zadata stavka pregledana pre 1 minut",
		TODO_VIEWED_1_SECOND_AGO: "Zadata stavka pregledana pre 1 sekundu",
		TODO_VIEWED_AT_DATE: "Zadata stavka pregledana dana ${date}",
		//Survey
		SURVEY_VIEWED_TODAY: "Anketa prikazana danas",
		SURVEY_VIEWED_YESTERDAY: "Anketa prikazana juče",
		SURVEY_VIEWED_HOURS_AGO: "Anketa prikazana pre ovoliko sati: ${hours}",
		SURVEY_VIEWED_MINUTES_AGO: "Anketa prikazana pre ovoliko minuta: ${minutes}",
		SURVEY_VIEWED_SECONDS_AGO: "Anketa prikazana pre ovoliko sekundi: ${seconds}",
		SURVEY_VIEWED_1_HOUR_AGO: "Anketa prikazana pre 1 sat",
		SURVEY_VIEWED_1_MINUTE_AGO: "Anketa prikazana pre 1 minut",
		SURVEY_VIEWED_1_SECOND_AGO: "Anketa prikazana pre 1 sekunde",
		SURVEY_VIEWED_AT_DATE: "Anketa prikazana: ${date}",
		//Survey
		GENERIC_VIEWED_TODAY: "Prikazano danas",
		GENERIC_VIEWED_YESTERDAY: "Prikazano juče",
		GENERIC_VIEWED_HOURS_AGO: "Prikazano pre ovoliko sati: ${hours}",
		GENERIC_VIEWED_MINUTES_AGO: "Prikazano pre ovoliko minuta: ${minutes}",
		GENERIC_VIEWED_SECONDS_AGO: "Prikazano pre ovoliko sekundi: ${seconds}",
		GENERIC_VIEWED_1_HOUR_AGO: "Prikazano pre 1 sat",
		GENERIC_VIEWED_1_MINUTE_AGO: "Prikazano pre 1 minut",
		GENERIC_VIEWED_1_SECOND_AGO: "Prikazano pre 1 sekunde",
		GENERIC_VIEWED_AT_DATE: "Prikazano: ${date}"
});

