/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Faceți click aici pentru a vedea cartea de vizită",
	"label.semtag.hover.alt" : "Faceți clic pentru a vedea cartea de vizită pentru {0}",
	"label.semtag.hover.altA11Y" : "Faceți clic aici sau apăsați Control-Enter pentru a vizualiza cartea de vizită",
	"label.personcard.dialog.title" : "Carte de vizită pentru {0}",

	"errorDefaultMsg2" : "S-a produs o eroare. Contactaţi administratorul dvs. de sistem.",

	"loadingSTStatus" : "Se încarcă starea Sametime...",
	"noStatuAvailable" : "Nu este disponibilă nicio stare Sametime",

	"label.personcard.cardnomarkup" : "Cartea de vizită nu a putut fi preluată",
	"label.inactive.user.msg" : "Această persoană nu mai este un utilizator activ",
	"label.message.information" : "Informații:",
	"label.personcard.noprofilemsg" : "Nu există un profil pentru această persoană",
	"label.personcard.cardreqexpired" : "Solicitarea pentru obținerea cărții de vizită a expirat",

	"label.bizcard.applinks.less" : "Afișare mai puțin",
	"label.bizcard.applinks.more" : "Afișare mai mult",

	"label.personcard.activitieslink" : "Activități",
	"label.personcard.activitieslink.title" : "Faceți clic aici pentru a vedea activități partajate",
	"label.personcard.blogslink" : "Blog-uri",
	"label.personcard.blogslink.title" : "Faceți clic aici pentru a vedea blog-ul acestei persoane",
	"label.personcard.communitieslink" : "Comunități",
	"label.personcard.communitieslink.title" : "Faceți clic aici pentru a vedea comunitățile acestei persoane",
	"label.personcard.dogearlink" : "Semne de carte",
	"label.personcard.dogearlink.title" : "Faceți clic aici pentru a vedea semnele de carte ale acestei persoane",
	"label.personcard.fileslink" : "Fișiere",
	"label.personcard.fileslink.title" : "Faceți clic aici pentru a vedea fișierele partajate ale acestei persoane",
	"label.personcard.forumlink" : "Forumuri",
	"label.personcard.forumlink.title" : "Faceți clic aici pentru a vedea postările acestei persoane din forum",
	"label.personcard.homepagelink" : "Acasă",
	"label.personcard.homepagelink.title" : "Faceți clic aici pentru a vedea pagina Acasă a acestei persoane",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Faceți clic aici pentru a vedea pagina pe mobilă a acestei persoane",
	"label.personcard.newslink" : "Știri",
	"label.personcard.newslink.title" : "Faceți clic aici pentru a vedea știrile acestei persoane",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Faceți clic aici pentru a vedea profilul acestei persoane",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Faceți clic aici pentru a vedea partajările quickr ale acestei persoane",
	"label.personcard.wikislink" : "Wiki-uri",
	"label.personcard.wikislink.title" : "Faceți clic aici pentru a vedea wiki-urile acestei persoane",

	"personCardMoreActions" : "Mai multe acțiuni",
	"personCardMoreActionsAltText" : "Faceți clic pentru meniul de acțiuni",

	"label.bizcard.dismiss": "Apăsați pe tasta Escape pentru a revoca această carte de vizită.",
	"label.bizcard.fullProfile": "Profil complet",
	"label.bizcard.activities": "Activități",
	"label.bizcard.communities": "Comunități",
	"label.bizcard.files": "Fișiere",
	"label.bizcard.forums": "Forumuri",
	"label.bizcard.bookmarks": "Semne de carte",
	"label.bizcard.blogs": "Blog-uri",
	"label.bizcard.wikis": "Wiki-uri",

	"personCardAddAsColleagues" : "Invitare la Rețeaua mea",
	"personCardAddAsMyColleagues" : "Invitare la Rețeaua mea",
	"personCardFollow" : "Urmărire",
	"personCardUnfollow" : "Oprire urmărire",
	"personCardChat" : "Chat",
	"personCardCall" : "Apelare",
	"personCardSendMail" : "Trimitere e-mail",
	"personCardSendEMail" : "Trimitere e-mail",
	"personCardProxyStatusAvailable" : "Sunt disponibil",
	"personCardDownloadVCard" : "Descărcare vCard",

	"friends" : "Rețea",
	"friendsFullPageTitle" : "Rețea",
	"friendsMenuTitleAllContacts" : "Toate contactele din rețea",
	"friendsMenuTitleMyContacts" : "Contacte din Rețeaua mea",
	"friendsInvitations" : "Invitații",
	"friendsMenuTitleInCommon" : "Persoane în comun",
	"friendsShowAllCommonFriends" : "Afișare tot...",
	"friendsViewAllFriends" : "Vizualizare tot ({0})",
	"friendsSendFriendRequest" : "Trimitere solicitare",
	"friendsNoFriends" : "Niciun contact din rețea nu este asociat cu acest profil",
	"friendsColleaguesInvite" : "Invitați pe {0} să fie contactul dvs. în rețea",
	"friendsColleaguesFor" : "Contacte în rețea pentru {0}",
	"friendsNewInv" : "{0} invitație nouă",
	"friendsNewInvs" : "{0} invitații noi",
	"friendsLoading" : "Se încarcă rețeaua...",
	"friendsLoadingInv" : "Se încarcă invitații...",
	"friendsSelectFriendForRemoval" : "Selectați mai întâi contactele pe care doriți să le eliminați.",
	"friendsRemoved" : "Contact(e) în rețea eliminat(e).",
	"friendsInvSent" : "Nu a fost trimisă nicio invitație deoarece există deja una în așteptare.",
	"friendsRemovedSelected" : "Eliminare din Rețeaua mea",
	"friendsSortByDisplayName" : "Nume afișare",
	"friendsSortByRecent" : "Recent",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "E-mail alternativ:",
	"friendsNewInvitationsCount" : "Aveți {0} invitație (invitații) nouă (noi)",
	"friendsNoInv" : "Nicio invitație",
	"friendsInCommonSingle" : "Aveți {0} contacte în rețea în comun",
	"friendsInCommonMulti" : "Aveți {0} contacte în rețea în comun",
	"friendsIncludeMsgForInv" : "Includeți un mesaj cu invitația dvs.:",
	"friendsInitialMsgForInv" : "Doresc să vă adaug în lista mea de contacte din rețeaua Connections.",
	"friendsSendInvAction" : "Trimitere invitație",
	"friendsCancelInvAction" : "Anulare",
	"friendsAcceptAction" : "Acceptare",
	"friendsIgnoreAction" : "Ignorare",
	"friendsYouExceedTextLimit" : "Mesajul dvs. de invitare este prea lung. Acesta poate avea maximum {1} caractere. Sunt {0} caractere în acest câmp.",
	"friendsCannotAddYourself" : "Nu vă puteţi adăuga pe dvs. înșivă drept contact în rețea.",
	"friendsIsYourColleague" : "{0} este contactul dvs. în rețea",
	"friendsRecentlyAdded" : "Persoane pe care le-ați adăugat recent în rețeaua dvs.",
	"friendsDate" : "Dată",
	"friendsCollapseWidget" : "Faceți clic pentru a restrânge această secțiune",
	"friendsExpandWidget" : "Faceți clic pentru a extinde această secțiune",
	"friendsIsInYourNetwork" : "{0} este în rețeaua dvs.",
	"friendsActionsFor" : "Acțiuni pentru rețea",
	"friendsInviteFollowError" : "S-a produs o eroare la încercarea de a urmări pe {0}",
	"friendsInviteTagError" : "S-a produs o eroare la încercarea de a marca cu tag pe {0}",
	"friendsPleaseLogIn" : "Autentificați-vă pentru a invita persoane în rețeaua dvs.",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Invitarea la rețeaua dvs. nu este posibilă deoarece {0} este deja în rețeaua dvs.",
	"friendsInviteAddTagsFor" : "Adăugare tag-uri pentru {0}:",
	"friendsInviteAlsoFollow" : "Și urmărire",
	"friendsInviteReceiveUpdates" : "(primire actualizări)",
	"friendsInviteUpdatesDescription" : "Primiți actualizări despre persoane pe care le urmăriți în pagina Acasă și într-un rezumat de e-mailuri.",
	"friendsInviteFollowHelp": "Pentru informații suplimentare, consultați {0}Urmărirea persoanelor{1}.",
	"friendsNetwork" : "Rețea",
	"friendsMyNetwork" : "Rețea",
	"friendsNetworkFor" : "Rețea pentru {0}",
	"friendsRemoveSelected" : "Eliminare selectate",
	"friendsRemoveSelectedTip" : "Faceți clic pentru a elimina persoanele selectate din rețeaua dvs.",
	"friendsNetworkInCommon" : "Aveți {0} conexiuni de rețea în comun.",
	"friendsAddToMyNetwork" : "Doresc să vă adaug la rețeaua Connections.",
	"friendsInvite" : "Invitare la Rețeaua mea",
	"friendsInvitePerson" : "Invitați pe {0} în rețeaua dvs.",
	"friendsInviteMessage" : "Doresc să vă adaug la rețeaua mea Connections.",
	"friendsInvitedEmailSubject" : "[Profiluri] Sunteți invitat să vă alăturați rețelei mele",
	"friendsInvitedEmailMsg1" : "v-a invitat să deveniți un contact în rețea cu următorul mesaj inclus în invitație:",
	"friendsInvitedEmailMsg2" : "Deschideţi pagina dvs. Invitare în rețea",
	"friendsInvitedEmailMsg3" : "Aș dori să vă adaug în rețeaua mea.",
	"friendsInvitedEmailMsg4" : "{0} v-a invitat să deveniți un contact în rețea.",
	"friendsInvitedEmailMsg5" : "{0} v-a invitat să deveniți un contact în rețea cu mesajul următor inclus în invitație:",
	"friendsInviteLegalNote" : "Prin trimiterea acestei invitații, sunteți de acord să-i permiteți lui {0} să comenteze în panoul profilului dvs.",
	"friendsInviteFailed" : "Din cauza unei erori de server, nu a fost trimisă o notificare prin e-mail către invitat. Cu toate acestea, invitatul va putea în continuare să accepte invitația prin intermediul aplicației web Profiluri.",
	"personInNetwork" : "Contact în rețea"
})
