define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Zatvori",
		   'rs_loading' : "Učitavanje...",
		   'rs_searchDirectory' : "Osoba nije ispisana? Koristite puno pretraživanje...",
		   'rs_searchGroupDirectory' : "Grupa nije na listi? Koristite puno pretraživanje...",
		   'rs_searchPersonAndGroupDirectory' : "Osoba ili grupa nije na listi? Koristite puno pretraživanje...",
		   'rs_searchCommunityDirectory' : "Zajednica nije na listi? Koristite puno pretraživanje...",
		   'rs_shadowText_searchDirectory' : "Upišite traženu osobu",
		   'rs_shadowText_searchGroupDirectory' : "Upišite da nađete grupu",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Upišite da nađete osobu ili grupu",
		   'rs_shadowText_searchCommunityDirectory' : "Upišite traženu zajednicu",
		   'rs_listItem' : "Stavka liste",
		   'rs_noResults' : "Nema rezultata za '${0}'",
		   'rs_today' : "Danas",
		   'rs_tomorrow' : "Sutra",
		   'rs_yesterday' : "Jučer",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Tekuće informacije za ove aktivnosti",
		   'rs_externalText' : "Ova aktivnost može imati članove izvan organizacije.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" je uspješno premještena u podzajednicu \"${destCommName}\".',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Pokaži više informacija o ovoj aktivnosti',
		   'rs_hideInfo' : 'Sakrij dodatne informacije',
		   'rs_more' : "Više",
		   'rs_hide' : "Sakrij",
		   'rs_edit' : "Uredi",
		   'rs_restore' : "Vraćanje",
		   'rs_deleteEntry' : "Obriši",
		   'rs_prioritize' : "Odredi prioritet",
		   'rs_markComplete' : "Označi dovršenim",
		   'rs_markIncomplete' : "Vraćanje",
		   'rs_linkMore' : "... [više]",
		   'rs_linkLess' : "... [manje]",
		   'rs_actUpdatedByDate' : "Ažurirao ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Ažurirao ${0}",// Updated by (author name)
		   'rs_actDue' : "Dospjelo ${0}",// Due (date)
		   'rs_actTags' : "Oznake: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Pokreni aktivnost iz ovog uzorka",
		   'rs_favoriteTemplate' : "Označi kao omiljeni uzorak",
		   'rs_normalTemplate' : "Označi kao normalni šablon",
		   'rs_tunedOutPri' : "Isključeno",
		   'rs_pagepos' : "${0} - ${1} od ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Prethodno",
		   'rs_navNextLabel' : "Sljedeće",
		   'rs_noActivities' : "Nema aktivnosti pokrenutih za ovu zajednicu.",
		   'rs_feedError' : "Nije uspjelo učitavanje tekućih informacija.",
		   'rs_highPri' : "Visoki prioritet",
		   'rs_medPri' : "Srednji prioritet",
		   'rs_normalPri' : "Normalan prioritet (default)",
		   'rs_tuneOut' : "Označi kao isključeno",
		   'rs_startActivity' : "Pokreni aktivnost",
		   'rs_startFirstActivity' : "Kreirajte svoju prvu aktivnost",
		   'rs_navNextLabel' : "Sljedeće",
		   'rs_viewAll' : "Pregled svih",
		   'rs_activityWidgetTitle' : "Aktivnosti",
		   'rs_activityWidgetBriefDescription' : "Pratite ciljeve zajednice.  Kreirajte stavke zadataka i dijelite resurse.",
		   'rs_activityWidgetDescription' : "Aktivnosti zajednice se mogu koristiti za saradnju i praćenje napretka projekata ili inicijativa zajednice.",
		   'rs_completedActivityLink' : "Prikaz gotovih aktivnosti",
		   'rs_activitiesUnavailable' : "Usluga Aktivnosti je nedostupna.",
		   'rs_errorPersists' : "Ako problem ne nestane, kontaktirajte vašeg sistemskog administratora.",
		   'rs_shared' : "Dijeljeno",
		   'rs_removeActFromComm' : "Uklonite iz zajednice",
		   'rs_externalLabel' : "Vanjsko",
		   // for ActivityForm
		   'rs_templateOptions' : "Opcije šablona",
		   'rs_template' : "Šablon",
		   'rs_tagsLabel' : "Oznake",
		   'rs_peopleLabel' : "Osobe",
		   'rs_aboutThisTemplate' : "O ovom uzorku",
		   'rs_activity' : "Aktivnost",
		   'rs_copyOf' : "Kopija od ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Cilj aktivnosti",
		   'rs_noTemplate' : "Ništa",
		   'rs_copyActivityMembers' : "Koristi članove iz aktivnosti",
		   'rs_copyTemplateMembers' : "Koristi članove iz šablona",
		   /* Forum Widget */
		   'rs_noTopics' : "Još nema tema za ovu zajednicu.",
		   'rs_noTopicsLoggedIn' : "Postavite pitanje, raspravljajte ili jednostavno podijelite vaše ideje.",
		   'rs_postedBy' : "Zadnja objava od",
		   'rs_topics' : "teme",
		   'rs_noTopicsShort' : "Nema tema",
		   'rs_topic' : "tema",
		   'rs_replies' : "odgovori",
		   'rs_noReplies' : "Nema odgovora",
		   'rs_reply' : "odgovor",
		   'rs_startTopic' : "Pokreni temu",
		   'rs_startFirstTopic' : "Pokretanje prve teme",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Zaključano]",
		   'rs_manageForumSetting' : "Upravljanje postavkama foruma",
		   'rs_forumSettingCommunityOverviewPage' : "Stranica pregleda zajednice:",
		   'rs_defaultForumList' : "Pokaži listu foruma po defaultu",
		   'rs_defaultTopicList' : "Pokaži listu tema po defaultu",
		   'rs_forumSettingApplicationView' : "Default pogled aplikacije foruma:",
		   'rs_forumSettingNote' : "Napomena: Teme se prikazuju po defaultu ako postoji samo jedan forum.",
		   'rs_forumSettingSubmit' : "Pošalji",
		   'rs_forumSettingSave' : "Spremi",
		   'rs_forumSettingSaveAndClose' : "Spremi i zatvori",
		   'rs_forumSettingConfirm' : "Vaše promjene za forume su spremljene.",
		   'rs_forumSettingError' : "Došlo je do greške. Kontaktirajte vašeg administratora.",
		   'rs_formSettingHideMessage' : "Sakrij ovu poruku",
		   'rs_forumSettingCancel' : "Odustani",
		   'rs_forumAnsweredQuestion' : "Odgovoreno pitanje",
		   'rs_forumUnAnsweredQuestion' : "Neodgovoreno pitanje",
		   'rs_forumSortBy' : "Sort po:",
		   'rs_forumSortByDate' : "Datum",
		   'rs_forumSortByReplies' : "Odgovori",
		   'rs_forumSortByTopic' : "Teme",
		   'rs_forumSortByTopicsAndReplies' : "Teme i odgovori",
		   'rs_sortByReplies' : "Sort po odgovorima",
		   'rs_sortbyTopicsAndReplies' : "Sort po temama i odgovorima",
		   'rs_forumOpenQuestions' : "Otvori pitanja",
		   'rs_feedOpenQuestions' : "Tekuće informacije za ova otvorena pitanja",
		   'rs_feedAnsweredQuestions' : "Tekuće informacije za ova odgovorena pitanja",
		   'rs_forumMessages' : "${0} poruka",
		   'rs_forumLastAddedPost' : "Zadnji post od ${0}",
		   'rs_forumTopics' : "${0} tema",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Kreiraj link osobe",
		   'rs_quote' : "Citat",
		   'rs_labelColon' : "Oznaka: ",
		   'rs_personColon' : "Osoba: ",
		   'rs_personLink' : "Link osobe",
		   'rs_replace' : "Zamijeni",
		   'rs_inactivePerson' : "${0} (neaktivno)", // person's name (inactive)
		   'rs_PersonPicture' : "Slike od ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Vanjski korisnik", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (vanjski korisnik)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Slika za ${0} (vanjski korisnik)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Ovaj korisnik može pristupiti datotekama i zajednicama koje se dijele izvan organizacije.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Obavijesti druge osobe",
		   'rs_messageColon' : "Poruka: ",
		   'rs_notifyColon' : "Obavijestiti: ",
		   'rs_notificationConfirm' : "Poruka obavijesti je uspješno poslana. ",
		   'rs_notificationFail' : "Poruka obavijesti nije poslana. Pokušajte ponovo kasnije i kontaktirajte vašeg sistemskog administratora ako se problem nastavi.",
		   'rs_pickCommunity' : "Izbor s liste zajednice",
		   'rs_typeName' : "Upišite ime",
		   'rs_typeToFilter' : "Upišite za filtriranje ove liste",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Upišite za filtriranje ove liste",
		   'rs_filterGroupLabel' : "Izbor grupe",
		   'rs_noResults' : "Nisu nađeni rezultati",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Prikaz ${0} rezultata od ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Ukloni",
		   /* Language Selector */
		   'rs_browser_setting' : "Postavke pretraživača",
		   'rs_customLangaugeLinkLabel' : "Uobičajeni jezik",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Skok na stranicu ${0} od ${1}",
		   "rs_jumpPageLabel" : "Skok na stranicu",
		   'rs_pageNumLabel' : "Broj stranice",
		   'rs_pageLabel' : "Stranica:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Oznake',
		   'rs_tagCloudToggleHint' : "Kliknite za skrivanje ili pokazivanje",
		   'rs_tagCloudHelpAlt' : "Potražite pomoć za oznake",
		   'rs_tagCloudNoTags' : "Još nema oznaka",
		   'rs_tagCloudNoRecentTags' : "Nema nedavnih oznaka",
		   'rs_tagCloudNoTagsProfiles' : "Pretražite direktorij. Ovdje se prikazuju oznake pridružene profilima koje je vratilo pretraživanje.",
		   'rs_tagLoadingTags' : "Učitavanje sadržaja",
		   'rs_tagCloudSelectedTags' : "Izabrane oznake",
		   'rs_tagCloudSeachDesc' : "Pronađi oznaku",
		   'rs_tagCloudSeach' : "Traži",
		   'rs_tagCloudRelatedTags' : "Povezane oznake",
		   'rs_tagCloudRelatedTagsDescription' : "Dodajte odgovarajuću oznaku da dodatno suzite vašu pretragu",
		   'rs_tagCloudError' : 'Došlo je do greške',
		   'rs_viewAsCloud' : "Oblak",
		   'rs_viewAsCloudTitle' : "Ispis oznaka kao oblak oznaka",
		   'rs_viewAsCloudDescription' : "Pregled oznaka kao oblak oznake",
		   'rs_viewAsList' : "Lista",
		   'rs_viewAsListTitle' : "Ispis oznaka kao sekvencijalne liste oznaka",
		   'rs_viewAsListDescription' : "Pregled oznaka kao sekvencijalne liste oznaka",
		   'rs_tagCloudViewAll' : "Pregled",
		   'rs_tagCloudViewAllTitle' : "Pregled svih oznaka",
		   'rs_normalTags' : "Aktivne oznake",
		   'rs_removeTag' : "Ukloni oznaku iz izabranih oznaka filtera",
		   'rs_clearAll' : "Očisti sve",
		   'rs_searchInputDefault' : "Upišite za pronalaženje oznake",
		   'rs_searchInputTagSelected' : "Upišite drugu oznaku",
		   'rs_relatedTagTitle' : "Dodavanje oznake ${0} s brojačem ${1}",
		   'rs_removeTagTitle' : "Ukloni oznaku ${0} iz izabranih oznaka filtera",
		   'rs_addTagTitle' : "Filtrirajte prema oznaci ${0} s brojačem ${1}",
		   'rs_tagDialogCloseTile' : "Zatvori",
		   'rs_tagDialogTitle' : "Sve oznake",
		   'rs_tagDialogPageInfo' : "${0} - ${1} od ${2} oznaka",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Pregled grupa",
		   'rs_group_browse_groups_dialog_title' : "Pregled grupa",
		   'rs_group_browse_find_groups' : "Nađi grupe",
		   'rs_group_browse_add_button' : "Dodaj",
		   'rs_group_browse_cancel_button' : "Odustani",
		   'rs_group_browse_enter_string' : "Upišite da nađete grupe",
		   'rs_group_browse_group_typeahead_label' : "Upišite ime grupe:",
		   'rs_group_browse_group_name' : "Ime grupe:",
		   'rs_group_browse_results_label' : "Izbor odgovarajuće grupe:",
		   'rs_group_browse_parent_group_label' : "Vi ste u:",
		   'rs_group_browse_next_page' : "Sljedeća stranica",
		   'rs_group_browse_previous' : "Prethodno",
		   'rs_group_browse_next' : "Sljedeće",
		   'rs_group_browse_paging' : "Podjela u stranice",
		   'rs_group_browse_previous_page' : "Prošla stranica",
		   'rs_group_browse_group_selected' : "Izabrana grupa:",
		   'rs_group_browse_group_no_groups' : "Ova grupa ne sadrži nikakve grupe",
		   'rs_group_browse_page_info' : "${0} - ${1} od ${2}",
		   'rs_group_browse_page_info_alt' : "Podudarne grupe ${0} do ${1} od ${2}",
		   'rs_group_browse_remove_selection' : 'Ukloni izbor ugniježđene grupe: ${0}',
		   'rs_group_browse_paging' : "Podjela u stranice",
		   'rs_member_groups' : "Grupe",
		   'rs_member_members' : "Članovi",
		   'rs_member_no_results' : "Nisu nađeni rezultati",
		   'rs_member_remove_group' : "Ukloni ${0}",
		   'rs_member_add_to_community' : "Kliknite za dodavanje člana",
		   'rs_member_remove_name' : "Kliknite za uklanjanje člana",
		   'rs_group_add_to_community' : "Kliknite za dodavanje grupe",
		   'rs_group_remove_name' : "Kliknite za uklanjanje grupe",
		   'rs_group_name' : "Ime grupe",
		   'rs_group_role' : "Uloga grupe",
		   'rs_warning' : "Upozorenje",
		   'rs_a11y_warning' : "Upozorenje:",
		   'rs_messagebox_close_btn_title' : "Zatvori",
		   'rs_messagebox_close_btn_alt' : "Zatvori",
		   'rs_messagebox_error_icon_alt' : "Greška",
		   'rs_messagebox_error_a11y_label' : "Greška:",
		   'rs_messagebox_warning_icon_alt' : "Upozorenje",
		   'rs_messagebox_warning_a11y_label' : "Upozorenje:",
		   'rs_messagebox_info_icon_alt' : "Informacije",
		   'rs_messagebox_info_a11y_label' : "Informacije:",
		   'rs_messagebox_success_icon_alt' : "Uspjeh",
		   'rs_messagebox_success_a11y_label' : "Uspjeh:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Ubaci link na datoteke",
		   'rs_docpicker_label' : "Link na datoteke",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Preuzmi ${0}",
		   'rs_docpicker_viewdetails_text' : "Pogled na detalje",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Pogled na detalje za ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Ukloni",
		   'rs_attachedfile_filename' : "Slika ${0}",
		   'rs_feedreader_warning' : "Upozorenje: Ovaj link je namijenjen za čitaoce tekućih informacija i može biti netačno prikazana u vašem pretraživaču. Kliknite OK za nastavak ili Odustani za povratak na stranicu.",
		   'rs_search' : "Traži",
		   'rs_all_connections' : "Sve veze",
		   'rs_advanced' : "Napredno",
		   'rs_select_scope' : "Izbor obima pretraživanja",
		   'rs_icfixlayout' : {
		      button_label : "Preformatiziraj",
		      dialog_title : "Preformatiziraj sadržaj",
		      warning : "Upozorenje",
		      reformat_save : "Preformatiziraj i spremi",
		      save_as_is : "Spremi kao šta je",
		      cancel : "Odustani",
		      warn_layout : "Vaš sadržaj prelazi najveću širinu prikaza.  Da li želite automatski preformatizirati tako da stane u dostupni prostor?",
		      remember_decision : "Zapamti moju odluku"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Došlo je do greške za vrijeme dijeljenja izabranih datoteka.",
		   'rs_sharefile_access_denied' : "Ova datoteka je izbrisana ili više nije dijeljena s vama.",
		   'rs_sharefile_invalid_request' : "Došlo je do greške za vrijeme dijeljenja izabranih datoteka.",
		   'rs_sharefile_sharing_intent_restriction' : "Datoteka se može dijeliti samo unutar vaše organizacije.",
		   'rs_sharefile_error_title' : "Greška",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'Na App Store',
		   'rs_mobileBanner_inGooglePlay' : 'U Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Otvori',
		   'rs_mobileBanner_view' : 'Pogled',
		   'rs_mobileBanner_hide' : 'Sakrij',

		   'rs_empty_column_placeholder' : 'Povucite aplikacije ovdje.',
		   'rs_widget_loading_error_title' : 'Ne može prikazati widget',
		   'rs_widget_loading_error_message' : 'Pokušajte ponovo kasnije i kontaktirajte vašeg sistemskog administratora ako se problem nastavi.',
		   'rs_widgets_loading_error_title' : 'Ne može prikazati widget(e) u ovoj zajednici',
		   'rs_widget_misplacement_warning' : 'Ova aplikacija ne stane u ovu kolonu. Vlasnik zajednice je može premjestiti u drugu kolonu ili je ukloniti sa stranice.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Naslov koji ste upisali je predug.',
		      empty_new_title : 'Naslov koji ste upisali ne može biti prazan.',
		      default_message : 'Ne može se promijeniti naslov ove ${0} aplikacije.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Naslov:  ',
		   'rs_widget_title_change_direction' : 'Promijenite naslov ove ${0} aplikacije.',
		   'rs_widget_title_change_title' : 'Promijeni naslov'
});
