/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrer etter:",
"SHOW":"Vis:",
"ACL_FILTER_LABEL":"Filtrer etter synlighet",
"PARENT_FILTER_LABEL":"Filtrer etter beholder",
"TYPE_FILTER_LABEL":"Filtrer etter type",
"PAGING_TOP":"Primær sideveksling",
"PAGING_BOTTOM":"Sekundær sideveksling",
"PREVIOUS":"Forrige",
"NEXT":"Neste",
"PAGE":"Side {0} av {1}",
"PAGE_COLON":"Side:",
"RESULTS":"{span}{0} - {1}{/span} av {2}",
"ITEMS":"{0} elementer",
/* Application names */
"ACTIVITIES":"Aktiviteter",
"BLOGS":"Blogger",
"CALENDAR":"Kalender",
"COMMUNITIES":"Fellesskap",
"BOOKMARKS":"Bokmerker",
"DOGEAR":"Bokmerker",
"EVENTS":"Hendelser",
"FILES":"Filer",
"FORUMS":"Fora",
"PROFILES":"Profiler",
"WIKI":"Wikier",
"WIKIS":"Wikier",
"FEEDS":"Kanaler",
"STATUS_UPDATES":"Statusoppdateringer",
"ONECOMMENT":"1 kommentar",
"COMMENTS":"{0} kommentarer",
"ONEPERSON":"1 person",
"PEOPLE":"{0} personer",
"TAGS":"Tagger:",
"TAGSMORE":"og {0} til",
"NORESULTSMESSAGE":"Det ble ikke funnet noen resultater for søket.",
"JAN":"Januar",
"FEB":"Februar",
"MAR":"Mars",
"APR":"April",
"MAY":"Mai",
"JUN":"Juni",
"JUL":"Juli",
"AUG":"August",
"SEP":"September",
"OCT":"Oktober",
"NOV":"November",
"DEC":"Desember",
"NO_CONTACT":"Søket ble ikke utført, for det ble ikke oppnådd kontakt med serveren.",
"SERVER_ERROR":"Søket ble ikke utført på grunn av serverfeil.",
"SORT_BY":"Sorter etter:",
"SORT_RELEVANCE":"Relevans",
"SORT_DATE":"Dato",
"SORT_LAST_UPDATED":"Sist oppdatert",
"SORT_DUE_DATE":"Frist",
"SORT_VISITS":"Besøk",
"SORT_COMMENTS":"Kommentarer",
"SORT_RECOMMENDATION":"Liker",
"SORT_POPULARITY":"Popularitet",
"SORT_FIRSTNAME":"Fornavn",
"SORT_LASTNAME":"Etternavn",
"SORT_DOWNLOADS":"Nedlastinger",
"SORT_TYPE":"Type",
"SORT_SIZE":"Størrelse",
"SORT_TITLE":"Tittel",
"PRIVATE":"Privat",
"MODERATED":"Styrt",
"COMMUNITY_ACTIVITY":"Fellesskapsaktivitet",
"COMMUNITY_BLOG":"Fellesskapsblogg",
"COMMUNITY_FILE":"Fellesskapsfil",
"COMMUNITY_FORUM":"Fellesskapsforum",
"COMMUNITY_WIKI":"Fellesskapswiki",
"COMMUNITY_FEED":" Fellesskapskanal",
"COMMUNITY_BOOKMARK":"Fellesskapsbokmerke",
"NO_TAG":"Ingen tagger ennå",
"NO_DATE":"Ingen datoer ennå",
"NO_PEOPLE":"Ingen personer ennå",
"REMOVE_FILTER_LABEL":"Klikk for å fjerne",
"REMOVE_FILTER_TITLE":"Fjern",
"REMOVE_FILTER_TOOLTIP":"Fjern dette filteret",
"COMMENT_ON":"Kommentar om:",
"EXPAND_COLLAPSE":"Klikk for å utvide / komprimere",
"EXPAND":"Utvid",
"COLLAPSE":"Komprimer",
"EXPAND_MONTHS_FILTER":"Utvid månedsfilteret for år {0}",
"SORT_RELEVANCE_LABEL":"Klikk for å sortere etter relevans",
"SORT_DATE_LABEL":"Klikk for å sortere etter dato",
"SORT_UPDATED_LABEL":"Klikk for å sortere etter sist oppdatert",
"SORT_DUE_LABEL":"Klikk for å sortere etter frist",
"SORT_VISITS_LABEL":"Klikk for å sortere etter antall besøkende",
"SORT_COMMENTS_LABEL":"Klikk for å sortere etter antall kommentarer",
"SORT_RECOMMENDATIONS_LABEL":"Klikk for å sortere etter antall anbefalinger (liker)",
"SORT_POPULARITY_LABEL":"Klikk for å sortere etter popularitet",
"SORT_FIRST_NAME_LABEL":"Klikk for å sortere etter fornavn",
"SORT_LAST_NAME_LABEL":"Klikk for å sortere etter etternavn",
"RATING":"Liker",
"GRADUATED":"Forfremmet",
"ONEVOTE":"1 stemme",
"VOTES":"{0} stemmer",
"BOOKMARK_THIS_RESULT":"Legg bokmerke på dette",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inaktiv)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} personer bokmerket",
/* eg from an Activity */
"FROMANACTIVITY":"fra en aktivitet",
"FROMABLOG":"fra en blogg",
"FROMANIDEATIONBLOG":"fra en idéblogg",
"FROMANEVENT":"fra en hendelse",
"FROMAFORUM":"fra et forum",
"FROMAWIKI":"fra en wiki",
"FROMACOMMUNITY":"fra et fellesskap",
"FROMXCOMMUNITIES":"fra {0} fellesskap",
/* For search results parentage */
"ACTIVITY_ALONE":"Aktivitet",
"BLOG_ALONE":"Blogg",
"IDEATIONBLOG_ALONE":"Idéblogg",
"ENTRY_ALONE":"Innlegg",
"EVENT_ALONE":"Hendelse",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Fellesskap",
"XCOMMUNITIES_ALONE":"{0} fellesskap",
"SHAREDCOMMUNITIES":"Delt med disse fellesskapene",
"INACOMMUNITY":"i et fellesskap",
"LASTUPDATED":"Søkeindeks ble sist oppdatert:",
"NODESCRIPTION":"Ingen beskrivelse eller sammendrag for dette resultatet.",
"ATTACHMENT":"Vedlegg:",
"ACTIVITY":"Aktivitet:",
"ACTIVITYBOOKMARK":"Aktivitetsbokmerke:",
"ACTIVITYCOMMENT":"Aktivitetskommentar:",
"ACTIVITYENTRY":"Aktivitetsoppføring:",
"ACTIVITYSECTION":"Aktivitetsseksjon:",
"ACTIVITYTODO":"Aktivitetsgjøremål:",
"BLOG":"Blogg:",
"BLOGENTRY":"Bloggoppføring:",
"BLOGCOMMENT":"Bloggkommentar:",
"BOOKMARK":"Bokmerke:",
"CALENDAREVENT":"Hendelse:",
"CATEGORY":"Kategori:",
"COMMENT":"Kommentar:",
"COMMUNITY":"Fellesskap:",
"ENTRY":"Innlegg:",
"EVENTDATEON":"Den: {0}",
"EVENTISALLDAY":"Heldagshendelse",
"EVENTREPEATS":"Gjentas",
"FEED":"Kanal:",
"FILE":"Fil:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forumkategori:",
"FORUMTOPIC":"Forumemne:",
"IDEA":"Ide:",
"IDEACOMMENT":"Idekommentar:",
"IDEATIONBLOG":"Idéblogg:",
"PAGE":"Side:",
"PROFILE":"Profil:",
"SECTION":"Seksjon:",
"STATUSUPDATE":"Statusoppdatering",
"STATUSUPDATE_PREFIX":"Statusoppdatering:",
"TOPIC":"Emne:",
"TOPIC_WITH_ATTACHMENT":"Emne",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Wiki-side:",
"WIKIFILE":"Wikivedlegg:",
"SEARCH":"Søk:",
"TODO":"Huskeliste:",
"ALLRESULTS":"Alle resultater",
"PUBLICCONTENT":"Felles innhold",
"MYCONTENT":"Mitt innhold",
"RESULTNOTFOUND":"Fant du ikke det du lette etter?",
"TEMPDIFFICULTIES":"Merk: På grunn av midlertidige problemer med indekseringen omfattet ikke søket ditt {0} som var endret i løpet av siste {1} dag(er).",
"TRYLATER":"Prøv igjen senere.",
"MULTIPLETEMPDIFFICULTIES":"Merk: På grunn av midlertidige problemer med indekseringen omfattet ikke søket ditt {0} som nylig var endret",
"YOUAREAUTHOR":"Du er en forfatter",
"YOUARECONTRIBUTOR":"Du er en bidragsyter",
"YOUAREOWNER":"Du er en eier",
"YOUAREMEMBER":"Du er et medlem",
/* Profiles */
"MYNETWORK":"Mitt nettverk",
"ALLPEOPLE":"Alle personer",
"EXCLUDEINACTIVE":"Utelat inaktive personer",
"PHONE":"Telefon:",
"EMAIL":"E-post:",
/* Communities */
"ALLCOMMUNITIES":"Alle fellesskap",
"PUBLICCOMMUNITIES":"Felles fellesskap",
"MYCOMMUNITIES":"Mine fellesskap",
"EVERYTHINGCOMMUNITIES":"Alt fra fellesskap",
"COMMUNITIESONLY":"Fellesskap",
"COMMUNITIESCONTENT":"Innhold fra fellesskap",
/* Activities */
"ALLACTIVITIES":"Alle aktiviteter",
"PUBLICACTIVITIES":"Felles aktiviteter",
"MYACTIVITIES":"Mine aktiviteter",
"EVERYTHINGACTIVITIES":"Alt fra aktiviteter",
"ACTIVITIESONLY":"Aktiviteter",
"SECTIONSACTIVITIES": "Seksjoner fra aktiviteter",
"ENTRIESACTIVITIES":"Oppføringer fra aktiviteter",
"TODOSACTIVITIES":"Huskeliste fra aktiviteter",
"BOOKMARKSACTIVITIES":"Bokmerker fra aktiviteter",
"FILESACTIVITIES":"Vedlegg fra aktiviteter",
"ALLTYPESACTIVITIES":"Alle typer aktiviteter",
"COMMUNITYACTIVITIES":"Aktiviteter fra fellesskap",
"STANDALONEACTIVITIES":"Frittstående aktiviteter",
/* Forums */
"ALLFORUMS":"Alle fora",
"PUBLICFORUMS":"Felles fora",
"MYFORUMS":"Mine fora",
"EVERYTHINGFORUMS":"Alt fra fora",
"FORUMSONLY":"Fora",
"TOPICSFORUMS":"Forumemne",
"FORUMCATEGORIES": "Forumkategorier",
"FILESFORUMS":"Vedlegg fra fora",
"ALLTYPESFORUMS":"Alle typer fora",
"COMMUNITYFORUMS":"Fora fra fellesskap",
"STANDALONEFORUMS":"Frittstående fora",
/* Blogs */
"ALLBLOGS":"Alle blogger",
"PUBLICBLOGS":"Felles blogger",
"MYBLOGS":"Mine blogger",
"EVERYTHINGBLOGS":"Alt fra blogger",
"BLOGSONLY":"Blogger",
"ENTRIESBLOGS":"Blogginnlegg",
"FILESBLOGS":"Vedlegg fra blogger",
"EVERYTHINGIDEATIONBLOGS":"Alt fra idéblogger",
"BLOGSIDEATIONBLOGS":"Idéblogger",
"BLOGSIDEAS":"Ideer",
"ALLTYPESBLOGS":"Alle typer blogger",
"COMMUNITYBLOGS":"Blogger fra fellesskap",
"COMMUNITYIDEATIONBLOGS":"Idéblogger fra fellesskap",
"STANDALONEBLOGS":"Frittstående blogger",
/* Bookmarks */
"ALLBOOKMARKS":"Alle bokmerker",
"PUBLICBOOKMARKS":"Felles bokmerker",
"MYBOOKMARKS":"Mine bokmerker",
"ALLTYPESBOOKMARKS":"Alle typer bokmerker",
"COMMUNITYBOOKMARKS":"Bokmerker fra fellesskap",
"STANDALONEBOOKMARKS":"Frittstående bokmerker",
/* Files */
"ALLFILES":"Alle filer",
"PUBLICFILES":"Fellesfiler",
"MYFILES":"Mine filer",
"ALLTYPESFILES":"Alle typer filer",
"COMMUNITYFILES":"Filer fra fellesskap",
"STANDALONEFILES":"Frittstående filer",
"NUMDOWNLOADS":"{0} nedlastinger",
/* Wikis */
"ALLWIKIS":"Alle wikier",
"PUBLICWIKIS":"Felles wikier",
"MYWIKIS":"Mine wikier",
"EVERYTHINGWIKIS":"Alt fra wikier",
"WIKISONLY":"Wikier",
"PAGESWIKIS":"Wiki-sider",
"FILESWIKIS":"Vedlegg fra wikier",
"ALLTYPESWIKIS":"Alle typer wikier",
"COMMUNITYWIKIS":"Wikier fra fellesskap",
"STANDALONEWIKIS":"Frittstående wikier",
/* Status Updates */
"ALLSTATUSUPDATES":"Alle statusoppdateringer",
"PUBLICSTATUSUPDATES":"Felles statusoppdateringer",
"MYSTATUSUPDATES":"Mine statusoppdateringer",
"ALLTYPESSTATUSUPDATES":"Alle typer statusoppdateringer",
"COMMUNITYSTATUSUPDATES":"Søkeresultater fra Fellesskap",
"STANDALONESTATUSUPDATES":"Søkeresultater fra Profiler",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Denne URLen er definert som bokmerke av en rekke brukere",
"BOOKMARKEDCOMMUNITY":"Dette fellesskapet er definert som bokmerke av en rekke brukere",
"BOOKMARKEDPROFILE":"Denne profilen er definert som bokmerke av en rekke brukere",
"BOOKMARKEDBLOG":"Denne bloggen er definert som bokmerke av en rekke brukere",
"COMMUNITYBLOG":"Dette er en blogg i et fellesskap",
"BOOKMARKEDACTIVITY":"Denne aktiviteten er definert som bokmerke av en rekke brukere",
"COMMUNITYACTIVITY":"Dette er en aktivitet i et fellesskap",
"BOOKMARKEDFILE":"Denne filen er definert som bokmerke av en rekke brukere",
"COMMUNITYFILE":"Dette er en fil i et fellesskap",
"BOOKMARKED":"Denne wikien er definert som bokmerke av en rekke brukere",
"COMMUNITYWIKI":"Dette er en wiki i et fellesskap",
"BOOKMARKEDFORUM":"Dette forumet er definert som bokmerke av en rekke brukere",
"COMMUNITYFORUM":"Dette er et forum i et fellesskap",
"ALLTAGANDTTILE":"Hvis du vil se alle titlene og taggene for denne URLen, klikker du på denne knappen",
"TAGS_ARE_FROM":"Dette søkeresultatet kan omfatte tagger fra:",
"BOOKMARKS_TITLE":"Bokmerker",
"COMMUNITIES_TITLE":"Fellesskap",
"ACTIVITIES_TITLE":"Aktiviteter",
"HELP":"Hjelp",
"MORESTATUSUPDATES":"Vis flere treff på statusoppdateringer",
"TITLE_PREFIX":"tittel:",
"LATEST_MESSAGE":"Nyeste melding",
"LATEST_STATUS_UPDATE":"Nyeste statusoppdatering",
"LATEST_COMMUNITY_STATUS_UPDATE":"Nyeste statusoppdatering for fellesskap",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Nyeste statusoppdatering for fellesskap",
"SEARCH_RESULTS":"Søkeresultater for Alt innhold",
"ACTIVITIES_SEARCH_RESULTS":"Søkeresultater for Aktiviteter",
"BLOGS_SEARCH_RESULTS":"Søkeresultater for Blogger",
"BOOKMARKS_SEARCH_RESULTS":"Søkeresultater for Bokmerker",
"COMMUNITIES_SEARCH_RESULTS":"Søkeresultater for Fellesskap",
"FILES_SEARCH_RESULTS":"Søkeresultater for Filer",
"FORUMS_SEARCH_RESULTS":"Søkeresultater for Fora",
"PROFILES_SEARCH_RESULTS":"Søkeresultater for Profiler",
"DIRECTORY_SEARCH_RESULTS":"Søkeresultater for katalog for ${orgName}",
"WIKIS_SEARCH_RESULTS":"Søkeresultater for Wikier",
"STATUS_UPDATES_SEARCH_RESULTS":"Søkeresultater for Statusoppdateringer",
"VIEW_ALL":"{span}Vis alle{/span} ({0})",
"MATCHING_ONE_OF":"Som samsvarer med en av:",
"MATCHING_ALL_OF":"Som samsvarer med alle:",
"MATCHING":"Som samsvarer med:",
"MATCHING_DOC_TYPE":"Samsvarende dokumenttype:",
"BOOKMARK_HELP":"Hjelp til Bokmerke",
"CLOSE_BOOKMARK_HELP":"Lukk Hjelp til Bokmerke",
"DOCUMENT_TYPE_PREFIX":"Dokumenttype:",
"FILE_PREVIEW_ONLY":"(Bare forhåndsvisningsmodus)"
})

