/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Başlık gerekli.",
	nourl: "URL gerekli.",
	fileSchema: "Uzak ya da yerel bir dosya bağlantısı eklemek isterseniz, bu bağlantı şu biçimlerden birine uymalıdır: dosya://uzak_yol ya da dosya:///yerel_yol.",
	invalidUrl: "Bu, geçerli bir topluluk URL'si değil.",
	invalidTagChar: "Girdiğiniz etiket listesi geçersiz '&' karakteri içeriyor. Lütfen bu karakteri etiket listesinden kaldırın.",
	txtHelp: "Yardım",
	txtHelpTags: "Etiketler Yardımı",
	txtHelpTagsClose: "Etiketler Yardımını Kapat",
	tagsall: "Tümü",
	tagsyours: "Size Ait",
	tagsrecent: "En Son: ",
	tagspopular: "Sık Kullanılan: ",
	tagsrecommended: "Önerilen: ",
	nothingselected: "Bir topluluk seçimi gerekli.",
	nothingselected_activity: "Bir etkinlik seçimi gerekli.",
	nothingselected_blogs: "Bir web günlüğü seçimi gerekli.",
	nothingselected_all: "Hizmet ya da girdi seçilmedi, yer işareti kaydedilmeyecek.",
	nothingFeedselected: "Hizmet ya da girdi seçilmedi, özet akışı kaydedilmeyecek.",
	alertDialogTitle: "İleti",
	alertDialogOK: "Tamam",
	expand: "Bu bölümü genişletmek için tıklatın",
	collapse: "Bu bölümü daraltmak için tıklatın",
	discussThis: "Bunu Tartış",
	by: "Yapan:",
	posted: "Gönderen:",
	attachments: "Ekler",
	communityForum: "Topluluk Forumu",
	notCommunityPage: "Güncel web sayfası, geçerli bir topluluk web sayfası değil. İlgili bir topluluk oluşturmak için, topluluk başlığını, bağlantısını ve açıklamasını el ile ekleyebilirsiniz.",
	privateCommunityNotice: "Bu topluluk sınırlı. Yalnızca topluluğun üyeleri tarafından görülebilir.",
	forumNameHint : "Bir forum adı yazın",
	formDescriptionHint:"Bu ilgili topluluğun neden topluluğunuzun ilgisini çekeceğini açıklayın.",
	information : "Bilgi",
	error : "Hata",
	success : "Başarılı",
	warning : "Uyarı",
	informationColon : "Bilgi:",
	successColon : "Başarılı:",
	warningColon : "Uyarı:",
	errorColon : "Hata:",
	feedAlreadyExist : "Özet akışı zaten toplulukta var.",
	bookmarkAlreadyExist : "Yer işareti zaten toplulukta var.",
	mentionAuthWarning:"Aşağıdaki sözü edilen kişiler, topluluğun üyesi olmadığından bu iletiyi göremeyecekler:",
	mentionAuthForumWarning:"Aşağıdaki sözü edilen kişiler, bu foruma erişemediklerinden bu iletiyi göremeyecekler:",
	exceedDescLength: "Girdiğiniz açıklama çok uzun.",
	communities_checked:"${0} topluluk seçildi",
	activities_checked:"${0} etkinlik seçildi",
	blogs_checked:"${0} web günlüğü seçildi"
})
