/* Copyright IBM Corp. 2008, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Izenburua beharrezkoa da",
	nourl: "URLa beharrezkoa da",
	fileSchema: "Urruneko fitxategi baten edo fitxategi lokal baten esteka gehitu nahi baduzu, formatu hauetariko bat izan behar du: fitxategia://urruneko_bideizena edo fitxategia:///bideizen_lokala.",
	invalidUrl: "Hau ez da komunitateen baliozko URLa",
	txtHelp: "Laguntza",
	txtHelpTags: "Etiketak laguntza",
	txtHelpTagsClose: "Etiketak laguntza itxi",
	tagsall: "Guztiak",
	tagsyours: "Zureak",
	tagsrecent: "Duela gutxikoak: ",
	tagspopular: "Ezagunak: ",
	tagsrecommended: "Gomendatuak: ",
	nothingselected: "Komunitatea hautatzea beharrezkoa da.",
	nothingselected_activity: "Jarduera hautatzea beharrezkoa da.",
	nothingselected_blogs: "Bloga hautatzea beharrezkoa da.",
	nothingselected_all: "Ez da zerbitzurik edo sarrerarik hautatu; laster-marka ez da gordeko.",
	nothingFeedselected: "Ez da zerbitzurik edo sarrerarik hautatu; jarioa ez da gordeko.",
	alertDialogTitle: "Mezua",
	alertDialogOK: "Ados",
	expand: "Egin klik sekzioa zabaltzeko",
	collapse: "Egin klik sekzioa tolesteko",
	discussThis: "Eztabaidatu hau",
	by: "kanala:",
	posted: "Argitaratuta:",
	attachments: "Eranskinak",
	communityForum: "Komunitatearen foroa",
	notCommunityPage: "Oraingo web-orria ez da komunitate web-orri baliozkoa. Eskuz sar dezakezu komunitatearen izenburua, esteka eta deskribapena erlazionatutako komunitatea sortzeko.",
	privateCommunityNotice: "Komunitate hau murriztua da. Komunitatearen kideek baino ezin dute ikusi.",
	forumNameHint : "Idatzi foro-izen bat",
	formDescriptionHint:"Azaldu zergatik interesatuko litzaiokeen zure komunitateari erlazionatutako komunitate hau.",
	information : "Informazioa",
	error : "Errorea",
	success : "Ongi",
	warning : "Abisua",
	informationColon : "Informazioa:",
	successColon : "Ongi:",
	warningColon : "Abisua:",
	errorColon : "Errorea:",
	feedAlreadyExist : "Badago jarioa komunitatean.",
	bookmarkAlreadyExist : "Badago laster-marka komunitatean.",
	mentionAuthWarning:"Izendatutako pertsona hauek ezingo dute mezua ikusi ez direlako komunitateko kideak:",
	mentionAuthForumWarning:"Izendatutako pertsona hauek ezingo dute mezua ikusi ezin dutelako foro hau atzitu:",
	exceedDescLength: "Idatzi duzun deskribapena luzeegia da.",
	communities_checked:"${0} komunitate hautatuta",
	activities_checked:"${0} jarduera hautatuta",
	blogs_checked:"${0} blog hautatuta"
})

