/* Copyright IBM Corp. 2008, 2015  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	CONNECT_TO: "연결할 사용자 초대",
	NDYK1:"추천할 추가 사용자 없음",
	LOADING: "로드 중",
	DYK_TITLE: "알 수도 있는 사람",
	INVITE_TITLE: "연결할 사용자에게 초대 발송",
	SEND_ACTION: "발송",
	CANCEL_ACTION: "취소",
	PREV: "이전",
	NEXT: "다음",
	bpct: "귀하의 블로그에 댓글을 작성했습니다",
	bpcc: "귀하가 동일한 블로그에 댓글을 작성했습니다",
	lpfr: "지인의 동료입니다",
	lm1: "귀하는 이 사용자의 관리자입니다",
	le1: "이 사용자는 귀하의 관리자입니다",
	sdm: "귀하와 동일한 관리자를 공유합니다",
	pt: "이 사용자가 귀하를 태그했습니다",
	pbt: "귀하가 이 사용자를 태그했습니다",
	acm: "귀하와 활동을 공유합니다",
	wikiCoContribution: "귀하와 사용자가 둘 다 동일한 위키를 편집했습니다",
	bpcb: "귀하가 사용자의 블로그에 댓글을 작성했습니다",
	lpcfr: "귀하와 동료를 공유합니다",
	ccmf: "귀하와 동일한 커뮤니티에 있습니다",
	ccms: "귀하와 동일한 커뮤니티에 있습니다",
	filesharing: "귀하와 파일을 공유합니다",
	forumthreaddiscussion: "귀하와 포럼 스레드를 공유합니다",
	ctb: "귀하와 책갈피를 공유합니다",
	tgw: "귀하와 태그가 일치합니다",
	tcu: "귀하와 동일한 태그를 사용했습니다",
	pctg: "귀하와 사용자가 둘 다 동일한 사용자를 태그했습니다",
	tgb: "동일한 사람이 귀하와 사용자를 모두 태그했습니다"
})
