/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Näytä käyntikortti napsauttamalla tätä",
	"label.semtag.hover.alt" : "Näytä käyntikortti napsauttamalla: {0}",
	"label.semtag.hover.altA11Y" : "Näytä käyntikortti napsauttamalla tätä tai painamalla Control+Enter",
	"label.personcard.dialog.title" : "Käyntikortti: {0}",

	"errorDefaultMsg2" : "On ilmennyt virhe. Ota yhteys järjestelmän pääkäyttäjään.",

	"loadingSTStatus" : "Sametime-tilan lataus on meneillään...",
	"noStatuAvailable" : "Sametime-tila ei ole käytettävissä",

	"label.personcard.cardnomarkup" : "Käyntikortin nouto ei onnistunut",
	"label.inactive.user.msg" : "Tämä henkilö ei ole enää aktiivinen käyttäjä",
	"label.message.information" : "Tiedot:",
	"label.personcard.noprofilemsg" : "Tälle henkilölle ei ole profiilia",
	"label.personcard.cardreqexpired" : "Käyntikortin hakupyyntö on vanhentunut",

	"label.bizcard.applinks.less" : "Näytä vähemmän",
	"label.bizcard.applinks.more" : "Näytä enemmän",

	"label.personcard.activitieslink" : "Aktiviteetit",
	"label.personcard.activitieslink.title" : "Tarkastele yhteisiä aktiviteetteja napsauttamalla tätä",
	"label.personcard.blogslink" : "Blogit",
	"label.personcard.blogslink.title" : "Tarkastele tämän henkilön blogia napsauttamalla tätä",
	"label.personcard.communitieslink" : "Yhteisöt",
	"label.personcard.communitieslink.title" : "Tarkastele tämän henkilön yhteisöjä napsauttamalla tätä",
	"label.personcard.dogearlink" : "Kirjanmerkit",
	"label.personcard.dogearlink.title" : "Näytä tämän henkilön kirjanmerkit napsauttamalla tätä",
	"label.personcard.fileslink" : "Tiedostot",
	"label.personcard.fileslink.title" : "Tarkastele tämän henkilön jaettuja tiedostoja napsauttamalla tätä",
	"label.personcard.forumlink" : "Keskusteluryhmät",
	"label.personcard.forumlink.title" : "Tarkastele tämän henkilön keskusteluryhmäviestejä napsauttamalla tätä",
	"label.personcard.homepagelink" : "Aloitussivu",
	"label.personcard.homepagelink.title" : "Tarkastele tämän henkilön aloitussivua napsauttamalla tätä",
	"label.personcard.mobilelink" : "Mobiili",
	"label.personcard.mobilelink.title" : "Tarkastele tämän henkilön mobiilisivua napsauttamalla tätä",
	"label.personcard.newslink" : "Uutiset",
	"label.personcard.newslink.title" : "Tarkastele tämän henkilön uutisia napsauttamalla tätä",
	"label.personcard.profilelink" : "Profiili",
	"label.personcard.profilelink.title" : "Tarkastele tämän henkilön profiilia napsauttamalla tätä",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Tarkastele tämän henkilön jaettua Quickr-sisältöä napsauttamalla tätä",
	"label.personcard.wikislink" : "Wikit",
	"label.personcard.wikislink.title" : "Tarkastele tämän henkilön wikejä napsauttamalla tätä",

	"personCardMoreActions" : "Lisää toimintoja",
	"personCardMoreActionsAltText" : "Tuo toimintovalikko näkyviin napsauttamalla",

	"label.bizcard.dismiss": "Hylkää käyntikortti painamalla Esc-näppäintä.",
	"label.bizcard.fullProfile": "Koko profiili",
	"label.bizcard.activities": "Aktiviteetit",
	"label.bizcard.communities": "Yhteisöt",
	"label.bizcard.files": "Tiedostot",
	"label.bizcard.forums": "Keskusteluryhmät",
	"label.bizcard.bookmarks": "Kirjanmerkit",
	"label.bizcard.blogs": "Blogit",
	"label.bizcard.wikis": "Wikit",

	"personCardAddAsColleagues" : "Kutsu omaan verkostoon",
	"personCardAddAsMyColleagues" : "Kutsu omaan verkostoon",
	"personCardFollow" : "Seuraa",
	"personCardUnfollow" : "Lopeta seuranta",
	"personCardChat" : "Keskustele",
	"personCardCall" : "Soita",
	"personCardSendMail" : "Lähetä sähköpostia",
	"personCardSendEMail" : "Lähetä sähköpostia",
	"personCardProxyStatusAvailable" : "Olen tavoitettavissa",
	"personCardDownloadVCard" : "Lataa vCard-kortti",

	"friends" : "Verkosto",
	"friendsFullPageTitle" : "Verkosto",
	"friendsMenuTitleAllContacts" : "Kaikki verkoston yhteyshenkilöt",
	"friendsMenuTitleMyContacts" : "Oman verkoston yhteyshenkilöt",
	"friendsInvitations" : "Kutsut",
	"friendsMenuTitleInCommon" : "Yhteiset henkilöt",
	"friendsShowAllCommonFriends" : "Näytä kaikki...",
	"friendsViewAllFriends" : "Näytä kaikki ({0})",
	"friendsSendFriendRequest" : "Lähetä pyyntö",
	"friendsNoFriends" : "Tähän profiiliin ei ole liitetty verkoston yhteyshenkilöitä",
	"friendsColleaguesInvite" : "Kutsu {0} verkostosi yhteyshenkilöksi",
	"friendsColleaguesFor" : "Henkilön {0} verkoston yhteyshenkilöt",
	"friendsNewInv" : "{0} uusi kutsu",
	"friendsNewInvs" : "{0} uutta kutsua",
	"friendsLoading" : "Ladataan verkostoa...",
	"friendsLoadingInv" : "Ladataan kutsuja...",
	"friendsSelectFriendForRemoval" : "Valitse ensin yhteystiedot, jotka haluat poistaa.",
	"friendsRemoved" : "Verkoston yhteyshenkilöt on poistettu.",
	"friendsInvSent" : "Kutsua ei ole lähetetty, koska kutsu on jo odottamassa.",
	"friendsRemovedSelected" : "Poista omasta verkostosta",
	"friendsSortByDisplayName" : "Näyttönimi",
	"friendsSortByRecent" : "Viimeisimmät",
	"friendsTelephone" : "Puhelin:",
	"friendsEmail" : "Sähköposti:",
	"friendsAltEmail" : "Vaihtoehtoinen sähköposti:",
	"friendsNewInvitationsCount" : "Sinulla on {0} uutta kutsua",
	"friendsNoInv" : "Ei kutsuja",
	"friendsInCommonSingle" : "Teillä on {0} yhteinen verkoston yhteyshenkilö",
	"friendsInCommonMulti" : "Teillä on {0} yhteistä verkoston yhteyshenkilöä",
	"friendsIncludeMsgForInv" : "Sisällytä viesti kutsuun:",
	"friendsInitialMsgForInv" : "Haluaisin lisätä sinut Connections-verkostoni yhteystietoihin.",
	"friendsSendInvAction" : "Lähetä kutsu",
	"friendsCancelInvAction" : "Peruuta",
	"friendsAcceptAction" : "Hyväksy",
	"friendsIgnoreAction" : "Hylkää",
	"friendsYouExceedTextLimit" : "Kutsun viesti on liian pitkä. Siinä voi olla enintään {1} merkkiä. Kentässä on {0} merkkiä.",
	"friendsCannotAddYourself" : "Et voi lisätä itseäsi verkoston yhteyshenkilöksi.",
	"friendsIsYourColleague" : "{0} on verkostosi yhteyshenkilö",
	"friendsRecentlyAdded" : "Henkilöt, jotka olet lisännyt verkostoosi äskettäin.",
	"friendsDate" : "Päivämäärä",
	"friendsCollapseWidget" : "Pienennä verkosto-osio osa napsauttamalla",
	"friendsExpandWidget" : "Laajenna verkosto-osio osa napsauttamalla",
	"friendsIsInYourNetwork" : "{0} on verkostossasi-",
	"friendsActionsFor" : "Verkoston toiminnot",
	"friendsInviteFollowError" : "Ilmeni virhe yritettäessä seurata: {0}",
	"friendsInviteTagError" : "Ilmeni virhe yritettäessä merkitä tunnisteella: {0}",
	"friendsPleaseLogIn" : "Kirjaudu sisään, jos haluat kutsua henkilöitä verkostoosi",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Kutsua omaan verkostoosi liittymisestä ei voi lähettää, koska {0} kuuluu jo verkostoosi.",
	"friendsInviteAddTagsFor" : "Lisää tunnisteet: {0}",
	"friendsInviteAlsoFollow" : "Seuraa myös",
	"friendsInviteReceiveUpdates" : "(päivitysten vastaanotto)",
	"friendsInviteUpdatesDescription" : "Saat seuraamiasi henkilöitä koskevia päivityksiä aloitussivulla ja sähköpostitiivistelmissä.",
	"friendsInviteFollowHelp": "Lisätietoja on kohdassa {0}Käyttäjien seuraaminen{1}.",
	"friendsNetwork" : "Verkosto",
	"friendsMyNetwork" : "Verkosto",
	"friendsNetworkFor" : "Käyttäjän {0} verkosto",
	"friendsRemoveSelected" : "Poista valitut",
	"friendsRemoveSelectedTip" : "Poista valitut henkilöt verkostosta napsauttamalla tätä.",
	"friendsNetworkInCommon" : "Teillä on {0} yhteistä verkoston yhteyshenkilöä.",
	"friendsAddToMyNetwork" : "Haluaisin lisätä sinut Connections-verkostooni.",
	"friendsInvite" : "Kutsu omaan verkostoon",
	"friendsInvitePerson" : "Kutsu {0} omaan verkostoon",
	"friendsInviteMessage" : "Haluaisin lisätä sinut Connections-verkostooni.",
	"friendsInvitedEmailSubject" : "[Profiilit] Sinut on kutsuttu liittymään verkostooni",
	"friendsInvitedEmailMsg1" : "on kutsunut sinut verkostoonsa seuraavalla viestillä:",
	"friendsInvitedEmailMsg2" : "Avaa Kutsu verkostoon -sivu",
	"friendsInvitedEmailMsg3" : "Haluaisin lisätä sinut verkostooni.",
	"friendsInvitedEmailMsg4" : "{0} kutsui sinut verkostoonsa.",
	"friendsInvitedEmailMsg5" : "{0} on kutsunut sinut verkostoonsa seuraavalla kutsuviestillä:",
	"friendsInviteLegalNote" : "Lähettämällä tämän kutsun sallit henkilön {0} lisätä kommentteja profiilisi tauluun.",
	"friendsInviteFailed" : "Sähköposti-ilmoitusta ei ole lähetetty kutsutulle henkilölle palvelinvirheen takia. Kutsuttu henkilö voi kuitenkin hyväksyä kutsun Profiilit-verkkosovelluksessa.",
	"personInNetwork" : "Verkoston yhteyshenkilö"
})
