/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "单击此处可查看名片",
	"label.semtag.hover.alt" : "单击可查看 {0} 的名片",
	"label.semtag.hover.altA11Y" : "单击此处或按 Ctrl+Enter 可查看名片",
	"label.personcard.dialog.title" : "{0} 的名片",

	"errorDefaultMsg2" : "发生了错误，请与系统管理员联系",

	"loadingSTStatus" : "正在装入 Sametime 状态...",
	"noStatuAvailable" : "无可用的 Sametime 状态",

	"label.personcard.cardnomarkup" : "无法检索到名片",
	"label.inactive.user.msg" : "此人员不再是活动用户",
	"label.message.information" : "信息：",
	"label.personcard.noprofilemsg" : "没有此人员的个人档案",
	"label.personcard.cardreqexpired" : "获取名片的请求已到期",

	"label.bizcard.applinks.less" : "显示更少",
	"label.bizcard.applinks.more" : "显示更多",

	"label.personcard.activitieslink" : "活动",
	"label.personcard.activitieslink.title" : "单击此处可查看共享活动",
	"label.personcard.blogslink" : "博客",
	"label.personcard.blogslink.title" : "单击此处可查看该人员的博客",
	"label.personcard.communitieslink" : "社区",
	"label.personcard.communitieslink.title" : "单击此处可查看该人员的社区",
	"label.personcard.dogearlink" : "书签",
	"label.personcard.dogearlink.title" : "单击此处可查看该人员的书签",
	"label.personcard.fileslink" : "文件",
	"label.personcard.fileslink.title" : "单击此处可查看该人员的共享文件",
	"label.personcard.forumlink" : "论坛",
	"label.personcard.forumlink.title" : "单击此处可查看该人员的论坛帖子",
	"label.personcard.homepagelink" : "主页",
	"label.personcard.homepagelink.title" : "单击此处可查看该人员的主页",
	"label.personcard.mobilelink" : "移动",
	"label.personcard.mobilelink.title" : "单击此处可查看该人员的移动页面",
	"label.personcard.newslink" : "新闻",
	"label.personcard.newslink.title" : "单击此处可查看该人员的新闻",
	"label.personcard.profilelink" : "个人档案",
	"label.personcard.profilelink.title" : "单击此处可查看该人员的个人档案",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "单击此处可查看该人员的 Quickr 共享",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "单击此处可查看该人员的 Wiki",

	"personCardMoreActions" : "更多操作",
	"personCardMoreActionsAltText" : "单击可打开操作菜单",

	"label.bizcard.dismiss": "按 Esc 键可退出此名片。",
	"label.bizcard.fullProfile": "完整个人档案",
	"label.bizcard.activities": "活动",
	"label.bizcard.communities": "社区",
	"label.bizcard.files": "文件",
	"label.bizcard.forums": "论坛",
	"label.bizcard.bookmarks": "书签",
	"label.bizcard.blogs": "博客",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "邀请加入我的网络",
	"personCardAddAsMyColleagues" : "邀请加入我的网络",
	"personCardFollow" : "关注",
	"personCardUnfollow" : "停止关注",
	"personCardChat" : "交谈",
	"personCardCall" : "呼叫",
	"personCardSendMail" : "发送电子邮件",
	"personCardSendEMail" : "发送电子邮件",
	"personCardProxyStatusAvailable" : "我有空",
	"personCardDownloadVCard" : "下载电子名片",

	"friends" : "网络",
	"friendsFullPageTitle" : "网络",
	"friendsMenuTitleAllContacts" : "所有网络联系人",
	"friendsMenuTitleMyContacts" : "我的网络联系人",
	"friendsInvitations" : "邀请",
	"friendsMenuTitleInCommon" : "共同的人员",
	"friendsShowAllCommonFriends" : "全部显示...",
	"friendsViewAllFriends" : "查看全部 ({0})",
	"friendsSendFriendRequest" : "发送请求",
	"friendsNoFriends" : "没有与此个人档案相关联的网络联系人",
	"friendsColleaguesInvite" : "邀请 {0} 成为您的网络联系人",
	"friendsColleaguesFor" : "{0} 的网络联系人",
	"friendsNewInv" : "{0} 个新邀请",
	"friendsNewInvs" : "{0} 个新邀请",
	"friendsLoading" : "正在装入网络...",
	"friendsLoadingInv" : "正在装入邀请...",
	"friendsSelectFriendForRemoval" : "请先选择您要除去的联系人。",
	"friendsRemoved" : "网络联系人已除去。",
	"friendsInvSent" : "未发送邀请，因为邀请已暂挂。",
	"friendsRemovedSelected" : "从我的网络除去",
	"friendsSortByDisplayName" : "显示姓名",
	"friendsSortByRecent" : "最近",
	"friendsTelephone" : "电话：",
	"friendsEmail" : "电子邮件地址：",
	"friendsAltEmail" : "备用电子邮件地址：",
	"friendsNewInvitationsCount" : "您有 {0} 条新邀请",
	"friendsNoInv" : "无邀请",
	"friendsInCommonSingle" : "你们有 {0} 个共同网络联系人",
	"friendsInCommonMulti" : "你们有 {0} 个共同网络联系人",
	"friendsIncludeMsgForInv" : "在邀请中包含以下消息：",
	"friendsInitialMsgForInv" : "我希望将您添加到我的 Connections 网络联系人列表中。",
	"friendsSendInvAction" : "发送邀请",
	"friendsCancelInvAction" : "取消",
	"friendsAcceptAction" : "接受",
	"friendsIgnoreAction" : "忽略",
	"friendsYouExceedTextLimit" : "邀请消息过长。最多为 {1} 个字符。此字段包含 {0} 个字符。",
	"friendsCannotAddYourself" : "不能将您自己添加为网络联系人。",
	"friendsIsYourColleague" : "{0} 是您的网络联系人",
	"friendsRecentlyAdded" : "您最近添加到网络中的人员。",
	"friendsDate" : "日期",
	"friendsCollapseWidget" : "单击可折叠该网段",
	"friendsExpandWidget" : "单击可展开该网段",
	"friendsIsInYourNetwork" : "{0} 在您的网络中。",
	"friendsActionsFor" : "网络操作",
	"friendsInviteFollowError" : "尝试关注 {0} 时发生错误",
	"friendsInviteTagError" : "尝试对 {0} 添加标签时发生错误",
	"friendsPleaseLogIn" : "请登录以邀请他人加入您的网络",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "由于 {0} 已在您的网络中，所以无法再邀请其加入您的网络。",
	"friendsInviteAddTagsFor" : "为 {0} 添加标签：",
	"friendsInviteAlsoFollow" : "并且关注",
	"friendsInviteReceiveUpdates" : "（接收更新）",
	"friendsInviteUpdatesDescription" : "在主页和电子邮件摘要中接收有关您所关注的人员的更新。",
	"friendsInviteFollowHelp": "有关更多信息，请参阅{0}关注人员{1}。",
	"friendsNetwork" : "网络",
	"friendsMyNetwork" : "网络",
	"friendsNetworkFor" : "{0} 的网络",
	"friendsRemoveSelected" : "除去选定项",
	"friendsRemoveSelectedTip" : "单击以从网络中除去所选人员。",
	"friendsNetworkInCommon" : "你们有 {0} 个共同网络联系人。",
	"friendsAddToMyNetwork" : "我希望将您添加到我的 Connections 网络中。",
	"friendsInvite" : "邀请加入我的网络",
	"friendsInvitePerson" : "邀请 {0} 加入您的网络",
	"friendsInviteMessage" : "我希望将您添加到我的 Connections 网络中。",
	"friendsInvitedEmailSubject" : "[个人档案] 您受邀加入我的网络",
	"friendsInvitedEmailMsg1" : "邀请您成为其网络联系人，并在邀请中包含以下消息：",
	"friendsInvitedEmailMsg2" : "打开您的“网络邀请”页面",
	"friendsInvitedEmailMsg3" : "希望将您添加到我的网络中。",
	"friendsInvitedEmailMsg4" : "{0} 邀请您成为网络联系人：",
	"friendsInvitedEmailMsg5" : "{0} 邀请您成为其网络联系人，并在邀请中包含以下消息：",
	"friendsInviteLegalNote" : "通过发送此邀请，您同意让 {0} 在您的个人档案公告板上发表评论。",
	"friendsInviteFailed" : "由于发生服务器错误，电子邮件通知未发送给受邀者。但是受邀者仍可以通过“个人档案”Web 应用程序接受您的邀请。",
	"personInNetwork" : "网络联系人"
})
