/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informasjon for node: ",
		"INSTALLED": "Kontrollerer de installerte tjenestene",
		"RESUMETOKENS": "Kontrollerer gjenopptakstokener",
		"SEEDLISTS": "Kontrollerer at kjernelistene er tilgjengelige",
		"CALENDARS": "Kontrollerer at plankalenderne er konfigurert på riktig måte",
		"VARIABLES": "Kontrollerer at WebSphere-variablene er definert",
		"TASKS": "Søker etter aktiverte indekseringsoppgaver",
		"INDEXFILES": "Søker etter nødvendige filer i indeksmappen",
		"LOGS": "Ser etter feil i loggen",
		"CONFIGFILES": "Kontrollerer konfigurasjonsfilene",
		"DICTIONARIES": "Kontrollerer antall ordlister som er aktivert",
		"SYNC": "Kontrollerer status for nodene",
		"DBRECORDS": "Kontrollerer databasepostene",
		"INSTALLEDMSG": "Følgende tjenester er installert: ",
		"RESUMETOKENSMSG": "Gjenopptakstokenet for: ",
		"SEEDLISTSMSG": "Kjernelisten kunne ikke hentes for: ",
		"CALENDARSMSG": "Kontroll av plankalender vellykket: ",
		"VARIABLESMSG": "Variabel: ",
		"TASKSMSG": "Følgende oppgave er aktivert: ",
		"INDEXFILESMSG" : "Følgende filer finnes i søkeindeksmappen: ",
		"LOGSMSG" : "Se gjennom følgende feilmeldinger: ",
		"CONFIGFILESMSG" : "Følgende konfigurasjonsfiler ble funnet: ",
		"DICTIONARIESMSG" : "Antall aktiverte ordlister: ",
		"INSYNC": "Alle noder er synkronisert",
		"OUTOFSYNC": "Antall noder som ikke er synkronisert: ",
		"NOTBLOCKED": "Ingen noder er blokkert",
		"BLOCKED": "Antall blokkerte noder: ",
		"INDATE": "Alle noder har riktig dato",
		"OUTOFDATE": "Antall noder uten riktig dato: ",
		"NUMOFDOCS": "Antall dokumenter i databasen er ",
		"FILESTOCONVERT": "Antall fildokumenter å konvertere er ",
		"CONVERTEDFILES": "Antall konverterte filer er ",
		"TOTALFILES": "Totalt antall filer i databasen ",
		"ERROR":"Feil",
		"ERROR_PREFIX":"Feil:",
		"INFO":"Informasjon",
		"INFO_PREFIX":"Informasjon:",
		"WARNING":"Advarsel",
		"WARNING_PREFIX":"Advarsel:",
		"LOADING_MESSAGE": "Laster inn",
		"SERVER_STATUS": "Serverstatus",
		"INITIAL_INDEXING_EXCEPTIONS": "Unntak ved førstegangsindeksering",
		"SYS_OUT_EXCEPTIONS": "SystemOut-loggunntak",
		"SEEDLIST_VALIDATE": "Kjernelistevalidering",
		"ERRORS_DURING_INITIAL_INDEXING":"Følgende unntak oppstod ved opprettelse av en førstegangsindeks",
		"CRAWL_FAILED": "Alle dataene for følgende tjeneste kunne ikke crawles: ",
		"EXCEPTION_ENCOUNTERED": "Crawlingen mislyktes med følgende melding: ",
		"SAND_VALIDATE": "SAND-validering",
		"CHECK_FOR_SAND_FILES":"Søker etter SAND-filene",
		"IS_FILE_AVAILABLE":"Kontrollerer at filen er opprettet: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Følgende unntak oppstod ved opprettelse av en førstegangsindeks",
		"CRAWL_FAILED":"Alle dataene for følgende tjeneste kunne ikke crawles: ",
		"EXCEPTION_ENCOUNTERED":"Crawlingen mislyktes med følgende melding: "
});

