/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Kliknij tutaj, aby wyświetlić wizytówkę",
	"label.semtag.hover.alt" : "Kliknij tutaj, aby wyświetlić wizytówkę dla {0}",
	"label.semtag.hover.altA11Y" : "Kliknij tutaj lub naciśnij klawisze Ctrl-Enter, aby wyświetlić wizytówkę",
	"label.personcard.dialog.title" : "Wizytówka dla {0}",

	"errorDefaultMsg2" : "Wystąpił błąd. Skontaktuj się z administratorem systemu.",

	"loadingSTStatus" : "Ładowanie statusu Sametime...",
	"noStatuAvailable" : "Status Sametime jest niedostępny",

	"label.personcard.cardnomarkup" : "Nie można pobrać wizytówki",
	"label.inactive.user.msg" : "Ta osoba nie jest już aktywnym użytkownikiem",
	"label.message.information" : "Informacja:",
	"label.personcard.noprofilemsg" : "Profil tej osoby nie istnieje",
	"label.personcard.cardreqexpired" : "Żądanie uzyskania wizytówki utraciło ważność",

	"label.bizcard.applinks.less" : "Pokaż mniej",
	"label.bizcard.applinks.more" : "Pokaż więcej",

	"label.personcard.activitieslink" : "Działania",
	"label.personcard.activitieslink.title" : "Kliknij tutaj, aby wyświetlić współużytkowane działania",
	"label.personcard.blogslink" : "Blogi",
	"label.personcard.blogslink.title" : "Kliknij tutaj, aby wyświetlić bloga tej osoby",
	"label.personcard.communitieslink" : "Społeczności",
	"label.personcard.communitieslink.title" : "Kliknij tutaj, aby wyświetlić społeczności tej osoby",
	"label.personcard.dogearlink" : "Zakładki",
	"label.personcard.dogearlink.title" : "Kliknij tutaj, aby wyświetlić zakładkę tej osoby",
	"label.personcard.fileslink" : "Pliki",
	"label.personcard.fileslink.title" : "Kliknij tutaj, aby wyświetlić pliki współużytkowane tej osoby",
	"label.personcard.forumlink" : "Fora",
	"label.personcard.forumlink.title" : "Kliknij tutaj, aby wyświetlić wpisy tej osoby na forum",
	"label.personcard.homepagelink" : "Strona główna",
	"label.personcard.homepagelink.title" : "Kliknij tutaj, aby wyświetlić stronę główną tej osoby",
	"label.personcard.mobilelink" : "Komórkowy",
	"label.personcard.mobilelink.title" : "Kliknij tutaj, aby wyświetlić stronę tej osoby w wersji dla urządzeń mobilnych",
	"label.personcard.newslink" : "Wiadomości",
	"label.personcard.newslink.title" : "Kliknij tutaj, aby wyświetlić wiadomości tej osoby",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Kliknij tutaj, aby wyświetlić profil tej osoby",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Kliknij tutaj, aby wyświetlić zasoby współużytkowane produktu Quickr tej osoby",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "Kliknij tutaj, aby wyświetlić wiki tej osoby",

	"personCardMoreActions" : "Więcej działań",
	"personCardMoreActionsAltText" : "Kliknij, aby wyświetlić menu działania",

	"label.bizcard.dismiss": "Naciśnij klawisz Escape, aby zamknąć tę wizytówkę.",
	"label.bizcard.fullProfile": "Pełny profil",
	"label.bizcard.activities": "Działania",
	"label.bizcard.communities": "Społeczności",
	"label.bizcard.files": "Pliki",
	"label.bizcard.forums": "Fora",
	"label.bizcard.bookmarks": "Zakładki",
	"label.bizcard.blogs": "Blogi",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "Zaproś do mojej sieci",
	"personCardAddAsMyColleagues" : "Zaproś do mojej sieci",
	"personCardFollow" : "Śledź",
	"personCardUnfollow" : "Anuluj śledzenie",
	"personCardChat" : "Czat",
	"personCardCall" : "Zadzwoń",
	"personCardSendMail" : "Wyślij wiadomość e-mail",
	"personCardSendEMail" : "Wyślij wiadomość e-mail",
	"personCardProxyStatusAvailable" : "Dostępny",
	"personCardDownloadVCard" : "Pobierz plik vCard",

	"friends" : "Sieć",
	"friendsFullPageTitle" : "Sieć",
	"friendsMenuTitleAllContacts" : "Wszystkie kontakty sieciowe",
	"friendsMenuTitleMyContacts" : "Moje kontakty sieciowe",
	"friendsInvitations" : "Zaproszenia",
	"friendsMenuTitleInCommon" : "Wspólni znajomi",
	"friendsShowAllCommonFriends" : "Pokaż wszystko...",
	"friendsViewAllFriends" : "Wyświetl wszystko ({0})",
	"friendsSendFriendRequest" : "Wyślij żądanie",
	"friendsNoFriends" : "Z tym profilem nie są powiązane żadne kontakty sieciowe",
	"friendsColleaguesInvite" : "Zaproś użytkownika {0} do swojej sieci kontaktów",
	"friendsColleaguesFor" : "Kontakty sieciowe użytkownika {0}",
	"friendsNewInv" : "{0} nowe zaproszenie",
	"friendsNewInvs" : "Nowe zaproszenia: {0}",
	"friendsLoading" : "Ładowanie sieci...",
	"friendsLoadingInv" : "Ładowanie zaproszeń...",
	"friendsSelectFriendForRemoval" : "Wybierz kontakty, które chcesz usunąć w pierwszej kolejności.",
	"friendsRemoved" : "Kontakty sieciowe zostały usunięte.",
	"friendsInvSent" : "Nie można wysłać zaproszenia, ponieważ jest już ono w toku.",
	"friendsRemovedSelected" : "Usuń z mojej sieci",
	"friendsSortByDisplayName" : "Nazwa wyświetlana",
	"friendsSortByRecent" : "Ostatnio używane",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "Adres e-mail:",
	"friendsAltEmail" : "Alternatywny adres e-mail:",
	"friendsNewInvitationsCount" : "Liczba nowych zaproszeń: {0}",
	"friendsNoInv" : "Brak zaproszeń",
	"friendsInCommonSingle" : "Macie {0} wspólny kontakt sieciowy",
	"friendsInCommonMulti" : "Macie następującą liczbę wspólnych kontaktów sieciowych: {0}",
	"friendsIncludeMsgForInv" : "Dołącz wiadomość do zaproszenia:",
	"friendsInitialMsgForInv" : "Zapraszam do mojej listy kontaktów sieciowych w programie Connections.",
	"friendsSendInvAction" : "Wyślij zaproszenie",
	"friendsCancelInvAction" : "Anuluj",
	"friendsAcceptAction" : "Akceptuj",
	"friendsIgnoreAction" : "Ignoruj",
	"friendsYouExceedTextLimit" : "Wiadomość zaproszenia jest za długa. Może zawierać co najwyżej następującą liczbę znaków: {1}. Liczba znaków wpisanych w tym polu: {0}.",
	"friendsCannotAddYourself" : "Nie można dodać siebie jako kontaktu sieciowego.",
	"friendsIsYourColleague" : "{0} jest Twoim kontaktem sieciowym.",
	"friendsRecentlyAdded" : "Osoby dodane ostatnio do sieci.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Kliknij, aby zwinąć sekcję sieci",
	"friendsExpandWidget" : "Kliknij, aby rozwinąć sekcję sieci",
	"friendsIsInYourNetwork" : "Użytkownik {0} jest w Twojej sieci",
	"friendsActionsFor" : "Działania dotyczące sieci",
	"friendsInviteFollowError" : "Wystąpił błąd podczas próby śledzenia {0}",
	"friendsInviteTagError" : "Wystąpił błąd podczas próby oznaczenia {0}",
	"friendsPleaseLogIn" : "Aby zaprosić osoby do swojej sieci należy się zalogować",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Zaproszenie użytkownika {0} do Twojej sieci nie jest możliwe, ponieważ ta osoba już znajduje się w tej sieci.",
	"friendsInviteAddTagsFor" : "Dodaj znaczniki dla użytkownika {0}:",
	"friendsInviteAlsoFollow" : "Śledź również",
	"friendsInviteReceiveUpdates" : "(otrzymywanie aktualizacji)",
	"friendsInviteUpdatesDescription" : "Otrzymuj aktualizacje dotyczące śledzonych osób w komponencie Strona główna i w podsumowaniu wysyłanym za pomocą poczty elektronicznej.",
	"friendsInviteFollowHelp": "Więcej informacji na ten temat zawiera sekcja {0}Śledzenie osób{1}.",
	"friendsNetwork" : "Sieć",
	"friendsMyNetwork" : "Sieć",
	"friendsNetworkFor" : "Sieć dla {0}",
	"friendsRemoveSelected" : "Usuń wybrane",
	"friendsRemoveSelectedTip" : "Kliknij, aby usunąć wybrane osoby ze swojej sieci.",
	"friendsNetworkInCommon" : "Liczba wspólnych znajomych: {0}.",
	"friendsAddToMyNetwork" : "Zapraszam do mojej sieci kontaktów w programie Connections.",
	"friendsInvite" : "Zaproś do mojej sieci",
	"friendsInvitePerson" : "Zaproś użytkownika {0} do swojej sieci",
	"friendsInviteMessage" : "Zapraszam do mojej sieci kontaktów w programie Connections.",
	"friendsInvitedEmailSubject" : "[Profile] Zapraszam do mojej sieci",
	"friendsInvitedEmailMsg1" : "zaprasza do swojej sieci kontaktów. Do zaproszenia dołączona jest następująca wiadomość:",
	"friendsInvitedEmailMsg2" : "Otwórz stronę zaproszenia do sieci",
	"friendsInvitedEmailMsg3" : "Zapraszam do mojej sieci kontaktów.",
	"friendsInvitedEmailMsg4" : "Użytkownik {0} zaprasza Cię do swojej sieci kontaktów:",
	"friendsInvitedEmailMsg5" : "{0} zaprasza do swojej sieci kontaktów. Do zaproszenia dołączona jest następująca wiadomość:",
	"friendsInviteLegalNote" : "Wysyłając to zaproszenie, zgadzasz się, aby użytkownik {0} publikował komentarze na tablicy w Twoim profilu.",
	"friendsInviteFailed" : "Z powodu błędu serwera powiadomienie e-mail nie zostało wysłane do zapraszanej osoby. Ta osoba będzie jednak mogła zaakceptować zaproszenie przy użyciu aplikacji WWW komponentu Profile.",
	"personInNetwork" : "Kontakt sieciowy"
})
