/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "العنوان مطلوب.",
	nourl: "عنوان Url مطلوب.",
	fileSchema: "اذا كنت تريد اضافة رابط ملف عن بعد أو محلي، فانه يجب أن يتوافق مع واحد أو أكثر من النسق التالية: file://remote_path أو file:///local_path.",
	invalidUrl: "هذا ليس بعنوان URL صحيح للمجتمع.",
	invalidTagChar: "يحتوي كشف الشارات الذي قمت بإدخاله على حرف غير صحيح وهو '&'. يرجى إزالة هذا الحرف من كشف الشارات.",
	txtHelp: "‏مساعدة‏",
	txtHelpTags: "مساعدة عن شارات التعليم",
	txtHelpTagsClose: "اغلاق المساعدة عن شارات التعليم",
	tagsall: "‏كل‏",
	tagsyours: "الخاص بك",
	tagsrecent: "الأحدث: ",
	tagspopular: "الأكثر شيوعا: ",
	tagsrecommended: "المفضل: ",
	nothingselected: "يجب تحديد المجتمع.",
	nothingselected_activity: "اختيار النشاط مطلوب.",
	nothingselected_blogs: "اختيار مدونة مطلوب.",
	nothingselected_all: "لم يتم تحديد أي خدمة أو ادخال، لن يتم حفظ علامة التوقف.",
	nothingFeedselected: "لم يتم تحديد أي خدمة أو ادخال، لن يتم حفظ وحدة المعلومات المسترجعة.",
	alertDialogTitle: "الرسالة",
	alertDialogOK: "‏حسنا‏",
	expand: "اضغط لعرض هذا القسم",
	collapse: "اضغط لطي هذا القسم",
	discussThis: "المناقشة مع",
	by: "بواسطة:",
	posted: "ارسال في:",
	attachments: "الملحقات",
	communityForum: "منتدى مناقشات المجتمع",
	notCommunityPage: "صفحة الانترنت الحالية لا تعد صفحة انترنت مجتمع صحيحة. يمكنك ادخال عنوان ورابط ووصف المجتمع يدويا لتكوين مجتمع متعلق.",
	privateCommunityNotice: "هذا المجتمع مقصور. وهو يكون مرئي لأعضاء المجتمع فقط.",
	forumNameHint : "أدخل اسم المنتدى",
	formDescriptionHint:"وضح لماذا يمكن أن يكون هذا المجتمع المتعلق موضع اهتمام من المجتمع الخاص بك.",
	information : "‏المعلومات‏",
	error : "لا يمكن لوحدة الخدمة اجراء البحث الآن.  حاول اجراء البحث في وقت لاحق.",
	success : "نجاح",
	warning : "تحذير",
	informationColon : "المعلومات:",
	successColon : "نجاح:",
	warningColon : "تحذير:",
	errorColon : "خطأ:",
	feedAlreadyExist : "وحدة المعلومات المسترجعة موجودة بالفعل في المجتمع.",
	bookmarkAlreadyExist : "علامة التوقف موجودة بالفعل في المجتمع.",
	mentionAuthWarning:"لن يستطيع الأشخاص التاليين الذين تم الاشارة اليهم مشاهدة الرسالة لأنهم ليسوا أعضاء بالمجتمع:",
	mentionAuthForumWarning:"لن يستطيع الأشخاص التاليين الذين تم الاشارة اليهم مشاهدة الرسالة لأنهم لا يمكنهم التوصل الى منتدى المناقشات هذا:",
	exceedDescLength: "الوصف الذي قمت بادخاله طويل جدا.",
	communities_checked:"تم تحديد ${0} مجتمع/مجتمعات",
	activities_checked:"تم تحديد ${0} نشاط/أنشطة",
	blogs_checked:"تم تحديد ${0} مدونة/مدونات"
})
