/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Фильтр:",
		"SHOW":"Показать:",
		"ACL_FILTER_LABEL":"Фильтровать по видимости",
		"PARENT_FILTER_LABEL":"Фильтровать по контейнеру",
		"TYPE_FILTER_LABEL":"Фильтровать по типу",
		"PAGING_TOP":"Основная разбивка на страницы",
		"PAGING_BOTTOM":"Дополнительная разбивка на страницы",
		"PREVIOUS":"Назад",
		"NEXT":"Далее",
		"PAGE":"Страница {0} из {1}",
		"PAGE_COLON":"Страница:",
		"RESULTS":"{span}{0}-{1}{/span} из {2}",
		"ITEMS":"{0} элементов",
		/* Application names */
		"ACTIVITIES":"Операции",
		"BLOGS":"Блоги",
		"CALENDAR":"Календарь",
		"COMMUNITIES":"Сообщества",
		"BOOKMARKS":"Закладки",
		"DOGEAR":"Закладки",
		"EVENTS":"Мероприятия",
		"FILES":"Файлы",
		"FORUMS":"Форумы",
		"PROFILES":"Профайлы",
		"WIKI":"Вики",
		"WIKIS":"Вики",
		"FEEDS":"Ленты новостей",
		"STATUS_UPDATES":"Обновления статуса",
		"ONECOMMENT":"1 комментарий",
		"COMMENTS":"{0} комментариев",
		"ONEPERSON":"1 пользователь",
		"PEOPLE":"{0} пользователей",
		"TAGS":"Теги:",
		"TAGSMORE":"и еще {0}",
		"NORESULTSMESSAGE":"Ничего не найдено",
		"JAN":"январь",
		"FEB":"февраль",
		"MAR":"март",
		"APR":"апрель",
		"MAY":"май",
		"JUN":"июнь",
		"JUL":"июль",
		"AUG":"август",
		"SEP":"сентябрь",
		"OCT":"октябрь",
		"NOV":"ноябрь",
		"DEC":"декабрь",
		"NO_CONTACT":"Поиск не выполнен, поскольку не удалось соединиться с сервером",
		"SERVER_ERROR":"Поиск не выполнен из-за ошибки сервера",
		"SORT_BY":"Сортировать по:",
		"SORT_RELEVANCE":"степень соответствия",
		"SORT_DATE":"Дата",
		"SORT_LAST_UPDATED":"Последнее обновление",
		"SORT_DUE_DATE":"Дата выполнения",
		"SORT_VISITS":"Посещения",
		"SORT_COMMENTS":"Комментарии",
		"SORT_RECOMMENDATION":"Отметки Мне нравится",
		"SORT_POPULARITY":"Популярность",
		"SORT_FIRSTNAME":"Имя",
		"SORT_LASTNAME":"Фамилия",
		"SORT_DOWNLOADS":"Загрузки",
		"SORT_TYPE":"Тип",
		"SORT_SIZE":"Размер",
		"SORT_TITLE":"Заголовок",
		"PRIVATE":"Личный",
		"MODERATED":"Модерируемое",
		"COMMUNITY_ACTIVITY":"Операция сообщества",
		"COMMUNITY_BLOG":"Блог сообщества",
		"COMMUNITY_FILE":"Файл сообщества",
		"COMMUNITY_FORUM":"Форум сообщества",
		"COMMUNITY_WIKI":"Вики сообщества",
		"COMMUNITY_FEED":"Лента новостей сообщества",
		"COMMUNITY_BOOKMARK":"Закладка сообщества",
		"NO_TAG":"Тегов еще нет",
		"NO_DATE":"Дат еще нет",
		"NO_PEOPLE":"Пользователей пока нет",
		"REMOVE_FILTER_LABEL":"Нажмите для удаления",
		"REMOVE_FILTER_TITLE":"Удалить",
		"REMOVE_FILTER_TOOLTIP":"Удалить этот фильтр",
		"COMMENT_ON":"Комментарий к:",
		"EXPAND_COLLAPSE":"Щелкните, чтобы развернуть или свернуть",
		"EXPAND":"Развернуть",
		"COLLAPSE":"Свернуть",
		"EXPAND_MONTHS_FILTER":"Развернуть фильтр месяцев для года {0}",
		"SORT_RELEVANCE_LABEL":"Щелкните для сортировки по степени соответствия",
		"SORT_DATE_LABEL":"Щелкните для сортировки по дате",
		"SORT_UPDATED_LABEL":"Щелкните для сортировки по последнему изменению",
		"SORT_DUE_LABEL":"Щелкните для сортировки по дате выполнения",
		"SORT_VISITS_LABEL":"Щелкните для сортировки по числу посещений",
		"SORT_COMMENTS_LABEL":"Щелкните для сортировки по числу комментариев",
		"SORT_RECOMMENDATIONS_LABEL":"Щелкните для сортировки по числу отзывов 'понравилось'",
		"SORT_POPULARITY_LABEL":"Щелкните для сортировки по популярности",
		"SORT_FIRST_NAME_LABEL":"Щелкните для сортировки по указанному имени",
		"SORT_LAST_NAME_LABEL":"Щелкните для сортировки по фамилии",
		"RATING":"Отметки Мне нравится",
		"GRADUATED":"Принято",
		"ONEVOTE":"1 голос",
		"VOTES":"{0} голосов",
		"BOOKMARK_THIS_RESULT":"Добавить в закладки",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (неактивный)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} людей в закладках",
		/* eg from an Activity */
		"FROMANACTIVITY":"из операции",
		"FROMABLOG":"из блога",
		"FROMANIDEATIONBLOG":"из блога идей",
		"FROMANEVENT":"из события",
		"FROMAFORUM":"из форума",
		"FROMAWIKI":"из вики",
		"FROMACOMMUNITY":"из сообщества",
		"FROMXCOMMUNITIES":"из {0} сообществ",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Операция",
		"BLOG_ALONE":"Блог",
		"IDEATIONBLOG_ALONE":"Блог идей",
		"ENTRY_ALONE":"Запись",
		"EVENT_ALONE":"Мероприятие",
		"FORUM_ALONE":"Форум",
		"WIKI_ALONE":"Вики",
		"COMMUNITY_ALONE":"Сообщество",
		"XCOMMUNITIES_ALONE":"{0} сообществ",
		"SHAREDCOMMUNITIES":"Совместный доступ с этими сообществами",
		"INACOMMUNITY":"в сообществе",
		"LASTUPDATED":"Последнее обновление индекса поиска:",
		"NODESCRIPTION":"Для этого результата нет описания или обзора.",
		"ATTACHMENT":"Вложение:",
		"ACTIVITY":"Операция:",
		"ACTIVITYBOOKMARK":"Закладка операции:",
		"ACTIVITYCOMMENT":"Комментарий для операции:",
		"ACTIVITYENTRY":"Запись операции:",
		"ACTIVITYSECTION":"Раздел операций:",
		"ACTIVITYTODO":"Задача операции:",
		"BLOG":"Блог:",
		"BLOGENTRY":"Запись блога:",
		"BLOGCOMMENT":"Комментарий к блогу:",
		"BOOKMARK":"Закладка:",
		"CALENDAREVENT":"Мероприятие:",
		"CATEGORY":"Категория:",
		"COMMENT":"Комментарий:",
		"COMMUNITY":"Сообщество:",
		"ENTRY":"Запись:",
		"EVENTDATEON":"В: {0}",
		"EVENTISALLDAY":"Мероприятие на весь день",
		"EVENTREPEATS":"Повторения",
		"FEED":"Лента новостей:",
		"FILE":"Файл:",
		"FORUM":"Форум:",
		"FORUMCATEGORY":"Категория форума:",
		"FORUMTOPIC":"Тема форума:",
		"IDEA":"Идея:",
		"IDEACOMMENT":"Комментарий к идее:",
		"IDEATIONBLOG":"Блог идей:",
		"PAGE":"Страница:",
		"PROFILE":"Профайл:",
		"SECTION":"Раздел:",
		"STATUSUPDATE":"Обновление статуса",
		"STATUSUPDATE_PREFIX":"Обновление состояния:",
		"TOPIC":"Тема:",
		"TOPIC_WITH_ATTACHMENT":"Тема",
		"WIKITYPE":"Вики:",
		"WIKIPAGE":"Страница вики:",
		"WIKIFILE":"Вложение вики:",
		"SEARCH":"Поиск:",
		"TODO":"Задача:",
		"ALLRESULTS":"Все результаты",
		"PUBLICCONTENT":"Общедоступные материалы",
		"MYCONTENT":"Мои материалы",
		"RESULTNOTFOUND":"Не нашли то, что искали?",
		"TEMPDIFFICULTIES":"Примечание: из-за временных проблем с индексацией в поиск не включены {0}, измененные недавно ({1} дн.).",
		"TRYLATER":"Повторите попытку позже.",
		"MULTIPLETEMPDIFFICULTIES":"Примечание: из-за временных проблем с индексацией в поиск не включены {0}, измененные недавно.",
		"YOUAREAUTHOR":"Вы являетесь автором",
		"YOUARECONTRIBUTOR":"Вы являетесь участником",
		"YOUAREOWNER":"Вы являетесь владельцем",
		"YOUAREMEMBER":"Вы являетесь членом",
		/* Profiles */
		"MYNETWORK":"Моя сеть",
		"ALLPEOPLE":"Все пользователи",
		"EXCLUDEINACTIVE":"Исключить неактивных пользователей",
		"PHONE":"Телефон:",
		"EMAIL":"Электронный адрес:",
		/* Communities */
		"ALLCOMMUNITIES":"Все сообщества",
		"PUBLICCOMMUNITIES":"Общедоступные сообщества",
		"MYCOMMUNITIES":"Мои сообщества",
		"EVERYTHINGCOMMUNITIES":"Все из сообществ",
		"COMMUNITIESONLY":"Сообщества",
		"COMMUNITIESCONTENT":"Содержимое из сообществ",
		/* Activities */
		"ALLACTIVITIES":"Все операции",
		"PUBLICACTIVITIES":"Общедоступные операции",
		"MYACTIVITIES":"Мои операции",
		"EVERYTHINGACTIVITIES":"Все из операций",
		"ACTIVITIESONLY":"Операции",
		"SECTIONSACTIVITIES": "Разделы из операций",
		"ENTRIESACTIVITIES":"Записи из операций",
		"TODOSACTIVITIES":"Задачи из операций",
		"BOOKMARKSACTIVITIES":"Закладки из операций",
		"FILESACTIVITIES":"Вложения из операций",
		"ALLTYPESACTIVITIES":"Все типы операций",
		"COMMUNITYACTIVITIES":"Операции из сообществ",
		"STANDALONEACTIVITIES":"Автономные операции",
		/* Forums */
		"ALLFORUMS":"Все форумы",
		"PUBLICFORUMS":"Общедоступные форумы",
		"MYFORUMS":"Мои форумы",
		"EVERYTHINGFORUMS":"Все из форумов",
		"FORUMSONLY":"Форумы",
		"TOPICSFORUMS":"Темы форума",
		"FORUMCATEGORIES": "Категории форумов",
		"FILESFORUMS":"Вложения из форумов",
		"ALLTYPESFORUMS":"Все типы форумов",
		"COMMUNITYFORUMS":"Форумы из сообществ",
		"STANDALONEFORUMS":"Автономные форумы",
		/* Blogs */
		"ALLBLOGS":"Все блоги",
		"PUBLICBLOGS":"Общедоступные блоги",
		"MYBLOGS":"Мои блоги",
		"EVERYTHINGBLOGS":"Все из блогов",
		"BLOGSONLY":"Блоги",
		"ENTRIESBLOGS":"Записи блога",
		"FILESBLOGS":"Вложения из блогов",
		"EVERYTHINGIDEATIONBLOGS":"Все из блогов идей",
		"BLOGSIDEATIONBLOGS":"Блоги идей",
		"BLOGSIDEAS":"Идеи",
		"ALLTYPESBLOGS":"Все типы блогов",
		"COMMUNITYBLOGS":"Блоги из сообществ",
		"COMMUNITYIDEATIONBLOGS":"Блоги идей из сообществ",
		"STANDALONEBLOGS":"Автономные блоги",
		/* Bookmarks */
		"ALLBOOKMARKS":"Все закладки",
		"PUBLICBOOKMARKS":"Общедоступные закладки",
		"MYBOOKMARKS":"Мои закладки",
		"ALLTYPESBOOKMARKS":"Все типы закладок",
		"COMMUNITYBOOKMARKS":"Закладки из сообществ",
		"STANDALONEBOOKMARKS":"Автономные закладки",
		/* Files */
		"ALLFILES":"Все файлы",
		"PUBLICFILES":"Общедоступные файлы",
		"MYFILES":"Мои файлы",
		"ALLTYPESFILES":"Все типы файлов",
		"COMMUNITYFILES":"Файлы из сообществ",
		"STANDALONEFILES":"Автономные файлы",
		"NUMDOWNLOADS":"{0} загрузок",
		/* Wikis */
		"ALLWIKIS":"Все вики",
		"PUBLICWIKIS":"Общедоступные вики",
		"MYWIKIS":"Мои вики",
		"EVERYTHINGWIKIS":"Все из вики",
		"WIKISONLY":"Вики",
		"PAGESWIKIS":"Страницы вики",
		"FILESWIKIS":"Вложения из вики",
		"ALLTYPESWIKIS":"Все типы вики",
		"COMMUNITYWIKIS":"Вики из сообществ",
		"STANDALONEWIKIS":"Автономные вики",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Все обновления состояния",
		"PUBLICSTATUSUPDATES":"Общедоступные обновления состояния",
		"MYSTATUSUPDATES":"Мои обновления состояния",
		"ALLTYPESSTATUSUPDATES":"Все типы обновлений состояния",
		"COMMUNITYSTATUSUPDATES":"Обновления состояния из приложения Сообщества",
		"STANDALONESTATUSUPDATES":"Обновления состояния из приложения Профайлы",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Этот URL добавлен в закладки несколькими пользователями",
		"BOOKMARKEDCOMMUNITY":"Это сообщество добавлено в закладки несколькими пользователями",
		"BOOKMARKEDPROFILE":"Этот профайл добавлен в закладки несколькими пользователями",
		"BOOKMARKEDBLOG":"Этот блог добавлен в закладки несколькими пользователями",
		"COMMUNITYBLOG":"Это блог в сообществе",
		"BOOKMARKEDACTIVITY":"Эта операция добавлена в закладки несколькими пользователями",
		"COMMUNITYACTIVITY":"Это операция в сообществе",
		"BOOKMARKEDFILE":"Этот файл добавлен в закладки несколькими пользователями",
		"COMMUNITYFILE":"Это файл в сообществе",
		"BOOKMARKED":"Эта вики добавлена в закладки несколькими пользователями",
		"COMMUNITYWIKI":"Это вики в сообществе",
		"BOOKMARKEDFORUM":"Этот форум добавлен в закладки несколькими пользователями",
		"COMMUNITYFORUM":"Это форум в сообществе",
		"ALLTAGANDTTILE":"Нажмите эту кнопку для просмотра всех заголовков и тегов данного URL",
		"TAGS_ARE_FROM":"Этот результат поиска может включать теги из:",
		"BOOKMARKS_TITLE":"Закладки",
		"COMMUNITIES_TITLE":"Сообщества",
		"ACTIVITIES_TITLE":"Операции",
		"HELP":"Справка",
		"MORESTATUSUPDATES":"Показать другие совпадающие обновления состояния",
		"TITLE_PREFIX":"заголовок:",
		"LATEST_MESSAGE":"Последнее сообщение",
		"LATEST_STATUS_UPDATE":"Последнее обновление состояния",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Последнее обновление состояния приложения Сообщества",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Последние обновления состояния приложения Сообщества",
		"SEARCH_RESULTS":"Все результаты поиска информации",
		"ACTIVITIES_SEARCH_RESULTS":"Операции - Результаты поиска",
		"BLOGS_SEARCH_RESULTS":"Блоги - Результаты поиска",
		"BOOKMARKS_SEARCH_RESULTS":"Закладки - Результаты поиска",
		"COMMUNITIES_SEARCH_RESULTS":"Сообщества - Результаты поиска",
		"FILES_SEARCH_RESULTS":"Файлы - Результаты поиска",
		"FORUMS_SEARCH_RESULTS":"Форумы - Результаты поиска",
		"PROFILES_SEARCH_RESULTS":"Профайлы - Результаты поиска",
		"DIRECTORY_SEARCH_RESULTS":"Результаты поиска в каталоге ${orgName}",
		"WIKIS_SEARCH_RESULTS":"Вики - Результаты поиска",
		"STATUS_UPDATES_SEARCH_RESULTS":"Обновления состояния - Результаты поиска",
		"VIEW_ALL":"{span}Показать все{/span} ({0})",
		"MATCHING_ONE_OF":"Один из:",
		"MATCHING_ALL_OF":"Все из:",
		"MATCHING":"Содержащие:",
		"MATCHING_DOC_TYPE":"Совпадающий тип документа:",
		"BOOKMARK_HELP":"Справка по закладкам",
		"CLOSE_BOOKMARK_HELP":"Закрыть справку по закладкам",
		"DOCUMENT_TYPE_PREFIX":"Тип документа:",
		"LAST_PAGE_MESSAGE": "Слишком много результатов поиска. Попробуйте сузить поиск, добавив дополнительные условия поиска.",
		"LAST_PAGE_SUBMESSAGE": "Первые {resultNumber} результатов."
});

