define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Schließen",
		   'rs_loading' : "Ladevorgang läuft...",
		   'rs_at' : "um",
		   'rs_searchDirectory' : "Person nicht aufgeführt? Vollständige Suche verwenden...",
		   'rs_searchGroupDirectory' : "Gruppe nicht aufgelistet? Vollständige Suche verwenden...",
		   'rs_searchPersonAndGroupDirectory' : "Person oder Gruppe nicht aufgelistet? Vollständige Suche verwenden...",
		   'rs_searchCommunityDirectory' : "Community nicht aufgelistet? Vollständige Suche verwenden...",
		   'rs_shadowText_searchDirectory' : "Suchbegriff für Person eingeben",
		   'rs_shadowText_searchGroupDirectory' : "Suchbegriff für Gruppe eingeben",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Suchbegriff für Person oder Gruppe eingeben",
		   'rs_shadowText_searchCommunityDirectory' : "Suchbegriff für Community eingeben",
		   'rs_listItem' : "Listeneintrag",
		   'rs_noResults' : "Keine Ergebnisse für '${0}'",
		   'rs_today' : "Heute",
		   'rs_tomorrow' : "Morgen",
		   'rs_yesterday' : "Gestern",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Feed für diese Aktivitäten",
		   'rs_externalText' : "Diese Aktivität kann Mitglieder aufnehmen, die nicht zu Ihrem Unternehmen gehören.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" wurde erfolgreich in die Subcommunity \"${destCommName}\" verschoben.',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Weitere Details zu dieser Aktivität anzeigen',
		   'rs_hideInfo' : 'Zusatzinformationen ausblenden',
		   'rs_more' : "Mehr",
		   'rs_hide' : "Ausblenden",
		   'rs_edit' : "Bearbeiten",
		   'rs_restore' : "Wiederherstellen ",
		   'rs_deleteEntry' : "Löschen",
		   'rs_prioritize' : "Prioritäten vergeben ",
		   'rs_markComplete' : "Als abgeschlossen markieren",
		   'rs_markIncomplete' : "Wiederherstellen ",
		   'rs_linkMore' : "... [mehr] ",
		   'rs_linkLess' : "... [weniger]",
		   'rs_actUpdatedByDate' : "Aktualisiert von ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Aktualisiert von ${0}",// Updated by (author name)
		   'rs_actDue' : "Fällig ${0}",// Due (date)
		   'rs_actTags' : "Tags: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Aktivität mit dieser Vorlage starten",
		   'rs_favoriteTemplate' : "Als bevorzugte Vorlage markieren",
		   'rs_normalTemplate' : "Als normale Vorlage markieren",
		   'rs_tunedOutPri' : "Inaktiviert",
		   'rs_pagepos' : "${0} - ${1} von ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Zurück",
		   'rs_navNextLabel' : "Weiter",
		   'rs_noActivities' : "Für diese Community wurden noch keine Aktivitäten gestartet.",
		   'rs_feedError' : "Feed konnte nicht geladen werden.",
		   'rs_highPri' : "Hohe Priorität ",
		   'rs_medPri' : "Mittlere Priorität ",
		   'rs_normalPri' : "Normale Priorität (Standard)",
		   'rs_tuneOut' : "Als inaktiviert markieren",
		   'rs_startActivity' : "Aktivität starten ",
		   'rs_startFirstActivity' : "Erste Aktivität erstellen",
		   'rs_navNextLabel' : "Weiter",
		   'rs_viewAll' : "Alle anzeigen",
		   'rs_activityWidgetTitle' : "Aktivitäten",
		   'rs_activityWidgetBriefDescription' : "Verfolgen Sie die Ziele der Community. Erstellen Sie Aufgaben und teilen Sie Ressourcen mit anderen Personen.",
		   'rs_activityWidgetDescription' : "Über die Community-Aktivitäten können Sie online mit anderen Benutzern zusammenarbeiten und die Fortschritte von Community-Projekten und -Initiativen nachverfolgen.",
		   'rs_completedActivityLink' : "Abgeschlossene Aktivitäten anzeigen",
		   'rs_activitiesUnavailable' : "Der Aktivitäten-Service ist nicht verfügbar.",
		   'rs_errorPersists' : "Wenn der Fehler weiterhin auftritt, wenden Sie sich an den Systemadministrator.",
		   'rs_shared' : "Geteilt",
		   'rs_removeActFromComm' : "Aus Community entfernen",
		   'rs_externalLabel' : "Extern ",
		   // for ActivityForm
		   'rs_templateOptions' : "Vorlagenoptionen",
		   'rs_template' : "Vorlage ",
		   'rs_tagsLabel' : "Tags",
		   'rs_peopleLabel' : "Personen",
		   'rs_aboutThisTemplate' : "Informationen zu dieser Vorlage",
		   'rs_activity' : "Aktivität ",
		   'rs_copyOf' : "Kopie von ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Ziel der Aktivität ",
		   'rs_noTemplate' : "Keine",
		   'rs_copyActivityMembers' : "Mitglieder aus Aktivität verwenden",
		   'rs_copyTemplateMembers' : "Mitglieder aus Vorlage verwenden",
		   /* Forum Widget */
		   'rs_noTopics' : "Für diese Community gibt es noch keine Themen.",
		   'rs_noTopicsLoggedIn' : "Fragen stellen, Gedanken oder Ideen austauschen.",
		   'rs_postedBy' : "Letzter Beitrag von",
		   'rs_topics' : "Themen ",
		   'rs_noTopicsShort' : "Keine Themen ",
		   'rs_topic' : "Thema ",
		   'rs_replies' : "Antworten",
		   'rs_noReplies' : "Keine Beiträge ",
		   'rs_reply' : "Antworten",
		   'rs_startTopic' : "Thema starten",
		   'rs_startFirstTopic' : "Erstes Thema starten ",
		   'rs_ok' : "OK",
		   'rs_locked' : "[Gesperrt]",
		   'rs_manageForumSetting' : "Foreneinstellungen verwalten ",
		   'rs_forumSettingCommunityOverviewPage' : "Community-Startseite: ",
		   'rs_defaultForumList' : "Standardmäßig Forenliste anzeigen ",
		   'rs_defaultTopicList' : "Standardmäßig Themenliste anzeigen ",
		   'rs_forumSettingApplicationView' : "Standardansicht für Forenanwendungen: ",
		   'rs_forumSettingNote' : "Hinweis: Standardmäßig werden Themen angezeigt, wenn nur ein Forum vorhanden ist. ",
		   'rs_forumSettingSubmit' : "Übergeben",
		   'rs_forumSettingSave' : "Speichern",
		   'rs_forumSettingSaveAndClose' : "Speichern und schließen",
		   'rs_forumSettingConfirm' : "Die Änderungen für Foren wurden gespeichert.",
		   'rs_forumSettingError' : "Es ist ein Fehler aufgetreten. Wenden Sie sich an den Administrator.",
		   'rs_formSettingHideMessage' : "Diese Nachricht ausblenden",
		   'rs_forumSettingCancel' : "Abbrechen",
		   'rs_forumAnsweredQuestion' : "Beantwortete Frage",
		   'rs_forumUnAnsweredQuestion' : "Nicht beantwortete Frage",
		   'rs_forumSortBy' : "Sortieren nach:",
		   'rs_forumSortByDate' : "Datum",
		   'rs_forumSortByReplies' : "Antworten",
		   'rs_forumSortByTopic' : "Themen",
		   'rs_forumSortByTopicsAndReplies' : "Themen und Antworten",
		   'rs_sortByReplies' : "Nach Antworten sortieren",
		   'rs_sortbyTopicsAndReplies' : "Nach Themen und Antworten sortieren",
		   'rs_forumOpenQuestions' : "Offene Fragen",
		   'rs_feedOpenQuestions' : "Feed für diese offenen Fragen",
		   'rs_feedAnsweredQuestions' : "Feed für diese beantworteten Fragen",
		   'rs_forumMessages' : "${0} Nachrichten",
		   'rs_forumLastAddedPost' : "Letzter Beitrag von ${0}",
		   'rs_forumTopics' : "${0} Themen",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Personenlink erstellen",
		   'rs_quote' : "Zitieren ",
		   'rs_labelColon' : "Bezeichnung: ",
		   'rs_personColon' : "Person: ",
		   'rs_personLink' : "Personenlink",
		   'rs_replace' : "Ersetzen",
		   'rs_inactivePerson' : "${0} (inaktiv)", // person's name (inactive)
		   'rs_PersonPicture' : "Bild von ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Externer Benutzer", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (externer Benutzer)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Bild von ${0} (externer Benutzer)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Dieser Benutzer hat Zugriff auf Dateien und Communitys, die extern geteilt sind. ",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Andere Personen benachrichtigen",
		   'rs_messageColon' : "Nachricht: ",
		   'rs_notifyColon' : "Benachrichtigen:",
		   'rs_notificationConfirm' : "Die Benachrichtigung wurde erfolgreich gesendet. ",
		   'rs_notificationFail' : "Die Benachrichtigung wurde nicht gesendet. Wiederholen Sie den Vorgang später und wenden Sie sich an den Systemadministrator, wenn der Fehler weiterhin auftritt.",
		   'rs_pickCommunity' : "Aus Community-Liste auswählen",
		   'rs_typeName' : "Namen eingeben ",
		   'rs_typeToFilter' : "Eingeben, um diese Liste zu filtern",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Eingeben, um diese Liste zu filtern",
		   'rs_filterGroupLabel' : "Gruppe auswählen",
		   'rs_noResults' : "Es wurden keine Ergebnisse gefunden",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "${0} Ergebnisse von ${1} werden angezeigt",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Entfernen",
		   /* Language Selector */
		   'rs_browser_setting' : "Browsereinstellung",
		   'rs_customLangaugeLinkLabel' : "Benutzerdefinierte Sprache",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Wechseln zu Seite ${0} von ${1}",
		   "rs_jumpPageLabel" : "Wechseln zu Seite",
		   'rs_pageNumLabel' : "Seitenzahl",
		   'rs_pageLabel' : "Seite:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Tags',
		   'rs_tagCloudToggleHint' : "Zum Ausblenden oder Anzeigen hier klicken",
		   'rs_tagCloudHelpAlt' : "Hilfe zu Tags anfordern ",
		   'rs_tagCloudNoTags' : "Noch keine Tags.",
		   'rs_tagCloudNoRecentTags' : "Keine neuen Tags",
		   'rs_tagCloudNoTagsProfiles' : "Verzeichnis durchsuchen. Tags, die den von der Suche zurückgegebenen Profilen zugeordnet sind, werden hier angezeigt.",
		   'rs_tagLoadingTags' : "Inhalt wird geladen ",
		   'rs_tagCloudSelectedTags' : "Ausgewählte Tags ",
		   'rs_tagCloudSeachDesc' : "Tag suchen ",
		   'rs_tagCloudSeach' : "Suche",
		   'rs_tagCloudRelatedTags' : "Zugehörige Tags ",
		   'rs_tagCloudRelatedTagsDescription' : "Zugehörigen Tag hinzufügen, um die Suche weiter einzugrenzen",
		   'rs_tagCloudError' : 'Es ist ein Fehler aufgetreten',
		   'rs_viewAsCloud' : "Wolke ",
		   'rs_viewAsCloudTitle' : "Tags als Tagwolke anzeigen ",
		   'rs_viewAsCloudDescription' : "Tags als Tagwolke anzeigen",
		   'rs_viewAsList' : "Liste",
		   'rs_viewAsListTitle' : "Tags als sequenzielle Tagliste anzeigen ",
		   'rs_viewAsListDescription' : "Tags als sequenzielle Tagliste anzeigen",
		   'rs_tagCloudViewAll' : "Durchsuchen",
		   'rs_tagCloudViewAllTitle' : "Alle Tags durchsuchen",
		   'rs_normalTags' : "Aktive Tags ",
		   'rs_removeTag' : "Tag aus den ausgewählten Filtertags entfernen ",
		   'rs_clearAll' : "Alle löschen",
		   'rs_searchInputDefault' : "Suchbegriff für Tag eingeben ",
		   'rs_searchInputTagSelected' : "Weiteren Tag eingeben ",
		   'rs_relatedTagTitle' : "Suchergebnisse für Tag ${0}, Anzahl ${1}, anzeigen",
		   'rs_removeTagTitle' : "Tag ${0} aus den ausgewählten Filtertags entfernen",
		   'rs_addTagTitle' : "Tag ${0} mit der Zahl ${1} filtern",
		   'rs_tagDialogCloseTile' : "Schließen",
		   'rs_tagDialogTitle' : "Alle Tags",
		   'rs_tagDialogPageInfo' : "${0} - ${1} von ${2} Tags",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Gruppen durchsuchen ",
		   'rs_group_browse_groups_dialog_title' : "Gruppen durchsuchen ",
		   'rs_group_browse_find_groups' : "Nach Gruppen suchen ",
		   'rs_group_browse_add_button' : "Hinzufügen",
		   'rs_group_browse_cancel_button' : "Abbrechen",
		   'rs_group_browse_enter_string' : "Geben Sie Text ein, um Gruppen zu finden.",
		   'rs_group_browse_group_typeahead_label' : "Gruppennamen eingeben:",
		   'rs_group_browse_group_name' : "Gruppenname:",
		   'rs_group_browse_results_label' : "Wählen Sie eine übereinstimmende Gruppe aus:",
		   'rs_group_browse_parent_group_label' : "Sie befinden sich in:",
		   'rs_group_browse_next_page' : "Nächste Seite ",
		   'rs_group_browse_previous' : "Zurück",
		   'rs_group_browse_next' : "Weiter",
		   'rs_group_browse_paging' : "Seitenwechsel",
		   'rs_group_browse_previous_page' : "Vorherige Seite ",
		   'rs_group_browse_group_selected' : "Ausgewählte Gruppe:",
		   'rs_group_browse_group_no_groups' : "Diese Gruppe enthält keine Gruppen. ",
		   'rs_group_browse_page_info' : "${0} - ${1} von ${2}",
		   'rs_group_browse_page_info_alt' : "Übereinstimmende Gruppen ${0} bis ${1} von ${2}",
		   'rs_group_browse_remove_selection' : 'Auswahl einer verschachtelten Gruppe aufheben: ${0}',
		   'rs_group_browse_paging' : "Seitenwechsel",
		   'rs_member_groups' : "Gruppen ",
		   'rs_member_members' : "Mitglieder",
		   'rs_member_no_results' : "Es wurden keine Ergebnisse gefunden",
		   'rs_member_remove_group' : "${0} entfernen ",
		   'rs_member_add_to_community' : "Klicken Sie hier, um ein Mitglied hinzuzufügen",
		   'rs_member_remove_name' : "Klicken Sie hier, um ein Mitglied zu entfernen",
		   'rs_group_add_to_community' : "Klicken Sie hier, um eine Gruppe hinzuzufügen",
		   'rs_group_remove_name' : "Klicken Sie hier, um eine Gruppe zu entfernen",
		   'rs_group_name' : "Gruppenname",
		   'rs_group_role' : "Gruppenrolle",
		   'rs_warning' : "Warnung ",
		   'rs_a11y_warning' : "Warnung:",
		   'rs_messagebox_close_btn_title' : "Schließen",
		   'rs_messagebox_close_btn_alt' : "Schließen",
		   'rs_messagebox_error_icon_alt' : "Fehler",
		   'rs_messagebox_error_a11y_label' : "Fehler:",
		   'rs_messagebox_warning_icon_alt' : "Warnung ",
		   'rs_messagebox_warning_a11y_label' : "Warnung:",
		   'rs_messagebox_info_icon_alt' : "Information ",
		   'rs_messagebox_info_a11y_label' : "Information: ",
		   'rs_messagebox_success_icon_alt' : "Erfolg",
		   'rs_messagebox_success_a11y_label' : "Erfolg:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Link zu Dateien einfügen",
		   'rs_docpicker_label' : "Link zu Dateien",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "${0} herunterladen",
		   'rs_docpicker_viewdetails_text' : "Details anzeigen",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Details zu ${0} anzeigen",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Entfernen",
		   'rs_attachedfile_filename' : "Bild ${0}",
		   'rs_feedreader_warning' : "Warnung: Dieser Link ist für Feed-Leseprogramme gedacht und wird in Ihrem Browser möglicherweise nicht korrekt angezeigt. Klicken Sie auf 'OK', um den Vorgang fortzusetzen, oder auf 'Abbrechen', um zur Seite zurückzukehren.",
		   'rs_search' : "Suche",
		   'rs_all_connections' : "Alle Anwendungen ",
		   'rs_advanced' : "Erweitert",
		   'rs_select_scope' : "Suchbereich auswählen",
		   'rs_icfixlayout' : {
		      button_label : "Neu formatieren",
		      dialog_title : "Inhalte neu formatieren",
		      warning : "Warnung ",
		      reformat_save : "Neu formatieren und speichern",
		      save_as_is : "Unverändert speichern ",
		      cancel : "Abbrechen",
		      warn_layout : "Die Inhalte überschreiten die maximale Anzeigebreite. Sollen sie automatisch so neu formatiert werden, dass sie in den verfügbaren Platz passen? ",
		      remember_decision : "Meine Auswahl merken"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Beim Teilen der ausgewählten Dateien ist ein Fehler aufgetreten. ",
		   'rs_sharefile_access_denied' : "Diese Datei wurde gelöscht oder wird nicht mehr mit Ihnen geteilt.",
		   'rs_sharefile_invalid_request' : "Beim Teilen der ausgewählten Dateien ist ein Fehler aufgetreten. ",
		   'rs_sharefile_sharing_intent_restriction' : "Die Datei kann nur innerhalb Ihres Unternehmens geteilt werden.",
		   'rs_sharefile_error_title' : "Fehler",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'Im App Store',
		   'rs_mobileBanner_inGooglePlay' : 'In Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Öffnen',
		   'rs_mobileBanner_view' : 'Anzeigen',
		   'rs_mobileBanner_hide' : 'Ausblenden',

		   'rs_empty_column_placeholder' : 'Apps hierher ziehen.',
		   'rs_widget_loading_error_title' : 'Das Widget kann nicht angezeigt werden',
		   'rs_widget_loading_error_message' : 'Wiederholen Sie den Vorgang später und wenden Sie sich an den Systemadministrator, wenn der Fehler weiterhin auftritt.',
		   'rs_widgets_loading_error_title' : 'Die Widgets in dieser Community können nicht angezeigt werden',
		   'rs_widget_misplacement_warning' : 'Diese App passt nicht in diese Spalte. Ein Community-Eigentümer kann sie in eine andere Spalte verschieben oder von der Seite entfernen.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Der von Ihnen eingegebene Titel ist zu lang. ',
		      empty_new_title : 'Der von Ihnen eingegebene Titel darf nicht leer sein. ',
		      default_message : 'Der Titel für diese ${0}-App kann nicht geändert werden. '
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Titel: ',
		   'rs_widget_title_change_direction' : 'Titel für diese ${0}-App ändern. ',
		   'rs_widget_title_change_title' : 'Titel ändern',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Mitglieder einladen oder hinzufügen",
		   'rs_vmmainContentDesc' : "Mitglieder einladen, um ihnen die Möglichkeit zu geben, an der Community teilzunehmen. Mitglieder hinzufügen, um sie automatisch hinzuzufügen. ",
		   'rs_vmtypeAheadLabel' : "Name oder E-Mail-Adresse:",
		   'rs_vmgroupTypeAheadLabel' : "Name: ",
		   'rs_vmtypeAheadRoleLabel' : " als",
		   'rs_vmgroupTypeAheadRoleLabel' : " als Mitglieder ",
		   'rs_vmtaNoResults' : "Keine Ergebnisse gefunden. ",
		   'rs_vmtaHeader' : "Header",
		   'rs_vmaddUser' : "Hinzufügen",
		   'rs_vmradioSectionTitle' : "Mitgliederoptionen:",
		   'rs_vmradioOne' : "Einladungen zum Teilnehmen an der Community senden",
		   'rs_vmradioTwo' : "Automatisch Benutzer zur Community hinzufügen",
		   'rs_vmtwistyA' : "Optionale Nachricht hinzufügen",
		   'rs_vmtwistyB' : "Zusätzlichen Text entfernen",
		   'rs_vmmessage' : "Nachricht:",
		   'rs_vmtextAreaStartText' : "Etwas sagen...",
		   'rs_vmcheckboxLabel' : "Mir eine Kopie senden",
		   'rs_vmsave' : "Speichern",
		   'rs_vminvite' : "Einladen",
		   'rs_vmcancel' : "Abbrechen",
		   'rs_userContentTitle' : "Informationen eingeben",
		   'rs_vmaddUser' : "Benutzer erstellen",
		   'rs_vmback'	 : "Zurück",
		   'rs_vmvisitor'	 : "Besucher",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Klicken Sie hier, um diese Community zu kopieren',
			'rs_commpicker' : ''

});
