/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klicken Sie hier, um die Visitenkarte anzuzeigen.",
	"label.semtag.hover.alt" : "Klicken Sie hier, um die Visitenkarte für {0} anzuzeigen.",
	"label.semtag.hover.altA11Y" : "Klicken Sie hier oder drücken Sie Strg+ Eingabe, um die Visitenkarte anzuzeigen.",
	"label.personcard.dialog.title" : "Visitenkarte für {0} anzeigen",

	"errorDefaultMsg2" : "Es ist ein Fehler aufgetreten. Wenden Sie sich an Ihren Systemadministrator.",

	"loadingSTStatus" : "Sametime-Status laden…",
	"noStatuAvailable" : "Kein Sametime-Status verfügbar",

	"label.personcard.cardnomarkup" : "Die Visitenkarte konnte nicht abgerufen werden.",
	"label.inactive.user.msg" : "Diese Person ist kein aktiver Benutzer mehr.",
	"label.message.information" : "Information:",
	"label.personcard.noprofilemsg" : "Für diese Person ist kein Profil vorhanden.",
	"label.personcard.cardreqexpired" : "Die Anforderung zum Abrufen der Visitenkarte ist abgelaufen.",

	"label.bizcard.applinks.less" : "Weniger anzeigen",
	"label.bizcard.applinks.more" : "Mehr anzeigen",

	"label.personcard.activitieslink" : "Aktivitäten",
	"label.personcard.activitieslink.title" : "Klicken Sie hier, um die geteilten Aktivitäten anzuzeigen.",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Klicken Sie hier, um den Blog dieser Person anzuzeigen.",
	"label.personcard.communitieslink" : "Communitys",
	"label.personcard.communitieslink.title" : "Klicken Sie hier, um die Communitys dieser Person anzuzeigen.",
	"label.personcard.dogearlink" : "Lesezeichen",
	"label.personcard.dogearlink.title" : "Klicken Sie hier, um die Lesezeichen dieser Person anzuzeigen.",
	"label.personcard.fileslink" : "Dateien",
	"label.personcard.fileslink.title" : "Klicken Sie hier, um die geteilten Dateien dieser Person anzuzeigen.",
	"label.personcard.forumlink" : "Foren",
	"label.personcard.forumlink.title" : "Klicken Sie hier, um die Forenposts dieser Person anzuzeigen.",
	"label.personcard.homepagelink" : "Home",
	"label.personcard.homepagelink.title" : "Klicken Sie hier, um die Startseite dieser Person anzuzeigen.",
	"label.personcard.mobilelink" : "Mobil",
	"label.personcard.mobilelink.title" : "Klicken Sie hier, um die Mobilseite dieser Person anzuzeigen.",
	"label.personcard.newslink" : "Nachrichten",
	"label.personcard.newslink.title" : "Klicken Sie hier, um die Nachrichten dieser Person anzuzeigen.",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klicken Sie hier, um das Profil dieser Person anzuzeigen.",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klicken Sie hier, um die geteilten Quickr-Elemente dieser Person anzuzeigen.",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Klicken Sie hier, um die Wikis dieser Person anzuzeigen.",

	"personCardMoreActions" : "Weitere Aktionen",
	"personCardMoreActionsAltText" : "Klicken Sie hier, um das Aktionsmenü anzuzeigen.",

	"label.bizcard.dismiss": "Drücken Sie die Esc, um diese Visitenkarte zu verwerfen.",
	"label.bizcard.fullProfile": "Vollständiges Problem",
	"label.bizcard.activities": "Aktivitäten",
	"label.bizcard.communities": "Communitys",
	"label.bizcard.files": "Dateien",
	"label.bizcard.forums": "Foren",
	"label.bizcard.bookmarks": "Lesezeichen",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "In mein Netzwerk einladen",
	"personCardAddAsMyColleagues" : "In mein Netzwerk einladen",
	"personCardFollow" : "Folgen",
	"personCardUnfollow" : "Nicht mehr folgen",
	"personCardChat" : "Chat",
	"personCardCall" : "Anrufen",
	"personCardSendMail" : "E-Mail senden",
	"personCardSendEMail" : "E-Mail senden",
	"personCardProxyStatusAvailable" : "Ich bin verfügbar",
	"personCardDownloadVCard" : "vCard herunterladen",

	"friends" : "Netzwerk",
	"friendsFullPageTitle" : "Netzwerk",
	"friendsMenuTitleAllContacts" : "Alle Netzwerkkontakte",
	"friendsMenuTitleMyContacts" : "Meine Netzwerkkontakte",
	"friendsInvitations" : "Einladungen",
	"friendsMenuTitleInCommon" : "Gemeinsame Kontakte",
	"friendsShowAllCommonFriends" : "Alle anzeigen…",
	"friendsViewAllFriends" : "Alle anzeigen ({0})",
	"friendsSendFriendRequest" : "Anforderung senden",
	"friendsNoFriends" : "Diesem Profil sind keine Netzwerkkontakte zugeordnet.",
	"friendsColleaguesInvite" : "{0} einladen, Ihr Netzwerkkontakt zu sein",
	"friendsColleaguesFor" : "Netzwerkkontakte für {0}",
	"friendsNewInv" : "{0} neue Einladung",
	"friendsNewInvs" : "{0} neue Einladungen",
	"friendsLoading" : "Netzwerk laden…",
	"friendsLoadingInv" : "Einladungen senden…",
	"friendsSelectFriendForRemoval" : "Wählen Sie zunächst die Kontakte aus, die Sie entfernen möchten.",
	"friendsRemoved" : "Netzwerkkontakt(e) wurde(n) entfernt.",
	"friendsInvSent" : "Es wurde keine Einladung gesendet, da bereits eine Einladung aussteht.",
	"friendsRemovedSelected" : "Aus \"Mein Netzwerk\" entfernen",
	"friendsSortByDisplayName" : "Anzeigename",
	"friendsSortByRecent" : "Neue",
	"friendsTelephone" : "Telefon:",
	"friendsEmail" : "E-Mail:",
	"friendsAltEmail" : "Alternative E-Mail-Adresse:",
	"friendsNewInvitationsCount" : "Sie haben {0} neue Einladung(en).",
	"friendsNoInv" : "Keine Einladungen",
	"friendsInCommonSingle" : "Sie haben {0} gemeinsamen Netzwerkkontakt.",
	"friendsInCommonMulti" : "Sie haben {0} gemeinsame Netzwerkkontakte.",
	"friendsIncludeMsgForInv" : "Nachricht zur Einladung hinzufügen:",
	"friendsInitialMsgForInv" : "Ich möchte Sie zu meiner Liste mit Connections-Netzwerkkontakten hinzufügen.",
	"friendsSendInvAction" : "Einladung senden",
	"friendsCancelInvAction" : "Abbrechen",
	"friendsAcceptAction" : "Akzeptieren",
	"friendsIgnoreAction" : "Ignorieren",
	"friendsYouExceedTextLimit" : "Ihre Einladungsnachricht ist zu lang. Sie darf höchstens {1} Zeichen enthalten. Dieses Feld enthält {0} Zeichen.",
	"friendsCannotAddYourself" : "Sie können sich nicht selbst als Netzwerkkontakt hinzufügen.",
	"friendsIsYourColleague" : "{0} ist Ihr Netzwerkkontakt.",
	"friendsRecentlyAdded" : "Personen, die Sie neu zu Ihrem Netzwerk hinzugefügt haben.",
	"friendsDate" : "Datum",
	"friendsCollapseWidget" : "Klicken Sie hier, um den Netzwerkabschnitt auszublenden.",
	"friendsExpandWidget" : "Klicken Sie hier, um den Netzwerkabschnitt einzublenden.",
	"friendsIsInYourNetwork" : "{0} ist in Ihrem Netzwerk.",
	"friendsActionsFor" : "Aktionen für Netzwerk",
	"friendsInviteFollowError" : "Beim Versuch, {0} zu folgen, ist ein Fehler aufgetreten.",
	"friendsInviteTagError" : "Beim Versuch, {0} mit einem Tag zu versehen, ist ein Fehler aufgetreten.",
	"friendsPleaseLogIn" : "Melden Sie sich an, um andere Personen in Ihr Netzwerk einzuladen.",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Eine Einladung in Ihr Netzwerk ist nicht möglich, da sich {0} bereits in Ihrem Netzwerk befindet.",
	"friendsInviteAddTagsFor" : "Tags für {0} hinzufügen:",
	"friendsInviteAlsoFollow" : "Ebenfalls folgen",
	"friendsInviteReceiveUpdates" : "(Aktualisierung erhalten)",
	"friendsInviteUpdatesDescription" : "Sie erhalten auf der Startseite und in einer E-Mail-Zusammenfassung Aktualisierungen zu Personen, denen Sie folgen.",
	"friendsInviteFollowHelp": "Weitere Informationen dazu erhalten Sie unter {0}Personen folgen{1}.",
	"friendsNetwork" : "Netzwerk",
	"friendsMyNetwork" : "Netzwerk",
	"friendsNetworkFor" : "Netzwerk für {0}",
	"friendsRemoveSelected" : "Auswahl entfernen",
	"friendsRemoveSelectedTip" : "Klicken Sie hier, um die ausgewählten Personen aus dem Netzwerk zu entfernen.",
	"friendsNetworkInCommon" : "Sie haben {0} gemeinsame Netzwerkverbindungen.",
	"friendsAddToMyNetwork" : "Ich möchte Sie zu meinem Connections-Netzwerk hinzufügen.",
	"friendsInvite" : "In mein Netzwerk einladen",
	"friendsInvitePerson" : "{0} in Ihr Netzwerk einladen",
	"friendsInviteMessage" : "Ich möchte Sie zu meinem Connections-Netzwerk hinzufügen.",
	"friendsInvitedEmailSubject" : "[Profile] Einladung in mein Netzwerk",
	"friendsInvitedEmailMsg1" : "hat Sie eingeladen, ein Netzwerkkontakt zu werden. Die folgende Nachricht ist in der Einladung enthalten:",
	"friendsInvitedEmailMsg2" : "Seite mit Ihren Netzwerkeinladungen öffnen",
	"friendsInvitedEmailMsg3" : "Ich möchte Sie zu meinem Netzwerk hinzufügen.",
	"friendsInvitedEmailMsg4" : "{0} hat Sie eingeladen, ein Netzwerkkontakt zu werden:",
	"friendsInvitedEmailMsg5" : "{0} hat Sie eingeladen, ein Netzwerkkontakt zu werden. Die folgende Nachricht ist in der Einladung enthalten:",
	"friendsInviteLegalNote" : "Durch Senden dieser Einladung stimmen Sie zu, dass {0} in Ihrem Profilboard Kommentare verfassen darf.",
	"friendsInviteFailed" : "Aufgrund eines Serverfehlers wurde eine E-Mail-Benachrichtigung nicht an den Eingeladenen gesendet. Der Eingeladene kann Ihre Einladung jedoch über die Profile-Webanwendung annehmen.",
	"personInNetwork" : "Netzwerkkontakt"
})
