/* Copyright IBM Corp. 2008, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Тақырып қажет.",
	nourl: "URL мекен-жайы қажет.",
	fileSchema: "Егер де қашықтағы немесе жергілікті файл сілтемесін қосуды қаласаңыз келесі пішіндердің бірімен расталуы тиіс: file://remote_path or file:///local_path.",
	invalidUrl: "Бұл жарамды қауымдастық URL-мекен-жайы емес.",
	txtHelp: "Анықтама",
	txtHelpTags: "Тегтер анықтамасы",
	txtHelpTagsClose: "Тегтер анықтамасын жабу",
	tagsall: "Барлығы",
	tagsyours: "Сіздің",
	tagsrecent: "Кейінгі: ",
	tagspopular: "Танымал: ",
	tagsrecommended: "Ұсынылған: ",
	nothingselected: "Қауымдастықты таңдау қажет.",
	nothingselected_activity: "Әрекетті таңдау қажет.",
	nothingselected_blogs: "Блогты таңдау қажет.",
	nothingselected_all: "Таңдалған қызмет немесе жазба жоқ, бетбелгі сақталмайды.",
	nothingFeedselected: "Таңдалған қызмет немесе жазба жоқ, арна сақталмайды.",
	alertDialogTitle: "Хабар",
	alertDialogOK: "OK",
	expand: "Осы бөлімді ашу үшін басу",
	collapse: "Осы бөлімді тасалау үшін басу",
	discussThis: "Осыны талқылау",
	by: "келесі бойынша:",
	posted: "Орналастырылды:",
	attachments: "Тіркемелер",
	communityForum: "Қауымдастық форумы",
	notCommunityPage: "Ағымдағы бет-бет жарамды қауымдастық веб-беті емес. Қауымдастық тақырыбын, сілтемесін және қатысты қауымдастық жасау үшін сипаттаманы қолмен енгізуге болады.",
	privateCommunityNotice: "Осы қауымдастық шектелген. Бұл тек қауымдастық мүшелеріне ғана көрінеді.",
	forumNameHint : "Форум атауын теру",
	formDescriptionHint:"Бұл байланысты қауымдастық сіздің қауымдастығыңызды қызықтыратындығын сипаттаңыз.",
	information : "Ақпарат",
	error : "Қате",
	success : "Сәтті",
	warning : "Ескерту",
	informationColon : "Ақпарат:",
	successColon : "Сәттілік:",
	warningColon : "Ескерту:",
	errorColon : "Қате:",
	feedAlreadyExist : "Арна осы қауымдастықта бұрыннан бар.",
	bookmarkAlreadyExist : "Осы қауымдастықта бетбелгі бұрыннан бар.",
	mentionAuthWarning:"Айтылған мына адамдар осы хабарды көре алмайтын болады, себебі олар осы қауымдастықтың мүшелері емес:",
	mentionAuthForumWarning:"Айтылған мына адамдар осы хабарды көре алмайтын болады, себебі олар осы форумға кіре алмайды:",
	exceedDescLength: "Енгізілген сипаттама тым ұзақ.",
	communities_checked:"${0} қауымдастық бөлектелген",
	activities_checked:"${0} әрекет бөлектелген",
	blogs_checked:"${0} блог бөлектелген"
})

