/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "按一下這裡以檢視名片",
	"label.semtag.hover.alt" : "按一下以檢視 {0} 的名片",
	"label.semtag.hover.altA11Y" : "按一下這裡或按 control-enter 以檢視名片",
	"label.personcard.dialog.title" : "{0} 的名片",

	"errorDefaultMsg2" : "發生錯誤，請與系統管理員聯絡",

	"loadingSTStatus" : "正在載入 Sametime 狀態...",
	"noStatuAvailable" : "沒有可用的 Sametime 狀態",

	"label.personcard.cardnomarkup" : "無法擷取名片",
	"label.inactive.user.msg" : "這個人已不再是作用中使用者",
	"label.message.information" : "資訊：",
	"label.personcard.noprofilemsg" : "不存在此人員的人員資訊",
	"label.personcard.cardreqexpired" : "取得名片的要求已過期",

	"label.bizcard.applinks.less" : "顯示更少",
	"label.bizcard.applinks.more" : "顯示更多內容",

	"label.personcard.activitieslink" : "活動",
	"label.personcard.activitieslink.title" : "按一下這裡以查看共用的活動",
	"label.personcard.blogslink" : "部落格",
	"label.personcard.blogslink.title" : "按一下這裡以查看此人員的部落格",
	"label.personcard.communitieslink" : "社群",
	"label.personcard.communitieslink.title" : "按一下這裡以查看此人員的社群",
	"label.personcard.dogearlink" : "書籤",
	"label.personcard.dogearlink.title" : "按一下這裡以查看此人員的書籤",
	"label.personcard.fileslink" : "檔案",
	"label.personcard.fileslink.title" : "按一下這裡以查看此人員的共用檔案",
	"label.personcard.forumlink" : "討論區",
	"label.personcard.forumlink.title" : "按一下這裡以查看此人員的討論區文章",
	"label.personcard.homepagelink" : "首頁",
	"label.personcard.homepagelink.title" : "按一下這裡以查看此人員的首頁",
	"label.personcard.mobilelink" : "行動電話",
	"label.personcard.mobilelink.title" : "按一下這裡以查看此人員的行動式頁面",
	"label.personcard.newslink" : "新聞",
	"label.personcard.newslink.title" : "按一下這裡以查看此人員的新聞",
	"label.personcard.profilelink" : "人員資訊",
	"label.personcard.profilelink.title" : "按一下這裡以查看此人員的人員資訊",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "按一下這裡以查看此人員的 Quickr 分享",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "按一下這裡以查看此人員的 Wiki",

	"personCardMoreActions" : "其他動作",
	"personCardMoreActionsAltText" : "按一下以取得動作功能表",

	"label.bizcard.dismiss": "按跳出鍵以跳出此名片。",
	"label.bizcard.fullProfile": "完整人員資訊",
	"label.bizcard.activities": "活動",
	"label.bizcard.communities": "社群",
	"label.bizcard.files": "檔案",
	"label.bizcard.forums": "討論區",
	"label.bizcard.bookmarks": "書籤",
	"label.bizcard.blogs": "部落格",
	"label.bizcard.wikis": "Wiki",

	"personCardAddAsColleagues" : "邀請加入我的網路",
	"personCardAddAsMyColleagues" : "邀請加入我的網路",
	"personCardFollow" : "追蹤",
	"personCardUnfollow" : "停止追蹤",
	"personCardChat" : "會談",
	"personCardCall" : "呼叫",
	"personCardSendMail" : "傳送電子郵件",
	"personCardSendEMail" : "傳送電子郵件",
	"personCardProxyStatusAvailable" : "我有空",
	"personCardDownloadVCard" : "下載 vCard",

	"friends" : "網路",
	"friendsFullPageTitle" : "網路",
	"friendsMenuTitleAllContacts" : "所有網路聯絡人",
	"friendsMenuTitleMyContacts" : "我的網路聯絡人",
	"friendsInvitations" : "邀請",
	"friendsMenuTitleInCommon" : "共同人員",
	"friendsShowAllCommonFriends" : "全部顯示...",
	"friendsViewAllFriends" : "檢視全部 ({0})",
	"friendsSendFriendRequest" : "傳送要求",
	"friendsNoFriends" : "沒有網路聯絡人與此人員資訊相關聯",
	"friendsColleaguesInvite" : "邀請 {0} 成為您的網路聯絡人",
	"friendsColleaguesFor" : "{0} 的網路聯絡人",
	"friendsNewInv" : "{0} 個新邀請",
	"friendsNewInvs" : "{0} 個新邀請",
	"friendsLoading" : "正在載入網路...",
	"friendsLoadingInv" : "正在載入邀請...",
	"friendsSelectFriendForRemoval" : "選取您要最先移除的聯絡人。",
	"friendsRemoved" : "已移除網路聯絡人。",
	"friendsInvSent" : "未傳送邀請，因為邀請已擱置。",
	"friendsRemovedSelected" : "從我的網路中移除",
	"friendsSortByDisplayName" : "顯示名稱",
	"friendsSortByRecent" : "最近",
	"friendsTelephone" : "電話：",
	"friendsEmail" : "電子郵件：",
	"friendsAltEmail" : "替代電子郵件：",
	"friendsNewInvitationsCount" : "您有 {0} 個新邀請",
	"friendsNoInv" : "沒有邀請",
	"friendsInCommonSingle" : "您有 {0} 個共同的網路聯絡人",
	"friendsInCommonMulti" : "您有 {0} 個共同的網路聯絡人",
	"friendsIncludeMsgForInv" : "在您的邀請中包括訊息：",
	"friendsInitialMsgForInv" : "我想要將您新增至我的 Connections 網路聯絡人清單。",
	"friendsSendInvAction" : "傳送邀請",
	"friendsCancelInvAction" : "取消",
	"friendsAcceptAction" : "接受",
	"friendsIgnoreAction" : "忽略",
	"friendsYouExceedTextLimit" : "您的邀請訊息太長。 最多可以為 {1} 個字元。 在此欄位中有 {0} 個字元。",
	"friendsCannotAddYourself" : "您無法將自己新增為網路聯絡人。",
	"friendsIsYourColleague" : "{0} 是您的網路聯絡人",
	"friendsRecentlyAdded" : "您最近新增至網路的人員。",
	"friendsDate" : "日期",
	"friendsCollapseWidget" : "按一下以收合網路區段",
	"friendsExpandWidget" : "按一下以展開網路區段",
	"friendsIsInYourNetwork" : "{0} 在您的網路中。",
	"friendsActionsFor" : "「網路」的動作",
	"friendsInviteFollowError" : "嘗試遵循 {0} 時發生錯誤",
	"friendsInviteTagError" : "嘗試標記 {0} 時發生錯誤",
	"friendsPleaseLogIn" : "請登入以邀請人員加入您的網路",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "{0} 已在您的網路中，因此無法邀請其加入您的網路。",
	"friendsInviteAddTagsFor" : "新增 {0} 的標籤：",
	"friendsInviteAlsoFollow" : "同時追蹤",
	"friendsInviteReceiveUpdates" : "（接收更新項目）",
	"friendsInviteUpdatesDescription" : "在首頁和電子郵件摘要中接收所追蹤人員的相關更新。",
	"friendsInviteFollowHelp": "如需相關資訊，請參閱{0}追蹤人員{1}。",
	"friendsNetwork" : "網路",
	"friendsMyNetwork" : "網路",
	"friendsNetworkFor" : "{0} 的網路",
	"friendsRemoveSelected" : "移除選取的項目",
	"friendsRemoveSelectedTip" : "按一下以從您的網路中移除選取的人員。",
	"friendsNetworkInCommon" : "您有 {0} 個共同的網路連線。",
	"friendsAddToMyNetwork" : "我想要將您新增至我的 Connections 網路。",
	"friendsInvite" : "邀請加入我的網路",
	"friendsInvitePerson" : "邀請 {0} 加入您的網路",
	"friendsInviteMessage" : "我想要將您新增至我的 Connections 網路。",
	"friendsInvitedEmailSubject" : "[人員資訊] 已邀請您加入我的網路",
	"friendsInvitedEmailMsg1" : "已邀請您成為網路聯絡人，並在邀請中包括下列訊息：",
	"friendsInvitedEmailMsg2" : "開啟您的「網路邀請」頁面",
	"friendsInvitedEmailMsg3" : "我想要將您新增至我的網路。",
	"friendsInvitedEmailMsg4" : "{0} 已邀請您成為網路聯絡人：",
	"friendsInvitedEmailMsg5" : "{0} 已邀請您成為網路聯絡人，並在邀請中包括下列訊息：",
	"friendsInviteLegalNote" : "傳送此邀請，表示您同意 {0} 可在人員資訊公佈欄上發表評論。",
	"friendsInviteFailed" : "由於發生伺服器錯誤，電子郵件通知未傳送至受邀者。不過，受邀者仍能透過「人員資訊」Web 應用程式，來接受您的邀請。",
	"personInNetwork" : "網路聯絡人"
})
