/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "标题必填项。",
	nourl: "URL 必填项。",
	fileSchema: "如果要添加远程或本地文件链接，必须遵守以下格式之一：file://remote_path 或 file:///local_path。",
	invalidUrl: "这不是有效的社区 URL。",
	invalidTagChar: "您输入的标签列表包含无效字符“&”。请从标签列表中除去该字符。",
	txtHelp: "帮助",
	txtHelpTags: "标签帮助",
	txtHelpTagsClose: "关闭“标签”帮助",
	tagsall: "全部",
	tagsyours: "您的",
	tagsrecent: "最新： ",
	tagspopular: "热门： ",
	tagsrecommended: "推荐： ",
	nothingselected: "需要选择社区。",
	nothingselected_activity: "需要选择活动。",
	nothingselected_blogs: "需要选择博客。",
	nothingselected_all: "未选择任何服务或条目，将不会保存书签。",
	nothingFeedselected: "未选择任何服务或条目，将不会保存订阅源。",
	alertDialogTitle: "消息",
	alertDialogOK: "确定",
	expand: "单击以展开该区段",
	collapse: "单击以折叠该区段",
	discussThis: "对此进行讨论",
	by: "作者：",
	posted: "已发布：",
	attachments: "附件",
	communityForum: "社区论坛",
	notCommunityPage: "当前的 Web 页面不是有效的社区 Web 页面。 可以手动输入社区标题、链接和描述来创建相关的社区。",
	privateCommunityNotice: "此社区受限制。它只能供社区成员查看。",
	forumNameHint : "输入论坛名称",
	formDescriptionHint:"描述您的社区为什么对此相关社区感兴趣。",
	information : "信息",
	error : "错误",
	success : "成功",
	warning : "警告",
	informationColon : "信息：",
	successColon : "成功：",
	warningColon : "警告：",
	errorColon : "错误：",
	feedAlreadyExist : "此社区内已存在订阅源。",
	bookmarkAlreadyExist : "此社区内已存在书签。",
	mentionAuthWarning:"以下提及的人员将无法查看该消息，因为他们不是社区的成员：",
	mentionAuthForumWarning:"以下提及的人员将无法查看该消息，因为他们无法访问此论坛：",
	exceedDescLength: "输入的描述过长。",
	communities_checked:"已选择 ${0} 个社区",
	activities_checked:"已选择 ${0} 个活动",
	blogs_checked:"已选择 ${0} 个博客"
})
