/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"フィルター:",
		"SHOW":"表示:",
		"ACL_FILTER_LABEL":"参照設定によるフィルター",
		"PARENT_FILTER_LABEL":"コンテナーによるフィルター",
		"TYPE_FILTER_LABEL":"タイプによるフィルター",
		"PAGING_TOP":"1 次ページング",
		"PAGING_BOTTOM":"2 次ページング",
		"PREVIOUS":"前へ",
		"NEXT":"次へ",
		"PAGE":"ページ {0}/{1}",
		"PAGE_COLON":"ページ:",
		"RESULTS":"{span}{0}-{1}{/span} / {2}",
		"ITEMS":"{0} 個の項目",
		/* Application names */
		"ACTIVITIES":"アクティビティー",
		"BLOGS":"ブログ",
		"CALENDAR":"カレンダー",
		"COMMUNITIES":"コミュニティー",
		"BOOKMARKS":"ブックマーク",
		"DOGEAR":"ブックマーク",
		"EVENTS":"イベント",
		"FILES":"ファイル",
		"FORUMS":"フォーラム",
		"PROFILES":"プロフィール",
		"WIKI":"Wiki",
		"WIKIS":"Wiki",
		"FEEDS":"フィード",
		"STATUS_UPDATES":"最新の状況",
		"ONECOMMENT":"1 件のコメント",
		"COMMENTS":"{0} 件のコメント",
		"ONEPERSON":"1 人のユーザー",
		"PEOPLE":"{0} 人のユーザー",
		"TAGS":"タグ:",
		"TAGSMORE":"とさらに {0} 個",
		"NORESULTSMESSAGE":"検索項目は見つかりませんでした",
		"JAN":"1 月",
		"FEB":"2 月",
		"MAR":"3 月",
		"APR":"4 月",
		"MAY":"5 月",
		"JUN":"6 月",
		"JUL":"7 月",
		"AUG":"8 月",
		"SEP":"9 月",
		"OCT":"10 月",
		"NOV":"11 月",
		"DEC":"12 月",
		"NO_CONTACT":"サーバーに接続できなかったため、検索は実行されませんでした",
		"SERVER_ERROR":"サーバー・エラーが原因で検索は実行されませんでした",
		"SORT_BY":"ソート順:",
		"SORT_RELEVANCE":"関連度",
		"SORT_DATE":"日付",
		"SORT_LAST_UPDATED":"最終更新日時",
		"SORT_DUE_DATE":"期限",
		"SORT_VISITS":"アクセス",
		"SORT_COMMENTS":"コメント",
		"SORT_RECOMMENDATION":"いいね",
		"SORT_POPULARITY":"人気度",
		"SORT_FIRSTNAME":"名",
		"SORT_LASTNAME":"姓",
		"SORT_DOWNLOADS":"ダウンロード",
		"SORT_TYPE":"タイプ",
		"SORT_SIZE":"サイズ",
		"SORT_TITLE":"タイトル",
		"PRIVATE":"非公開",
		"MODERATED":"管理対象",
		"COMMUNITY_ACTIVITY":"コミュニティー・アクティビティー",
		"COMMUNITY_BLOG":"コミュニティー・ブログ",
		"COMMUNITY_FILE":"コミュニティー・ファイル",
		"COMMUNITY_FORUM":"コミュニティー・フォーラム",
		"COMMUNITY_WIKI":"コミュニティー Wiki",
		"COMMUNITY_FEED":"コミュニティー・フィード",
		"COMMUNITY_BOOKMARK":"コミュニティー・ブックマーク",
		"NO_TAG":"まだタグはありません",
		"NO_DATE":"まだ日付はありません",
		"NO_PEOPLE":"ユーザーがまだ存在しません",
		"REMOVE_FILTER_LABEL":"クリックして削除",
		"REMOVE_FILTER_TITLE":"削除",
		"REMOVE_FILTER_TOOLTIP":"このフィルターの削除",
		"COMMENT_ON":"コメント対象:",
		"EXPAND_COLLAPSE":"クリックして展開/省略表示",
		"EXPAND":"展開",
		"COLLAPSE":"省略表示",
		"EXPAND_MONTHS_FILTER":"年 {0} の月フィルターを展開",
		"SORT_RELEVANCE_LABEL":"関連順にソートするにはクリック",
		"SORT_DATE_LABEL":"日付順にソートするにはクリック",
		"SORT_UPDATED_LABEL":"最終更新日時順にソートするにはクリック",
		"SORT_DUE_LABEL":"期限順にソートするにはクリック",
		"SORT_VISITS_LABEL":"アクセス数の順にソートするにはクリック",
		"SORT_COMMENTS_LABEL":"コメント数の順にソートするにはクリック",
		"SORT_RECOMMENDATIONS_LABEL":"「いいね」の数の順にソートするにはクリック",
		"SORT_POPULARITY_LABEL":"人気度順にソートするにはクリック",
		"SORT_FIRST_NAME_LABEL":"名前順にソートするにはクリック",
		"SORT_LAST_NAME_LABEL":"姓順にソートするにはクリック",
		"RATING":"いいね",
		"GRADUATED":"投票終了",
		"ONEVOTE":"1 票",
		"VOTES":"{0} 票",
		"BOOKMARK_THIS_RESULT":"これをブックマーク",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (非アクティブ)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} 人のユーザーがブックマーク付け",
		/* eg from an Activity */
		"FROMANACTIVITY":"アクティビティーから",
		"FROMABLOG":"ブログから",
		"FROMANIDEATIONBLOG":"アイデア・ブログから",
		"FROMANEVENT":"イベントから",
		"FROMAFORUM":"フォーラムから",
		"FROMAWIKI":"Wiki から",
		"FROMACOMMUNITY":"コミュニティーから",
		"FROMXCOMMUNITIES":"{0} コミュニティーから",
		/* For search results parentage */
		"ACTIVITY_ALONE":"アクティビティー",
		"BLOG_ALONE":"ブログ",
		"IDEATIONBLOG_ALONE":"アイデア・ブログ",
		"ENTRY_ALONE":"エントリー",
		"EVENT_ALONE":"イベント",
		"FORUM_ALONE":"フォーラム",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"コミュニティー",
		"XCOMMUNITIES_ALONE":"{0} コミュニティー",
		"SHAREDCOMMUNITIES":"これらのコミュニティーに共有",
		"INACOMMUNITY":"コミュニティーで",
		"LASTUPDATED":"検索インデックスの最終更新日時:",
		"NODESCRIPTION":"この結果に対する説明と要約はありません。",
		"ATTACHMENT":"添付ファイル:",
		"ACTIVITY":"アクティビティー:",
		"ACTIVITYBOOKMARK":"アクティビティー・ブックマーク:",
		"ACTIVITYCOMMENT":"アクティビティーのコメント:",
		"ACTIVITYENTRY":"アクティビティー・エントリー:",
		"ACTIVITYSECTION":"アクティビティー・セクション:",
		"ACTIVITYTODO":"アクティビティー To Do:",
		"BLOG":"ブログ:",
		"BLOGENTRY":"ブログ・エントリー:",
		"BLOGCOMMENT":"ブログ・コメント:",
		"BOOKMARK":"ブックマーク:",
		"CALENDAREVENT":"イベント:",
		"CATEGORY":"カテゴリー:",
		"COMMENT":"コメント:",
		"COMMUNITY":"コミュニティー:",
		"ENTRY":"エントリー:",
		"EVENTDATEON":"日付: {0}",
		"EVENTISALLDAY":"終日イベント",
		"EVENTREPEATS":"繰り返し",
		"FEED":"フィード:",
		"FILE":"ファイル:",
		"FORUM":"フォーラム:",
		"FORUMCATEGORY":"フォーラムのカテゴリー:",
		"FORUMTOPIC":"フォーラム・トピック:",
		"IDEA":"アイデア:",
		"IDEACOMMENT":"アイデア・コメント:",
		"IDEATIONBLOG":"アイデア・ブログ:",
		"PAGE":"ページ:",
		"PROFILE":"プロフィール:",
		"SECTION":"セクション:",
		"STATUSUPDATE":"最新の状況",
		"STATUSUPDATE_PREFIX":"最新の状況:",
		"TOPIC":"トピック:",
		"TOPIC_WITH_ATTACHMENT":"トピック",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Wiki ページ:",
		"WIKIFILE":"Wiki 添付ファイル:",
		"SEARCH":"検索:",
		"TODO":"To Do:",
		"ALLRESULTS":"すべての結果",
		"PUBLICCONTENT":"公開コンテンツ",
		"MYCONTENT":"マイ・コンテンツ",
		"RESULTNOTFOUND":"必要な情報が見つかりませんでしたか?",
		"TEMPDIFFICULTIES":"注: 一時的なインデックス付け障害により、過去 {1} 日間に変更された {0} が検索に含められませんでした。",
		"TRYLATER":"後でもう一度実行してください。",
		"MULTIPLETEMPDIFFICULTIES":"注: 一時的なインデックス付け障害により、最近変更された {0} が検索に含められませんでした",
		"YOUAREAUTHOR":"あなたは作成者です",
		"YOUARECONTRIBUTOR":"あなたは投稿者です",
		"YOUAREOWNER":"あなたは所有者です",
		"YOUAREMEMBER":"あなたはメンバーです",
		/* Profiles */
		"MYNETWORK":"マイ・ネットワーク",
		"ALLPEOPLE":"すべてのユーザー",
		"EXCLUDEINACTIVE":"非アクティブなユーザーを除外",
		"PHONE":"電話番号:",
		"EMAIL":"メール:",
		/* Communities */
		"ALLCOMMUNITIES":"すべてのコミュニティー",
		"PUBLICCOMMUNITIES":"公開コミュニティー",
		"MYCOMMUNITIES":"マイ・コミュニティー",
		"EVERYTHINGCOMMUNITIES":"コミュニティーのすべての内容",
		"COMMUNITIESONLY":"コミュニティー",
		"COMMUNITIESCONTENT":"コミュニティーのコンテンツ",
		/* Activities */
		"ALLACTIVITIES":"すべてのアクティビティー",
		"PUBLICACTIVITIES":"公開アクティビティー",
		"MYACTIVITIES":"マイ・アクティビティー",
		"EVERYTHINGACTIVITIES":"アクティビティーからのすべて",
		"ACTIVITIESONLY":"アクティビティー",
		"SECTIONSACTIVITIES": "アクティビティーからのセクション",
		"ENTRIESACTIVITIES":"アクティビティーからのエントリー",
		"TODOSACTIVITIES":"アクティビティーからの To Do",
		"BOOKMARKSACTIVITIES":"アクティビティーからのブックマーク",
		"FILESACTIVITIES":"アクティビティーからの添付ファイル",
		"ALLTYPESACTIVITIES":"すべてのタイプのアクティビティー",
		"COMMUNITYACTIVITIES":"コミュニティーからのアクティビティー",
		"STANDALONEACTIVITIES":"スタンドアロン・アクティビティー",
		/* Forums */
		"ALLFORUMS":"すべてのフォーラム",
		"PUBLICFORUMS":"公開フォーラム",
		"MYFORUMS":"マイ・フォーラム",
		"EVERYTHINGFORUMS":"フォーラムからのすべて",
		"FORUMSONLY":"フォーラム",
		"TOPICSFORUMS":"フォーラム・トピック",
		"FORUMCATEGORIES": "フォーラムのカテゴリー",
		"FILESFORUMS":"フォーラムからの添付ファイル",
		"ALLTYPESFORUMS":"すべてのタイプのフォーラム",
		"COMMUNITYFORUMS":"コミュニティーからのフォーラム",
		"STANDALONEFORUMS":"スタンドアロン・フォーラム",
		/* Blogs */
		"ALLBLOGS":"すべてのブログ",
		"PUBLICBLOGS":"公開ブログ",
		"MYBLOGS":"マイ・ブログ",
		"EVERYTHINGBLOGS":"ブログからのすべて",
		"BLOGSONLY":"ブログ",
		"ENTRIESBLOGS":"ブログ・エントリー",
		"FILESBLOGS":"ブログからの添付ファイル",
		"EVERYTHINGIDEATIONBLOGS":"アイデア・ブログからのすべて",
		"BLOGSIDEATIONBLOGS":"アイデア・ブログ",
		"BLOGSIDEAS":"アイデア",
		"ALLTYPESBLOGS":"すべてのタイプのブログ",
		"COMMUNITYBLOGS":"コミュニティーからのブログ",
		"COMMUNITYIDEATIONBLOGS":"コミュニティーからのアイデア・ブログ",
		"STANDALONEBLOGS":"スタンドアロン・ブログ",
		/* Bookmarks */
		"ALLBOOKMARKS":"すべてのブックマーク",
		"PUBLICBOOKMARKS":"公開ブックマーク",
		"MYBOOKMARKS":"マイ・ブックマーク",
		"ALLTYPESBOOKMARKS":"すべてのタイプのブックマーク",
		"COMMUNITYBOOKMARKS":"コミュニティーからのブックマーク",
		"STANDALONEBOOKMARKS":"スタンドアロン・ブックマーク",
		/* Files */
		"ALLFILES":"すべてのファイル",
		"PUBLICFILES":"公開ファイル",
		"MYFILES":"マイ・ファイル",
		"ALLTYPESFILES":"すべてのタイプのファイル",
		"COMMUNITYFILES":"コミュニティーからのファイル",
		"STANDALONEFILES":"スタンドアロン・ファイル",
		"NUMDOWNLOADS":"{0} 件のダウンロード",
		/* Wikis */
		"ALLWIKIS":"すべての Wiki",
		"PUBLICWIKIS":"公開 Wiki",
		"MYWIKIS":"マイ Wiki",
		"EVERYTHINGWIKIS":"Wiki からのすべて",
		"WIKISONLY":"Wiki",
		"PAGESWIKIS":"Wiki ページ",
		"FILESWIKIS":"Wiki からの添付ファイル",
		"ALLTYPESWIKIS":"すべてのタイプの Wiki",
		"COMMUNITYWIKIS":"コミュニティーからの Wiki",
		"STANDALONEWIKIS":"スタンドアロン Wiki",
		/* Status Updates */
		"ALLSTATUSUPDATES":"すべての最新の状況",
		"PUBLICSTATUSUPDATES":"公開されている最新の状況",
		"MYSTATUSUPDATES":"自分の最新の状況",
		"ALLTYPESSTATUSUPDATES":"すべてのタイプの最新の状況",
		"COMMUNITYSTATUSUPDATES":"コミュニティーからの最新の状況",
		"STANDALONESTATUSUPDATES":"プロフィールからの最新の状況",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"この URL は、多数のユーザーによってブックマークされています",
		"BOOKMARKEDCOMMUNITY":"このコミュニティーは、多数のユーザーによってブックマークされています",
		"BOOKMARKEDPROFILE":"このプロフィールは、多数のユーザーによってブックマークされています",
		"BOOKMARKEDBLOG":"このブログは、多数のユーザーによってブックマークされています",
		"COMMUNITYBLOG":"これは、コミュニティー内のブログです",
		"BOOKMARKEDACTIVITY":"このアクティビティーは、多数のユーザーによってブックマークされています",
		"COMMUNITYACTIVITY":"これは、コミュニティー内のアクティビティーです",
		"BOOKMARKEDFILE":"このファイルは、多数のユーザーによってブックマークされています",
		"COMMUNITYFILE":"これは、コミュニティー内のファイルです",
		"BOOKMARKED":"この Wiki は、多数のユーザーによってブックマークされています",
		"COMMUNITYWIKI":"これは、コミュニティー内の Wiki です",
		"BOOKMARKEDFORUM":"このフォーラムは、多数のユーザーによってブックマークされています",
		"COMMUNITYFORUM":"これは、コミュニティー内のフォーラムです",
		"ALLTAGANDTTILE":"この URL のすべてのタイトルとタグを表示するには、このボタンをクリックしてください",
		"TAGS_ARE_FROM":"この検索結果には、次に示す項目からのタグが含まれている可能性があります。",
		"BOOKMARKS_TITLE":"ブックマーク",
		"COMMUNITIES_TITLE":"コミュニティー",
		"ACTIVITIES_TITLE":"アクティビティー",
		"HELP":"ヘルプ",
		"MORESTATUSUPDATES":"最新の状況をさらに表示",
		"TITLE_PREFIX":"タイトル:",
		"LATEST_MESSAGE":"最新メッセージ",
		"LATEST_STATUS_UPDATE":"最近の最新の状況",
		"LATEST_COMMUNITY_STATUS_UPDATE":"最近のコミュニティー最新状況",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"最近のコミュニティー最新状況",
		"SEARCH_RESULTS":"すべてのコンテンツ検索結果",
		"ACTIVITIES_SEARCH_RESULTS":"アクティビティーの検索結果",
		"BLOGS_SEARCH_RESULTS":"ブログの検索結果",
		"BOOKMARKS_SEARCH_RESULTS":"ブックマークの検索結果",
		"COMMUNITIES_SEARCH_RESULTS":"コミュニティーの検索結果",
		"FILES_SEARCH_RESULTS":"ファイルの検索結果",
		"FORUMS_SEARCH_RESULTS":"フォーラムの検索結果",
		"PROFILES_SEARCH_RESULTS":"プロフィールの検索結果",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} ディレクトリー検索結果",
		"WIKIS_SEARCH_RESULTS":"Wiki の検索結果",
		"STATUS_UPDATES_SEARCH_RESULTS":"最新の状況の検索結果",
		"VIEW_ALL":"{span}すべて表示{/span} ({0})",
		"MATCHING_ONE_OF":"次のいずれかと一致:",
		"MATCHING_ALL_OF":"次のすべてと一致:",
		"MATCHING":"マッチング:",
		"MATCHING_DOC_TYPE":"文書タイプのマッチング:",
		"BOOKMARK_HELP":"ブックマークのヘルプ",
		"CLOSE_BOOKMARK_HELP":"ブックマークのヘルプを閉じる",
		"DOCUMENT_TYPE_PREFIX":"文書タイプ:",
		"LAST_PAGE_MESSAGE": "検索結果が多すぎます。 さらに検索語を追加することで検索を絞り込んでください。",
		"LAST_PAGE_SUBMESSAGE": "最初の {resultNumber} 件の関連性の高い結果を取得します。"
});

