/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "O título é requerido.",
	nourl: "O URL é requerido.",
	fileSchema: "Caso pretenda adicionar uma ligação para um ficheiro remoto ou local, esta tem de estar em conformidade com um dos seguintes formatos: ficheiro://caminho_remoto ou ficheiro:///caminho_local.",
	invalidUrl: "Não se trata de um URL da comunidade válido.",
	invalidTagChar: "A lista de etiquetas introduzida contém o caráter inválido \"&\". Remova este caráter da lista de etiquetas.",
	txtHelp: "Ajuda",
	txtHelpTags: "Ajuda de etiquetas",
	txtHelpTagsClose: "Fechar ajuda de etiquetas",
	tagsall: "Tudo",
	tagsyours: "As suas",
	tagsrecent: "Recentes: ",
	tagspopular: "Populares: ",
	tagsrecommended: "Recomendadas: ",
	nothingselected: "É requerida a selecção de uma comunidade.",
	nothingselected_activity: "É requerida a selecção de uma actividade.",
	nothingselected_blogs: "É requerida a selecção de um blogue.",
	nothingselected_all: "Não está seleccionado qualquer serviço ou entrada, pelo que o marcador não será guardado.",
	nothingFeedselected: "Não está seleccionado qualquer serviço ou entrada, pelo que o feed não será guardado.",
	alertDialogTitle: "Mensagem",
	alertDialogOK: "OK",
	expand: "Faça clique para expandir esta secção",
	collapse: "Faça clique para contrair esta secção",
	discussThis: "Debater isto",
	by: "por:",
	posted: "Publicado:",
	attachments: "Anexos",
	communityForum: "Fórum da comunidade",
	notCommunityPage: "A página da Web actual não corresponde a uma página da Web da comunidade válida. Pode introduzir manualmente o título, a ligação e a descrição da comunidade para criar uma comunidade relacionada.",
	privateCommunityNotice: "Esta comunidade é restrita. Apenas está visível para os membros da comunidade.",
	forumNameHint : "Introduza o nome de um fórum",
	formDescriptionHint:"Descreva o motivo pelo qual esta comunidade relacionada poderá ser do interesse da sua comunidade.",
	information : "Informações",
	error : "Erro",
	success : "Êxito",
	warning : "Aviso",
	informationColon : "Informações:",
	successColon : "Êxito:",
	warningColon : "Aviso:",
	errorColon : "Erro:",
	feedAlreadyExist : "O feed já existe na comunidade.",
	bookmarkAlreadyExist : "O marcador já existe na comunidade.",
	mentionAuthWarning:"As pessoas referidas em seguida não poderão visualizar a mensagem, uma vez que não são membros da comunidade:",
	mentionAuthForumWarning:"As pessoas referidas em seguida não poderão visualizar a mensagem, uma vez que não podem aceder a este fórum:",
	exceedDescLength: "A descrição introduzida é demasiado longa.",
	communities_checked:"${0} comunidade(s) seleccionada(s)",
	activities_checked:"${0} actividade(s) seleccionada(s)",
	blogs_checked:"${0} blogue(s) seleccionado(s)"
})
