/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "הוספת תמונה",
   newUpload : "טעינה חדשה",
   URL : "URL",
   imageLibrary : "ספריית תמונות",
   description : "תיאור:",
   imageFile : "קבצים:",
   OK: "אישור",
   cancel: "ביטול",
   required: "שדה דרוש",
   preview: "תצוגה מקדימה:",
   previewWarning: "נראה שטעינת התמונה לא הצליחה, אתם בטוחים שזהו URL תמונה חוקי?",
   alt: "תמליל חלופי:",
   filesTab: "מיישום הקבצים",
   images:"תמונות:",
   browse:"עיון...‏",
   imagePickerTitle:"הוספת תמונה מיישום הקבצים",
   componentImagePickerTitle:" ${0} תמונות שנטענו",
   /* New String for insert image dialog */
   title: "הוספת תמונה",
   uploadBtn: "טעינת תמונה",   
   insertBtn: "הוספת תמונה",
   uploadTab: "קבצים מקומיים",
   externalTab: "כתובת URL",
   internalTab: "תמונות קיימות",
   fileFieldTip: "גררו ושחררו תמונות משולחן העבודה ישירות לתוך חלון זה כדי לטעון אותן.",
   AdditionalSection: "אפשרויות נוספות",
   ExpandSection: "הרחבת אפשרויות נוספות",
   CloseSection: "כיווץ אפשרויות נוספות",
   webURLPrompt: "URL של תמונה:",
   previewPrompt: "אזור תצוגה מקדימה: יתכן שיידרש זמן מה להצגת תמונות גדולות.",
   noExistingImage: "בעיה! עדיין לא נוספו תמונות.",
   selectExistingImage: "בחירת תמונה קיימת:",
   urlMissing: "נא לציין URL",
   urlInvalid: "URL לא חוקי. הקפידו לציין URL חוקי ונסו שוב.",
   previousItem: "הקודם",
   nextItem: "הבא",
   oneImageOneTime: "כבר נוספה תמונה לחלון זה. אפשר להוסיף רק תמונה אחת בכל פעם.",
   loadingErrorMsg: "אירעה שגיאה בטעינת התמונות הקיימות. נסו שוב מאוחר יותר",
   urlInputTooltip: "ציינו את ה-URL של התמונה"
})

