/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "פרטי צומת: ",
		"INSTALLED": "בדיקת השירותים המותקנים",
		"RESUMETOKENS": "בדיקת אסימוני החידוש",
		"SEEDLISTS": "בדיקת זמינות של רשימות הזרעה",
		"CALENDARS": "בדיקה שיומני התזמון מוגדרים כהלכה",
		"VARIABLES": "בדיקה שמשתני WebSphere הוגדרו",
		"TASKS": "בדיקת משימות מפתוח מופעלות",
		"INDEXFILES": "בדיקת קבצים דרושים בתיקיית האינדקס",
		"LOGS": "סקירת יומנים לאיתור שגיאות",
		"CONFIGFILES": "סקירת קובצי התצורה",
		"DICTIONARIES": "בדיקת מספר המילונים שהופעלו",
		"SYNC": "בדיקת מצב הצמתים",
		"DBRECORDS": "בדיקת רשומות מסד הנתונים",
		"INSTALLEDMSG": "השירות שלהלן מותקן: ",
		"RESUMETOKENSMSG": "אסימון החידוש עבור: ",
		"SEEDLISTSMSG": "לא ניתן לקבל את רשימת ההזרעה עבור: ",
		"CALENDARSMSG": "בדיקת יומני התזמון הצליחה: ",
		"VARIABLESMSG": "משתנה: ",
		"TASKSMSG": "המשימה שלהלן מופעלת: ",
		"INDEXFILESMSG" : "הקבצים שלהלן נמצאים בתיקיית אינדקס החיפוש: ",
		"LOGSMSG" : "עיינו בהודעות השגיאה שלהלן: ",
		"CONFIGFILESMSG" : "נמצאו קובצי התצורה שלהלן: ",
		"DICTIONARIESMSG" : "מספר המילונים המופעלים הוא: ",
		"INSYNC": "כל הצמתים מסונכרנים",
		"OUTOFSYNC": "מספר הצמתים שאינם מסונכרנים: ",
		"NOTBLOCKED": "אין צמתים חסומים",
		"BLOCKED": "מספר הצמתים החסומים הוא: ",
		"INDATE": "כל הצמתים עדכניים",
		"OUTOFDATE": "מספר הצמתים שאינם עדכניים הוא: ",
		"NUMOFDOCS": "מספר המסמכים במסד הנתונים הוא ",
		"FILESTOCONVERT": "מספר קובצי המסמכים להמרה הוא ",
		"CONVERTEDFILES": "מספר הקבצים שהומרו הוא ",
		"TOTALFILES": "מספר כולל של קבצים במסד הנתונים ",
		"ERROR":"שגיאה",
		"ERROR_PREFIX":"שגיאה:",
		"INFO":"מידע",
		"INFO_PREFIX":"מידע:‏",
		"WARNING":"אזהרה",
		"WARNING_PREFIX":"אזהרה:",
		"LOADING_MESSAGE": "טעינה בביצוע",
		"SERVER_STATUS": "מצב שרת",
		"INITIAL_INDEXING_EXCEPTIONS": "חריגות מיפתוח ראשוני",
		"SYS_OUT_EXCEPTIONS": "חריגות ביומן SystemOut",
		"SEEDLIST_VALIDATE": "אימות רשימת הזרעה",
		"ERRORS_DURING_INITIAL_INDEXING":"השגיאות שלהלן אירוע ביצירת מפתח ראשונה",
		"CRAWL_FAILED": "לא ניתן לנבור בכל הנתונים עבור השירותים שלהלן: ",
		"EXCEPTION_ENCOUNTERED": "הנבירה נכשלה עם ההודעה שלהלן: ",
		"SAND_VALIDATE": "אימות SAND",
		"CHECK_FOR_SAND_FILES":"בדיקת קובצי SAND",
		"IS_FILE_AVAILABLE":"בדיקה שהקובץ נוצר: ",
		"ERRORS_DURING_INITIAL_INDEXING":"השגיאות שלהלן אירוע ביצירת מפתח ראשונה",
		"CRAWL_FAILED":"לא ניתן לנבור בכל הנתונים עבור השירותים שלהלן: ",
		"EXCEPTION_ENCOUNTERED":"הנבירה נכשלה עם ההודעה שלהלן: "
});

