/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Titlul este necesar.",
	nourl: "URL-ul este necesar.",
	fileSchema: "Dacă vreţi să adăugaţi o legătură de fişier local sau la distanţă, trebuie să fie conformă cu unul din următoarele formate: file://cale_la_distanţă sau file:///cale_locală.",
	invalidUrl: "Acesta nu este un URL de comunitate valid.",
	invalidTagChar: "Lista de taguri pe care ați introdus-o conține caracterul nevalid '&'. Eliminați acest caracter din lista de taguri.",
	txtHelp: "Ajutor",
	txtHelpTags: "Ajutor Taguri",
	txtHelpTagsClose: "Tagurile ajută la închidere",
	tagsall: "Toate",
	tagsyours: "Ale dumneavoastră",
	tagsrecent: "Recente: ",
	tagspopular: "Populare: ",
	tagsrecommended: "Recomandate: ",
	nothingselected: "O selecţie comunitate este necesară.",
	nothingselected_activity: "O selecţie activitate este necesară.",
	nothingselected_blogs: "O selecţie blog este necesară.",
	nothingselected_all: "Nu este selectat nici un serviciu sau intrare, semnul de carte nu va fi salvat.",
	nothingFeedselected: "Nu este selectat nici un serviciu sau intrare, alimentarea nu va fi salvată.",
	alertDialogTitle: "Mesaj",
	alertDialogOK: "OK",
	expand: "Faceţi clic pentru a expanda această secţiune",
	collapse: "Faceţi clic pentru a restrânge această secţiune",
	discussThis: "Discutaţi aceasta",
	by: "de către:",
	posted: "Postat:",
	attachments: "Ataşamente",
	communityForum: "Forum Comunitate",
	notCommunityPage: "Pagina de web curentă nu este o pagină de web comunitate validă. Puteţi introduce manual titlul comunităţii, legătura şi descrierea pentru a crea o comunitate înrudită.",
	privateCommunityNotice: "Această comunitate este restricţionată. Este vizibilă numai pentru membrii comunităţii.",
	forumNameHint : "Tastaţi un nume de forum",
	formDescriptionHint:"Descrieţi de ce această comunitate înrudită ar interesa comunitatea dumneavoastră.",
	information : "Informaţii",
	error : "Eroare",
	success : "Succes",
	warning : "Avertisment",
	informationColon : "Informaţii:",
	successColon : "Succes:",
	warningColon : "Avertisment:",
	errorColon : "Eroare:",
	feedAlreadyExist : "Alimentarea există deja în comunitate.",
	bookmarkAlreadyExist : "Semnul de carte există deja în comunitate.",
	mentionAuthWarning:"Următoarele persoane menţionate nu vor putea vizualiza mesajul, deoarece nu sunt membri ai comunităţii:",
	mentionAuthForumWarning:"Următoarele persoane menţionate nu vor putea vizualiza mesajul, deoarece nu pot accesa acest forum:",
	exceedDescLength: "Descrierea pe care aţi introdus-o este prea lungă.",
	communities_checked:"${0} comunităţi selectate",
	activities_checked:"${0} activităţi selectate",
	blogs_checked:"${0} bloguri selectate"
})
