/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Clique aqui para visualizar o cartão de visita",
	"label.semtag.hover.alt" : "Clique aqui para visualizar o cartão de visita para {0}",
	"label.semtag.hover.altA11Y" : "Clique aqui ou pressione Control-Enter para visualizar o cartão de visita",
	"label.personcard.dialog.title" : "Cartão de visita para {0}",

	"errorDefaultMsg2" : "Ocorreu um erro. Entre em contato com o administrador do sistema.",

	"loadingSTStatus" : "Carregando status do Sametime...",
	"noStatuAvailable" : "Nenhum status do Sametime disponível",

	"label.personcard.cardnomarkup" : "O cartão de visita não pôde ser recuperado",
	"label.inactive.user.msg" : "Esta pessoa não é mais um usuário ativo",
	"label.message.information" : "Informações:",
	"label.personcard.noprofilemsg" : "Não existe um perfil para esta pessoa",
	"label.personcard.cardreqexpired" : "A solicitação para obter o cartão de visita expirou",

	"label.bizcard.applinks.less" : "Mostrar menos",
	"label.bizcard.applinks.more" : "Mostrar mais",

	"label.personcard.activitieslink" : "Atividades",
	"label.personcard.activitieslink.title" : "Clique aqui para ver as atividades em comum",
	"label.personcard.blogslink" : "Blogs",
	"label.personcard.blogslink.title" : "Clique aqui para ver o blog desta pessoa",
	"label.personcard.communitieslink" : "Comunidades",
	"label.personcard.communitieslink.title" : "Clique aqui para ver as comunidades desta pessoa",
	"label.personcard.dogearlink" : "Favoritos",
	"label.personcard.dogearlink.title" : "Clique aqui para ver os favoritos desta pessoa",
	"label.personcard.fileslink" : "Arquivos",
	"label.personcard.fileslink.title" : "Clique aqui para ver os arquivos compartilhados desta pessoa",
	"label.personcard.forumlink" : "Fóruns",
	"label.personcard.forumlink.title" : "Clique aqui para ver as postagens de fórum desta pessoa",
	"label.personcard.homepagelink" : "Página inicial",
	"label.personcard.homepagelink.title" : "Clique aqui para ver página inicial desta pessoa",
	"label.personcard.mobilelink" : "Celular",
	"label.personcard.mobilelink.title" : "Clique aqui para ver a página do dispositivo móvel desta pessoa",
	"label.personcard.newslink" : "Notícias",
	"label.personcard.newslink.title" : "Clique aqui para ver as notícias desta pessoa",
	"label.personcard.profilelink" : "Perfil",
	"label.personcard.profilelink.title" : "Clique aqui para ver o perfil desta pessoa",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Clique aqui para ver os compartilhamentos quickr desta pessoa",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Clique aqui para ver os wikis desta pessoa",

	"personCardMoreActions" : "Mais Ações",
	"personCardMoreActionsAltText" : "Clique para obter o menu de ação",

	"label.bizcard.dismiss": "Pressione Escape para recusar este cartão de visita.",
	"label.bizcard.fullProfile": "Perfil Completo",
	"label.bizcard.activities": "Atividades",
	"label.bizcard.communities": "Comunidades",
	"label.bizcard.files": "Arquivos",
	"label.bizcard.forums": "Fóruns",
	"label.bizcard.bookmarks": "Favoritos",
	"label.bizcard.blogs": "Blogs",
	"label.bizcard.wikis": "Wikis",

	"personCardAddAsColleagues" : "Convidar para Minha Rede",
	"personCardAddAsMyColleagues" : "Convidar para Minha Rede",
	"personCardFollow" : "Seguir",
	"personCardUnfollow" : "Parar de Seguir",
	"personCardChat" : "Bate-papo",
	"personCardCall" : "Chamar",
	"personCardSendMail" : "Enviar E-mail",
	"personCardSendEMail" : "Enviar E-mail",
	"personCardProxyStatusAvailable" : "Estou disponível",
	"personCardDownloadVCard" : "Fazer download do vCard",

	"friends" : "Rede",
	"friendsFullPageTitle" : "Rede",
	"friendsMenuTitleAllContacts" : "Todos os Contatos da Rede",
	"friendsMenuTitleMyContacts" : "Meus Contatos da Rede",
	"friendsInvitations" : "Convites",
	"friendsMenuTitleInCommon" : "Pessoas em Comum",
	"friendsShowAllCommonFriends" : "Mostrar todos...",
	"friendsViewAllFriends" : "Visualizar Todos ({0})",
	"friendsSendFriendRequest" : "Enviar solicitação",
	"friendsNoFriends" : "Nenhum contato da rede está associado a este perfil",
	"friendsColleaguesInvite" : "Convide {0} para ser seu contato da rede",
	"friendsColleaguesFor" : "Contatos da rede de {0}",
	"friendsNewInv" : "{0} novo convite",
	"friendsNewInvs" : "{0} novos convites",
	"friendsLoading" : "Carregando Rede...",
	"friendsLoadingInv" : "Carregando Convites...",
	"friendsSelectFriendForRemoval" : "Selecione os contatos que você deseja remover primeiro.",
	"friendsRemoved" : "Contato(s) de rede removido(s).",
	"friendsInvSent" : "Nenhum convite foi enviado por que um convite já está pendente.",
	"friendsRemovedSelected" : "Remover da Minha Rede",
	"friendsSortByDisplayName" : "Nome de Exibição",
	"friendsSortByRecent" : "Recente",
	"friendsTelephone" : "Telefone:",
	"friendsEmail" : "E-mail:",
	"friendsAltEmail" : "E-mail Alternativo:",
	"friendsNewInvitationsCount" : "Você tem {0} novo(s) convite(s)",
	"friendsNoInv" : "Sem convites",
	"friendsInCommonSingle" : "Vocês têm {0} contato da rede em comum",
	"friendsInCommonMulti" : "Vocês têm {0} contatos da rede em comum",
	"friendsIncludeMsgForInv" : "Inclua uma mensagem em seu convite:",
	"friendsInitialMsgForInv" : "Eu gostaria de incluir você em minha lista de contatos da rede Connections.",
	"friendsSendInvAction" : "Enviar Convite",
	"friendsCancelInvAction" : "Cancelar",
	"friendsAcceptAction" : "Aceitar",
	"friendsIgnoreAction" : "Ignorar",
	"friendsYouExceedTextLimit" : "Sua mensagem de convite é muito longa. Pode ter um máximo de {1} caracteres. Há {0} caracteres neste campo.",
	"friendsCannotAddYourself" : "Você não pode se incluir como um contato da rede.",
	"friendsIsYourColleague" : "{0} é seu contato da rede.",
	"friendsRecentlyAdded" : "Pessoas incluídas recentemente na sua rede.",
	"friendsDate" : "Data",
	"friendsCollapseWidget" : "Clique para reduzir a seção da rede",
	"friendsExpandWidget" : "Clique para expandir a seção da rede",
	"friendsIsInYourNetwork" : "{0} está em sua rede.",
	"friendsActionsFor" : "Ações para a Rede",
	"friendsInviteFollowError" : "Ocorreu um erro ao tentar seguir {0}",
	"friendsInviteTagError" : "Ocorreu um erro ao tentar marcar {0}",
	"friendsPleaseLogIn" : "Efetue login para convidar pessoas para sua rede",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "O convite para a sua rede não é possível porque o {0} já está em sua rede.",
	"friendsInviteAddTagsFor" : "Adicionar marcações para {0}:",
	"friendsInviteAlsoFollow" : "Seguir Também",
	"friendsInviteReceiveUpdates" : "(receber atualizações)",
	"friendsInviteUpdatesDescription" : "Receba atualizações sobre pessoas que você está seguindo na Página Inicial e em um resumo de e-mail.",
	"friendsInviteFollowHelp": "Para obter mais informações, consulte {0}Seguindo pessoas{1}.",
	"friendsNetwork" : "Rede",
	"friendsMyNetwork" : "Rede",
	"friendsNetworkFor" : "Rede de {0}",
	"friendsRemoveSelected" : "Remover Selecionado",
	"friendsRemoveSelectedTip" : "Clique para remover as pessoas selecionadas da sua rede.",
	"friendsNetworkInCommon" : "Você possui {0} conexões da rede em comum.",
	"friendsAddToMyNetwork" : "Eu gostaria de incluir você em minha rede do Connections.",
	"friendsInvite" : "Convidar para Minha Rede",
	"friendsInvitePerson" : "Convidar {0} para sua rede",
	"friendsInviteMessage" : "Eu gostaria de incluir você em minha rede do Connections.",
	"friendsInvitedEmailSubject" : "[Perfis] Você está convidado a ingressar na minha rede",
	"friendsInvitedEmailMsg1" : "convidou você para se tornar um contato da rede com a seguinte mensagem incluída no convite:",
	"friendsInvitedEmailMsg2" : "Página Abrir o Convite da Rede",
	"friendsInvitedEmailMsg3" : "Desejo incluir você à minha rede.",
	"friendsInvitedEmailMsg4" : "{0} convidou você para se tornar um contato da rede:",
	"friendsInvitedEmailMsg5" : "{0} convidou você para se tornar um contato da rede com a seguinte mensagem incluída no convite:",
	"friendsInviteLegalNote" : "Ao enviar este convite, você concorda em permitir que {0} faça comentários no seu quadro de perfil.",
	"friendsInviteFailed" : "Devido a um erro do servidor, uma notificação de e-mail não foi enviada para o convidado. No entanto, o convidado ainda poderá aceitar seu convite por meio do aplicativo de Perfis da web.",
	"personInNetwork" : "Contato"
})
