/* Copyright IBM Corp. 2011, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Klik di sini untuk melihat kartu nama",
	"label.semtag.hover.alt" : "Klik untuk melihat kartu nama untuk {0}",
	"label.semtag.hover.altA11Y" : "Klik di sini atau tekan control-enter untuk melihat kartu nama",
	"label.personcard.dialog.title" : "Kartu nama untuk {0}",

	"errorDefaultMsg2" : "Terjadi kesalahan, hubungi administrator sistem Anda",

	"loadingSTStatus" : "Memuat status Sametime...",
	"noStatuAvailable" : "Tidak ada status Sametime tersedia",

	"label.personcard.cardnomarkup" : "Kartu nama tidak dapat diperoleh",
	"label.inactive.user.msg" : "Orang ini tidak lagi merupakan pengguna aktif",
	"label.message.information" : "Informasi:",
	"label.personcard.noprofilemsg" : "Tidak ada profil mengenai orang ini",
	"label.personcard.cardreqexpired" : "Permintaan untuk mendapatkan kartu nama telah habis waktunya",

	"label.bizcard.applinks.less" : "Tampilkan sedikit",
	"label.bizcard.applinks.more" : "Tampilkan banyak",

	"label.personcard.activitieslink" : "Aktivitas",
	"label.personcard.activitieslink.title" : "Klik di sini untuk melihat aktivitas yang dibagi",
	"label.personcard.blogslink" : "Blog",
	"label.personcard.blogslink.title" : "Klik di sini untuk melihat blog orang ini",
	"label.personcard.communitieslink" : "Komunitas",
	"label.personcard.communitieslink.title" : "Klik di sini untuk melihat komunitas orang ini",
	"label.personcard.dogearlink" : "Markah",
	"label.personcard.dogearlink.title" : "Klik di sini untuk melihat markah orang ini",
	"label.personcard.fileslink" : "File",
	"label.personcard.fileslink.title" : "Klik di sini untuk melihat file yang dibagi orang ini",
	"label.personcard.forumlink" : "Forum",
	"label.personcard.forumlink.title" : "Klik di sini untuk melihat pos forum orang ini",
	"label.personcard.homepagelink" : "Alamat Rumah",
	"label.personcard.homepagelink.title" : "Klik di sini untuk melihat laman orang ini",
	"label.personcard.mobilelink" : "Nomor ponsel",
	"label.personcard.mobilelink.title" : "Klik di sini untuk melihat halaman mobile orang ini",
	"label.personcard.newslink" : "Berita",
	"label.personcard.newslink.title" : "Klik di sini untuk melihat berita orang ini",
	"label.personcard.profilelink" : "Profil",
	"label.personcard.profilelink.title" : "Klik di sini untuk melihat profil orang ini",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Klik di sini untuk melihat quickr berbagi orang ini",
	"label.personcard.wikislink" : "Wiki",
	"label.personcard.wikislink.title" : "Klik di sini untuk melihat wiki orang ini",

	"personCardMoreActions" : "Tindakan Lain",
	"personCardMoreActionsAltText" : "Klik untuk menu tindakan",

	"label.bizcard.dismiss": "Tekan keluar untuk menyingkirkan kartu nama ini.",

	"personCardAddAsColleagues" : "Undang ke Jaringan Saya",
	"personCardAddAsMyColleagues" : "Undang ke Jaringan Saya",
	"personCardFollow" : "Ikuti",
	"personCardUnfollow" : "Berhenti Mengikuti",
	"personCardChat" : "Obrolan",
	"personCardCall" : "Hubungi",
	"personCardSendMail" : "Kirim Email",
	"personCardSendEMail" : "Kirim Email",
	"personCardProxyStatusAvailable" : "Saya tersedia",
	"personCardDownloadVCard" : "Unduh vCard",

	"friends" : "Jaringan",
	"friendsFullPageTitle" : "Jaringan",
	"friendsMenuTitleAllContacts" : "Semua Kontak Jaringan",
	"friendsMenuTitleMyContacts" : "Kontak Jaringan Saya",
	"friendsInvitations" : "Undangan",
	"friendsMenuTitleInCommon" : "Orang yang sama",
	"friendsShowAllCommonFriends" : "Tampilkan semua...",
	"friendsViewAllFriends" : "Lihat Semua ({0})",
	"friendsSendFriendRequest" : "Kirim permintaan",
	"friendsNoFriends" : "Tidak ada kontak jaringan yang terkait dengan profil ini",
	"friendsColleaguesInvite" : "Undang {0} untuk menjadi kontak jaringan Anda",
	"friendsColleaguesFor" : "Kontak Jaringan untuk {0}",
	"friendsNewInv" : "{0} undangan baru",
	"friendsNewInvs" : "{0} undangan baru",
	"friendsLoading" : "Memuat Jaringan...",
	"friendsLoadingInv" : "Memuat Undangan...",
	"friendsSelectFriendForRemoval" : "Pilih kontak yang ingin Anda hapus terlebih dahulu.",
	"friendsRemoved" : "Kontak jaringan dihapus.",
	"friendsInvSent" : "Tidak ada undangan yang dikirim karena undangan tertunda.",
	"friendsRemovedSelected" : "Hapus dari Jaringan Saya",
	"friendsSortByDisplayName" : "Nama Tampilan",
	"friendsSortByRecent" : "Terkini",
	"friendsTelephone" : "Telepon:",
	"friendsEmail" : "Email:",
	"friendsAltEmail" : "Email Alternatif:",
	"friendsNewInvitationsCount" : "Anda memiliki {0} undangan(-undangan) baru",
	"friendsNoInv" : "Tidak ada undangan",
	"friendsInCommonSingle" : "Anda memiliki {0} kontak jaringan yang sama",
	"friendsInCommonMulti" : "Anda memiliki {0} kontak jaringan yang sama",
	"friendsIncludeMsgForInv" : "Sertakan pesan dengan undangan Anda:",
	"friendsInitialMsgForInv" : "Saya ingin menambahkan Anda ke daftar kontak jaringan Koneksi saya.",
	"friendsSendInvAction" : "Kirim Undangan",
	"friendsCancelInvAction" : "Batal",
	"friendsAcceptAction" : "Terima",
	"friendsIgnoreAction" : "Abaikan",
	"friendsYouExceedTextLimit" : "Pesan undangan Anda terlalu panjang. Maksimum {1} karakter. Terdapat {0} karakter di kolom ini.",
	"friendsCannotAddYourself" : "Anda tidak dapat menambahkan diri Anda sendiri sebagai kontak jaringan.",
	"friendsIsYourColleague" : "{0} adalah kontak jaringan Anda",
	"friendsRecentlyAdded" : "Orang yang baru ditambahkan ke jaringan Anda.",
	"friendsDate" : "Tanggal",
	"friendsCollapseWidget" : "Klik untuk melipat bagian jaringan",
	"friendsExpandWidget" : "Klik untuk mengembangkan bagian jaringan",
	"friendsIsInYourNetwork" : "{0} berada dalam jaringan Anda.",
	"friendsActionsFor" : "Tindakan untuk Jaringan",
	"friendsInviteFollowError" : "Terjadi kesalahan ketika mencoba untuk mengikuti {0}",
	"friendsInviteTagError" : "Terjadi kesalahan ketika mencoba untuk menandai {0}",
	"friendsPleaseLogIn" : "Harap login untuk mengundang orang ke jaringan Anda",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Undangan ke jaringan Anda tidak mungkin dilakukan karena {0} telah berada di jaringan Anda.",
	"friendsInviteAddTagsFor" : "Tambah tanda untuk {0}:",
	"friendsInviteAlsoFollow" : "Ikuti juga",
	"friendsInviteReceiveUpdates" : "(menerima pembaruan)",
	"friendsInviteUpdatesDescription" : "Menerima pembaruan mengenai orang yang Anda ikuti pada Laman dan dalam ringkasan email.",
	"friendsInviteFollowHelp": "Untuk informasi lebih lanjut, lihat {0}Orang yang Mengikuti{1}.",
	"friendsNetwork" : "Jaringan",
	"friendsMyNetwork" : "Jaringan",
	"friendsNetworkFor" : "Jaringan untuk {0}",
	"friendsRemoveSelected" : "Hapus yang Dipilih",
	"friendsRemoveSelectedTip" : "Klik untuk menghapus orang yang dipilih dari jaringan Anda.",
	"friendsNetworkInCommon" : "Anda memiliki {0} koneksi jaringan yang sama.",
	"friendsAddToMyNetwork" : "Saya ingin menambahkan Anda ke jaringan Koneksi saya.",
	"friendsInvite" : "Undang ke Jaringan Saya",
	"friendsInvitePerson" : "Undang {0} ke jaringan Anda",
	"friendsInviteMessage" : "Saya ingin menambahkan Anda ke jaringan Koneksi saya.",
	"friendsInvitedEmailSubject" : "[Profiles] Anda diundang untuk bergabung dengan jaringan saya",
	"friendsInvitedEmailMsg1" : "telah mengundang Anda untuk menjadi kontak jaringan beserta pesan berikut yang disertakan dalam undangan:",
	"friendsInvitedEmailMsg2" : "Buka halaman Undangan Jaringan Anda",
	"friendsInvitedEmailMsg3" : "Saya ingin menambahkan Anda ke jaringan saya.",
	"friendsInvitedEmailMsg4" : "{0} telah mengundang Anda untuk menjadi kontak jaringan:",
	"friendsInvitedEmailMsg5" : "{0} telah mengundang Anda untuk menjadi kontak jaringan beserta pesan berikut yang disertakan dalam undangan:",
	"friendsInviteLegalNote" : "Dengan mengirimkan undangan ini, Anda setuju untuk mengizinkan {0} memberikan komentar pada papan profil Anda.",
	"friendsInviteFailed" : "Oleh karena kesalahan server, email notifikasi tidak terkirim kepada orang yang akan diundang. Namun orang tersebut masih  dapat menerima undangan Anda melalui aplikasi web Profile."
})

