/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Filtrar por:",
"SHOW":"Mostrar:",
"ACL_FILTER_LABEL":"Filtrar por visibilidad",
"PARENT_FILTER_LABEL":"Filtrar por contenedor",
"TYPE_FILTER_LABEL":"Filtrar por tipo",
"PAGING_TOP":"Paginación primaria",
"PAGING_BOTTOM":"Paginación secundaria",
"PREVIOUS":"Anterior",
"NEXT":"Siguiente",
"PAGE":"Página {0} de {1}",
"PAGE_COLON":"Página:",
"RESULTS":"{span}{0}-{1}{/span} de {2}",
"ITEMS":"{0} elementos",
/* Application names */
"ACTIVITIES":"Actividades",
"BLOGS":"Blogs",
"CALENDAR":"Agenda",
"COMMUNITIES":"Comunidades",
"BOOKMARKS":"Marcadores",
"DOGEAR":"Marcadores",
"EVENTS":"Eventos",
"FILES":"Archivos",
"FORUMS":"Foros",
"PROFILES":"Perfiles",
"WIKI":"Wikis",
"WIKIS":"Wikis",
"FEEDS":"Canales de información",
"STATUS_UPDATES":"Actualizaciones de estado",
"ONECOMMENT":"1 comentario",
"COMMENTS":"{0} comentarios",
"ONEPERSON":"1 persona",
"PEOPLE":"{0} Personas",
"TAGS":"Etiquetas:",
"TAGSMORE":"y {0} más",
"NORESULTSMESSAGE":"No se han encontrado resultados en esta búsqueda.",
"JAN":"Enero",
"FEB":"Febrero",
"MAR":"Marzo",
"APR":"Abril",
"MAY":"Mayo",
"JUN":"Junio",
"JUL":"Julio",
"AUG":"Agosto",
"SEP":"Septiembre",
"OCT":"Octubre",
"NOV":"Noviembre",
"DEC":"Diciembre",
"NO_CONTACT":"La búsqueda no se realizó porque no fue posible contactar con el servidor.",
"SERVER_ERROR":"La búsqueda no se realizó debido a un error del servidor.",
"SORT_BY":"Ordenar por:",
"SORT_RELEVANCE":"Relevancia",
"SORT_DATE":"Fecha",
"SORT_LAST_UPDATED":"Última actualización",
"SORT_DUE_DATE":"Fecha de vencimiento",
"SORT_VISITS":"Visitas",
"SORT_COMMENTS":"Comentarios",
"SORT_RECOMMENDATION":"Gusta",
"SORT_POPULARITY":"Popularidad",
"SORT_FIRSTNAME":"Nombre",
"SORT_LASTNAME":"Apellido",
"SORT_DOWNLOADS":"Descargas",
"SORT_TYPE":"Tipo",
"SORT_SIZE":"Tamaño",
"SORT_TITLE":"Tratamiento",
"PRIVATE":"Privado",
"MODERATED":"Moderado",
"COMMUNITY_ACTIVITY":"Actividad de comunidad",
"COMMUNITY_BLOG":"Blog de comunidad",
"COMMUNITY_FILE":"Archivo de comunidad",
"COMMUNITY_FORUM":"Foro de comunidad",
"COMMUNITY_WIKI":"Wiki de comunidad",
"COMMUNITY_FEED":"Canal de información de comunidad",
"COMMUNITY_BOOKMARK":"Marcador de comunidad",
"NO_TAG":"No hay etiquetas aún",
"NO_DATE":"Aún no hay fechas",
"NO_PEOPLE":"Aún no hay nadie",
"REMOVE_FILTER_LABEL":"Pulse aquí para suprimir",
"REMOVE_FILTER_TITLE":"Eliminar",
"REMOVE_FILTER_TOOLTIP":"Suprimir este filtro",
"COMMENT_ON":"Comentar:",
"EXPAND_COLLAPSE":"Pulse aquí para expandir / contraer",
"EXPAND":"Expandir",
"COLLAPSE":"Contraer",
"EXPAND_MONTHS_FILTER":"Expandir el filtro de meses del año {0}",
"SORT_RELEVANCE_LABEL":"Pulse aquí para ordenar por relevancia",
"SORT_DATE_LABEL":"Pulse aquí ordenar por fecha",
"SORT_UPDATED_LABEL":"Pulse aquí para ordenar por última actualización",
"SORT_DUE_LABEL":"Pulse aquí para ordenar por fecha de vencimiento",
"SORT_VISITS_LABEL":"Pulse aquí para ordenar por número de visitas",
"SORT_COMMENTS_LABEL":"Pulse aquí para ordenar por número de comentarios",
"SORT_RECOMMENDATIONS_LABEL":"Pulse para ordenar por número de 'Me gusta'",
"SORT_POPULARITY_LABEL":"Pulse aquí para ordenar por popularidad",
"SORT_FIRST_NAME_LABEL":"Pulse aquí para ordenar por un nombre específico",
"SORT_LAST_NAME_LABEL":"Pulse aquí para ordenar por apellido",
"RATING":"Gusta",
"GRADUATED":"Graduada",
"ONEVOTE":"1 voto",
"VOTES":"{0} votos",
"BOOKMARK_THIS_RESULT":"Incluir esto como marcador",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inactivo)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} personas como marcador",
/* eg from an Activity */
"FROMANACTIVITY":"de una actividad",
"FROMABLOG":"de un blog",
"FROMANIDEATIONBLOG":"desde un blog de ideación",
"FROMANEVENT":"de un Evento",
"FROMAFORUM":"de un foro",
"FROMAWIKI":"de una wiki",
"FROMACOMMUNITY":"de una comunidad",
"FROMXCOMMUNITIES":"desde {0} Comunidades",
/* For search results parentage */
"ACTIVITY_ALONE":"Actividad",
"BLOG_ALONE":"Blog",
"IDEATIONBLOG_ALONE":"Blog de ideación",
"ENTRY_ALONE":"Entrada",
"EVENT_ALONE":"Evento",
"FORUM_ALONE":"Foro",
"WIKI_ALONE":"Wiki",
"COMMUNITY_ALONE":"Comunidad",
"XCOMMUNITIES_ALONE":"Comunidades de {0}",
"SHAREDCOMMUNITIES":"Compartido con estas comunidades",
"INACOMMUNITY":"en una comunidad",
"LASTUPDATED":"Fecha de la última actualización del índice de búsqueda:",
"NODESCRIPTION":"No hay ninguna descripción o resumen para este resultado.",
"ATTACHMENT":"Archivo adjunto:",
"ACTIVITY":"Actividad:",
"ACTIVITYBOOKMARK":"Marcador de actividad:",
"ACTIVITYCOMMENT":"Comentario de la actividad:",
"ACTIVITYENTRY":"Entrada de actividad:",
"ACTIVITYSECTION":"Sección de actividad:",
"ACTIVITYTODO":"Actividad pendiente:",
"BLOG":"Blog:",
"BLOGENTRY":"Entrada de blog:",
"BLOGCOMMENT":"Comentario de blog:",
"BOOKMARK":"Marcador:",
"CALENDAREVENT":"Evento:",
"CATEGORY":"Categoría:",
"COMMENT":"Comentario:",
"COMMUNITY":"Comunidad:",
"ENTRY":"Entrada:",
"EVENTDATEON":"El: {0}",
"EVENTISALLDAY":"Evento de todo el día",
"EVENTREPEATS":"Repeticiones",
"FEED":"Canal de información:",
"FILE":"Archivo:",
"FORUM":"Foro:",
"FORUMCATEGORY":"Categoría de foro:",
"FORUMTOPIC":"Tema del foro:",
"IDEA":"Idea:",
"IDEACOMMENT":"Comentario de idea:",
"IDEATIONBLOG":"Blog de ideación:",
"PAGE":"Página:",
"PROFILE":"Perfil:",
"SECTION":"Sección:",
"STATUSUPDATE":"Actualización del estado",
"STATUSUPDATE_PREFIX":"Actualización de estado:",
"TOPIC":"Tema:",
"TOPIC_WITH_ATTACHMENT":"Tema",
"WIKITYPE":"Wiki:",
"WIKIPAGE":"Página de wiki:",
"WIKIFILE":"Archivo adjunto de wiki:",
"SEARCH":"Búsqueda:",
"TODO":"Tarea pendiente:",
"ALLRESULTS":"Todos los resultados",
"PUBLICCONTENT":"Contenido público",
"MYCONTENT":"Mi contenido",
"RESULTNOTFOUND":"¿No encontró lo que estaba buscando?",
"TEMPDIFFICULTIES":"Nota: Debido a las dificultades de indexación temporales, su búsqueda no incluía {0} que se habían modificado en los últimos {1} días.",
"TRYLATER":"Vuelva a intentarlo más adelante.",
"MULTIPLETEMPDIFFICULTIES":"Nota: Debido a las dificultades de indexación temporales, su búsqueda no incluía {0} que se habían modificado recientemente",
"YOUAREAUTHOR":"Es un autor",
"YOUARECONTRIBUTOR":"Es un colaborador",
"YOUAREOWNER":"Es un propietario",
"YOUAREMEMBER":"Es un miembro",
/* Profiles */
"MYNETWORK":"Mi red",
"ALLPEOPLE":"Todas las personas",
"EXCLUDEINACTIVE":"Excluir personas inactivas",
"PHONE":"Teléfono:",
"EMAIL":"Correo electrónico:",
/* Communities */
"ALLCOMMUNITIES":"Todas las comunidades",
"PUBLICCOMMUNITIES":"Comunidades públicas",
"MYCOMMUNITIES":"Mis comunidades",
"EVERYTHINGCOMMUNITIES":"Todo de las comunidades",
"COMMUNITIESONLY":"Comunidades",
"COMMUNITIESCONTENT":"Contenido de las comunidades",
/* Activities */
"ALLACTIVITIES":"Todas las actividades",
"PUBLICACTIVITIES":"Actividades públicas",
"MYACTIVITIES":"Mis actividades",
"EVERYTHINGACTIVITIES":"Todo de las actividades",
"ACTIVITIESONLY":"Actividades",
"SECTIONSACTIVITIES": "Secciones de actividades",
"ENTRIESACTIVITIES":"Entradas de las actividades",
"TODOSACTIVITIES":"Tareas pendientes de las actividades",
"BOOKMARKSACTIVITIES":"Marcadores de actividades",
"FILESACTIVITIES":"Archivos adjuntos de las actividades",
"ALLTYPESACTIVITIES":"Todos los tipos de actividades",
"COMMUNITYACTIVITIES":"Actividades de las comunidades",
"STANDALONEACTIVITIES":"Actividades autónomas",
/* Forums */
"ALLFORUMS":"Todos los foros",
"PUBLICFORUMS":"Foros públicos",
"MYFORUMS":"Mis foros",
"EVERYTHINGFORUMS":"Todo de los foros",
"FORUMSONLY":"Foros",
"TOPICSFORUMS":"Temas del foro",
"FORUMCATEGORIES": "Categorías de foro",
"FILESFORUMS":"Archivos adjuntos de los foros",
"ALLTYPESFORUMS":"Todos los tipos de foros",
"COMMUNITYFORUMS":"Foros de las comunidades",
"STANDALONEFORUMS":"Foros autónomos",
/* Blogs */
"ALLBLOGS":"Todos los blogs",
"PUBLICBLOGS":"Blogs públicos",
"MYBLOGS":"Mis blogs",
"EVERYTHINGBLOGS":"Todo de los blogs",
"BLOGSONLY":"Blogs",
"ENTRIESBLOGS":"Entradas de blog",
"FILESBLOGS":"Archivos adjuntos de los blogs",
"EVERYTHINGIDEATIONBLOGS":"Todo de los blogs de ideación",
"BLOGSIDEATIONBLOGS":"Blogs de ideación",
"BLOGSIDEAS":"Ideas",
"ALLTYPESBLOGS":"Todos los tipos de blogs",
"COMMUNITYBLOGS":"Blogs de las comunidades",
"COMMUNITYIDEATIONBLOGS":"Blogs de ideación desde Comunidades",
"STANDALONEBLOGS":"Blogs autónomos",
/* Bookmarks */
"ALLBOOKMARKS":"Todos los marcadores",
"PUBLICBOOKMARKS":"Marcadores públicos",
"MYBOOKMARKS":"Mis marcadores",
"ALLTYPESBOOKMARKS":"Todos los tipos de marcadores",
"COMMUNITYBOOKMARKS":"Marcadores de las comunidades",
"STANDALONEBOOKMARKS":"Marcadores autónomos",
/* Files */
"ALLFILES":"Todos los archivos",
"PUBLICFILES":"Archivos públicos",
"MYFILES":"Mis archivos",
"ALLTYPESFILES":"Todos los tipos de archivos",
"COMMUNITYFILES":"Archivos de las comunidades",
"STANDALONEFILES":"Archivos autónomos",
"NUMDOWNLOADS":"{0} Descargas",
/* Wikis */
"ALLWIKIS":"Todas las wikis",
"PUBLICWIKIS":"Wikis públicas",
"MYWIKIS":"Mis wikis",
"EVERYTHINGWIKIS":"Todo de las wikis",
"WIKISONLY":"Wikis",
"PAGESWIKIS":"Páginas de wiki",
"FILESWIKIS":"Archivos adjuntos de las wikis",
"ALLTYPESWIKIS":"Todos los tipos de wikis",
"COMMUNITYWIKIS":"Wikis de las comunidades",
"STANDALONEWIKIS":"Wikis autónomas",
/* Status Updates */
"ALLSTATUSUPDATES":"Todas las actualizaciones de estado",
"PUBLICSTATUSUPDATES":"Actualizaciones de estado públicas",
"MYSTATUSUPDATES":"Mis actualizaciones de estado",
"ALLTYPESSTATUSUPDATES":"Todos los tipos de actualizaciones de estado",
"COMMUNITYSTATUSUPDATES":"Actualizaciones de estado de Comunidades",
"STANDALONESTATUSUPDATES":"Actualizaciones de estado de Perfiles",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Este URL ha sido incluido como marcador por un número de usuarios",
"BOOKMARKEDCOMMUNITY":"Esta comunidad ha sido incluida como marcador por un número de usuarios",
"BOOKMARKEDPROFILE":"Este perfil ha sido incluido como marcador por un número de usuarios",
"BOOKMARKEDBLOG":"Este blog ha sido incluido como marcador por un número de usuarios",
"COMMUNITYBLOG":"Es un blog de una comunidad",
"BOOKMARKEDACTIVITY":"Esta actividad ha sido marcada por varios usuarios",
"COMMUNITYACTIVITY":"Es una actividad de una comunidad",
"BOOKMARKEDFILE":"Este archivo ha sido incluido como marcador por un número de usuarios",
"COMMUNITYFILE":"Es un archivo de una comunidad",
"BOOKMARKED":"Esta Wiki ha sido incluida como marcador por un número de usuarios",
"COMMUNITYWIKI":"Es una wiki de una comunidad",
"BOOKMARKEDFORUM":"Este foro ha sido incluido como marcador por un número de usuarios",
"COMMUNITYFORUM":"Es un foro de una comunidad",
"ALLTAGANDTTILE":"Para ver todos los títulos y etiquetas de este URL, pulse este botón",
"TAGS_ARE_FROM":"Este resultado de búsqueda puede incluir etiquetas de:",
"BOOKMARKS_TITLE":"Marcadores",
"COMMUNITIES_TITLE":"Comunidades",
"ACTIVITIES_TITLE":"Actividades",
"HELP":"Ayuda",
"MORESTATUSUPDATES":"Ver más coincidencias de actualizaciones de estado",
"TITLE_PREFIX":"título:",
"LATEST_MESSAGE":"Último mensaje",
"LATEST_STATUS_UPDATE":"Actualización de estado más reciente",
"LATEST_COMMUNITY_STATUS_UPDATE":"Actualización de estado más reciente de la comunidad",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Actualización de estado más reciente de Comunidades",
"SEARCH_RESULTS":"Todos los resultados de la búsqueda de contenido",
"ACTIVITIES_SEARCH_RESULTS":"Resultados de búsqueda de actividades",
"BLOGS_SEARCH_RESULTS":"Resultados de búsqueda de blogs",
"BOOKMARKS_SEARCH_RESULTS":"Resultados de búsqueda de marcadores",
"COMMUNITIES_SEARCH_RESULTS":"Resultados de búsqueda de comunidades",
"FILES_SEARCH_RESULTS":"Resultados de búsqueda de archivos",
"FORUMS_SEARCH_RESULTS":"Resultados de búsqueda de foros",
"PROFILES_SEARCH_RESULTS":"Resultados de búsqueda de perfiles",
"DIRECTORY_SEARCH_RESULTS":"Resultados de la búsqueda de directorio ${orgName}",
"WIKIS_SEARCH_RESULTS":"Resultados de búsqueda de wikis",
"STATUS_UPDATES_SEARCH_RESULTS":"Resultados de búsqueda de actualizaciones de estado",
"VIEW_ALL":"{span}Ver todos{/span} ({0})",
"MATCHING_ONE_OF":"Coincide con uno de:",
"MATCHING_ALL_OF":"Coincide con todos los:",
"MATCHING":"Que coincida con:",
"MATCHING_DOC_TYPE":"Tipo de documento coincidente:",
"BOOKMARK_HELP":"Ayuda del marcador",
"CLOSE_BOOKMARK_HELP":"Cerrar ayuda del marcador",
"DOCUMENT_TYPE_PREFIX":"Tipo de documento:",
"FILE_PREVIEW_ONLY":"(Sólo modalidad de vista previa)"
})

