/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"NODE": "Información del nodo: ",
	"INSTALLED": "Comprobando los servicios instalados",
	"RESUMETOKENS": "Comprobando las señales reanudadas",
	"SEEDLISTS": "Comprobando que las listas de semillas estén disponibles",
	"CALENDARS": "Comprobando que los calendarios de planificación se hayan configurado correctamente",
	"VARIABLES": "Comprobando que las variables de WebSphere se hayan establecido",
	"TASKS": "Buscando tareas de indexación habilitadas",
	"INDEXFILES": "Buscando los archivos necesarios en la carpeta de índice",
	"LOGS": "Revisando los registro en busca de errores",
	"CONFIGFILES": "Revisando los archivos de configuración",
	"DICTIONARIES": "Comprobando el número de diccionarios que se han habilitado",
	"SYNC": "Comprobando el estado de los nodos",
	"DBRECORDS": "Comprobando los registros de base de datos",
	"INSTALLEDMSG": "Se ha instalado el siguiente servicio: ",
	"RESUMETOKENSMSG": "La señal reanudada de: ",
	"SEEDLISTSMSG": "No se ha podido obtener la lista de semillas de: ",
	"CALENDARSMSG": "Se ha pasado la comprobación del calendario de planificación: ",
	"VARIABLESMSG": "Variable: ",
	"TASKSMSG": "Se ha habilitado la siguiente tarea: ",
	"INDEXFILESMSG" : "Los siguientes archivos están en la carpeta del índice de búsqueda: ",
	"LOGSMSG" : "Revise los siguientes mensajes de error: ",
	"CONFIGFILESMSG" : "Se han encontrado los siguientes archivos de configuración: ",
	"DICTIONARIESMSG" : "El número de diccionarios habilitados es: ",
	"INSYNC": "Todos los nodos están sincronizados",
	"OUTOFSYNC": "El número de nodos no sincronizados es: ",
	"NOTBLOCKED": "No hay ningún nodo bloqueado",
	"BLOCKED": "El número de nodos bloqueados es: ",
	"INDATE": "Todos los nodos están sincronizados",
	"OUTOFDATE": "El número de nodos caducados es: ",
	"NUMOFDOCS": "El número de documentos de la base de datos es ",
	"FILESTOCONVERT": "El número de documentos de archivo a convertir es ",
	"CONVERTEDFILES": "El número de archivos convertidos es ",
	"TOTALFILES": "El número total de archivos en la base de datos ",
	"ERROR":"Error",
	"ERROR_PREFIX":"Error:",
	"INFO":"Información",
	"INFO_PREFIX":"Información:",
	"WARNING":"Aviso",
	"WARNING_PREFIX":"Aviso:",
	"LOADING_MESSAGE": "Cargando",
	"SERVER_STATUS": "Estado del servidor",
	"INITIAL_INDEXING_EXCEPTIONS": "Excepciones de indexación inicial",
	"SYS_OUT_EXCEPTIONS": "Excepciones de registro de SystemOut",
	"SEEDLIST_VALIDATE": "Validación de listas de origen",
	"ERRORS_DURING_INITIAL_INDEXING":"Se han producido las excepciones siguientes al crear el índice inicial",
	"CRAWL_FAILED": "No se han podido rastrear todos los datos del servicio siguiente: ",
	"EXCEPTION_ENCOUNTERED": "El rastreo ha sido erróneo con el mensaje siguiente: ",
	"SAND_VALIDATE": "Validación SAND",
	"CHECK_FOR_SAND_FILES":"Buscando archivos SAND",
	"IS_FILE_AVAILABLE":"Comprobando que se ha creado el archivo: ",
	"ERRORS_DURING_INITIAL_INDEXING":"Se han producido las excepciones siguientes al crear el índice inicial",
	"CRAWL_FAILED":"No se han podido rastrear todos los datos del servicio siguiente: ",
	"EXCEPTION_ENCOUNTERED":"El rastreo ha sido erróneo con el mensaje siguiente: "
})

