/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Angiv en titel.",
	nourl: "Angiv en URL.",
	fileSchema: "Hvis du vil tilføje et link til en ekstern eller lokal fil, skal det overholde et af følgende formater: file://ekstern_sti eller file:///lokal_sti.",
	invalidUrl: "Dette er ikke en gyldig fællesskabs-URL.",
	invalidTagChar: "Den emneliste, du har angivet, indeholder det ugyldige tegn '&'.  Fjern dette tegn fra emnelisten.",
	txtHelp: "Hjælp",
	txtHelpTags: "Hjælp til emneord",
	txtHelpTagsClose: "Luk hjælpen til Emneord",
	tagsall: "Alle",
	tagsyours: "Dine",
	tagsrecent: "Seneste: ",
	tagspopular: "Populære: ",
	tagsrecommended: "Anbefalede: ",
	nothingselected: "Vælg et fællesskab.",
	nothingselected_activity: "Vælg en aktivitet.",
	nothingselected_blogs: "Vælg en blog.",
	nothingselected_all: "Du har ikke valgt en service eller en indgang. Bogmærket bliver ikke gemt.",
	nothingFeedselected: "Du har ikke valgt en service eller en indgang. Feeden bliver ikke gemt.",
	alertDialogTitle: "Meddelelse",
	alertDialogOK: "OK",
	expand: "Klik for at udvide sektionen",
	collapse: "Klik for at skjule sektionen",
	discussThis: "Diskutér dette",
	by: "af:",
	posted: "Opslået:",
	attachments: "Vedhæftninger",
	communityForum: "Fællesskabsforum",
	notCommunityPage: "Den aktuelle webside er ikke en gyldig fællesskabswebside. Du kan indtaste fællesskabstitel, link og beskrivelse for at oprette et relateret fællesskab.",
	privateCommunityNotice: "Dette fællesskab er begrænset. Det er kun synligt for medlemmer af fællesskabet.",
	forumNameHint : "Skriv et forumnavn.",
	formDescriptionHint:"Beskriv, hvorfor dette relaterede fællesskab kan være af interesse for dit fællesskab.",
	information : "Information",
	error : "Fejl",
	success : "Udført",
	warning : "Advarsel",
	informationColon : "Information:",
	successColon : "Udført:",
	warningColon : "Advarsel:",
	errorColon : "Fejl:",
	feedAlreadyExist : "Feed findes allerede i fællesskabet.",
	bookmarkAlreadyExist : "Bogmærke findes allerede i fællesskabet.",
	mentionAuthWarning:"Følgende personer kan ikke se ikke beskeden, fordi de ikke er medlemmer af fællesskabet:",
	mentionAuthForumWarning:"Følgende personer kan ikke se beskeden, fordi de ikke har adgang til dette forum:",
	exceedDescLength: "Den angivne beskrivelse er for lang.",
	communities_checked:"${0} fællesskab(er) valgt",
	activities_checked:"${0} aktivitet(er) valgt",
	blogs_checked:"${0} blog(ge) valgt"
})
