/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"필터 기준:",
		"SHOW":"표시:",
		"ACL_FILTER_LABEL":"표시 설정별 필터",
		"PARENT_FILTER_LABEL":"컨테이너별 필터",
		"TYPE_FILTER_LABEL":"유형별 필터",
		"PAGING_TOP":"기본 페이징",
		"PAGING_BOTTOM":"보조 페이징",
		"PREVIOUS":"이전",
		"NEXT":"다음",
		"PAGE":"{0}/{1} 페이지",
		"PAGE_COLON":"페이지:",
		"RESULTS":"{2}의 {span}{0}-{1}{/span}",
		"ITEMS":"{0}개의 항목",
		/* Application names */
		"ACTIVITIES":"활동",
		"BLOGS":"블로그",
		"CALENDAR":"일정관리",
		"COMMUNITIES":"커뮤니티",
		"BOOKMARKS":"책갈피",
		"DOGEAR":"책갈피",
		"EVENTS":"이벤트",
		"FILES":"파일",
		"FORUMS":"포럼",
		"PROFILES":"프로파일",
		"WIKI":"위키",
		"WIKIS":"위키",
		"FEEDS":"피드",
		"STATUS_UPDATES":"상태 업데이트",
		"ONECOMMENT":"1개의 댓글",
		"COMMENTS":"{0}개의 댓글",
		"ONEPERSON":"1명의 사용자",
		"PEOPLE":"{0}명의 사용자",
		"TAGS":"태그:",
		"TAGSMORE":"및 {0} 이상",
		"NORESULTSMESSAGE":"해당 검색에 대한 결과 없음",
		"JAN":"1월",
		"FEB":"2월",
		"MAR":"3월",
		"APR":"4월",
		"MAY":"5월",
		"JUN":"6월",
		"JUL":"7월",
		"AUG":"8월",
		"SEP":"9월",
		"OCT":"10월",
		"NOV":"11월",
		"DEC":"12월",
		"NO_CONTACT":"서버에 접속할 수 없어 검색이 수행되지 않음",
		"SERVER_ERROR":"서버 오류로 인해 검색이 수행되지 않음",
		"SORT_BY":"정렬 기준:",
		"SORT_RELEVANCE":"관련성",
		"SORT_DATE":"날짜",
		"SORT_LAST_UPDATED":"마지막 업데이트 날짜",
		"SORT_DUE_DATE":"만기 날짜",
		"SORT_VISITS":"방문",
		"SORT_COMMENTS":"댓글",
		"SORT_RECOMMENDATION":"좋아요",
		"SORT_POPULARITY":"인기도",
		"SORT_FIRSTNAME":"이름",
		"SORT_LASTNAME":"성",
		"SORT_DOWNLOADS":"다운로드",
		"SORT_TYPE":"유형",
		"SORT_SIZE":"크기",
		"SORT_TITLE":"제목",
		"PRIVATE":"개인용",
		"MODERATED":"운영자 중심",
		"COMMUNITY_ACTIVITY":"커뮤니티 활동",
		"COMMUNITY_BLOG":"커뮤니티 블로그",
		"COMMUNITY_FILE":"커뮤니티 파일",
		"COMMUNITY_FORUM":"커뮤니티 포럼",
		"COMMUNITY_WIKI":"커뮤니티 위키",
		"COMMUNITY_FEED":"커뮤니티 피드",
		"COMMUNITY_BOOKMARK":"커뮤니티 책갈피",
		"NO_TAG":"아직 태그 없음",
		"NO_DATE":"아직 날짜 없음",
		"NO_PEOPLE":"아직 사용자 없음",
		"REMOVE_FILTER_LABEL":"제거하려면 클릭",
		"REMOVE_FILTER_TITLE":"제거",
		"REMOVE_FILTER_TOOLTIP":"이 필터를 제거합니다.",
		"COMMENT_ON":"다음에 대한 댓글:",
		"EXPAND_COLLAPSE":"펼치거나 접으려면 클릭",
		"EXPAND":"펼치기",
		"COLLAPSE":"접기",
		"EXPAND_MONTHS_FILTER":"{0}년의 월별 필터 펼치기 ",
		"SORT_RELEVANCE_LABEL":"관련성을 기준으로 정렬하려면 클릭하십시오.",
		"SORT_DATE_LABEL":"날짜를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_UPDATED_LABEL":"마지막 업데이트 날짜를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_DUE_LABEL":"만기 날짜 기준으로 정렬하려면 클릭하십시오.",
		"SORT_VISITS_LABEL":"방문 수를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_COMMENTS_LABEL":"댓글 수를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_RECOMMENDATIONS_LABEL":"좋아요 수를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_POPULARITY_LABEL":"인기도를 기준으로 정렬하려면 클릭하십시오.",
		"SORT_FIRST_NAME_LABEL":"이름을 기준으로 정렬하려면 클릭하십시오.",
		"SORT_LAST_NAME_LABEL":"성을 기준으로 정렬하려면 클릭하십시오.",
		"RATING":"좋아요",
		"GRADUATED":"승격됨",
		"ONEVOTE":"1표",
		"VOTES":"{0}표",
		"BOOKMARK_THIS_RESULT":"책갈피 지정",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0}(비활성)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"책갈피가 지정된 {0}명의 사용자",
		/* eg from an Activity */
		"FROMANACTIVITY":"활동에서",
		"FROMABLOG":"블로그에서",
		"FROMANIDEATIONBLOG":"아이디어 블로그에서",
		"FROMANEVENT":"이벤트에서",
		"FROMAFORUM":"포럼에서",
		"FROMAWIKI":"위키에서",
		"FROMACOMMUNITY":"커뮤니티에서",
		"FROMXCOMMUNITIES":"{0} 커뮤니티에서",
		/* For search results parentage */
		"ACTIVITY_ALONE":"활동",
		"BLOG_ALONE":"블로그",
		"IDEATIONBLOG_ALONE":"아이디어 블로그",
		"ENTRY_ALONE":"항목",
		"EVENT_ALONE":"이벤트",
		"FORUM_ALONE":"포럼",
		"WIKI_ALONE":"위키",
		"COMMUNITY_ALONE":"커뮤니티",
		"XCOMMUNITIES_ALONE":"{0} 커뮤니티",
		"SHAREDCOMMUNITIES":"이들 커뮤니티와 공유",
		"INACOMMUNITY":"커뮤니티에",
		"LASTUPDATED":"검색 색인 마지막 업데이트 날짜:",
		"NODESCRIPTION":"이 결과에 대한 설명 또는 요약이 없습니다.",
		"ATTACHMENT":"첨부:",
		"ACTIVITY":"활동:",
		"ACTIVITYBOOKMARK":"활동 책갈피:",
		"ACTIVITYCOMMENT":"활동 댓글:",
		"ACTIVITYENTRY":"활동 항목:",
		"ACTIVITYSECTION":"활동 섹션:",
		"ACTIVITYTODO":"활동 작업관리:",
		"BLOG":"블로그: ",
		"BLOGENTRY":"블로그 항목:",
		"BLOGCOMMENT":"블로그 댓글:",
		"BOOKMARK":"책갈피:",
		"CALENDAREVENT":"이벤트:",
		"CATEGORY":"카테고리:",
		"COMMENT":"댓글:",
		"COMMUNITY":"커뮤니티: ",
		"ENTRY":"항목:",
		"EVENTDATEON":"이벤트 날짜: {0}",
		"EVENTISALLDAY":"종일 이벤트",
		"EVENTREPEATS":"반복",
		"FEED":"피드:",
		"FILE":"파일:",
		"FORUM":"포럼:",
		"FORUMCATEGORY":"포럼 카테고리:",
		"FORUMTOPIC":"포럼 주제:",
		"IDEA":"아이디어:",
		"IDEACOMMENT":"아이디어 댓글:",
		"IDEATIONBLOG":"아이디어 블로그:",
		"PAGE":"페이지:",
		"PROFILE":"프로파일:",
		"SECTION":"섹션:",
		"STATUSUPDATE":"상태 업데이트",
		"STATUSUPDATE_PREFIX":"상태 업데이트:",
		"TOPIC":"주제:",
		"TOPIC_WITH_ATTACHMENT":"주제",
		"WIKITYPE":"위키:",
		"WIKIPAGE":"위키 페이지:",
		"WIKIFILE":"위키 첨부:",
		"SEARCH":"검색:",
		"TODO":"작업관리:",
		"ALLRESULTS":"모든 결과",
		"PUBLICCONTENT":"공용 컨텐츠",
		"MYCONTENT":"내 컨텐츠",
		"RESULTNOTFOUND":"찾는 대상을 찾지 못했습니까?",
		"TEMPDIFFICULTIES":"참고: 임시 색인 작성 문제로 인해 최근 {1}일에 변경된 {0}이(가) 검색에 포함되지 않았습니다.",
		"TRYLATER":"나중에 다시 시도하십시오.",
		"MULTIPLETEMPDIFFICULTIES":"참고: 임시 색인 작성 문제로 인해 최근 변경된 {0}이(가) 검색에 포함되지 않았습니다.",
		"YOUAREAUTHOR":"작성자입니다.",
		"YOUARECONTRIBUTOR":"기고자입니다.",
		"YOUAREOWNER":"소유자입니다. ",
		"YOUAREMEMBER":"회원입니다.",
		/* Profiles */
		"MYNETWORK":"내 네트워크",
		"ALLPEOPLE":"모든 사용자",
		"EXCLUDEINACTIVE":"비활성 사용자 제외",
		"PHONE":"전화:",
		"EMAIL":"이메일:",
		/* Communities */
		"ALLCOMMUNITIES":"모든 커뮤니티",
		"PUBLICCOMMUNITIES":"공용 커뮤니티",
		"MYCOMMUNITIES":"내 커뮤니티",
		"EVERYTHINGCOMMUNITIES":"커뮤니티에서 모두",
		"COMMUNITIESONLY":"커뮤니티",
		"COMMUNITIESCONTENT":"커뮤니티에서 컨텐츠",
		/* Activities */
		"ALLACTIVITIES":"모든 활동",
		"PUBLICACTIVITIES":"공용 활동",
		"MYACTIVITIES":"내 활동",
		"EVERYTHINGACTIVITIES":"활동에서 모두",
		"ACTIVITIESONLY":"활동",
		"SECTIONSACTIVITIES": "활동의 섹션",
		"ENTRIESACTIVITIES":"활동에서 항목",
		"TODOSACTIVITIES":"활동의 작업관리",
		"BOOKMARKSACTIVITIES":"활동의 책갈피",
		"FILESACTIVITIES":"활동에서 첨부",
		"ALLTYPESACTIVITIES":"모든 유형의 활동",
		"COMMUNITYACTIVITIES":"커뮤니티에서 활동",
		"STANDALONEACTIVITIES":"독립형 활동",
		/* Forums */
		"ALLFORUMS":"모든 포럼",
		"PUBLICFORUMS":"공용 포럼",
		"MYFORUMS":"내 포럼",
		"EVERYTHINGFORUMS":"포럼에서 모두",
		"FORUMSONLY":"포럼",
		"TOPICSFORUMS":"포럼 주제",
		"FORUMCATEGORIES": "포럼 카테고리",
		"FILESFORUMS":"포럼에서 첨부",
		"ALLTYPESFORUMS":"모든 유형의 포럼",
		"COMMUNITYFORUMS":"커뮤니티에서 포럼",
		"STANDALONEFORUMS":"독립형 포럼",
		/* Blogs */
		"ALLBLOGS":"모든 블로그",
		"PUBLICBLOGS":"공용 블로그",
		"MYBLOGS":"내 블로그",
		"EVERYTHINGBLOGS":"블로그에서 모두",
		"BLOGSONLY":"블로그",
		"ENTRIESBLOGS":"블로그 항목",
		"FILESBLOGS":"블로그에서 첨부",
		"EVERYTHINGIDEATIONBLOGS":"아이디어 블로그에서 모두",
		"BLOGSIDEATIONBLOGS":"아이디어 블로그",
		"BLOGSIDEAS":"아이디어",
		"ALLTYPESBLOGS":"모든 유형의 블로그",
		"COMMUNITYBLOGS":"커뮤니티에서 블로그",
		"COMMUNITYIDEATIONBLOGS":"커뮤니티에서 아이디어 블로그",
		"STANDALONEBLOGS":"독립형 블로그",
		/* Bookmarks */
		"ALLBOOKMARKS":"모든 책갈피",
		"PUBLICBOOKMARKS":"공용 책갈피",
		"MYBOOKMARKS":"내 책갈피",
		"ALLTYPESBOOKMARKS":"모든 유형의 책갈피",
		"COMMUNITYBOOKMARKS":"커뮤니티에서 책갈피",
		"STANDALONEBOOKMARKS":"독립형 책갈피",
		/* Files */
		"ALLFILES":"모든 파일",
		"PUBLICFILES":"공용 파일",
		"MYFILES":"내 파일",
		"ALLTYPESFILES":"모든 유형의 파일",
		"COMMUNITYFILES":"커뮤니티에서 파일",
		"STANDALONEFILES":"독립형 파일",
		"NUMDOWNLOADS":"{0}회 다운로드",
		/* Wikis */
		"ALLWIKIS":"모든 위키",
		"PUBLICWIKIS":"공용 위키",
		"MYWIKIS":"내 위키",
		"EVERYTHINGWIKIS":"위키에서 모두",
		"WIKISONLY":"위키",
		"PAGESWIKIS":"위키 페이지",
		"FILESWIKIS":"위키에서 첨부",
		"ALLTYPESWIKIS":"모든 유형의 위키",
		"COMMUNITYWIKIS":"커뮤니티에서 위키",
		"STANDALONEWIKIS":"독립형 위키",
		/* Status Updates */
		"ALLSTATUSUPDATES":"모든 상태 업데이트",
		"PUBLICSTATUSUPDATES":"공용 상태 업데이트",
		"MYSTATUSUPDATES":"내 상태 업데이트",
		"ALLTYPESSTATUSUPDATES":"모든 유형의 상태 업데이트",
		"COMMUNITYSTATUSUPDATES":"커뮤니티의 상태 업데이트",
		"STANDALONESTATUSUPDATES":"프로파일의 상태 업데이트",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"여러 사용자가 이 URL에 책갈피를 지정했습니다.",
		"BOOKMARKEDCOMMUNITY":"여러 사용자가 이 커뮤니티에 책갈피를 지정했습니다.",
		"BOOKMARKEDPROFILE":"여러 사용자가 이 프로파일에 책갈피를 지정했습니다.",
		"BOOKMARKEDBLOG":"여러 사용자가 이 블로그에 책갈피를 지정했습니다.",
		"COMMUNITYBLOG":"커뮤니티 내의 블로그입니다.",
		"BOOKMARKEDACTIVITY":"여러 사용자가 이 활동에 책갈피를 지정했습니다.",
		"COMMUNITYACTIVITY":"커뮤니티 내의 활동입니다.",
		"BOOKMARKEDFILE":"여러 사용자가 이 파일에 책갈피를 지정했습니다.",
		"COMMUNITYFILE":"커뮤니티 내의 파일입니다.",
		"BOOKMARKED":"여러 사용자가 이 위키에 책갈피를 지정했습니다.",
		"COMMUNITYWIKI":"커뮤니티 내의 위키입니다.",
		"BOOKMARKEDFORUM":"여러 사용자가 이 포럼에 책갈피를 지정했습니다.",
		"COMMUNITYFORUM":"커뮤니티 내의 포럼입니다.",
		"ALLTAGANDTTILE":"이 URL의 모든 제목 및 태그를 표시하려면 이 단추를 클릭하십시오.",
		"TAGS_ARE_FROM":"이 검색 결과에 포함되는 태그의 원래 위치:",
		"BOOKMARKS_TITLE":"책갈피",
		"COMMUNITIES_TITLE":"커뮤니티",
		"ACTIVITIES_TITLE":"활동",
		"HELP":"도움말",
		"MORESTATUSUPDATES":"추가 상태 업데이트 일치 보기",
		"TITLE_PREFIX":"제목:",
		"LATEST_MESSAGE":"최신 메시지",
		"LATEST_STATUS_UPDATE":"최신 상태 업데이트",
		"LATEST_COMMUNITY_STATUS_UPDATE":"최신 커뮤니티 상태 업데이트",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"최신 커뮤니티 상태 업데이트",
		"SEARCH_RESULTS":"모든 컨텐츠 검색 결과",
		"ACTIVITIES_SEARCH_RESULTS":"활동 검색 결과",
		"BLOGS_SEARCH_RESULTS":"블로그 검색 결과",
		"BOOKMARKS_SEARCH_RESULTS":"책갈피 검색 결과",
		"COMMUNITIES_SEARCH_RESULTS":"커뮤니티 검색 결과",
		"FILES_SEARCH_RESULTS":"파일 검색 결과",
		"FORUMS_SEARCH_RESULTS":"포럼 검색 결과",
		"PROFILES_SEARCH_RESULTS":"프로파일 검색 결과",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} 디렉토리 검색 결과",
		"WIKIS_SEARCH_RESULTS":"위키 검색 결과",
		"STATUS_UPDATES_SEARCH_RESULTS":"상태 업데이트 검색 결과",
		"VIEW_ALL":"{span}모두 보기{/span}({0})",
		"MATCHING_ONE_OF":"다음 중 하나 일치:",
		"MATCHING_ALL_OF":"다음 항목과 모두 일치:",
		"MATCHING":"일치:",
		"MATCHING_DOC_TYPE":"일치하는 문서 유형:",
		"BOOKMARK_HELP":"책갈피 도움말",
		"CLOSE_BOOKMARK_HELP":"책갈피 도움말 닫기",
		"DOCUMENT_TYPE_PREFIX":"문서 유형:",
		"LAST_PAGE_MESSAGE": "검색 결과가 너무 많습니다. 검색 용어를 추가하여 검색 범위를 좁히십시오.",
		"LAST_PAGE_SUBMESSAGE": "첫 번째 {resultNumber} 관련 결과를 가져오는 중입니다."
});

