/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Informazioni per il nodo: ",
		"INSTALLED": "Controllo dei servizi installati",
		"RESUMETOKENS": "Controllo dei token di ripristino",
		"SEEDLISTS": "Controllo della disponibilità degli elenchi seed",
		"CALENDARS": "Controllo della corretta configurazione dei calendari di pianificazione",
		"VARIABLES": "Controllo dell'impostazione delle variabili WebSphere",
		"TASKS": "Controllo per le attività di indicizzazione abilitate",
		"INDEXFILES": "Controllo nella cartella dell'indice della presenza dei file richiesti",
		"LOGS": "Revisione dei log di errori",
		"CONFIGFILES": "Revisione dei file di configurazione",
		"DICTIONARIES": "Controllo dell'abilitazione del numero di dizionari",
		"SYNC": "Controllo dello stato dei nodi",
		"DBRECORDS": "Controllo dei record del database",
		"INSTALLEDMSG": "Il seguente servizio è installato: ",
		"RESUMETOKENSMSG": "Il token di ripristino per: ",
		"SEEDLISTSMSG": "L'elenco seed non è stato ottenuto per: ",
		"CALENDARSMSG": "Controllo del calendario di pianificazione riuscito: ",
		"VARIABLESMSG": "Variabile: ",
		"TASKSMSG": "La seguente attività è abilitata: ",
		"INDEXFILESMSG" : "I seguenti file sono presenti nella cartella dell'indice di ricerca: ",
		"LOGSMSG" : "Rivedere i seguenti messaggi di errore: ",
		"CONFIGFILESMSG" : "Sono stati trovati i seguenti file di configurazione: ",
		"DICTIONARIESMSG" : "Il numero di dizionari abilitati è: ",
		"INSYNC": "Tutti i nodi sono sincronizzati",
		"OUTOFSYNC": "Il numero di nodi non sincronizzati è: ",
		"NOTBLOCKED": "Nessun nodo bloccato",
		"BLOCKED": "Il numero di nodi bloccati è: ",
		"INDATE": "Tutti i nodi sono aggiornati",
		"OUTOFDATE": "Il numero di nodi non aggiornati è: ",
		"NUMOFDOCS": "Il numero di documenti nel database è ",
		"FILESTOCONVERT": "Il numero di documenti file da convertire è ",
		"CONVERTEDFILES": "Il numero di file convertiti è ",
		"TOTALFILES": "Il numero totale di file nel database ",
		"ERROR":"Errore",
		"ERROR_PREFIX":"Errore:",
		"INFO":"Informazioni",
		"INFO_PREFIX":"Informazioni:",
		"WARNING":"Avviso",
		"WARNING_PREFIX":"Avviso:",
		"LOADING_MESSAGE": "Caricamento",
		"SERVER_STATUS": "Stato del server",
		"INITIAL_INDEXING_EXCEPTIONS": "Eccezioni di indicizzazione iniziale",
		"SYS_OUT_EXCEPTIONS": "Eccezioni log SystemOut",
		"SEEDLIST_VALIDATE": "Convalida elenchi seed",
		"ERRORS_DURING_INITIAL_INDEXING":"Si sono verificate le seguenti eccezioni durante la creazione di un indice iniziale",
		"CRAWL_FAILED": "Tutti i dati per il seguente servizio non sono stati sottoposti a crawling: ",
		"EXCEPTION_ENCOUNTERED": "Il crawling non è riuscito ed è stato restituito il seguente messaggio: ",
		"SAND_VALIDATE": "Convalida SAND",
		"CHECK_FOR_SAND_FILES":"Controllo per i file SAND",
		"IS_FILE_AVAILABLE":"Verifica che il file è stato creato: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Si sono verificate le seguenti eccezioni durante la creazione di un indice iniziale",
		"CRAWL_FAILED":"Tutti i dati per il seguente servizio non sono stati sottoposti a crawling: ",
		"EXCEPTION_ENCOUNTERED":"Il crawling non è riuscito ed è stato restituito il seguente messaggio: "
});

