/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Süzme temeli:",
"SHOW":"Göster:",
"ACL_FILTER_LABEL":"Görünürlüğe göre süz",
"PARENT_FILTER_LABEL":"Kapsayıcıya göre süz",
"TYPE_FILTER_LABEL":"Türe göre süz",
"PAGING_TOP":"Birincil sayfalama",
"PAGING_BOTTOM":"İkincil sayfalama",
"PREVIOUS":"Önceki",
"NEXT":"Sonraki",
"PAGE":"Sayfa {0} / {1}",
"PAGE_COLON":"Sayfa:",
"RESULTS":"{span}{0} - {1}{/span} / {2}",
"ITEMS":"{0} öğe",
/* Application names */
"ACTIVITIES":"Etkinlikler",
"BLOGS":"Web Günlükleri",
"CALENDAR":"Takvim",
"COMMUNITIES":"Topluluklar",
"BOOKMARKS":"Yer İşaretleri",
"DOGEAR":"Yer İşaretleri",
"EVENTS":"Takvim Etkinlikleri",
"FILES":"Dosyalar",
"FORUMS":"Forumlar",
"PROFILES":"Profiller",
"WIKI":"Vikiler",
"WIKIS":"Vikiler",
"FEEDS":"Özet Akışları",
"STATUS_UPDATES":"Durum Güncelleştirmeleri",
"ONECOMMENT":"1 yorum",
"COMMENTS":"{0} yorum",
"ONEPERSON":"1 Kişi",
"PEOPLE":"{0} Kişi",
"TAGS":"Etiketler:",
"TAGSMORE":"ve diğer {0}",
"NORESULTSMESSAGE":"Bu arama için sonuç bulunamadı",
"JAN":"Ocak",
"FEB":"Şubat",
"MAR":"Mart",
"APR":"Nisan",
"MAY":"Mayıs",
"JUN":"Haziran",
"JUL":"Temmuz",
"AUG":"Ağustos",
"SEP":"Eylül",
"OCT":"Ekim",
"NOV":"Kasım",
"DEC":"Aralık",
"NO_CONTACT":"Sunucuyla iletişim kurulamadığı için arama gerçekleştirilmedi",
"SERVER_ERROR":"Bir sunucu hatası nedeniyle arama gerçekleştirilmedi",
"SORT_BY":"Sıralama temeli:",
"SORT_RELEVANCE":"İlgi",
"SORT_DATE":"Tarih",
"SORT_LAST_UPDATED":"Son Güncelleştirme",
"SORT_DUE_DATE":"Son Tarih",
"SORT_VISITS":"Ziyaretler",
"SORT_COMMENTS":"Yorumlar",
"SORT_RECOMMENDATION":"Beğeniler",
"SORT_POPULARITY":"Sık kullanım",
"SORT_FIRSTNAME":"Ad",
"SORT_LASTNAME":"Soyadı",
"SORT_DOWNLOADS":"Karşıdan Yüklemeler",
"SORT_TYPE":"Tür",
"SORT_SIZE":"Boyut",
"SORT_TITLE":"Başlık",
"PRIVATE":"Özel",
"MODERATED":"Denetlenen",
"COMMUNITY_ACTIVITY":"Topluluk Etkinliği",
"COMMUNITY_BLOG":"Topluluk Web Günlüğü",
"COMMUNITY_FILE":"Topluluk Dosyası",
"COMMUNITY_FORUM":"Topluluk Forumu",
"COMMUNITY_WIKI":"Topluluk Vikisi",
"COMMUNITY_FEED":"Topluluk Özet Akışı",
"COMMUNITY_BOOKMARK":"Topluluk Yer İşareti",
"NO_TAG":"Henüz herhangi bir etiket yok",
"NO_DATE":"Henüz tarih yok",
"NO_PEOPLE":"Henüz kişi yok",
"REMOVE_FILTER_LABEL":"Kaldırmak için tıklatın",
"REMOVE_FILTER_TITLE":"Kaldır",
"REMOVE_FILTER_TOOLTIP":"Bu süzgeci kaldır",
"COMMENT_ON":"Yorum yap:",
"EXPAND_COLLAPSE":"Genişletmek / daraltmak için tıklatın",
"EXPAND":"Genişlet",
"COLLAPSE":"Daralt",
"EXPAND_MONTHS_FILTER":"{0} yılının aylar süzgecini genişletin",
"SORT_RELEVANCE_LABEL":"İlgiye göre sıralamak için",
"SORT_DATE_LABEL":"Tarihe göre sıralamak için tıklatın",
"SORT_UPDATED_LABEL":"Son güncelleştirilene göre sıralamak için tıklatın",
"SORT_DUE_LABEL":"Son tarihe göre sıralamak için tıklatın",
"SORT_VISITS_LABEL":"Ziyaret sayısına göre sıralamak için tıklatın",
"SORT_COMMENTS_LABEL":"Yorum sayısına göre sıralamak için tıklatın",
"SORT_RECOMMENDATIONS_LABEL":"Beğenme sayısına göre sıralamak için tıklatın",
"SORT_POPULARITY_LABEL":"Sık kullanıma göre sıralamak için tıklatın",
"SORT_FIRST_NAME_LABEL":"Ada göre sıralamak için tıklatın",
"SORT_LAST_NAME_LABEL":"Soyadına göre sıralamak için tıklatın",
"RATING":"Beğeniler",
"GRADUATED":"Olgunlaştırılmış",
"ONEVOTE":"1 oy",
"VOTES":"{0} oy",
"BOOKMARK_THIS_RESULT":"Buraya yer işareti ekle",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (etkin değil)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} kişiye yer işareti eklendi",
/* eg from an Activity */
"FROMANACTIVITY":"bir Etkinlikten",
"FROMABLOG":"bir Web Günlüğünden",
"FROMANIDEATIONBLOG":"bir Fikir Günlüğünden",
"FROMANEVENT":"bir Takvim Etkinliğinden",
"FROMAFORUM":"bir Forumdan",
"FROMAWIKI":"bir Vikiden",
"FROMACOMMUNITY":"bir Topluluktan",
"FROMXCOMMUNITIES":"{0} Topluluktan",
/* For search results parentage */
"ACTIVITY_ALONE":"Etkinlik",
"BLOG_ALONE":"Web Günlüğü",
"IDEATIONBLOG_ALONE":"Fikir Günlüğü",
"ENTRY_ALONE":"Girdi",
"EVENT_ALONE":"Takvim Etkinliği",
"FORUM_ALONE":"Forum",
"WIKI_ALONE":"Viki",
"COMMUNITY_ALONE":"Topluluk",
"XCOMMUNITIES_ALONE":"{0} Topluluk",
"SHAREDCOMMUNITIES":"Bu topluluklarla paylaşılan",
"INACOMMUNITY":"bir Toplulukta",
"LASTUPDATED":"Arama dizininin son güncelleştirme tarihi:",
"NODESCRIPTION":"Bu sonuç için açıklama ya da özet yok.",
"ATTACHMENT":"Ek:",
"ACTIVITY":"Etkinlik:",
"ACTIVITYBOOKMARK":"Etkinlik yer işareti:",
"ACTIVITYCOMMENT":"Etkinlik yorumu:",
"ACTIVITYENTRY":"Etkinlik girdisi:",
"ACTIVITYSECTION":"Etkinlik bölümü:",
"ACTIVITYTODO":"Etkinlik yapılacak işi:",
"BLOG":"Web günlüğü:",
"BLOGENTRY":"Web günlüğü girdisi:",
"BLOGCOMMENT":"Fikir günlüğü yorumu:",
"BOOKMARK":"Yer işareti:",
"CALENDAREVENT":"Takvim Etkinliği:",
"CATEGORY":"Kategori:",
"COMMENT":"Yorum:",
"COMMUNITY":"Topluluk:",
"ENTRY":"Girdi:",
"EVENTDATEON":"Şu günlerde: {0}",
"EVENTISALLDAY":"Tam günlük etkinlik",
"EVENTREPEATS":"Yinelensin",
"FEED":"Özet akışı:",
"FILE":"Dosya:",
"FORUM":"Forum:",
"FORUMCATEGORY":"Forum kategorisi:",
"FORUMTOPIC":"Forum konusu:",
"IDEA":"Fikir:",
"IDEACOMMENT":"Fikir yorumu:",
"IDEATIONBLOG":"Fikir Günlüğü",
"PAGE":"Sayfa:",
"PROFILE":"Profil:",
"SECTION":"Bölüm:",
"STATUSUPDATE":"Durum Güncelleştirmesi",
"STATUSUPDATE_PREFIX":"Durum Güncelleştirmesi:",
"TOPIC":"Konu:",
"TOPIC_WITH_ATTACHMENT":"Konu",
"WIKITYPE":"Viki:",
"WIKIPAGE":"Viki sayfası:",
"WIKIFILE":"Viki eki:",
"SEARCH":"Ara:",
"TODO":"Yapılacak İş:",
"ALLRESULTS":"Tüm Sonuçlar",
"PUBLICCONTENT":"Genel İçerik",
"MYCONTENT":"İçeriğim",
"RESULTNOTFOUND":"Aradığınızı bulamadınız mı?",
"TEMPDIFFICULTIES":"Not: Geçici dizin zorlukları nedeniyle, aramanız son {1} gün içinde değiştirilen {0} öğesini içermedi.",
"TRYLATER":"Lütfen daha sonra yeniden deneyin.",
"MULTIPLETEMPDIFFICULTIES":"Not: Geçici dizinleme zorlukları nedeniyle aramanız, yeni değiştirilen {0} öğesini içermiyordu",
"YOUAREAUTHOR":"Yazarsınız.",
"YOUARECONTRIBUTOR":"Katkıda bulunuyorsunuz.",
"YOUAREOWNER":"Sahipsiniz.",
"YOUAREMEMBER":"Üyesiniz.",
/* Profiles */
"MYNETWORK":"Ağım",
"ALLPEOPLE":"Tüm Kişiler",
"EXCLUDEINACTIVE":"Etkin Olmayan Kişileri Dışla",
"PHONE":"Telefon:",
"EMAIL":"E-posta:",
/* Communities */
"ALLCOMMUNITIES":"Tüm Topluluklar",
"PUBLICCOMMUNITIES":"Genel Topluluklar",
"MYCOMMUNITIES":"Topluluklarım",
"EVERYTHINGCOMMUNITIES":"Topluluklardaki Her Şey",
"COMMUNITIESONLY":"Topluluklar",
"COMMUNITIESCONTENT":"Topluluklardaki İçerik",
/* Activities */
"ALLACTIVITIES":"Tüm Etkinlikler",
"PUBLICACTIVITIES":"Genel Etkinlikler",
"MYACTIVITIES":"Etkinliklerim",
"EVERYTHINGACTIVITIES":"Etkinliklerdeki Her Şey",
"ACTIVITIESONLY":"Etkinlikler",
"SECTIONSACTIVITIES": "Etkinliklerdeki Bölümler",
"ENTRIESACTIVITIES":"Etkinliklerdeki Girdiler",
"TODOSACTIVITIES":"Etkinliklerdeki Yapılacak İşler",
"BOOKMARKSACTIVITIES":"Etkinliklerdeki Yer İşaretleri",
"FILESACTIVITIES":"Etkinliklerdeki Ekler",
"ALLTYPESACTIVITIES":"Tüm Etkinlik Türleri",
"COMMUNITYACTIVITIES":"Topluluklardaki Etkinlikler",
"STANDALONEACTIVITIES":"Bağımsız Etkinlikler",
/* Forums */
"ALLFORUMS":"Tüm Forumlar",
"PUBLICFORUMS":"Genel Forumlar",
"MYFORUMS":"Forumlarım",
"EVERYTHINGFORUMS":"Forumlardaki Her Şey",
"FORUMSONLY":"Forumlar",
"TOPICSFORUMS":"Forum Konuları",
"FORUMCATEGORIES": "Forum Kategorileri",
"FILESFORUMS":"Forumlardaki Ekler",
"ALLTYPESFORUMS":"Tüm Forum Türleri",
"COMMUNITYFORUMS":"Topluluklardaki Forumlar",
"STANDALONEFORUMS":"Bağımsız Forumlar",
/* Blogs */
"ALLBLOGS":"Tüm Web Günlükleri",
"PUBLICBLOGS":"Genel Web Günlükleri",
"MYBLOGS":"Web Günlüklerim",
"EVERYTHINGBLOGS":"Web Günlüklerindeki Her Şey",
"BLOGSONLY":"Web Günlükleri",
"ENTRIESBLOGS":"Web Günlüğü Girdileri",
"FILESBLOGS":"Web Günlüklerindeki Ekler",
"EVERYTHINGIDEATIONBLOGS":"Fikir Günlüklerindeki Her Şey",
"BLOGSIDEATIONBLOGS":"Fikir Günlükleri",
"BLOGSIDEAS":"Fikirler",
"ALLTYPESBLOGS":"Tüm Web Günlüğü Türleri",
"COMMUNITYBLOGS":"Topluluklar'daki Web Günlükleri",
"COMMUNITYIDEATIONBLOGS":"Topluluklar'daki Fikir Günlükleri",
"STANDALONEBLOGS":"Bağımsız Web Günlükleri",
/* Bookmarks */
"ALLBOOKMARKS":"Tüm Yer İşaretleri",
"PUBLICBOOKMARKS":"Genel Yer İşaretleri",
"MYBOOKMARKS":"Yer İşaretlerim",
"ALLTYPESBOOKMARKS":"Tüm Yer İşareti Türleri",
"COMMUNITYBOOKMARKS":"Topluluklardaki Yer İşaretleri",
"STANDALONEBOOKMARKS":"Bağımsız Yer İşaretleri",
/* Files */
"ALLFILES":"Tüm Dosyalar",
"PUBLICFILES":"Genel Dosyalar",
"MYFILES":"Dosyalarım",
"ALLTYPESFILES":"Tüm Dosya Türleri",
"COMMUNITYFILES":"Topluluklardaki Dosyalar",
"STANDALONEFILES":"Bağımsız Dosyalar",
"NUMDOWNLOADS":"{0} Karşıdan Yükleme",
/* Wikis */
"ALLWIKIS":"Tüm Vikiler",
"PUBLICWIKIS":"Genel Vikiler",
"MYWIKIS":"Vikilerim",
"EVERYTHINGWIKIS":"Vikilerdeki Her Şey",
"WIKISONLY":"Vikiler",
"PAGESWIKIS":"Viki Sayfaları",
"FILESWIKIS":"Vikilerdeki Ekler",
"ALLTYPESWIKIS":"Tüm Viki Türleri",
"COMMUNITYWIKIS":"Topluluklardaki Vikiler",
"STANDALONEWIKIS":"Bağımsız Vikiler",
/* Status Updates */
"ALLSTATUSUPDATES":"Tüm Durum Güncelleştirmeleri",
"PUBLICSTATUSUPDATES":"Genel Durum Güncelleştirmeleri",
"MYSTATUSUPDATES":"Durum Güncelleştirmelerim",
"ALLTYPESSTATUSUPDATES":"Tüm Durum Güncelleştirmesi Türleri",
"COMMUNITYSTATUSUPDATES":"Topluluklardaki Durum Güncelleştirmeleri",
"STANDALONESTATUSUPDATES":"Profillerdeki Durum Güncelleştirmeleri",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"Bu URL'ye birkaç kullanıcı tarafından yer işareti eklendi",
"BOOKMARKEDCOMMUNITY":"Bu topluluğa birkaç kullanıcı tarafından yer işareti eklendi",
"BOOKMARKEDPROFILE":"Bu Profile birkaç kullanıcı tarafından yer işareti eklendi",
"BOOKMARKEDBLOG":"Bu Web Günlüğüne birkaç kullanıcı tarafından yer işareti eklendi",
"COMMUNITYBLOG":"Bu, topluluk içindeki bir web günlüğüdür",
"BOOKMARKEDACTIVITY":"Bu Etkinliğe birkaç kullanıcı tarafından yer işareti eklendi",
"COMMUNITYACTIVITY":"Bu, topluluk içindeki bir Etkinliktir",
"BOOKMARKEDFILE":"Bu Dosyaya birkaç kullanıcı tarafından yer işareti eklendi",
"COMMUNITYFILE":"Bu, topluluk içindeki bir Dosyadır",
"BOOKMARKED":"Bu Vikiye birkaç kullanıcı tarafından yer işareti eklendi",
"COMMUNITYWIKI":"Bu, topluluk içindeki bir Vikidir",
"BOOKMARKEDFORUM":"Bu Foruma birkaç kullanıcı tarafından yer işareti eklendi",
"COMMUNITYFORUM":"Bu, topluluk içindeki bir Forumdur",
"ALLTAGANDTTILE":"Bu URL'ye ilişkin tüm başlıkları ve etiketleri görmek için bu düğmeyi tıklatın",
"TAGS_ARE_FROM":"Bu arama sonucu şu konumdan etiketleri içerebilir:",
"BOOKMARKS_TITLE":"Yer İşaretleri",
"COMMUNITIES_TITLE":"Topluluklar",
"ACTIVITIES_TITLE":"Etkinlikler",
"HELP":"Yardım",
"MORESTATUSUPDATES":"Daha fazla durum güncelleştirmesi eşleştirmesi görüntüle",
"TITLE_PREFIX":"başlık:",
"LATEST_MESSAGE":"Son İleti",
"LATEST_STATUS_UPDATE":"Son Durum Güncelleştirmesi",
"LATEST_COMMUNITY_STATUS_UPDATE":"Son Topluluk Durumu Güncelleştirmesi",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Son Topluluk Durumu Güncelleştirmesi",
"SEARCH_RESULTS":"Tüm İçerik Araması Sonuçları",
"ACTIVITIES_SEARCH_RESULTS":"Etkinlikler Arama Sonuçları",
"BLOGS_SEARCH_RESULTS":"Web Günlükleri Arama Sonuçları",
"BOOKMARKS_SEARCH_RESULTS":"Yer İşaretleri Arama Sonuçları",
"COMMUNITIES_SEARCH_RESULTS":"Topluluklar Arama Sonuçları",
"FILES_SEARCH_RESULTS":"Dosyalar Arama Sonuçları",
"FORUMS_SEARCH_RESULTS":"Forumlar Arama Sonuçları",
"PROFILES_SEARCH_RESULTS":"Profiller Arama Sonuçları",
"DIRECTORY_SEARCH_RESULTS":"${orgName} Dizini Arama Sonuçları",
"WIKIS_SEARCH_RESULTS":"Vikiler Arama Sonuçları",
"STATUS_UPDATES_SEARCH_RESULTS":"Durum Güncelleştirmeleri Arama Sonuçları",
"VIEW_ALL":"{span}Tümünü Görüntüle{/span} ({0})",
"MATCHING_ONE_OF":"Biriyle eşleşen:",
"MATCHING_ALL_OF":"Tümüyle eşleşen:",
"MATCHING":"Eşleşme:",
"MATCHING_DOC_TYPE":"Eşleşen Belge Türü:",
"BOOKMARK_HELP":"Yer İşareti Yardımı",
"CLOSE_BOOKMARK_HELP":"Yer İşareti Yardımını Kapat",
"DOCUMENT_TYPE_PREFIX":"Belge türü:",
"FILE_PREVIEW_ONLY":"(Salt Önizleme Modu)"
})

