/* *************************************************************** */
/*                                                                 */
/* HCL Confidential                                                */
/*                                                                 */
/* OCO Source Materials                                            */
/*                                                                 */
/* Copyright HCL Technologies Limited 2022                         */
/*                                                                 */
/* The source code for this program is not published or otherwise  */
/* divested of its trade secrets, irrespective of what has been    */
/* deposited with the U.S. Copyright Office.                       */
/*                                                                 */
/* *************************************************************** */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Щракнете тук, за да видите визитката",
	"label.semtag.hover.alt" : "Щракнете тук, за да видите визитката за {0}",
	"label.semtag.hover.altA11Y" : "Щракнете тук или натиснете Control-Enter, за да видите визитката",
	"label.personcard.dialog.title" : "Визитка за {0}",

	"errorDefaultMsg2" : "Възникна грешка; свържете се с вашия системен администратор",

	"loadingSTStatus" : "Зареждане на състояние Sametime...",
	"noStatuAvailable" : "Няма налично състояние Sametime",

	"label.personcard.cardnomarkup" : "Визитката не можа да бъде извлечена",
	"label.inactive.user.msg" : "Това лице вече не е активен потребител",
	"label.message.information" : "Информация:",
	"label.personcard.noprofilemsg" : "Не съществува профил за това лице",
	"label.personcard.cardreqexpired" : "Срокът на искане за получаване на визитка е изтекъл",

	"label.bizcard.applinks.less" : "Показване на по-малко",
	"label.bizcard.applinks.more" : "Показване на повече",

	"label.personcard.activitieslink" : "Дейности",
	"label.personcard.activitieslink.title" : "Щракнете тук, за да видите споделените дейности",
	"label.personcard.blogslink" : "Блогове",
	"label.personcard.blogslink.title" : "Щракнете тук, за да видите блога на това лице",
	"label.personcard.communitieslink" : "Общности",
	"label.personcard.communitieslink.title" : "Щракнете тук, за да видите общностите на това лице",
	"label.personcard.dogearlink" : "Показалци",
	"label.personcard.dogearlink.title" : "Щракнете тук, за да видите показалците на това лице",
	"label.personcard.fileslink" : "Файлове",
	"label.personcard.fileslink.title" : "Щракнете тук, за да видите споделените файлове на това лице",
	"label.personcard.forumlink" : "Форуми",
	"label.personcard.forumlink.title" : "Щракнете тук, за да видите публикации във форума на това лице",
	"label.personcard.homepagelink" : "Начало",
	"label.personcard.homepagelink.title" : "Щракнете тук, за да видите началната страница на това лице",
	"label.personcard.mobilelink" : "Мобилно устройство",
	"label.personcard.mobilelink.title" : "Щракнете тук, за да видите страницата за мобилно устройство на това лице",
	"label.personcard.newslink" : "Новини",
	"label.personcard.newslink.title" : "Щракнете тук, за да видите новините на това лице",
	"label.personcard.profilelink" : "Профил",
	"label.personcard.profilelink.title" : "Щракнете тук, за да видите профила на това лице",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Щракнете тук, за да видите споделянията на това лице в quickr",
	"label.personcard.wikislink" : "Wiki сайтове",
	"label.personcard.wikislink.title" : "Щракнете тук, за да видите wiki сайтовете на това лице",

	"personCardMoreActions" : "Повече действия",
	"personCardMoreActionsAltText" : "Щракнете за менюто с действия",

	"label.bizcard.dismiss": "Натиснете Esc, за да отмените тази визитка.",
	"label.bizcard.fullProfile": "Пълен профил",
	"label.bizcard.activities": "Дейности",
	"label.bizcard.communities": "Общности",
	"label.bizcard.files": "Файлове",
	"label.bizcard.forums": "Форуми",
	"label.bizcard.bookmarks": "Показалци",
	"label.bizcard.blogs": "Блогове",
	"label.bizcard.wikis": "Wiki сайтове",

	"personCardAddAsColleagues" : "Покана за \"Моята мрежа\"",
	"personCardAddAsMyColleagues" : "Покана за \"Моята мрежа\"",
	"personCardFollow" : "Следване",
	"personCardUnfollow" : "Спиране на следването",
	"personCardChat" : "Чат",
	"personCardCall" : "Повикване",
	"personCardSendMail" : "Изпращане на имейл",
	"personCardSendEMail" : "Изпращане на имейл",
	"personCardProxyStatusAvailable" : "На разположение съм",
	"personCardDownloadVCard" : "Изтегляне на vCard",

	"friends" : "Мрежа",
	"friendsFullPageTitle" : "Мрежа",
	"friendsMenuTitleAllContacts" : "Всички мрежови контакти",
	"friendsMenuTitleMyContacts" : "Моите мрежови контакти",
	"friendsInvitations" : "Покани",
	"friendsMenuTitleInCommon" : "Общи хора",
	"friendsShowAllCommonFriends" : "Показване на всички...",
	"friendsViewAllFriends" : "Преглед на всички ({0})",
	"friendsSendFriendRequest" : "Изпращане на искане",
	"friendsNoFriends" : "Няма мрежови контакти, свързани с този профил",
	"friendsColleaguesInvite" : "Покана за {0} да бъде ваш мрежов контакт",
	"friendsColleaguesFor" : "Мрежови контакти за {0}",
	"friendsNewInv" : "{0} нова покана",
	"friendsNewInvs" : "{0} нови покани",
	"friendsLoading" : "Зареждане на мрежа...",
	"friendsLoadingInv" : "Изпращане на покани...",
	"friendsSelectFriendForRemoval" : "Изберете контактите, които искате да премахнете първо.",
	"friendsRemoved" : "Мрежовите контакти са премахнати.",
	"friendsInvSent" : "Не е изпратена покана, защото има чакаща покана.",
	"friendsRemovedSelected" : "Премахване от \"Моята мрежа\"",
	"friendsSortByDisplayName" : "Показвано име",
	"friendsSortByRecent" : "Скорошни",
	"friendsTelephone" : "Телефон:",
	"friendsEmail" : "Имейл:",
	"friendsAltEmail" : "Алтернативен имейл:",
	"friendsNewInvitationsCount" : "Имате {0} нови покани",
	"friendsNoInv" : "Моите покани",
	"friendsInCommonSingle" : "Вие имате {0} общ мрежов контакт",
	"friendsInCommonMulti" : "Вие имате {0} общи мрежови контакти",
	"friendsIncludeMsgForInv" : "Включване на съобщение към вашата покана:",
	"friendsInitialMsgForInv" : "Желая да ви добавя в моя списък с контакти от мрежата Connections.",
	"friendsSendInvAction" : "Изпращане на покана",
	"friendsCancelInvAction" : "Отмяна",
	"friendsAcceptAction" : "Приемане",
	"friendsIgnoreAction" : "Игнориране",
	"friendsYouExceedTextLimit" : "Вашето съобщение за покана е твърде дълго. То може да е максимум {1} знака. Има {0} знака в това поле.",
	"friendsCannotAddYourself" : "Не можете да добавите себе си като мрежов контакт.",
	"friendsIsYourColleague" : "{0} е ваш мрежов контакт",
	"friendsRecentlyAdded" : "Хора, които скоро сте добавили към вашата мрежа.",
	"friendsDate" : "Дата",
	"friendsCollapseWidget" : "Щракнете, за да свиете този раздел на мрежата",
	"friendsExpandWidget" : "Щракнете, за да разгънете този раздел на мрежата",
	"friendsIsInYourNetwork" : "{0} е във вашата мрежа",
	"friendsActionsFor" : "Действия за мрежа",
	"friendsInviteFollowError" : "Възникна грешка при опит за следване на {0}",
	"friendsInviteTagError" : "Възникна грешка при опит за постаяне на етикет на {0}",
	"friendsPleaseLogIn" : "Влезте, за да поканите хора във вашата мрежа",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Покана за вашата мрежа не е възможна, защото {0} вече е във вашата мрежа.",
	"friendsInviteAddTagsFor" : "Добавяне на етикети за {0}",
	"friendsInviteAlsoFollow" : "Също следване",
	"friendsInviteReceiveUpdates" : "(получаване на актуализации)",
	"friendsInviteUpdatesDescription" : "Получаване на актуализации за хора, които следвате, на началната страница и в имейл резюме.",
	"friendsInviteFollowHelp": "За повече информация, вижте {0}Следване на хора{1}.",
	"friendsNetwork" : "Мрежа",
	"friendsMyNetwork" : "Мрежа",
	"friendsNetworkFor" : "Мрежа за {0}",
	"friendsRemoveSelected" : "Премахване на избраните",
	"friendsRemoveSelectedTip" : "Щракнете, за да премахнете избраните хора от вашата мрежа.",
	"friendsNetworkInCommon" : "Имате {0} общи мрежови връзки.",
	"friendsAddToMyNetwork" : "Желая да ви добавя в моя списък с контакти от мрежата Connections.",
	"friendsInvite" : "Покана в \"Моята мрежа\"",
	"friendsInvitePerson" : "Покана за {0} във вашата мрежа",
	"friendsInviteMessage" : "Желая да ви добавя към моята мрежа на Connections.",
	"friendsInvitedEmailSubject" : "[Profiles] Вие сте поканени да се присъедините към моята мрежа",
	"friendsInvitedEmailMsg1" : "ви покани да станете мрежов контакт със следното съобщение, включено в поканата:",
	"friendsInvitedEmailMsg2" : "Отваряне на вашата страница с покани за мрежата",
	"friendsInvitedEmailMsg3" : "Желая да ви добавя към моята мрежа.",
	"friendsInvitedEmailMsg4" : "{0} ви покани да станете мрежов контакт:",
	"friendsInvitedEmailMsg5" : "{0} ви покани да станете мрежов контакт със следното съобщение, включено в поканата:",
	"friendsInviteLegalNote" : "Като изпращате тази покана, вие се съгласявате да позволите на {0} да коментира на таблото на вашия профил.",
	"friendsInviteFailed" : "Поради грешка в сървъра, не беше изпратено известие по имейл до поканения. Поканеният обаче все още ще може да приеме вашата покана през уеб приложението \"Профили\".",
	"personInNetwork" : "Мрежов контакт"
})
