/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Solmun tiedot: ",
		"INSTALLED": "Järjestelmä tarkistaa asennetut palvelut",
		"RESUMETOKENS": "Järjestelmä tarkistaa jatkovuoromerkit",
		"SEEDLISTS": "Järjestelmä tarkistaa, että alkuarvoluettelot ovat käytettävissä",
		"CALENDARS": "Järjestelmä tarkistaa, että ajankäyttökalenterit on määritetty oikein",
		"VARIABLES": "Järjestelmä tarkistaa, että WebSphere-muuttujat on määritetty",
		"TASKS": "Tarkistetaan, onko järjestelmässä käyttöön otettuja indeksointitehtäviä",
		"INDEXFILES": "Järjestelmä tarkistaa, onko indeksikansiossa pakollisia tiedostoja",
		"LOGS": "Järjestelmä tarkistaa, onko lokeissa virheitä",
		"CONFIGFILES": "Järjestelmä tarkistaa kokoonpanotiedostot",
		"DICTIONARIES": "Järjestelmä tarkistaa käyttöön otettujen sanastojen määrän",
		"SYNC": "Järjestelmä tarkistaa solmujen tilan",
		"DBRECORDS": "Järjestelmä tarkistaa tietokantatietueet",
		"INSTALLEDMSG": "Seuraava palvelu on asennettu: ",
		"RESUMETOKENSMSG": "Jatkovuoromerkki kohteelle: ",
		"SEEDLISTSMSG": "Alkuarvoluettelon nouto kohteelle ei onnistunut: ",
		"CALENDARSMSG": "Ajankäyttökalenterin tarkistus on läpäisty: ",
		"VARIABLESMSG": "Muuttuja: ",
		"TASKSMSG": "Seuraava tehtävä on käytössä: ",
		"INDEXFILESMSG" : "Seuraavat tiedostot ovat hakuindeksikansiossa: ",
		"LOGSMSG" : "Tarkista seuraavat virhesanomat: ",
		"CONFIGFILESMSG" : "Seuraavat kokoonpanotiedostot on löydetty: ",
		"DICTIONARIESMSG" : "Käyttöön otettujen sanastojen määrä on: ",
		"INSYNC": "Kaikki solmut ovat synkronoituja",
		"OUTOFSYNC": "Synkronoimattomien solmujen määrä on: ",
		"NOTBLOCKED": "Yhtään solmua ei ole estetty",
		"BLOCKED": "Estettyjen solmujen määrä on: ",
		"INDATE": "Kaikki solmut ovat ajan tasalla",
		"OUTOFDATE": "Vanhentuneiden solmujen määrä on: ",
		"NUMOFDOCS": "Asiakirjojen määrä tietokannassa on ",
		"FILESTOCONVERT": "Muunnettavien tiedostoasiakirjojen määrä on ",
		"CONVERTEDFILES": "Muunnettujen tiedostojen määrä on ",
		"TOTALFILES": "Tietokannan tiedostojen kokonaismäärä ",
		"ERROR":"Virhe",
		"ERROR_PREFIX":"Virhe:",
		"INFO":"Ilmoitus",
		"INFO_PREFIX":"Ilmoitus:",
		"WARNING":"Varoitus",
		"WARNING_PREFIX":"Varoitus:",
		"LOADING_MESSAGE": "Lataus",
		"SERVER_STATUS": "Palvelimen tila",
		"INITIAL_INDEXING_EXCEPTIONS": "Alkuindeksoinnin poikkeukset",
		"SYS_OUT_EXCEPTIONS": "SystemOut-lokin poikkeukset",
		"SEEDLIST_VALIDATE": "Alkuarvoluettelojen tarkistus",
		"ERRORS_DURING_INITIAL_INDEXING":"Alkuindeksin luonnissa ilmenivät seuraavat poikkeukset",
		"CRAWL_FAILED": "Seuraavan palvelun kaikkien tietojen läpikäynti ei onnistunut: ",
		"EXCEPTION_ENCOUNTERED": "Läpikäynti epäonnistui ja palautti seuraavan sanoman: ",
		"SAND_VALIDATE": "SAND-tarkistus",
		"CHECK_FOR_SAND_FILES":"Tarkistetaan, onko järjestelmässä SAND-tiedostoja",
		"IS_FILE_AVAILABLE":"Järjestelmä tarkistaa, että tiedosto on luotu: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Alkuindeksin luonnissa ilmenivät seuraavat poikkeukset",
		"CRAWL_FAILED":"Seuraavan palvelun kaikkien tietojen läpikäynti ei onnistunut: ",
		"EXCEPTION_ENCOUNTERED":"Läpikäynti epäonnistui ja palautti seuraavan sanoman: "
});

