/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Suodatusperuste:",
		"SHOW":"Näytä:",
		"ACL_FILTER_LABEL":"Suodata näkyvyyden perusteella",
		"PARENT_FILTER_LABEL":"Suodata säilön perusteella",
		"TYPE_FILTER_LABEL":"Suodata lajin perusteella",
		"PAGING_TOP":"Ensisijainen sivunumerointi",
		"PAGING_BOTTOM":"Toissijainen sivunumerointi",
		"PREVIOUS":"Edellinen",
		"NEXT":"Seuraava",
		"PAGE":"Sivu {0} / {1}",
		"PAGE_COLON":"Sivu:",
		"RESULTS":"{span}{0}-{1}{/span} / {2}",
		"ITEMS":"{0} kohdetta",
		/* Application names */
		"ACTIVITIES":"Aktiviteetit",
		"BLOGS":"Verkkolokit",
		"CALENDAR":"Kalenteri",
		"COMMUNITIES":"Yhteisöt",
		"BOOKMARKS":"Kirjanmerkit",
		"DOGEAR":"Kirjanmerkit",
		"EVENTS":"Tapahtumat",
		"FILES":"Tiedostot",
		"FORUMS":"Keskusteluryhmät",
		"PROFILES":"Profiilit",
		"WIKI":"Wikit",
		"WIKIS":"Wikit",
		"FEEDS":"Syötteet",
		"STATUS_UPDATES":"Tilapäivitykset",
		"ONECOMMENT":"1 kommentti",
		"COMMENTS":"{0} kommenttia",
		"ONEPERSON":"Yksi henkilö",
		"PEOPLE":"{0} henkilöä",
		"TAGS":"Tunnisteet:",
		"TAGSMORE":"ja {0} lisää",
		"NORESULTSMESSAGE":"Haulla ei löytynyt tuloksia.",
		"JAN":"Tammikuu",
		"FEB":"Helmikuu",
		"MAR":"Maaliskuu",
		"APR":"Huhtikuu",
		"MAY":"Toukokuu",
		"JUN":"Kesäkuu",
		"JUL":"Heinäkuu",
		"AUG":"Elokuu",
		"SEP":"Syyskuu",
		"OCT":"Lokakuu",
		"NOV":"Marraskuu",
		"DEC":"Joulukuu",
		"NO_CONTACT":"Hakua ei suoritettu, koska palvelimeen ei voitu muodostaa yhteyttä.",
		"SERVER_ERROR":"Hakua ei suoritettu palvelinvirheen vuoksi.",
		"SORT_BY":"Lajitteluperuste:",
		"SORT_RELEVANCE":"Tärkeys",
		"SORT_DATE":"Päivämäärä",
		"SORT_LAST_UPDATED":"Viimeksi päivitetty",
		"SORT_DUE_DATE":"Määräpäivä",
		"SORT_VISITS":"Vierailut",
		"SORT_COMMENTS":"Kommentit",
		"SORT_RECOMMENDATION":"Pitämiset",
		"SORT_POPULARITY":"Suosio",
		"SORT_FIRSTNAME":"Etunimi",
		"SORT_LASTNAME":"Sukunimi",
		"SORT_DOWNLOADS":"Lataukset",
		"SORT_TYPE":"Laji",
		"SORT_SIZE":"Koko",
		"SORT_TITLE":"Puhuttelutitteli",
		"PRIVATE":"Yksityinen",
		"MODERATED":"Valvottu",
		"COMMUNITY_ACTIVITY":"Yhteisön aktiviteetti",
		"COMMUNITY_BLOG":"Yhteisön verkkoloki",
		"COMMUNITY_FILE":"Yhteisön tiedosto",
		"COMMUNITY_FORUM":"Yhteisön keskusteluryhmä",
		"COMMUNITY_WIKI":"Yhteisön wiki",
		"COMMUNITY_FEED":"Yhteisön syöte",
		"COMMUNITY_BOOKMARK":"Yhteisön kirjanmerkki",
		"NO_TAG":"Tunnisteita ei ole vielä",
		"NO_DATE":"Päivämääriä ei ole vielä",
		"NO_PEOPLE":"Henkilöitä ei ole vielä",
		"REMOVE_FILTER_LABEL":"Poista napsauttamalla",
		"REMOVE_FILTER_TITLE":"Poista",
		"REMOVE_FILTER_TOOLTIP":"Poista tämä suodatin",
		"COMMENT_ON":"Kommentoi merkintää:",
		"EXPAND_COLLAPSE":"Laajenna tai pienennä napsauttamalla",
		"EXPAND":"Laajenna",
		"COLLAPSE":"Pienennä",
		"EXPAND_MONTHS_FILTER":"Laajenna vuoden {0} kuukausisuodatin",
		"SORT_RELEVANCE_LABEL":"Lajittele tärkeyden perusteella napsauttamalla",
		"SORT_DATE_LABEL":"Lajittele päivämäärän perusteella napsauttamalla",
		"SORT_UPDATED_LABEL":"Lajittele viimeisimmän päivityksen mukaan napsauttamalla tätä",
		"SORT_DUE_LABEL":"Lajittele määräpäivän perusteella napsauttamalla tätä",
		"SORT_VISITS_LABEL":"Lajittele vierailujen määrän perusteella napsauttamalla",
		"SORT_COMMENTS_LABEL":"Lajittele kommenttien määrän perusteella napsauttamalla",
		"SORT_RECOMMENDATIONS_LABEL":"Lajittele pitämisten määrän perusteella napsauttamalla",
		"SORT_POPULARITY_LABEL":"Lajittele suosion perusteella napsauttamalla",
		"SORT_FIRST_NAME_LABEL":"Lajittele etunimen perusteella napsauttamalla",
		"SORT_LAST_NAME_LABEL":"Lajittele sukunimen perusteella napsauttamalla",
		"RATING":"Pitämiset",
		"GRADUATED":"Valmistunut",
		"ONEVOTE":"1 ääni",
		"VOTES":"{0} ääntä",
		"BOOKMARK_THIS_RESULT":"Lisää tämä kirjanmerkiksi",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (passiivinen)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} kirjanmerkittyä henkilöä",
		/* eg from an Activity */
		"FROMANACTIVITY":"aktiviteetista",
		"FROMABLOG":"verkkolokista",
		"FROMANIDEATIONBLOG":"ideointiverkkolokista",
		"FROMANEVENT":"tapahtumasta",
		"FROMAFORUM":"keskusteluryhmästä",
		"FROMAWIKI":"wikistä",
		"FROMACOMMUNITY":"yhteisöstä",
		"FROMXCOMMUNITIES":"{0} yhteisöstä",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Aktiviteetti",
		"BLOG_ALONE":"Verkkoloki",
		"IDEATIONBLOG_ALONE":"Ideointiverkkoloki",
		"ENTRY_ALONE":"Merkintä",
		"EVENT_ALONE":"Tapahtuma",
		"FORUM_ALONE":"Keskusteluryhmä",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Yhteisö",
		"XCOMMUNITIES_ALONE":"{0} yhteisöä",
		"SHAREDCOMMUNITIES":"Yhteiskäytössä näiden yhteisöjen kanssa",
		"INACOMMUNITY":"yhteisössä",
		"LASTUPDATED":"Hakuindeksi on päivitetty viimeksi:",
		"NODESCRIPTION":"Tuloksen kuvausta tai tiivistelmää ei ole.",
		"ATTACHMENT":"Liite:",
		"ACTIVITY":"Aktiviteetti:",
		"ACTIVITYBOOKMARK":"Aktiviteetin kirjanmerkki:",
		"ACTIVITYCOMMENT":"Aktiviteetin kommentti:",
		"ACTIVITYENTRY":"Aktiviteettimerkintä:",
		"ACTIVITYSECTION":"Aktiviteettiosa:",
		"ACTIVITYTODO":"Aktiviteettitehtävä:",
		"BLOG":"Verkkoloki:",
		"BLOGENTRY":"Verkkolokimerkintä:",
		"BLOGCOMMENT":"Verkkolokin kommentti:",
		"BOOKMARK":"Kirjanmerkki:",
		"CALENDAREVENT":"Tapahtuma:",
		"CATEGORY":"Luokka:",
		"COMMENT":"Kommentti:",
		"COMMUNITY":"Yhteisö:",
		"ENTRY":"Merkintä:",
		"EVENTDATEON":"Päiväys: {0}",
		"EVENTISALLDAY":"Koko päivän tapahtuma",
		"EVENTREPEATS":"Toistuva",
		"FEED":"Syöte:",
		"FILE":"Tiedosto:",
		"FORUM":"Keskusteluryhmä:",
		"FORUMCATEGORY":"Keskusteluryhmän luokka:",
		"FORUMTOPIC":"Keskusteluryhmän aihe:",
		"IDEA":"Idea:",
		"IDEACOMMENT":"Idean kommentti:",
		"IDEATIONBLOG":"Ideointiverkkoloki:",
		"PAGE":"Sivu:",
		"PROFILE":"Profiili:",
		"SECTION":"Osa:",
		"STATUSUPDATE":"Tilapäivitys",
		"STATUSUPDATE_PREFIX":"Tilapäivitys:",
		"TOPIC":"Aihe:",
		"TOPIC_WITH_ATTACHMENT":"Aihe",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Wikisivu:",
		"WIKIFILE":"Wikiliite:",
		"SEARCH":"Haku:",
		"TODO":"Tehtävä:",
		"ALLRESULTS":"Kaikki tulokset",
		"PUBLICCONTENT":"Julkinen sisältö",
		"MYCONTENT":"Oma sisältö",
		"RESULTNOTFOUND":"Etkö löytänyt etsimääsi?",
		"TEMPDIFFICULTIES":"Huomautus: Tilapäisten indeksointiongelmien takia hausta puuttuivat kohteet {0}, jotka ovat muuttuneet viimeisten {1} päivän aikana.",
		"TRYLATER":"Yritä myöhemmin uudelleen.",
		"MULTIPLETEMPDIFFICULTIES":"Huomautus: Tilapäisten indeksointiongelmien takia hausta puuttuivat kohteet {0}, jotka ovat muuttuneet äskettäin",
		"YOUAREAUTHOR":"Olet tekijä",
		"YOUARECONTRIBUTOR":"Olet lisääjä",
		"YOUAREOWNER":"Olet omistaja",
		"YOUAREMEMBER":"Olet jäsen",
		/* Profiles */
		"MYNETWORK":"Oma verkosto",
		"ALLPEOPLE":"Kaikki henkilöt",
		"EXCLUDEINACTIVE":"Sulje pois passiiviset henkilöt",
		"PHONE":"Puhelinnumero:",
		"EMAIL":"Sähköpostiosoite:",
		/* Communities */
		"ALLCOMMUNITIES":"Kaikki yhteisöt",
		"PUBLICCOMMUNITIES":"Julkiset yhteisöt",
		"MYCOMMUNITIES":"Omat yhteisöt",
		"EVERYTHINGCOMMUNITIES":"Kaikki yhteisöistä",
		"COMMUNITIESONLY":"Yhteisöt",
		"COMMUNITIESCONTENT":"Yhteisöjen sisältö",
		/* Activities */
		"ALLACTIVITIES":"Kaikki aktiviteetit",
		"PUBLICACTIVITIES":"Julkiset aktiviteetit",
		"MYACTIVITIES":"Omat aktiviteetit",
		"EVERYTHINGACTIVITIES":"Kaikki aktiviteeteista",
		"ACTIVITIESONLY":"Aktiviteetit",
		"SECTIONSACTIVITIES": "Aktiviteettien osat",
		"ENTRIESACTIVITIES":"Aktiviteettien merkinnät",
		"TODOSACTIVITIES":"Aktiviteettien tehtävät",
		"BOOKMARKSACTIVITIES":"Aktiviteettien kirjanmerkit",
		"FILESACTIVITIES":"Aktiviteettien liitteet",
		"ALLTYPESACTIVITIES":"Kaikki aktiviteettilajit",
		"COMMUNITYACTIVITIES":"Yhteisöjen aktiviteetit",
		"STANDALONEACTIVITIES":"Itsenäiset aktiviteetit",
		/* Forums */
		"ALLFORUMS":"Kaikki keskusteluryhmät",
		"PUBLICFORUMS":"Julkiset keskusteluryhmät",
		"MYFORUMS":"Omat keskusteluryhmät",
		"EVERYTHINGFORUMS":"Kaikki keskusteluryhmistä",
		"FORUMSONLY":"Keskusteluryhmät",
		"TOPICSFORUMS":"Keskusteluryhmän aiheet",
		"FORUMCATEGORIES": "Keskusteluryhmän luokat",
		"FILESFORUMS":"Keskusteluryhmien liitteet",
		"ALLTYPESFORUMS":"Kaikki keskusteluryhmälajit",
		"COMMUNITYFORUMS":"Yhteisöjen keskusteluryhmät",
		"STANDALONEFORUMS":"Itsenäiset keskusteluryhmät",
		/* Blogs */
		"ALLBLOGS":"Kaikki verkkolokit",
		"PUBLICBLOGS":"Julkiset verkkolokit",
		"MYBLOGS":"Omat verkkolokit",
		"EVERYTHINGBLOGS":"Kaikki verkkolokeista",
		"BLOGSONLY":"Verkkolokit",
		"ENTRIESBLOGS":"Verkkolokin merkinnät",
		"FILESBLOGS":"Verkkolokien liitteet",
		"EVERYTHINGIDEATIONBLOGS":"Kaikki ideointiverkkolokeista",
		"BLOGSIDEATIONBLOGS":"Ideointiverkkolokit",
		"BLOGSIDEAS":"Ideat",
		"ALLTYPESBLOGS":"Kaikki verkkolokilajit",
		"COMMUNITYBLOGS":"Yhteisöjen verkkolokit",
		"COMMUNITYIDEATIONBLOGS":"Yhteisöjen ideointiverkkolokit",
		"STANDALONEBLOGS":"Itsenäiset verkkolokit",
		/* Bookmarks */
		"ALLBOOKMARKS":"Kaikki kirjanmerkit",
		"PUBLICBOOKMARKS":"Julkiset kirjanmerkit",
		"MYBOOKMARKS":"Omat kirjanmerkit",
		"ALLTYPESBOOKMARKS":"Kaikki kirjanmerkkilajit",
		"COMMUNITYBOOKMARKS":"Yhteisöjen kirjanmerkit",
		"STANDALONEBOOKMARKS":"Itsenäiset kirjanmerkit",
		/* Files */
		"ALLFILES":"Kaikki tiedostot",
		"PUBLICFILES":"Julkiset tiedostot",
		"MYFILES":"Omat tiedostot",
		"ALLTYPESFILES":"Kaikki tiedostolajit",
		"COMMUNITYFILES":"Yhteisöjen tiedostot",
		"STANDALONEFILES":"Itsenäiset tiedostot",
		"NUMDOWNLOADS":"{0} latausta",
		/* Wikis */
		"ALLWIKIS":"Kaikki wikit",
		"PUBLICWIKIS":"Julkiset wikit",
		"MYWIKIS":"Omat wikit",
		"EVERYTHINGWIKIS":"Kaikki wikeistä",
		"WIKISONLY":"Wikit",
		"PAGESWIKIS":"Wikisivut",
		"FILESWIKIS":"Wikien liitteet",
		"ALLTYPESWIKIS":"Kaikki wikilajit",
		"COMMUNITYWIKIS":"Yhteisöjen wikit",
		"STANDALONEWIKIS":"Itsenäiset wikit",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Kaikki tilapäivitykset",
		"PUBLICSTATUSUPDATES":"Julkiset tilapäivitykset",
		"MYSTATUSUPDATES":"Omat tilapäivitykset",
		"ALLTYPESSTATUSUPDATES":"Kaikki tilapäivityslajit",
		"COMMUNITYSTATUSUPDATES":"Yhteisöjen tilapäivitykset",
		"STANDALONESTATUSUPDATES":"Profiilien tilapäivitykset",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Tietyt käyttäjät ovat lisänneet tämän URL-osoitteen kirjanmerkkeihinsä",
		"BOOKMARKEDCOMMUNITY":"Tietyt käyttäjät ovat lisänneet tämän yhteisön kirjanmerkkeihinsä",
		"BOOKMARKEDPROFILE":"Tietyt käyttäjät ovat lisänneet tämän profiilin kirjanmerkkeihinsä",
		"BOOKMARKEDBLOG":"Tietyt käyttäjät ovat lisänneet tämän verkkolokin kirjanmerkkeihinsä",
		"COMMUNITYBLOG":"Tämä on yhteisön sisäinen verkkoloki",
		"BOOKMARKEDACTIVITY":"Tietyt käyttäjät ovat lisänneet tämän aktiviteetin kirjanmerkkeihinsä",
		"COMMUNITYACTIVITY":"Tämä on yhteisön sisäinen aktiviteetti",
		"BOOKMARKEDFILE":"Tietyt käyttäjät ovat lisänneet tämän tiedoston kirjanmerkkeihinsä",
		"COMMUNITYFILE":"Tämä on yhteisön sisäinen tiedosto",
		"BOOKMARKED":"Tietyt käyttäjät ovat lisänneet tämän wikin kirjanmerkkeihinsä",
		"COMMUNITYWIKI":"Tämä on yhteisön sisäinen wiki",
		"BOOKMARKEDFORUM":"Tietyt käyttäjät ovat lisänneet tämän keskusteluryhmän kirjanmerkkeihinsä",
		"COMMUNITYFORUM":"Tämä on yhteisön sisäinen keskusteluryhmä",
		"ALLTAGANDTTILE":"Saat näyttöön kaikki URL-osoitteen otsikot ja tunnisteet napsauttamalla tätä painiketta",
		"TAGS_ARE_FROM":"Hakutulokset saattavat sisältää tunnisteita seuraavista kohteista:",
		"BOOKMARKS_TITLE":"Kirjanmerkit",
		"COMMUNITIES_TITLE":"Yhteisöt",
		"ACTIVITIES_TITLE":"Aktiviteetit",
		"HELP":"Ohje",
		"MORESTATUSUPDATES":"Näytä lisää tilapäivitysten vastineita",
		"TITLE_PREFIX":"Otsikko:",
		"LATEST_MESSAGE":"Uusin viesti",
		"LATEST_STATUS_UPDATE":"Uusin tilapäivitys",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Uusin yhteisön tilapäivitys",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Uusin yhteisöjen tilapäivitys",
		"SEARCH_RESULTS":"Kaiken sisällön hakutulokset",
		"ACTIVITIES_SEARCH_RESULTS":"Aktiviteettien hakutulokset",
		"BLOGS_SEARCH_RESULTS":"Verkkolokien hakutulokset",
		"BOOKMARKS_SEARCH_RESULTS":"Kirjanmerkkien hakutulokset",
		"COMMUNITIES_SEARCH_RESULTS":"Yhteisöjen hakutulokset",
		"FILES_SEARCH_RESULTS":"Tiedostojen hakutulokset",
		"FORUMS_SEARCH_RESULTS":"Keskusteluryhmien hakutulokset",
		"PROFILES_SEARCH_RESULTS":"Profiilien hakutulokset",
		"DIRECTORY_SEARCH_RESULTS":"${orgName}: hakemistohaun tulokset",
		"WIKIS_SEARCH_RESULTS":"Wikien hakutulokset",
		"STATUS_UPDATES_SEARCH_RESULTS":"Tilapäivitysten hakutulokset",
		"VIEW_ALL":"{span}Näytä kaikki{/span} ({0})",
		"MATCHING_ONE_OF":"Vastine johonkin seuraavista:",
		"MATCHING_ALL_OF":"Vastine kaikkiin seuraavista:",
		"MATCHING":"Vastaavuus:",
		"MATCHING_DOC_TYPE":"Vastaava asiakirjalaji:",
		"BOOKMARK_HELP":"Kirjanmerkkien ohje",
		"CLOSE_BOOKMARK_HELP":"Sulje kirjanmerkkien ohje",
		"DOCUMENT_TYPE_PREFIX":"Asiakirjalaji:",
		"LAST_PAGE_MESSAGE": "Hakutuloksia on hyvin paljon. Kokeile tarkentaa hakua lisäämällä hakuehtoja.",
		"LAST_PAGE_SUBMESSAGE": "Näkyvissä on ensimmäiset {resultNumber} oleellista tulosta."
});

