/* Copyright IBM Corp. 2008, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Potreban je naslov.",
	nourl: "Potreban je Url.",
	fileSchema: "Ukoliko želite da dodate udaljeni ili lokalni link ka datoteci, potrebno je da bude u jednom od sledećih formata: file://remote_path ili file:///local_path.",
	invalidUrl: "Ovo nije važeći URL zajednice.",
	txtHelp: "Pomoć",
	txtHelpTags: "Pomoć sa oznakama",
	txtHelpTagsClose: "Zatvori pomoć sa oznakama",
	tagsall: "Svi",
	tagsyours: "Vaši",
	tagsrecent: "Nedavno: ",
	tagspopular: "Popularno: ",
	tagsrecommended: "Preporučeno: ",
	nothingselected: "Potrebno je izabrati zajednicu.",
	nothingselected_activity: "Potrebno je izabrati aktivnost.",
	nothingselected_blogs: "Potrebno je izabrati blog.",
	nothingselected_all: "Nije izabrana usluga ili unos, obeleživač neće biti sačuvan.",
	nothingFeedselected: "Nije izabrana usluga ili unos, fid neće biti sačuvan.",
	alertDialogTitle: "Poruka",
	alertDialogOK: "U redu",
	expand: "Kliknite da biste proširili odeljak",
	collapse: "Kliknite da biste skupili odeljak",
	discussThis: "Diskutuj o ovome",
	by: "od:",
	posted: "Postavljeno:",
	attachments: "Prilozi",
	communityForum: "Forum zajednice",
	notCommunityPage: "Aktuelna veb stranica nije važeća veb stranica zajednice. Moguće je da ručno unesete naslov zajednice, link i opis da biste kreirali srodnu zajednicu.",
	privateCommunityNotice: "Ova zajednica je ograničena. Vidljiva je samo članovima zajednice.",
	forumNameHint : "Unesite ime foruma",
	formDescriptionHint:"Opišite zašto bi ova srodna zajednica zainteresovala vašu zajednicu.",
	information : "Informacije",
	error : "Greška",
	success : "Uspešno",
	warning : "Upozorenje",
	informationColon : "Informacije:",
	successColon : "Uspešno:",
	warningColon : "Upozorenje:",
	errorColon : "Greška:",
	feedAlreadyExist : "Fid već postoji u zajednici.",
	bookmarkAlreadyExist : "Obeleživač već postoji u zajednici.",
	mentionAuthWarning:"Sledeće pomenute osobe neće biti u stanju da prikažu poruku jer nisu članovi ove zajednice:",
	mentionAuthForumWarning:"Sledeće pomenute osobe neće biti u stanju da prikažu poruku jer ne mogu pristupiti ovom forumu:",
	exceedDescLength: "Opis koji ste uneli je predugačak.",
	communities_checked:"${0} izabranih zajednica",
	activities_checked:"${0} izabranih aktivnosti",
	blogs_checked:"${0} izabranih blogova"
})

