/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "節點資訊： ",
		"INSTALLED": "檢查已安裝的服務",
		"RESUMETOKENS": "檢查回復記號",
		"SEEDLISTS": "檢查是否可使用種子清單",
		"CALENDARS": "檢查是否已正確配置排程行事曆",
		"VARIABLES": "檢查是否已設定 WebSphere 變數",
		"TASKS": "檢查已啟用的索引作業",
		"INDEXFILES": "檢查所需檔案的索引資料夾",
		"LOGS": "檢閱日誌中的錯誤",
		"CONFIGFILES": "檢閱配置檔",
		"DICTIONARIES": "檢查已啟用的字典數目",
		"SYNC": "檢查節點的狀態",
		"DBRECORDS": "檢查資料庫記錄",
		"INSTALLEDMSG": "已安裝下列服務： ",
		"RESUMETOKENSMSG": "回復記號用於： ",
		"SEEDLISTSMSG": "無法取得下列項目的種子清單： ",
		"CALENDARSMSG": "通過排程行事曆檢查： ",
		"VARIABLESMSG": "變數： ",
		"TASKSMSG": "已啟用下列作業： ",
		"INDEXFILESMSG" : "下列檔案位於搜尋索引資料夾中： ",
		"LOGSMSG" : "檢閱下列錯誤訊息： ",
		"CONFIGFILESMSG" : "已找到下列配置檔： ",
		"DICTIONARIESMSG" : "已啟用的字典數目： ",
		"INSYNC": "所有節點皆在同步中",
		"OUTOFSYNC": "不同步的節點數目： ",
		"NOTBLOCKED": "未封鎖任何節點",
		"BLOCKED": "已封鎖的節點數目： ",
		"INDATE": "所有節點於日期",
		"OUTOFDATE": "過期的節點數目： ",
		"NUMOFDOCS": "資料庫中的文件數目是 ",
		"FILESTOCONVERT": "要轉換的檔案文件數目是 ",
		"CONVERTEDFILES": "轉換的檔案數目是 ",
		"TOTALFILES": "資料庫中的檔案總數 ",
		"ERROR":"錯誤",
		"ERROR_PREFIX":"錯誤：",
		"INFO":"資訊",
		"INFO_PREFIX":"資訊：",
		"WARNING":"警告",
		"WARNING_PREFIX":"警告：",
		"LOADING_MESSAGE": "載入中",
		"SERVER_STATUS": "伺服器狀態",
		"INITIAL_INDEXING_EXCEPTIONS": "起始檢索異常狀況",
		"SYS_OUT_EXCEPTIONS": "SystemOut 日誌異常狀況",
		"SEEDLIST_VALIDATE": "種子清單驗證",
		"ERRORS_DURING_INITIAL_INDEXING":"建立起始索引時發生下列異常狀況",
		"CRAWL_FAILED": "無法搜索下列服務的所有資料： ",
		"EXCEPTION_ENCOUNTERED": "搜索失敗，訊息如下： ",
		"SAND_VALIDATE": "SAND 驗證",
		"CHECK_FOR_SAND_FILES":"正在檢查是否有 SAND 檔案",
		"IS_FILE_AVAILABLE":"正在檢查是否已建立檔案： ",
		"ERRORS_DURING_INITIAL_INDEXING":"建立起始索引時發生下列異常狀況",
		"CRAWL_FAILED":"無法搜索下列服務的所有資料： ",
		"EXCEPTION_ENCOUNTERED":"搜索失敗，訊息如下： "
});

