/* Copyright IBM Corp. 2011, 2018  All Rights Reserved.              */

({
   dialogTitle : "Adicionar imagem",
   newUpload : "Nova transferência",
   URL : "URL",
   imageLibrary : "Biblioteca de imagens",
   description : "Descrição:",
   imageFile : "Ficheiros:",
   OK: "OK",
   cancel: "Cancelar",
   required: "Campo obrigatório",
   preview: "Pré-visualizar:",
   previewWarning: "Aparentemente, ocorreu uma falha ao carregar a imagem. Tem a certeza de que se trata de um URL de imagem válido?",
   alt: "Texto alternativo:",
   filesTab: "Dos ficheiros",
   images:"Imagens:",
   browse:"Pesquisar...",
   imagePickerTitle:"Inserir imagens de Ficheiros",
   componentImagePickerTitle:" ${0} imagens transferidas",
   /* New String for insert image dialog */
   title: "Inserir imagem",
   uploadBtn: "Transferir imagem",   
   insertBtn: "Inserir imagem",
   uploadTab: "Ficheiros locais",
   externalTab: "URL da Web",
   internalTab: "Imagens existentes",
   fileFieldTip: "Arraste e largue imagens do seu ambiente de trabalho directamente para esta janela para as carregar.",
   AdditionalSection: "Opções adicionais",
   ExpandSection: "Expandir Opções adicionais",
   CloseSection: "Contrair Opções adicionais",
   webURLPrompt: "URL de imagem da Web:",
   previewPrompt: "Área de pré-visualização: As imagens grandes podem levar algum tempo até serem apresentadas.",
   noExistingImage: "Ups! Ainda não foi adicionada nenhuma imagem.",
   selectExistingImage: "Seleccione uma imagem existente:",
   urlMissing: "Introduza um URL",
   urlInvalid: "URL não válido. Certifique-se de que introduz um URL válido e tente novamente.",
   previousItem: "Anterior",
   nextItem: "Seguinte",
   oneImageOneTime: "Já foi adicionada uma imagem a esta janela. Apenas pode inserir uma imagem de cada vez.",
   loadingErrorMsg: "Ocorre um erro ao carregar imagens já existentes. Tente novamente mais tarde",
   urlInputTooltip: "Introduza o URL da Web da imagem"
})

