/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"FILTERBY":"Filtriraj po:",
		"SHOW":"Pokaži:",
		"ACL_FILTER_LABEL":"Filter po vidljivosti",
		"PARENT_FILTER_LABEL":"Filter po spremniku",
		"TYPE_FILTER_LABEL":"Filter po tipu",
		"PAGING_TOP":"Primarna podjela u stranice",
		"PAGING_BOTTOM":"Sekundarna podjela u stranice",
		"PREVIOUS":"Prethodna",
		"NEXT":"Sljedeća",
		"PAGE":"Stranica {0} od {1}",
		"PAGE_COLON":"Stranica:",
		"RESULTS":"{span}{0}-{1}{/span} od {2}",
		"ITEMS":"{0} stavki",
		/* Application names */
		"ACTIVITIES":"Aktivnosti",
		"BLOGS":"Blogovi",
		"CALENDAR":"Kalendar",
		"COMMUNITIES":"Zajednice",
		"BOOKMARKS":"Knjiške oznake",
		"DOGEAR":"Knjiške oznake",
		"EVENTS":"Događaji",
		"FILES":"Datoteke",
		"FORUMS":"Forumi",
		"PROFILES":"Profili",
		"WIKI":"Wikiji",
		"WIKIS":"Wikiji",
		"FEEDS":"Tekuće informacije",
		"STATUS_UPDATES":"Ažuriranja statusa",
		"ONECOMMENT":"1 komentar",
		"COMMENTS":"{0} komentara",
		"ONEPERSON":"1 osoba",
		"PEOPLE":"{0} osoba",
		"TAGS":"Oznake:",
		"TAGSMORE":"i još {0}",
		"NORESULTSMESSAGE":"Nisu nađeni rezultati za ovo pretraživanje",
		"JAN":"Siječanj",
		"FEB":"Veljača",
		"MAR":"Ožujak",
		"APR":"Travanj",
		"MAY":"Svi",
		"JUN":"Lip",
		"JUL":"Srp",
		"AUG":"Kolovoz",
		"SEP":"Rujan",
		"OCT":"Listopad",
		"NOV":"Studeni",
		"DEC":"Prosinac",
		"NO_CONTACT":"Pretraživanje nije izvedeno jer se nije moglo kontaktirati poslužitelj",
		"SERVER_ERROR":"Pretraživanje nije izvedeno zbog greške poslužitelja.",
		"SORT_BY":"Sortiraj po:",
		"SORT_RELEVANCE":"Važnost",
		"SORT_DATE":"Datum",
		"SORT_LAST_UPDATED":"Zadnja promjena",
		"SORT_DUE_DATE":"Datum dospijeća",
		"SORT_VISITS":"Posjete",
		"SORT_COMMENTS":"Komentari",
		"SORT_RECOMMENDATION":"Sviđanja",
		"SORT_POPULARITY":"Popularnost",
		"SORT_FIRSTNAME":"Ime",
		"SORT_LASTNAME":"Prezime",
		"SORT_DOWNLOADS":"Preuzimanja",
		"SORT_TYPE":"Tip",
		"SORT_SIZE":"Veličina",
		"SORT_TITLE":"Naslov",
		"PRIVATE":"Privatno",
		"MODERATED":"Moderirano",
		"COMMUNITY_ACTIVITY":"Aktivnost zajednice",
		"COMMUNITY_BLOG":"Blog zajednice",
		"COMMUNITY_FILE":"Datoteka zajednice",
		"COMMUNITY_FORUM":"Forum zajednice",
		"COMMUNITY_WIKI":"Wiki zajednice",
		"COMMUNITY_FEED":"Informacije za zajednicu",
		"COMMUNITY_BOOKMARK":"Knjiška oznaka zajednice",
		"NO_TAG":"Još nema oznaka",
		"NO_DATE":"Još nema datuma",
		"NO_PEOPLE":"Još nema osoba",
		"REMOVE_FILTER_LABEL":"Kliknite za uklanjanje",
		"REMOVE_FILTER_TITLE":"Ukloni",
		"REMOVE_FILTER_TOOLTIP":"Ukloni ovaj filter",
		"COMMENT_ON":"Komentiraj:",
		"EXPAND_COLLAPSE":"Kliknite za proširiti / srušiti",
		"EXPAND":"Proširi",
		"COLLAPSE":"Sruši",
		"EXPAND_MONTHS_FILTER":"Proširite filter mjeseci za godinu {0}",
		"SORT_RELEVANCE_LABEL":"Kliknite za sort po važnosti",
		"SORT_DATE_LABEL":"Kliknite za sort po datumu",
		"SORT_UPDATED_LABEL":"Kliknite za sort po zadnjoj promjeni",
		"SORT_DUE_LABEL":"Kliknite za sort po datumu dospijeća",
		"SORT_VISITS_LABEL":"Kliknite za sort po broju ili posjetima",
		"SORT_COMMENTS_LABEL":"Kliknite za sort po broju komentara",
		"SORT_RECOMMENDATIONS_LABEL":"Kliknite za sort po broju oznaka 'sviđa mi se'",
		"SORT_POPULARITY_LABEL":"Kliknite za sort po popularnosti",
		"SORT_FIRST_NAME_LABEL":"Kliknite za sort po imenu",
		"SORT_LAST_NAME_LABEL":"Kliknite za sort po prezimenu",
		"RATING":"Sviđanja",
		"GRADUATED":"Stupnjevano",
		"ONEVOTE":"1 glas",
		"VOTES":"{0} glasova",
		"BOOKMARK_THIS_RESULT":"Označi ovo kao knjišku oznaku",
		/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
		"INACTIVE":"{0} (neaktivan)",
		/* only ever more than 1, so 2 people, 3 people etc */
		"BOOKMARKERS":"{0} osoba označeno",
		/* eg from an Activity */
		"FROMANACTIVITY":"iz Aktivnosti",
		"FROMABLOG":"iz Bloga",
		"FROMANIDEATIONBLOG":"iz Bloga ideja",
		"FROMANEVENT":"iz Događaja",
		"FROMAFORUM":"iz Foruma",
		"FROMAWIKI":"iz Wikija",
		"FROMACOMMUNITY":"iz Zajednice",
		"FROMXCOMMUNITIES":"iz {0} Zajednica",
		/* For search results parentage */
		"ACTIVITY_ALONE":"Aktivnost",
		"BLOG_ALONE":"Blog",
		"IDEATIONBLOG_ALONE":"Blog ideja",
		"ENTRY_ALONE":"Unos",
		"EVENT_ALONE":"Događaj",
		"FORUM_ALONE":"Forum",
		"WIKI_ALONE":"Wiki",
		"COMMUNITY_ALONE":"Zajednica",
		"XCOMMUNITIES_ALONE":"{0} Zajednica",
		"SHAREDCOMMUNITIES":"Dijeljeno s ovim zajednicama",
		"INACOMMUNITY":"u Zajednici",
		"LASTUPDATED":"Indeks pretraživanja je zadnji puta mijenjan:",
		"NODESCRIPTION":"Nema opisa ili sažetka za ovaj rezultat.",
		"ATTACHMENT":"Prilog:",
		"ACTIVITY":"Aktivnost:",
		"ACTIVITYBOOKMARK":"Knjiška oznaka aktivnosti:",
		"ACTIVITYCOMMENT":"Komentar aktivnosti:",
		"ACTIVITYENTRY":"Unos aktivnosti:",
		"ACTIVITYSECTION":"Odjeljak aktivnosti:",
		"ACTIVITYTODO":"Aktivnost za napraviti:",
		"BLOG":"Blog:",
		"BLOGENTRY":"Unos u blog:",
		"BLOGCOMMENT":"Komentar u blogu:",
		"BOOKMARK":"Knjiška oznaka:",
		"CALENDAREVENT":"Događaj:",
		"CATEGORY":"Kategorija:",
		"COMMENT":"Komentar:",
		"COMMUNITY":"Zajednica:",
		"ENTRY":"Unos:",
		"EVENTDATEON":"Datum: {0}",
		"EVENTISALLDAY":"Cjelodnevni događaj",
		"EVENTREPEATS":"Ponavljanja",
		"FEED":"Tekuće informacije:",
		"FILE":"Datoteka:",
		"FORUM":"Forum:",
		"FORUMCATEGORY":"Kategorija foruma:",
		"FORUMTOPIC":"Tema foruma:",
		"IDEA":"Ideja:",
		"IDEACOMMENT":"Komentar ideje:",
		"IDEATIONBLOG":"Blog ideja:",
		"PAGE":"Stranica:",
		"PROFILE":"Profil:",
		"SECTION":"Odjeljak:",
		"STATUSUPDATE":"Ažuriranje statusa",
		"STATUSUPDATE_PREFIX":"Ažuriranje statusa:",
		"TOPIC":"Poglavlje:",
		"TOPIC_WITH_ATTACHMENT":"Tema",
		"WIKITYPE":"Wiki:",
		"WIKIPAGE":"Stranica wikija:",
		"WIKIFILE":"Prilog u wikiju:",
		"SEARCH":"Traži:",
		"TODO":"Za napraviti:",
		"ALLRESULTS":"Svi rezultati",
		"PUBLICCONTENT":"Javni sadržaj",
		"MYCONTENT":"Moj sadržaj",
		"RESULTNOTFOUND":"Niste pronašli ono što tražite?",
		"TEMPDIFFICULTIES":"Napomena: Zbog privremenih poteškoća u indeksiranju, vaše pretraživanje nije uključivalo {0} promijenjene u zadnjih {1} dana.",
		"TRYLATER":"Molimo pokušajte ponovno kasnije.",
		"MULTIPLETEMPDIFFICULTIES":"Napomena: Zbog privremenih poteškoća u indeksiranju, vaše pretraživanje nije uključivalo {0} koji su nedavno promijenjeni",
		"YOUAREAUTHOR":"Vi ste autor",
		"YOUARECONTRIBUTOR":"Vi ste doprinositelj",
		"YOUAREOWNER":"Vi ste vlasnik",
		"YOUAREMEMBER":"Vi ste član",
		/* Profiles */
		"MYNETWORK":"Moja mreža",
		"ALLPEOPLE":"Sve osobe",
		"EXCLUDEINACTIVE":"Isključi neaktivne osobe",
		"PHONE":"Telefon:",
		"EMAIL":"E-mail:",
		/* Communities */
		"ALLCOMMUNITIES":"Sve zajednice",
		"PUBLICCOMMUNITIES":"Javne zajednice",
		"MYCOMMUNITIES":"Moje zajednice",
		"EVERYTHINGCOMMUNITIES":"Sve iz Zajednice",
		"COMMUNITIESONLY":"Zajednice",
		"COMMUNITIESCONTENT":"Sadržaj iz Zajednice",
		/* Activities */
		"ALLACTIVITIES":"Sve aktivnosti",
		"PUBLICACTIVITIES":"Javne aktivnosti",
		"MYACTIVITIES":"Moje aktivnosti",
		"EVERYTHINGACTIVITIES":"Sve iz Aktivnosti",
		"ACTIVITIESONLY":"Aktivnosti",
		"SECTIONSACTIVITIES": "Odjeljci iz Aktivnosti",
		"ENTRIESACTIVITIES":"Unosi iz Aktivnosti",
		"TODOSACTIVITIES":"Radni zadaci iz Aktivnosti",
		"BOOKMARKSACTIVITIES":"Knjiške oznake iz Aktivnosti",
		"FILESACTIVITIES":"Prilozi iz Aktivnosti",
		"ALLTYPESACTIVITIES":"Svi tipovi iz Aktivnosti",
		"COMMUNITYACTIVITIES":"Aktivnosti iz Zajednica",
		"STANDALONEACTIVITIES":"Samostalne aktivnosti",
		/* Forums */
		"ALLFORUMS":"Svi forumi",
		"PUBLICFORUMS":"Javni forumi",
		"MYFORUMS":"Moji forumi",
		"EVERYTHINGFORUMS":"Sve iz Foruma",
		"FORUMSONLY":"Forumi",
		"TOPICSFORUMS":"Teme foruma",
		"FORUMCATEGORIES": "Kategorije foruma",
		"FILESFORUMS":"Prilozi iz Foruma",
		"ALLTYPESFORUMS":"Svi tipovi foruma",
		"COMMUNITYFORUMS":"Forumi iz Zajednica",
		"STANDALONEFORUMS":"Samostalni forumi",
		/* Blogs */
		"ALLBLOGS":"Svi blogovi",
		"PUBLICBLOGS":"Javni blogovi",
		"MYBLOGS":"Moji blogovi",
		"EVERYTHINGBLOGS":"Sve iz blogova",
		"BLOGSONLY":"Blogovi",
		"ENTRIESBLOGS":"Blog unosi",
		"FILESBLOGS":"Prilozi iz blogova",
		"EVERYTHINGIDEATIONBLOGS":"Sve iz Blogova ideja",
		"BLOGSIDEATIONBLOGS":"Blogovi ideja",
		"BLOGSIDEAS":"Ideje",
		"ALLTYPESBLOGS":"Svi tipovi blogova",
		"COMMUNITYBLOGS":"Blogovi iz Zajednica",
		"COMMUNITYIDEATIONBLOGS":"Blogovi ideja iz Zajednica",
		"STANDALONEBLOGS":"Samostalni blogovi",
		/* Bookmarks */
		"ALLBOOKMARKS":"Sve knjiške oznake",
		"PUBLICBOOKMARKS":"Javne knjiške oznake",
		"MYBOOKMARKS":"Moje knjiške oznake",
		"ALLTYPESBOOKMARKS":"Svi tipovi knjiških oznaka",
		"COMMUNITYBOOKMARKS":"Knjiške oznake iz Zajednica",
		"STANDALONEBOOKMARKS":"Samostalne knjiške oznake",
		/* Files */
		"ALLFILES":"Sve datoteke",
		"PUBLICFILES":"Javne datoteke",
		"MYFILES":"Moje datoteke",
		"ALLTYPESFILES":"Svi tipovi datoteka",
		"COMMUNITYFILES":"Datoteke iz Zajednica",
		"STANDALONEFILES":"Samostalne datoteke",
		"NUMDOWNLOADS":"{0} preuzimanja",
		/* Wikis */
		"ALLWIKIS":"Svi wikiji",
		"PUBLICWIKIS":"Javni wikiji",
		"MYWIKIS":"Moji wikiji",
		"EVERYTHINGWIKIS":"Sve iz wikija",
		"WIKISONLY":"Wikiji",
		"PAGESWIKIS":"Wiki stranice",
		"FILESWIKIS":"Prilozi iz wikija",
		"ALLTYPESWIKIS":"Svi tipovi wikija",
		"COMMUNITYWIKIS":"Wikiji iz zajednica",
		"STANDALONEWIKIS":"Samostalni wikiji",
		/* Status Updates */
		"ALLSTATUSUPDATES":"Sva ažuriranja statusa",
		"PUBLICSTATUSUPDATES":"Javna ažuriranja statusa",
		"MYSTATUSUPDATES":"Moja ažuriranja statusa",
		"ALLTYPESSTATUSUPDATES":"Svi tipovi ažuriranja statusa",
		"COMMUNITYSTATUSUPDATES":"Ažuriranja statusa iz Zajednica",
		"STANDALONESTATUSUPDATES":"Ažuriranja statusa iz Profila",
		/*String for search feedback dialog box*/
		"BOOKMARKEDURL":"Ovaj URL je označen prema broju korisnika",
		"BOOKMARKEDCOMMUNITY":"Ova zajednica je označena prema broju korisnika",
		"BOOKMARKEDPROFILE":"Ovaj profil je označen prema broju korisnika",
		"BOOKMARKEDBLOG":"Ovaj blog je označen prema broju korisnika",
		"COMMUNITYBLOG":"Ovo je blog unutar zajednice",
		"BOOKMARKEDACTIVITY":"Ova aktivnost je označena prema broju korisnika",
		"COMMUNITYACTIVITY":"Ovo je aktivnost unutar zajednice",
		"BOOKMARKEDFILE":"Ova datoteka je označena prema broju korisnika",
		"COMMUNITYFILE":"Ovo je datoteka unutar zajednice",
		"BOOKMARKED":"Ovaj wiki je označen prema broju korisnika",
		"COMMUNITYWIKI":"Ovo je wiki unutar zajednice",
		"BOOKMARKEDFORUM":"Ovaj forum je označen prema broju korisnika",
		"COMMUNITYFORUM":"Ovo je forum unutar zajednice",
		"ALLTAGANDTTILE":"Kliknite na ovaj gumb da vidite sve naslove i oznake za ovaj URL",
		"TAGS_ARE_FROM":"Ovaj rezultat pretraživanja može uključivati oznake iz:",
		"BOOKMARKS_TITLE":"Knjiške oznake",
		"COMMUNITIES_TITLE":"Zajednice",
		"ACTIVITIES_TITLE":"Aktivnosti",
		"HELP":"Pomoć",
		"MORESTATUSUPDATES":"Pregled više podudarnih ažuriranja statusa",
		"TITLE_PREFIX":"Naslov:",
		"LATEST_MESSAGE":"Zadnja poruka",
		"LATEST_STATUS_UPDATE":"Zadnje ažuriranje statusa",
		"LATEST_COMMUNITY_STATUS_UPDATE":"Zadnje ažuriranje statusa zajednice",
		"LATEST_COMMUNITIES_STATUS_UPDATE":"Zadnje ažuriranje statusa zajednice",
		"SEARCH_RESULTS":"Svi rezultati pretraživanja sadržaja",
		"ACTIVITIES_SEARCH_RESULTS":"Rezultati pretraživanja aktivnosti",
		"BLOGS_SEARCH_RESULTS":"Rezultati pretraživanja blogova",
		"BOOKMARKS_SEARCH_RESULTS":"Rezultati pretraživanja knjiških oznaka",
		"COMMUNITIES_SEARCH_RESULTS":"Rezultati pretraživanja zajednica",
		"FILES_SEARCH_RESULTS":"Rezultati pretraživanja datoteka",
		"FORUMS_SEARCH_RESULTS":"Rezultati pretraživanja foruma",
		"PROFILES_SEARCH_RESULTS":"Rezultati pretraživanja profila",
		"DIRECTORY_SEARCH_RESULTS":"${orgName} Rezultati pretraživanja direktorija",
		"WIKIS_SEARCH_RESULTS":"Rezultati pretraživanja wikija",
		"STATUS_UPDATES_SEARCH_RESULTS":"Rezultati pretraživanja ažuriranja statusa",
		"VIEW_ALL":"{span}Pregled svih{/span} ({0})",
		"MATCHING_ONE_OF":"Podudara se jedan od:",
		"MATCHING_ALL_OF":"Podudara se sve od:",
		"MATCHING":"Podudara se:",
		"MATCHING_DOC_TYPE":"Podudarni tip dokumenta:",
		"BOOKMARK_HELP":"Pomoć za knjišku oznaku",
		"CLOSE_BOOKMARK_HELP":"Zatvori pomoć za knjišku oznaku",
		"DOCUMENT_TYPE_PREFIX":"Tip dokumenta:",
		"LAST_PAGE_MESSAGE": "Uh, ovo je velik broj rezultata pretraživanja. Pokušajte suziti pretraživanje dodavanjem dodatnih pojmova pretraživanja.",
		"LAST_PAGE_SUBMESSAGE": "Prikazuje se prvih {resultNumber} relevantnih rezultata."
});

