/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Se necesita un título.",
	nourl: "Se necesita un URL.",
	fileSchema: "Si desea añadir un enlace de archivo remoto o local, deberá seguir uno de los formatos siguientes: file://vía_acceso_remota o file:///vía_acceso_local.",
	invalidUrl: "Este no es un URL de comunidad válido.",
	invalidTagChar: "La lista de etiquetas que ha introducido contiene el carácter no válido '&'.  Elimine este carácter de la lista de etiquetas.",
	txtHelp: "Ayuda",
	txtHelpTags: "Ayuda de etiquetas",
	txtHelpTagsClose: "Etiquetas Ayuda Cerrar",
	tagsall: "Todo",
	tagsyours: "Los suyos",
	tagsrecent: "Reciente: ",
	tagspopular: "Popular: ",
	tagsrecommended: "Recomendado: ",
	nothingselected: "Es necesario seleccionar una comunidad.",
	nothingselected_activity: "Es necesario seleccionar una actividad.",
	nothingselected_blogs: "Es necesario seleccionar un blog.",
	nothingselected_all: "No se ha seleccionado ningún servicio ni entrada, el marcador no se guardará.",
	nothingFeedselected: "No se ha seleccionado ningún servicio ni entrada, el canal de información no se guardará.",
	alertDialogTitle: "Mensaje",
	alertDialogOK: "Aceptar",
	expand: "Pulse aquí para expandir la sección",
	collapse: "Pulse aquí para contraer la sección",
	discussThis: "Debatir esto",
	by: "por:",
	posted: "Publicado:",
	attachments: "Archivos adjuntos",
	communityForum: "Foro de comunidad",
	notCommunityPage: "La página web actual no es una página web de comunidad válida. Puede introducir manualmente el título de la comunidad, un enlace y la descripción para crear una comunidad relacionada.",
	privateCommunityNotice: "Esta comunidad está restringida. Solo es visible para los miembros de la comunidad.",
	forumNameHint : "Escriba un nombre de foro",
	formDescriptionHint:"Describa el motivo de que esta comunidad relacionada le interese a su comunidad.",
	information : "Información",
	error : "Error",
	success : "Correcto",
	warning : "Aviso",
	informationColon : "Información:",
	successColon : "Correcto:",
	warningColon : "Aviso:",
	errorColon : "Error:",
	feedAlreadyExist : "El canal de información ya existe en la comunidad.",
	bookmarkAlreadyExist : "El marcador ya existe en la comunidad.",
	mentionAuthWarning:"Las personas que se mencionan a continuación no podrán ver el mensaje porque no son miembros de la comunidad:",
	mentionAuthForumWarning:"Las siguientes personas mencionadas no podrán ver el mensaje porque no tienen acceso a este foro:",
	exceedDescLength: "La descripción que ha especificado es demasiado larga.",
	communities_checked:"${0} comunidades seleccionadas",
	activities_checked:"${0} actividades seleccionadas",
	blogs_checked:"${0} blogs seleccionados"
})
