/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "És necessari un títol.",
	nourl: "És necessari un URL.",
	fileSchema: "Si voleu afegir un enllaç de fitxer remot o local, ha de tenir un dels formats següents: file://via_accés_remota o file:///via_accés_local.",
	invalidUrl: "Això no és un URL de comunitat vàlid.",
	invalidTagChar: "La llista d'etiquetes que heu especificat conté el caràcter no vàlid "&". Elimineu-lo de la llista d'etiquetes.",
	txtHelp: "Ajuda",
	txtHelpTags: "Ajuda d'etiqueta",
	txtHelpTagsClose: "Tanca l'ajuda d'etiquetes",
	tagsall: "Tot",
	tagsyours: "Vostres",
	tagsrecent: "Recent: ",
	tagspopular: "Popular: ",
	tagsrecommended: "Recomanat: ",
	nothingselected: "Es necessita una selecció de comunitat.",
	nothingselected_activity: "Es necessita una selecció d'activitat.",
	nothingselected_blogs: "Es necessita una selecció de blog.",
	nothingselected_all: "No s'ha seleccionat cap servei o entrada, l'adreça d'interès no es desarà.",
	nothingFeedselected: "No s'ha seleccionat cap servei o entrada, el canal d'informació no es desarà.",
	alertDialogTitle: "Missatge",
	alertDialogOK: "D'acord",
	expand: "Feu clic per ampliar aquesta secció",
	collapse: "Feu clic per reduir aquesta secció",
	discussThis: "Debatre sobre això",
	by: "per:",
	posted: "Publicat:",
	attachments: "Fitxers adjunts",
	communityForum: "Fòrum de comunitat",
	notCommunityPage: "La pàgina web actual no és una pàgina web de comunitat vàlida. Podeu introduir manualment el títol, l'enllaç i la descripció de la comunitat per crear una comunitat relacionada.",
	privateCommunityNotice: "Aquesta comunitat és restringida. Només és visible per als membres de la comunitat.",
	forumNameHint : "Escriviu un nom de fòrum",
	formDescriptionHint:"Descriviu perquè aquesta comunitat relacionada interessaria a la vostra comunitat.",
	information : "Informació",
	error : "Error",
	success : "Correcte",
	warning : "Advertiment",
	informationColon : "Informació:",
	successColon : "Correcte:",
	warningColon : "Advertiment:",
	errorColon : "Error:",
	feedAlreadyExist : "Ja existeix el canal d'informació a la comunitat.",
	bookmarkAlreadyExist : "Ja existeix l'adreça d'interès a la comunitat.",
	mentionAuthWarning:"Les persones que es mencionen a continuació no podran veure el missatge perquè no són membres de la comunitat:",
	mentionAuthForumWarning:"Les persones que es mencionen a continuació no podran veure el missatge perquè no poden accedir a aquest fòrum:",
	exceedDescLength: "La descripció és massa llarga.",
	communities_checked:"${0} comunitats seleccionades",
	activities_checked:"${0} activitats seleccionades",
	blogs_checked:"${0} blogs seleccionats"
})
