/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Naslov je obvezen.",
	nourl: "Url je obvezen.",
	fileSchema: "Če želite dodati povezavo na oddaljeno ali lokalno datoteko, mora ustrezati eni od naslednjih oblik zapisov: file://oddaljena_pot ali file:///lokalna_pot.",
	invalidUrl: "To ni veljaven URL skupnosti.",
	invalidTagChar: "Seznam oznak, ki ste ga vnesli, vsebuje neveljaven znak »&«. Odstranite ga s seznama oznak.",
	txtHelp: "Pomoč",
	txtHelpTags: "Pomoč za oznake",
	txtHelpTagsClose: "Zapri pomoč za oznake",
	tagsall: "Vse",
	tagsyours: "Vaše",
	tagsrecent: "Nedavne: ",
	tagspopular: "Popularne: ",
	tagsrecommended: "Priporočene: ",
	nothingselected: "Izbor skupnosti je obvezen.",
	nothingselected_activity: "Izbor dejavnosti je obvezen.",
	nothingselected_blogs: "Izbor bloga je obvezen.",
	nothingselected_all: "Izbrana ni nobena storitev ali vnos. Zaznamek ne bo shranjen.",
	nothingFeedselected: "Izbrana ni nobena storitev ali vnos. Vir ne bo shranjen.",
	alertDialogTitle: "Sporočilo",
	alertDialogOK: "V redu",
	expand: "Kliknite, da razširite ta razdelek",
	collapse: "Kliknite, da strnete ta razdelek",
	discussThis: "Razprava o tem",
	by: "Opravil:",
	posted: "Objavljeno:",
	attachments: "Priloge",
	communityForum: "Forum skupnosti",
	notCommunityPage: "Trenutna spletna strani ni veljavna spletna stran skupnosti. Če želite ustvariti sorodno skupnost, lahko ročno vnesete naslov in opis skupnosti ter povezavo nanjo.",
	privateCommunityNotice: "Ta skupnost je omejena. Vidna je samo članom skupnosti.",
	forumNameHint : "Vpišite ime foruma",
	formDescriptionHint:"Opišite, zakaj bi bila ta sorodna skupnost zanimiva za vašo skupnost.",
	information : "Informacije",
	error : "Napaka",
	success : "Uspeh",
	warning : "Opozorilo",
	informationColon : "Informacije:",
	successColon : "Uspešno:",
	warningColon : "Opozorilo:",
	errorColon : "Napaka:",
	feedAlreadyExist : "Vir že obstaja v skupnosti.",
	bookmarkAlreadyExist : "Zaznamek že obstaja v skupnosti.",
	mentionAuthWarning:"Naslednje omenjene osebe si ne bodo mogle ogledati sporočila, ker niso člani skupnosti:",
	mentionAuthForumWarning:"Naslednje omenjene osebe si ne bodo mogle ogledati sporočila, ker ne morejo dostopati do tega foruma:",
	exceedDescLength: "Vneseni opis je predolg.",
	communities_checked:"Št. izbranih skupnosti: ${0}",
	activities_checked:"Št. izbranih dejavnosti: ${0}",
	blogs_checked:"Št. izbranih blogov: ${0}"
})
