/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "Title is required.",
	nourl: "Url is required.",
	fileSchema: "If you want to add a remote or local file link it must conform with one of the following formats: file://remote_path or file:///local_path.",
	invalidUrl: "This is not a valid community URL.",
	invalidTagChar: "The tag list you entered contains invalid character '&'.  Please remove this character from the tag list.",
	txtHelp: "Help",
	txtHelpTags: "Tags Help",
	txtHelpTagsClose: "Tags Help Close",
	tagsall: "All",
	tagsyours: "Yours",
	tagsrecent: "Recent: ",
	tagspopular: "Popular: ",
	tagsrecommended: "Recommended: ",
	nothingselected: "A community selection is required.",
	nothingselected_activity: "An activity selection is required.",
	nothingselected_blogs: "A blog selection is required.",
	nothingselected_all: "No service or entry is selected, the bookmark will not be saved.",
	nothingFeedselected: "No service or entry is selected, the feed will not be saved.",
	alertDialogTitle: "Message",
	alertDialogOK: "OK",
	expand: "Click to expand this section",
	collapse: "Click to collapse this section",
	discussThis: "Discuss This",
	by: "by:",
	posted: "Posted:",
	attachments: "Attachments",
	communityForum: "Community Forum",
	notCommunityPage: "The current web page is not a valid community web page. You can manually input the community title, link and description to create a related community.",
	privateCommunityNotice: "This community is retricted. It is only visible to members of the community.",
	forumNameHint : "Type a forum name",
	formDescriptionHint:"Describe why this related community would interest your community.",
	information : "Information",
	error : "Error",
	success : "Success",
	warning : "Warning",
	informationColon : "Information:",
	successColon : "Success:",
	warningColon : "Warning:",
	errorColon : "Error:",
	feedAlreadyExist : "Feed already exists in the community.",
	bookmarkAlreadyExist : "Bookmark already exists in the community.",
	mentionAuthWarning:"The following people mentioned will not be able to view the message because they are not members of the community:",
	mentionAuthForumWarning:"The following people mentioned will not be able to view the message because they cannot access this forum:",
	exceedDescLength: "The description you entered is too long.",
	communities_checked:"${0} communities selected",
	activities_checked:"${0} activities selected",
	blogs_checked:"${0} blogs selected"
})
