/* Copyright IBM Corp. 2011, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
	"label.semtag.hover" : "Πατήστε εδώ για να δείτε την επαγγελματική κάρτα",
	"label.semtag.hover.alt" : "Πατήστε για να προβληθεί η επαγγελματική κάρτα για το χρήστη {0}",
	"label.semtag.hover.altA11Y" : "Πατήστε εδώ ή πατήστε Ctrl+Enter για να προβληθεί η επαγγελματική κάρτα",
	"label.personcard.dialog.title" : "Επαγγελματική κάρτα για το χρήστη {0}",

	"errorDefaultMsg2" : "Παρουσιάστηκε σφάλμα, επικοινωνήστε με το διαχειριστή του συστήματος",

	"loadingSTStatus" : "Φόρτωση κατάστασης Sametime...",
	"noStatuAvailable" : "Δεν υπάρχουν πληροφορίες για την κατάσταση Sametime",

	"label.personcard.cardnomarkup" : "Δεν ήταν δυνατή η ανάκτηση της επαγγελματικής κάρτας",
	"label.inactive.user.msg" : "Αυτό το πρόσωπο δεν είναι πια ενεργός χρήστης",
	"label.message.information" : "Πληροφορίες:",
	"label.personcard.noprofilemsg" : "Δεν υπάρχει προφίλ για αυτό το πρόσωπο",
	"label.personcard.cardreqexpired" : "Η αίτηση ανάκτησης της επαγγελματικής κάρτας έληξε",

	"label.bizcard.applinks.less" : "Εμφάνιση λιγότερων",
	"label.bizcard.applinks.more" : "Εμφάνιση περισσότερων",

	"label.personcard.activitieslink" : "Δραστηριότητες",
	"label.personcard.activitieslink.title" : "Πατήστε εδώ για να δείτε κοινόχρηστες δραστηριότητες",
	"label.personcard.blogslink" : "Ιστολόγια",
	"label.personcard.blogslink.title" : "Πατήστε εδώ για να δείτε το ιστολόγιο αυτού του προσώπου",
	"label.personcard.communitieslink" : "Κοινότητες",
	"label.personcard.communitieslink.title" : "Πατήστε εδώ για να προβληθούν οι κοινότητες στις οποίες ανήκει αυτό το πρόσωπο",
	"label.personcard.dogearlink" : "Σελιδοδείκτες",
	"label.personcard.dogearlink.title" : "Πατήστε εδώ για να δείτε τους σελιδοδείκτες αυτού του προσώπου",
	"label.personcard.fileslink" : "Αρχεία",
	"label.personcard.fileslink.title" : "Πατήστε εδώ για να δείτε τα κοινόχρηστα αρχεία αυτού του προσώπου",
	"label.personcard.forumlink" : "Φόρουμ",
	"label.personcard.forumlink.title" : "Πατήστε εδώ για να δείτε τις αναρτήσεις φόρουμ αυτού του προσώπου",
	"label.personcard.homepagelink" : "Αρχική σελίδα",
	"label.personcard.homepagelink.title" : "Πατήστε εδώ για να δείτε την αρχική σελίδα αυτού του προσώπου",
	"label.personcard.mobilelink" : "Κινητές συσκευές",
	"label.personcard.mobilelink.title" : "Πατήστε εδώ για να δείτε τη σελίδα κινητών συσκευών αυτού του προσώπου",
	"label.personcard.newslink" : "Ειδήσεις",
	"label.personcard.newslink.title" : "Πατήστε εδώ για να δείτε τις ειδήσεις αυτού του προσώπου",
	"label.personcard.profilelink" : "Προφίλ",
	"label.personcard.profilelink.title" : "Πατήστε εδώ για να προβληθεί το προφίλ αυτού του προσώπου",
	"label.personcard.quickrlink" : "Quickr",
	"label.personcard.quickrlink.title" : "Πατήστε εδώ για να δείτε τους κοινόχρηστους φακέλους αυτού του προσώπου στο Quickr",
	"label.personcard.wikislink" : "Wikis",
	"label.personcard.wikislink.title" : "Πατήστε εδώ για να δείτε τα wiki αυτού του προσώπου",

	"personCardMoreActions" : "Περισσότερες ενέργειες",
	"personCardMoreActionsAltText" : "Πατήστε για μενού ενεργειών",

	"label.bizcard.dismiss": "Πατήστε Εscape για να κλείσει η επαγγελματική κάρτα.",

	"personCardAddAsColleagues" : "Πρόσκληση στο δίκτυό μου",
	"personCardAddAsMyColleagues" : "Πρόσκληση στο δίκτυό μου",
	"personCardFollow" : "Παρακολούθηση",
	"personCardUnfollow" : "Τερματισμός παρακολούθησης",
	"personCardChat" : "Συνομιλία",
	"personCardCall" : "Κλήση",
	"personCardSendMail" : "Αποστολή e-mail",
	"personCardSendEMail" : "Αποστολή e-mail",
	"personCardProxyStatusAvailable" : "Είμαι διαθέσιμος",
	"personCardDownloadVCard" : "Μεταφόρτωση vCard",

	"friends" : "Δίκτυο",
	"friendsFullPageTitle" : "Δίκτυο",
	"friendsMenuTitleAllContacts" : "Όλες οι δικτυακές επαφές",
	"friendsMenuTitleMyContacts" : "Οι δικτυακές επαφές μου",
	"friendsInvitations" : "Προσκλήσεις",
	"friendsMenuTitleInCommon" : "Κοινά πρόσωπα",
	"friendsShowAllCommonFriends" : "Εμφάνιση όλων...",
	"friendsViewAllFriends" : "Προβολή όλων ({0})",
	"friendsSendFriendRequest" : "Αποστολή αίτησης",
	"friendsNoFriends" : "Δεν αντιστοιχούν δικτυακές επαφές σε αυτό το προφίλ",
	"friendsColleaguesInvite" : "Πρόσκληση του χρήστη {0} για συμμετοχή στο δίκτυό σας",
	"friendsColleaguesFor" : "Δικτυακές επαφές του χρήστη {0}",
	"friendsNewInv" : "{0} νέα πρόσκληση",
	"friendsNewInvs" : "{0} νέες προσκλήσεις",
	"friendsLoading" : "Φόρτωση δικτύου...",
	"friendsLoadingInv" : "Φόρτωση προσκλήσεων...",
	"friendsSelectFriendForRemoval" : "Επιλέξτε πρώτα τις επαφές που θέλετε να αφαιρέσετε από το δίκτυό σας.",
	"friendsRemoved" : "Αφαιρέθηκαν μία ή περισσότερες δικτυακές επαφές.",
	"friendsInvSent" : "Δεν εστάλη πρόσκληση γιατί ήδη εκκρεμεί πρόσκληση.",
	"friendsRemovedSelected" : "Αφαίρεση από το δίκτυό μου",
	"friendsSortByDisplayName" : "Εμφανιζόμενο όνομα",
	"friendsSortByRecent" : "Ημερομηνία",
	"friendsTelephone" : "Τηλέφωνο:",
	"friendsEmail" : "Διεύθυνση e-mail:",
	"friendsAltEmail" : "Εναλλακτική διεύθυνση e-mail:",
	"friendsNewInvitationsCount" : "Έχετε {0} νέες προσκλήσεις",
	"friendsNoInv" : "Δεν υπάρχουν προσκλήσεις",
	"friendsInCommonSingle" : "Έχετε {0} κοινή δικτυακή επαφή",
	"friendsInCommonMulti" : "Έχετε {0} κοινές δικτυακές επαφές",
	"friendsIncludeMsgForInv" : "Συμπεριλάβετε ένα μήνυμα στην πρόσκλησή σας:",
	"friendsInitialMsgForInv" : "Θα ήθελα να σας προσθέσω στη λίστα των δικτυακών επαφών μου στο Connections.",
	"friendsSendInvAction" : "Αποστολή πρόσκλησης",
	"friendsCancelInvAction" : "Ακύρωση",
	"friendsAcceptAction" : "Αποδοχή",
	"friendsIgnoreAction" : "Αγνόηση",
	"friendsYouExceedTextLimit" : "Το μήνυμα πρόσκλησης είναι πολύ μεγάλο. Δεν επιτρέπεται να υπερβαίνει τους {1} χαρακτήρες. Έχετε καταχωρήσει {0} χαρακτήρες σε αυτό το πεδίο.",
	"friendsCannotAddYourself" : "Δεν μπορείτε να προσθέσετε τον εαυτό σας ως δικτυακή επαφή.",
	"friendsIsYourColleague" : "Ο χρήστης {0} είναι επαφή στο δίκτυό σας",
	"friendsRecentlyAdded" : "Πρόσωπα που προσθέσατε πρόσφατα στο δίκτυό σας.",
	"friendsDate" : "Ημερομηνία",
	"friendsCollapseWidget" : "Πατήστε για να συμπτύξετε την ενότητα δικτύου.",
	"friendsExpandWidget" : "Πατήστε για να αναπτύξετε την ενότητα δικτύου.",
	"friendsIsInYourNetwork" : "Ο χρήστης {0} έχει συνδεθεί στο δίκτυό σας.",
	"friendsActionsFor" : "Ενέργειες για το δίκτυο",
	"friendsInviteFollowError" : "Παρουσιάστηκε σφάλμα κατά την προσπάθεια παρακολούθησης του στοιχείου {0}.",
	"friendsInviteTagError" : "Παρουσιάστηκε σφάλμα κατά την προσπάθεια προσθήκης προσδιοριστικού στο στοιχείο {0}.",
	"friendsPleaseLogIn" : "Πρέπει να συνδεθείτε προκειμένου να προσκαλέσετε πρόσωπα στο δίκτυό σας",
	// {0} - person name from profile
	"friendsPersonAlreadyInYourNetwork" : "Δεν μπορείτε να προσκαλέσετε το χρήστη {0} στο δίκτυό σας γιατί ανήκει ήδη σε αυτό.",
	"friendsInviteAddTagsFor" : "Προσθήκη προσδιοριστικών για {0}:",
	"friendsInviteAlsoFollow" : "Επίσης παρακολούθηση",
	"friendsInviteReceiveUpdates" : "(λήψη ενημερώσεων)",
	"friendsInviteUpdatesDescription" : "Οι ενημερωμένες πληροφορίες σχετικά με τα πρόσωπα που παρακολουθείτε θα αποστέλλονται στην αρχική σελίδα σας και σε ένα συνοπτικό e-mail.",
	"friendsInviteFollowHelp": "Για περισσότερες πληροφορίες, βλ. {0}Παρακολούθηση προσώπων{1}.",
	"friendsNetwork" : "Δίκτυο",
	"friendsMyNetwork" : "Δίκτυο",
	"friendsNetworkFor" : "Δίκτυο για το χρήστη {0}",
	"friendsRemoveSelected" : "Αφαίρεση επιλεγμένων",
	"friendsRemoveSelectedTip" : "Πατήστε για να αφαιρέσετε τα επιλεγμένα πρόσωπα από το δίκτυό σας.",
	"friendsNetworkInCommon" : "Έχετε {0} κοινές συνδέσεις δικτύου.",
	"friendsAddToMyNetwork" : "Θα ήθελα να σας προσθέσω στο δίκτυό μου στο Connections.",
	"friendsInvite" : "Πρόσκληση στο δίκτυό μου",
	"friendsInvitePerson" : "Πρόσκληση του χρήστη {0} στο δίκτυό σας",
	"friendsInviteMessage" : "Θα ήθελα να σας προσθέσω στο δίκτυό μου στο Connections.",
	"friendsInvitedEmailSubject" : "[Προφίλ] Σας προσκαλώ να γίνετε μέλος στο δίκτυό μου",
	"friendsInvitedEmailMsg1" : "σας προσκάλεσε στο δίκτυό του. Η πρόσκληση περιέχει το ακόλουθο μήνυμα:",
	"friendsInvitedEmailMsg2" : "Άνοιγμα της σελίδας πρόσκλησης σε δίκτυο",
	"friendsInvitedEmailMsg3" : "Θα ήθελα να σας προσθέσω στο δίκτυό μου.",
	"friendsInvitedEmailMsg4" : "Ο χρήστης {0} σας προσκάλεσε στο δίκτυό του:",
	"friendsInvitedEmailMsg5" : "Ο χρήστης {0} σας προσκάλεσε στο δίκτυό του. Η πρόσκληση περιέχει το ακόλουθο μήνυμα:",
	"friendsInviteLegalNote" : "Αποστέλλοντας αυτή την πρόσκληση, συμφωνείτε ότι επιτρέπετε στο χρήστη {0} να προσθέσει σχόλια στον πίνακα του προφίλ σας.",
	"friendsInviteFailed" : "Εξαιτίας κάποιου σφάλματος στον εξυπηρετητή, δεν εστάλη ειδοποίηση μέσω e-mail στον προσκεκλημένο. Ωστόσο, ο προσκεκλημένος θα έχει τη δυνατότητα να αποδεχθεί την πρόσκλησή σας χρησιμοποιώντας τη διαδικτυακή εφαρμογή Προφίλ."
})

