define({
	/* *************************************************************** */
	/*                                                                 */
	/* HCL Confidential                                                */
	/*                                                                 */
	/* OCO Source Materials                                            */
	/*                                                                 */
	/* Copyright HCL Technologies Limited 2008, 2019                   */
	/*                                                                 */
	/* The source code for this program is not published or otherwise  */
	/* divested of its trade secrets, irrespective of what has been    */
	/* deposited with the U.S. Copyright Office.                       */
	/*                                                                 */
	/* *************************************************************** */
  // NLS_CHARSET=UTF-8
		   'rs_close' : "Tutup",
		   'rs_loading' : "Memuat...",
		   'rs_at' : "di",
		   'rs_searchDirectory' : "Orang tidak terdaftar? Gunakan pencarian penuh...",
		   'rs_searchGroupDirectory' : "Grup tidak terdaftar? Gunakan pencarian penuh...",
		   'rs_searchPersonAndGroupDirectory' : "Orang atau grup tidak terdaftar? Gunakan pencarian penuh...",
		   'rs_searchCommunityDirectory' : "Komunitas tidak terdaftar? Gunakan pencarian penuh...",
		   'rs_shadowText_searchDirectory' : "Ketik untuk menemukan orang",
		   'rs_shadowText_searchGroupDirectory' : "Ketik untuk mencari grup",
		   'rs_shadowText_searchPersonAndGroupDirectory' : "Ketik untuk menemukan orang atau grup",
		   'rs_shadowText_searchCommunityDirectory' : "Ketik untuk mencari komunitas",
		   'rs_listItem' : "Item Daftar",
		   'rs_noResults' : "Tidak ada hasil untuk '${0}'",
		   'rs_today' : "Hari ini",
		   'rs_tomorrow' : "Besok",
		   'rs_yesterday' : "Kemarin",
		   /* Activity List Widget */
		   'rs_activityFeedLink' : "Umpan untuk aktivitas ini",
		   'rs_externalText' : "Aktivitas ini dapat memiliki anggota-anggota dari luar organisasi Anda.",
		   'rs_moveActivitySuccess' : '\"${activityTitle}\" telah berhasil dipindahkan ke \"${destCommName}\" sub komunitas.',
		   // copy 'rs_moreInfo' and 'rs_hideInfo' from activity's strings.js
		   'rs_moreInfo' : 'Tampilkan lebih banyak informasi mengenai Aktivitas ini',
		   'rs_hideInfo' : 'Sembunyikan informasi kustom',
		   'rs_more' : "Lebih Banyak",
		   'rs_hide' : "Sembunyikan",
		   'rs_edit' : "Ubah",
		   'rs_restore' : "Pulihkan",
		   'rs_deleteEntry' : "Delete",
		   'rs_prioritize' : "Memprioritaskan",
		   'rs_markComplete' : "Tandai sebagai Selesai",
		   'rs_markIncomplete' : "Pulihkan",
		   'rs_linkMore' : "... [lebih]",
		   'rs_linkLess' : "... [less]",
		   'rs_actUpdatedByDate' : "Diperbarui oleh ${0} ${1}",// Updated by (author name) (date)
		   'rs_actUpdatedBy' : "Diperbarui oleh ${0}",// Updated by (author name)
		   'rs_actDue' : "Tanggal Tenggat ${0}",// Due (date)
		   'rs_actTags' : "Label: ",
		   'rs_actTagsDelim' : ", ",
		   'rs_startFromTemplate' : "Mulai Aktivitas dari Templat ini",
		   'rs_favoriteTemplate' : "Tandai sebagai Templat Favorit",
		   'rs_normalTemplate' : "Tandai sebagai templat normal",
		   'rs_tunedOutPri' : "Diabaikan",
		   'rs_pagepos' : "${0} - ${1} of ${2}", // pagination - e.g. 1 - 10 of 100
		   'rs_navPrevLabel' : "Sebelumnya",
		   'rs_navNextLabel' : "Berikutnya",
		   'rs_noActivities' : "Tidak ada aktivitas yang dimulai untuk komunitas ini.",
		   'rs_feedError' : "Gagal memuat umpan.",
		   'rs_highPri' : "Prioritas Tinggi",
		   'rs_medPri' : "Prioritas Sedang",
		   'rs_normalPri' : "Prioritas Normal (Standar)",
		   'rs_tuneOut' : "Tandai sebagai Diabaikan",
		   'rs_startActivity' : "Mulai Aktivitas",
		   'rs_startFirstActivity' : "Buat Aktivitas Pertama Anda",
		   'rs_navNextLabel' : "Berikutnya",
		   'rs_viewAll' : "Tampilkan Semua",
		   'rs_activityWidgetTitle' : "Aktivitas",
		   'rs_activityWidgetBriefDescription' : "Telusuri tujuan komunitas.  Buat daftar tugas dan bagi sumber.",
		   'rs_activityWidgetDescription' : "Aktivitas komunitas dapat digunakan untuk berkolaborasi dan menelusuri perkembangan proyek atau inisiatif komunitas.",
		   'rs_completedActivityLink' : "Tampilkan Aktivitas yang diselelesaikan",
		   'rs_activitiesUnavailable' : "Layanan Aktivitas tidak tersedia.",
		   'rs_errorPersists' : "Jika masalah berlanjut, harap hubungi administrator sistem Anda.",
		   'rs_shared' : "Dibagi",
		   'rs_removeActFromComm' : "Hapus dari komunitas",
		   'rs_externalLabel' : "Eksternal",
		   // for ActivityForm
		   'rs_templateOptions' : "Pilihan Templat",
		   'rs_template' : "Templat",
		   'rs_tagsLabel' : "Tanda",
		   'rs_peopleLabel' : "Orang",
		   'rs_aboutThisTemplate' : "Tentang Templat ini",
		   'rs_activity' : "Aktivitas",
		   'rs_copyOf' : "Salinan dari ${0}",// copy of (activity name)
		   'rs_activityFormGoal' : "Tujuan Aktivitas",
		   'rs_noTemplate' : "Tidak ada",
		   'rs_copyActivityMembers' : "Gunakan anggota dari aktivitas",
		   'rs_copyTemplateMembers' : "Gunakan anggota dari templat",
		   /* Forum Widget */
		   'rs_noTopics' : "Belum ada topik untuk komunitas ini.",
		   'rs_noTopicsLoggedIn' : "Menanyakan pertanyaan, berdiskusi, atau sekedar membagikan ide Anda.",
		   'rs_postedBy' : "Publikasi terakhir oleh",
		   'rs_topics' : "topik",
		   'rs_noTopicsShort' : "Tidak ada topik",
		   'rs_topic' : "topik",
		   'rs_replies' : "balasan",
		   'rs_noReplies' : "Tidak ada balasan",
		   'rs_reply' : "balas",
		   'rs_startTopic' : "Memulai Topik",
		   'rs_startFirstTopic' : "Mulai Topik Pertama",
		   'rs_ok' : "Ya",
		   'rs_locked' : "[Locked]",
		   'rs_manageForumSetting' : "Mengelola Pengaturan Forum",
		   'rs_forumSettingCommunityOverviewPage' : "Halaman Ikhtisar Komunitas:",
		   'rs_defaultForumList' : "Tunjukkan daftar forum standar",
		   'rs_defaultTopicList' : "Tunjukkan daftar topik standar",
		   'rs_forumSettingApplicationView' : "Tampilan aplikasi forum standar:",
		   'rs_forumSettingNote' : "Catatan: Topik ditampilkan oleh pengaturan standar jika hanya ada satu forum.",
		   'rs_forumSettingSubmit' : "Ajukan",
		   'rs_forumSettingSave' : "Simpan",
		   'rs_forumSettingSaveAndClose' : "Simpan dan Tutup",
		   'rs_forumSettingConfirm' : "Perubahan Anda untuk Forum sudah disimpan.",
		   'rs_forumSettingError' : "Kesalahan terjadi. Harap hubungi administrator Anda.",
		   'rs_formSettingHideMessage' : "Sembunyikan pesan",
		   'rs_forumSettingCancel' : "Batal",
		   'rs_forumAnsweredQuestion' : "Pertanyaan yang sudah dijawab",
		   'rs_forumUnAnsweredQuestion' : "Pertanyaan yang belum dijawab",
		   'rs_forumSortBy' : "Urutkan menurut:",
		   'rs_forumSortByDate' : "Tanggal",
		   'rs_forumSortByReplies' : "Balasan",
		   'rs_forumSortByTopic' : "Topik",
		   'rs_forumSortByTopicsAndReplies' : "Topik dan Balasan",
		   'rs_sortByReplies' : "Sortir Menurut Balasan",
		   'rs_sortbyTopicsAndReplies' : "Sortir Menurut Topik dan Balasan",
		   'rs_forumOpenQuestions' : "Pertanyaan Terbuka",
		   'rs_feedOpenQuestions' : "Umpan untuk pertanyaan terbuka ini",
		   'rs_feedAnsweredQuestions' : "Umpan untuk pertanyaan yang sudah dijawab ini",
		   'rs_forumMessages' : "${0} Pesan",
		   'rs_forumLastAddedPost' : "Publikasi terakhir oleh ${0}",
		   'rs_forumTopics' : "${0} topik",
		   /* End discussion forum */
		   /* Editor plugins -- some for a possible one we haven't implemented yet */
		   'rs_createPersonLink' : "Buat Tautan Orang",
		   'rs_quote' : "Kutipan",
		   'rs_labelColon' : "Tanda: ",
		   'rs_personColon' : "Orang: ",
		   'rs_personLink' : "Tautan Orang",
		   'rs_replace' : "Ganti",
		   'rs_inactivePerson' : "${0} (tidak aktif)", // person's name (inactive)
		   'rs_PersonPicture' : "Gambar ${0}", // person name's picture
		   /*Visitor mode -- external user name decoration use cases */
		   'rs_PersonExternalLabel' : "Pengguna Eksternal", // A label for the visitor model use cases.
		   'rs_PersonExternal' : "${0} (Pengguna Eksternal)", //'{0}' is the person's name. This will be used for the user profile name and profile photo tooltip
		   'rs_PersonPictureExternal' : "Gambar milik ${0} (Pengguna Eksternal)", // Alt text for the external user's profile photo
		   'rs_personExternalDesc' : "Pengguna ini memiliki akses ke File dan Komunitas yang dibagikan secara eksternal.",
		   /* End editor plugins */
		   /* Notification Form */
		   'rs_notifyOthers' : "Beritahukan orang lain",
		   'rs_messageColon' : "Pesan: ",
		   'rs_notifyColon' : "Memberitahukan: ",
		   'rs_notificationConfirm' : "Pesan notifikasi berhasil dikirim. ",
		   'rs_notificationFail' : "Pesan notifikasi tidak terkirim. Coba lagi nanti dan hubungi administrator sistem Anda jika masalah terus berlanjut.",
		   'rs_pickCommunity' : "Pilih dari Daftar Komunitas",
		   'rs_typeName' : "Ketik Nama",
		   'rs_typeToFilter' : "Ketik untuk memfilter daftar ini",
		   /* End Notification Form */
		   /* FilteringCheckbox */
		   'rs_filterListPrompt' : "Ketik untuk memfilter daftar ini",
		   'rs_filterGroupLabel' : "Pilih Grup",
		   'rs_noResults' : "Tidak ada hasil ditemukan",
		   // ${0} will be replaced with a number
		   'rs_numResults' : "Menampilkan ${0} hasil dari ${1}",
		   /* PeopleFilterList */
		   'rs_removeFilter' : "Hapus",
		   /* Language Selector */
		   'rs_browser_setting' : "Pengaturan Browser",
		   'rs_customLangaugeLinkLabel' : "Bahasa Kustom",
		   /* Paging controls */
		   // 0 and 1 are page numbers
		   'rs_jumpPage' : "Pindah ke halaman ${0} dari ${1}",
		   "rs_jumpPageLabel" : "Pindah ke halaman",
		   'rs_pageNumLabel' : "Jumlah Halaman",
		   'rs_pageLabel' : "Halaman:",
		   /* Common Tags Widget */
		   'rs_tagCloudNavigationLabel' : 'Tanda',
		   'rs_tagCloudToggleHint' : "Klik untuk menyembunyikan atau menampilkan",
		   'rs_tagCloudHelpAlt' : "Dapatkan bantuan dengan tanda",
		   'rs_tagCloudNoTags' : "Belum ada label",
		   'rs_tagCloudNoRecentTags' : "Tidak ada tanda terbaru",
		   'rs_tagCloudNoTagsProfiles' : "Cari direktori. Tanda yang berkaitan dengan profil yang dikembalikan oleh pencarian akan ditampilkan di sini.",
		   'rs_tagLoadingTags' : "Memuat Konten",
		   'rs_tagCloudSelectedTags' : "Tanda yang Dipilih",
		   'rs_tagCloudSeachDesc' : "Cari Tanda",
		   'rs_tagCloudSeach' : "Cari",
		   'rs_tagCloudRelatedTags' : "Tanda Terkait",
		   'rs_tagCloudRelatedTagsDescription' : "Tambahkan tanda terkait untuk lebih mempersempit pencarian Anda",
		   'rs_tagCloudError' : 'Terdapat kesalahan',
		   'rs_viewAsCloud' : "Cloud",
		   'rs_viewAsCloudTitle' : "Daftarkan tanda sebagai cloud tanda",
		   'rs_viewAsCloudDescription' : "Tampilkan tanda sebagai cloud tanda",
		   'rs_viewAsList' : "Daftar",
		   'rs_viewAsListTitle' : "Daftarkan tanda sebagai daftar tanda yang berurutan",
		   'rs_viewAsListDescription' : "Tampilkan tanda sebagai daftar tanda yang berurutan",
		   'rs_tagCloudViewAll' : "Cari",
		   'rs_tagCloudViewAllTitle' : "Cari semua tanda",
		   'rs_normalTags' : "Tanda Aktif",
		   'rs_removeTag' : "Hapus tanda dari tanda filter yang dipilih",
		   'rs_clearAll' : "Hapus semua",
		   'rs_searchInputDefault' : "Ketik untuk mencari tanda",
		   'rs_searchInputTagSelected' : "Ketik tanda lain",
		   'rs_relatedTagTitle' : "Tampilkan hasil pencarian tanda ${0}, hitungan ${1}",
		   'rs_removeTagTitle' : "Hilangkan tanda ${0} dari tanda filter yang dipilih",
		   'rs_addTagTitle' : "Filter menurut tanda ${0} dengan hitungan ${1}",
		   'rs_tagDialogCloseTile' : "Tutup",
		   'rs_tagDialogTitle' : "Semua Tanda",
		   'rs_tagDialogPageInfo' : "${0} - ${1} dari ${2} tanda",
		   /* Group Selection (Picker) Widget */
		   'rs_group_browse_groups' : "Jelajah Grup",
		   'rs_group_browse_groups_dialog_title' : "Jelajah Grup",
		   'rs_group_browse_find_groups' : "Cari Grup",
		   'rs_group_browse_add_button' : "Tambah",
		   'rs_group_browse_cancel_button' : "Batal",
		   'rs_group_browse_enter_string' : "Ketik untuk mencari grup",
		   'rs_group_browse_group_typeahead_label' : "Ketik nama grup:",
		   'rs_group_browse_group_name' : "Nama grup:",
		   'rs_group_browse_results_label' : "Pilih grup yang cocok:",
		   'rs_group_browse_parent_group_label' : "Anda sedang berada:",
		   'rs_group_browse_next_page' : "Halaman Berikutnya",
		   'rs_group_browse_previous' : "Sebelumnya",
		   'rs_group_browse_next' : "Berikutnya",
		   'rs_group_browse_paging' : "Penomoran Halaman",
		   'rs_group_browse_previous_page' : "Halaman Sebelumnya",
		   'rs_group_browse_group_selected' : "Grup yang Dipilih:",
		   'rs_group_browse_group_no_groups' : "Grup ini tidak memiliki grup apa pun",
		   'rs_group_browse_page_info' : "${0} - ${1} of ${2}",
		   'rs_group_browse_page_info_alt' : "Grup yang cocok ${0} melalui ${1} dari ${2}",
		   'rs_group_browse_remove_selection' : 'Hapus pilihan grup yang bertumpuk: ${0}',
		   'rs_group_browse_paging' : "Penomoran Halaman",
		   'rs_member_groups' : "Grup",
		   'rs_member_members' : "Anggota",
		   'rs_member_no_results' : "Tidak ada hasil ditemukan",
		   'rs_member_remove_group' : "Hapus ${0}",
		   'rs_member_add_to_community' : "Klik untuk menambahkan anggota",
		   'rs_member_remove_name' : "Klik untuk menghapus anggota",
		   'rs_group_add_to_community' : "Klik untuk menambahkan grup",
		   'rs_group_remove_name' : "Klik untuk menghapus grup",
		   'rs_group_name' : "Nama Kelompok",
		   'rs_group_role' : "Peran Grup",
		   'rs_warning' : "Peringatan",
		   'rs_a11y_warning' : "Peringatan:",
		   'rs_messagebox_close_btn_title' : "Tutup",
		   'rs_messagebox_close_btn_alt' : "Tutup",
		   'rs_messagebox_error_icon_alt' : "Salah",
		   'rs_messagebox_error_a11y_label' : "Kesalahan:",
		   'rs_messagebox_warning_icon_alt' : "Peringatan",
		   'rs_messagebox_warning_a11y_label' : "Peringatan:",
		   'rs_messagebox_info_icon_alt' : "Informasi",
		   'rs_messagebox_info_a11y_label' : "Informasi:",
		   'rs_messagebox_success_icon_alt' : "Berhasil",
		   'rs_messagebox_success_a11y_label' : "Berhasil:",
		   /* Document Picker CK Plugin */
		   'rs_docpicker_title' : "Masukkan Tautan ke File",
		   'rs_docpicker_label' : "Tautan ke File",
		   // '{0}' is a filename
		   'rs_docpicker_download_title' : "Unduh ${0}",
		   'rs_docpicker_viewdetails_text' : "Lihat Detail",
		   // '{0}' is a filename
		   'rs_docpicker_viewdetails_title' : "Lihat detail dari ${0}",
		   /* AttachedFileList widget */
		   'rs_attachedfile_remove_alt' : "Hapus",
		   'rs_attachedfile_filename' : "Gambar ${0}",
		   'rs_feedreader_warning' : "Peringatan: Tautan ini dimaksudkan untuk pembaca umpan dan dapat ditampilkan tidak benar di browser Anda. Klik OK untuk melanjutkan, atau Batal untuk kembali ke halaman.",
		   'rs_search' : "Cari",
		   'rs_all_connections' : "Semua koneksi",
		   'rs_advanced' : "Lanjutan",
		   'rs_select_scope' : "Pilih cakupan pencarian",
		   'rs_icfixlayout' : {
		      button_label : "Format Ulang",
		      dialog_title : "Format Ulang Konten",
		      warning : "Peringatan",
		      reformat_save : "Format Ulang dan Simpan",
		      save_as_is : "Simpan sebagaimana adanya",
		      cancel : "Batal",
		      warn_layout : "Konten Anda melebihi lebar tampilan maksimum.  Apakah Anda ingin memformat kembali secara otomatis agar sesuai dengan ruang yang tersedia?",
		      remember_decision : "Ingat keputusan saya"
		   },
		   //The following error messages are used by icdocpicker when private files are shared with a Community.
		   'rs_sharefile_constraint_violation' : "Terjadi kesalahan saat sedang membagi file yang dipilih.",
		   'rs_sharefile_access_denied' : "File ini telah dihapus atau tidak lagi dibagi dengan Anda.",
		   'rs_sharefile_invalid_request' : "Terjadi kesalahan saat sedang membagi file yang dipilih.",
		   'rs_sharefile_sharing_intent_restriction' : "File hanya dapat dibagi di dalam organisasi Anda.",
		   'rs_sharefile_error_title' : "Salah",
		   /* Strings for the native mobile app banners */
		   'rs_mobileBanner_title' : 'HCL Connections',
		   'rs_mobileBanner_inAppStore' : 'Di App Store',
		   'rs_mobileBanner_inGooglePlay' : 'Di Google Play',
		   'rs_mobileBanner_author' : 'HCL Software',
		   'rs_mobileBanner_open' : 'Terbuka',
		   'rs_mobileBanner_view' : 'Lihat',
		   'rs_mobileBanner_hide' : 'Sembunyikan',

		   'rs_empty_column_placeholder' : 'Seret aplikasi ke sini.',
		   'rs_widget_loading_error_title' : 'Tidak dapat menampilkan widget',
		   'rs_widget_loading_error_message' : 'Coba lagi nanti dan hubungi administrator sistem Anda jika masalah terus berlanjut.',
		   'rs_widgets_loading_error_title' : 'Tidak dapat menanmpilkan widget(-widget) dalam komunitas ini',
		   'rs_widget_misplacement_warning' : 'Aplikasi ini tidak cukup di dalam kolom ini. Pemilik komunitas dapat memindahkannya ke kolom lain atau menghapusnya dari halaman.',

		   'rs_widget_title_change_fail_message' : {
		      title_too_long : 'Judul yang Anda masukkan terlalu panjang.',
		      empty_new_title : 'Judul yang Anda masukkan tidak boleh kosong.',
		      default_message : 'Tidak dapat mengganti judul untuk ${0} aplikasi ini.'
		   },

		   /* Strings for change title dialog */
		   'rs_widget_title_change_label' : 'Judul:  ',
		   'rs_widget_title_change_direction' : 'Ganti judul untuk ${0} aplikasi ini.',
		   'rs_widget_title_change_title' : 'Ganti Judul',
		   /* Strings for Visitor Model Invite dialog */
		   'rs_vmmainContentTitle' : "Undang atau Tambahkan Anggota",
		   'rs_vmmainContentDesc' : "Undang anggota untuk memberikan kesempatan kepada mereka untuk bergabung dalam komunitas. Tambahkan anggota agar secara otomatis menyertakan mereka.",
		   'rs_vmtypeAheadLabel' : "Nama atau Email: ",
		   'rs_vmgroupTypeAheadLabel' : "Nama: ",
		   'rs_vmtypeAheadRoleLabel' : " sebagai ",
		   'rs_vmgroupTypeAheadRoleLabel' : " sebagai Anggota ",
		   'rs_vmtaNoResults' : "Tidak Ada Hasil yang ditemukan.",
		   'rs_vmtaHeader' : "header",
		   'rs_vmaddUser' : "Tambah",
		   'rs_vmradioSectionTitle' : "Opsi Anggota:",
		   'rs_vmradioOne' : "Kirim undangan untuk bergabung dengan komunitas",
		   'rs_vmradioTwo' : "Secara otomatis menambahkan pengguna ke komunitas",
		   'rs_vmtwistyA' : "Tambahkan Pesan Opsional",
		   'rs_vmtwistyB' : "Hapus pesan tambahan",
		   'rs_vmmessage' : "Pesan:",
		   'rs_vmtextAreaStartText' : "Katakan sesuatu...",
		   'rs_vmcheckboxLabel' : "Kirimkan salinan kepada saya",
		   'rs_vmsave' : "Simpan",
		   'rs_vminvite' : "Undang",
		   'rs_vmcancel' : "Batal",
		   'rs_userContentTitle' : "Masukkan Informasi",
		   'rs_vmaddUser' : "Buat Pengguna",
		   'rs_vmback'	 : "Sebelumnya",
		   'rs_vmvisitor'	 : "Pengunjung",
			/* Strings for Communities picker */
			'rs_commpicker_logo_alt' : 'Klik di sini untuk menyalin komunitas ini',
			'rs_commpicker' : ''

});
