/* Copyright HCL Technologies Limited 2008, 2010  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({	
	notitle: "需要標題。",
	nourl: "需要 URL。",
	fileSchema: "如果您想新增遠端或本端檔案，則必須符合下列其中一個格式：file://remote_path 或 file:///local_path。",
	invalidUrl: "這不是有效的社群 URL。",
	invalidTagChar: "您輸入的標籤清單包含無效的字元「&」。請從標籤清單中移除這個字元。",
	txtHelp: "說明",
	txtHelpTags: "標籤說明",
	txtHelpTagsClose: "標籤說明已關閉",
	tagsall: "全部",
	tagsyours: "您的",
	tagsrecent: "最近的： ",
	tagspopular: "熱門： ",
	tagsrecommended: "建議的： ",
	nothingselected: "需要選擇社群。",
	nothingselected_activity: "需要選擇活動。",
	nothingselected_blogs: "需要選擇部落格。",
	nothingselected_all: "尚未選取服務或項目，將不會儲存書籤。",
	nothingFeedselected: "尚未選取服務或項目，將不會儲存資訊來源。",
	alertDialogTitle: "訊息",
	alertDialogOK: "確定",
	expand: "按一下以展開此區段",
	collapse: "按一下以收合此區段",
	discussThis: "討論此內容",
	by: "作者：",
	posted: "張貼：",
	attachments: "附件",
	communityForum: "社群討論區",
	notCommunityPage: "現行網頁不是有效的社群網頁。 您可以手動輸入社群標題、鏈結及說明來建立相關的社群。",
	privateCommunityNotice: "此社群是受限社群。只有社群成員才能看到此社群。",
	forumNameHint : "輸入討論區名稱",
	formDescriptionHint:"說明您的社群為何會對這個相關社群有興趣。",
	information : "資訊",
	error : "錯誤",
	success : "順利完成",
	warning : "警告",
	informationColon : "資訊：",
	successColon : "成功：",
	warningColon : "警告：",
	errorColon : "錯誤：",
	feedAlreadyExist : "社群中已有此資訊來源。",
	bookmarkAlreadyExist : "社群中已有此書籤。",
	mentionAuthWarning:"下列提及的人員不是社群的成員，所以無法檢視此訊息：",
	mentionAuthForumWarning:"下列提及的人員將無法檢視訊息，因為他們不能存取此討論區：",
	exceedDescLength: "您輸入的說明太長。",
	communities_checked:"已選取 ${0} 個社群",
	activities_checked:"已選取 ${0} 個活動",
	blogs_checked:"已選取 ${0} 個部落格"
})
