/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
({
"FILTERBY":"Iragazi honen arabera:",
"SHOW":"Erakutsi:",
"ACL_FILTER_LABEL":"Iragazi ikusgaitasunaren arabera",
"PARENT_FILTER_LABEL":"Iragazi edukitzailearen arabera",
"TYPE_FILTER_LABEL":"Iragazi motaren arabera",
"PAGING_TOP":"Lehen orrialdekatzea",
"PAGING_BOTTOM":"Bigarren orrialdekatzea",
"PREVIOUS":"Aurrekoa",
"NEXT":"Hurrengoa",
"PAGE":"{1} orritatik {0}",
"PAGE_COLON":"Orria:",
"RESULTS":"{span}{0}-{1}{/span} {2}(e)tik",
"ITEMS":"{0} elementu",
/* Application names */
"ACTIVITIES":"Jarduerak",
"BLOGS":"Blogak",
"CALENDAR":"Egutegia",
"COMMUNITIES":"Komunitateak",
"BOOKMARKS":"Laster-markak",
"DOGEAR":"Laster-markak",
"EVENTS":"Gertaerak",
"FILES":"Fitxategiak",
"FORUMS":"Foroak",
"PROFILES":"Profilak",
"WIKI":"Wikiak",
"WIKIS":"Wikiak",
"FEEDS":"Jarioak",
"STATUS_UPDATES":"Egoera-eguneratzeak",
"ONECOMMENT":"Iruzkin bat",
"COMMENTS":"{0} iruzkin",
"ONEPERSON":"Pertsona bat",
"PEOPLE":"{0} pertsona",
"TAGS":"Etiketak:",
"TAGSMORE":"eta {0} gehiago",
"NORESULTSMESSAGE":"Ez da bilaketaren emaitzarik aurkitu",
"JAN":"Urtarrila",
"FEB":"Otsaila",
"MAR":"Martxoa",
"APR":"Apirila",
"MAY":"Maiatza",
"JUN":"Ekaina",
"JUL":"Uztaila",
"AUG":"Abuztua",
"SEP":"Iraila",
"OCT":"Urria",
"NOV":"Azaroa",
"DEC":"Abendua",
"NO_CONTACT":"Bilaketa ez da burutu ezin izan delako zerbitzariarekin harremanetan jarri",
"SERVER_ERROR":"Ez da bilaketa burutu zerbitzariaren errore bat dela eta",
"SORT_BY":"Sailkatu honen arabera:",
"SORT_RELEVANCE":"Garrantzia",
"SORT_DATE":"Data",
"SORT_LAST_UPDATED":"Azken eguneratzea",
"SORT_DUE_DATE":"Epemuga",
"SORT_VISITS":"Bisitak",
"SORT_COMMENTS":"Iruzkinak",
"SORT_RECOMMENDATION":"Atsegiteak",
"SORT_POPULARITY":"Ospea",
"SORT_FIRSTNAME":"Izena",
"SORT_LASTNAME":"Abizena",
"SORT_DOWNLOADS":"Deskargak",
"SORT_TYPE":"Mota",
"SORT_SIZE":"Tamaina",
"SORT_TITLE":"Izenburua",
"PRIVATE":"Pribatua",
"MODERATED":"Moderatua",
"COMMUNITY_ACTIVITY":"Komunitatearen jarduera",
"COMMUNITY_BLOG":"Komunitatearen bloga",
"COMMUNITY_FILE":"Komunitatearen fitxategia",
"COMMUNITY_FORUM":"Komunitatearen foroa",
"COMMUNITY_WIKI":"Komunitatearen wikia",
"COMMUNITY_FEED":"Komunitatearen jarioa",
"COMMUNITY_BOOKMARK":"Komunitatearen laster-markak",
"NO_TAG":"Oraindik ez dago etiketarik",
"NO_DATE":"Oraindik ez dago datarik",
"NO_PEOPLE":"Oraindik ez dago pertsonarik",
"REMOVE_FILTER_LABEL":"Egin klik ezabatzeko",
"REMOVE_FILTER_TITLE":"Kendu",
"REMOVE_FILTER_TOOLTIP":"Kendu iragazki hau",
"COMMENT_ON":"Idatzi iruzkina hemen:",
"EXPAND_COLLAPSE":"Egin klik zabaltzeko / tolesteko",
"EXPAND":"Zabaldu",
"COLLAPSE":"Tolestu",
"EXPAND_MONTHS_FILTER":"Zabaldu {0}. urteko hilabeteen iragazkia",
"SORT_RELEVANCE_LABEL":"Egin klik garrantziaren arabera sailkatzeko",
"SORT_DATE_LABEL":"Egin klik dataren arabera sailkatzeko",
"SORT_UPDATED_LABEL":"Egin klik azken eguneratzearen arabera sailkatzeko",
"SORT_DUE_LABEL":"Egin klik epemugaren arabera sailkatzeko",
"SORT_VISITS_LABEL":"Egin klik bisita kopuruaren arabera sailkatzeko",
"SORT_COMMENTS_LABEL":"Egin klik iruzkin kopuruaren arabera sailkatzeko",
"SORT_RECOMMENDATIONS_LABEL":"Egin klik atsegiteen kopuruaren arabera sailkatzeko",
"SORT_POPULARITY_LABEL":"Egin klik ospearen arabera sailkatzeko",
"SORT_FIRST_NAME_LABEL":"Egin klik emandako izenaren arabera sailkatzeko",
"SORT_LAST_NAME_LABEL":"Egin klik abizenaren arabera sailkatzeko",
"RATING":"Atsegiteak",
"GRADUATED":"Graduatua",
"ONEVOTE":"Boto bat",
"VOTES":"{0} boto",
"BOOKMARK_THIS_RESULT":"Ezarri hau gogoko gisa",
/* {0} is the display name. An example of this is: "Amy Jones2 (inactive)" */
"INACTIVE":"{0} (inaktibo)",
/* only ever more than 1, so 2 people, 3 people etc */
"BOOKMARKERS":"{0} pertsona gogoko gisa ezarrita",
/* eg from an Activity */
"FROMANACTIVITY":"Jarduera batetik",
"FROMABLOG":"Blog batetik",
"FROMANIDEATIONBLOG":"Ideiagintza-blog batetik",
"FROMANEVENT":"Gertaera batetik",
"FROMAFORUM":"Foro batetik",
"FROMAWIKI":"Wiki batetik",
"FROMACOMMUNITY":"Komunitate batetik",
"FROMXCOMMUNITIES":"{0} komunitatetatik",
/* For search results parentage */
"ACTIVITY_ALONE":"Jarduera",
"BLOG_ALONE":"Bloga",
"IDEATIONBLOG_ALONE":"Ideiagintza-bloga",
"ENTRY_ALONE":"Sarrera",
"EVENT_ALONE":"Gertaera",
"FORUM_ALONE":"Foroa",
"WIKI_ALONE":"Wikia",
"COMMUNITY_ALONE":"Komunitatea",
"XCOMMUNITIES_ALONE":"{0} komunitate",
"SHAREDCOMMUNITIES":"Komunitate hauekin partekatua",
"INACOMMUNITY":"Komunitate batean",
"LASTUPDATED":"Bilaketa-indizearen azken eguneratzea:",
"NODESCRIPTION":"Ez dago emaitza honentzako deskribapenik edo laburpenik",
"ATTACHMENT":"Eranskina:",
"ACTIVITY":"Jarduera:",
"ACTIVITYBOOKMARK":"Jardueraren laster-marka:",
"ACTIVITYCOMMENT":"Jardueraren iruzkina:",
"ACTIVITYENTRY":"Jardueraren sarrera:",
"ACTIVITYSECTION":"Jardueraren sekzioa:",
"ACTIVITYTODO":"Jardueraren egitekoa:",
"BLOG":"Bloga:",
"BLOGENTRY":"Blog-sarrera:",
"BLOGCOMMENT":"Blog-iruzkina:",
"BOOKMARK":"Laster-marka:",
"CALENDAREVENT":"Gertaera:",
"CATEGORY":"Kategoria:",
"COMMENT":"Iruzkina:",
"COMMUNITY":"Komunitatea:",
"ENTRY":"Sarrera:",
"EVENTDATEON":"Data: {0}",
"EVENTISALLDAY":"Egun osoko gertaera",
"EVENTREPEATS":"Errepikapenak",
"FEED":"Jarioa:",
"FILE":"Fitxategia:",
"FORUM":"Foroa:",
"FORUMCATEGORY":"Foroaren kategoria:",
"FORUMTOPIC":"Foroaren gaia:",
"IDEA":"Ideia:",
"IDEACOMMENT":"Ideia-iruzkina:",
"IDEATIONBLOG":"Ideiagintza-bloga:",
"PAGE":"Orria:",
"PROFILE":"Profila:",
"SECTION":"Sekzioa:",
"STATUSUPDATE":"Egoera-eguneratzea",
"STATUSUPDATE_PREFIX":"Egoera-eguneratzea:",
"TOPIC":"Gaia:",
"TOPIC_WITH_ATTACHMENT":"Gaia",
"WIKITYPE":"Wikia:",
"WIKIPAGE":"Wiki-orria:",
"WIKIFILE":"Wiki eranskina:",
"SEARCH":"Bilatu:",
"TODO":"Egitekoa:",
"ALLRESULTS":"Emaitza guztiak",
"PUBLICCONTENT":"Eduki publikoa",
"MYCONTENT":"Nire edukia",
"RESULTNOTFOUND":"Ez duzu bila zenbiltzana aurkitu?",
"TEMPDIFFICULTIES":"Oharra: aldi baterako indexatze-arazoak direla eta, zure bilaketak ez ditu azken {1} egunotan aldatutako {0}(a)k barne hartu.",
"TRYLATER":"Saiatu berriro geroago.",
"MULTIPLETEMPDIFFICULTIES":"Oharra: aldi baterako indexatze-arazoak direla eta, zure bilaketak ez ditu duela gutxi aldatutako {0}(a)k barne hartu.",
"YOUAREAUTHOR":"Egilea zara",
"YOUARECONTRIBUTOR":"Kolaboratzailea zara",
"YOUAREOWNER":"Jabea zara",
"YOUAREMEMBER":"Kidea zara",
/* Profiles */
"MYNETWORK":"Nire sarea",
"ALLPEOPLE":"Jende guztia",
"EXCLUDEINACTIVE":"Baztertu jende inaktiboa",
"PHONE":"Telefonoa:",
"EMAIL":"Helbide elektronikoa:",
/* Communities */
"ALLCOMMUNITIES":"Komunitate guztiak",
"PUBLICCOMMUNITIES":"Komunitate publikoak",
"MYCOMMUNITIES":"Nire komunitateak",
"EVERYTHINGCOMMUNITIES":"Komunitateetako guztia",
"COMMUNITIESONLY":"Komunitateak",
"COMMUNITIESCONTENT":"Komunitateetako edukia",
/* Activities */
"ALLACTIVITIES":"Jarduera guztiak",
"PUBLICACTIVITIES":"Jarduera publikoak",
"MYACTIVITIES":"Nire jarduerak",
"EVERYTHINGACTIVITIES":"Jardueretako guztia",
"ACTIVITIESONLY":"Jarduerak",
"SECTIONSACTIVITIES": "Jardueretako sekzioak",
"ENTRIESACTIVITIES":"Jardueretako sarrerak",
"TODOSACTIVITIES":"Jardueretako egitekoak",
"BOOKMARKSACTIVITIES":"Jardueretako laster-markak",
"FILESACTIVITIES":"Jardueretako eranskinak",
"ALLTYPESACTIVITIES":"Jarduera mota guztiak",
"COMMUNITYACTIVITIES":"Komunitateetako jarduerak",
"STANDALONEACTIVITIES":"Jarduera autonomoak",
/* Forums */
"ALLFORUMS":"Foro guztiak",
"PUBLICFORUMS":"Foro publikoak",
"MYFORUMS":"Nire foroak",
"EVERYTHINGFORUMS":"Foroetako guztia",
"FORUMSONLY":"Foroak",
"TOPICSFORUMS":"Foroetako gaiak",
"FORUMCATEGORIES": "Foroetako kategoriak",
"FILESFORUMS":"Foroetako eranskinak",
"ALLTYPESFORUMS":"Foro mota guztiak",
"COMMUNITYFORUMS":"Komunitateetako foroak",
"STANDALONEFORUMS":"Foro autonomoak",
/* Blogs */
"ALLBLOGS":"Blog guztiak",
"PUBLICBLOGS":"Blog publikoak",
"MYBLOGS":"Nire blogak",
"EVERYTHINGBLOGS":"Blogetako guztia",
"BLOGSONLY":"Blogak",
"ENTRIESBLOGS":"Blogetako sarrerak",
"FILESBLOGS":"Blogetako eranskinak",
"EVERYTHINGIDEATIONBLOGS":"Ideiagintza-blogetako guztia",
"BLOGSIDEATIONBLOGS":"Ideiagintza-blogak",
"BLOGSIDEAS":"Ideiak",
"ALLTYPESBLOGS":"Blog mota guztiak",
"COMMUNITYBLOGS":"Komunitateetako blogak",
"COMMUNITYIDEATIONBLOGS":"Komunitateetako ideiagintza-blogak",
"STANDALONEBLOGS":"Blog autonomoak",
/* Bookmarks */
"ALLBOOKMARKS":"Laster-marka guztiak",
"PUBLICBOOKMARKS":"Laster-marka publikoak",
"MYBOOKMARKS":"Nire laster-markak",
"ALLTYPESBOOKMARKS":"Laster-marka mota guztiak",
"COMMUNITYBOOKMARKS":"Komunitateetako laster-markak",
"STANDALONEBOOKMARKS":"Laster-marka autonomoak",
/* Files */
"ALLFILES":"Fitxategi guztiak",
"PUBLICFILES":"Fitxategi publikoak",
"MYFILES":"Nire fitxategiak",
"ALLTYPESFILES":"Fitxategi mota guztiak",
"COMMUNITYFILES":"Komunitateetako fitxategiak",
"STANDALONEFILES":"Fitxategi autonomoak",
"NUMDOWNLOADS":"{0} deskarga",
/* Wikis */
"ALLWIKIS":"Wiki guztiak",
"PUBLICWIKIS":"Wiki publikoak",
"MYWIKIS":"Nire wikiak",
"EVERYTHINGWIKIS":"Wikietako guztia",
"WIKISONLY":"Wikiak",
"PAGESWIKIS":"Wiki-orriak",
"FILESWIKIS":"Wikietako eranskinak",
"ALLTYPESWIKIS":"Wiki mota guztiak",
"COMMUNITYWIKIS":"Komunitateetako wikiak",
"STANDALONEWIKIS":"Wiki autonomoak",
/* Status Updates */
"ALLSTATUSUPDATES":"Egoera-eguneratze guztiak",
"PUBLICSTATUSUPDATES":"Egoera-eguneratze publikoak",
"MYSTATUSUPDATES":"Nire egoera-eguneratzeak",
"ALLTYPESSTATUSUPDATES":"Egoera-eguneratze guztiak",
"COMMUNITYSTATUSUPDATES":"Komunitateetako egoera-eguneratzeak",
"STANDALONESTATUSUPDATES":"Profiletako egoera-eguneratzeak",
/*String for search feedback dialog box*/
"BOOKMARKEDURL":"URL hau hainbat erabiltzailek gorde dute gogoko gisa",
"BOOKMARKEDCOMMUNITY":"Komunitate hau hainbat erabiltzailek gorde dute gogoko gisa",
"BOOKMARKEDPROFILE":"Profil hau hainbat erabiltzailek gorde dute gogoko gisa",
"BOOKMARKEDBLOG":"Blog hau hainbat erabiltzailek gorde dute gogoko gisa",
"COMMUNITYBLOG":"Komunitate bateko bloga da hau",
"BOOKMARKEDACTIVITY":"Jarduera hau hainbat erabiltzailek gorde dute gogoko gisa",
"COMMUNITYACTIVITY":"Komunitate bateko jarduera da hau",
"BOOKMARKEDFILE":"Fitxategi hau hainbat erabiltzailek gorde dute gogoko gisa",
"COMMUNITYFILE":"Komunitate bateko fitxategia da hau",
"BOOKMARKED":"Wiki hau hainbat erabiltzailek gorde dute gogoko gisa",
"COMMUNITYWIKI":"Komunitate bateko wikia da hau",
"BOOKMARKEDFORUM":"Foro hau hainbat erabiltzailek gorde dute gogoko gisa",
"COMMUNITYFORUM":"Komunitate bateko foroa da hau",
"ALLTAGANDTTILE":"URL honen izenburu eta etiketa guztiak ikusteko, sakatu botoi hau",
"TAGS_ARE_FROM":"Bilaketaren emaitza honek hemengo etiketak izan ditzake:",
"BOOKMARKS_TITLE":"Laster-markak",
"COMMUNITIES_TITLE":"Komunitateak",
"ACTIVITIES_TITLE":"Jarduerak",
"HELP":"Laguntza",
"MORESTATUSUPDATES":"Ikusi bat datozen egoera-eguneratze gehiago",
"TITLE_PREFIX":"izenburua:",
"LATEST_MESSAGE":"Azken mezuak",
"LATEST_STATUS_UPDATE":"Azken egoera-eguneratzeak",
"LATEST_COMMUNITY_STATUS_UPDATE":"Komunitatetako egoera-eguneratze berriak",
"LATEST_COMMUNITIES_STATUS_UPDATE":"Komunitateetako egoera-eguneratze berriak",
"SEARCH_RESULTS":"Eduki guztien bilaketaren emaitzak",
"ACTIVITIES_SEARCH_RESULTS":"Jardueretako bilaketaren emaitzak",
"BLOGS_SEARCH_RESULTS":"Blogak ataleko bilaketaren emaitzak",
"BOOKMARKS_SEARCH_RESULTS":"Laster-marketako bilaketaren emaitzak",
"COMMUNITIES_SEARCH_RESULTS":"Komunitateetako bilaketaren emaitzak",
"FILES_SEARCH_RESULTS":"Fitxategietako bilaketaren emaitzak",
"FORUMS_SEARCH_RESULTS":"Foroetako bilaketaren emaitzak",
"PROFILES_SEARCH_RESULTS":"Profiletako bilaketaren emaitzak",
"DIRECTORY_SEARCH_RESULTS":"${orgName} direktorioko bilaketaren emaitzak",
"WIKIS_SEARCH_RESULTS":"Wikietako bilaketaren emaitzak",
"STATUS_UPDATES_SEARCH_RESULTS":"Egoera-eguneratzeetako bilaketaren emaitzak",
"VIEW_ALL":"{span}Ikusi guztiak{/span} ({0})",
"MATCHING_ONE_OF":"Bat datozenak, bat hauetatik:",
"MATCHING_ALL_OF":"Bat datozenak, guztiak hauetatik:",
"MATCHING":"Bat datozenak:",
"MATCHING_DOC_TYPE":"Bat datorren dokumentu mota:",
"BOOKMARK_HELP":"Laster-marka laguntza",
"CLOSE_BOOKMARK_HELP":"Itxi 'Laster-marka laguntza'",
"DOCUMENT_TYPE_PREFIX":"Dokumentu mota:",
"FILE_PREVIEW_ONLY":"(Aurrebista-modua soilik)"
})

