/* Copyright IBM Corp. 2011, 2015  All Rights Reserved.              */

({
   dialogTitle : "Add Image",
   newUpload : "New Upload",
   URL : "URL",
   imageLibrary : "Image Library",
   description : "Description:",
   imageFile : "Files:",
   OK: "OK",
   cancel: "Cancel",
   required: "Required field",
   preview: "Preview:",
   previewWarning: "The image seems to have failed to load, are you sure this is a valid image url?",
   alt: "Alternate text:",
   filesTab: "From Files",
   images:"Images:",
   browse:"Browse...",
   imagePickerTitle:"Insert Images from Files",
   componentImagePickerTitle:" ${0} uploaded images",
   /* New String for insert image dialog */
   title: "Insert Image",
   uploadBtn: "Upload Image",   
   insertBtn: "Insert Image",
   uploadTab: "Local Files",
   externalTab: "Web URL",
   internalTab: "Existing Images",
   fileFieldTip: "Drag and drop images from your desktop directly into this window to upload them.",
   AdditionalSection: "Additional Options",
   ExpandSection: "Expand Additional Options",
   CloseSection: "Collapse Additional Options",
   webURLPrompt: "Web Image URL:",
   previewPrompt: "Preview area: Large images might take awhile to display.",
   noExistingImage: "Oops! No image has been added yet.",
   selectExistingImage: "Select an existing image:",
   urlMissing: "Enter a URL",
   urlInvalid: "Invalid URL. Make sure to enter a valid URL and try again.",
   previousItem: "Previous",
   nextItem: "Next",
   oneImageOneTime: "An image is already added into this Window. You can insert only one image at a time.",
   loadingErrorMsg: "An error occurs when loading existing images. Try again later",
   urlInputTooltip: "Enter the web URL of the image"
})
