/* Copyright IBM Corp. 2009, 2016  All Rights Reserved.              */

// NLS_CHARSET=UTF-8
define({
		"NODE": "Oplysninger for node: ",
		"INSTALLED": "Kontrollerer de installerede services",
		"RESUMETOKENS": "Kontrollerer genoptagelsestokens",
		"SEEDLISTS": "Kontrollerer, at seedlisterne er tilgængelige",
		"CALENDARS": "Kontrollerer, at planlægningskalenderne er konfigureret korrekt",
		"VARIABLES": "Kontrollerer, at WebSphere-variablerne er angivet",
		"TASKS": "Kontrollerer, at indekseringsopgaverne er aktiveret",
		"INDEXFILES": "Kontrollerer indeksfolderen for påkrævede filer",
		"LOGS": "Gennemser logfilerne for fejl",
		"CONFIGFILES": "Gennemser konfigurationsfilerne",
		"DICTIONARIES": "Kontrollerer antallet af ordbøger, der er aktiveret",
		"SYNC": "Kontroller status for noderne",
		"DBRECORDS": "Kontrollerer databaserecords",
		"INSTALLEDMSG": "Følgende service er installeret: ",
		"RESUMETOKENSMSG": "Genoptagelsestokenet for: ",
		"SEEDLISTSMSG": "Seedlisten kunne ikke hentes for: ",
		"CALENDARSMSG": "Kontrollen af planlægningskalenderen er udført: ",
		"VARIABLESMSG": "Variabel: ",
		"TASKSMSG": "Følgende opgave er forkert aktiveret: ",
		"INDEXFILESMSG" : "Følgende filer findes i søgeindeksfolderen: ",
		"LOGSMSG" : "Gennemse følgende fejlmeddelelse: ",
		"CONFIGFILESMSG" : "Følgende konfigurationsfiler er fundet: ",
		"DICTIONARIESMSG" : "Antallet af aktiverede ordbøger er: ",
		"INSYNC": "Alle noder er synkroniseret",
		"OUTOFSYNC": "Antallet af ikke-synkroniserede noder er: ",
		"NOTBLOCKED": "Ingen noder er blokeret",
		"BLOCKED": "Antallet af blokerede noder er: ",
		"INDATE": "Alle noder er opdateret",
		"OUTOFDATE": "Antallet af forældede noder er: ",
		"NUMOFDOCS": "Antallet af dokumenter i databasen er: ",
		"FILESTOCONVERT": "Antallet af fildokumenter, der skal konverteres, er: ",
		"CONVERTEDFILES": "Antallet af konverterede filer er: ",
		"TOTALFILES": "Det samlede antal filer i databasen ",
		"ERROR":"Fejl",
		"ERROR_PREFIX":"Fejl:",
		"INFO":"Information",
		"INFO_PREFIX":"Information:",
		"WARNING":"Advarsel",
		"WARNING_PREFIX":"Advarsel:",
		"LOADING_MESSAGE": "Indlæser",
		"SERVER_STATUS": "Serverstatus",
		"INITIAL_INDEXING_EXCEPTIONS": "Undtagelser ved startindeksering",
		"SYS_OUT_EXCEPTIONS": "Undtagelser i SystemOut-log",
		"SEEDLIST_VALIDATE": "Validering af seedlister",
		"ERRORS_DURING_INITIAL_INDEXING":"Der er opstået følgende undtagelser under oprettelse af et startindeks",
		"CRAWL_FAILED": "Det var ikke muligt at gennemsøge alle data for følgende serviceprogram: ",
		"EXCEPTION_ENCOUNTERED": "Gennemsøgningen blev ikke udført korrekt. Der er følgende meddelelse: ",
		"SAND_VALIDATE": "SAND-validering",
		"CHECK_FOR_SAND_FILES":"Kontrollerer SAND-filerne",
		"IS_FILE_AVAILABLE":"Kontrollerer, at filen er oprettet: ",
		"ERRORS_DURING_INITIAL_INDEXING":"Der er opstået følgende undtagelser under oprettelse af et startindeks",
		"CRAWL_FAILED":"Det var ikke muligt at gennemsøge alle data for følgende serviceprogram: ",
		"EXCEPTION_ENCOUNTERED":"Gennemsøgningen blev ikke udført korrekt. Der er følgende meddelelse: "
});

